<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/TerminoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/TerminoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:terMO="http://www.bcie.org/TerminoMO" 
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/TerminoMO" schemaLocation="../../Schema/TerminoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>  
  <wsdl:message name="ConsultarTerminoRequestMessage">
    <wsdl:part name="request" element="terMO:ConsultarTerminoRequest"/>
  </wsdl:message>
  <wsdl:message name="ConsultarTerminoResponseMessage">
    <wsdl:part name="response" element="terMO:ConsultarTerminoResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarTerminoPT">
    <wsdl:operation name="consultarTermino">
      <wsdl:input message="tns:ConsultarTerminoRequestMessage"/>
      <wsdl:output message="tns:ConsultarTerminoResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarTermino12Bnd" type="tns:ConsultarTerminoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarTermino">
      <soap12:operation style="document" soapAction="http://www.bcie.org/TerminoService/consultarTermino"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>