<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/TerminoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/TerminoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:terMO="http://www.bcie.org/TerminoMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/TerminoMO" schemaLocation="../../Schema/TerminoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CrearTerminoRequestMessage">
    <wsdl:part name="request" element="terMO:CrearTerminoRequest"/>
  </wsdl:message>
  <wsdl:message name="CrearTerminoResponseMessage">
    <wsdl:part name="response" element="terMO:CrearTerminoResponse"/>
  </wsdl:message>
  <wsdl:portType name="TerminoPT">
    <wsdl:operation name="crearTermino">
      <wsdl:input message="tns:CrearTerminoRequestMessage"/>
      <wsdl:output message="tns:CrearTerminoResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Termino12Bnd" type="tns:TerminoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearTermino">
      <soap12:operation style="document" soapAction="http://www.bcie.org/TerminoService/crearTermino"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>