<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ServiceBusApplication/UploadInvoiceEdiAPP/UploadInvoiceJmsReference" name="UploadInvoiceJmsReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UploadInvoiceJmsReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ServiceBusApplication/UploadInvoiceEdiAPP/UploadInvoiceJmsReference"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="upl:Produce_Message_ptt" xmlns:upl="http://xmlns.oracle.com/pcbpel/adapter/jms/ServiceBusApplication/UploadInvoiceEdiAPP/UploadInvoiceJmsReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>