<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Cliente/ActualizarClientes/ActualiizarClientes" name="ActualiizarCliente_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ActualiizarClientes.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Cliente/ActualizarClientes/ActualiizarClientes"/>
    <wsdl:binding name="ActualiizarClientes_ptt-binding" type="act:ActualiizarClientes_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/Cliente/ActualizarClientes/ActualiizarClientes">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="update">
            <soap:operation soapAction="update"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>