<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"
                xmlns:ns0="http://www.bcie.org/ConfiguracionProcesosMO"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="http://www.bcie.org/ProductoBO" xmlns:confBO="http://www.bcie.org/ConfiguracionProcesosBO"
                xmlns:ns3="http://www.bcie.org/DeclaracionJuradaBO" xmlns:operBO="http://www.bcie.org/OperacionBO"
                xmlns:resBO="http://www.bcie.org/ResultBO" xmlns:ns2="http://www.bcie.org/CatalogoBO"
                xmlns:ns4="http://www.bcie.org/ClienteBO" xmlns:ns5="http://www.bcie.org/ErrorBO"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:ns6="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns7="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/Schema/ConfiguracionProcesosMO.xsd"/>
        <oracle-xsl-mapper:rootElement name="configuracionEvaluacionResponse"
                                       namespace="http://www.bcie.org/ConfiguracionProcesosMO"/>
        <oracle-xsl-mapper:param name="configuracionEvaluacionResponse"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/Evaluacion/V1/EvaluacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="EvaluacionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [THU DEC 10 12:28:33 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:EvaluacionPayload>
      <tns:Header>
        <header:Operacion>
          <ns6:CodigoOperacion>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:idOperacion"/>
          </ns6:CodigoOperacion>
          <ns6:NombreOperacion>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:nombre"/>
          </ns6:NombreOperacion>
          <ns6:ResponsableOperacion>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:responsable"/>
          </ns6:ResponsableOperacion>
          <ns6:CodigoCliente>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:cliente/ns4:idCliente"/>
          </ns6:CodigoCliente>
          <ns6:NombreCliente>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:cliente/ns4:razonSocial"/>
          </ns6:NombreCliente>
          <ns6:CodigoProducto>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:producto/ns1:idProducto"/>
          </ns6:CodigoProducto>
          <ns6:NombreProducto>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:producto/ns1:descripcion"/>
          </ns6:NombreProducto>
          <xsl:for-each select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:montoOperacion/operBO:montoOperacion">
            <xsl:if test="operBO:id=2">
              <ns6:MontoSolicitado>
                <xsl:value-of select="operBO:monto"/>
              </ns6:MontoSolicitado>
            </xsl:if>
          </xsl:for-each>
          <ns6:Pais>
            <xsl:value-of select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:operacion/operBO:cliente/ns4:pais/ns2:Descripcion"/>
          </ns6:Pais>
        </header:Operacion>
        <parameter:ParameterType>
          <parameter:parameterName/>
          <parameter:parameterValue/>
        </parameter:ParameterType>
      </tns:Header>
      <tns:Configuration>
        <tns:requiereSIEMAS>true</tns:requiereSIEMAS>
        <tns:requiereIBCIE>true</tns:requiereIBCIE>
      </tns:Configuration>
      <xsl:for-each select="/ns0:configuracionEvaluacionResponse/ns0:configuracionEvaluacion/confBO:RolesEquipoTrabajo/confBO:Rol">
        <tns:EquipoPayload>
          <xsl:if test="ns2:Id=14">
            <tns:AnalistaAED>
              <xsl:value-of select="ns2:DescripcionCorta"/>
            </tns:AnalistaAED>
          </xsl:if>
        </tns:EquipoPayload>
      </xsl:for-each>
    </tns:EvaluacionPayload>
  </xsl:template>
</xsl:stylesheet>
