<wsdl:definitions name="ActualizarPreguntas" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarPreguntas" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarPreguntas" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarPreguntas" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarPreguntas_plt">
    <plt:role name="ActualizarPreguntas_role">
      <plt:portType name="tns:ActualizarPreguntas_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarPreguntas" schemaLocation="../XSD/ActualizarPreguntas_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="PreguntaCollection_msg">
        <wsdl:part name="PreguntaCollection" element="top:PreguntaCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarPreguntas_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:PreguntaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>