<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://tempuri.org/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.banesco.com/eopt/AcctStmtImgInq_V1.0" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0" xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:eoCom="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../../Commons/backends/ESCTA/resources/wsdl/EstadoCuentaElectronicoSoap12Mock.wsdl"/>
            <oracle-xsl-mapper:rootElement name="sConsultarEstadoCuentaResponse" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/AcctStmtImgInq/AcctStmtImgInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctStmtImgInqRs" namespace="http://xmlns.banesco.com/eopt/AcctStmtImgInq_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED AUG 17 15:16:03 COT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <xsl:choose>
         <xsl:when test="string-length (/ns0:sConsultarEstadoCuentaResponse/ns0:sConsultarEstadoCuentaResult ) > 0">
            <tns:AcctStmtImgInqRs>
               <tns:Status>
                  <eoStatus:StatusCode>
                     <xsl:value-of select="&quot;M0000&quot;"/>
                  </eoStatus:StatusCode>
                  <eoStatus:StatusDesc>
                     <xsl:value-of select="DVMFunctions:lookupValue (&quot;Commons/dvm/ServiceProperties&quot;, &quot;CODE&quot;, &quot;M0000&quot;, &quot;VALUE&quot;, &quot;CouldNotBeFound&quot; )"/>
                  </eoStatus:StatusDesc>
               </tns:Status>
               <tns:Binary>
                  <eoCom:ImageURL>
                     <xsl:value-of select="/ns0:sConsultarEstadoCuentaResponse/ns0:sConsultarEstadoCuentaResult"/>
                  </eoCom:ImageURL>
               </tns:Binary>
            </tns:AcctStmtImgInqRs>
         </xsl:when>
         <xsl:otherwise>
            <tns:AcctStmtImgInqRs>
               <tns:Status>
                  <eoStatus:StatusCode>
                     <xsl:value-of select="&quot;M0002&quot;"/>
                  </eoStatus:StatusCode>
                  <eoStatus:StatusDesc>
                     <xsl:value-of select="DVMFunctions:lookupValue (&quot;Commons/dvm/ServiceProperties&quot;, &quot;CODE&quot;, &quot;M0002&quot;, &quot;VALUE&quot;, &quot;CouldNotBeFound&quot; )"/>
                  </eoStatus:StatusDesc>
               </tns:Status>
            </tns:AcctStmtImgInqRs>
         </xsl:otherwise>
      </xsl:choose>
   </xsl:template>
</xsl:stylesheet>