<wsdl:definitions name="ActualizarTBILineaCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/ActualizarTBILineaCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/ActualizarTBILineaCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarTBILineaCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarTBILineaCredito_plt">
    <plt:role name="ActualizarTBILineaCredito_role">
      <plt:portType name="tns:ActualizarTBILineaCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarTBILineaCredito" schemaLocation="../XSD/TBILineaCredito.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="TbiLineaCreditoCollection_msg">
        <wsdl:part name="TbiLineaCreditoCollection" element="top:TbiLineaCreditoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarTBILineaCredito_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:TbiLineaCreditoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>