<wsdl:definitions name="ConsultarReglas_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarReglas_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarReglas_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarReglas_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarReglas_DB_plt">
    <plt:role name="ConsultarReglas_DB_role">
      <plt:portType name="tns:ConsultarReglas_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarReglas_DB" schemaLocation="../XSD/ConsultarReglas_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarReglas_DBInput_msg">
        <wsdl:part name="ConsultarReglas_DBInput_msg" element="db:ConsultarReglas_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarReglas_DBOutputCollection_msg">
        <wsdl:part name="ConsultarReglas_DBOutputCollection" element="db:ConsultarReglas_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarReglas_DB_ptt">
        <wsdl:operation name="ConsultarReglas_DB">
            <wsdl:input message="tns:ConsultarReglas_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarReglas_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>