<?xml version='1.0' encoding='UTF-8'?>
<WL5G3N0:definitions xmlns="" name="GARANTIAS" targetNamespace="http://org/bcie/ws/middle/GARANTIAS.wsdl" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.w3.org/2001/XMLSchema" xmlns:WL5G3N2="http://org/bcie/ws/middle/GARANTIAS.wsdl" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types/>
  <WL5G3N0:message name="GARANTIAS_consultacobertura">
    <WL5G3N0:part name="numerolineacredito" type="WL5G3N1:string"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="GARANTIAS_consultacoberturaResponse">
    <WL5G3N0:part name="porcentajeexigido_out" type="WL5G3N1:decimal"/>
    <WL5G3N0:part name="monto_out" type="WL5G3N1:decimal"/>
    <WL5G3N0:part name="codigoresultado_out" type="WL5G3N1:decimal"/>
    <WL5G3N0:part name="tiporesultado_out" type="WL5G3N1:decimal"/>
    <WL5G3N0:part name="mensajeerror_out" type="WL5G3N1:string"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="GARANTIAS">
    <WL5G3N0:operation name="consultacobertura" parameterOrder="numerolineacredito porcentajeexigido_out monto_out codigoresultado_out tiporesultado_out mensajeerror_out">
      <WL5G3N0:input message="WL5G3N2:GARANTIAS_consultacobertura"/>
      <WL5G3N0:output message="WL5G3N2:GARANTIAS_consultacoberturaResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="GARANTIAS" type="WL5G3N2:GARANTIAS">
    <WL5G3N3:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <WL5G3N0:operation name="consultacobertura">
      <WL5G3N3:operation soapAction="http://org/bcie/ws/middle/GARANTIAS.wsdl/consultacobertura"/>
      <WL5G3N0:input>
        <WL5G3N3:body use="literal" namespace="http://org/bcie/ws/middle/GARANTIAS.wsdl" parts="numerolineacredito"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body use="literal" namespace="http://org/bcie/ws/middle/GARANTIAS.wsdl" parts="porcentajeexigido_out monto_out codigoresultado_out tiporesultado_out mensajeerror_out"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="GARANTIAS">
    <WL5G3N0:port name="GARANTIAS" binding="WL5G3N2:GARANTIAS">
      <WL5G3N3:address location="http://hn-obpm-qa.bcie.org:7065/MIDDLE/GARANTIAS"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>