<wsdl:definitions
     name="ConsultarProductoByIdOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/ConsultarProductoByIdOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/ConsultarProductoByIdOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarProductoByIdOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarProductoByIdOperacion_plt" >
    <plt:role name="ConsultarProductoByIdOperacion_role" >
      <plt:portType name="tns:ConsultarProductoByIdOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarProductoByIdOperacion" schemaLocation="../XSD/ConsultarProductoByIdOperacion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarProductoByIdOperacionInput_msg">
        <wsdl:part name="ConsultarProductoByIdOperacionInput_msg" element="db:ConsultarProductoByIdOperacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarProductoByIdOperacionOutputCollection_msg">
        <wsdl:part name="ConsultarProductoByIdOperacionOutputCollection" element="db:ConsultarProductoByIdOperacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarProductoByIdOperacion_ptt">
        <wsdl:operation name="ConsultarProductoByIdOperacion">
            <wsdl:input message="tns:ConsultarProductoByIdOperacionInput_msg"/>
            <wsdl:output message="tns:ConsultarProductoByIdOperacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
