<wsdl:definitions name="ConsultarContratoByIntanciaProceso" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContratoByIntanciaProceso" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContratoByIntanciaProceso" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarContratoByIntanciaProceso" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarContratoByIntanciaProceso_plt">
    <plt:role name="ConsultarContratoByIntanciaProceso_role">
      <plt:portType name="tns:ConsultarContratoByIntanciaProceso_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarContratoByIntanciaProceso" schemaLocation="../XSD/ConsultarContratoByIntanciaProceso_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContratoByIntanciaProcesoSelect_inputParameters">
        <wsdl:part name="ConsultarContratoByIntanciaProcesoSelect_inputParameters" element="top:ConsultarContratoByIntanciaProcesoSelect_instanciaProcesoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ContratoCollection_msg">
        <wsdl:part name="ContratoCollection" element="top:ContratoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContratoByIntanciaProceso_ptt">
        <wsdl:operation name="ConsultarContratoByIntanciaProcesoSelect">
            <wsdl:input message="tns:ConsultarContratoByIntanciaProcesoSelect_inputParameters"/>
            <wsdl:output message="tns:ContratoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>