<wsdl:definitions name="ConsultarSolicitudAprobacionById" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarSolicitudAprobacionById" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarSolicitudAprobacionById" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSolicitudAprobacionById" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarSolicitudAprobacionById_plt">
    <plt:role name="ConsultarSolicitudAprobacionById_role">
      <plt:portType name="tns:ConsultarSolicitudAprobacionById_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSolicitudAprobacionById" schemaLocation="../XSD/ConsultarSolicitudAprobacionById.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarSolicitudAprobacionByIdInput_msg">
        <wsdl:part name="ConsultarSolicitudAprobacionByIdInput_msg" element="db:ConsultarSolicitudAprobacionByIdInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarSolicitudAprobacionByIdOutputCollection_msg">
        <wsdl:part name="ConsultarSolicitudAprobacionByIdOutputCollection" element="db:ConsultarSolicitudAprobacionByIdOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarSolicitudAprobacionById_ptt">
        <wsdl:operation name="ConsultarSolicitudAprobacionById">
            <wsdl:input message="tns:ConsultarSolicitudAprobacionByIdInput_msg"/>
            <wsdl:output message="tns:ConsultarSolicitudAprobacionByIdOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>