<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project15/ValidarProcesoAprobacionFinalizado" name="ValidarProcesoAprobacionFinalizado_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ValidarProcesoAprobacionFinalizado.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project15/ValidarProcesoAprobacionFinalizado"/>
    <wsdl:binding name="ValidarProcesoAprobacionFinalizado_ptt-binding" type="val:ValidarProcesoAprobacionFinalizado_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project15/ValidarProcesoAprobacionFinalizado">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ValidarProcesoAprobacionFinalizado">
            <soap:operation soapAction="ValidarProcesoAprobacionFinalizado"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>