<wsdl:definitions
     name="ConsultarLineaCredito"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project13/ConsultarLineaCredito"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project13/ConsultarLineaCredito"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLineaCredito"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarLineaCredito_plt" >
    <plt:role name="ConsultarLineaCredito_role" >
      <plt:portType name="tns:ConsultarLineaCredito_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLineaCredito" schemaLocation="../XSD/ConsultarLineaCredito.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarLineaCreditoInput_msg">
        <wsdl:part name="ConsultarLineaCreditoInput_msg" element="db:ConsultarLineaCreditoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarLineaCreditoOutputCollection_msg">
        <wsdl:part name="ConsultarLineaCreditoOutputCollection" element="db:ConsultarLineaCreditoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarLineaCredito_ptt">
        <wsdl:operation name="ConsultarLineaCredito">
            <wsdl:input message="tns:ConsultarLineaCreditoInput_msg"/>
            <wsdl:output message="tns:ConsultarLineaCreditoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
