<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="LeccionesAprendidasProcess"
     targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/LeccionesAprendidasProcess"
     xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/LeccionesAprendidasProcess"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:inp1="http://xmlns.oracle.com/bpmn/bpmnProcess/LeccionesAprendidasProcess"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/LeccionesAprendidasProcess"
                 schemaLocation="../../Schema/PA17/LeccionesAprendidasProcess.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="InicioLeccionesAprendidas">
        <wsdl:part name="parameters" element="tns:InicioLeccionesAprendidas"/>
    </wsdl:message>
    <wsdl:message name="FinLeccionesAprendidas">
        <wsdl:part name="parameters" element="tns:FinLeccionesAprendidas"/>
    </wsdl:message>
    <wsdl:portType name="LeccionesAprendidasProcessPortType">
        <wsdl:operation name="InicioLeccionesAprendidas">
            <wsdl:input message="tns:InicioLeccionesAprendidas"/>
        </wsdl:operation>
        <wsdl:operation name="FinLeccionesAprendidas">
            <wsdl:input message="tns:FinLeccionesAprendidas"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="LeccionesAprendidasProcessBinding" type="tns:LeccionesAprendidasProcessPortType">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="InicioLeccionesAprendidas">
            <soap12:operation style="document" soapAction="InicioLeccionesAprendidas"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="FinLeccionesAprendidas">
            <soap12:operation style="document" soapAction="FinLeccionesAprendidas"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <plnk:partnerLinkType name="LeccionesAprendidasProcessPortTypePartnerLinkType">
      <plnk:role name="LeccionesAprendidasProcessPortTypeProvider">
        <plnk:portType name="tns:LeccionesAprendidasProcessPortType"/>
      </plnk:role>
    </plnk:partnerLinkType>
</wsdl:definitions>
