<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.banesco.com/eopt/AcctTrnAddAdvInq_V1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://www.temenos.com/T24/ofs/Response" xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon" xmlns:ns1="http://www.temenos.com/T24/ofs/BANENQ345FTAMLType" xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/WSBANENQ345FTAML/CONSULTATrama345FTResponse.xsd"/>
            <oracle-xsl-mapper:rootElement name="BANENQ345FTAMLResponse" namespace="http://www.temenos.com/T24/ofs/Response"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/AcctTrnAddAdvInq/AcctTrnAddAdvInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctTrnAddAdvFTInqRs" namespace="http://xmlns.banesco.com/eopt/AcctTrnAddAdvInq_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON SEP 24 08:24:45 GMT-05:00 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:variable name="statusCode" select="DVMFunctions:lookupValue (&quot;Commons/dvm/StatusMappingBcknd&quot;, &quot;T24&quot;, /ns0:BANENQ345FTAMLResponse/ResponseCommon/Status, &quot;CNCODE&quot;, &quot;M0006&quot; )"/>
   <xsl:template match="/">
      <tns:AcctTrnAddAdvFTInqRs>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/EstatusdeCuentaoProducto/text()">
            <tns:AcctStatus>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/EstatusdeCuentaoProducto"/>
            </tns:AcctStatus>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SaldoDisponible/text()">
            <tns:AvailAmt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SaldoDisponible"/>
            </tns:AvailAmt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SignoValor/text()">
            <tns:AvailAmtSign>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SignoValor"/>
            </tns:AvailAmtSign>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/BancoDestino/text()">
            <tns:BankDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/BancoDestino"/>
            </tns:BankDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ReferenciadePagodeServicio1/text()">
            <tns:BillerId>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ReferenciadePagodeServicio1"/>
            </tns:BillerId>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/RegionSucursal/text()">
            <tns:BranchRegion>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/RegionSucursal"/>
            </tns:BranchRegion>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoEfectivo/text()">
            <tns:CashAmt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoEfectivo"/>
            </tns:CashAmt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CanaloMedio/text()">
            <tns:Channel>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CanaloMedio"/>
            </tns:Channel>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumeroFinChequera/text()">
            <tns:ChkBookFinalNum>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumeroFinChequera"/>
            </tns:ChkBookFinalNum>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumeroInicialChequera/text()">
            <tns:ChkBookInitialNum>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumeroInicialChequera"/>
            </tns:ChkBookInitialNum>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipodeChequera/text()">
            <tns:ChkBookType>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipodeChequera"/>
            </tns:ChkBookType>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeDocumentoCheque/text()">
            <tns:ChkNumber>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeDocumentoCheque"/>
            </tns:ChkNumber>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoChequeAjeno/text()">
            <tns:ChkOtherAmt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoChequeAjeno"/>
            </tns:ChkOtherAmt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoChequePropio/text()">
            <tns:ChkPropAmt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoChequePropio"/>
            </tns:ChkPropAmt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechaCompensacion/text()">
            <tns:CompensationDt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechaCompensacion"/>
            </tns:CompensationDt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodClienteRIMDestino/text()">
            <tns:CustomerIdDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodClienteRIMDestino"/>
            </tns:CustomerIdDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodClienteRIMOrigen/text()">
            <tns:CustomerIdOr>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodClienteRIMOrigen"/>
            </tns:CustomerIdOr>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NombreClienteTitularCtaDestino/text()">
            <tns:CustomerNameDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NombreClienteTitularCtaDestino"/>
            </tns:CustomerNameDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NombreClienteTitularCtaOrigen/text()">
            <tns:CustomerNameOr>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NombreClienteTitularCtaOrigen"/>
            </tns:CustomerNameOr>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechaVinculacionCliente/text()">
            <tns:CustomerSince>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechaVinculacionCliente"/>
            </tns:CustomerSince>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/DebitoCreditouOtras/text()">
            <tns:DebitCredit>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/DebitoCreditouOtras"/>
            </tns:DebitCredit>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CorreoElectronicoEmail/text()">
            <tns:Email>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CorreoElectronicoEmail"/>
            </tns:Email>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FlagEmpleadoCtaDestino/text()">
            <tns:EmployeeAcctDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FlagEmpleadoCtaDestino"/>
            </tns:EmployeeAcctDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FlagEmpleadoCtaOrigen/text()">
            <tns:EmployeeAcctOr>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FlagEmpleadoCtaOrigen"/>
            </tns:EmployeeAcctOr>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IDdeEmpleadoRUTNITRFC/text()">
            <tns:EmployeeId>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IDdeEmpleadoRUTNITRFC"/>
            </tns:EmployeeId>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigodeEntidadCompania/text()">
            <tns:EntityCode>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigodeEntidadCompania"/>
            </tns:EntityCode>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FlagTipodeCuentaVIP/text()">
            <tns:FlagVip>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FlagTipodeCuentaVIP"/>
            </tns:FlagVip>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Telefono1Residencia/text()">
            <tns:HousePhone>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Telefono1Residencia"/>
            </tns:HousePhone>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Fechaultimomovimientodelacuent/text()">
            <tns:LastMovDt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Fechaultimomovimientodelacuent"/>
            </tns:LastMovDt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipoMensaje/text()">
            <tns:MessageType>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipoMensaje"/>
            </tns:MessageType>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Telefono2Oficina/text()">
            <tns:OfficePhone>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Telefono2Oficina"/>
            </tns:OfficePhone>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechadeaperturaCUenta/text()">
            <tns:OpenAcctDate>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechadeaperturaCUenta"/>
            </tns:OpenAcctDate>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SucursalAperturaCuentaDestino/text()">
            <tns:OpenBranchDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SucursalAperturaCuentaDestino"/>
            </tns:OpenBranchDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SucursalAperturaCuentaOrigen/text()">
            <tns:OpenBranchOr>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SucursalAperturaCuentaOrigen"/>
            </tns:OpenBranchOr>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Telefono3Otro/text()">
            <tns:OtherPhone>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Telefono3Otro"/>
            </tns:OtherPhone>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoSobregiroAutorizado/text()">
            <tns:OverdueAmt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoSobregiroAutorizado"/>
            </tns:OverdueAmt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IndicadordeSobregiro/text()">
            <tns:OverdueIndicator>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IndicadordeSobregiro"/>
            </tns:OverdueIndicator>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/DireccionDomicilio/text()">
            <tns:PersonAddr>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/DireccionDomicilio"/>
            </tns:PersonAddr>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IddeClienteRFC/text()">
            <tns:PersonalId>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IddeClienteRFC"/>
            </tns:PersonalId>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IDdeClienteDestino/text()">
            <tns:PersonalIdDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/IDdeClienteDestino"/>
            </tns:PersonalIdDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipoPersona/text()">
            <tns:PersonType>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipoPersona"/>
            </tns:PersonType>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipodeProductoDestino/text()">
            <tns:ProdTypeDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipodeProductoDestino"/>
            </tns:ProdTypeDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigodeProducto/text()">
            <tns:ProductCode>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigodeProducto"/>
            </tns:ProductCode>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Reverso/text()">
            <tns:RecordStatus>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/Reverso"/>
            </tns:RecordStatus>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigoRespuesta/text()">
            <tns:ResponseCode>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigoRespuesta"/>
            </tns:ResponseCode>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SegmentodelCliente/text()">
            <tns:Segment>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/SegmentodelCliente"/>
            </tns:Segment>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ReferenciaPagodeServicio3/text()">
            <tns:SerProvId>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ReferenciaPagodeServicio3"/>
            </tns:SerProvId>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ReferenciadePagodeServicio2/text()">
            <tns:ServName>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ReferenciadePagodeServicio2"/>
            </tns:ServName>
         </xsl:if>
         <tns:Status>
           <eoStatus:StatusCode>
                   <xsl:value-of select="$statusCode"/>
               </eoStatus:StatusCode>
               <eoStatus:StatusDesc>
               <xsl:value-of select="DVMFunctions:lookupValue (&quot;Commons/dvm/StatusMappingBcknd&quot;, &quot;T24&quot;, /ns0:BANENQ345FTAMLResponse/ResponseCommon/Status, &quot;CNDESC&quot;, &quot;FALLO EN LA OPERACION&quot; )"/>
               </eoStatus:StatusDesc>
            <eoStatus:AdditionalStatus>
               <xsl:if test="/ns0:BANENQ345FTAMLResponse/ResponseCommon/Status/text()">
                  <eoStatus:StatusCode>
                     <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/ResponseCommon/Status"/>
                  </eoStatus:StatusCode>
               </xsl:if>
               <xsl:if test="/ns0:BANENQ345FTAMLResponse/ResponseCommon/Message/text()">
                  <eoStatus:StatusDesc>
                     <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/ResponseCommon/Message"/>
                  </eoStatus:StatusDesc>
               </xsl:if>
            </eoStatus:AdditionalStatus>
         </tns:Status>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigoSubproducto/text()">
            <tns:SubProdCode>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/CodigoSubproducto"/>
            </tns:SubProdCode>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipopagodeServicio/text()">
            <tns:SvcPaymentType>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipopagodeServicio"/>
            </tns:SvcPaymentType>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ClaveTrasnferInterbancaria/text()">
            <tns:TransferKey>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/ClaveTrasnferInterbancaria"/>
            </tns:TransferKey>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeCuentaDestino/text()">
            <tns:TxnAccountDes>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeCuentaDestino"/>
            </tns:TxnAccountDes>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeCuentaOrigen/text()">
            <tns:TxnAccountOr>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeCuentaOrigen"/>
            </tns:TxnAccountOr>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/OficinaReceptoradeTransferencia/text()">
            <tns:TxnBranch>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/OficinaReceptoradeTransferencia"/>
            </tns:TxnBranch>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MonedaTrx/text()">
            <tns:TxnCurrency>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MonedaTrx"/>
            </tns:TxnCurrency>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechaTrx/text()">
            <tns:TxnDate>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/FechaTrx"/>
            </tns:TxnDate>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeReferencia/text()">
            <tns:TxnRef>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/NumerodeReferencia"/>
            </tns:TxnRef>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/HoraTrx/text()">
            <tns:TxnTime>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/HoraTrx"/>
            </tns:TxnTime>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoTotalTrx/text()">
            <tns:TxnTotalAmt>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/MontoTotalTrx"/>
            </tns:TxnTotalAmt>
         </xsl:if>
         <xsl:if test="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipoUsuario/text()">
            <tns:UserType>
               <xsl:value-of select="/ns0:BANENQ345FTAMLResponse/BANENQ345FTAML/gBANENQ345FTAMLDetailType/mBANENQ345FTAMLDetailType/TipoUsuario"/>
            </tns:UserType>
         </xsl:if>
      </tns:AcctTrnAddAdvFTInqRs>
   </xsl:template>
</xsl:stylesheet>