<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="DistributePriceChangeProcess" targetNamespace="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess" xmlns:ns1="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeDistributeProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://msoffice.utils.ea.agarcia.mx/" xmlns:ns3="http://mx.agarcia.ea/Applications/JDA/PriceChange/ProcessMicroTask">
   <plnk:partnerLinkType name="DistributePriceChangeProcess">
      <plnk:role name="DistributePriceChangeProcessProvider" portType="client:DistributePriceChangeProcess"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Applications/JDA/PriceChange/ProcessMicroTask" location="http://uat-osb.agarcia.com.mx:7004/Applications/JDA/JDAPriceChange/PS/JDAAPIPriceChangeSvc?WSDL"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess" xmlns:ns1="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeDistributeProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://msoffice.utils.ea.agarcia.mx/">
         <import namespace="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess" schemaLocation="../Schemas/DistributePriceChangeProcess.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess" xmlns:ns1="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeDistributeProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://msoffice.utils.ea.agarcia.mx/">
         <import namespace="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeDistributeProcess" schemaLocation="../Schemas/PriceChangeDistributeSchema.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess" xmlns:ns1="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeDistributeProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://msoffice.utils.ea.agarcia.mx/">
         <xsd:import namespace="http://msoffice.utils.ea.agarcia.mx/" schemaLocation="http://172.16.19.26:7004/Applications/Commons/MSOfficeUtil/PS/ExcelGeneratorUtilPXY/v1.0?SCHEMA%2FApplications%2FCommons%2FMSOfficeUtil%2FSchema%2FExcelGeneratorUtilSchema"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="DistributePriceChangeProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:DistributePriceChangeRequest"/>
   </wsdl:message>
   <wsdl:message name="DistributePriceChangeProcessResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="DistributePriceChangeProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:DistributePriceChangeProcessRequestMessage"/>
         <wsdl:output message="client:DistributePriceChangeProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="DistributePriceChangeProcessBinding" type="client:DistributePriceChangeProcess">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="process">
         <soap:operation style="document" soapAction="http://xmlns.oracle.com/PriceChangeProcessBackup/DistributePriceChange/DistributePriceChangeProcess/process"/>
         <wsdl:input>
            <soap:body use="literal" parts="payload"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" parts="payload"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
