/* Formatted on 08/08/2017 05:34:13 p.m. (QP5 v5.136.908.31019) */
SELECT CLI.ID_FLEXCUBE AS BHQ_CLIENTE,
       CLI.RAZON_SOCIAL AS NOMBRE_CLIENTE,
       CLI.TIPO_PERSONA AS ID_TIPO_PERSONA,  
           CATPER.DESCRIPCION AS TIPO_PERSONA,                
       CLI.TIPO_INSTITUCION AS ID_TIPO_INSTITUCION,
       CLI.OFICINA AS ID_OFICINA,
       CATP.DESCRIPCION AS PAIS_OPERACION,
       CATP.COD_EXTERNO AS PAIS_CODIGO_EXTERNO,
       CSIN.DESCRIPCION AS SECTOR_INSTITUCIONAL,
       CTT.DESCRIPCION AS TIPO_INSTITUCION,
       CTC.DESCRIPCION_CORTA AS TIPO_CLIENTE,
       CATOFI.DESCRIPCION AS OFICINA,
       CLI.SECTOR,
       SECR.ID_TCA_SCR,
       TCSCR.DESCRIPCION DESCRIPCION_SCR,
       TESSCR.DESCRIPCION  ESTADO_SCR
  FROM CLIENTES CLI
         INNER JOIN  SEGUIMIENTO_CREDITICIO SECR
         ON SECR.ID_CLIENTE=CLI.ID_CLIENTE
         LEFT JOIN TCA_SCR TCSCR
         ON SECR.ID_TCA_SCR =TCSCR.ID
         INNER JOIN  TCA_ESTADO_SCR TESSCR
         ON TESSCR.ID=SECR.ID_TCA_ESTADO_SCR
       INNER JOIN FENIX.CAT_PAISES CATP                        --PAIS CODIGO--
          ON CATP.ID = CLI.PAIS
       INNER JOIN CAT_SECTOR_INSTITUCIONAL CSIN       --SECTOR INSTITUCIONAL--
          ON CSIN.ID = CLI.SECTOR
       INNER JOIN CAT_TIPO_INSTITUCION CTT               --TIPO INSTITUCION --
          ON CTT.ID = CLI.TIPO_INSTITUCION
       INNER JOIN FENIX.CAT_TIPO_CLIENTE CTC                  --TIPO CLIENTE--
          ON CTC.ID = CLI.TIPO_CLIENTE
       INNER JOIN CAT_OFICINA CATOFI
          ON CATOFI.ID = CLI.OFICINA
       INNER JOIN CAT_TIPO_PERSONA CATPER
          ON CATPER.ID = CLI.TIPO_PERSONA
  
         TCA_ESTADO_SCR
         
         
         SELECT * FROM SEGUIMIENTO_CREDITICIO 
--         WHERE ID_CLIENTE=1961
         ORDER BY  FECHA_REGISTRO DESC
         
         
      SELECT CLI.*
  FROM CLIENTES CLI
          JOIN  SEGUIMIENTO_CREDITICIO SECR
         ON SECR.ID_CLIENTE=CLI.ID_CLIENTE
         
               SELECT CLI.*
  FROM SEGUIMIENTO_CREDITICIO SECR
          JOIN   CLIENTES CLI
         ON SECR.ID_CLIENTE=CLI.ID_CLIENTE