/* Formatted on 01/08/2017 10:53:08 a.m. (QP5 v5.136.908.31019) */
  SELECT OPE.ID_OPERACION,
         OPE.NOMBRE AS NOMBRE_OPERACION,
         OPE.DESCRIPCION AS DESCRIPCION,
         OPE.ESTADO AS ID_ESTADO_OPERACION,
         OPE.USUARIO AS NOMBRE_USUARIO,
         OPE.SCR,
         OPE.RAROC,
         OPE.TIR,
         OPE.TIR_ESTATUS,
         OPE.FECHA_INICIO,
         OPE.FECHA_BAJA,
         OPE.TIPO_GARANTIA AS ID_GARANTIA,
         CLI.SECTOR,
         CLI.ID_FLEXCUBE AS BHQ_CLIENTE,
         CLI.RAZON_SOCIAL AS NOMBRE_CLIENTE,
         CLI.TIPO_PERSONA AS ID_TIPO_PERSONA,
         CLI.TIPO_INSTITUCION AS ID_TIPO_INSTITUCION,
         CLI.OFICINA AS ID_OFICINA,
         TCOP.DESCRIPCION AS ESTADO_OPERACION,
         TPE.DESCRIPCION AS PERSPECTIVA,
         CATP.DESCRIPCION AS PAIS_OPERACION,
         CATP.COD_EXTERNO AS PAIS_CODIGO_EXTERNO,
         CPR.DESCRIPCION_CORTA AS PRODUCTO,
         CSIN.DESCRIPCION AS SECTOR_INSTITUCIONAL,
         CTT.DESCRIPCION AS TIPO_INSTITUCION,
         CSM.DESCRIPCION_CORTA AS SECTOR_MERCADO,
         GAR.DESCRIPCION_CORTA AS GARANTIA,
         CTC.DESCRIPCION_CORTA AS TIPO_CLIENTE,
         CAE.DESCRIPCION AS ACTIVIDAD_ECONOMICA,
         CIE.DESCRIPCION AS INICIATIVA_ESTRATEGICA,
         CEE.DESCRIPCION AS EJE_ESTRATEGICO,
         ADF.DESCRIPCION AS AREA_FOCALIZACION,
         RPAI.DESCRIPCION AS RANGO_PAISES,
     MOSOLI.MONTO             AS MONTO_SOLICITADO,
MOPAPRO.MONTO     AS MONTO_APROBADO,
         CATOFI.DESCRIPCION AS OFICINA,
         CATPER.DESCRIPCION AS TIPO_PERSONA,
         CATP.ID AS ID_PRODUCTO,
         CPR.TIENE_RIESGO_CREDITO,
         SUPER.ID_TCA_SCT,
         TSCT.DESCRIPCION_CORTA DESCRIPCION_CORTA_SCT
    FROM FENIX.OPERACION OPE
         INNER JOIN CLIENTES CLI
            ON OPE.ID_CLIENTE = CLI.ID_CLIENTE
         INNER JOIN CAT_PRODUCTO CPR
            ON CPR.ID = OPE.ID_PRODUCTO
         INNER JOIN TCA_ESTADO_OPERACION TCOP             --ESTADO OPERACION--
            ON OPE.ESTADO = TCOP.ID
         LEFT JOIN TCA_PERSPECTIVA TPE                         --PERSPECTIVA--
            ON TPE.ID = OPE.ID_PERSPECTIVA
         INNER JOIN FENIX.CAT_PAISES CATP --PAIS OPERACION----   --PAIS CODIGO--
            ON CATP.ID = CLI.PAIS
         INNER JOIN CAT_SECTOR_INSTITUCIONAL CSIN     --SECTOR INSTITUCIONAL--
            ON CSIN.ID = CLI.SECTOR
         INNER JOIN CAT_TIPO_INSTITUCION CTT             --TIPO INSTITUCION --
            ON CTT.ID = CLI.TIPO_INSTITUCION
         LEFT JOIN FENIX.CAT_SECTOR_MERCADO CSM             --SECTOR MERCADO--
            ON CSM.ID = OPE.SECTOR_MERCADO
         LEFT JOIN FENIX.CAT_TIPO_GARANTIA GAR                    --GARANTÍA--
            ON GAR.ID = OPE.TIPO_GARANTIA
         INNER JOIN FENIX.CAT_TIPO_CLIENTE CTC                --TIPO CLIENTE--
            ON CTC.ID = CLI.TIPO_CLIENTE
         INNER JOIN CAT_ACTIVIDAD_ECONOMICA CAE        --ACTIVIDAD ECONOMICA--
            ON CAE.ID = OPE.ACTIVIDAD_ECONOMICA
         INNER JOIN CAT_INICIATIVA_ESTRATEGICA CIE  --INICIATIVA ESTRATÉGICA--
            ON CIE.ID = OPE.INICIATIVA_ESTRATEGICA
         INNER JOIN CAT_EJE_ESTRATEGICO CEE                --EJE ESTRATEGICO--
            ON CEE.ID = OPE.EJE_ESTRATEGICO
         INNER JOIN CAT_AREA_FOCALIZACION ADF         --AREA DE FOCALIZACION--
            ON ADF.ID = OPE.AREA_FOCALIZACION
         LEFT JOIN TCA_RANGO_PAISES RPAI                      --RANGO PAISES--
            ON RPAI.ID = OPE.ID_RANGO_PAIS
         INNER JOIN CAT_OFICINA CATOFI
            ON CATOFI.ID = CLI.OFICINA
         INNER JOIN CAT_TIPO_PERSONA CATPER
            ON CATPER.ID = CLI.TIPO_PERSONA
            LEFT JOIN MONTO_OPERACION MOSOLI    --MONTO SOLICITADO--
            ON ( MOSOLI.ID_OPERACION = OPE.ID_OPERACION
                 AND MOSOLI.ID_TCA_TIPO_MONTO = 2)
            LEFT JOIN       MONTO_OPERACION MOPAPRO      --MONTO APROBADO--
           ON ( MOPAPRO.ID_TCA_TIPO_MONTO = 3
                 AND MOPAPRO.ID_OPERACION = OPE.ID_OPERACION)
                 INNER JOIN SUPERVISION SUPER 
                 ON (SUPER.ID_OPERACION =OPE.ID_OPERACION)
                 INNER  JOIN  TCA_SCT TSCT
                 ON TSCT.ID=SUPER.ID_TCA_SCT
 WHERE       SUPER.ID_TCA_SCT IS NOT NULL
--OPE.ID_OPERACION = 503707
ORDER BY ID_OPERACION ASC
--3,633