--------------------------------------------------------
-- Archivo creado  - lunes-octubre-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Function F_ACTUALIZA_PERSP_CLI
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "FENIX"."F_ACTUALIZA_PERSP_CLI" 
(
  P_ID_CLIENTE IN CLIENTES.ID_CLIENTE%TYPE 
, P_ID_FLUJO IN  SEGUIMIENTO_CREDITICIO.ID_FLUJO%TYPE 
) RETURN VARCHAR2 
AS 
V_C_ID_TCA_PERSPECTIVA CLIENTES.ID_TCA_PERSPECTIVA%TYPE;
V_S_ID_TCA_PERSPECTIVA SEGUIMIENTO_CREDITICIO.ID_TCA_PERSPECTIVA%TYPE;
BEGIN
    SELECT C.ID_TCA_PERSPECTIVA,S.ID_TCA_PERSPECTIVA
    INTO V_C_ID_TCA_PERSPECTIVA,V_S_ID_TCA_PERSPECTIVA
    FROM CLIENTES C, SEGUIMIENTO_CREDITICIO S
    WHERE C.ID_CLIENTE=S.ID_CLIENTE AND S.TIPO_INICIO='NORMAL' AND C.ID_CLIENTE=P_ID_CLIENTE
    AND S.ID_FLUJO=P_ID_FLUJO
    AND s.ID= (select max(id) from SEGUIMIENTO_CREDITICIO where ID_CLIENTE=P_ID_CLIENTE and TIPO_INICIO='NORMAL' and ID_FLUJO=P_ID_FLUJO );
    IF V_C_ID_TCA_PERSPECTIVA<>V_S_ID_TCA_PERSPECTIVA THEN
        UPDATE CLIENTES
        SET ID_TCA_PERSPECTIVA=V_S_ID_TCA_PERSPECTIVA 
        WHERE ID_CLIENTE=P_ID_CLIENTE;
        COMMIT;
        RETURN 'SI';
    ELSIF V_C_ID_TCA_PERSPECTIVA IS NULL AND V_S_ID_TCA_PERSPECTIVA IS NOT NULL THEN
        UPDATE CLIENTES
        SET ID_TCA_PERSPECTIVA=V_S_ID_TCA_PERSPECTIVA 
        WHERE ID_CLIENTE=P_ID_CLIENTE;
        COMMIT;
        RETURN 'SI';
    ELSE
        RETURN 'NO';
    END IF;
EXCEPTION
  WHEN OTHERS THEN
      RETURN 'NO';
END F_ACTUALIZA_PERSP_CLI;

/
