create or replace PROCEDURE SP_CONSULTAR_IMPORTE_TRANSITO(
   P_IDLINEA              IN NUMBER,
   P_LINEA_FINANCIERA     IN VARCHAR2,
   P_PAIS                 IN VARCHAR2, 
   P_MONEDA               IN VARCHAR2, 
   P_CODIGO_RES          OUT NUMBER,
   P_Mensaje             OUT VARCHAR2, 
   P_FECHA_ESTIMADA          DATE,   
   RECORDSET1            OUT SYS_REFCURSOR,   
   RECORDSET             OUT SYS_REFCURSOR
   )
AS
   v_Monto_transito         NUMBER;
   v_con_linea              NUMBER;
   RECORDSET_SELECT         VARCHAR2(2000);
BEGIN
   SELECT COUNT ( * )
     INTO v_con_linea
     FROM LINEA_CREDITO LC
    WHERE ID = P_IDLINEA AND LC.ID_FLEXCUBE IS NOT NULL;

   IF (v_con_linea > 0) THEN
   
      RECORDSET_SELECT :='SELECT SUM (MONTO_DESEMBOLSAR) AS MONTO_DESEMBOLSAR,TTM.COD_EXTERNO';
      RECORDSET_SELECT := RECORDSET_SELECT ||' FROM CONTRATO_DESEMBOLSO CD,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' TCA_ESTADO_OPERACION TEO,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' TRE_SOLICITUD_LINEA_CREDITO TRSL,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' LINEA_CREDITO LC,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' TCA_TIPO_MONEDA TTM,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' CONTRATO CON,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' OPERACION OPE,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' CLIENTES CLI,';
      RECORDSET_SELECT := RECORDSET_SELECT ||' CAT_PAISES CPA';
      RECORDSET_SELECT := RECORDSET_SELECT ||' WHERE CD.ID_TCA_ESTADO = TEO.ID';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND TRSL.ID_CONTRATO_DESEMBOLSO = CD.ID';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND TRSL.ID_LINEA = LC.ID';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND CD.ID_TCA_TIPO_MONEDA = TTM.ID';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND LC.ID_FLEXCUBE IS NOT NULL';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND LC.ID_CONTRATO = CON.ID';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND CON.ID_OPERACION = OPE.ID_OPERACION';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND OPE.ID_CLIENTE = CLI.ID_CLIENTE';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND CLI.PAIS = CPA.ID';
      RECORDSET_SELECT := RECORDSET_SELECT ||' AND TEO.ID IN (14, 15, 16)';
      
      IF (P_IDLINEA IS NOT NULL) THEN 
        RECORDSET_SELECT := RECORDSET_SELECT ||' AND LC.ID = '||P_IDLINEA||'';
      END IF;
      IF (P_LINEA_FINANCIERA IS NOT NULL) THEN 
        RECORDSET_SELECT := RECORDSET_SELECT ||' AND NVL('''||P_LINEA_FINANCIERA||''',CD.PROGRAMA_OPERACION) LIKE (''%''||CD.PROGRAMA_OPERACION||''%'')';
      END IF;
      IF (P_FECHA_ESTIMADA IS NOT NULL) THEN 
        RECORDSET_SELECT := RECORDSET_SELECT ||' AND TO_CHAR (CD.FECHA_ESTIMADA_DESEMBOLSAR , ''MM-YYYY'')   = '''||TO_CHAR (P_FECHA_ESTIMADA , 'MM-YYYY')||'''';
      END IF;
      IF (P_PAIS IS NOT NULL) THEN 
        RECORDSET_SELECT := RECORDSET_SELECT ||' AND NVL('''||P_PAIS||''',CPA.COD_EXTERNO) LIKE (''%''||CPA.COD_EXTERNO||''%'')';
      END IF;
      IF (P_MONEDA IS NOT NULL) THEN 
        RECORDSET_SELECT := RECORDSET_SELECT ||' AND NVL('''||P_MONEDA||''',TTM.COD_EXTERNO) LIKE (''%''||TTM.COD_EXTERNO||''%'')';
      END IF;
      --DBMS_OUTPUT.PUT_LINE(RECORDSET_SELECT);
      RECORDSET_SELECT := RECORDSET_SELECT ||' GROUP BY TTM.COD_EXTERNO';
      OPEN RECORDSET FOR RECORDSET_SELECT;

      OPEN RECORDSET1 FOR
         SELECT CD.ID ID_CONTRATO_DESEMBOLSO,
                CD.PROGRAMADO,
                CD.FECHA_ESTIMADA_DESEMBOLSAR,
                CD.FECHA_EFECTIVA,
                CD.FECHA_REGISTRO,
                CD.BAN_ESTATUS,
                CD.MONTO_DESEMBOLSAR,
                CD.ID_TCA_TIPO_MONEDA,
				CD.DESTINO_FINANCIAMIENTO,
                TTM.DESCRIPCION_CORTA DESCRIPCION_CORTA_MONEDA,
                CD.ID_TCA_ESTADO,
                TEO.DESCRIPCION_CORTA DESCRIPCION_CORTA_ESTADO,
                LC.NUMERO_LINEA_CREDITO,
                LC.ID ID_LINEA_CREDITO
           FROM CONTRATO_DESEMBOLSO CD,
                TCA_ESTADO_OPERACION TEO,
                TRE_SOLICITUD_LINEA_CREDITO TRSL,
                LINEA_CREDITO LC,
                TCA_TIPO_MONEDA TTM,
                CONTRATO CON,
                OPERACION OPE,
                CLIENTES CLI,
                CAT_PAISES CPA
          WHERE     CD.ID_TCA_ESTADO = TEO.ID
                AND TRSL.ID_CONTRATO_DESEMBOLSO = CD.ID
                AND TRSL.ID_LINEA = LC.ID
                AND CD.ID_TCA_TIPO_MONEDA = TTM.ID
                AND LC.ID_CONTRATO = CON.ID
                AND CON.ID_OPERACION = OPE.ID_OPERACION
                AND OPE.ID_CLIENTE = CLI.ID_CLIENTE
                AND CLI.PAIS = CPA.ID
                AND LC.ID = P_IDLINEA;

--      P_Monto_transito := v_Monto_transito;

      P_CODIGO_RES := 1;

      P_MENSAJE := 'Procedimiento ejecutado correctamente ';
   ELSE
      P_CODIGO_RES := 1;
      P_MENSAJE :=
            'La linea de credito '
         || ' '
         || P_IDLINEA
         || ' '
         || ' No tiene asignado un ID_FLEXCUBE';
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      P_CODIGO_RES := 0;
      P_MENSAJE :=
         'Error en el procedimiento Consultar Importe Transito, No existen datos!';
   WHEN OTHERS
   THEN
      P_CODIGO_RES := 0;
      P_MENSAJE := 'Error en el procedimiento Consultar Importe Transito!';
END;
/