CREATE OR REPLACE PROCEDURE FENIX.SP_OBTENER_RECIBO_PAGO (
   P_FECHA_INICIO    IN     DATE,
   P_FECHA_FIN       IN     DATE,
   P_LISTA_RECIBOS      OUT SYS_REFCURSOR)
IS
BEGIN
   OPEN P_LISTA_RECIBOS FOR
      SELECT FECHA_EFECTIVA,
             LINEA,
             NUMERO_PRESTAMO,
             NUMERO_TESORERIA,
             NUMERO_RECIBO,
             VALOR_ADEUDADO,
             SALDO_DESCRIPCION,
             MONEDA_ADEUDADA,
             PCA_VALOR_CAMBIO,
             CODIGO_MONEDA,
             MONEDA_PAGADA,
             VALOR_PAGADO
        FROM VTA_RECIBO_PAGO_F_EFECTIVA VRPFE
       WHERE VRPFE.FECHA_EFECTIVA BETWEEN P_FECHA_INICIO AND P_FECHA_FIN;
END;
/
