CREATE OR REPLACE TYPE T_BITACORA_DOCUMENTO AS OBJECT
(
	ID	NUMBER(12,0),
	ID_DOCUMENTO	NUMBER(12),
	ID_ADJUNTO	NUMBER(12),
	ESTADO	VARCHAR2(20),
	NUM_INSTANCIA	VARCHAR2(256),
	SE_HA_NOTIFICADO	NUMBER(1),
	LOGIN_USUARIO	VARCHAR2(32),
	NOMBRE_USUARIO	VARCHAR2(128),
	ID_TCA_TAREA_BPM	NUMBER(5),
	BAN_ESTATUS	NUMBER(1),
	FECHA_REGISTRO	DATE,
	DESCRIPCION	VARCHAR2(4000),
	ES_REG_ACTIVO	NUMBER(1)
);