CREATE OR REPLACE TRIGGER TRE_SOL_LINEA_CREDITO_TGR
AFTER INSERT   ON TRE_SOLICITUD_LINEA_CREDITO FOR EACH ROW
DECLARE
	CONTRATO NUMBER(12,0);
	ID_EXCEPTUADO NUMBER(1,0);
	ID_REGLA_EXCEP NUMBER(5,0);
	SOLICITUD NUMBER(12,0);
	IN_INSTANCIA VARCHAR(256);
	IN_USUARIO VARCHAR2(255) := 'SYS';
	VALUE VARCHAR2(1);
	err_num NUMBER;
	err_msg VARCHAR2(255);
   
	CURSOR c2 IS
		SELECT ID_TCA_REGLA, EXCEPTUADO, INSTANCIA_PROCESO 
		FROM TRE_EXCEPCION_SOLICITUD
		WHERE ID_SOLICITUD = SOLICITUD AND EN_PROCESO_EXCEPCION = 0 AND EXCEPTUADO =1;

	-- Se heredan las excepciones realizadas a la solicitud de desembolso, a los nuevos contratos de desembolso que se registren y asocien a dicha solicitud de desembolso.
BEGIN

	CONTRATO := :NEW.ID_CONTRATO_DESEMBOLSO;
	SOLICITUD :=  :NEW.ID_SOLICITUD;

	--SELECT 'Y' INTO VALUE FROM TRE_EXCEPCION_SOLICITUD WHERE ID_SOLICITUD = SOLICITUD AND  EN_PROCESO_EXCEPCION = 0 AND EXCEPTUADO = 1;
  
	--IF VALUE = 'Y' THEN
 
		OPEN c2;
			LOOP
				FETCH c2 INTO ID_REGLA_EXCEP,ID_EXCEPTUADO, IN_INSTANCIA;
				EXIT WHEN c2%notfound;
		  
				IF ID_EXCEPTUADO =1 THEN
		  
					SELECT USUARIO INTO IN_USUARIO FROM TBI_PROCESO_OPERACION WHERE INSTANCIA_PROCESO = IN_INSTANCIA  AND ID_TAREA = 165 AND BAN_ES_FIN_ACTIVIDAD = 1;
		
					UPDATE TRE_REGLA_DESEMBOLSO SET EXCEPTUADO = ID_EXCEPTUADO, USUARIOEXCEPTUA = IN_USUARIO, FECHA_EXCEPCION = SYSDATE  WHERE ID_TCA_REGLA = ID_REGLA_EXCEP AND       
					ID_DESEMBOLSO = CONTRATO;
					
					DBMS_OUTPUT.PUT_LINE(ID_REGLA_EXCEP || ' - ' || ID_EXCEPTUADO || ' - ' || IN_INSTANCIA || ' - ' || IN_USUARIO );
				END IF;

			END LOOP;
		CLOSE c2;
	--END IF;

EXCEPTION 
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SQLERRM;
		
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','TRIGGER TRE_SOL_LINEA_CREDITO_TGR','Solicitud: ' || SOLICITUD || ' - Contrato: '||CONTRATO||' - Error: '||TO_CHAR(err_num)||' '||SUBSTR(err_msg,1,520),TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
	END;
/
