
CREATE OR REPLACE VIEW VCA_FONDO
	AS
		SELECT MIS_CLASS, MIS_CODE, CODE_DESC, ACTIVE
		FROM MIDDLE.FC_V_MIS_CODES
		WHERE MIS_CLASS ='FONDO'
			AND ACTIVE='A'
			AND MIS_CODE IN('1','7','10','25','57', '98');