<wsdl:definitions name="ConsultarDocumentoTareaDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarDocumentoTareaDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarDocumentoTareaDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDocumentoTareaDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarDocumentoTareaDB_plt">
    <plt:role name="ConsultarDocumentoTareaDB_role">
      <plt:portType name="tns:ConsultarDocumentoTareaDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDocumentoTareaDB" schemaLocation="../XSD/ConsultarDocumentoTareaDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarDocumentoTareaDBInput_msg">
        <wsdl:part name="ConsultarDocumentoTareaDBInput_msg" element="db:ConsultarDocumentoTareaDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarDocumentoTareaDBOutputCollection_msg">
        <wsdl:part name="ConsultarDocumentoTareaDBOutputCollection" element="db:ConsultarDocumentoTareaDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarDocumentoTareaDB_ptt">
        <wsdl:operation name="ConsultarDocumentoTareaDB">
            <wsdl:input message="tns:ConsultarDocumentoTareaDBInput_msg"/>
            <wsdl:output message="tns:ConsultarDocumentoTareaDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>