<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ObtenerURL"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ObtenerURL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ObtenerURL">
        <plnk:role name="ObtenerURLPT" portType="tns:ObtenerURLPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ObtenerURL" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ObtenerURL/V1/Wsdl/ObtenerURL.wsdl"/>
</wsdl:definitions>
