<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.banesco.com/eopt/AcctLoanAgreeAdd_V1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.banesco.com/appopt/WFAcctLoanAppSvc/AcctLoanAgreeAdd_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns6="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns7="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns5="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanAgreeAdd/AcctLoanAgreeAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctLoanAgreeAddRs" namespace="http://xmlns.banesco.com/eopt/AcctLoanAgreeAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/WFAcctLoan/AcctLoanAgreeAdd/AcctLoanAgreeAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctLoanAgreeAddRs" namespace="http://xmlns.banesco.com/appopt/WFAcctLoanAppSvc/AcctLoanAgreeAdd_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI MAY 18 16:52:45 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AcctLoanAgreeAddRs>         
         <xsl:if test="/ns0:AcctLoanAgreeAddRs/ns0:Acct/ns0:AcctKey/eoAcct:AcctId">
            <tns:AcctLoanAgreeRec>
               <tns:Acct>
                  <tns:AcctKey>
                     <tns:AcctId>
                        <xsl:value-of select="/ns0:AcctLoanAgreeAddRs/ns0:Acct/ns0:AcctKey/eoAcct:AcctId"/>
                     </tns:AcctId>
                  </tns:AcctKey>
                  <!--tns:CredicAcctData>
                     <tns:Agreement>
                        <tns:AgreementId>
                           <xsl:value-of select="/ns0:AcctLoanAgreeAddRs/ns0:Acct/ns0:CreditAcctData/ns0:Agreement/eoAcct:AgreementId"/>
                        </tns:AgreementId>
                     </tns:Agreement>
                  </tns:CredicAcctData-->
               </tns:Acct>
            </tns:AcctLoanAgreeRec>
         </xsl:if>   
         <tns:Status>
            <appoptcommon:StatusCode>
               <xsl:value-of select="/ns0:AcctLoanAgreeAddRs/ns0:Status/eoStatus:StatusCode"/>
            </appoptcommon:StatusCode>
            <appoptcommon:StatusDesc>
               <xsl:value-of select="/ns0:AcctLoanAgreeAddRs/ns0:Status/eoStatus:StatusDesc"/>
            </appoptcommon:StatusDesc>
         </tns:Status>
      </tns:AcctLoanAgreeAddRs>
   </xsl:template>
</xsl:stylesheet>
