<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="urn:ActualizarSolicitudAprobacionByIdOperacionSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:ActualizarSolicitudAprobacionByIdOperacionSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO">
<wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ActualizarSolicitudAprobacionByIdOperacionRequestMessage">
    <wsdl:part name="ActualizarSolicitudAprobacionByIdOperacionRequest"
               element="solAproMO:ActualizarSolicitudAprobacionByIdOperacionRequest"/>
  </wsdl:message>
  <wsdl:message name="ActualizarSolicitudAprobacionByIdOperacionResponseMessage">
    <wsdl:part name="ActualizarSolicitudAprobacionByIdOperacionResponse"
               element="solAproMO:ActualizarSolicitudAprobacionByIdOperacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ActualizarSolicitudAprobacionByIdOperacionPT">
    <wsdl:operation name="actualizarSolicitudAprobacionByIdOperacion">
      <wsdl:input message="tns:ActualizarSolicitudAprobacionByIdOperacionRequestMessage"/>
      <wsdl:output message="tns:ActualizarSolicitudAprobacionByIdOperacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ActualizarSolicitudAprobacionByIdOperacionPT12Bnd"
                type="tns:ActualizarSolicitudAprobacionByIdOperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizarSolicitudAprobacionByIdOperacion">
      <soap12:operation style="document"
                        soapAction="urn:ActualizarSolicitudAprobacionByIdOperacionSAD/actualizarSolicitudAprobacionByIdOperacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="ActualizarSolicitudAprobacionByIdOperacionRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="ActualizarSolicitudAprobacionByIdOperacionResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>