<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ConsultarDecisionAprobacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarDecisionAprobacion"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultarDecisionAprobacionRequestMessage">
    <wsdl:part name="request" element="solAproMO:ConsultarDecisionAprobacionByIdAprobacionRequest"/>
  </wsdl:message>
  <wsdl:message name="ConsultarDecisionAprobacionResponseMessage">
    <wsdl:part name="response" element="solAproMO:ConsultarDecisionAprobacionByIdAprobacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarDecisionAprobacionPT">
    <wsdl:operation name="consultarDecisionAprobacion">
      <wsdl:input message="tns:ConsultarDecisionAprobacionRequestMessage"/>
      <wsdl:output message="tns:ConsultarDecisionAprobacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarDecisionAprobacion12Bnd" type="tns:ConsultarDecisionAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarDecisionAprobacion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarDecisionAprobacion/consultarDecisionAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>