<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/CrearRegistroVotacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearRegistroVotacion"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CreaRegistroVotacionRequestMessage">
    <wsdl:part name="request" element="solAproMO:CrearRegistroVotacionRequest"/>
  </wsdl:message>
  <wsdl:message name="CreaRegistroVotacionResponseMessage">
    <wsdl:part name="response" element="solAproMO:CrearRegistroVotacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="CrearRegistroVotacionPT">
    <wsdl:operation name="crearRegistroVotacion">
      <wsdl:input message="tns:CreaRegistroVotacionRequestMessage"/>
      <wsdl:output message="tns:CreaRegistroVotacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CrearRegistroVotacion12Bnd" type="tns:CrearRegistroVotacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearRegistroVotacion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CrearRegistroVotacion/crearRegistroVotacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>