<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ValidarMoraSOR" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ValidarMoraSOR" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:CliMO="http://www.bcie.org/ClienteMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ValidarMoraSOR/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestValidarMoraMessage">
    <part name="request" element="CliMO:ValidarMoraRequest"/>
  </message>
  <message name="responseValidarMoraMessage">
    <part name="response" element="CliMO:ValidarMoraResponse"/>
  </message>
  <portType name="ValidarMora_PT">
    <operation name="ValidarMora">
      <input message="tns:requestValidarMoraMessage"/>
      <output message="tns:responseValidarMoraMessage"/>
    </operation>
  </portType>
  <binding name="ValidarMora_PTSOAP12Binding" type="tns:ValidarMora_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ValidarMora">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ValidarMoraSOR/ValidarMora"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>