<wsdl:definitions name="ValidarOperacionProceso_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/OIDServices/ValidarOperacionProceso_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/OIDServices/ValidarOperacionProceso_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarOperacionProceso_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ValidarOperacionProceso_DB_plt">
    <plt:role name="ValidarOperacionProceso_DB_role">
      <plt:portType name="tns:ValidarOperacionProceso_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarOperacionProceso_DB" schemaLocation="../XSD/ValidarOperacionProceso_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ValidarOperacionProceso_DBInput_msg">
        <wsdl:part name="ValidarOperacionProceso_DBInput_msg" element="db:ValidarOperacionProceso_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ValidarOperacionProceso_DBOutputCollection_msg">
        <wsdl:part name="ValidarOperacionProceso_DBOutputCollection" element="db:ValidarOperacionProceso_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ValidarOperacionProceso_DB_ptt">
        <wsdl:operation name="ValidarOperacionProceso_DB">
            <wsdl:input message="tns:ValidarOperacionProceso_DBInput_msg"/>
            <wsdl:output message="tns:ValidarOperacionProceso_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>