<wsdl:definitions name="ConsultarTreComision_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarTreComision_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarTreComision_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreComision_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTreComision_DB_plt">
    <plt:role name="ConsultarTreComision_DB_role">
      <plt:portType name="tns:ConsultarTreComision_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreComision_DB" schemaLocation="../XSD/ConsultarTreComision_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTreComision_DBInput_msg">
        <wsdl:part name="ConsultarTreComision_DBInput_msg" element="db:ConsultarTreComision_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTreComision_DBOutputCollection_msg">
        <wsdl:part name="ConsultarTreComision_DBOutputCollection" element="db:ConsultarTreComision_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTreComision_DB_ptt">
        <wsdl:operation name="ConsultarTreComision_DB">
            <wsdl:input message="tns:ConsultarTreComision_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarTreComision_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>