<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="caseTwoPrimary" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ItemCataloApp/ItemDiffTranslate/caseTwoPrimary" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ItemCataloApp/ItemDiffTranslate/caseTwoPrimary" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoPrimary" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="caseTwoPrimary_plt">
      <plt:role name="caseTwoPrimary_role">
         <plt:portType name="tns:caseTwoPrimary_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoPrimary" schemaLocation="../Schemas/caseTwoPrimary_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="caseTwoPrimarySelect_inputParameters">
      <wsdl:part name="caseTwoPrimarySelect_inputParameters" element="top:caseTwoPrimarySelect_idC2_appCodeC2_catDefC2_parnIdC2_parnCatIdC2InputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmItemsDiffsCollection_msg">
      <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
   </wsdl:message>
   <wsdl:portType name="caseTwoPrimary_ptt">
      <wsdl:operation name="caseTwoPrimarySelect">
         <wsdl:input message="tns:caseTwoPrimarySelect_inputParameters"/>
         <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
