<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.banesco.com/eopt/PartyStaffInq_V1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.banesco.com/appopt/WFPartyAppSvc/PartyStaffInq_V1.0"
                exclude-result-prefixes="oracle-xsl-mapper xsl ns0 eoPar eoStatus ns2"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Party/PartyStaffInq/PartyStaffInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PartyStaffInqRs"
                                       namespace="http://xmlns.banesco.com/eopt/PartyStaffInq_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/WFParty/PartyStaffInq/PartyStaffInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PartyStaffInqRs"
                                       namespace="http://xmlns.banesco.com/appopt/WFPartyAppSvc/PartyStaffInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON MAR 12 17:00:26 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:PartyStaffInqRs>
      <xsl:if test="/ns0:PartyStaffInqRs/ns0:Party">
        <tns:Party>
          <xsl:if test="/ns0:PartyStaffInqRs/ns0:Party/ns0:PartyKey">
            <tns:PartyKey>
              <xsl:if test="/ns0:PartyStaffInqRs/ns0:Party/ns0:PartyKey/eoPar:PartyId/text()">
                <tns:PartyId>
                  <xsl:value-of select="/ns0:PartyStaffInqRs/ns0:Party/ns0:PartyKey/eoPar:PartyId"/>
                </tns:PartyId>
              </xsl:if>
              <xsl:if test="/ns0:PartyStaffInqRs/ns0:Party/ns0:PartyKey/eoPar:PartyType/text()">
                <tns:PartyType>
                  <xsl:value-of select="/ns0:PartyStaffInqRs/ns0:Party/ns0:PartyKey/eoPar:PartyType"/>
                </tns:PartyType>
              </xsl:if>
            </tns:PartyKey>
          </xsl:if>
          <xsl:if test="/ns0:PartyStaffInqRs/ns0:Party/ns0:OrgPartyInfo">
            <tns:OrgPartyInfo>
              <xsl:if test="/ns0:PartyStaffInqRs/ns0:Party/ns0:OrgPartyInfo/ns0:OrgData">
                <tns:OrgData>
                  <xsl:for-each select="/ns0:PartyStaffInqRs/ns0:Party/ns0:OrgPartyInfo/ns0:OrgData/eoPar:Staff">
                    <tns:Staff>
                      <xsl:if test="eoPar:BirthDt/text()">
                        <tns:BirthDt>
                          <xsl:value-of select="eoPar:BirthDt"/>
                        </tns:BirthDt>
                      </xsl:if>
                      <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                      <xsl:if test="eoPar:CountryBirth/ns2:CountryCode/text()">
                        <tns:CountryBirth>
                          <appoptcommon:CountryCode>
                            <xsl:value-of select="eoPar:CountryBirth/ns2:CountryCode"/>
                          </appoptcommon:CountryCode>                         
                        </tns:CountryBirth>
                      </xsl:if>                      
                      <xsl:if test="eoPar:FATCA">
                        <tns:FATCA>
                          <!-- Se eliminan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                          <!--xsl:if test="eoPar:FATCA/eoPar:FatcaType/text()">
                            <tns:FatcaType>
                              <xsl:value-of select="eoPar:FATCA/eoPar:FatcaType"/>
                            </tns:FatcaType>
                          </xsl:if>
                          <xsl:if test="eoPar:FATCA/eoPar:FormId/text()">
                            <tns:FormId>
                              <xsl:value-of select="eoPar:FATCA/eoPar:FormId"/>
                            </tns:FormId>
                          </xsl:if-->
                          <xsl:if test="eoPar:FATCA/eoPar:GIIN/text()">
                            <tns:GIIN>
                              <xsl:value-of select="eoPar:FATCA/eoPar:GIIN"/>
                            </tns:GIIN>
                          </xsl:if>
                          <!-- Se eliminan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                          <!--xsl:if test="eoPar:FATCA/eoPar:GreenCard/text()">
                            <tns:GreenCard>
                              <xsl:value-of select="eoPar:FATCA/eoPar:GreenCard"/>
                            </tns:GreenCard>
                          </xsl:if-->
                          <xsl:if test="eoPar:FATCA/eoPar:OtherNationality/text()">
                            <tns:OtherNationality>
                              <xsl:value-of select="eoPar:FATCA/eoPar:OtherNationality"/>
                            </tns:OtherNationality>
                          </xsl:if>
                          <!-- Se eliminan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                          <!--xsl:if test="eoPar:FATCA/eoPar:SSN/text()">
                            <tns:SSN>
                              <xsl:value-of select="eoPar:FATCA/eoPar:SSN"/>
                            </tns:SSN>
                          </xsl:if>
                          <xsl:if test="eoPar:FATCA/eoPar:TIN/text()">
                            <tns:TIN>
                              <xsl:value-of select="eoPar:FATCA/eoPar:TIN"/>
                            </tns:TIN>
                          </xsl:if-->
                          <xsl:if test="eoPar:FATCA/eoPar:US183Permanence/text()">
                            <tns:US183Permanence>
                              <xsl:value-of select="eoPar:FATCA/eoPar:US183Permanence"/>
                            </tns:US183Permanence>
                          </xsl:if>
                          <xsl:if test="eoPar:FATCA/eoPar:USRelated/text()">
                            <tns:USRelated>
                              <xsl:value-of select="eoPar:FATCA/eoPar:USRelated"/>
                            </tns:USRelated>
                          </xsl:if>
                          <xsl:if test="eoPar:FATCA/eoPar:USResid/text()">
                            <tns:USResid>
                              <xsl:value-of select="eoPar:FATCA/eoPar:USResid"/>
                            </tns:USResid>
                          </xsl:if>
                          <xsl:if test="eoPar:FATCA/eoPar:USSignor/text()">
                            <tns:USSignor>
                              <xsl:value-of select="eoPar:FATCA/eoPar:USSignor"/>
                            </tns:USSignor>
                          </xsl:if>
                        </tns:FATCA>
                      </xsl:if>
                      <xsl:if test="eoPar:Gender/text()">
                        <tns:Gender>
                          <xsl:value-of select="eoPar:Gender"/>
                        </tns:Gender>
                      </xsl:if>
                      <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                      <xsl:if test="eoPar:OrgEstablishDt/text()">
                        <tns:OrgEstablishDt>
                          <xsl:value-of select="eoPar:OrgEstablishDt"/>
                        </tns:OrgEstablishDt>
                      </xsl:if>                      
                      <xsl:if test="eoPar:PartyData">
                        <tns:PartyData>
                          <xsl:if test="eoPar:PartyData/eoPar:Contact">
                            <tns:Contact>
                              <xsl:if test="eoPar:PartyData/eoPar:Contact/ns2:Locator">
                                <tns:Locator>
                                  <xsl:for-each select="eoPar:PartyData/eoPar:Contact/ns2:Locator/ns2:PostAddr">
                                    <tns:PostAddr>
                                      <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                                      <xsl:if test="ns2:AddrDesc/text()">
                                        <tns:AddrDesc>
                                          <xsl:value-of select="ns2:AddrDesc"/>
                                        </tns:AddrDesc>
                                      </xsl:if>                                      
                                      <xsl:if test="ns2:Building">
                                        <tns:Building>
                                          <xsl:if test="ns2:Building/ns2:Cod/text()">
                                            <appoptcommon:Cod>
                                              <xsl:value-of select="ns2:Building/ns2:Cod"/>
                                            </appoptcommon:Cod>
                                          </xsl:if>
                                          <xsl:if test="ns2:Building/ns2:Desc/text()">
                                            <appoptcommon:Desc>
                                              <xsl:value-of select="ns2:Building/ns2:Desc"/>
                                            </appoptcommon:Desc>
                                          </xsl:if>
                                        </tns:Building>
                                      </xsl:if>
                                      <xsl:if test="ns2:City">
                                        <tns:City>
                                          <xsl:if test="ns2:City/ns2:Cod/text()">
                                            <appoptcommon:Cod>
                                              <xsl:value-of select="ns2:City/ns2:Cod"/>
                                            </appoptcommon:Cod>
                                          </xsl:if>
                                          <xsl:if test="ns2:City/ns2:Desc/text()">
                                            <appoptcommon:Desc>
                                              <xsl:value-of select="ns2:City/ns2:Desc"/>
                                            </appoptcommon:Desc>
                                          </xsl:if>
                                        </tns:City>
                                      </xsl:if>
                                      <xsl:if test="ns2:CountyDistrict">
                                        <tns:CountyDistrict>
                                          <xsl:if test="ns2:CountyDistrict/ns2:Cod/text()">
                                            <appoptcommon:Cod>
                                              <xsl:value-of select="ns2:CountyDistrict/ns2:Cod"/>
                                            </appoptcommon:Cod>
                                          </xsl:if>
                                          <xsl:if test="ns2:CountyDistrict/ns2:Desc/text()">
                                            <appoptcommon:Desc>
                                              <xsl:value-of select="ns2:CountyDistrict/ns2:Desc"/>
                                            </appoptcommon:Desc>
                                          </xsl:if>
                                        </tns:CountyDistrict>
                                      </xsl:if>
                                      <xsl:if test="ns2:HouseNumber/text()">
                                        <tns:HouseNumber>
                                          <xsl:value-of select="ns2:HouseNumber"/>
                                        </tns:HouseNumber>
                                      </xsl:if>
                                      <xsl:if test="ns2:Jurisdiction">
                                        <tns:Jurisdiction>
                                          <xsl:if test="ns2:Jurisdiction/ns2:Cod/text()">
                                            <appoptcommon:Cod>
                                              <xsl:value-of select="ns2:Jurisdiction/ns2:Cod"/>
                                            </appoptcommon:Cod>
                                          </xsl:if>
                                          <xsl:if test="ns2:Jurisdiction/ns2:Desc/text()">
                                            <appoptcommon:Desc>
                                              <xsl:value-of select="ns2:Jurisdiction/ns2:Desc"/>
                                            </appoptcommon:Desc>
                                          </xsl:if>
                                        </tns:Jurisdiction>
                                      </xsl:if>
                                      <xsl:if test="ns2:PostalCode/text()">
                                        <tns:PostalCode>
                                          <xsl:value-of select="ns2:PostalCode"/>
                                        </tns:PostalCode>
                                      </xsl:if>
                                      <xsl:if test="ns2:Province">
                                        <tns:Province>
                                          <xsl:if test="ns2:Province/ns2:Cod/text()">
                                            <appoptcommon:Cod>
                                              <xsl:value-of select="ns2:Province/ns2:Cod"/>
                                            </appoptcommon:Cod>
                                          </xsl:if>
                                          <xsl:if test="ns2:Province/ns2:Desc/text()">
                                            <appoptcommon:Desc>
                                              <xsl:value-of select="ns2:Province/ns2:Desc"/>
                                            </appoptcommon:Desc>
                                          </xsl:if>
                                        </tns:Province>
                                      </xsl:if>
                                      <xsl:if test="ns2:Street/text()">
                                        <tns:Street>
                                          <xsl:value-of select="ns2:Street"/>
                                        </tns:Street>
                                      </xsl:if>
                                      <xsl:if test="ns2:Country">
                                        <tns:Country>
                                          <xsl:if test="ns2:Country/ns2:CountryCode/text()">
                                            <tns:CountryCode>
                                              <xsl:value-of select="ns2:Country/ns2:CountryCode"/>
                                            </tns:CountryCode>
                                          </xsl:if>
                                          <xsl:if test="ns2:Country/ns2:CountryName/text()">
                                            <tns:CountryName>
                                              <xsl:value-of select="ns2:Country/ns2:CountryName"/>
                                            </tns:CountryName>
                                          </xsl:if>
                                        </tns:Country>
                                      </xsl:if>
                                    </tns:PostAddr>
                                  </xsl:for-each>
                                  <xsl:for-each select="eoPar:PartyData/eoPar:Contact/ns2:Locator/ns2:Phone">
                                    <tns:Phone>
                                      <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                                      <xsl:if test="ns2:AreaCode/text()">
                                        <tns:AreaCode>
                                          <xsl:value-of select="ns2:AreaCode"/>
                                        </tns:AreaCode>
                                      </xsl:if>
                                      <xsl:if test="ns2:PhoneNum/text()">
                                        <tns:PhoneNum>
                                          <xsl:value-of select="ns2:PhoneNum"/>
                                        </tns:PhoneNum>
                                      </xsl:if>
                                      <xsl:if test="ns2:PhoneType/text()">
                                        <tns:PhoneType>
                                          <xsl:value-of select="ns2:PhoneType"/>
                                        </tns:PhoneType>
                                      </xsl:if>
                                    </tns:Phone>
                                  </xsl:for-each>
                                </tns:Locator>
                              </xsl:if>
                            </tns:Contact>
                          </xsl:if>
                          <xsl:if test="eoPar:PartyData/eoPar:Nationality/text()">
                            <tns:Nationality>
                              <xsl:value-of select="eoPar:PartyData/eoPar:Nationality"/>
                            </tns:Nationality>
                          </xsl:if>
                          <xsl:if test="eoPar:PartyData/eoPar:IssuedIdent">
                            <tns:IssuedIdent>
                              <tns:Ident>
                                <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                                <xsl:if test="eoPar:PartyData/eoPar:IssuedIdent/eoPar:Ident/eoPar:IssuedIdentValue/text()">
                                  <tns:IssuedIdentValue>
                                    <xsl:value-of select="eoPar:PartyData/eoPar:IssuedIdent/eoPar:Ident/eoPar:IssuedIdentValue"/>
                                  </tns:IssuedIdentValue>
                                </xsl:if>                              
                              </tns:Ident>
                            </tns:IssuedIdent>
                          </xsl:if>                          
                        </tns:PartyData>
                      </xsl:if>
                      <xsl:if test="eoPar:PartyKey">
                        <tns:PartyKey>
                          <xsl:if test="eoPar:PartyKey/eoPar:PartyId/text()">
                            <tns:PartyId>
                              <xsl:value-of select="eoPar:PartyKey/eoPar:PartyId"/>
                            </tns:PartyId>
                          </xsl:if>
                          <xsl:if test="eoPar:PartyKey/eoPar:PartyType/text()">
                            <tns:PartyType>
                              <xsl:value-of select="eoPar:PartyKey/eoPar:PartyType"/>
                            </tns:PartyType>
                          </xsl:if>
                        </tns:PartyKey>
                      </xsl:if>
                      <xsl:if test="eoPar:PEPData">
                        <tns:PEPData>
                          <xsl:if test="eoPar:PEPData/eoPar:GovEntity/text()">
                            <tns:GovEntity>
                              <xsl:value-of select="eoPar:PEPData/eoPar:GovEntity"/>
                            </tns:GovEntity>
                          </xsl:if>
                          <xsl:if test="eoPar:PEPData/eoPar:GovRelated/text()">
                            <tns:GovRelated>
                              <xsl:value-of select="eoPar:PEPData/eoPar:GovRelated"/>
                            </tns:GovRelated>
                          </xsl:if>
                          <xsl:if test="eoPar:PEPData/eoPar:IsPEP/text()">
                            <tns:IsPEP>
                              <xsl:value-of select="eoPar:PEPData/eoPar:IsPEP"/>
                            </tns:IsPEP>
                          </xsl:if>
                          <xsl:if test="eoPar:PEPData/eoPar:OrgIntBelong/text()">
                            <tns:OrgIntBelong>
                              <xsl:value-of select="eoPar:PEPData/eoPar:OrgIntBelong"/>
                            </tns:OrgIntBelong>
                          </xsl:if>
                          <xsl:for-each select="eoPar:PEPData/eoPar:PEPRelated">
                            <tns:PEPRelated>
                              <xsl:if test="eoPar:Country">
                                <tns:Country>
                                  <xsl:if test="eoPar:Country/ns2:CountryCode/text()">
                                    <appoptcommon:CountryCode>
                                      <xsl:value-of select="eoPar:Country/ns2:CountryCode"/>
                                    </appoptcommon:CountryCode>
                                  </xsl:if>
                                  <xsl:if test="eoPar:Country/ns2:CountryName/text()">
                                    <appoptcommon:CountryName>
                                      <xsl:value-of select="eoPar:Country/ns2:CountryName"/>
                                    </appoptcommon:CountryName>
                                  </xsl:if>
                                </tns:Country>
                              </xsl:if>
                              <!-- Se eliminan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                              <!--xsl:if test="eoPar:PersonData">
                                <tns:PersonData>
                                  <xsl:if test="eoPar:PersonData/eoPar:Nationality/text()">
                                    <tns:Nationality>
                                      <xsl:value-of select="eoPar:PersonData/eoPar:Nationality"/>
                                    </tns:Nationality>
                                  </xsl:if>
                                  <xsl:if test="eoPar:PersonData/eoPar:PersonName">
                                    <tns:PersonName>
                                      <xsl:if test="eoPar:PersonData/eoPar:PersonName/eoPar:FullName">
                                        <tns:FullName>
                                          <xsl:value-of select="eoPar:PersonData/eoPar:PersonName/eoPar:FullName"/>
                                        </tns:FullName>
                                      </xsl:if>
                                    </tns:PersonName>
                                  </xsl:if>
                                </tns:PersonData>
                              </xsl:if>
                              <xsl:if test="eoPar:PublicPos/text()">
                                <tns:PublicPos>
                                  <xsl:value-of select="eoPar:PublicPos"/>
                                </tns:PublicPos>
                              </xsl:if>
                              <xsl:if test="eoPar:RelType/text()">
                                <tns:RelType>
                                  <xsl:value-of select="eoPar:RelType"/>
                                </tns:RelType>
                              </xsl:if-->
                            </tns:PEPRelated>
                          </xsl:for-each>
                        </tns:PEPData>
                      </xsl:if>
                      <xsl:if test="eoPar:PersonName">
                        <tns:PersonName>
                          <xsl:if test="eoPar:PersonName/eoPar:FirstName/text()">
                            <tns:FirstName>
                              <xsl:value-of select="eoPar:PersonName/eoPar:FirstName"/>
                            </tns:FirstName>
                          </xsl:if>
                          <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                          <xsl:if test="eoPar:PersonName/eoPar:LastName/text()">
                            <tns:LastName>
                              <xsl:value-of select="eoPar:PersonName/eoPar:LastName"/>
                            </tns:LastName>
                          </xsl:if>
                          <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                          <xsl:if test="eoPar:PersonName/eoPar:SecondLastName/text()">
                            <tns:SecondLastName>
                              <xsl:value-of select="eoPar:PersonName/eoPar:SecondLastName"/>
                            </tns:SecondLastName>
                          </xsl:if>
                          <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                          <xsl:if test="eoPar:PersonName/eoPar:SecondName/text()">
                            <tns:SecondName>
                              <xsl:value-of select="eoPar:PersonName/eoPar:SecondName"/>
                            </tns:SecondName>
                          </xsl:if>
                        </tns:PersonName>
                      </xsl:if>
                      <xsl:if test="eoPar:Profession">
                        <tns:Profession>
                          <xsl:if test="eoPar:Profession/ns2:Type/text()">
                            <appoptcommon:Type>
                              <xsl:value-of select="eoPar:Profession/ns2:Type"/>
                            </appoptcommon:Type>
                          </xsl:if>
                          <xsl:if test="eoPar:Profession/ns2:Value/text()">
                            <appoptcommon:Value>
                              <xsl:value-of select="eoPar:Profession/ns2:Value"/>
                            </appoptcommon:Value>
                          </xsl:if>
                        </tns:Profession>
                      </xsl:if>
                      <!-- Se agregan por cambio solicitado por negocio, ejecucion 22-05-2018 -->
                      <xsl:if test="eoPar:Shareholding/text()">
                        <tns:Shareholding>
                          <xsl:value-of select="eoPar:Shareholding"/>
                        </tns:Shareholding>
                      </xsl:if>
                      <xsl:if test="eoPar:SharesType/ns2:Cod/text()">
                        <tns:SharesType>
                        <appoptcommon:Cod>
                          <xsl:value-of select="eoPar:SharesType/ns2:Cod"/>
                        </appoptcommon:Cod>
                      </tns:SharesType>
                      </xsl:if>                      
                      <xsl:if test="eoPar:StaffPosition/text()">
                        <tns:StaffPosition>
                          <xsl:value-of select="eoPar:StaffPosition"/>
                        </tns:StaffPosition>
                      </xsl:if>
                    </tns:Staff>
                  </xsl:for-each>
                </tns:OrgData>
              </xsl:if>
            </tns:OrgPartyInfo>
          </xsl:if>
        </tns:Party>
      </xsl:if>
      <tns:Status>
        <appoptcommon:StatusCode>
          <xsl:value-of select="/ns0:PartyStaffInqRs/ns0:Status/eoStatus:StatusCode"/>
        </appoptcommon:StatusCode>
        <xsl:choose>
          <xsl:when test="/ns0:PartyStaffInqRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc/text()">
            <appoptcommon:StatusDesc>
              <xsl:value-of select="/ns0:PartyStaffInqRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc"/>
            </appoptcommon:StatusDesc>
          </xsl:when>
          <xsl:otherwise>
            <appoptcommon:StatusDesc>
              <xsl:value-of select="/ns0:PartyStaffInqRs/ns0:Status/eoStatus:StatusDesc"/>
            </appoptcommon:StatusDesc>
          </xsl:otherwise>
        </xsl:choose>
      </tns:Status>
    </tns:PartyStaffInqRs>
  </xsl:template>
</xsl:stylesheet>
