<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.banesco.com/appopt/T24AcctAppSvc/AcctStmtInq_V1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.banesco.com/eopt/AcctStmtInq_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns3="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:eoAcctStmt="http://xmlns.banesco.com/eo/AcctStmt_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns7="http://xmlns.banesco.com/eo/Payee_V1.0"
                xmlns:eoCom="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/AcctStmtInq/AcctStmtInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctStmtInqRs" namespace="http://xmlns.banesco.com/eopt/AcctStmtInq_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/T24Acct/AcctStmtInq/AcctStmtInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctStmtInqRs" namespace="http://xmlns.banesco.com/appopt/T24AcctAppSvc/AcctStmtInq_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED MAY 23 16:44:47 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AcctStmtInqRs>
         <tns:Status>
            <appoptcommon:StatusCode>
               <xsl:value-of select="/ns0:AcctStmtInqRs/ns0:Status/eoStatus:StatusCode"/>
            </appoptcommon:StatusCode>
            <appoptcommon:StatusDesc>
               <xsl:value-of select="/ns0:AcctStmtInqRs/ns0:Status/eoStatus:StatusDesc"/>
            </appoptcommon:StatusDesc>
         </tns:Status>
         <xsl:for-each select="/ns0:AcctStmtInqRs/ns0:AcctStmt">
            <tns:AcctStmt>
               <xsl:if test="eoAcctStmt:AcctStmtInfo">
                  <tns:AcctStmtInfo>
                     <xsl:if test="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate">
                        <tns:CustomDate>
                           <xsl:if test="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate/eoCom:Day/text()">
                              <tns:Day>
                                 <xsl:value-of select="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate/eoCom:Day"/>
                              </tns:Day>
                           </xsl:if>
                           <xsl:if test="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate/eoCom:Month/text()">
                              <tns:Month>
                                 <xsl:value-of select="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate/eoCom:Month"/>
                              </tns:Month>
                           </xsl:if>
                           <xsl:if test="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate/eoCom:Year/text()">
                              <tns:Year>
                                 <xsl:value-of select="eoAcctStmt:AcctStmtInfo/eoAcctStmt:CustomDate/eoCom:Year"/>
                              </tns:Year>
                           </xsl:if>
                        </tns:CustomDate>
                     </xsl:if>
                     <xsl:if test="eoAcctStmt:AcctStmtInfo/eoAcctStmt:StmtFile/eoCom:FileURL/text()">
                        <tns:FileURL>
                           <tns:FileURL>
                              <xsl:value-of select="eoAcctStmt:AcctStmtInfo/eoAcctStmt:StmtFile/eoCom:FileURL"/>
                           </tns:FileURL>
                        </tns:FileURL>
                     </xsl:if>
                  </tns:AcctStmtInfo>
               </xsl:if>
               <xsl:if test="eoAcctStmt:AcctStmtKey/eoAcctStmt:AcctStmtId/text()">
                  <tns:AcctStmtKey>
                     <xsl:if test="eoAcctStmt:AcctStmtKey/eoAcctStmt:AcctStmtId/text()">
                        <tns:AcctStmtId>
                           <xsl:value-of select="eoAcctStmt:AcctStmtKey/eoAcctStmt:AcctStmtId"/>
                        </tns:AcctStmtId>
                     </xsl:if>
                  </tns:AcctStmtKey>
               </xsl:if>
            </tns:AcctStmt>
         </xsl:for-each>
      </tns:AcctStmtInqRs>
   </xsl:template>
</xsl:stylesheet>
