<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Evaluacion" targetNamespace="http://xmlns.bcie.com/EvaluacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:evaMO="http://www.bcie.org/EvaluacionMO"
                  xmlns:tns="http://xmlns.bcie.com/EvaluacionService"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/EvaluacionMO"
                  schemaLocation="../../Schema/EvaluacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Delete -->
  <!-- Delete -->
  <wsdl:message name="requestEliminarCuestionarioMessage">
    <wsdl:part name="request" element="evaMO:EliminarCuestionarioRequest"/>
  </wsdl:message>
  <wsdl:message name="responseEliminarCuestionarioMessage">
    <wsdl:part name="response" element="evaMO:EliminarCuestionarioResponse"/>
  </wsdl:message>
  <wsdl:portType name="EliminarCuestionarioPT">
    <!-- Delete -->
    <wsdl:operation name="EliminarCuestionario">
      <wsdl:documentation>Eliminar un cuestionario</wsdl:documentation>
      <wsdl:input message="tns:requestEliminarCuestionarioMessage"/>
      <wsdl:output message="tns:responseEliminarCuestionarioMessage"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="EliminarCuestionario12Bnd" type="tns:EliminarCuestionarioPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="EliminarCuestionario">
      <soap12:operation style="document"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
