
-------------------------------
-- Fecha: 20171201
-- Objetivo: Se reunen en un solo script los objetos a desplegar 
-------------------------------

-- 01

CREATE TABLE FENIX.TMP_ERROR_USUARIOS
(
  USUARIO_ROL  VARCHAR2(65 BYTE)
);
/

CREATE INDEX FENIX.USUARIO_ROL_ERROR_IND ON FENIX.TMP_ERROR_USUARIOS
(USUARIO_ROL);
/

CREATE TABLE FENIX.TMP_PARA_USUARIOS
(
  USUARIO_ROL  VARCHAR2(65 BYTE)
);
/

CREATE INDEX FENIX.USUARIO_ROL_IND ON FENIX.TMP_PARA_USUARIOS
(USUARIO_ROL);
/

CREATE INDEX FENIX.DESCRIPCION_IND ON FENIX.TCA_PLANTILLA_CORREO
(DESCRIPCION);

/
-- 02

create or replace TYPE T_TAGS_DEFINICION as object (
  TAG VARCHAR2(100),
VALOR  VARCHAR2 (4000));

/
-- 03

create or replace TYPE       T_TAGS AS TABLE  OF T_TAGS_DEFINICION;

/
-- 04

CREATE OR REPLACE TYPE T_BITACORA_DOCUMENTO AS OBJECT
(
	ID	NUMBER(12,0),
	ID_DOCUMENTO	NUMBER(12),
	ID_ADJUNTO	NUMBER(12),
	ESTADO	VARCHAR2(20),
	NUM_INSTANCIA	VARCHAR2(256),
	SE_HA_NOTIFICADO	NUMBER(1),
	LOGIN_USUARIO	VARCHAR2(32),
	NOMBRE_USUARIO	VARCHAR2(128),
	ID_TCA_TAREA_BPM	NUMBER(5),
	BAN_ESTATUS	NUMBER(1),
	FECHA_REGISTRO	DATE,
	DESCRIPCION	VARCHAR2(4000),
	ES_REG_ACTIVO	NUMBER(1)
);

/
