<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="MDMCostChangeListener" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AGSOABpelApplication/MDMCostChangeListener/MDMCostChangeListener" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AGSOABpelApplication/MDMCostChangeListener/MDMCostChangeListener" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MDMCostChangeListener" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="MDMCostChangeListener_plt">
      <plt:role name="MDMCostChangeListener_role">
         <plt:portType name="tns:MDMCostChangeListener_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MDMCostChangeListener" schemaLocation="../Schemas/MDMCostChangeListener_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CchEventsCollection_msg">
      <wsdl:part name="CchEventsCollection" element="top:CchEventsCollection"/>
   </wsdl:message>
   <wsdl:portType name="MDMCostChangeListener_ptt">
      <wsdl:operation name="receive">
         <wsdl:input message="tns:CchEventsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
