<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateSupplierMessage" name="RMSCreateSupplierMessage-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSCreateSupplierMessage.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateSupplierMessage"/>
    <wsdl:binding name="RMSCreateSupplierMessage_ptt-binding" type="rms:RMSCreateSupplierMessage_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateSupplierMessage">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSCreateSupplierMessage">
            <soap:operation soapAction="RMSCreateSupplierMessage"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>