<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/RMSCostChange/CostChangeFindDetailsByIDBS" name="CostChangeFindDetailsByIDBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CostChangeFindDetailsByIDBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/RMSCostChange/CostChangeFindDetailsByIDBS"/>
    <wsdl:binding name="CostChangeFindDetailsByIDBS_ptt-binding" type="cos:CostChangeFindDetailsByIDBS_ptt" xmlns:cos="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/RMSCostChange/CostChangeFindDetailsByIDBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CostChangeFindDetailsByIDBSSelect">
            <soap:operation soapAction="CostChangeFindDetailsByIDBSSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>