<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/UpsertTransferencia_DB" name="UpsertTransferencia_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UpsertTransferencia_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/UpsertTransferencia_DB"/>
    <wsdl:binding name="UpsertTransferencia_DB_ptt-binding" type="ups:UpsertTransferencia_DB_ptt" xmlns:ups="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/UpsertTransferencia_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="UpsertTransferencia_DB">
            <soap:operation soapAction="UpsertTransferencia_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>