<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CierreFideicomisoProcess" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/CierreFideicomisoProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:types>
<xsd:schema>
<xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CierreFideicomisoProcess" schemaLocation="../../Schema/PA14/CierreFideicomisoProcess.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="InicioCierreFideicomiso">
<wsdl:part name="parameters" element="tns:InicioCierreFideicomiso"/>
</wsdl:message>
<wsdl:message name="FinCierreFideicomiso">
<wsdl:part name="parameters" element="tns:FinCierreFideicomiso"/>
</wsdl:message>
<wsdl:portType name="CierreFideicomisoProcessPortType">
<wsdl:operation name="InicioCierreFideicomiso">
<wsdl:input message="tns:InicioCierreFideicomiso"/>
</wsdl:operation>
<wsdl:operation name="FinCierreFideicomiso">
<wsdl:input message="tns:FinCierreFideicomiso"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="CierreFideicomisoProcessBinding" type="tns:CierreFideicomisoProcessPortType">
<wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="InicioCierreFideicomiso">
<wsdlsoap:operation style="document" soapAction="InicioCierreFideicomiso"/>
<wsdl:input>
<wsdlsoap:body use="literal"/>
</wsdl:input>
</wsdl:operation>
<wsdl:operation name="FinCierreFideicomiso">
<wsdlsoap:operation style="document" soapAction="FinCierreFideicomiso"/>
<wsdl:input>
<wsdlsoap:body use="literal"/>
</wsdl:input>
</wsdl:operation>
</wsdl:binding>
<plnk:partnerLinkType name="CierreFideicomisoProcessPortTypePartnerLinkType">
<plnk:role name="CierreFideicomisoProcessPortTypeProvider">
<plnk:portType name="tns:CierreFideicomisoProcessPortType"/>
</plnk:role>
</plnk:partnerLinkType>
</wsdl:definitions>
