<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/ConsultarTransferenciasRecursosById_DB" name="ConsultarTransferenciasRecursosById_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarTransferenciasRecursosById_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/ConsultarTransferenciasRecursosById_DB"/>
    <wsdl:binding name="ConsultarTransferenciasRecursosById_DB_ptt-binding" type="con:ConsultarTransferenciasRecursosById_DB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/ConsultarTransferenciasRecursosById_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarTransferenciasRecursosById_DB">
            <soap:operation soapAction="ConsultarTransferenciasRecursosById_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>