<wsdl:definitions name="ConsultarClienteProcesoDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClienteProcesoDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClienteProcesoDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarClienteProcesoDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarClienteProcesoDB_plt">
    <plt:role name="ConsultarClienteProcesoDB_role">
      <plt:portType name="tns:ConsultarClienteProcesoDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarClienteProcesoDB" schemaLocation="../XSD/ConsultarClienteProcesoDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarClienteProcesoDBSelect_inputParameters">
        <wsdl:part name="ConsultarClienteProcesoDBSelect_inputParameters" element="top:ConsultarClienteProcesoDBSelect_idCliente_idProcesoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="TreClienteProcesoBpmCollection_msg">
        <wsdl:part name="TreClienteProcesoBpmCollection" element="top:TreClienteProcesoBpmCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarClienteProcesoDB_ptt">
        <wsdl:operation name="ConsultarClienteProcesoDBSelect">
            <wsdl:input message="tns:ConsultarClienteProcesoDBSelect_inputParameters"/>
            <wsdl:output message="tns:TreClienteProcesoBpmCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>