package org.bcie.fenix.common.model.vo.detalleop.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 24 11:26:59 CDT 2021
// ---------------------------------------------------------------------
public interface GetDetalleOperacionVO extends ViewObject {
    boolean obtenerDetalleOperacionById(Integer idOperacion);
}

