<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ObtenerAvisoCobro/ObtenerAvisoCobro" name="ObtenerAvisoCobro_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ObtenerAvisoCobro.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ObtenerAvisoCobro/ObtenerAvisoCobro"/>
    <wsdl:binding name="ObtenerAvisoCobro_ptt-binding" type="obt:ObtenerAvisoCobro_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ObtenerAvisoCobro/ObtenerAvisoCobro">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerAvisoCobro">
            <soap:operation soapAction="ObtenerAvisoCobro"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>