<wsdl:definitions
     name="ConsultarFondoById_BS"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarFondoById_BS"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarFondoById_BS"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarFondoById_BS"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarFondoById_BS_plt" >
    <plt:role name="ConsultarFondoById_BS_role" >
      <plt:portType name="tns:ConsultarFondoById_BS_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarFondoById_BS"
                schemaLocation="../XSD/ConsultarFondoById_BS.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarFondoById_BSInput_msg">
        <wsdl:part name="ConsultarFondoById_BSInput_msg" element="db:ConsultarFondoById_BSInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarFondoById_BSOutputCollection_msg">
        <wsdl:part name="ConsultarFondoById_BSOutputCollection" element="db:ConsultarFondoById_BSOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarFondoById_BS_ptt">
        <wsdl:operation name="ConsultarFondoById_BS">
            <wsdl:input message="tns:ConsultarFondoById_BSInput_msg"/>
            <wsdl:output message="tns:ConsultarFondoById_BSOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
