<wsdl:definitions
     name="ConsultarLineaCreditoByIdLineaCredito"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/PropagarLineaCredito/ConsultarLineaCreditoByIdLineaCredito"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/PropagarLineaCredito/ConsultarLineaCreditoByIdLineaCredito"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLineaCreditoByIdLineaCredito"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarLineaCreditoByIdLineaCredito_plt" >
    <plt:role name="ConsultarLineaCreditoByIdLineaCredito_role" >
      <plt:portType name="tns:ConsultarLineaCreditoByIdLineaCredito_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLineaCreditoByIdLineaCredito" schemaLocation="../XSD/ConsultarLineaCreditoByIdLineaCredito.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarLineaCreditoByIdLineaCreditoInput_msg">
        <wsdl:part name="ConsultarLineaCreditoByIdLineaCreditoInput_msg" element="db:ConsultarLineaCreditoByIdLineaCreditoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarLineaCreditoByIdLineaCreditoOutputCollection_msg">
        <wsdl:part name="ConsultarLineaCreditoByIdLineaCreditoOutputCollection" element="db:ConsultarLineaCreditoByIdLineaCreditoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarLineaCreditoByIdLineaCredito_ptt">
        <wsdl:operation name="ConsultarLineaCreditoByIdLineaCredito">
            <wsdl:input message="tns:ConsultarLineaCreditoByIdLineaCreditoInput_msg"/>
            <wsdl:output message="tns:ConsultarLineaCreditoByIdLineaCreditoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
