<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/consultarCodigoCliente_DB" name="consultarCodigoCliente_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="consultarCodigoCliente_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/consultarCodigoCliente_DB"/>
    <wsdl:binding name="consultarCodigoCliente_DB_ptt-binding" type="con:consultarCodigoCliente_DB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/consultarCodigoCliente_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="consultarCodigoCliente_DB">
            <soap:operation soapAction="consultarCodigoCliente_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>