<wsdl:definitions name="ValidarEnvioNotifSupervTCC" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnvioNotifSupervTCC" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnvioNotifSupervTCC" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidarEnvioNotifSupervTCC" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ValidarEnvioNotifSupervTCC_plt">
    <plt:role name="ValidarEnvioNotifSupervTCC_role">
      <plt:portType name="tns:ValidarEnvioNotifSupervTCC_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidarEnvioNotifSupervTCC" schemaLocation="../XSD/ValidarEnvioNotifSupervTCC.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="ValidarEnvioNotifSupervTCCRequest_msg">
        <wsdl:part name="ValidarEnvioNotifSupervTCCRequest_msg" element="db:ValidarEnvioNotifSupervTCCRequest"/>
    </wsdl:message>
    <wsdl:message name="ValidarEnvioNotifSupervTCCResponse_msg">
        <wsdl:part name="ValidarEnvioNotifSupervTCCResponse_msg" element="db:ValidarEnvioNotifSupervTCCResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarEnvioNotifSupervTCC_ptt">
        <wsdl:operation name="ValidarEnvioNotifSupervTCC">
            <wsdl:input message="tns:ValidarEnvioNotifSupervTCCRequest_msg"/>
            <wsdl:output message="tns:ValidarEnvioNotifSupervTCCResponse_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>