<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultarSaldoLineaSAD" targetNamespace="http://www.bcie.org/ConsultarSaldoLineaSAD" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.bcie.org/ConsultarSaldoLineaSAD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ConsultarSaldoLinea_SB">
      <plnk:role name="ConsultarSaldoLinea_PT" portType="tns:ConsultarSaldoLinea_PT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bcie.org/ConsultarSaldoLineaSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/ADAPTER/ConsultarSaldoLineaSAD.wsdl"/>
</wsdl:definitions>
