<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearBitacora" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearBitacora" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:regBitMO="http://www.bcie.org/CrearBitacoraMO">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/CrearBitacoraMO" schemaLocation="../Schema/CrearBitacoraMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="CrearBitacoraRequestMessage">
    <part name="CrearBitacoraRequest" element="regBitMO:CrearBitacoraRequest"/>
  </message>
  <message name="CrearBitacoraResponseMessage">
    <part name="CrearBitacoraResponse" element="regBitMO:CrearBitacoraResponse"/>
  </message>
  <portType name="CrearBitacoraPT">
    <operation name="crearBitacora">
      <input message="tns:CrearBitacoraRequestMessage"/>
      <output message="tns:CrearBitacoraResponseMessage"/>
    </operation>
  </portType>
  <binding name="CrearBitacoraPT12Bnd" type="tns:CrearBitacoraPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearBitacora">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CrearBitacora/crearBitacora"/>
      <input>
        <soap12:body use="literal" parts="CrearBitacoraRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="CrearBitacoraResponse"/>
      </output>
    </operation>
  </binding>
</definitions>