<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/SolicitudAprobacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO"
                  xmlns:tns="http://xmlns.bcie.com/SolicitudAprobacionService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Read -->
  <wsdl:message name="requestConsultarUsuarioReunionMessage">
    <wsdl:part name="request" element="solAproMO:ConsultarUsuarioReunionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseConsultarUsuarioReunionMessage">
    <wsdl:part name="response" element="solAproMO:ConsultarUsuarioReunionResponse"/>
  </wsdl:message>

  <wsdl:portType name="ConsultarUsuarioReunionPT">
    <wsdl:operation name="ConsultarUsuarioReunion">
      <wsdl:documentation></wsdl:documentation>
      <wsdl:input message="tns:requestConsultarUsuarioReunionMessage"/>
      <wsdl:output message="tns:responseConsultarUsuarioReunionMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarUsuarioReunionBnd" type="tns:ConsultarUsuarioReunionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarUsuarioReunion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/SolicitudAprobacionService/ConsultarUsuarioReunion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>