<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoClienteDB" name="ConsultarBitacoraProcesoCliente_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarBitacoraProcesoClienteDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoClienteDB"/>
    <wsdl:binding name="ConsultarBitacoraProcesoClienteDB_ptt-binding" type="con:ConsultarBitacoraProcesoClienteDB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoClienteDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarBitacoraProcesoClienteDB">
            <soap:operation soapAction="ConsultarBitacoraProcesoClienteDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>