package org.bcie.fenix.common.model.vo.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 14 13:45:02 CDT 2015
// ---------------------------------------------------------------------
public interface OperacionesAsociadasVO extends ViewObject {
    void asociarOperaciones(Row row);

    void limpiarAsociarOperaciones();
}

