<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConfigurarSolicitudAprobacion/ConsultarTreComiteRol" name="ConsultarTreComiteRol_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarTreComiteRol.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConfigurarSolicitudAprobacion/ConsultarTreComiteRol"/>
    <wsdl:binding name="ConsultarTreComiteRol_ptt-binding" type="con:ConsultarTreComiteRol_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConfigurarSolicitudAprobacion/ConsultarTreComiteRol">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarTreComiteRol">
            <soap:operation soapAction="ConsultarTreComiteRol"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>