<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/EliminarContacto/QueryEliminaContactoClienteService" name="QueryEliminaContactoClienteServiceDB_bs-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../WSDL/QueryEliminaContactoClienteService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/EliminarContacto/QueryEliminaContactoClienteService"/>
    <wsdl:binding name="QueryEliminaContactoClienteService_ptt-binding" type="quer:QueryEliminaContactoClienteService_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/EliminarContacto/QueryEliminaContactoClienteService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryEliminaContactoClienteService">
            <soap:operation soapAction="QueryEliminaContactoClienteService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>