<wsdl:definitions name="ConsultarTreTermino_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarTreTermino_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarTreTermino_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreTermino_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTreTermino_DB_plt">
    <plt:role name="ConsultarTreTermino_DB_role">
      <plt:portType name="tns:ConsultarTreTermino_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreTermino_DB"
                schemaLocation="../XSD/ConsultarTreTermino_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTreTermino_DBInput_msg">
        <wsdl:part name="ConsultarTreTermino_DBInput_msg" element="db:ConsultarTreTermino_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTreTermino_DBOutputCollection_msg">
        <wsdl:part name="ConsultarTreTermino_DBOutputCollection" element="db:ConsultarTreTermino_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTreTermino_DB_ptt">
        <wsdl:operation name="ConsultarTreTermino_DB">
            <wsdl:input message="tns:ConsultarTreTermino_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarTreTermino_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>