<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDAModifySupplierProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Suppliers/JDAModifySupplierProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N4="http://mx.agarcia.ea/Capabilities/Core/Suppliers/JDAModifySupplierProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="JDAModifySupplierProcessPXY">
      <plnk:role name="ModifySupplierPType" portType="WL5G3N4:ModifySupplierPType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/Suppliers/JDAModifySupplierProcess" location="http://192.1.50.179:7003/Capabilities/Core/Supplier/SupplierEntitySvc/PS/JDAModifySupplierProcessPXY?wsdl"/>
</wsdl:definitions>
