<wsdl:definitions
     name="ConsultarFuente"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project13/ConsultarFuente"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project13/ConsultarFuente"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarFuente"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarFuente_plt" >
    <plt:role name="ConsultarFuente_role" >
      <plt:portType name="tns:ConsultarFuente_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarFuente" schemaLocation="../XSD/ConsultarFuente.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarFuenteInput_msg">
        <wsdl:part name="ConsultarFuenteInput_msg" element="db:ConsultarFuenteInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarFuenteOutputCollection_msg">
        <wsdl:part name="ConsultarFuenteOutputCollection" element="db:ConsultarFuenteOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarFuente_ptt">
        <wsdl:operation name="ConsultarFuente">
            <wsdl:input message="tns:ConsultarFuenteInput_msg"/>
            <wsdl:output message="tns:ConsultarFuenteOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
