<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/GestionCobroMO" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/GestionCobroMO" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/GestionCobroMO"
                  schemaLocation="../../Schema/GestionCobroMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="GenerarAvisoCobroRequestMessage">
    <part name="GenerarAvisoCobroRequest" element="tns:GenerarAvisoCobroRequest"/>
  </message>
  <message name="GenerarAvisoCobroResponseMessage">
    <part name="GenerarAvisoCobroResponse" element="tns:GenerarAvisoCobroResponse"/>
  </message>
  <portType name="GenerarAvisoCobroPT">
    <operation name="generarAvisoCobro">
      <input message="tns:GenerarAvisoCobroRequestMessage"/>
      <output message="tns:GenerarAvisoCobroResponseMessage"/>
    </operation>
  </portType>
  <binding name="GenerarAvisoCobroPT12Bnd" type="tns:GenerarAvisoCobroPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="generarAvisoCobro">
      <soap12:operation style="document" soapAction="http://www.bcie.org/GestionCobroMO/generarAvisoCobro"/>
      <input>
        <soap12:body use="literal" parts="GenerarAvisoCobroRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="GenerarAvisoCobroResponse"/>
      </output>
    </operation>
  </binding>
</definitions>