<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Usuario" targetNamespace="http://xmlns.bcie.com/UsuarioService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:usMO="http://www.bcie.org/UsuarioMO"
                  xmlns:tns="http://xmlns.bcie.com/UsuarioService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/UsuarioMO" schemaLocation="../Schema/UsuarioMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestAutenticarUsuarioMessage">
    <wsdl:part name="request" element="usMO:AutenticarUsuarioRequest"/>
  </wsdl:message>
  <wsdl:message name="responseAutenticarUsuarioMessage">
    <wsdl:part name="response" element="usMO:AutenticarUsuarioResponse"/>
  </wsdl:message>
  <wsdl:portType name="AutenticarUsuarioPT">
    <wsdl:operation name="autenticarUsuario">
      <wsdl:input message="tns:requestAutenticarUsuarioMessage"/>
      <wsdl:output message="tns:responseAutenticarUsuarioMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AutenticarUsuario12Bnd" type="tns:AutenticarUsuarioPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="autenticarUsuario">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/UsuarioService/autenticarUsuario"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
