<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/RMSViewsSPReference" name="RMSViewsSPReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSViewsSPReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/RMSViewsSPReference"/>
    <wsdl:binding name="RMSViewsSPReference_ptt-binding" type="rms:RMSViewsSPReference_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/RMSViewsSPReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSViewsSPReference">
            <soap:operation soapAction="RMSViewsSPReference"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>