<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ImplementacionPCT"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ImplementacionPCT"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ImplementacionPCT"
     xmlns:inp1="http://www.bcie.org/ImplementacionPctMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/ImplementacionPctMO" schemaLocation="../Schema/ImplementacionPctMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="InciaProcesoLote_In" element="inp1:procesoLoteRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="InciaProcesoLote_Out" element="inp1:procesoLoteResponse"/>
    </wsdl:message>
    <wsdl:portType name="ImplementacionPCT_ptt">
        <wsdl:operation name="InciaProcesoLote">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ImplementacionPCT_bind" type="tns:ImplementacionPCT_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="InciaProcesoLote">
            <soap12:operation style="document" soapAction="InciaProcesoLote" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/InciaProcesoLote"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/InciaProcesoLote"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
