<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/InsertarGenerarDetalleGestionCobro/InsertarGenerarDetalleGestionCobro" name="InsertarGenerarDetalleGestionCobro_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="InsertarGenerarDetalleGestionCobro.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/InsertarGenerarDetalleGestionCobro/InsertarGenerarDetalleGestionCobro"/>
    <wsdl:binding name="InsertarGenerarDetalleGestionCobro_ptt-binding" type="ins:InsertarGenerarDetalleGestionCobro_ptt" xmlns:ins="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/InsertarGenerarDetalleGestionCobro/InsertarGenerarDetalleGestionCobro">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>