<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CreateColorProcess" targetNamespace="http://xmlns.oracle.com/RetailOperMK/CreateColorProcess/CreateColorProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/RetailOperMK/CreateColorProcess/CreateColorProcess" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateColorEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateColorEntity" schemaLocation="../Schemas/CreateColorEntitySchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CreateColorProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:createColorRequest"/>
   </wsdl:message>
   <wsdl:message name="CreateColorProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:createColorResponse"/>
   </wsdl:message>
   <wsdl:portType name="CreateColorProcess">
      <wsdl:operation name="create">
         <wsdl:input message="client:CreateColorProcessRequestMessage"/>
         <wsdl:output message="client:CreateColorProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="CreateColorProcess">
      <plnk:role name="CreateColorProcessProvider" portType="client:CreateColorProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
