<wsdl:definitions name="ConsultarContrapartesTermino_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContrapartesTermino_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContrapartesTermino_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContrapartesTermino_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarContrapartesTermino_DB_plt">
    <plt:role name="ConsultarContrapartesTermino_DB_role">
      <plt:portType name="tns:ConsultarContrapartesTermino_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContrapartesTermino_DB" schemaLocation="../XSD/ConsultarContrapartesTermino_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContrapartesTermino_DBInput_msg">
        <wsdl:part name="ConsultarContrapartesTermino_DBInput_msg" element="db:ConsultarContrapartesTermino_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarContrapartesTermino_DBOutputCollection_msg">
        <wsdl:part name="ConsultarContrapartesTermino_DBOutputCollection" element="db:ConsultarContrapartesTermino_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContrapartesTermino_DB_ptt">
        <wsdl:operation name="ConsultarContrapartesTermino_DB">
            <wsdl:input message="tns:ConsultarContrapartesTermino_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarContrapartesTermino_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>