<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarMomentoCobroSAD"
     targetNamespace="http://www.bcie.org/ConsultarMomentoCobroSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ConsultarMomentoCobroSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarMomentoCobro_SB">
        <plnk:role name="ConsultarMomentoCobro_PT" portType="tns:ConsultarMomentoCobro_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ConsultarMomentoCobroSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ConsultarMomentoCobroSAD.wsdl"/>
</wsdl:definitions>
