<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://xmlns.banesco.com/eopt/AcctTrnInq_V1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.banesco.com/appopt/TCIBAcctAppSvc/AcctTrnInq_V1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns4="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Party_V1.0" xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0" xmlns:eoTrn="http://xmlns.banesco.com/eo/Trn_V1.0" xmlns:ns1="http://xmlns.banesco.com/appopt/AOptCommon_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Banking_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:eoMsgHdr="http://xmlns.banesco.com/eo/MsgHdr_V1.0" xmlns:ns6="http://xmlns.banesco.com/eo/Card_V1.0" xmlns:eoCom="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Payee_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/AcctTrnInq/AcctTrnInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctTrnInqRs" namespace="http://xmlns.banesco.com/eopt/AcctTrnInq_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/TCIBAcct/AcctTrnInq/AcctTrnInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctTrnInqRs" namespace="http://xmlns.banesco.com/appopt/TCIBAcctAppSvc/AcctTrnInq_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE DEC 12 14:13:34 COT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:AcctTrnInqRs>
         <xsl:if test="/ns0:AcctTrnInqRs/ns0:RecCtrl">
            <tns:RecCtrlOut>
               <ns1:EndRecNum>
                  <xsl:value-of select="/ns0:AcctTrnInqRs/ns0:RecCtrl/EndRecNum"/>
               </ns1:EndRecNum>
               <ns1:LastRec>
                  <xsl:value-of select="/ns0:AcctTrnInqRs/ns0:RecCtrl/LastRec"/>
               </ns1:LastRec>
            </tns:RecCtrlOut>
         </xsl:if>
         <tns:Status>
            <tns:StatusCode>
               <xsl:value-of select="/ns0:AcctTrnInqRs/ns0:Status/eoStatus:StatusCode"/>
            </tns:StatusCode>
            <tns:StatusDesc>
               <xsl:value-of select="/ns0:AcctTrnInqRs/ns0:Status/eoStatus:StatusDesc"/>
            </tns:StatusDesc>
         </tns:Status>
         <xsl:for-each select="/ns0:AcctTrnInqRs/ns0:Trn">
            <tns:Trn>
               <xsl:if test="eoTrn:CurBalance/text()">
                  <tns:CurBalance>
                     <xsl:value-of select="eoTrn:CurBalance"/>
                  </tns:CurBalance>
               </xsl:if>
               <xsl:if test="eoTrn:Desc/text()">
                  <tns:Desc>
                     <xsl:value-of select="eoTrn:Desc"/>
                  </tns:Desc>
               </xsl:if>
               <xsl:if test="eoTrn:EffDt/text()">
                  <tns:EffDt>
                     <xsl:value-of select="eoTrn:EffDt"/>
                  </tns:EffDt>
               </xsl:if>
               <xsl:if test="eoTrn:TrnRef/text()">
                  <tns:TrnRef>
                     <xsl:value-of select="eoTrn:TrnRef"/>
                  </tns:TrnRef>
               </xsl:if>
               <xsl:if test="eoTrn:TrnSubType/text()">
                  <tns:TrnSubType>
                     <xsl:value-of select="eoTrn:TrnSubType"/>
                  </tns:TrnSubType>
               </xsl:if>
               <xsl:if test="eoTrn:TrnType/eoCom:Type/text()">
                  <tns:TrnType>
                     <tns:Type>
                        <xsl:value-of select="eoTrn:TrnType/eoCom:Type"/>
                     </tns:Type>
                  </tns:TrnType>
               </xsl:if>
               <xsl:if test="eoTrn:TotalCurAmt/eoCom:Amt/text()">
                  <tns:TotalCurAmt>
                     <tns:Amt>
                        <xsl:value-of select="eoTrn:TotalCurAmt/eoCom:Amt"/>
                     </tns:Amt>
                  </tns:TotalCurAmt>
               </xsl:if>
            </tns:Trn>
         </xsl:for-each>
      </tns:AcctTrnInqRs>
   </xsl:template>
</xsl:stylesheet>