<wsdl:definitions name="ConsultarCondicionDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarCondicionDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarCondicionDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarCondicionDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarCondicionDB_plt">
    <plt:role name="ConsultarCondicionDB_role">
      <plt:portType name="tns:ConsultarCondicionDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarCondicionDB" schemaLocation="../XSD/ConsultarCondicionDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarCondicionDBSelect_inputParameters">
        <wsdl:part name="ConsultarCondicionDBSelect_inputParameters" element="top:ConsultarCondicionDBSelect_idCondicionInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CondicionCollection_msg">
        <wsdl:part name="CondicionCollection" element="top:CondicionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCondicionDB_ptt">
        <wsdl:operation name="ConsultarCondicionDBSelect">
            <wsdl:input message="tns:ConsultarCondicionDBSelect_inputParameters"/>
            <wsdl:output message="tns:CondicionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>