<wsdl:definitions name="ConsultarPlantillaByProceso" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarPlantillaByProceso" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarPlantillaByProceso" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarPlantillaByProceso" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarPlantillaByProceso_plt">
    <plt:role name="ConsultarPlantillaByProceso_role">
      <plt:portType name="tns:ConsultarPlantillaByProceso_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarPlantillaByProceso" schemaLocation="../XSD/ConsultarPlantillaByProceso.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarPlantillaByProcesoInput_msg">
        <wsdl:part name="ConsultarPlantillaByProcesoInput_msg" element="db:ConsultarPlantillaByProcesoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarPlantillaByProcesoOutputCollection_msg">
        <wsdl:part name="ConsultarPlantillaByProcesoOutputCollection" element="db:ConsultarPlantillaByProcesoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarPlantillaByProceso_ptt">
        <wsdl:operation name="ConsultarPlantillaByProceso">
            <wsdl:input message="tns:ConsultarPlantillaByProcesoInput_msg"/>
            <wsdl:output message="tns:ConsultarPlantillaByProcesoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>