<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="oneCaseDb" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ItemCataloApp/ItemDiffTranslate/oneCaseDb" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ItemCataloApp/ItemDiffTranslate/oneCaseDb" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="oneCaseDb_plt">
      <plt:role name="oneCaseDb_role">
         <plt:portType name="tns:oneCaseDb_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" schemaLocation="../Schemas/oneCaseDb_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="oneCaseDbSelect_inputParameters">
      <wsdl:part name="oneCaseDbSelect_inputParameters" element="top:oneCaseDbSelect_idC1_appCodeC1_catDetC1_parIdC1_parCatIdC1_targetAppCodeC1InputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmItemsDiffsCollection_msg">
      <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
   </wsdl:message>
   <wsdl:portType name="oneCaseDb_ptt">
      <wsdl:operation name="oneCaseDbSelect">
         <wsdl:input message="tns:oneCaseDbSelect_inputParameters"/>
         <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
