-- Declare package containing conversion functions between SQL and PL/SQL types
CREATE OR REPLACE PACKAGE BPEL_RPM_CREAREVENT AS
   FUNCTION xx_cargar_cambio_de_precios$c (I_ID INTEGER,
	I_DESCRIPCION VARCHAR2,
	I_TIPO CHAR,
	I_RAZON CHAR,
	I_NIVEL CHAR,
	I_BASE CHAR,
	I_FECHA_INICIAL DATE,
	I_FECHA_FINAL DATE,
	I_DIAS INTEGER,
	I_PRECIO NUMBER,
	I_PCT NUMBER,
	I_CANT_CAMBIO NUMBER,
	I_ESTILO VARCHAR2,
	I_SKU VARCHAR2,
	I_TIENDA INTEGER,
	I_FIN_DE_ARCHIVO INTEGER,
	O_ERROR_MESSAGE OUT VARCHAR2
	) RETURN INTEGER;
END BPEL_RPM_CREAREVENT;
/
show errors
CREATE OR REPLACE PACKAGE BODY BPEL_RPM_CREAREVENT IS

   FUNCTION xx_cargar_cambio_de_precios$c (I_ID INTEGER,
	I_DESCRIPCION VARCHAR2,
	I_TIPO CHAR,
	I_RAZON CHAR,
	I_NIVEL CHAR,
	I_BASE CHAR,
	I_FECHA_INICIAL DATE,
	I_FECHA_FINAL DATE,
	I_DIAS INTEGER,
	I_PRECIO NUMBER,
	I_PCT NUMBER,
	I_CANT_CAMBIO NUMBER,
	I_ESTILO VARCHAR2,
	I_SKU VARCHAR2,
	I_TIENDA INTEGER,
	I_FIN_DE_ARCHIVO INTEGER,
	O_ERROR_MESSAGE OUT VARCHAR2
	) RETURN INTEGER IS
 RETURN_ INTEGER;
 I_FIN_DE_ARCHIVO_ BOOLEAN;
   BEGIN
 I_FIN_DE_ARCHIVO_ := SYS.SQLJUTL.INT2BOOL(I_FIN_DE_ARCHIVO);
      RETURN_ := SYS.SQLJUTL.BOOL2INT(XXRMS.XX_CARGAR_CAMBIO_DE_PRECIOS.CREAR_EVENTO(I_ID,
	I_DESCRIPCION,
	I_TIPO,
	I_RAZON,
	I_NIVEL,
	I_BASE,
	I_FECHA_INICIAL,
	I_FECHA_FINAL,
	I_DIAS,
	I_PRECIO,
	I_PCT,
	I_CANT_CAMBIO,
	I_ESTILO,
	I_SKU,
	I_TIENDA,
	I_FIN_DE_ARCHIVO_,
	O_ERROR_MESSAGE
	));
      return RETURN_;
   END xx_cargar_cambio_de_precios$c;

END BPEL_RPM_CREAREVENT;
/
show errors
exit
