<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://xmlns.banesco.com/eopt/AcctLoanCollateralAdd_V1.0"
                xmlns:tns="http://xmlns.banesco.com/appopt/WFAcctLoanAppSvc/AcctLoanCollateralAdd_V1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns3="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:eoCollateral="http://xmlns.banesco.com/eo/Collateral_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanCollateralAdd/AcctLoanCollateralAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctLoanCollateralAddRs"
                                       namespace="http://xmlns.banesco.com/eopt/AcctLoanCollateralAdd_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/WFAcctLoan/AcctLoanCollateralAdd/AcctLoanCollateralAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctLoanCollateralAddRs"
                                       namespace="http://xmlns.banesco.com/appopt/WFAcctLoanAppSvc/AcctLoanCollateralAdd_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU MAY 24 08:57:27 GMT-05:00 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AcctLoanCollateralAddRs>
      <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:AcctKey">
        <tns:AcctKey>
          <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:AcctKey/eoAcct:AcctId/text()">
            <tns:AcctId>
              <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:AcctKey/eoAcct:AcctId"/>
            </tns:AcctId>
          </xsl:if>
        </tns:AcctKey>
      </xsl:if>
      <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:Collateral">
        <tns:Collateral>
          <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:PartyKey">
            <tns:PartyKey>
              <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:PartyKey/ns4:VerifyDigit">
                <tns:VerifyDigit>
                  <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:PartyKey/ns4:VerifyDigit"/>
                </tns:VerifyDigit>
              </xsl:if>
              <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:PartyKey/ns4:PartyId">
                <tns:PartyId>
                  <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:PartyKey/ns4:PartyId"/>
                </tns:PartyId>
              </xsl:if>
            </tns:PartyKey>
          </xsl:if>
          <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:CollateralKey">
            <tns:CollateralKey>
              <xsl:if test="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:CollateralKey/eoCollateral:CollateralId">
                <tns:CollateralId>
                  <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:Collateral/eoCollateral:CollateralKey/eoCollateral:CollateralId"/>
                </tns:CollateralId>
              </xsl:if>
            </tns:CollateralKey>
          </xsl:if>
        </tns:Collateral>
      </xsl:if>
      <tns:Status>
        <appoptcommon:StatusCode>
          <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:Status/eoStatus:StatusCode"/>
        </appoptcommon:StatusCode>
        <xsl:choose>
               <xsl:when test="/ns0:AcctLoanCollateralAddRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc/text()">
                  <appoptcommon:StatusDesc>
                     <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc"/>
                  </appoptcommon:StatusDesc>
               </xsl:when>
               <xsl:otherwise>
                  <appoptcommon:StatusDesc>
                     <xsl:value-of select="/ns0:AcctLoanCollateralAddRs/ns0:Status/eoStatus:StatusDesc"/>
                  </appoptcommon:StatusDesc>
               </xsl:otherwise>
            </xsl:choose>
      </tns:Status>
    </tns:AcctLoanCollateralAddRs>
  </xsl:template>
</xsl:stylesheet>
