<wsdl:definitions name="StoreService" targetNamespace="http://www.agarcia.mx/ServiceBus/Store" xmlns:tns="http://www.agarcia.mx/ServiceBus/Store" xmlns:ebm="http://www.agarcia.mx/EnterpriseObjects/Store" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Store" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Store/StoreEBM.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ProcessStoreReqMsg">
    <wsdl:part name="ProcessStoreReqMsg" element="ebm:ProcessStoreEBM"/>
  </wsdl:message>
  <wsdl:message name="ProcessStoreRespMsg">
    <wsdl:part name="ProcessStoreRespMsg" element="ebm:ProcessStoreResponseEBM"/>
  </wsdl:message>
  <wsdl:portType name="ProcessStore_ptt">
    <wsdl:operation name="ProcessStore">
      <wsdl:input message="tns:ProcessStoreReqMsg"/>
      <wsdl:output message="tns:ProcessStoreRespMsg"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ProcessStore_bind" type="tns:ProcessStore_ptt">
    <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
    <wsdl:operation name="ProcessStore">
      <soap12:operation style="document" soapAction="ProcessStore" soapActionRequired="false"/>
      <wsdl:input>
        <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/Store"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/Store"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>