<wsdl:definitions name="ConsultarCobroComisionById" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCobroComisionById" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCobroComisionById" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCobroComisionById" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarCobroComisionById_plt">
    <plt:role name="ConsultarCobroComisionById_role">
      <plt:portType name="tns:ConsultarCobroComisionById_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCobroComisionById" schemaLocation="../XSD/ConsultarCobroComisionById.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarCobroComisionByIdInput_msg">
        <wsdl:part name="ConsultarCobroComisionByIdInput_msg" element="db:ConsultarCobroComisionByIdInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarCobroComisionByIdOutputCollection_msg">
        <wsdl:part name="ConsultarCobroComisionByIdOutputCollection" element="db:ConsultarCobroComisionByIdOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCobroComisionById_ptt">
        <wsdl:operation name="ConsultarCobroComisionById">
            <wsdl:input message="tns:ConsultarCobroComisionByIdInput_msg"/>
            <wsdl:output message="tns:ConsultarCobroComisionByIdOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>