<wsdl:definitions name="ConsultarCodExternoPais" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarCodExternoPais" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarCodExternoPais" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCodExternoPais" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarCodExternoPais_plt">
    <plt:role name="ConsultarCodExternoPais_role">
      <plt:portType name="tns:ConsultarCodExternoPais_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCodExternoPais" schemaLocation="../XSD/ConsultarCodExternoPais.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarCodExternoPaisInput_msg">
        <wsdl:part name="ConsultarCodExternoPaisInput_msg" element="db:ConsultarCodExternoPaisInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarCodExternoPaisOutputCollection_msg">
        <wsdl:part name="ConsultarCodExternoPaisOutputCollection" element="db:ConsultarCodExternoPaisOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCodExternoPais_ptt">
        <wsdl:operation name="ConsultarCodExternoPais">
            <wsdl:input message="tns:ConsultarCodExternoPaisInput_msg"/>
            <wsdl:output message="tns:ConsultarCodExternoPaisOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>