<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetFullHierarchyDB" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetHierarchyDB" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Resources/InputQuery.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetFullHierarchyDBInputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetHierarchyDB"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Resources/GetFullHierarchyDB_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetFullHierarchyDBSelect_IdDeptoRms_IdClaseRMS_IdTipoRMSInputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetFullHierarchyDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI NOV 06 00:13:32 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetFullHierarchyDBSelect_IdDeptoRms_IdClaseRMS_IdTipoRMSInputParameters>
         <xsl:if test="/ns0:GetFullHierarchyDBInputParameters/ns0:IdDeptoRMS">
            <tns:IdDeptoRms>
               <xsl:value-of select="/ns0:GetFullHierarchyDBInputParameters/ns0:IdDeptoRMS"/>
            </tns:IdDeptoRms>
         </xsl:if>
         <xsl:if test="/ns0:GetFullHierarchyDBInputParameters/ns0:IdClaseRMS">
            <tns:IdClaseRMS>
               <xsl:value-of select="/ns0:GetFullHierarchyDBInputParameters/ns0:IdClaseRMS"/>
            </tns:IdClaseRMS>
         </xsl:if>
         <xsl:if test="/ns0:GetFullHierarchyDBInputParameters/ns0:IdTipoRMS">
            <tns:IdTipoRMS>
               <xsl:value-of select="/ns0:GetFullHierarchyDBInputParameters/ns0:IdTipoRMS"/>
            </tns:IdTipoRMS>
         </xsl:if>
      </tns:GetFullHierarchyDBSelect_IdDeptoRms_IdClaseRMS_IdTipoRMSInputParameters>
   </xsl:template>
</xsl:stylesheet>