<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConvertirDocumentoFenixSOR"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConvertirDocumentoFenixSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ConvertirDocumentoFenixSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.bcie.com/DocumentoService"
    >
    <plnk:partnerLinkType name="EliminarDocumentosFenix">
        <plnk:role name="EliminarDocumentosFenixPT" portType="tns:EliminarDocumentosFenixPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConvertirDocumentoFenixSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Wsdl/BPEL/EliminarDocumentosFenixSOR.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/DocumentoService" location="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Wsdl/ADAPTER/ConsultarDocumentosFenixSAD.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/DocumentoService" location="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Wsdl/ADAPTER/EliminarDocumentoFenixSAD.wsdl"/>
</wsdl:definitions>
