<wsdl:definitions
     name="CrearMontoOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project1/CrearMontoOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project1/CrearMontoOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearMontoOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearMontoOperacion_plt" >
    <plt:role name="CrearMontoOperacion_role" >
      <plt:portType name="tns:CrearMontoOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearMontoOperacion" schemaLocation="../XSD/CrearMontoOperacion_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="MontoOperacionCollection_msg">
        <wsdl:part name="MontoOperacionCollection" element="top:MontoOperacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearMontoOperacion_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:MontoOperacionCollection_msg"/>
            <wsdl:output message="tns:MontoOperacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
