<wsdl:definitions
     name="ConsultarSeguimientoCrediticioByIdClienteDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSeguimientoCrediticioByIdClienteDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSeguimientoCrediticioByIdClienteDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSeguimientoCrediticioByIdClienteDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarSeguimientoCrediticioByIdClienteDB_plt" >
    <plt:role name="ConsultarSeguimientoCrediticioByIdClienteDB_role" >
      <plt:portType name="tns:ConsultarSeguimientoCrediticioByIdClienteDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSeguimientoCrediticioByIdClienteDB" schemaLocation="../XSD/ConsultarSeguimientoCrediticioByIdClienteDB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarSeguimientoCrediticioByIdClienteDBInput_msg">
        <wsdl:part name="ConsultarSeguimientoCrediticioByIdClienteDBInput_msg" element="db:ConsultarSeguimientoCrediticioByIdClienteDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarSeguimientoCrediticioByIdClienteDBOutputCollection_msg">
        <wsdl:part name="ConsultarSeguimientoCrediticioByIdClienteDBOutputCollection" element="db:ConsultarSeguimientoCrediticioByIdClienteDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarSeguimientoCrediticioByIdClienteDB_ptt">
        <wsdl:operation name="ConsultarSeguimientoCrediticioByIdClienteDB">
            <wsdl:input message="tns:ConsultarSeguimientoCrediticioByIdClienteDBInput_msg"/>
            <wsdl:output message="tns:ConsultarSeguimientoCrediticioByIdClienteDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
