<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ValidarClienteProcesoMO" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ValidarClienteProcesoMO"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ValidarClienteProceso/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/ValidarClienteProcesoMO" schemaLocation="../Schema/ValidarClienteProcesoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ValidarClienteProcesoRequestMessage">
    <part name="request" element="tns:ValidarClienteProcesoRequest"/>
  </message>
  <message name="ValidarClienteProcesoResponseMessage">
    <part name="response" element="tns:ValidarClienteProcesoResponse"/>
  </message>
  <portType name="ValidarClienteProcesoPT">
    <operation name="ValidarClienteProceso">
      <input message="tns:ValidarClienteProcesoRequestMessage"/>
      <output message="tns:ValidarClienteProcesoResponseMessage"/>
    </operation>
  </portType>
  <binding name="ValidarClienteProcesoPTSOAP12Bnd" type="tns:ValidarClienteProcesoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ValidarClienteProceso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ValidarClienteProcesoMO/ValidarClienteProceso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>