<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.agarcia.mx/EnterpriseObjects/UploadInvoiceEdiAPP" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/Invoice" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Invoice/RecorsFile.xsd"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://www.agarcia.mx/EnterpriseObjects/UploadInvoiceEdiAPP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Invoice/InvoiceEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="InvoiceEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Invoice"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED SEP 09 21:01:46 CDT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InvoiceEBM>
         <tns:dataArea>
            <tns:InvoiceEBO>
               <tns:HeadInvoice>
                  <tns:FHRecord_descriptor>FHEAD</tns:FHRecord_descriptor>
                  <tns:FHLine_id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:FHEAD/ns0:LineId"/>
                  </tns:FHLine_id>
                  <tns:FHGentran_ID>
                     <xsl:value-of select="/ns0:Root-Element/ns0:FHEAD/ns0:GentranID"/>
                  </tns:FHGentran_ID>
                  <tns:FHCurrent_date>
                     <xsl:value-of select="/ns0:Root-Element/ns0:FHEAD/ns0:Currentdate"/>
                  </tns:FHCurrent_date>
                  <tns:Record_descriptor>THEAD</tns:Record_descriptor>
                  <tns:Line_id2>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:LineId"/>
                  </tns:Line_id2>
                  <tns:Transaction_number>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:TransactionNum"/>
                  </tns:Transaction_number>
                  <tns:Document_Type>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:DocumType"/>
                  </tns:Document_Type>
                  <tns:Vendor_Document_Number>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:UUID"/>
                  </tns:Vendor_Document_Number>
                  <tns:Group_ID>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:GroupID"/>
                  </tns:Group_ID>
                  <tns:Vendor_Type>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:VendorType"/>
                  </tns:Vendor_Type>
                  <tns:Vendor_ID>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:VendorID"/>
                  </tns:Vendor_ID>
                  <tns:Vendor_Document_Date>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:VendorDocDate"/>
                  </tns:Vendor_Document_Date>
                  <tns:Order_Number>
                     <com:ID>
                        <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:OrderNumber"/>
                     </com:ID>
                  </tns:Order_Number>
                  <tns:Location>
                     <com:LocationId>
                        <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Location"/>
                     </com:LocationId>
                  </tns:Location>
                  <tns:Location_Type>
                     <com:LocationId>
                        <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:LocationType"/>
                     </com:LocationId>
                  </tns:Location_Type>
                  <tns:Terms>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Terms"/>
                  </tns:Terms>
                  <tns:Due_Date>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:DueDate"/>
                  </tns:Due_Date>
                  <tns:Payment_method>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Paymentmethod"/>
                  </tns:Payment_method>
                  <tns:Currency_code>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Currencycode"/>
                  </tns:Currency_code>
                  <tns:Exchange_rate>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Exchangerate"/>
                  </tns:Exchange_rate>
                  <tns:Sign_Indicator>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Sign"/>
                  </tns:Sign_Indicator>
                  <tns:Total_Cost>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:TotalCost"/>
                  </tns:Total_Cost>
                  <tns:Sign_Indicator1>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Sing1"/>
                  </tns:Sign_Indicator1>
                  <tns:Total_VAT_Amount>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:TotalVATAmount"/>
                  </tns:Total_VAT_Amount>
                  <tns:Sign_Indicator2>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Sing2"/>
                  </tns:Sign_Indicator2>
                  <tns:Total_Quantity>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:TotalQuantity"/>
                  </tns:Total_Quantity>
                  <tns:Sign_Indicator3>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:Sing3"/>
                  </tns:Sign_Indicator3>
                  <tns:Total_Discount>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:TotalDiscount"/>
                  </tns:Total_Discount>
                  <tns:Freight_Type>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:FreightType"/>
                  </tns:Freight_Type>
                  <tns:Paid_Ind>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:PaidInd"/>
                  </tns:Paid_Ind>
                  <tns:Multi_Location>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:MultiLocation"/>
                  </tns:Multi_Location>
                  <tns:Merchandise_Type>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:MerchandiseType"/>
                  </tns:Merchandise_Type>
                  <tns:Deal_Id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:DealId"/>
                  </tns:Deal_Id>
                  <tns:Deal_Detail_Id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:DealDetailId"/>
                  </tns:Deal_Detail_Id>
                  <tns:Ref_CNR_Ext_Doc_Id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:RefCNRExtDocId"/>
                  </tns:Ref_CNR_Ext_Doc_Id>
                  <tns:Ref_INV_Ext_Doc_Id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:RefINVExtDocId"/>
                  </tns:Ref_INV_Ext_Doc_Id>
                  <tns:Deal_Approval_Indicator>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:DealAppInd"/>
                  </tns:Deal_Approval_Indicator>
                  <tns:RTV_indicator>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:RTVind"/>
                  </tns:RTV_indicator>
                  <tns:Reference1>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:CustDocRef1"/>
                  </tns:Reference1>
                  <tns:Reference2>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:CustDocRef2"/>
                  </tns:Reference2>
                  <tns:Reference3>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:CustDocRef3"/>
                  </tns:Reference3>
                  <tns:Reference4>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:CustDocRef4"/>
                  </tns:Reference4>
                  <tns:Cross_reference_doc_numb>
                     <xsl:value-of select="/ns0:Root-Element/ns0:THEAD/ns0:CrossReference"/>
                  </tns:Cross_reference_doc_numb>
               </tns:HeadInvoice>
               <xsl:for-each select="/ns0:Root-Element/ns0:TDETL">
                  <tns:DetailInvoice>
                     <tns:Record_descriptor>TDETL</tns:Record_descriptor>
                     <tns:Line_id>
                        <xsl:value-of select="ns0:LineId"/>
                     </tns:Line_id>
                     <tns:Transaction_number>
                        <xsl:value-of select="ns0:TranNumber"/>
                     </tns:Transaction_number>
                     <tns:UPC>
                        <xsl:value-of select="ns0:UPC"/>
                     </tns:UPC>
                     <tns:UPC_Supplement>
                        <xsl:value-of select="ns0:UPCSupp"/>
                     </tns:UPC_Supplement>
                     <tns:Item>
                        <xsl:value-of select="ns0:Item"/>
                     </tns:Item>
                     <tns:VPN>
                        <xsl:value-of select="ns0:VPN"/>
                     </tns:VPN>
                     <tns:Sign_Indicator>
                        <xsl:value-of select="ns0:Sign"/>
                     </tns:Sign_Indicator>
                     <tns:Original_Doc_Quantity>
                        <xsl:value-of select="ns0:DocQuantity"/>
                     </tns:Original_Doc_Quantity>
                     <tns:Sign_Indicator1>
                        <xsl:value-of select="ns0:Sign1"/>
                     </tns:Sign_Indicator1>
                     <tns:Original_Unit_cost>
                        <xsl:value-of select="ns0:UnitCost"/>
                     </tns:Original_Unit_cost>
                     <tns:Original_VAT_Code>
                        <com:Identification>
                           <com:ID>
                              <xsl:value-of select="ns0:VATCode"/>
                           </com:ID>
                        </com:Identification>
                     </tns:Original_VAT_Code>
                     <tns:Original_VAT_rate>
                        <xsl:value-of select="ns0:VATRate"/>
                     </tns:Original_VAT_rate>
                     <tns:Sign_Indicator2>
                        <xsl:value-of select="ns0:Sign2"/>
                     </tns:Sign_Indicator2>
                     <tns:Total_Allowance>
                        <xsl:value-of select="ns0:TotalAllowance"/>
                     </tns:Total_Allowance>
                  </tns:DetailInvoice>
               </xsl:for-each>
               <tns:TVatsInvoice>
                  <tns:Line_id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TVATS/ns0:LineId"/>
                  </tns:Line_id>
                  <tns:Record_descriptor>TVATS</tns:Record_descriptor>
                  <tns:Sign_Indicator>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TVATS/ns0:Sign"/>
                  </tns:Sign_Indicator>
                  <tns:Transaction_number>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TVATS/ns0:TransactionNum"/>
                  </tns:Transaction_number>
                  <tns:VAT_code>
                     <com:Identification>
                        <com:ID>
                           <xsl:value-of select="/ns0:Root-Element/ns0:TVATS/ns0:VATcode"/>
                        </com:ID>
                     </com:Identification>
                     <com:TotalTaxesTransferred>
                        <xsl:value-of select="/ns0:Root-Element/ns0:TVATS/ns0:CostVATCode"/>
                     </com:TotalTaxesTransferred>
                     <com:TotalTaxesWithheld/>
                  </tns:VAT_code>
                  <tns:VAT_rate>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TVATS/ns0:VATrate"/>
                  </tns:VAT_rate>
               </tns:TVatsInvoice>
               <tns:CheckInvoice>
                  <tns:FTLine_id>
                     <xsl:value-of select="/ns0:Root-Element/ns0:FTAIL/ns0:LineId"/>
                  </tns:FTLine_id>
                  <tns:FTRecord_descriptor>FTAIL</tns:FTRecord_descriptor>
                  <tns:FTTransaction_lines>
                     <xsl:value-of select="/ns0:Root-Element/ns0:FTAIL/ns0:NumLines"/>
                  </tns:FTTransaction_lines>
                  <tns:TTTransaction_number>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TTAIL/ns0:TransactionNum"/>
                  </tns:TTTransaction_number>
                  <tns:TTLine_id2>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TTAIL/ns0:LineId"/>
                  </tns:TTLine_id2>
                  <tns:TTRecord_descriptor2>TTAIL</tns:TTRecord_descriptor2>
                  <tns:TTTransaction_lines2>
                     <xsl:value-of select="/ns0:Root-Element/ns0:TTAIL/ns0:TransactionLines"/>
                  </tns:TTTransaction_lines2>
               </tns:CheckInvoice>
            </tns:InvoiceEBO>
         </tns:dataArea>
      </tns:InvoiceEBM>
   </xsl:template>
</xsl:stylesheet>