<wsdl:definitions name="PollItemRMSDBService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/PollItemRMSDBService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/PollItemRMSDBService" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollItemRMSDBService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="PollItemRMSDBService_plt">
    <plt:role name="PollItemRMSDBService_role">
      <plt:portType name="tns:PollItemRMSDBService_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollItemRMSDBService_plt">
    <plt:role name="PollItemRMSDBService_role">
      <plt:portType name="tns:PollItemRMSDBService_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="PollItemRMSDBService_plt">
    <plt:role name="PollItemRMSDBService_role">
      <plt:portType name="tns:PollItemRMSDBService_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollItemRMSDBService" schemaLocation="../Schemas/PollItemRMSDBService_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="XxJsonDocumentsCollection_msg">
        <wsdl:part name="XxJsonDocumentsCollection" element="top:XxJsonDocumentsCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollItemRMSDBService_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:XxJsonDocumentsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>