<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/PollItemRMSDBService" name="PollItemRMSDBService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="PollItemRMSDBService-db.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/PollItemRMSDBService"/>
  <wsdl:binding name="PollItemRMSDBService_ptt-binding" type="pol:PollItemRMSDBService_ptt" xmlns:pol="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/PollItemRMSDBService">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="receive">
      <soap:operation soapAction="receive"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>