<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSCreateItemDbReference" name="RMSCreateItemDbReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSCreateItemDbReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSCreateItemDbReference"/>
    <wsdl:binding name="RMSCreateItemDbReference_ptt-binding" type="rms:RMSCreateItemDbReference_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSCreateItemDbReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSCreateItemDbReference">
            <soap:operation soapAction="RMSCreateItemDbReference"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>