<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCreditoByIdContrato" name="EliminarLineaCreditoByIdContrato_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarLineaCreditoByIdContrato.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCreditoByIdContrato"/>
    <wsdl:binding name="EliminarLineaCreditoByIdContrato_ptt-binding" type="elim:EliminarLineaCreditoByIdContrato_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCreditoByIdContrato">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarLineaCreditoByIdContrato">
            <soap:operation soapAction="EliminarLineaCreditoByIdContrato"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>