<wsdl:definitions name="QueryItemRMSReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/QueryItemRMSReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/ItemApp/QueryItemRMSReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryItemRMSReference" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryItemRMSReference_plt">
    <plt:role name="QueryItemRMSReference_role">
      <plt:portType name="tns:QueryItemRMSReference_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryItemRMSReference" schemaLocation="../Schema/QueryItemRMSReference_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryItemRMSReferenceSelect_inputParameters">
        <wsdl:part name="QueryItemRMSReferenceSelect_inputParameters" element="top:QueryItemRMSReferenceSelect_ItemParamInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaItemVwCollection_msg">
        <wsdl:part name="XxSoaItemVwCollection" element="top:XxSoaItemVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryItemRMSReference_ptt">
        <wsdl:operation name="QueryItemRMSReferenceSelect">
            <wsdl:input message="tns:QueryItemRMSReferenceSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaItemVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>