<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarExcepcionSolicitudSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/ConsultarExcepcionSolicitudSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarDesembolsosByIdSAD/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarExcepcionSolicitudMessage">
    <part name="request" element="desMO:ConsultarExcepcionSolicitudRequest"/>
  </message>
  <message name="responseConsultarExcepcionSolicitudMessage">
    <part name="response" element="desMO:ConsultarExcepcionSolicitudResponse"/>
  </message>
  <portType name="ConsultarExcepcionSolicituPT">
    <operation name="ConsultarExcepcionSolicitud">
      <input message="tns:requestConsultarExcepcionSolicitudMessage"/>
      <output message="tns:responseConsultarExcepcionSolicitudMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarExcepcionSolicituPTSOAP12Bnd" type="tns:ConsultarExcepcionSolicituPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarExcepcionSolicitud">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarExcepcionSolicitudSAD/ConsultarExcepcionSolicitud"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>