<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidarMontoMaximoDesembolsoSAD"
     targetNamespace="http://www.bcie.org/ValidarMontoMaximoDesembolsoSAD"
     xmlns:tns="http://www.bcie.org/ValidarMontoMaximoDesembolsoSAD"
     xmlns:inp1="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ValidarMontoMaximoDesembolsoRequestMessage">
        <wsdl:part name="ValidarMontoMaximoDesembolsoRequest" element="inp1:ValidarMontoMaximoDesembolsoRequest"/>
    </wsdl:message>
    <wsdl:message name="ValidarMontoMaximoDesembolsoResponseMessage">
        <wsdl:part name="ValidarMontoMaximoDesembolsoResponse" element="inp1:ValidarMontoMaximoDesembolsoResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarMontoMaximoDesembolsoPT">
        <wsdl:operation name="ValidarMontoMaximoDesembolso">
            <wsdl:input message="tns:ValidarMontoMaximoDesembolsoRequestMessage"/>
            <wsdl:output message="tns:ValidarMontoMaximoDesembolsoResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarMontoMaximoDesembolso_PTSOAP12Binding" type="tns:ValidarMontoMaximoDesembolsoPT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ValidarMontoMaximoDesembolso">
            <soap12:operation style="document" soapAction="http://www.bcie.org/ValidarMontoMaximoDesembolsoSAD/ValidarMontoMaximoDesembolso" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.bcie.org/ValidarMontoMaximoDesembolsoSAD"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.bcie.org/ValidarMontoMaximoDesembolsoSAD"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
