<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarPerspClie_SB" name="ActualizarPerspClie_SB_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ActualizarPerspClie_SB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarPerspClie_SB"/>
    <wsdl:binding name="ActualizarPerspClie_SB_ptt-binding" type="act:ActualizarPerspClie_SB_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarPerspClie_SB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ActualizarPerspClie_SB">
            <soap:operation soapAction="ActualizarPerspClie_SB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>