<wsdl:definitions name="ConsultarPlazoGracia" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarPlazoGracia" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarPlazoGracia" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarPlazoGracia" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarPlazoGracia_plt">
    <plt:role name="ConsultarPlazoGracia_role">
      <plt:portType name="tns:ConsultarPlazoGracia_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarPlazoGracia" schemaLocation="../XSD/ConsultarPlazoGracia.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarPlazoGraciaInput_msg">
        <wsdl:part name="ConsultarPlazoGraciaInput_msg" element="db:ConsultarPlazoGraciaInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarPlazoGraciaOutputCollection_msg">
        <wsdl:part name="ConsultarPlazoGraciaOutputCollection" element="db:ConsultarPlazoGraciaOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarPlazoGracia_ptt">
        <wsdl:operation name="ConsultarPlazoGracia">
            <wsdl:input message="tns:ConsultarPlazoGraciaInput_msg"/>
            <wsdl:output message="tns:ConsultarPlazoGraciaOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>