<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearActualizarClienteProcesoDB" name="CrearActualizarClienteProcesoDB_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../WSDL/CrearActualizarClienteProcesoDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearActualizarClienteProcesoDB"/>
    <wsdl:binding name="CrearActualizarClienteProcesoDB_ptt-binding" type="cre:CrearActualizarClienteProcesoDB_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearActualizarClienteProcesoDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>