<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Cliente" targetNamespace="http://xmlns.bcie.com/ClienteService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cliMO="http://www.bcie.org/ClienteMO"
                  xmlns:tns="http://xmlns.bcie.com/ClienteService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestActualizarClienteMessage">
    <wsdl:part name="request" element="cliMO:ActualizarClienteRequest"/>
  </wsdl:message>
  <wsdl:message name="responseActualizarClienteMessage">
    <wsdl:part name="response" element="cliMO:ActualizarClienteResponse"/>
  </wsdl:message>
  <wsdl:portType name="ActualizarClientePT">
    <wsdl:operation name="actualizarCliente">
      <wsdl:input message="tns:requestActualizarClienteMessage"/>
      <wsdl:output message="tns:responseActualizarClienteMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ActualizarCliente12Bnd" type="tns:ActualizarClientePT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizarCliente">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ClienteService/ActualizarCliente"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>