<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaTermino" name="ConsultarTerminoByLineaCredito_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarTcaTermino.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaTermino"/>
    <wsdl:binding name="ConsultarTcaTermino_ptt-binding" type="con:ConsultarTcaTermino_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaTermino">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarTcaTermino">
            <soap:operation soapAction="ConsultarTcaTermino"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>