<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/DeliveryQuantityApp/AIA_DeliveryQuantityAdjustmentTopic" name="AIA_DeliveryQuantityAdjustmentTopic-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AIA_DeliveryQuantityAdjustmentTopic.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/DeliveryQuantityApp/AIA_DeliveryQuantityAdjustmentTopic"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="aia:Produce_Message_ptt" xmlns:aia="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/DeliveryQuantityApp/AIA_DeliveryQuantityAdjustmentTopic">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>