CREATE OR REPLACE TRIGGER FENIX.OPERACION_INS_TGR
AFTER INSERT ON FENIX.OPERACION
FOR EACH ROW
DECLARE
	v_id_tbi_operacion NUMBER;
	err_num NUMBER;
	err_msg VARCHAR2(255);
BEGIN

  SELECT TBI_OPERACION_SEQ.NEXTVAL INTO v_id_tbi_operacion FROM DUAL;
  
  INSERT INTO TBI_OPERACION (ID, ID_OPERACION, TIPO_ACCION, FECHA_REGISTRO) VALUES (v_id_tbi_operacion,:NEW.ID_OPERACION,'AGREGAR_OPERACION', SYSDATE);  
  
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'ID_OPERACION',:NEW.ID_OPERACION,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'USUARIO',:NEW.USUARIO,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'NOMBRE',:NEW.NOMBRE,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'ID_CLIENTE',:NEW.ID_CLIENTE,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'ID_PRODUCTO',:NEW.ID_PRODUCTO,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'FECHA_INICIO',:NEW.FECHA_INICIO,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'SCR',:NEW.SCR,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'SCR_ESTATUS',:NEW.SCR_ESTATUS,NULL);  
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'ETAPA',:NEW.ETAPA,NULL);
  INSERT INTO TBI_OPERACION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_operacion,'ESTADO',:NEW.ESTADO,NULL);
  
EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SUBSTR(SQLERRM,1,250);
		
		
		DBMS_OUTPUT.put_line('Error al insertar en la tabla de bitácora de operación');
		DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line(err_msg);
		
        
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','OPERACION_INS_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
		COMMIT;
END;