CREATE OR REPLACE PROCEDURE P_VALIDA_CLIENTE_DUPLICADO ( P_ABREVIATURA VARCHAR2,  P_RAZON_SOCIAL VARCHAR2,
   RECORDSET            OUT SYS_REFCURSOR)
   
IS
 P_ID_CLIENTE NUMBER;
 V_ABREVIATURA VARCHAR2 (250 );
 V_VALOR  VARCHAR2 (250 );

BEGIN

SELECT ID_CLIENTE INTO P_ID_CLIENTE  FROM CLIENTES 
WHERE ABREVIATURA =P_ABREVIATURA
AND BAN_ESTATUS=1
AND ROWNUM =1;

  OPEN RECORDSET FOR
SELECT   ID_CLIENTE,   ID_FLEXCUBE,   RAZON_SOCIAL,   ABREVIATURA,   TIPO_PERSONA,   TIPO_CLIENTE,   SECTOR ,   TIPO_INSTITUCION,
  PAIS  ,   GRUPO_ECONOMICO    ,   TIPO_IDENTIFICACION  ,   NUMERO_IDENTIFICACION ,  OFICINA           ,  FECHA_REGISTRO    ,
  FECHA_APROBACION       ,   EJECUTIVO              ,   COMENTARIO_APROBACION  ,   AUTORIZO               ,   BAN_ESTATUS            ,   FECHA_BAJA             ,
  DIA_PAGO    , 'ABREVIATURA' VALOR FROM CLIENTES
  WHERE ID_CLIENTE =P_ID_CLIENTE;
  
  EXCEPTION
WHEN NO_DATA_FOUND THEN

BEGIN

SELECT F_VALIDACION_RASONSOCIAL(P_RAZON_SOCIAL||' ', ' ') INTO V_VALOR FROM DUAL;



       OPEN RECORDSET FOR
SELECT   ID_CLIENTE,   ID_FLEXCUBE,   RAZON_SOCIAL,   ABREVIATURA,   TIPO_PERSONA,   TIPO_CLIENTE,   SECTOR ,   TIPO_INSTITUCION,
  PAIS  ,   GRUPO_ECONOMICO    ,   TIPO_IDENTIFICACION  ,   NUMERO_IDENTIFICACION ,  OFICINA           ,  FECHA_REGISTRO    ,
  FECHA_APROBACION       ,   EJECUTIVO              ,   COMENTARIO_APROBACION  ,   AUTORIZO               ,   BAN_ESTATUS            ,   FECHA_BAJA             ,
  DIA_PAGO  , 'RAZONSOCIAL' VALOR  FROM CLIENTES
  WHERE RAZON_SOCIAL LIKE  '%'||V_VALOR||'%' ;


 EXCEPTION
WHEN NO_DATA_FOUND THEN



   DBMS_OUTPUT.PUT_LINE (V_ABREVIATURA  || ' ' || V_VALOR);
 
END;
END;
/
