CREATE OR REPLACE PROCEDURE SP_CREAR_FT05(
P_ID_DESEMBOLSO IN NUMBER,
P_ID_TRANSFERENCIA_FT05 IN OUT NUMBER,
P_BHQ_TRANSFERENCIA IN VARCHAR2,
P_CODIGO_RES OUT NUMBER,
P_MENSAJE OUT VARCHAR2)

IS  

v_fechaDsiponibilidad date;

BEGIN

IF P_ID_DESEMBOLSO IS NOT NULL THEN 
    SELECT FECHA_DISPONIBILIDAD_FONDOS  INTO v_fechaDsiponibilidad FROM CONTRATO_DESEMBOLSO  WHERE ID = P_ID_DESEMBOLSO;

    IF P_ID_TRANSFERENCIA_FT05 IS NULL THEN

        SELECT TRANSFERENCIA_BANCARIA_SEQ.NEXTVAL  INTO P_ID_TRANSFERENCIA_FT05 FROM DUAL;
  
        UPDATE CONTRATO_DESEMBOLSO
        SET ID_TRANSFERENCIA_FT05 = P_ID_TRANSFERENCIA_FT05,
            FECHA_EFECTIVA_FT05 = v_fechaDsiponibilidad
        WHERE ID = P_ID_DESEMBOLSO;
        
        P_CODIGO_RES := 0;
        P_MENSAJE := 'Actualización exitosa';
        

    ELSE
        IF P_BHQ_TRANSFERENCIA IS NOT NULL THEN
        
            UPDATE CONTRATO_DESEMBOLSO
            SET BHQ_TRANSFERENCIA_FT05 = P_BHQ_TRANSFERENCIA,
            FECHA_EFECTIVA_FT05 = v_fechaDsiponibilidad
            WHERE ID = P_ID_DESEMBOLSO
            AND ID_TRANSFERENCIA_FT05 = P_ID_TRANSFERENCIA_FT05;
            
            P_CODIGO_RES := 0;
            P_MENSAJE := 'Datos de TRANSFERENCIA_FT05 actualizados correctamente';
            
        
        END IF;
        P_CODIGO_RES := 0;
        P_MENSAJE := 'SIN BHQ';
    END IF;

ELSE

P_CODIGO_RES := 1;
P_MENSAJE := 'Id del contrato desembolso es requerido';


END IF;

EXCEPTION
   WHEN OTHERS
   THEN
      P_CODIGO_RES := 1;
      P_MENSAJE := SQLERRM;

END;

