create or replace TYPE       T_REGLA_DESEMBOLSO  AS OBJECT
 (
  ID                 NUMBER(12) ,
  ID_DESEMBOLSO      NUMBER(12),
  ID_TCA_REGLA       NUMBER(12),
  EXCEPTUADO         NUMBER(1),
  USUARIO_EXCEPTUA   VARCHAR2(32),
  FECHA_EXCEPCION    DATE
  );
  
  /
  
create or replace TYPE       T_LISTA_REGLAS_DESEMBOLSO AS TABLE  OF T_REGLA_DESEMBOLSO;
  

/

create or replace PROCEDURE SP_UPSERT_REGLAS_DESEMBOLSO(
P_LISTA_REGLA_DESEMBOLSO IN T_LISTA_REGLAS_DESEMBOLSO,
P_LISTA_REGLA_DESEMBOLSO_OUT OUT T_LISTA_REGLAS_DESEMBOLSO,
P_CODIGO_RES OUT NUMBER,
P_MENSAJE OUT VARCHAR2
)

IS 
V_ID_REGLA_DESEMBOLSO NUMBER;
V_REGLA_DESEMBOLSO_ACTUAL   TRE_REGLA_DESEMBOLSO%ROWTYPE;

BEGIN

  --DBMS_OUTPUT.ENABLE (BUFFER_SIZE >= NULL);

  P_LISTA_REGLA_DESEMBOLSO_OUT := T_LISTA_REGLAS_DESEMBOLSO();
  P_LISTA_REGLA_DESEMBOLSO_OUT.EXTEND(P_LISTA_REGLA_DESEMBOLSO.COUNT);
  
  IF (P_LISTA_REGLA_DESEMBOLSO.COUNT > 0) THEN

    FOR IND IN 1 .. P_LISTA_REGLA_DESEMBOLSO.COUNT
    LOOP
      IF P_LISTA_REGLA_DESEMBOLSO (IND).ID IS NULL
      THEN
  
          SELECT TRE_REGLA_DESEMBOLSO_SEQ.NEXTVAL INTO V_ID_REGLA_DESEMBOLSO FROM DUAL;
  
            INSERT INTO TRE_REGLA_DESEMBOLSO
            VALUES (V_ID_REGLA_DESEMBOLSO,
                    P_LISTA_REGLA_DESEMBOLSO(IND).ID_DESEMBOLSO,
                    P_LISTA_REGLA_DESEMBOLSO(IND).ID_TCA_REGLA,
                    P_LISTA_REGLA_DESEMBOLSO(IND).EXCEPTUADO,
                    P_LISTA_REGLA_DESEMBOLSO(IND).USUARIO_EXCEPTUA,
                    P_LISTA_REGLA_DESEMBOLSO(IND).FECHA_EXCEPCION);
          
                    P_LISTA_REGLA_DESEMBOLSO_OUT(IND) := P_LISTA_REGLA_DESEMBOLSO(IND);
                    P_LISTA_REGLA_DESEMBOLSO_OUT(IND).ID := V_ID_REGLA_DESEMBOLSO;
  
      ELSE
  
            SELECT ID,ID_DESEMBOLSO, ID_TCA_REGLA,EXCEPTUADO,USUARIOEXCEPTUA,FECHA_EXCEPCION 
            INTO V_REGLA_DESEMBOLSO_ACTUAL
            FROM  TRE_REGLA_DESEMBOLSO 
            WHERE ID = P_LISTA_REGLA_DESEMBOLSO(IND).ID;
  
            UPDATE TRE_REGLA_DESEMBOLSO
            SET ID_DESEMBOLSO = NVL(P_LISTA_REGLA_DESEMBOLSO(IND).ID_DESEMBOLSO,V_REGLA_DESEMBOLSO_ACTUAL.ID_DESEMBOLSO),
                ID_TCA_REGLA = NVL (P_LISTA_REGLA_DESEMBOLSO(IND).ID_TCA_REGLA,V_REGLA_DESEMBOLSO_ACTUAL.ID_TCA_REGLA),
                EXCEPTUADO = NVL (P_LISTA_REGLA_DESEMBOLSO(IND).EXCEPTUADO,V_REGLA_DESEMBOLSO_ACTUAL.EXCEPTUADO),
                USUARIOEXCEPTUA = NVL (P_LISTA_REGLA_DESEMBOLSO(IND).USUARIO_EXCEPTUA,V_REGLA_DESEMBOLSO_ACTUAL.USUARIOEXCEPTUA),
                FECHA_EXCEPCION = NVL (P_LISTA_REGLA_DESEMBOLSO(IND).FECHA_EXCEPCION,V_REGLA_DESEMBOLSO_ACTUAL.FECHA_EXCEPCION)
                WHERE ID = P_LISTA_REGLA_DESEMBOLSO(IND).ID;
      
                P_LISTA_REGLA_DESEMBOLSO_OUT(IND) := P_LISTA_REGLA_DESEMBOLSO(IND);
                P_LISTA_REGLA_DESEMBOLSO_OUT(IND).ID := P_LISTA_REGLA_DESEMBOLSO(IND).ID;
                
      END IF;   
          DBMS_OUTPUT.PUT_LINE ('ID_TRE ' || P_LISTA_REGLA_DESEMBOLSO (IND).ID);
 
    END LOOP;
 
 END IF;
 
    P_CODIGO_RES := 0;
    P_MENSAJE := 'Procedimiento  ejecutado  correctamente !';
    

    
EXCEPTION
   WHEN OTHERS
   THEN
      P_CODIGO_RES := 1;
      P_MENSAJE := SQLERRM;
 
 END;