CREATE OR REPLACE TRIGGER FENIX.SUPERVISION_DEL_TGR 
AFTER DELETE ON FENIX.SUPERVISION
FOR EACH ROW
DECLARE 
	err_num NUMBER;   
	err_msg VARCHAR2(255);
   
	BEGIN		
		DELETE FROM TBI_SUPERVISION_CAMPO WHERE ID_BITACORA IN  (SELECT ID FROM TBI_SUPERVISION WHERE ID_SUPERVISION = :OLD.ID);
		DELETE FROM TBI_SUPERVISION WHERE ID_SUPERVISION = :OLD.ID;
	
	EXCEPTION
		WHEN OTHERS THEN
			err_num := SQLCODE;
			err_msg := SUBSTR(SQLERRM,1,250);
			
			
			DBMS_OUTPUT.put_line('Error al borrar en la tabla de bitácora de supervisión');		
			DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
			DBMS_OUTPUT.put_line(err_msg);
			
			
			INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
			VALUES('TRG','SUPERVISION_DEL_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
			COMMIT;
	
	END;