CREATE OR REPLACE TRIGGER FENIX.SUPERVISION_INS_TGR
AFTER INSERT ON FENIX.SUPERVISION
FOR EACH ROW
DECLARE
	v_id_tbi_supervision NUMBER;
	err_num NUMBER;
	err_msg VARCHAR2(255);

BEGIN

  SELECT TBI_SUPERVISION_SEQ.NEXTVAL INTO v_id_tbi_supervision FROM DUAL;
  
  INSERT INTO TBI_SUPERVISION (ID, ID_SUPERVISION, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES (v_id_tbi_supervision,:NEW.ID,'AGREGAR_SUPERVISION',:NEW.LOGIN_USUARIO,:NEW.NOMBRE_USUARIO,SYSDATE);  
  
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'ID',:NEW.ID,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'ID_OPERACION',:NEW.ID_OPERACION,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'ID_TCA_SCT',:NEW.ID_TCA_SCT,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'CALIFICACION_FINAL',:NEW.CALIFICACION_FINAL,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'FECHA_VISITA',:NEW.FECHA_VISITA,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'FECHA_AVANCE',:NEW.FECHA_AVANCE,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'FECHA_INFORME',:NEW.FECHA_INFORME,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'AVANCE_FISICO',:NEW.AVANCE_FISICO,NULL);  
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'AVANCE_FINANCIERO',:NEW.AVANCE_FINANCIERO,NULL);  
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'TIPO_ACTUALIZACION',:NEW.TIPO_ACTUALIZACION,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'ES_PROYECTO_EN_OPERACION',:NEW.ES_PROYECTO_EN_OPERACION,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'INSTANCIA_PROCESO',:NEW.INSTANCIA_PROCESO,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'BAN_ESTATUS',:NEW.BAN_ESTATUS,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'LOGIN_USUARIO',:NEW.LOGIN_USUARIO,NULL);  
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'NOMBRE_USUARIO',:NEW.NOMBRE_USUARIO,NULL);    
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'LOGIN_USUARIO_ULTIMO_CAMBIO',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,NULL);   
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'NOMBRE_USUARIO_ULTIMO_CAMBIO',:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,NULL);
  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'FECHA_ULTIMO_CAMBIO',:NEW.FECHA_ULTIMO_CAMBIO,NULL);
 

EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SUBSTR(SQLERRM,1,250);
		
		
		DBMS_OUTPUT.put_line('Error al insertar en la tabla de bitácora de supervisión');		
		DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line(err_msg);
		
        
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','SUPERVISION_INS_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
		COMMIT;
		
END;