

CREATE OR REPLACE TRIGGER TERMINO_UPD_TGR
AFTER UPDATE ON TERMINO
FOR EACH ROW

DECLARE
	v_id_tbi_termino NUMBER;	
	err_num NUMBER;
	err_msg VARCHAR2(255);
	
BEGIN

	SELECT TBI_TERMINO_SEQ.NEXTVAL INTO v_id_tbi_termino FROM DUAL;
	
	-- ID_TCA_TERMINO = 1 - T101, 30 - T603
  
	IF (:NEW.ID_TCA_TERMINO = 1) 	THEN 
		INSERT INTO TBI_TERMINO(ID, ID_TERMINO, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_termino,:NEW.ID,'MODIFICAR TERMINO T101',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,SYSDATE);  
	ELSIF (:NEW.ID_TCA_TERMINO = 30) THEN
		INSERT INTO TBI_TERMINO(ID, ID_TERMINO, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_termino,:NEW.ID,'MODIFICAR TERMINO T603',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,SYSDATE);  
	END IF;
	
	IF (:NEW.ID_TCA_TERMINO = 1) OR (:NEW.ID_TCA_TERMINO = 30)
	THEN 

		IF UPDATING ('ID_OPERACION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_OPERACION',:NEW.ID_OPERACION,:OLD.ID_OPERACION);	  
		END IF;
		IF UPDATING ('NOMBRE') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'NOMBRE',:NEW.NOMBRE,:OLD.NOMBRE);
		END IF;	
		IF UPDATING ('DESCRIPCION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'DESCRIPCION',:NEW.DESCRIPCION,:OLD.DESCRIPCION);
		END IF;
		IF UPDATING ('ID_TCA_TERMINO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TERMINO',:NEW.ID_TCA_TERMINO,:OLD.ID_TCA_TERMINO);
		END IF;
		IF UPDATING ('ID_TCA_TIPO_FECHA_INICIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_FECHA_INICIO',:NEW.ID_TCA_TIPO_FECHA_INICIO,:OLD.ID_TCA_TIPO_FECHA_INICIO);
		END IF;
		IF UPDATING ('FECHA_INICIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_INICIO',:NEW.FECHA_INICIO,:OLD.FECHA_INICIO);
		END IF;
		IF UPDATING ('PLAZO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PLAZO',:NEW.PLAZO,:OLD.PLAZO);
		END IF;
		IF UPDATING ('ID_TCA_FRECUENCIA_PLAZO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_PLAZO',:NEW.ID_TCA_FRECUENCIA_PLAZO,:OLD.ID_TCA_FRECUENCIA_PLAZO);  
		END IF;
		IF UPDATING ('FECHA_VENCIMIENTO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_VENCIMIENTO',:NEW.FECHA_VENCIMIENTO,:OLD.FECHA_VENCIMIENTO);  
		END IF;
		IF UPDATING ('ID_TCA_MONEDA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_MONEDA',:NEW.ID_TCA_MONEDA,:OLD.ID_TCA_MONEDA);  
		END IF;
		IF UPDATING ('MONTO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MONTO',:NEW.MONTO,:OLD.MONTO);    
		END IF;
		IF UPDATING ('TASA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TASA',:NEW.TASA,:OLD.TASA);
		END IF;
		IF UPDATING ('ID_TCA_TIPO_TASA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_TASA',:NEW.ID_TCA_TIPO_TASA,:OLD.ID_TCA_TIPO_TASA);
		END IF;
		IF UPDATING ('FECHA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA',:NEW.FECHA,:OLD.FECHA);  
		END IF;
		IF UPDATING ('FRECUENCIA_REVISION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FRECUENCIA_REVISION',:NEW.FRECUENCIA_REVISION,:OLD.FRECUENCIA_REVISION);  
		END IF;
		IF UPDATING ('ID_TCA_FRECUENCIA_REVISION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_REVISION',:NEW.ID_TCA_FRECUENCIA_REVISION,:OLD.ID_TCA_FRECUENCIA_REVISION);  
		END IF;        
		IF UPDATING ('FECHA_INICIO_REVISION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_INICIO_REVISION',:NEW.FECHA_INICIO_REVISION,:OLD.FECHA_INICIO_REVISION); 
		END IF;        
		IF UPDATING ('FRECUENCIA_PAGO_INTERES') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FRECUENCIA_PAGO_INTERES',:NEW.FRECUENCIA_PAGO_INTERES,:OLD.FRECUENCIA_PAGO_INTERES);  	  
		END IF;
		IF UPDATING ('ID_TCA_FRECUENCIA_PAGO_INTERES') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_PAGO_INTERES',:NEW.ID_TCA_FRECUENCIA_PAGO_INTERES,:OLD.ID_TCA_FRECUENCIA_PAGO_INTERES);  
		END IF;
		IF UPDATING ('FECHA_INICIO_PAGO_INTERES') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_INICIO_PAGO_INTERES',:NEW.FECHA_INICIO_PAGO_INTERES,:OLD.FECHA_INICIO_PAGO_INTERES);  
		END IF;
		IF UPDATING ('FRECUENCIA_AMORTIZACION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FRECUENCIA_AMORTIZACION',:NEW.FRECUENCIA_AMORTIZACION,:OLD.FRECUENCIA_AMORTIZACION);  
		END IF;
		IF UPDATING ('ID_TCA_FRECUENCIA_AMORTIZACION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_AMORTIZACION',:NEW.ID_TCA_FRECUENCIA_AMORTIZACION,:OLD.ID_TCA_FRECUENCIA_AMORTIZACION); 
		END IF;
		IF UPDATING ('MORA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MORA',:NEW.MORA,:OLD.MORA);  	  
		END IF;
		IF UPDATING ('PORCENTAJE_COBERTURA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_COBERTURA',:NEW.PORCENTAJE_COBERTURA,:OLD.PORCENTAJE_COBERTURA);  
		END IF;
		IF UPDATING ('SE_APLICAN_RECURSOS_CONCESION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'SE_APLICAN_RECURSOS_CONCESION',:NEW.SE_APLICAN_RECURSOS_CONCESION,:OLD.SE_APLICAN_RECURSOS_CONCESION);  
		END IF;
		IF UPDATING ('SE_APLICAN_RECURSOS_EXTERNOS') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'SE_APLICAN_RECURSOS_EXTERNOS',:NEW.SE_APLICAN_RECURSOS_EXTERNOS,:OLD.SE_APLICAN_RECURSOS_EXTERNOS);  
		END IF;
		IF UPDATING ('TIPO_CONTRAPARTE') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TIPO_CONTRAPARTE',:NEW.TIPO_CONTRAPARTE,:OLD.TIPO_CONTRAPARTE);  
		END IF;
		IF UPDATING ('MONTO_MINIMO_DESEMBOLSO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MONTO_MINIMO_DESEMBOLSO',:NEW.MONTO_MINIMO_DESEMBOLSO,:OLD.MONTO_MINIMO_DESEMBOLSO);  
		END IF;
		IF UPDATING ('MONTO_MAXIMO_DESEMBOLSO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MONTO_MAXIMO_DESEMBOLSO',:NEW.MONTO_MAXIMO_DESEMBOLSO,:OLD.MONTO_MAXIMO_DESEMBOLSO);  
		END IF;
		IF UPDATING ('TASA_MINIMA_DESEMBOLSO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TASA_MINIMA_DESEMBOLSO',:NEW.TASA_MINIMA_DESEMBOLSO,:OLD.TASA_MINIMA_DESEMBOLSO);  
		END IF;
		IF UPDATING ('TASA_MAXIMA_DESEMBOLSO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TASA_MAXIMA_DESEMBOLSO',:NEW.TASA_MAXIMA_DESEMBOLSO,:OLD.TASA_MAXIMA_DESEMBOLSO);  
		END IF;
		IF UPDATING ('ID_TCA_ESTADO_TCC') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_ESTADO_TCC',:NEW.ID_TCA_ESTADO_TCC,:OLD.ID_TCA_ESTADO_TCC);  
		END IF;
		IF UPDATING ('ID_TCA_SUB_ESTADO_TCC') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_SUB_ESTADO_TCC',:NEW.ID_TCA_SUB_ESTADO_TCC,:OLD.ID_TCA_SUB_ESTADO_TCC);  
		END IF;
		IF UPDATING ('FECHA_REGISTRO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,:OLD.FECHA_REGISTRO);  
		END IF;
		IF UPDATING ('BAN_ESTATUS') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'BAN_ESTATUS',:NEW.BAN_ESTATUS,:OLD.BAN_ESTATUS);  
		END IF;
		IF UPDATING ('ID_TERMINO_ENMENDADO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TERMINO_ENMENDADO',:NEW.ID_TERMINO_ENMENDADO,:OLD.ID_TERMINO_ENMENDADO);  
		END IF;
		IF UPDATING ('FECHA_ENMIENDA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_ENMIENDA',:NEW.FECHA_ENMIENDA,:OLD.FECHA_ENMIENDA);  
		END IF;
		IF UPDATING ('CLIENTE_GESTIONA_CONTRATACION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'CLIENTE_GESTIONA_CONTRATACION',:NEW.CLIENTE_GESTIONA_CONTRATACION,:OLD.CLIENTE_GESTIONA_CONTRATACION);  
		END IF;
		IF UPDATING ('REQUIERE_FONDO_PRESUPUESTARIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'REQUIERE_FONDO_PRESUPUESTARIO',:NEW.REQUIERE_FONDO_PRESUPUESTARIO,:OLD.REQUIERE_FONDO_PRESUPUESTARIO);  
		END IF;
		IF UPDATING ('REQ_FORMALIZACION_AUTOMATICA') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'REQ_FORMALIZACION_AUTOMATICA',:NEW.REQ_FORMALIZACION_AUTOMATICA,:OLD.REQ_FORMALIZACION_AUTOMATICA);  
		END IF;
		IF UPDATING ('REQUIERE_ORDEN_INICIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'REQUIERE_ORDEN_INICIO',:NEW.REQUIERE_ORDEN_INICIO,:OLD.REQUIERE_ORDEN_INICIO);  
		END IF;
		IF UPDATING ('PORCENTAJE_MODIFICACION') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_MODIFICACION',:NEW.PORCENTAJE_MODIFICACION,:OLD.PORCENTAJE_MODIFICACION);  
		END IF;
		IF UPDATING ('ID_TCA_TIPO_AVANCE') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_AVANCE',:NEW.ID_TCA_TIPO_AVANCE,:OLD.ID_TCA_TIPO_AVANCE);  
		END IF;
		IF UPDATING ('ID_TCA_TIPO_PORCENTAJE') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_PORCENTAJE',:NEW.ID_TCA_TIPO_PORCENTAJE,:OLD.ID_TCA_TIPO_PORCENTAJE);  
		END IF;
		IF UPDATING ('PORCENTAJE') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE',:NEW.PORCENTAJE,:OLD.PORCENTAJE);  
		END IF;
		IF UPDATING ('PORCENTAJE_INICIAL') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_INICIAL',:NEW.PORCENTAJE_INICIAL,:OLD.PORCENTAJE_INICIAL);  
		END IF;
		IF UPDATING ('PORCENTAJE_FINAL') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_FINAL',:NEW.PORCENTAJE_FINAL,:OLD.PORCENTAJE_FINAL);  
		END IF;
		IF UPDATING ('LOGIN_USUARIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'LOGIN_USUARIO',:NEW.LOGIN_USUARIO,:OLD.LOGIN_USUARIO);
		END IF;
		IF UPDATING ('NOMBRE_USUARIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'NOMBRE_USUARIO',:NEW.NOMBRE_USUARIO,:OLD.NOMBRE_USUARIO);		
		END IF;		
		IF UPDATING ('LOGIN_USUARIO_ULTIMO_CAMBIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'LOGIN_USUARIO_ULTIMO_CAMBIO',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:OLD.LOGIN_USUARIO_ULTIMO_CAMBIO);
		END IF;
		IF UPDATING ('NOMBRE_USUARIO_ULTIMO_CAMBIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'NOMBRE_USUARIO_ULTIMO_CAMBIO',:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,:OLD.NOMBRE_USUARIO_ULTIMO_CAMBIO);
		END IF;
		IF UPDATING ('FECHA_ULTIMO_CAMBIO') THEN
			INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_ULTIMO_CAMBIO',:NEW.FECHA_ULTIMO_CAMBIO,:OLD.FECHA_ULTIMO_CAMBIO);
		END IF;
	END IF;
	
EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SUBSTR(SQLERRM,1,250);
		
		DBMS_OUTPUT.put_line('Error al actualizar en la tabla de bitácora de término');
		DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line(err_msg);
				
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','TERMINO_UPD_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
		COMMIT;
	
END;
