<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDACreateRetailStoreProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/JDACreateRetailStoreProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N4="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/JDACreateRetailStoreProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="JDACreateRetailStore">
      <plnk:role name="JDACreateRetailStorePType" portType="WL5G3N4:JDACreateRetailStorePType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/JDACreateRetailStoreProcess" location="http://172.16.19.34:7004/Capabilities/Core/RetailStore/RetailStoreEntitySvc/PS/JDACreateRetailStoreProcessPXY?wsdl"/>
</wsdl:definitions>
