<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="TranslateRetailStoreTaskActionWSLD" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N1="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="TranslateJDA">
      <plnk:role name="TranslateRetailStoreTaskActionPType" portType="WL5G3N1:TranslateRetailStoreTaskActionPType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" location="http://172.16.19.34:7004/Capabilities/Core/RetailStore/RetailStoreEntitySvc/PS/TranslateRetailStoreTaskActionPXY?wsdl"/>
</wsdl:definitions>
