<?xml version='1.0' encoding='UTF-8'?>
<WL5G3N0:definitions name="TranslateRetailStoreTaskActionWSLD" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
   <WL5G3N0:types>
      <xsd:schema xmlns:inp1="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction" schemaLocation="http://172.16.19.26:7004/Capabilities/Core/RetailStore/RetailStoreEntitySvc/PS/TranslateRetailStoreTaskActionPXY?SCHEMA%2FCapabilities%2FCore%2FRetailStore%2FRetailStoreEntitySvc%2FResources%2FSchema%2FTranslateRetailTaskActionSchema"/>
      </xsd:schema>
   </WL5G3N0:types>
   <WL5G3N0:message name="requestMessage">
      <WL5G3N0:part name="request" element="WL5G3N1:translateRequest"/>
   </WL5G3N0:message>
   <WL5G3N0:message name="replyMessage">
      <WL5G3N0:part name="response" element="WL5G3N1:translateResponse"/>
   </WL5G3N0:message>
   <WL5G3N0:portType name="TranslateRetailStoreTaskActionPType">
      <WL5G3N0:operation name="translate">
         <WL5G3N0:input message="WL5G3N1:requestMessage"/>
         <WL5G3N0:output message="WL5G3N1:replyMessage"/>
      </WL5G3N0:operation>
   </WL5G3N0:portType>
   <WL5G3N0:binding name="TranslateRetailStoreTaskActionBinding" type="WL5G3N1:TranslateRetailStoreTaskActionPType">
      <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <WL5G3N0:operation name="translate">
         <WL5G3N2:operation style="document" soapAction="translate"/>
         <WL5G3N0:input>
            <WL5G3N2:body use="literal" namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction"/>
         </WL5G3N0:input>
         <WL5G3N0:output>
            <WL5G3N2:body use="literal" namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/TranslateRetailStoreTaskAction"/>
         </WL5G3N0:output>
      </WL5G3N0:operation>
   </WL5G3N0:binding>
   <WL5G3N0:service name="TranslateRetailStoreTaskActionBindingQSService">
      <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
      <WL5G3N0:port name="TranslateRetailStoreTaskActionBindingQSPort" binding="WL5G3N1:TranslateRetailStoreTaskActionBinding">
         <WL5G3N2:address location="http://172.16.19.26:7004/Capabilities/Core/RetailStore/RetailStoreEntitySvc/PS/TranslateRetailStoreTaskActionPXY"/>
      </WL5G3N0:port>
   </WL5G3N0:service>
</WL5G3N0:definitions>
