<wsdl:definitions name="ftpDownloarOrder" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/DownloadOrderService/ftpDownloarOrder" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/DownloadOrderService/ftpDownloarOrder" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:imp1="http://TargetNamespace.com/ftpDownloarOrder">
  <plt:partnerLinkType name="Prcoess_plt">
    <plt:role name="Prcoess_role">
      <plt:portType name="tns:Prcoess_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://TargetNamespace.com/ftpDownloarOrder" schemaLocation="FileEdi.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Prcoess_msg">
        <wsdl:part name="body" element="imp1:bodyFile"/>
    </wsdl:message>
    <wsdl:portType name="Prcoess_ptt">
        <wsdl:operation name="Prcoess">
            <wsdl:input message="tns:Prcoess_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>