<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/CrearTreLineaCreditoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearTreLineaCreditoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
   <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
 <wsdl:message name="CrearTreLineaCreditoRequestMessage">
  <wsdl:part name="request" element="linCrBO:CrearTreLineaCreditoRequest"/>
 </wsdl:message>
 <wsdl:message name="CrearTreLineaCreditoResponseMessage">
  <wsdl:part name="response" element="linCrBO:CrearTreLineaCreditoResponse"/>
 </wsdl:message>
 <wsdl:portType name="TreLineaCreditoPT">
  <wsdl:operation name="crearTreLineaCredito">
   <wsdl:input message="tns:CrearTreLineaCreditoRequestMessage"/>
   <wsdl:output message="tns:CrearTreLineaCreditoResponseMessage"/>
  </wsdl:operation>
 </wsdl:portType>
 <wsdl:binding name="TreLineaCredito12Bnd" type="tns:TreLineaCreditoPT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="crearTreLineaCredito">
   <soap12:operation style="document"
                     soapAction="http://www.bcie.org/CrearTreLineaCreditoService/crearTreLineaCredito"/>
   <wsdl:input>
    <soap12:body use="literal" parts="request"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="response"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
</wsdl:definitions>