
  CREATE OR REPLACE FUNCTION F_ETIQUETAS_COMISION
(
  P_ID IN VARCHAR2  
, P_ETIQUETA IN VARCHAR2  
) RETURN VARCHAR2 IS
  
  V_TIPO VARCHAR (250);

BEGIN
  CASE WHEN (P_ETIQUETA = 'Tipo de Comisión') THEN
    SELECT TC.DESCRIPCION INTO V_TIPO FROM TCA_TIPO_COMISION TTC
    JOIN TCA_COMISION TC ON (TC.ID_TCA_TIPO_COMISION = TTC.ID)
    JOIN COMISION COM ON (COM.ID_TCA_COMISION = TC.ID)
    WHERE COM.ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Descripción') THEN
    SELECT NOMBRE INTO V_TIPO FROM COMISION 
      WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Nombre') THEN
    SELECT NOMBRE INTO V_TIPO FROM COMISION 
      WHERE ID = P_ID;
      
  WHEN (P_ETIQUETA = 'Comisión Compartida') THEN
  SELECT CASE WHEN COMISION_COMPARTIDA = 1 THEN 'SI' ELSE 'NO' END AS COMISION_COMPARTIDA 
  INTO V_TIPO FROM COMISION
    WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Momento de Cobro') THEN
  SELECT TMC.DESCRIPCION INTO V_TIPO FROM TCA_MOMENTO_COBRO TMC
  JOIN COMISION COM ON (COM.ID_TCA_MOMENTO_COBRO = TMC.ID)
  WHERE COM.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Tipo Valor') THEN
  SELECT TTT.DESCRIPCION INTO V_TIPO FROM TCA_TIPO_TASA TTT
  JOIN COMISION COM ON (COM.ID_TCA_TIPO_TASA = TTT.ID)
  WHERE COM.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Valor')THEN
  SELECT CONCAT(PORCENTAJE_SOBRE_MONTO_BASE, '%') INTO V_TIPO FROM COMISION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Tipo Monto Base') THEN
  SELECT TMBC.DESCRIPCION INTO V_TIPO FROM TCA_MONTO_BASE_COMISION TMBC
  JOIN COMISION COM ON (TMBC.ID = COM.ID_TCA_MONTO_BASE)
  WHERE COM.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Importe del Monto') THEN
  SELECT TO_CHAR(MONTO_BASE,'$999,999,999,999,999.99') INTO V_TIPO FROM COMISION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Monto de la Comisión')THEN
  SELECT TO_CHAR(MONTO_COMISION,'$999,999,999,999,999.99') INTO V_TIPO FROM COMISION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Moneda')THEN
  SELECT TTM.DESCRIPCION_CORTA INTO V_TIPO FROM TCA_TIPO_MONEDA TTM
  JOIN COMISION COM ON (COM.ID_TCA_MONEDA = TTM.ID)
  WHERE COM.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Base de Cálculo')THEN
  SELECT TBC.DESCRIPCION INTO V_TIPO FROM TCA_BASE_CALCULO TBC
  JOIN COMISION COM ON(COM.ID_TCA_BASE_CALCULO = TBC.ID)
  WHERE COM.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fecha de vigencia del préstamo')THEN
  SELECT FECHA_VALOR INTO V_TIPO FROM COMISION  
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fecha de vencimiento')THEN
  SELECT FECHA_VENCIMIENTO INTO V_TIPO FROM COMISION  
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fecha de inicio de capital')THEN
  SELECT FECHA_INICIO_CAPITAL INTO V_TIPO FROM COMISION  
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Frecuencia de Pago')THEN
  SELECT FRECUENCIA_PAGO INTO V_TIPO FROM COMISION  
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Tipo de Frecuencia de Pago')THEN
  SELECT TTF.DESCRIPCION INTO V_TIPO FROM TCA_TIPO_FRECUENCIA TTF
  JOIN COMISION COM ON(COM.ID_TCA_TIPO_FRECUENCIA = TTF.ID)
  WHERE COM.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fondo al que aplica')THEN
  SELECT VF.CODE_DESC INTO V_TIPO FROM VCA_FONDO VF
  JOIN COMISION COM ON(COM.ID_TCA_FONDO = VF.MIS_CODE)
  WHERE COM.ID = P_ID;
  
  ELSE NULL;
  
  END CASE;
  
  RETURN V_TIPO;
END F_ETIQUETAS_COMISION;

/
