
  CREATE OR REPLACE FUNCTION F_ETIQUETAS_TERMINO
(P_ID VARCHAR2, P_ETIQUETA VARCHAR2)

RETURN VARCHAR2 
  IS
    V_TIPO  VARCHAR2 (250);
BEGIN
 
  CASE WHEN (P_ETIQUETA = 'Tipo Fecha de Inicio') THEN
  SELECT DISTINCT TTFI.DESCRIPCION
        INTO V_TIPO
        FROM TERMINO TER
        LEFT JOIN TCA_TERMINO TT
        ON (TER.ID_TCA_TERMINO = TT.ID)
        LEFT JOIN TCO_ATRIBUTO_TCC TAT
        ON (TAT.ID_TCA_TERMINO = TT.ID)
        LEFT JOIN TCA_TIPO_FECHA_INICIO TTFI
        ON (TER.ID_TCA_TIPO_FECHA_INICIO = TTFI.ID)
        WHERE TER.ID = P_ID;
        
  WHEN (P_ETIQUETA = 'Fecha de Inicio') THEN     
    SELECT FECHA_INICIO INTO V_TIPO FROM TERMINO WHERE ID = P_ID;  
    
  WHEN (P_ETIQUETA = 'Nombre' OR P_ETIQUETA = 'Nombre del Término' ) THEN 
    SELECT NOMBRE INTO V_TIPO FROM TERMINO WHERE ID = P_ID;  
    
  WHEN (P_ETIQUETA = 'Plazo' OR P_ETIQUETA = 'Plazo de la Línea' 
        OR P_ETIQUETA = 'Plazo de financiamiento' OR P_ETIQUETA = 'Plazo de la Garantía'
        OR P_ETIQUETA = 'Período de Gracia') THEN
    SELECT PLAZO INTO V_TIPO FROM TERMINO WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Tipo Plazo' OR P_ETIQUETA = 'Tipo Plazo de la Línea' 
          OR P_ETIQUETA = 'Tipo Plazo de financiamiento' OR P_ETIQUETA = 'Tipo Plazo de la garantía'
          OR P_ETIQUETA = 'Tipo de Período de Gracia' OR P_ETIQUETA = 'Tipo Frecuencia de Revisión'
          OR P_ETIQUETA = 'Tipo Frecuencia de Pago de Interés' OR P_ETIQUETA = 'Tipo Frecuencia de Amortización') THEN
    SELECT TFP.DESCRIPCION
        INTO V_TIPO
        FROM TCA_TIPO_FRECUENCIA TFP
        JOIN TERMINO TER
        ON (TER.ID_TCA_FRECUENCIA_PLAZO = TFP.ID)
        WHERE TER.ID = P_ID;
        
  WHEN (P_ETIQUETA = 'Fecha de vencimiento' OR P_ETIQUETA = 'Fecha máxima' OR P_ETIQUETA = 'Fecha') THEN
    SELECT FECHA_VENCIMIENTO INTO V_TIPO FROM TERMINO WHERE ID = P_ID;
    IF V_TIPO IS NULL THEN 
      SELECT FECHA INTO V_TIPO FROM TERMINO WHERE ID = P_ID AND ID_TCA_TERMINO <> 9; 
    END IF;
    
  WHEN (P_ETIQUETA = 'Descripción') THEN
    SELECT DESCRIPCION INTO V_TIPO FROM TERMINO WHERE ID = P_ID;  
      
  WHEN (P_ETIQUETA = 'Moneda') THEN
    SELECT TTM.DESCRIPCION_CORTA INTO V_TIPO FROM TCA_TIPO_MONEDA TTM
      JOIN TERMINO TER ON (TER.ID_TCA_MONEDA = TTM.ID)
      WHERE TER.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Monto') THEN
    SELECT TO_CHAR(MONTO,'$999,999,999,999,999.99')  INTO V_TIPO FROM TERMINO
      WHERE ID = P_ID;
      
  WHEN (P_ETIQUETA = 'Tasa') THEN
    SELECT TASA INTO V_TIPO FROM TERMINO
      WHERE ID = P_ID;
      
  WHEN (P_ETIQUETA = 'Tipo de Tasa') THEN
    SELECT TTT.DESCRIPCION INTO V_TIPO FROM TCA_TIPO_TASA TTT
      JOIN TERMINO TER ON (TER.ID_TCA_TIPO_TASA = TTT.ID)
    WHERE TER.ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Frecuencia de Revisión') THEN
    SELECT FRECUENCIA_REVISION INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fecha de Inicio de Revisión')THEN
    SELECT FECHA_INICIO_REVISION INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Frecuencia de Pago de Interés')THEN
    SELECT FRECUENCIA_PAGO_INTERES INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Fecha de Inicio de Pago de Interés')THEN
    SELECT FECHA_INICIO_PAGO_INTERES INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Frecuencia de Amortización') THEN
    SELECT FRECUENCIA_AMORTIZACION INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Tipo de Contraparte') THEN
    SELECT TIPO_CONTRAPARTE INTO V_TIPO FROM TERMINO 
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Monto mínimo por desembolso')THEN
    SELECT TO_CHAR(MONTO_MINIMO_DESEMBOLSO,'$999,999,999,999,999.99') INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Monto máximo por desembolso')THEN
    SELECT TO_CHAR(MONTO_MAXIMO_DESEMBOLSO,'$999,999,999,999,999.99') INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Tasa mímina por desembolso') THEN
    SELECT CONCAT(TASA_MINIMA_DESEMBOLSO, '%') INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Tasa máxima por desembolso')THEN
    SELECT CONCAT(TASA_MAXIMA_DESEMBOLSO, '%') INTO V_TIPO FROM TERMINO
    WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Fecha de Ingreso' OR P_ETIQUETA = 'Fecha de Aprobación' OR
        P_ETIQUETA = 'Fecha de firma del contrato' OR P_ETIQUETA = 'Fecha de Vigencia') THEN
    SELECT FECHA INTO V_TIPO FROM TERMINO WHERE ID = P_ID;
    
  WHEN (P_ETIQUETA = 'Aplican recursos concesionales') THEN
    SELECT  CASE WHEN SE_APLICAN_RECURSOS_CONCESION = 1 THEN 'SI' ELSE 'NO' END AS SE_APLICAN_RECURSOS_CONCESION INTO V_TIPO FROM TERMINO WHERE ID = P_ID; 
  
  ELSE NULL;
  END CASE;
  RETURN V_TIPO;
  
END F_ETIQUETAS_TERMINO;

/
