CREATE OR REPLACE TRIGGER FENIX.SEGUIMIENTO_CRED_INS_TGR
AFTER INSERT ON FENIX.SEGUIMIENTO_CREDITICIO
FOR EACH ROW
DECLARE
	v_id_tbi_seg_cred NUMBER;
  	err_num NUMBER;
	err_msg VARCHAR2(255);

BEGIN

	SELECT TBI_SEGUIMIENTO_CRED_SEQ.NEXTVAL INTO v_id_tbi_seg_cred FROM DUAL;
	  
	INSERT INTO TBI_SEGUIMIENTO_CREDITICIO(ID, ID_SEGUIMIENTO, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_seg_cred,:NEW.ID,'AGREGAR_SEGUIMIENTO',:NEW.LOGIN_USUARIO,:NEW.NOMBRE_USUARIO,SYSDATE);  
	  
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID',:NEW.ID,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_CLIENTE',:NEW.ID_CLIENTE,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'TIPO_INICIO',:NEW.TIPO_INICIO,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'TIPO_REVISION',:NEW.TIPO_REVISION,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_TCA_SCR',:NEW.ID_TCA_SCR,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_TCA_ESTADO_SCR',:NEW.ID_TCA_ESTADO_SCR,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_TCA_PERSPECTIVA',:NEW.ID_TCA_PERSPECTIVA,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ES_CALIFICACION_DIVIDIDA',:NEW.ES_CALIFICACION_DIVIDIDA,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'FECHA_APROBADO',:NEW.FECHA_APROBADO,NULL);  
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'INSTANCIA_PROCESO',:NEW.INSTANCIA_PROCESO,NULL);  
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'LOGIN_USUARIO',:NEW.LOGIN_USUARIO,NULL);  
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'NOMBRE_USUARIO',:NEW.NOMBRE_USUARIO,NULL);    
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'BAN_ESTATUS',:NEW.BAN_ESTATUS,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_FLUJO',:NEW.ID_FLUJO,NULL);  
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'LOGIN_USUARIO_ULTIMO_CAMBIO',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'NOMBRE_USUARIO_ULTIMO_CAMBIO',:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,NULL);
	INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'FECHA_ULTIMO_CAMBIO',:NEW.FECHA_ULTIMO_CAMBIO,NULL);
	 
EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SUBSTR(SQLERRM,1,250);
			
			
		DBMS_OUTPUT.put_line('Error al insertar en la tabla de bitácora de seguimiento crediticio.');		
		DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line(err_msg);
			
			
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','SEGUIMIENTO_CRED_INS_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
		COMMIT;
	
  
END;