
CREATE OR REPLACE TYPE T_ADJUNTO force as object (
ID_ADJUNTO  NUMBER (12));
/

CREATE OR REPLACE TYPE T_LISTA_ADJUNTO AS TABLE  OF T_ADJUNTO;
/

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_DOCUMENTOS (P_ADJUNTOS IN T_LISTA_ADJUNTO, P_RESULTADO OUT VARCHAR2)
IS


BEGIN

   FOR I IN 1 .. P_ADJUNTOS.COUNT
   LOOP
   
      UPDATE ADJUNTO
         SET CONTENT = NULL
       WHERE ID_ADJUNTO= P_ADJUNTOS (I).ID_ADJUNTO;

      UPDATE DOCUMENTO
         SET BAN_ESTATUS = 0
       WHERE ID_DOCUMENTO = (SELECT ID_DOCUMENTO
                               FROM ADJUNTO
                              WHERE ID_ADJUNTO = P_ADJUNTOS (I).ID_ADJUNTO);


END LOOP;

P_RESULTADO:= 'OK';

END;
/
