<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContratoByIntanciaProceso" name="ConsultarContratoByIntanciaProceso_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../../../../../ModeloNegocio/DominioContrato/Contrato/ConsultarContratoByInstanciaProceso/WSDL/ConsultarContratoByIntanciaProceso.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContratoByIntanciaProceso"/>
    <wsdl:binding name="ConsultarContratoByIntanciaProceso_ptt-binding" type="con:ConsultarContratoByIntanciaProceso_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarContratoByIntanciaProceso">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarContratoByIntanciaProcesoSelect">
            <soap:operation soapAction="ConsultarContratoByIntanciaProcesoSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>