<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://xmlns.banesco.com/eopt/PersonPartyInfoInq_V1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://www.temenos.com/T24/ofs/Response"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns1="http://www.temenos.com/T24/ofs/BPAENQCUSTOMERPNType"
                xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon"
                xmlns:ns2="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/BS_T24_BPAENQCUSTOMERPN/PersonalCustomerEnquiryPNConsultaClienteNaturalesPNResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="BPAENQCUSTOMERPNResponse"
                                       namespace="http://www.temenos.com/T24/ofs/Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Party/PersonPartyInfoInq/PersonPartyInfoInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PersonPartyInfoInqRs"
                                       namespace="http://xmlns.banesco.com/eopt/PersonPartyInfoInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE MAR 20 10:09:25 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:variable name="statusCode"
                select="DVMFunctions:lookupValue (&quot;Commons/dvm/StatusMappingBcknd&quot;, &quot;T24&quot;, /ns0:BPAENQCUSTOMERPNResponse/ResponseCommon/Status, 'CNCODE', 'M0006' )"/>
  <xsl:template match="/">
    <tns:PersonPartyInfoInqRs>
      <xsl:if test='$statusCode = "M0000" and /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN'>
        <tns:PartyKey>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ID/text()">
            <eoPar:PartyId>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ID"/>
            </eoPar:PartyId>
          </xsl:if>
          <!-- Multivaor T24-->
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTPERSONTYPE/text()">
            <eoPar:PartyType>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTPERSONTYPE"/>
            </eoPar:PartyType>
          </xsl:if>
        </tns:PartyKey>
      <xsl:if test='$statusCode = "M0000" and count(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN)'>
        <tns:PersonPartyInfo>
          <!-- Multivalor T24-->
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTMAINOFF/text()">
            <eoPar:AcctOfficial>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTMAINOFF"/>
            </eoPar:AcctOfficial>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTRELBANK/text()">
            <eoPar:BankRelType>
              <ns3:Cod>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTRELBANK"/>
              </ns3:Cod>
            </eoPar:BankRelType>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/BANPLAN/text()">
            <eoPar:ClubBanesco>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/BANPLAN"/>
            </eoPar:ClubBanesco>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CUSTOMERCLASS/text()">
            <eoPar:CustomerClass>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CUSTOMERCLASS"/>
            </eoPar:CustomerClass>
          </xsl:if>
          <!-- Multivalor T24-->
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTCUSTOMERTYP/text()">
            <eoPar:CustomerType>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTCUSTOMERTYP"/>
            </eoPar:CustomerType>
          </xsl:if>
          <!-- Se descomenta, a petición de Marlon Peña 25-07-2018 -->
          <!-- Multivalor T24-->
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ACTIVITYECONOM/text()">
            <eoPar:EconomicActivity>              
              <ns3:Cod>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ACTIVITYECONOM"/>
              </ns3:Cod>              
            </eoPar:EconomicActivity>
          </xsl:if>          
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CUSTOMERSINCE/text()">
            <eoPar:EstablishedDt>
              <xsl:value-of select="xp20:format-dateTime (/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CUSTOMERSINCE,'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' )"/>
            </eoPar:EstablishedDt>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INDUSTRY/text()">
            <eoPar:Industry>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INDUSTRY"/>
            </eoPar:Industry>
          </xsl:if>
          <!-- Multivalor T24-->
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LANGUAGE/text()">
            <eoPar:Language>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LANGUAGE"/>
            </eoPar:Language>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/MNEMONIC/text()">
            <eoPar:MNEMONIC>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/MNEMONIC"/>
            </eoPar:MNEMONIC>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPANYBOOK/text()">
            <eoPar:OriginatingBranch>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPANYBOOK"/>
            </eoPar:OriginatingBranch>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/REFERIMIENTO/text()">
            <eoPar:Referral>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/REFERIMIENTO"/>
            </eoPar:Referral>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/REFERIMIENTODAO/text()">
            <eoPar:ReferredBy>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/REFERIMIENTODAO"/>
            </eoPar:ReferredBy>
          </xsl:if>
          <!-- Multivalor T24-->
          <eoPar:ResidenceCountry>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/RESIDENCE/text()">
              <ns3:CountryCode>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/RESIDENCE"/>
              </ns3:CountryCode>
            </xsl:if>
          </eoPar:ResidenceCountry>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/VINCHANNEL/text()">
            <eoPar:SalesChannel>            
              <ns3:Value>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/VINCHANNEL"/>
              </ns3:Value>            
            </eoPar:SalesChannel>
          </xsl:if>          
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTSECOFFICER/text()">
            <eoPar:SecAcctOfficial>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTSECOFFICER"/>
            </eoPar:SecAcctOfficial>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTTCIBTYPE/text()">
            <eoPar:SecondaryUser>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTTCIBTYPE"/>
            </eoPar:SecondaryUser>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SECTOR/text()">
            <eoPar:Sector>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SECTOR"/>
            </eoPar:Sector>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTRELTYPEPA/text()">
            <eoPar:SIBRelType>
              <ns3:Cod>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTRELTYPEPA"/>
              </ns3:Cod>
            </eoPar:SIBRelType>
          </xsl:if>
          <!-- Se comenta a petición de Marlon Peña 25-07-2018 -->
          <!--eoPar:SIBRelType>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ACTIVITYECONOM/text()">
              <ns3:Cod>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ACTIVITYECONOM"/>
              </ns3:Cod>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/RELTYPESIB/text()">
              <ns3:Desc>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/RELTYPESIB"/>
              </ns3:Desc>
            </xsl:if>
          </eoPar:SIBRelType-->
          <eoPar:SubTarget>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTSUBSEGMENT/text()">
              <ns3:Cod>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTSUBSEGMENT"/>
              </ns3:Cod>
            </xsl:if>
          </eoPar:SubTarget>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/TARGET/text()">
            <eoPar:Target>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/TARGET"/>
            </eoPar:Target>
          </xsl:if>
          <eoPar:PartyStatus>
            <!--xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ISSUEDATE/text()">
              <eoPar:EffDt>
                <xsl:value-of select="xp20:format-dateTime (/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ISSUEDATE,'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' )"/>
              </eoPar:EffDt>
            </xsl:if-->
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CUSTOMERSTATUS/text()">
              <eoPar:Status>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CUSTOMERSTATUS"/>
              </eoPar:Status>
            </xsl:if>
          </eoPar:PartyStatus>
          <eoPar:CreditRisk>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CALCRISKCLASS/text()">
              <eoPar:CalcRiskClass>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CALCRISKCLASS"/>
              </eoPar:CalcRiskClass>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/MANUALRISKCLASS/text()">
              <eoPar:ManualRiskClass>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/MANUALRISKCLASS"/>
              </eoPar:ManualRiskClass>
            </xsl:if>
          </eoPar:CreditRisk>
          <eoPar:Income>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMEFREQ/text()">
              <eoPar:Freq>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMEFREQ"/>
              </eoPar:Freq>
            </xsl:if>
            <eoPar:IncomeLocation>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMEWHERE"/>
            </eoPar:IncomeLocation>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMESOURCE/text()">
              <eoPar:IncomeSource>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMESOURCE"/>
              </eoPar:IncomeSource>
            </xsl:if>
            <!-- Multivalor T24-->
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMEIN/text()">
              <eoPar:IncomeType>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INCOMEIN"/>
              </eoPar:IncomeType>
            </xsl:if>
          </eoPar:Income>
          <eoPar:PEPData>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPCOLABORADOR/text()">
              <eoPar:Collaborator>
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPCOLABORADOR, 'VALUE', '2' )"/>
              </eoPar:Collaborator>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPFAMILY/text()">
              <eoPar:Family>
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPFAMILY, 'VALUE', '2' )"/>
              </eoPar:Family>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGOVRELATION/text()">
              <eoPar:GovEntity>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGOVRELATION"/>
              </eoPar:GovEntity>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGOVERNMENT/text()">
              <eoPar:GovRelated>
                <!--xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGOVERNMENT"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGOVERNMENT, 'VALUE', '2' )"/>
              </eoPar:GovRelated>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEP/text()">
              <eoPar:IsPEP>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEP"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEP, 'VALUE', '2' )"/>
              </eoPar:IsPEP>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTORGINTERNAT/text()">
              <eoPar:OrgIntBelong>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTORGINTERNAT"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPORGINTERNAT, 'VALUE', '2' )"/>
              </eoPar:OrgIntBelong>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPPERIOD/text()">
              <eoPar:PeriodStart>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPPERIOD"/>-->
                <xsl:value-of select="concat(substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPPERIOD, 1, 4), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPPERIOD, 5, 2), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPPERIOD, 7, 2))"/>
              </eoPar:PeriodStart>
            </xsl:if>
            <xsl:for-each select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType">
              <xsl:if test="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEP, 'VALUE', '2' )='true'">
                <eoPar:PEPRelated>
                  <xsl:if test="PEPCOUNTRY/text()">
                    <eoPar:Country>                  
                      <ns3:CountryCode>
                        <xsl:value-of select="PEPCOUNTRY"/>
                      </ns3:CountryCode>                  
                      <!-- Se cambia mapeo, a PersonPartyInfo.PEPData.PEPRelated.PersonData.IssuedIdent.IssuedLoc.Value  -->
                      <!--xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPCOUNTRYID/text()">
                    <ns3:CountryName>
                    <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PEPCOUNTRYID"/>
                  </ns3:CountryName-->                
                    </eoPar:Country>
                  </xsl:if>                
                  <eoPar:PersonData>
                    <!-- Multivalor T24-->
                    <xsl:if test="PEPNATIONALITY/text()">
                      <eoPar:Nationality>
                        <xsl:value-of select="PEPNATIONALITY"/>
                      </eoPar:Nationality>
                    </xsl:if>                 
                    <eoPar:IssuedIdent>
                      <xsl:if test="PEPLEGALID/text()">
                        <eoPar:Ident>                     
                          <eoPar:IssuedIdentValue>
                            <xsl:value-of select="PEPLEGALID"/>
                          </eoPar:IssuedIdentValue>                      
                        </eoPar:Ident>
                      </xsl:if>                    
                      <!-- Multivalor T24-->
                      <xsl:if test="PEPCOUNTRYID/text()">
                        <eoPar:IssuedLoc>
                          <ns3:Value>
                            <xsl:value-of select="PEPCOUNTRYID"/>
                          </ns3:Value>
                        </eoPar:IssuedLoc>
                      </xsl:if>                  
                    </eoPar:IssuedIdent>
                    <xsl:if test="PEPNAME/text()">
                      <eoPar:PersonName>                    
                        <eoPar:FullName>
                          <xsl:value-of select="PEPNAME"/>
                        </eoPar:FullName>                    
                      </eoPar:PersonName>
                    </xsl:if>                  
                  </eoPar:PersonData>
                  <!-- Multivalor T24-->
                  <xsl:if test="PEPPUBLICPOS/text()">
                    <eoPar:PublicPos>
                      <xsl:value-of select="PEPPUBLICPOS"/>
                    </eoPar:PublicPos>
                  </xsl:if>
                  <!-- Multivalor T24-->
                  <xsl:if test="PEPRELTYPE/text()">
                    <eoPar:RelType>
                      <xsl:value-of select="PEPRELTYPE"/>
                    </eoPar:RelType>
                  </xsl:if>
                </eoPar:PEPRelated>
              </xsl:if>              
            </xsl:for-each>            
          </eoPar:PEPData>
          <eoPar:FATCA>
            <!-- Multivalor T24-->
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CLIENTTYPE/text()">
              <eoPar:FatcaType>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/CLIENTTYPE"/>
              </eoPar:FatcaType>
            </xsl:if>
            <!-- Multivalor T24-->
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FORMTYPE/text()">
              <eoPar:FormId>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FORMTYPE"/>
              </eoPar:FormId>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/GREENCARD/text()">
              <eoPar:GreenCard>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/GREENCARD"/>
              </eoPar:GreenCard>
            </xsl:if>
            <!-- Multivalor T24-->
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCANATIONAL/text()">
              <eoPar:OtherNationality>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCANATIONAL"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCANATIONAL, 'VALUE', '2' )"/>
              </eoPar:OtherNationality>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/TINCODE/text()">
              <eoPar:TIN>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/TINCODE"/>
              </eoPar:TIN>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUS183/text()">
              <eoPar:US183Permanence>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUS183"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUS183, 'VALUE', '2' )"/>
              </eoPar:US183Permanence>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSRELATED/text()">
              <eoPar:USRelated>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSRELATED"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSRELATED, 'VALUE', '2' )"/>
              </eoPar:USRelated>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSRESID/text()">
              <eoPar:USResid>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSRESID"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSRESID, 'VALUE', '2' )"/>
              </eoPar:USResid>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSSIGNOR/text()">
              <eoPar:USSignor>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSSIGNOR"/>-->
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FATCAUSSIGNOR, 'VALUE', '2' )"/>
              </eoPar:USSignor>
            </xsl:if>
          </eoPar:FATCA>
          <xsl:for-each select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType">
            <xsl:if test="RELCUSTOMER/text()">
              <eoPar:CRMRel>
                <!-- Multivalor T24-->              
                <eoPar:CustomerId>
                  <xsl:value-of select="RELCUSTOMER"/>
                </eoPar:CustomerId>              
                <!-- Multivalor T24-->
                <xsl:if test="RELATIONCODE/text()">
                  <eoPar:RelationshipType>                
                    <ns3:Cod>
                      <xsl:value-of select="RELATIONCODE"/>
                    </ns3:Cod>                
                  </eoPar:RelationshipType>
                </xsl:if>              
              </eoPar:CRMRel>
            </xsl:if>            
          </xsl:for-each>          
          <eoPar:CostCenter>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ACCOUNTOFFICER/text()">
              <ns3:CostCenterId>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/ACCOUNTOFFICER"/>
              </ns3:CostCenterId>
            </xsl:if>
          </eoPar:CostCenter>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/NOOFDEPENDENTS/text()">
            <eoPar:Dependents>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/NOOFDEPENDENTS"/>
            </eoPar:Dependents>
          </xsl:if>          
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EDUCATIONLEVEL/text()">
            <eoPar:EducationLevel>
              <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EDUCATIONLEVEL"/>
            </eoPar:EducationLevel>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/DATELASTVERIFIED/text()">
            <eoPar:LastUpDt>
              <xsl:value-of select="xp20:format-dateTime (/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/DATELASTVERIFIED,'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' )"/>
            </eoPar:LastUpDt>
          </xsl:if>
          <eoPar:MaritalStat>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/MARITALSTATUS/text()">
              <ns3:Value>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/MARITALSTATUS"/>
              </ns3:Value>
            </xsl:if>
          </eoPar:MaritalStat>
          <eoPar:Profession>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PROFESSION/text()">
              <ns3:Value>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PROFESSION"/>
              </ns3:Value>
            </xsl:if>
          </eoPar:Profession>
          <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SOCIALSECNO/text()">
              <eoPar:SocialSecNumber>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SOCIALSECNO"/>
              </eoPar:SocialSecNumber>
            </xsl:if>
          <eoPar:PersonData>
            <eoPar:Contact>
              <ns3:Locator>
                <!-- Multivalor T24-->
                <xsl:for-each select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType">
                  <xsl:if test="EMAIL1/text()">
                    <ns3:Email>                    
                      <ns3:Value>
                        <xsl:value-of select="EMAIL1"/>
                      </ns3:Value>                    
                    </ns3:Email>
                  </xsl:if>                  
                </xsl:for-each>
                <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FACEBOOK/text()">
                  <ns3:SocialMedia>
                    <ns3:Type>Facebook</ns3:Type>
                    <ns3:Value>
                      <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/FACEBOOK"/>
                    </ns3:Value>
                  </ns3:SocialMedia>
                </xsl:if>
                <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INSTAGRAM/text()">
                  <ns3:SocialMedia>
                    <ns3:Type>Instagram</ns3:Type>
                    <ns3:Value>
                      <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/INSTAGRAM"/>
                    </ns3:Value>
                  </ns3:SocialMedia>
                </xsl:if>
                <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/TWITTER/text()">
                  <ns3:SocialMedia>
                    <ns3:Type>Twitter</ns3:Type>
                    <ns3:Value>
                      <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/TWITTER"/>
                    </ns3:Value>
                  </ns3:SocialMedia>
                </xsl:if>                  
                  <xsl:for-each select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType">
                  <ns3:PostAddr>
                    <!-- Multivalor T24-->
                    <xsl:if test="ADDRESS/text()">
                      <ns3:AddrDesc>
                        <xsl:value-of select="ADDRESS"/>
                      </ns3:AddrDesc>
                    </xsl:if>
                    <xsl:if test="LTBUILDING/text()">
                      <ns3:Building>                      
                        <ns3:Desc>
                          <xsl:value-of select="LTBUILDING"/>
                        </ns3:Desc>                      
                      </ns3:Building>
                    </xsl:if>                   
                    <!-- Multivalor T24-->
                    <xsl:if test="TOWNCOUNTRY/text()">
                      <ns3:City>                      
                        <ns3:Cod>
                          <xsl:value-of select="TOWNCOUNTRY"/>
                        </ns3:Cod>                      
                      </ns3:City>
                    </xsl:if>    
                    <xsl:if test="LTDISTRICT/text()">
                      <ns3:CountyDistrict>                      
                        <ns3:Cod>
                          <xsl:value-of select="LTDISTRICT"/>
                        </ns3:Cod>                      
                      </ns3:CountyDistrict>
                    </xsl:if>                   
                    <!-- Multivalor T24-->
                    <xsl:if test="LTHOUSENO/text()">
                      <ns3:HouseNumber>
                        <xsl:value-of select="LTHOUSENO"/>
                      </ns3:HouseNumber>
                    </xsl:if>
                    <xsl:if test="LTSECTOR/text()">
                      <ns3:Jurisdiction>                      
                        <ns3:Cod>
                          <xsl:value-of select="LTSECTOR"/>
                        </ns3:Cod>                      
                      </ns3:Jurisdiction>
                    </xsl:if>                    
                    <xsl:if test="POSTCODE/text()">
                      <ns3:PostalCode>
                        <xsl:value-of select="POSTCODE"/>
                      </ns3:PostalCode>
                    </xsl:if>
                    <xsl:if test="LTPROVINCE/text()">
                      <ns3:Province>                      
                        <ns3:Cod>
                          <xsl:value-of select="LTPROVINCE"/>
                        </ns3:Cod>                      
                      </ns3:Province>
                    </xsl:if>                    
                    <xsl:if test="STREET/text()">
                      <ns3:Street>
                        <xsl:value-of select="STREET"/>
                      </ns3:Street>
                    </xsl:if>
                    <xsl:if test="COUNTRY/text()">
                      <ns3:Country>                      
                        <ns3:CountryCode>
                          <xsl:value-of select="COUNTRY"/>
                        </ns3:CountryCode>                      
                      </ns3:Country>
                    </xsl:if>                    
                  </ns3:PostAddr>
                </xsl:for-each> 
                <xsl:for-each select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType">
                  <xsl:if test="PHONE1/text()">
                    <ns3:Phone>                    
                      <ns3:PhoneNum>
                        <xsl:value-of select="PHONE1"/>
                      </ns3:PhoneNum>
                      <ns3:PhoneType>Home</ns3:PhoneType>                    
                    </ns3:Phone>
                  </xsl:if>
                  <xsl:if test="SMS1/text()">
                    <ns3:Phone>
                      <xsl:if test="SMS1">
                        <ns3:AreaCode>
                          <xsl:value-of select="LTPHONECODE"/>
                        </ns3:AreaCode>
                      </xsl:if>
                      <!-- Multivalor T24-->                      
                      <ns3:PhoneNum>
                        <xsl:value-of select="SMS1"/>
                      </ns3:PhoneNum>
                      <ns3:PhoneType>Mobile</ns3:PhoneType>                      
                    </ns3:Phone>
                  </xsl:if>
                  <xsl:if test="FAX1/text()">
                    <ns3:Phone>                    
                      <ns3:PhoneNum>
                        <xsl:value-of select="FAX1"/>
                      </ns3:PhoneNum>
                      <ns3:PhoneType>Fax</ns3:PhoneType>                    
                    </ns3:Phone>
                  </xsl:if>                  
                </xsl:for-each>                
              </ns3:Locator>
            </eoPar:Contact>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/NATIONALITY/text()">
              <eoPar:Nationality>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/NATIONALITY"/>
              </eoPar:Nationality>
            </xsl:if>
            <xsl:for-each select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType">
              <eoPar:IssuedIdent>
                <!-- Multivalor T24-->
                <xsl:if test="LEGALEXPDATE/text()">
                  <eoPar:ExpDt>
                    <xsl:value-of select="xp20:format-dateTime (LEGALEXPDATE,'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' )"/>
                  </eoPar:ExpDt>
                </xsl:if>
                <eoPar:Ident>
                  <xsl:if test="LEGALDOCNAME/text()">
                    <eoPar:IssuedIdentType>
                      <xsl:value-of select="LEGALDOCNAME"/>
                    </eoPar:IssuedIdentType>
                  </xsl:if>
                  <!-- Multivalor T24-->
                  <xsl:if test="LEGALID/text()">
                    <eoPar:IssuedIdentValue>
                      <xsl:value-of select="LEGALID"/>
                    </eoPar:IssuedIdentValue>
                  </xsl:if>
                </eoPar:Ident>
                <!-- multivalor T24-->
                <xsl:if test="LEGALISSAUTH/text()">
                  <eoPar:IssuedLoc>                  
                    <ns3:Value>
                      <xsl:value-of select="LEGALISSAUTH"/>
                    </ns3:Value>                  
                  </eoPar:IssuedLoc>
                </xsl:if>                
                <xsl:if test="LEGALISSDATE/text()">
                  <eoPar:IssueDt>
                    <xsl:value-of select="xp20:format-dateTime (LEGALISSDATE,'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]' )"/>
                  </eoPar:IssueDt>
                </xsl:if>
              </eoPar:IssuedIdent>
            </xsl:for-each>            
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/DATEOFBIRTH/text()">
              <eoPar:BirthDt>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/DATEOFBIRTH"/>
              </eoPar:BirthDt>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/GENDER/text()">
              <eoPar:Gender>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/GENDER"/>
              </eoPar:Gender>
            </xsl:if>
            <eoPar:PersonName>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGIVENNAME">
                <eoPar:FirstName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTGIVENNAME"/>
                </eoPar:FirstName>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTFULLNAME/text()">
                <eoPar:FullName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTFULLNAME"/>
                </eoPar:FullName>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTFAMILYNAME/text()">
                <eoPar:LastName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTFAMILYNAME"/>
                </eoPar:LastName>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTMARRIEDNAME/text()">
                <eoPar:MarriedName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTMARRIEDNAME"/>
                </eoPar:MarriedName>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTFAMILYNAME2/text()">
                <eoPar:SecondLastName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTFAMILYNAME2"/>
                </eoPar:SecondLastName>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTMIDDLENAME/text()">
                <eoPar:SecondName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/LTMIDDLENAME"/>
                </eoPar:SecondName>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SHORTNAME/text()">
                <eoPar:ShortName>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SHORTNAME"/>
                </eoPar:ShortName>
              </xsl:if>
            </eoPar:PersonName>
          </eoPar:PersonData>
          <eoPar:Employment>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTSTART/text()">
              <eoPar:EmploymentStartDt>
                <!--<xsl:value-of select="xp20:format-dateTime(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTSTART,'[Y0001]-[M01]-[D01]T[H01]:[m01]:[s01]')"/>-->
                <xsl:value-of select="concat(substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTSTART, 1, 4), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTSTART, 5, 2), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTSTART, 7, 2))"/>
              </eoPar:EmploymentStartDt>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPTROFFID/text()">
              <eoPar:GovermentId>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPTROFFID"/>
              </eoPar:GovermentId>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/JOBTITLE/text()">
              <eoPar:JobTitle>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/JOBTITLE"/>
              </eoPar:JobTitle>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPEND/text()">
              <eoPar:PrevEmploymentEndDt>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPEND"/>-->
                <xsl:value-of select="concat(substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPEND, 1, 4), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPEND, 5, 2), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPEND, 7, 2))"/>
              </eoPar:PrevEmploymentEndDt>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPSTART/text()">
              <eoPar:PrevEmploymentStartDt>
                <!--<xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPSTART"/>-->
                <xsl:value-of select="concat(substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPSTART, 1, 4), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPSTART, 5, 2), '-', substring(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/PREVEMPSTART, 7, 2))"/>
              </eoPar:PrevEmploymentStartDt>
            </xsl:if>
            <eoPar:Salary>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SALARY/text()">
                <ns3:Amt>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SALARY"/>
                </ns3:Amt>
              </xsl:if>
            </eoPar:Salary>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SALARYTYPE/text()">
              <eoPar:SalaryFreq>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SALARYTYPE"/>
              </eoPar:SalaryFreq>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SALARYRANGE/text()">
              <eoPar:SalaryRange>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SALARYRANGE"/>
              </eoPar:SalaryRange>
            </xsl:if>
            <eoPar:TimeFrame>
              <ns3:Duration>
                <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTTIME/text()">
                  <ns3:Desc>
                    <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTTIME"/>
                    <!--<xsl:value-of select="translate(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTTIME, translate(/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYMENTTIME,'0123456789',''), '')"/>-->
                  </ns3:Desc>
                </xsl:if>
              </ns3:Duration>
            </eoPar:TimeFrame>
            <eoPar:OrgData>
              <eoPar:Contact>
                <ns3:Locator>
                  <ns3:PostAddr>
                    <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPREFERENCE/text()">
                      <ns3:AddrDesc>
                        <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPREFERENCE"/>
                      </ns3:AddrDesc>
                    </xsl:if>
                    <ns3:Building>
                      <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPBUILDING/text()">
                        <ns3:Desc>
                          <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPBUILDING"/>
                        </ns3:Desc>
                      </xsl:if>
                    </ns3:Building>
                    <ns3:City>
                      <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPTOWN/text()">
                        <ns3:Cod>
                          <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPTOWN"/>
                        </ns3:Cod>
                      </xsl:if>
                    </ns3:City>
                    <ns3:CountyDistrict>
                      <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPDISTRICT/text()">
                        <ns3:Cod>
                          <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPDISTRICT"/>
                        </ns3:Cod>
                      </xsl:if>
                    </ns3:CountyDistrict>
                    <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPOFFICE/text()">
                      <ns3:HouseNumber>
                        <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPOFFICE"/>
                      </ns3:HouseNumber>
                    </xsl:if>
                    <ns3:Jurisdiction>
                      <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPSECTOR/text()">
                        <ns3:Cod>
                          <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPSECTOR"/>
                        </ns3:Cod>
                      </xsl:if>
                    </ns3:Jurisdiction>
                    <ns3:Province>
                      <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPPROVINCE/text()">
                        <ns3:Cod>
                          <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPPROVINCE"/>
                        </ns3:Cod>
                      </xsl:if>
                    </ns3:Province>
                    <ns3:Country>
                      <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPCOUNTRY/text()">
                        <ns3:CountryCode>
                          <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPCOUNTRY"/>
                        </ns3:CountryCode>
                      </xsl:if>
                    </ns3:Country>
                  </ns3:PostAddr>
                  <ns3:Phone>
                    <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OFFPHONE/text()">
                      <ns3:PhoneNum>
                        <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OFFPHONE"/>
                      </ns3:PhoneNum>
                    <ns3:PhoneType>Office</ns3:PhoneType>
                    </xsl:if>
                  </ns3:Phone>
                </ns3:Locator>
              </eoPar:Contact>
              <eoPar:IssuedIdent>
                <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPANYID/text()">
                  <eoPar:Ident>
                    <eoPar:IssuedIdentValue>
                      <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPANYID"/>
                    </eoPar:IssuedIdentValue>
                  </eoPar:Ident>
                </xsl:if>
              </eoPar:IssuedIdent>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/BUSSINESSTYPE/text()">
                <eoPar:BusinessType>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/BUSSINESSTYPE"/>
                </eoPar:BusinessType>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPANYTYPE/text()">
                <eoPar:Type>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/COMPANYTYPE"/>
                </eoPar:Type>
              </xsl:if>
              <eoPar:OrgName>
                <!-- Se quita mapeo a petición de cambio por Marlon Peña 07-08-2018 -->
                <!--xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SHORTNAME/text()">
                  <eoPar:BusinessName>
                    <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/SHORTNAME"/>
                  </eoPar:BusinessName>
                </xsl:if-->
                <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYERSNAME/text()">
                  <eoPar:FullName>
                    <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYERSNAME"/>
                  </eoPar:FullName>
                </xsl:if>
              </eoPar:OrgName>
            </eoPar:OrgData>
            <eoPar:OtherIncome>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERINCOME/text()">
                <eoPar:IncomeAmt>                
                  <ns3:Amt>
                    <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERINCOME"/>
                  </ns3:Amt>                
                </eoPar:IncomeAmt>
              </xsl:if>              
              <eoPar:IncomeLocation>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERWHERE"/>
              </eoPar:IncomeLocation>              
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERINCSOURCE/text()">
                <eoPar:IncomeSource>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERINCSOURCE"/>
                </eoPar:IncomeSource>
              </xsl:if>
              <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERIN/text()">
                <eoPar:IncomeType>
                  <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/OTHERIN"/>
                </eoPar:IncomeType>
              </xsl:if>
            </eoPar:OtherIncome>
          </eoPar:Employment>
          <eoPar:EmployeeData>
            <xsl:if test="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYEENUMBER/text()">
              <eoPar:EmployeeNumber>
                <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/BPAENQCUSTOMERPN/gBPAENQCUSTOMERPNDetailType/mBPAENQCUSTOMERPNDetailType[1]/EMPLOYEENUMBER"/>
              </eoPar:EmployeeNumber>
            </xsl:if>
          </eoPar:EmployeeData>
        </tns:PersonPartyInfo>
      </xsl:if>
      </xsl:if>
      <tns:Status>
        <eoStatus:StatusCode>
          <xsl:value-of select="$statusCode"/>
        </eoStatus:StatusCode>
        <eoStatus:StatusDesc>
          <xsl:value-of select="DVMFunctions:lookupValue (&quot;Commons/dvm/StatusMappingBcknd&quot;, &quot;T24&quot;, /ns0:BPAENQCUSTOMERPNResponse/ResponseCommon/Status, 'CNDESC', 'FALLO EN LA OPERACION')"/>
        </eoStatus:StatusDesc>
        <eoStatus:AdditionalStatus>
          <eoStatus:StatusCode>
            <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/ResponseCommon/Status"/>
          </eoStatus:StatusCode>
          <eoStatus:StatusDesc>
            <xsl:value-of select="/ns0:BPAENQCUSTOMERPNResponse/ResponseCommon/Message"/>
          </eoStatus:StatusDesc>
        </eoStatus:AdditionalStatus>
      </tns:Status>
    </tns:PersonPartyInfoInqRs>
  </xsl:template>
</xsl:stylesheet>