<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarCommitmentSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarCommitmentSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linMO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarCommitmentSAD/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarCommitmentMessage">
    <part name="request" element="linMO:ConsultarCommitmentRequest"/>
  </message>
  <message name="responseConsultarCommitmentMessage">
    <part name="response" element="linMO:ConsultarCommitmentResponse"/>
  </message>
  <portType name="ConsultarCommitment_PT">
    <operation name="consultarCommitment">
      <input message="tns:requestConsultarCommitmentMessage"/>
      <output message="tns:responseConsultarCommitmentMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarCommitment_PTSOAP12Binding" type="tns:ConsultarCommitment_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarCommitment">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ConsultarCommitmentSAD/consultarCommitment"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>