<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarProgramacionPYD" 
            xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarProgramacionPYD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:liMO="http://www.bcie.org/LineaCreditoMO">
   <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarProgramacionPYD/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
 <message name="requestConsultarProgramacionPYDMessage">
  <part name="request" element="liMO:ConsultarProgramacionPYDRequest"/>
 </message>
 <message name="responseConsultarProgramacionPYDMessage">
  <part name="response" element="liMO:ConsultarProgramacionPYDResponse"/>
 </message>
 <portType name="ConsultarProgramacionPYD_PT">
  <operation name="ConsultarProgramacionPYD">
   <input message="tns:requestConsultarProgramacionPYDMessage"/>
   <output message="tns:responseConsultarProgramacionPYDMessage"/>
  </operation>
 </portType>
 <binding name="ConsultarProgramacionPYD_PTSOAP12Binding" type="tns:ConsultarProgramacionPYD_PT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="ConsultarProgramacionPYD">
   <soap12:operation style="document"
                     soapAction="http://www.bcie.org/ConsultarProgramacionPYD/ConsultarProgramacionPYD"/>
   <input>
    <soap12:body use="literal" parts="request"/>
   </input>
   <output>
    <soap12:body use="literal" parts="response"/>
   </output>
  </operation>
 </binding>
</definitions>