<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:EliminarLineaCreditoSAD" 
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:EliminarLineaCreditoSAD" 
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="EliminarLineaCreditoRequestMessage">
    <part name="EliminarLineaCreditoRequest" element="linCrBO:EliminarLineaCreditoRequest"/>
  </message>
  <message name="EliminarLineaCreditoResponseMessage">
    <part name="EliminarLineaCreditoResponse" element="linCrBO:EliminarLineaCreditoResponse"/>
  </message>
  <portType name="EliminarLineaCreditoPT">
    <operation name="EliminarLineaCreditoRequest">
      <input message="tns:EliminarLineaCreditoRequestMessage"/>
      <output message="tns:EliminarLineaCreditoResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarLineaCreditoPTSOAP12Binding" type="tns:EliminarLineaCreditoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="EliminarLineaCreditoRequest">
      <soap12:operation style="document" soapAction="urn:EliminarLineaCreditoSAD/EliminarLineaCreditoRequest"/>
      <input>
        <soap12:body use="literal" parts="EliminarLineaCreditoRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="EliminarLineaCreditoResponse"/>
      </output>
    </operation>
  </binding>
</definitions>