<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/TBILineaCreditoConsultarSAD" 
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/TBILineaCreditoConsultarSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:liMO="http://www.bcie.org/LineaCreditoMO">
	<types>
		<xsd:schema targetNamespace="http://www.bcie.org/TBILineaCreditoConsultarSAD/types" elementFormDefault="qualified">
			<xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
		</xsd:schema>
	</types>
	<message name="TBILineaCreditoConsultarRequestMessage">
		<part name="request" element="liMO:TBILineaCreditoConsultarRequest"/>
	</message>
	<message name="TBILineaCreditoConsultarResponseMessage">
		<part name="response" element="liMO:TBILineaCreditoConsultarResponse"/>
	</message>
	<portType name="TBILineaCreditoConsultar_PT">
		<operation name="TBILineaCreditoConsultar">
			<input message="tns:TBILineaCreditoConsultarRequestMessage"/>
			<output message="tns:TBILineaCreditoConsultarResponseMessage"/>
		</operation>
	</portType>
	<binding name="TBILineaCreditoConsultar_PT12Bnd" type="tns:TBILineaCreditoConsultar_PT">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="TBILineaCreditoConsultar">
			<soap12:operation style="document" soapAction="http://www.bcie.org/LineaCreditoService/TBILineaCreditoConsultar"/>
			<input>
				<soap12:body use="literal" parts="request"/>
			</input>
			<output>
				<soap12:body use="literal" parts="response"/>
			</output>
		</operation>
	</binding>
</definitions>