<wsdl:definitions name="CreateItemRMS" targetNamespace="http://www.agarcia.mx/ServiceBus/Item" xmlns:tns="http://www.agarcia.mx/ServiceBus/Item" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ebm="http://www.agarcia.mx/EnterpriseObjects/Item" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Item" schemaLocation="../../EnterpriseObjectLibrary/EBO/Item/ItemEBM.xsd"/>
        </xsd:schema>   
    </wsdl:types>
    <wsdl:message name="CreateItemEBM">
        <wsdl:part name="CreateItemEBM" element="ebm:CreateItemEBM"/>
    </wsdl:message>
     <wsdl:message name="CreateItemResponseEBM">
        <wsdl:part name="CreateItemResponseEBM" element="ebm:CreateItemResponseEBM"/>
    </wsdl:message>    
    <wsdl:portType name="ItemRMSService_ptt">
    <wsdl:operation name="CreateItem">
      <wsdl:input message="tns:CreateItemEBM"/>
      <wsdl:output message="tns:CreateItemResponseEBM"/>      
    </wsdl:operation>
  </wsdl:portType>
    
</wsdl:definitions>