<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="www.bcie.org/CrearActualizarDetalleTransaccionSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="www.bcie.org/CrearActualizarDetalleTransaccionSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="www.bcie.org/CrearActualizarDetalleTransaccionSAD/types"
                elementFormDefault="qualified">
         <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
    </xsd:schema> 
  </types>
  <message name="CrearActualizarDetalleTransaccionSADRequestMessage">
    <part name="CrearActualizarDetalleTransaccionSADRequest" element="desMO:CrearActualizarDetalleTransaccionRequest"/>
  </message>
  <message name="CrearActualizarDetalleTransaccionSADResponseMessage">
    <part name="CrearActualizarDetalleTransaccionSADResponse"
          element="desMO:CrearActualizarDetalleTransaccionResponse"/>
  </message>
  <portType name="crearActualizarDetalleTransaccionSAD_pt">
    <operation name="crearActualizarDetalleTransaccionSAD">
      <input message="tns:CrearActualizarDetalleTransaccionSADRequestMessage"/>
      <output message="tns:CrearActualizarDetalleTransaccionSADResponseMessage"/>
    </operation>
  </portType>
  <binding name="crearActualizarDetalleTransaccionSAD_pt12Bnd" type="tns:crearActualizarDetalleTransaccionSAD_pt">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearActualizarDetalleTransaccionSAD">
      <soap12:operation style="document"
                        soapAction="www.bcie.org/CrearActualizarDetalleTransaccionSAD/crearActualizarDetalleTransaccionSAD"/>
      <input>
        <soap12:body use="literal" parts="CrearActualizarDetalleTransaccionSADRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="CrearActualizarDetalleTransaccionSADResponse"/>
      </output>
    </operation>
  </binding>
</definitions>