<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearActualizarReglasDesembolso"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/CrearActualizarReglasDesembolso"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearActualizarReglasDesembolso/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestCrearActualizarReglasDesembolsoMessage">
    <part name="request" element="desMO:CrearActualizarReglasDesembolsoRequest"/>
  </message>
  <message name="responseCrearActualizarReglasDesembolsoMessage">
    <part name="response" element="desMO:CrearActualizarReglasDesembolsoResponse"/>
  </message>
  <portType name="CrearActualizarReglasDesembolso">
    <operation name="crearActualizarReglasDesembolso">
      <input message="tns:requestCrearActualizarReglasDesembolsoMessage"/>
      <output message="tns:responseCrearActualizarReglasDesembolsoMessage"/>
    </operation>
  </portType>
  <binding name="CrearActualizarReglasDesembolsoSOAP12Binding" type="tns:CrearActualizarReglasDesembolso">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearActualizarReglasDesembolso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearActualizarReglasDesembolso/crearActualizarReglasDesembolso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>