<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearReservaFondosMFCSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearReservaFondosMFCSAD"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearReservaFondosMFCSAD/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestCrearReservaFondosMFCMessage">
    <part name="request" element="desMO:CrearReservaFondosMFCRequest"/>
  </message>
  <message name="responseCrearReservaFondosMFCMessage">
    <part name="response" element="desMO:CrearReservaFondosMFCResponse"/>
  </message>
  <portType name="CrearReservaFondosMFC_PT">
    <operation name="crearReservaFondosMFC">
      <input message="tns:requestCrearReservaFondosMFCMessage"/>
      <output message="tns:responseCrearReservaFondosMFCMessage"/>
    </operation>
  </portType>
  <binding name="CrearReservaFondosMFC_PTSOAP12Binding" type="tns:CrearReservaFondosMFC_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearReservaFondosMFC">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearReservaFondosMFCSAD/crearReservaFondosMFC"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>