<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidarF1SAD"
     targetNamespace="http://www.bcie.org/ValidarF1SAD"
     xmlns:tns="http://www.bcie.org/ValidarF1SAD"
     xmlns:desMO="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestValidarF1Message">
        <wsdl:part name="request" element="desMO:ValidarF1Request"/>
    </wsdl:message>
    <wsdl:message name="responseValidarF1Message">
        <wsdl:part name="response" element="desMO:ValidarF1Response"/>
    </wsdl:message>
    <wsdl:portType name="ValidarF1_PT">
        <wsdl:operation name="ValidarF1">
            <wsdl:input message="tns:requestValidarF1Message"/>
            <wsdl:output message="tns:responseValidarF1Message"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarF1_PTSOAP12Binding" type="tns:ValidarF1_PT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ValidarF1">
            <soap12:operation style="document" soapAction="ValidarF1" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
