<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bice.org/ActualizarLineaCreditoService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:tns="http://www.bice.org/ActualizarLineaCreditoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
             
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="PropagarFuenteLineaCreditoRequestMessage">
    <part name="request" element="linCrBO:PropagarFuenteLCRequest"/>
  </message>
  <message name="PropagarFuenteLineaCreditoResponseMessage">
    <part name="response" element="linCrBO:PropagarFuenteLCResponse"/>
  </message>
  <portType name="PropagarFueteLCPT">
    <operation name="propagarFuente">
      <input message="tns:PropagarFuenteLineaCreditoRequestMessage"/>
      <output message="tns:PropagarFuenteLineaCreditoResponseMessage"/>
    </operation>
  </portType>
  <binding name="PropagarFueteLCPT12Bnd" type="tns:PropagarFueteLCPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="propagarFuente">
      <soap12:operation style="document" soapAction="http://www.bice.org/ActualizarLineaCreditoService/propagarFuente"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>