<wsdl:definitions name="ConsultarDetalleTransaccionDesembolso_db" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDetalleTransaccionDesembolso/ConsultarDetalleTransaccionDesembolso_db" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDetalleTransaccionDesembolso/ConsultarDetalleTransaccionDesembolso_db" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleTransaccionDesembolso_db" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarDetalleTransaccionDesembolso_db_plt">
    <plt:role name="ConsultarDetalleTransaccionDesembolso_db_role">
      <plt:portType name="tns:ConsultarDetalleTransaccionDesembolso_db_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleTransaccionDesembolso_db" schemaLocation="../XSD/ConsultarDetalleTransaccionByIdDesembolso.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarDetalleTransaccionDesembolso_dbInput_msg">
        <wsdl:part name="ConsultarDetalleTransaccionDesembolso_dbInput_msg" element="db:ConsultarDetalleTransaccionDesembolso_dbInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarDetalleTransaccionDesembolso_dbOutputCollection_msg">
        <wsdl:part name="ConsultarDetalleTransaccionDesembolso_dbOutputCollection" element="db:ConsultarDetalleTransaccionDesembolso_dbOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarDetalleTransaccionDesembolso_db_ptt">
        <wsdl:operation name="ConsultarDetalleTransaccionDesembolso_db">
            <wsdl:input message="tns:ConsultarDetalleTransaccionDesembolso_dbInput_msg"/>
            <wsdl:output message="tns:ConsultarDetalleTransaccionDesembolso_dbOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>