<wsdl:definitions name="caseThreeCatalogTranslate" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeCatalogTranslate" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeCatalogTranslate" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseThreeCatalogTranslate" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="caseThreeCatalogTranslate_plt">
    <plt:role name="caseThreeCatalogTranslate_role">
      <plt:portType name="tns:caseThreeCatalogTranslate_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseThreeCatalogTranslate" schemaLocation="caseThreeCatalogTranslate_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="caseThreeCatalogTranslateSelect_inputParameters">
        <wsdl:part name="caseThreeCatalogTranslateSelect_inputParameters" element="top:caseThreeCatalogTranslateSelect_idC3_appCodeC3_catIdC3_targetAppCodeC3InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmItemsCatalogsCollection_msg">
        <wsdl:part name="MdmItemsCatalogsCollection" element="top:MdmItemsCatalogsCollection"/>
    </wsdl:message>
    <wsdl:portType name="caseThreeCatalogTranslate_ptt">
        <wsdl:operation name="caseThreeCatalogTranslateSelect">
            <wsdl:input message="tns:caseThreeCatalogTranslateSelect_inputParameters"/>
            <wsdl:output message="tns:MdmItemsCatalogsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>