<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ConsultarHerramientaCE"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ConsultarHerramientaCE"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarHerramientaCE_SB">
        <plnk:role name="ConsultarHerramientaCE_PT" portType="tns:ConsultarHerramientaCE_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ConsultarHerramientaCE" location="oramds:/apps/Resources/ComponentesComunes/DominioHerramientaCE/HerramientaCE/V1/Wsdl/ADAPTER/ConsultarHerramientaCESAD.wsdl"/>
</wsdl:definitions>
