DROP TABLE FENIX.TCA_TAREA_CON_BTN_DIN;

CREATE TABLE TCA_TAREA_CON_BTN_DIN 
(
  ID NUMBER NOT NULL,
  COMPONENTE VARCHAR2(50) NOT NULL,
  ID_TAREA_BPM NUMBER NOT NULL,
  BAN_STATUS NUMBER NOT NULL,
  ACCION VARCHAR2(50) NOT NULL,
  PRODUCTO_CONFIGURADO NUMBER(1) NOT NULL,
  RETORNO NUMBER(1) NOT NULL,
  VISIBLE NUMBER(1) NOT NULL,
  FECHA_REGISTRO DATE DEFAULT SYSDATE,
  ID_PRODUCTO NUMBER NOT NULL,
  CONSTRAINT TCA_TAREA_CON_BTN_DIN_PK PRIMARY KEY (ID) ENABLE 
);




ALTER TABLE FENIX.TCA_TAREA_CON_BTN_DIN ADD CONSTRAINT TCA_PRODUCTO_BTN_DIN_TCA_TAREA_BTN_FK FOREIGN KEY ( ID_PRODUCTO ) REFERENCES CAT_PRODUCTO ( ID ) ENABLE;
ALTER TABLE FENIX.TCA_TAREA_CON_BTN_DIN ADD CONSTRAINT TCA_TAR_CON_BTN_DIN_TCA_TAREA_BPM_FK FOREIGN KEY ( ID_TAREA_BPM ) REFERENCES TCA_TAREA_BPM ( ID ) ENABLE;
ALTER TABLE FENIX.TCA_TAREA_CON_BTN_DIN ADD CONSTRAINT TCA_TAREA_CON_BTN_DIN_PRO_CHK CHECK  (PRODUCTO_CONFIGURADO IN(0, 1)) ENABLE;
ALTER TABLE FENIX.TCA_TAREA_CON_BTN_DIN ADD CONSTRAINT TCA_TAREA_CON_BTN_DIN_RET_CHK CHECK (RETORNO IN(0, 1))ENABLE;
ALTER TABLE FENIX.TCA_TAREA_CON_BTN_DIN ADD CONSTRAINT TCA_TAREA_CON_BTN_DIN_VIS_CHK CHECK (VISIBLE IN(0, 1)) ENABLE;


COMMENT ON TABLE FENIX.TCA_TAREA_CON_BTN_DIN IS 'Tabla de configuración para determinar el outcome del proceso BPM aplicable a cualquier proceso en turno';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.ID IS 'Índice de la Tabla';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.COMPONENTE IS 'Identificador del Numero de botón';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.ID_TAREA_BPM IS 'Identificador de Tarea';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.BAN_STATUS IS '1 - true (fila activada) , 0 - false (fila desactivado)';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.ACCION IS 'Nombre del botón que se desea renderizar ';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.PRODUCTO_CONFIGURADO IS 'Simulación de la tabla de verdad';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.RETORNO IS '1 - true (Retorno de otra tarea) , 0 - false (No es retorno de otra tarea)';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.VISIBLE IS 'Resultado de la tabla de verdad conforme a la visibilidad de los diferentes escenarios';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.FECHA_REGISTRO IS 'Fecha de alta del registro';
COMMENT ON COLUMN FENIX.TCA_TAREA_CON_BTN_DIN.ID_PRODUCTO IS 'Producto a configurar por separado [ Prestamo tradicional ], [ Prestamo XXX ]';




--Secuencia
DROP SEQUENCE FENIX.TCA_TAREA_CON_BTN_DIN_SEQ;
CREATE SEQUENCE FENIX.TCA_TAREA_CON_BTN_DIN_SEQ;

-- Disparador SIMPLE
DROP TRIGGER FENIX.TCA_TAREA_CON_BTN_DIN_TRG;
CREATE OR REPLACE TRIGGER TCA_TAREA_CON_BTN_DIN_TRG
BEFORE INSERT ON FENIX.TCA_TAREA_CON_BTN_DIN
FOR EACH ROW
DECLARE
    new_id NUMBER;

BEGIN
    SELECT FENIX.TCA_TAREA_CON_BTN_DIN_SEQ.NEXTVAL
     INTO new_id FROM Dual;
    :NEW.ID := new_id;
END;




INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',1,0,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',1,1,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',0,0,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',0,1,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',1,0,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',1,1,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',0,0,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',0,1,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',1,0,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',1,1,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',0,0,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_1',55,1,'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS',0,1,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',1,0,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',1,1,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',0,0,0,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',0,1,0,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',1,0,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',1,1,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',0,0,0,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',0,1,0,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',1,0,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',1,1,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',0,0,0,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_2',55,1,'ENVIAR_COFI',0,1,0,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',1,0,0,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',1,1,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',0,0,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',0,1,1,1);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',1,0,0,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',1,1,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',0,0,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',0,1,1,7);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',1,0,0,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',1,1,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',0,0,1,28);
INSERT INTO FENIX.TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, BAN_STATUS, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE, ID_PRODUCTO) VALUES ('BTN_3',55,1,'ENVIAR_RESPONSABLE',0,1,1,28);