<wsdl:definitions name="CrearTerminoDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearTerminoDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearTerminoDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearTerminoDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearTerminoDB_plt">
    <plt:role name="CrearTerminoDB_role">
      <plt:portType name="tns:CrearTerminoDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearTerminoDB"
                schemaLocation="../XSD/CrearTerminoDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="TerminoCollection_msg">
        <wsdl:part name="TerminoCollection" element="top:TerminoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearTerminoDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TerminoCollection_msg"/>
            <wsdl:output message="tns:TerminoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>