<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSB_BCIE/CANALES/PublicarJMS" name="PublicarJMS_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PublicarJMS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSB_BCIE/CANALES/PublicarJMS"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="pub:Produce_Message_ptt" xmlns:pub="http://xmlns.oracle.com/pcbpel/adapter/jms/OSB_BCIE/CANALES/PublicarJMS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>