<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraCuestionario/SP_GENERA_CUESTIONARIO" name="GenerarCuestionarioSP_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GenerarCuestionarioSP.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraCuestionario/SP_GENERA_CUESTIONARIO"/>
    <wsdl:binding name="SP_GENERA_CUESTIONARIO_ptt-binding" type="sp:SP_GENERA_CUESTIONARIO_ptt" xmlns:sp="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraCuestionario/SP_GENERA_CUESTIONARIO">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SP_GENERA_CUESTIONARIO">
            <soap:operation soapAction="SP_GENERA_CUESTIONARIO"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>