<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://ww.bcie.org/EliminarUsuarioAprobacionByIdSolicitudService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://ww.bcie.org/EliminarUsuarioAprobacionByIdSolicitudService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EliminarUsuarioAprobacionByIdAprobacion_SB">
        <plnk:role name="EliminarUsuarioAprobacionByIdAprobacionPT" portType="tns:EliminarUsuarioAprobacionByIdAprobacionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://ww.bcie.org/EliminarUsuarioAprobacionByIdSolicitudService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/SolicitudAprobacion/V1/Wsdl/ADAPTER/EliminarUsuarioAprobacionByIdSolicitudSAD.wsdl"/>
</wsdl:definitions>
