<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="MerchandiseHierarchyFindByIdProcess" targetNamespace="http://xmlns.oracle.com/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindByIdProcess/MerchandiseHierarchyFindByIdProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindByIdProcess/MerchandiseHierarchyFindByIdProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" schemaLocation="../Schemas/oneCaseDb_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="MerchandiseHierarchyFindByIdProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:oneCaseDbSelect_IdC1_appCodeC1_CatIdC1_targetAppCodeC1InputParameters"/>
   </wsdl:message>
   <wsdl:message name="MerchandiseHierarchyFindByIdProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:MdmMerchandHierarchiesCollection"/>
   </wsdl:message>
   <wsdl:portType name="MerchandiseHierarchyFindByIdProcess">
      <wsdl:operation name="findById">
         <wsdl:input message="client:MerchandiseHierarchyFindByIdProcessRequestMessage"/>
         <wsdl:output message="client:MerchandiseHierarchyFindByIdProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="MerchandiseHierarchyFindByIdProcess">
      <plnk:role name="MerchandiseHierarchyFindByIdProcessProvider" portType="client:MerchandiseHierarchyFindByIdProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
