<wsdl:definitions name="InsertaBiCorreoElectronico" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/InsertaBiCorreoElectronico" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/InsertaBiCorreoElectronico" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertaBiCorreoElectronico" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="InsertaBiCorreoElectronico_plt">
    <plt:role name="InsertaBiCorreoElectronico_role">
      <plt:portType name="tns:InsertaBiCorreoElectronico_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertaBiCorreoElectronico" schemaLocation="../XSD/InsertaBiCorreoElectronico_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="TbiEnvioCorreo2Collection_msg">
        <wsdl:part name="TbiEnvioCorreo2Collection" element="top:TbiEnvioCorreo"/>
    </wsdl:message>
    <wsdl:portType name="InsertaBiCorreoElectronico_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:TbiEnvioCorreo2Collection_msg"/>
            <wsdl:output message="tns:TbiEnvioCorreo2Collection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>