<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/EsUsuarioEnGrupoService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/EsUsuarioEnGrupoService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ValidarUsuario">
        <plnk:role name="EsUsuarioEnGrupoPT" portType="tns:EsUsuarioEnGrupoPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/EsUsuarioEnGrupoService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/Usuario/V1/WSDL/EsUsuarioEnGrupo.wsdl"/>
</wsdl:definitions>
