<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/MatrizTCCService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/MatrizTCCService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ObtenerTCCInicio">
        <plnk:role name="MatrizTCCPT" portType="tns:MatrizTCCPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/MatrizTCCService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/MatrizTCC/V1/Wsdl/MatrizTCC.wsdl"/>
</wsdl:definitions>
