<wsdl:definitions name="ConsultarObservacionCondicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project16/ConsultarObservacionCondicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project16/ConsultarObservacionCondicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarObservacionCondicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarObservacionCondicion_plt">
    <plt:role name="ConsultarObservacionCondicion_role">
      <plt:portType name="tns:ConsultarObservacionCondicion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarObservacionCondicion" schemaLocation="../XSD/ConsultarObservacionCondicionV2.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarObservacionCondicionInput_msg">
        <wsdl:part name="ConsultarObservacionCondicionInput_msg" element="db:ConsultarObservacionCondicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarObservacionCondicionOutputCollection_msg">
        <wsdl:part name="ConsultarObservacionCondicionOutputCollection" element="db:ConsultarObservacionCondicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarObservacionCondicion_ptt">
        <wsdl:operation name="ConsultarObservacionCondicion">
            <wsdl:input message="tns:ConsultarObservacionCondicionInput_msg"/>
            <wsdl:output message="tns:ConsultarObservacionCondicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>