<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.banesco.com/eopt/AcctLoanInfoAdd_V1.0" xmlns:tns="http://xmlns.banesco.com/eopt/AcctLoanAdd_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns6="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns5="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanInfoAdd/AcctLoanInfoAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctLoanInfoAddRs" namespace="http://xmlns.banesco.com/eopt/AcctLoanInfoAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanAdd/AcctLoanAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctLoanAddRs" namespace="http://xmlns.banesco.com/eopt/AcctLoanAdd_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUL 23 16:22:55 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="AcctId"/>
   <xsl:template match="/">
      <tns:AcctLoanAddRs>
         <tns:AcctKey>
            <eoAcct:AcctId>
               <xsl:value-of select="$AcctId"/>
            </eoAcct:AcctId>
            <xsl:if test="/ns0:AcctLoanInfoAddRs/ns0:AcctKey/eoAcct:AcctReference/text()">
               <eoAcct:AcctReference>
                  <xsl:value-of select="/ns0:AcctLoanInfoAddRs/ns0:AcctKey/eoAcct:AcctReference"/>
               </eoAcct:AcctReference>
            </xsl:if>
            <xsl:if test="/ns0:AcctLoanInfoAddRs/ns0:AcctKey/eoAcct:AlternateId/text()">
               <eoAcct:AlternateId>
                  <xsl:value-of select="/ns0:AcctLoanInfoAddRs/ns0:AcctKey/eoAcct:AlternateId"/>
               </eoAcct:AlternateId>
            </xsl:if>
         </tns:AcctKey>
         <tns:Status>
            <eoStatus:StatusCode>
               <xsl:value-of select="/ns0:AcctLoanInfoAddRs/ns0:Status/eoStatus:StatusCode"/>
            </eoStatus:StatusCode>
            <eoStatus:StatusDesc>
               <xsl:value-of select="/ns0:AcctLoanInfoAddRs/ns0:Status/eoStatus:StatusDesc"/>
            </eoStatus:StatusDesc>
            <eoStatus:AdditionalStatus>
               <eoStatus:StatusCode>
                  <xsl:value-of select="/ns0:AcctLoanInfoAddRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusCode"/>
               </eoStatus:StatusCode>
               <eoStatus:StatusDesc>
                  <xsl:value-of select="/ns0:AcctLoanInfoAddRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc"/>
               </eoStatus:StatusDesc>
            </eoStatus:AdditionalStatus>
         </tns:Status>
      </tns:AcctLoanAddRs>
   </xsl:template>
</xsl:stylesheet>
