<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CondicionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/CondicionMO">
<types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConsultarCondicionByIdLineaCreditoRequestMessage">
    <part name="ConsultarCondicionByIdLineaCreditoRequest" element="conMO:ConsultarCondicionByIdLineaCreditoRequest"/>
  </message>
  <message name="ConsultarCondicionByIdLineaCreditoResponseMessage">
    <part name="ConsultarCondicionByIdLineaCreditoResponse" element="conMO:ConsultarCondicionByIdLineaCreditoResponse"/>
  </message>
  <portType name="ConsultarCondicionByIdLineaCreditoPT">
    <operation name="consultarCondicionByIdLineaCredito">
      <input message="tns:ConsultarCondicionByIdLineaCreditoRequestMessage"/>
      <output message="tns:ConsultarCondicionByIdLineaCreditoResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarCondicionByIdLineaCreditoPT12Bnd" type="tns:ConsultarCondicionByIdLineaCreditoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarCondicionByIdLineaCredito">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CondicionService/consultarCondicionByIdLineaCredito"/>
      <input>
        <soap12:body use="literal" parts="ConsultarCondicionByIdLineaCreditoRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ConsultarCondicionByIdLineaCreditoResponse"/>
      </output>
    </operation>
  </binding>
</definitions>