<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/EliminarCondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/EliminarCondicionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:conMO="http://www.bcie.org/CondicionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="EliminarCondicionResquestMessage">
    <wsdl:part name="request" element="conMO:EliminarCondicionRequest"/>
  </wsdl:message>
  <wsdl:message name="EliminarCondicionResponseMessage">
    <wsdl:part name="response" element="conMO:EliminarCondicionResponse"/>
  </wsdl:message>
  <wsdl:portType name="EliminarCondicionPT">
    <wsdl:operation name="eliminarCondicion">
      <wsdl:input message="tns:EliminarCondicionResquestMessage"/>
      <wsdl:output message="tns:EliminarCondicionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EliminarCondicion12Bnd" type="tns:EliminarCondicionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="eliminarCondicion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/EliminarCondicionService/eliminarCondicion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>