<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ValidarNoObjecion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ValidarNoObjecion" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:estDec="http://xmlns.bcie.org/EstadosDeclaracion">
  <types>
    <xsd:schema>
            <xsd:import namespace="http://xmlns.bcie.org/EstadosDeclaracion" schemaLocation="../Schema/EstadosDeclaracionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ValidarNoObjecionBRRequestMessage">
    <part name="part" element="estDec:EstadosDeclaracionRequest"/>
  </message>
  <message name="ValidarNoObjecionBRResponseMessage">
    <part name="part" element="estDec:EstadosDeclaracionResponse"/>
  </message>
  <portType name="EstadosDeclaracionPT">
    <operation name="estadosDeclaracion">
      <input message="tns:ValidarNoObjecionBRRequestMessage"/>
      <output message="tns:ValidarNoObjecionBRResponseMessage"/>
    </operation>
  </portType>
  <binding name="EstadosDeclaracion12Bnd" type="tns:EstadosDeclaracionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="estadosDeclaracion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ValidarNoObjecion/estadosDeclaracion"/>
      <input>
        <soap12:body use="literal" parts="part"/>
      </input>
      <output>
        <soap12:body use="literal" parts="part"/>
      </output>
    </operation>
  </binding>
</definitions>