<wsdl:definitions name="EliminarTreTermino_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarTreTermino_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarTreTermino_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTreTermino_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarTreTermino_DB_plt">
    <plt:role name="EliminarTreTermino_DB_role">
      <plt:portType name="tns:EliminarTreTermino_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTreTermino_DB" schemaLocation="../XSD/EliminarTreTermino_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarTreTermino_DBInput_msg">
        <wsdl:part name="EliminarTreTermino_DBInput_msg" element="db:EliminarTreTermino_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarTreTermino_DB_ptt">
        <wsdl:operation name="EliminarTreTermino_DB">
            <wsdl:input message="tns:EliminarTreTermino_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>