package org.bcie.fenix.common.model.vo.common;

import java.sql.Timestamp;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 12 18:56:54 CDT 2017
// ---------------------------------------------------------------------
public interface ConsultaFechaTransRecursosBydesembolso extends ViewObject {
    Timestamp obtenerFechatransferenciaRecursos(Long idContrato);
}

