package org.bcie.fenix.common.model.vo.common;

import java.util.Map;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 03 17:05:36 CDT 2015
// ---------------------------------------------------------------------
public interface TareaProcesoBpmVO extends ViewObject {
    Map getEtapaTareaByIdTareaBpm(Integer idTareaBpm);
}

