<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/AdministrarClienteProcess"
                  xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/AdministrarClienteProcess"
                  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/AdministrarClienteProcess"
                  schemaLocation="../../Schema/PA06/AdministrarClienteProcess.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="InicioAdministrarCliente">
    <wsdl:part name="parameters" element="tns:InicioAdministrarCliente"/>
  </wsdl:message>
  <wsdl:message name="FinAdministrarCliente">
    <wsdl:part name="parameters" element="tns:FinAdministrarCliente"/>
  </wsdl:message>
  <wsdl:portType name="AdministrarClienteProcessPortType">
    <wsdl:operation name="InicioAdministrarCliente">
      <wsdl:input message="tns:InicioAdministrarCliente"/>
    </wsdl:operation>
    <wsdl:operation name="FinAdministrarCliente">
      <wsdl:input message="tns:FinAdministrarCliente"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AdministrarClienteProcessBinding" type="tns:AdministrarClienteProcessPortType">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="InicioAdministrarCliente">
      <wsdlsoap:operation style="document" soapAction="InicioAdministrarCliente"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="FinAdministrarCliente">
      <wsdlsoap:operation style="document" soapAction="FinAdministrarCliente"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <plnk:partnerLinkType name="AdministrarClienteProcessPortTypePartnerLinkType">
    <plnk:role name="AdministrarClienteProcessPortTypeProvider">
      <plnk:portType name="tns:AdministrarClienteProcessPortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
</wsdl:definitions>
