<wsdl:definitions name="ActualizarComponente" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarComponente" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarComponente" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarComponente" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarComponente_plt">
    <plt:role name="ActualizarComponente_role">
      <plt:portType name="tns:ActualizarComponente_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarComponente"
                schemaLocation="../XSD/ActualizarComponente_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ComponenteCollection_msg">
        <wsdl:part name="ComponenteCollection" element="top:ComponenteCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarComponente_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:ComponenteCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>