<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ComisionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ComisionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:comMO="http://www.bcie.org/ComisionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ComisionMO"
                  schemaLocation="../../../../Comision/V1/Schema/ComisionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="requestConsultarComisionesPagadasMessage">
    <part name="request" element="comMO:ConsultarComisionesPagadasRequest"/>
  </message>
  <message name="responseConsultarComisionesPagadasMessage">
    <part name="response" element="comMO:ConsultarComisionesPagadasResponse"/>
  </message>
  <portType name="ComisionPT">
    <operation name="consultarComisionesPagadas">
      <input message="tns:requestConsultarComisionesPagadasMessage"/>
      <output message="tns:responseConsultarComisionesPagadasMessage"/>
    </operation>
  </portType>
  <binding name="Comision12Bnd" type="tns:ComisionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarComisionesPagadas">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ComisionService/consultarComisionesPagadas"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>