<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/crearAvisoCobroComisionServiceV2"
                  xmlns="http://schemas.xmlsoap.org/wsdl/" 
                  xmlns:tns="http://www.bcie.org/crearAvisoCobroComisionServiceV2"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:comMO="http://www.bcie.org/ComisionMO">
    <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ComisionMO"
                  schemaLocation="../../../../Comision/V1/Schema/ComisionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="CrearAvisoCobroComisionV2RequestMessage">
    <wsdl:part name="request" element="comMO:CrearAvisoCobroComisionV2Request"/>
  </wsdl:message>
  <wsdl:message name="CrearAvisoCobroComisionV2ResponseMessage">
    <wsdl:part name="response" element="comMO:CrearAvisoCobroComisionV2Response"/>
  </wsdl:message>
    <wsdl:portType name="CrearAvisoCobroComisionV2PT">
        <wsdl:operation name="crearAvisoCobroComisionV2">
      <wsdl:input message="tns:CrearAvisoCobroComisionV2RequestMessage"/>
      <wsdl:output message="tns:CrearAvisoCobroComisionV2ResponseMessage"/>
    </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CrearAvisoCobroComision12V2Bnd" type="tns:CrearAvisoCobroComisionV2PT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="crearAvisoCobroComisionV2">
            <soap12:operation style="document"
                              soapAction="http://www.bcie.org/crearAvisoCobroComisionServiceV2/crearAvisoCobroComisionV2"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
