<wsdl:definitions name="ConsultarOperacionesByIdCliente" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacionesByIdCliente" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacionesByIdCliente" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionesByIdCliente" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarOperacionesByIdCliente_plt">
    <plt:role name="ConsultarOperacionesByIdCliente_role">
      <plt:portType name="tns:ConsultarOperacionesByIdCliente_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionesByIdCliente" schemaLocation="../XSD/ConsultarOperacionesByIdCliente.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarOperacionesByIdClienteInput_msg">
        <wsdl:part name="ConsultarOperacionesByIdClienteInput_msg" element="db:ConsultarOperacionesByIdClienteInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarOperacionesByIdClienteOutputCollection_msg">
        <wsdl:part name="ConsultarOperacionesByIdClienteOutputCollection" element="db:ConsultarOperacionesByIdClienteOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarOperacionesByIdCliente_ptt">
        <wsdl:operation name="ConsultarOperacionesByIdCliente">
            <wsdl:input message="tns:ConsultarOperacionesByIdClienteInput_msg"/>
            <wsdl:output message="tns:ConsultarOperacionesByIdClienteOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>