<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.banesco.com/eopt/PmtCardAdd_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://xmlns.banesco.com/eopt/tdcPmtAdd" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns3="http://xmlns.banesco.com/eo/Banking_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoPmt="http://xmlns.banesco.com/eo/Pmt_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Bill_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:eoptTdcPmtRev="http://xmlns.banesco.com/eopt/tdcPmtRev"
                xmlns:ns6="http://xmlns.banesco.com/service/WAY4Svc" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:eoptTdcCardAcctTrnInq="http://xmlns.banesco.com/eopt/tdcCardAcctTrnInq"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:eoptTdcCardAcctRelInq="http://xmlns.banesco.com/eopt/tdcCardAcctRelInq"
                xmlns:eoptCambiarEstatusTDD="http://xmlns.banesco.com/eopt/CambiarEstatusTDD"
                xmlns:ns7="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns8="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:ns9="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns10="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:ns12="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns11="http://xmlns.banesco.com/eo/Payee_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Payment/PmtCardAdd/PmtCardAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="PmtCardAddRq" namespace="http://xmlns.banesco.com/eopt/PmtCardAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../../Commons/backends/WAY4/resources/wsdl/WebServiceWAY4SvcMock.wsdl"/>
            <oracle-xsl-mapper:rootElement name="tdcPmtAddRq" namespace="http://xmlns.banesco.com/eopt/tdcPmtAdd"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED AUG 17 16:40:49 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:tdcPmtAddRq>
         <tns:RqUID>
            <xsl:value-of select="oraext:generate-guid ( )"/>
         </tns:RqUID>
         <tns:PmtInfo>
            <tns:CurAmt>
               <tns:Amt>
                  <xsl:value-of select="/ns0:PmtCardAddRq/ns0:Pmt/eoPmt:CurAmt/ns4:Amt"/>
               </tns:Amt>
               <tns:CurCode>
                  <tns:CurCodeValue>
                     <xsl:value-of select="/ns0:PmtCardAddRq/ns0:Pmt/eoPmt:CurAmt/ns4:CurCode/ns4:Value"/>
                  </tns:CurCodeValue>
               </tns:CurCode>
            </tns:CurAmt>
            <tns:PmtInstruction>
               <tns:PmtMethod>
                  <xsl:value-of select="/ns0:PmtCardAddRq/ns0:Pmt/eoPmt:PmtInstruction/eoPmt:PmtMethod"/>
               </tns:PmtMethod>
               <tns:CountryCode>
                  <tns:CountryCodeValue>
                     <xsl:value-of select="/ns0:PmtCardAddRq/ns0:Pmt/eoPmt:PmtInstruction/eoPmt:CountryCode/ns4:CountryCodeValue"/>
                  </tns:CountryCodeValue>
               </tns:CountryCode>
            </tns:PmtInstruction>
            <tns:PmtCreditDetail>
               <tns:ToAcctKeys>
                  <tns:CardKeys>
                     <tns:CardId>
                        <xsl:value-of select="/ns0:PmtCardAddRq/ns0:Pmt/eoPmt:PmtTrnDetail/eoPmt:CardKey/ns1:CardId"/>
                     </tns:CardId>
                  </tns:CardKeys>
               </tns:ToAcctKeys>
            </tns:PmtCreditDetail>
         </tns:PmtInfo>
      </tns:tdcPmtAddRq>
   </xsl:template>
</xsl:stylesheet>
