<wsdl:definitions
     name="ActualizarSolicitudAprobacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarSolicitudAprobacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarSolicitudAprobacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarSolicitudAprobacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarSolicitudAprobacion_plt" >
    <plt:role name="ActualizarSolicitudAprobacion_role" >
      <plt:portType name="tns:ActualizarSolicitudAprobacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarSolicitudAprobacion" schemaLocation="../XSD/ActualizarSolicitudAprobacion_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="SolicitudAprobacionCollection_msg">
        <wsdl:part name="SolicitudAprobacionCollection" element="top:SolicitudAprobacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarSolicitudAprobacion_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:SolicitudAprobacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
