<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetASN" name="DBMDMDetASN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBMDMDetASN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetASN"/>
    <wsdl:binding name="DBMDMDetASN_ptt-binding" type="dbm:DBMDMDetASN_ptt" xmlns:dbm="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetASN">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBMDMDetASNSelect">
            <soap:operation soapAction="DBMDMDetASNSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>