<wsdl:definitions name="DBMDMDetCjaASN" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetCjaASN" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetCjaASN" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBMDMDetCjaASN" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="DBMDMDetCjaASN_plt">
    <plt:role name="DBMDMDetCjaASN_role">
      <plt:portType name="tns:DBMDMDetCjaASN_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBMDMDetCjaASN" schemaLocation="DBMDMDetCjaASN_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="DBMDMDetCjaASNSelect_inputParameters">
        <wsdl:part name="DBMDMDetCjaASNSelect_inputParameters" element="top:DBMDMDetCjaASNSelect_asn_lpnInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaAsninDetCjaViewCollection_msg">
        <wsdl:part name="XxSoaAsninDetCjaViewCollection" element="top:XxSoaAsninDetCjaViewCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBMDMDetCjaASN_ptt">
        <wsdl:operation name="DBMDMDetCjaASNSelect">
            <wsdl:input message="tns:DBMDMDetCjaASNSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaAsninDetCjaViewCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>