<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetCjaASN" name="DBMDMDetCjaASN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBMDMDetCjaASN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetCjaASN"/>
    <wsdl:binding name="DBMDMDetCjaASN_ptt-binding" type="dbm:DBMDMDetCjaASN_ptt" xmlns:dbm="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMDetCjaASN">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBMDMDetCjaASNSelect">
            <soap:operation soapAction="DBMDMDetCjaASNSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>