<wsdl:definitions
     name="ConsultarEnmiendas"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project20/ConsultarEnmiendas"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project20/ConsultarEnmiendas"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarEnmiendas"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarEnmiendas_plt" >
    <plt:role name="ConsultarEnmiendas_role" >
      <plt:portType name="tns:ConsultarEnmiendas_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarEnmiendas" schemaLocation="../XSD/ConsultarEnmiendas.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarEnmiendasInput_msg">
        <wsdl:part name="ConsultarEnmiendasInput_msg" element="db:ConsultarEnmiendasInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarEnmiendasOutputCollection_msg">
        <wsdl:part name="ConsultarEnmiendasOutputCollection" element="db:ConsultarEnmiendasOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarEnmiendas_ptt">
        <wsdl:operation name="ConsultarEnmiendas">
            <wsdl:input message="tns:ConsultarEnmiendasInput_msg"/>
            <wsdl:output message="tns:ConsultarEnmiendasOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
