<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/HierarchyAPP/BorrardbReference" name="BorrardbReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="BorrardbReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/HierarchyAPP/BorrardbReference"/>
    <wsdl:binding name="BorrardbReference_ptt-binding" type="bor:BorrardbReference_ptt" xmlns:bor="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/HierarchyAPP/BorrardbReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BorrardbReferenceSelect">
            <soap:operation soapAction="BorrardbReferenceSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>