<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/ConsultarTBLineaCredito" name="ConsultarTBLineaCredito-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarTBLineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/ConsultarTBLineaCredito"/>
    <wsdl:binding name="ConsultarTBLineaCredito_ptt-binding" type="con:ConsultarTBLineaCredito_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/ConsultarTBLineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarTBLineaCredito">
            <soap:operation soapAction="ConsultarTBLineaCredito"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>