<wsdl:definitions name="RPMFindPriceChangeEventDetailsDBBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMFindPriceChangeEventDetailsDBBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMFindPriceChangeEventDetailsDBBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/RPMFindPriceChangeEventDetailsDBBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="RPMFindPriceChangeEventDetailsDBBS_plt">
    <plt:role name="RPMFindPriceChangeEventDetailsDBBS_role">
      <plt:portType name="tns:RPMFindPriceChangeEventDetailsDBBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/RPMFindPriceChangeEventDetailsDBBS" schemaLocation="RPMFindPriceChangeEventDetailsDBBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="RPMFindPriceChangeEventDetailsDBBSSelect_inputParameters">
        <wsdl:part name="RPMFindPriceChangeEventDetailsDBBSSelect_inputParameters" element="top:RPMFindPriceChangeEventDetailsDBBSSelect_pPriceChangeIDInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxPcExportDetCollection_msg">
        <wsdl:part name="XxPcExportDetCollection" element="top:XxPcExportDetCollection"/>
    </wsdl:message>
    <wsdl:portType name="RPMFindPriceChangeEventDetailsDBBS_ptt">
        <wsdl:operation name="RPMFindPriceChangeEventDetailsDBBSSelect">
            <wsdl:input message="tns:RPMFindPriceChangeEventDetailsDBBSSelect_inputParameters"/>
            <wsdl:output message="tns:XxPcExportDetCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>