<wsdl:definitions name="RPMSavePriceChangeDBBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMSavePriceChangeDBBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMSavePriceChangeDBBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RPMSavePriceChangeDBBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="RPMSavePriceChangeDBBS_plt">
    <plt:role name="RPMSavePriceChangeDBBS_role">
      <plt:portType name="tns:RPMSavePriceChangeDBBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RPMSavePriceChangeDBBS" schemaLocation="RPMSavePriceChangeDBBS_sp.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="RPMSavePriceChangeDBBS_ptt">
        <wsdl:operation name="RPMSavePriceChangeDBBS">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>