
  CREATE OR REPLACE FUNCTION F_ETIQUETAS_CONDICION
(
  P_ID IN VARCHAR2  
, P_ETIQUETA IN VARCHAR2  
) RETURN VARCHAR2 IS
  
  V_TIPO VARCHAR(1024);
  TYPE NUM_TAB IS TABLE OF NUMBER;
  
  /*CURSOR C1
  IS
    SELECT TCC.DESCRIPCION FROM CONDICION CON
    JOIN TRE_CATEGORIA_CONDICION TCCO ON (tcco.id_CONDICION = con.id)
    JOIN TCA_CATEGORIA_CONDICION TCC ON (TCCO.ID_TCA_CATEGORIA = TCC.ID)
    WHERE CON.ID = P_ID;*/

BEGIN

  --OPEN C1;
  --FETCH C1 INTO V_TIPO;

  CASE WHEN (P_ETIQUETA = 'Sección')THEN
  SELECT NOMBRE INTO V_TIPO FROM CONDICION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Descripción')THEN
  SELECT DESCRIPCION INTO V_TIPO FROM CONDICION
  WHERE ID = P_ID;
  
 /* WHEN (P_ETIQUETA = 'Categoría')THEN
  RETURN V_TIPO;*/
  
  --CLOSE C1;
  
  WHEN (P_ETIQUETA = 'Tipo de Control')THEN
  SELECT TCC.DESCRIPCION INTO V_TIPO FROM TCA_CONTROL_CONDICION TCC
  JOIN CONDICION CON ON(CON.ID_TCA_CONTROL_CONDICION = TCC.ID)
  WHERE CON.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Tipo Fecha Inicio')THEN
  SELECT TTFI.DESCRIPCION INTO V_TIPO FROM TCA_TIPO_FECHA_INICIO TTFI
  JOIN CONDICION CON ON(CON.ID_TCA_TIPO_FECHA_INICIO = TTFI.ID)
  WHERE CON.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fecha Inicio')THEN
  SELECT FECHA_INICIO INTO V_TIPO FROM CONDICION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Nombre')THEN
  SELECT NOMBRE INTO V_TIPO FROM CONDICION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Plazo')THEN
  SELECT PLAZO INTO V_TIPO FROM CONDICION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Tipo Plazo')THEN
  SELECT TTF.DESCRIPCION INTO V_TIPO FROM TCA_TIPO_FRECUENCIA TTF
  JOIN CONDICION CON ON(CON.ID_TCA_FRECUENCIA_PLAZO = TTF.ID)
  WHERE CON.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fecha Final')THEN
  SELECT FECHA_FINAL INTO V_TIPO FROM CONDICION
  WHERE ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Categoría')THEN
  SELECT LISTAGG(TCC.DESCRIPCION, ', ') WITHIN GROUP (ORDER BY TCC.DESCRIPCION) AS DESCRIPCION
    INTO V_TIPO FROM CONDICION CON
    JOIN TRE_CATEGORIA_CONDICION TRCC ON (CON.ID = TRCC.ID_CONDICION)
    JOIN TCA_CATEGORIA_CONDICION TCC ON (TRCC.ID_TCA_CATEGORIA = TCC.ID)
    WHERE CON.ID = P_ID;
    
  WHEN (P_ETIQUETA ='Eventos')THEN
  SELECT LISTAGG(TEC.DESCRIPCION, ', ') WITHIN GROUP (ORDER BY TEC.DESCRIPCION) AS DESCRIPCION 
    INTO V_TIPO FROM CONDICION CON
    JOIN TRE_TCA_EVENTO_CONDICION TREC ON (CON.ID = TREC.ID_CONDICION)
    JOIN TCA_EVENTO_CONDICION TEC ON (TREC.ID_TCA_EVENTO = TEC.ID)
    WHERE CON.ID = P_ID;
  
  WHEN (P_ETIQUETA = 'Fuente')THEN
  SELECT LISTAGG(FNT.DESCRIPCION, ', ') WITHIN GROUP (ORDER BY FNT.DESCRIPCION) AS DESCRIPCION
    INTO V_TIPO FROM CONDICION CON
    JOIN TRE_FUENTE_CONDICION TFC ON (CON.ID = TFC.ID_CONDICION)
    JOIN FUENTE FNT ON (TFC.ID_FUENTE = FNT.ID)
    WHERE ID_CONDICION = P_ID;
    
  WHEN (P_ETIQUETA = 'Línea')THEN
  SELECT LISTAGG(LIN.DESCRIPCION_LINEA, ', ') WITHIN GROUP (ORDER BY LIN.DESCRIPCION_LINEA) AS DESCRIPCION_LINEA
    INTO V_TIPO FROM CONDICION CON
    JOIN TRE_LINEA_CREDITO_TCC TLCT ON (CON.ID = TLCT.ID_CONDICION)
    JOIN LINEA_CREDITO LIN ON (TLCT.ID_LINEA_CREDITO = LIN.ID)
    WHERE CON.ID = P_ID;
    
  /*WHEN (P_ETIQUETA = 'Observaciones')THEN
  SELECT OBS_CON.OBSERVACION INTO V_TIPO FROM CONDICION CON
    JOIN OBSERVACION_CONDICION OBS_CON ON (CON.ID = OBS_CON.ID_CONDICION)
    WHERE CON.ID = P_ID;*/
  
  ELSE NULL;

  END CASE;
  RETURN V_TIPO;
END F_ETIQUETAS_CONDICION;

/
