CREATE OR REPLACE  TYPE  T_CONDICION_FECHA FORCE AS OBJECT
(ID NUMBER (12), 
 ID_TCA_TIPO_FECHA_INICIO NUMBER (5),
FECHA_VIGENCIA DATE);
/

CREATE OR REPLACE TYPE T_CONDICION AS TABLE OF T_CONDICION_FECHA;
/

CREATE  TABLE TMP_PLAZO_CONDICION
(
FECHA_INICIO_PLAZO DATE,
FECHA_FINAL_PLAZO DATE
);
/
