CREATE OR REPLACE TRIGGER FENIX.SEGUIMIENTO_CRED_UPD_TGR 
	AFTER UPDATE ON FENIX.SEGUIMIENTO_CREDITICIO FOR EACH ROW
	DECLARE 
	v_id_tbi_seg_cred NUMBER;	
	err_num NUMBER;   
	err_msg VARCHAR2(255);
   
BEGIN        
                    
		SELECT TBI_SEGUIMIENTO_CRED_SEQ.NEXTVAL INTO v_id_tbi_seg_cred FROM DUAL;
	  
		INSERT INTO TBI_SEGUIMIENTO_CREDITICIO (ID, ID_SEGUIMIENTO, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_seg_cred,:NEW.ID,'MODIFICAR_SEGUIMIENTO', :NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,SYSDATE);  

				
		IF UPDATING ('ID_CLIENTE') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_CLIENTE',:NEW.ID_CLIENTE,:OLD.ID_CLIENTE);
		END IF;  
		IF UPDATING ('TIPO_INICIO') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'TIPO_INICIO',:NEW.TIPO_INICIO,:OLD.TIPO_INICIO);
		END IF;  
		IF UPDATING ('TIPO_REVISION') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'TIPO_REVISION',:NEW.TIPO_REVISION,:OLD.TIPO_REVISION);
		END IF;  
		IF UPDATING ('ID_TCA_SCR') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_TCA_SCR',:NEW.ID_TCA_SCR,:OLD.ID_TCA_SCR);
		END IF;  
		IF UPDATING ('ID_TCA_ESTADO_SCR') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_TCA_ESTADO_SCR',:NEW.ID_TCA_ESTADO_SCR,:OLD.ID_TCA_ESTADO_SCR);
		END IF;  
		IF UPDATING ('ID_TCA_PERSPECTIVA') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_TCA_PERSPECTIVA',:NEW.ID_TCA_PERSPECTIVA,:OLD.ID_TCA_PERSPECTIVA);
		END IF;  
		IF UPDATING ('ES_CALIFICACION_DIVIDIDA') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ES_CALIFICACION_DIVIDIDA',:NEW.ES_CALIFICACION_DIVIDIDA,:OLD.ES_CALIFICACION_DIVIDIDA);
		END IF;  
		IF UPDATING ('FECHA_APROBADO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'FECHA_APROBADO',:NEW.FECHA_APROBADO,:OLD.FECHA_APROBADO);
		END IF;  
		IF UPDATING ('INSTANCIA_PROCESO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'INSTANCIA_PROCESO',:NEW.INSTANCIA_PROCESO,:OLD.INSTANCIA_PROCESO);
		END IF;  
		IF UPDATING ('LOGIN_USUARIO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'LOGIN_USUARIO',:NEW.LOGIN_USUARIO,:OLD.LOGIN_USUARIO);
		END IF;  
		IF UPDATING ('NOMBRE_USUARIO') THEN
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'NOMBRE_USUARIO',:NEW.NOMBRE_USUARIO,:OLD.NOMBRE_USUARIO);
		END IF;  
		IF UPDATING ('FECHA_REGISTRO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,:OLD.FECHA_REGISTRO);
		END IF;  
		IF UPDATING ('BAN_ESTATUS') THEN 
		   INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'BAN_ESTATUS',:NEW.BAN_ESTATUS,:OLD.BAN_ESTATUS);
		END IF;  
		IF UPDATING ('ID_FLUJO') THEN 
		   INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'ID_FLUJO',:NEW.ID_FLUJO,:OLD.ID_FLUJO);
		END IF;  	
		IF UPDATING ('LOGIN_USUARIO_ULTIMO_CAMBIO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'LOGIN_USUARIO_ULTIMO_CAMBIO',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:OLD.LOGIN_USUARIO_ULTIMO_CAMBIO);
		END IF;  
		IF UPDATING ('NOMBRE_USUARIO_ULTIMO_CAMBIO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'NOMBRE_USUARIO_ULTIMO_CAMBIO',:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,:OLD.NOMBRE_USUARIO_ULTIMO_CAMBIO);
		END IF;  
		IF UPDATING ('FECHA_ULTIMO_CAMBIO') THEN  
		  INSERT INTO TBI_SEGUIMIENTO_CRED_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_seg_cred,'FECHA_ULTIMO_CAMBIO',:NEW.FECHA_ULTIMO_CAMBIO,:OLD.FECHA_ULTIMO_CAMBIO);
		END IF;  

 
EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SUBSTR(SQLERRM,1,250);
			
			
		DBMS_OUTPUT.put_line('Error al actualizar en la tabla de bitácora de seguimiento crediticio.');		
		DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line(err_msg);
			
			
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','SEGUIMIENTO_CRED_UPD_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
		COMMIT;
			
END;