create or replace PROCEDURE SP_CONSULTA_DESEMBOLSO (
   P_ID_DESEMBOLSO  IN  T_NUMBER_TAB,
   P_CODIGO_RES     OUT NUMBER,
   P_MENSAJE        OUT VARCHAR2,
   RECORDSET        OUT SYS_REFCURSOR,
   RECORDSET2       OUT SYS_REFCURSOR)
AS
BEGIN

OPEN RECORDSET FOR 
   SELECT CD.ID ID_DESEMBOLSO,
  CD.MONTO_DESEMBOLSAR,
  CD.PROGRAMADO,
  CD.FECHA_EFECTIVA FECHA_EFECTIVA_DESEMBOLSO,
  CD.FECHA_ESTIMADA_DESEMBOLSAR,
  CD.FECHA_ESTIMADA_DISP_RECURSOS,
  CD.FECHA_INICIO_PROCESO_DESEM,
  CD.ID_TCA_ESTADO ,
  CD.MONTO_DESEMBOLSAR_USD,
  CD.FONDO,
  CD.CUENTA_CON_RECURSOS_EXTERNOS RECURSOS_EXTERNOS,
  CD.CUENTA_CLIENTE,
  CD.FECHA_DISPONIBILIDAD_FONDOS,
  CD.ORIGEN_TRANFERENCIA_CLIENTE,
  CD.CONTRATO_FLEXCUBE,
  CD.LOGIN_USUARIO USUARIO,
  CD.REFERENCIA,
  TEO.DESCRIPCION DESCRIPCION_ESTADO,
  TEO.DESCRIPCION_CORTA DESCRIPCION_CORTA_ESTADO,
  TEO.COD_EXTERNO CODIGO_EXTERNO_ESTADO,
  TEO.BAN_ESTATUS BAN_ESTATUS_ESTADO,
  CD.ID_TCA_TIPO_MONEDA,
  CD.PROGRAMA_OPERACION,
  CD.DESTINO_FINANCIAMIENTO,
  CD.ID_TRANSFERENCIA_FT05,
  CD.BHQ_TRANSFERENCIA_FT05,
  CD.FECHA_EFECTIVA_FT05,
  TTM.ID ID_TCA_MONEDA,
  TTM.DESCRIPCION DESCRIPCION_MONEDA,
  TTM.DESCRIPCION_CORTA DESCRIPCION_CORTA_MONEDA,
  TTM.COD_EXTERNO COD_EXTERNO_MONEDA,
  TTM.BAN_ESTATUS BAN_ESTATUS_MONEDA,
  LC.ID ID_LINEA_CREDITO,
  LC.CODIGO_ASIGNACION ,
  F.ID FUENTE,
  F.ID_CONTRATO,
  F.ID_LINEA_PASIVA,
  F.MONTO_ASIGNADO MONTO_ASIGNADO_FUENTE,
  F.NUMERO_ASIGNACION,
  F.PORCENTAJE,
  F.DESCRIPCION DESCRIPCION_FUENTE,
  F.COMENTARIO COMENTARIO_FUENTE,
  F.FECHA_OBTENIDO,
  TVF.ES_EXTERNO,
  TLP.MONTO_DESEMBOLSAR MONTO_DESEMBOLSAR_FUENTE,
  TLP.MONTO_DISPONIBLE MONTO_DISPONIBLE_FUENTE,
  TLP.RESERVA_TOTAL RESERVA_TOTAL_FUENTE,
  CF.ID ID_CONDICION_FINANCIERA,
  CF.ID_PRODUCTO_FLEXCUBE,
  CF.ID_TCA_ESPECIFICACION_FECHA,
  CF.FECHA_VENCIMIENTO,
  CF.FECHA_PRIMER_PAGO_CAPITAL,
  CF.FECHA_PROXIMO_PAGO_INTERES,
  CF.FECHA_PROXIMA_REVISION_SPREAD,
  CF.FECHA_PROXIMA_REVISION_TASA,
  CF.FRECUENCIA_PAGO_CAPITAL,
  CF.FRECUENCIA_REVISION_TASA,
  CF.FRECUENCIA_PLAZO,
  CF.FRECUENCIA_PERIODO_GRACIA,
  CF.FRECUENCIA_PAGO_INTERES,
  CF.FRECUENCIA_REVISION_SPREAD,
  CF.TRATAMIENTO_DIAS_FERIADOS,
  (CASE WHEN CF.CODIGO_TASA_REFERENCIA_SPREAD IS NULL THEN  NVL( CF.SPREAD_TASA, 0) ELSE NVL(TDSF.VALOR_ACTUAL, 0)  END) AS SPREAD_TASA ,
  CF.CODIGO_TASA_REFERENCIA_SPREAD,
  CF.SPREAD_MORA,
  CF.LIMITE_TASA_MAXIMA TASA_MAXIMA,
  CF.LIMITE_TASA_MINIMA TASA_MINIMA,
  CF.MONTO_DESCUENTO MONTO_ESPECIAL,
  CF.CODIGO_TASA_REFERENCIA,
  CF.VALOR_TASA TASA_FIJA,
  TDF.DESCRIPCION DESC_CORTA_TASA_REFERENCIA,
  TDF.DESCRIPCION_TASA DESCRIPCION_TASA_REFERENCIA,
  TDF.VALOR_ACTUAL VALOR_TASA_REFERENCIA,
  CF.ID_TCA_BASE_CALCULO,
  TBC.DESCRIPCION DESCRIPCION_BASE_CALCULO,
  TBC.DESCRIPCION_CORTA DESCRIPCION_CORTA_BASE_CALCULO,
  TBC.COD_EXTERNO COD_EXTERNO_BASE_CALCULO,
  CF.ID_TCA_FRECUENCIA_PAGO_CAPITAL,
  TF.DESCRIPCION DESCRIPCION_F_PAGO_CAPITAL,
  TF.DESCRIPCION_CORTA DES_CORTA_F_PAGO_CAPITAL,
  TF.COD_EXTERNO COD_EXTERNO_F_PAGO_CAPITAL,
  CF.ID_TCA_FRECUENCIA_REV_TASA,
  TFR.DESCRIPCION DESCRIPCION_FREC_REV_TASA,
  TFR.DESCRIPCION_CORTA DES_CORTA_FREC_REV_TASA,
  TFR.COD_EXTERNO COD_EXTERNO_FREC_REV_TASA,
  CF.ID_TCA_FRECUENCIA_PLAZO,
  TFP.DESCRIPCION DESCRIPCION_FRECUENCIA_PLAZO,
  TFP.DESCRIPCION_CORTA DESCRIPCION_CORTA_FREC_PLAZO,
  TFP.COD_EXTERNO COD_EXTERNO_FREC_PLAZO,
  CF.ID_TCA_FRECUENCIA_PERIODO_GRA,
  TFG.DESCRIPCION DESCRIPCION_PERIODO_GRA,
  TFG.DESCRIPCION_CORTA DESCRIPCION_CORTA_PERIODO_GRA,
  TFG.COD_EXTERNO COD_EXTERNO_PERIODO_GRA,
  CF.ID_TCA_FRECUENCIA_PAGO_INTERES,
  TFI.DESCRIPCION DESCRIPCION_FREC_PAGO_INTERES,
  TFI.DESCRIPCION_CORTA DES_CORTA_FREC_PAGO_INTERES,
  TFI.COD_EXTERNO COD_EXTERNO_FREC_PAGO_INTERES,
  CF.ID_TCA_FRECUENCIA_REV_SPREAD,
  TFS.DESCRIPCION DESCRIPCION_FRE_REV_SPREAD,
  TFS.DESCRIPCION_CORTA DES_CORTA_FRE_REV_SPREAD,
  TFS.COD_EXTERNO COD_EXTERNO_FRE_REV_SPREAD,
  CF.ID_TCA_TIPO_TASA_DESEMBOLSO ID_TIPO_TASA_DESEMBOLSO,
  TTD.DESCRIPCION DESCRIPCION_TASA_DESEMBOLSO,
  TTD.DESCRIPCION_CORTA DESC_CORTA_TASA_DESEMBOLSO,
  TTD.COD_EXTERNO COD_EXTERNO_TASA_DESEMBOLSO,
  FCD.CODIGO CODIGO_PROD_FLEX,
  FCD.DESCRIPCION DESCRIPCION_PROD_FLEX,
  FCD.TIPO_TASA TIPO_TASA_PROD_FLEX,
  FCD.COMPONENTE_PRINCIPAL PRINCIPAL_PROD_FLEX,
  FCD.CODIGO_COMPONENTE CODIGO_COMPONENTE_PROD_FLEX,
  CD.ID_CAT_ACTIVIDAD_ECONOMICA,
  AE.DESCRIPCION DES_ACTIVIDAD_ECONOMICA,
  AE.DESCRIPCION_CORTA DES_CORTA_ACTIVIDAD_ECONOMICA,
  AE.COD_EXTERNO COD_EXT_ACTIVIDAD_ECONOMICA,
  CD.ID_CAT_AREA_FOCALIZACION,
  AF.DESCRIPCION DES_AREA_FOCALIZACION,
  AF.DESCRIPCION_CORTA DES_CORTA_AREA_FOCALIZACION,
  AF.COD_EXTERNO COD_EXTERNO_AREA_FOCALIZACION,
  CD.ID_CAT_EJE_ESTRATEGICO,
  EE.DESCRIPCION DES_EJE_ESTRATEGICO,
  EE.DESCRIPCION_CORTA DES_CORTA_EJE_ESTRATEGICO,
  EE.COD_EXTERNO COD_EXTERNO_EJE_ESTRATEGICO,
  CG.ID CARGO_DESEMBOLSO,
  CG.COMPONENTE,
  CG.MONTO_CARGO,
  CG.FECHA_REGISTRO FECHA_REGISTRO_CARGO,
  CF.ID_TCA_TIPO_CALENDARIO,
  CF.SE_PUEDE_MOVER_ENTRE_MESES,
  TC.DESCRIPCION DESCRIPCION_CALENDARIO,
  TC.DESCRIPCION_CORTA DESCRIPCION_CORTA_CALENDARIO,
  TC.COD_EXTERNO COD_EXTERNO_CALENDARIO, CD.ID_TCA_MODALIDAD_FINAN
FROM CONTRATO_DESEMBOLSO CD
INNER JOIN TRE_SOLICITUD_LINEA_CREDITO TSL
ON (TSL.ID_CONTRATO_DESEMBOLSO = CD.ID)
INNER JOIN LINEA_CREDITO LC
ON (LC.ID = TSL.ID_LINEA)
LEFT JOIN TRE_LINEA_PASIVA TLP
ON (TLP.ID_CONTRATO = CD.ID)
LEFT JOIN FUENTE F
ON (F.ID = TLP.ID_FUENTE)
INNER JOIN TCA_ESTADO_OPERACION TEO
ON (TEO.ID = CD.ID_TCA_ESTADO)
INNER JOIN TCA_TIPO_MONEDA TTM
ON (TTM.ID  = CD.ID_TCA_TIPO_MONEDA)
LEFT JOIN CONDICIONES_FINANCIERAS CF
ON CD.ID = CF.ID_CONTRATO_DESEMBOLSO
LEFT JOIN TCA_TIPO_TASA_DESEMBOLSO TTD
ON CF.ID_TCA_TIPO_TASA_DESEMBOLSO = TTD.ID
LEFT JOIN VTA_PROD_FLEX_COMPONENTE_DESEM FCD
ON CF.ID_PRODUCTO_FLEXCUBE = FCD.ID
LEFT JOIN TCA_TIPO_FRECUENCIA TF
ON TF.ID = CF.ID_TCA_FRECUENCIA_PAGO_CAPITAL
LEFT JOIN TCA_TIPO_FRECUENCIA TFR
ON TFR.ID = CF.ID_TCA_FRECUENCIA_REV_TASA
LEFT JOIN TCA_TIPO_FRECUENCIA TFP
ON TFP.ID = CF.ID_TCA_FRECUENCIA_PLAZO
LEFT JOIN TCA_TIPO_FRECUENCIA TFG
ON TFG.ID = CF.ID_TCA_FRECUENCIA_PERIODO_GRA
LEFT JOIN TCA_TIPO_FRECUENCIA TFI
ON TFI.ID = CF.ID_TCA_FRECUENCIA_PAGO_INTERES
LEFT JOIN TCA_TIPO_FRECUENCIA TFS
ON TFS.ID = CF.ID_TCA_FRECUENCIA_REV_SPREAD
LEFT JOIN TCA_BASE_CALCULO TBC
ON TBC.ID = CF.ID_TCA_BASE_CALCULO
LEFT JOIN VCA_TASAS_DESEMBOLSO_FLEXCUBE TDF
ON TDF.CODIGO = CF.CODIGO_TASA_REFERENCIA
LEFT JOIN VCA_TASAS_SPREAD_DESEM_FLEX TDSF
ON TDSF.CODIGO=CF.CODIGO_TASA_REFERENCIA_SPREAD
LEFT JOIN CAT_ACTIVIDAD_ECONOMICA AE
ON AE.ID = CD.ID_CAT_ACTIVIDAD_ECONOMICA
LEFT JOIN CAT_EJE_ESTRATEGICO EE
ON EE.ID = CD.ID_CAT_EJE_ESTRATEGICO
LEFT JOIN CAT_AREA_FOCALIZACION AF
ON AF.ID = CD.ID_CAT_AREA_FOCALIZACION
LEFT JOIN CARGO_DESEMBOLSO CG
ON CG.ID_CONTRATO_DESEMBOLSO = CD.ID
LEFT JOIN TCA_TIPO_CALENDARIO TC
ON TC.ID = CF.ID_TCA_TIPO_CALENDARIO
LEFT JOIN VCA_FUENTE TVF
ON TVF.ID = F.ID_LINEA_PASIVA
WHERE CD.ID in( select * from table(P_ID_DESEMBOLSO))
AND TTM.DESCRIPCION_CORTA = NVL(TDF.CODIGO_MONEDA ,TTM.DESCRIPCION_CORTA);

OPEN RECORDSET2 FOR 

SELECT CC.ID CALENDARIO_COMPLEJO, CC.TIPO_PAGO TIPO_PAGO_CALENDARIO, 
DC.FECHA_PAGO FECHA_PAGO_CALENDARIO,DC.MONTO_PAGO MONTO_PAGO_CALENDARIO, CC.ID_CONDICION_FINANCIERA,
CF.ID_CONTRATO_DESEMBOLSO
FROM CALENDARIO_COMPLEJO CC
INNER JOIN CONDICIONES_FINANCIERAS CF
ON CF.ID = CC.ID_CONDICION_FINANCIERA
INNER JOIN DETALLE_CALENDARIO DC
ON (CC.ID = DC.ID_CALENDARIO_COMPLEJO)
WHERE CF.ID_CONTRATO_DESEMBOLSO in( select * from table(P_ID_DESEMBOLSO))
ORDER BY DC.FECHA_PAGO ASC;

P_CODIGO_RES := 0;

EXCEPTION
WHEN OTHERS THEN

P_CODIGO_RES := SQLCODE;

P_MENSAJE := SQLERRM;

END;