create or replace PROCEDURE SP_CONSULTAR_HERRAMIENTA_CE (
P_COD_EXTERNO_ACTIVIDAD IN VARCHAR2,
P_COD_EXTERNO_AREA IN VARCHAR2,
P_COD_EXTERNO_EJE IN VARCHAR2,
RECORDSET_ACTIVIDAD   OUT SYS_REFCURSOR,
RECORDSET_AREA        OUT SYS_REFCURSOR,
RECORDSET_EJE         OUT SYS_REFCURSOR,
P_CODIGO_RES          OUT NUMBER,
P_MENSAJE             OUT VARCHAR2)

IS

BEGIN 

IF P_COD_EXTERNO_ACTIVIDAD IS NOT NULL THEN

OPEN RECORDSET_ACTIVIDAD FOR

  SELECT ID ID_ACTIVIDAD, DESCRIPCION DESCRIPCION_ACTIVIDAD,DESCRIPCION_CORTA DESCRIPCION_CORTA_ACTIVIDAD, COD_EXTERNO COD_EXTERNO_ACTIVIDAD, BAN_ESTATUS BAN_ESTATUS_ACTIVIDAD
  FROM CAT_ACTIVIDAD_ECONOMICA
  WHERE COD_EXTERNO = P_COD_EXTERNO_ACTIVIDAD;
  
END IF;

IF P_COD_EXTERNO_AREA IS NOT NULL THEN

OPEN RECORDSET_AREA FOR 
  
  SELECT ID ID_AREA, DESCRIPCION DESCRIPCION_AREA,DESCRIPCION_CORTA DESCRIPCION_CORTA_AREA, COD_EXTERNO COD_EXTERNO_AREA, BAN_ESTATUS BAN_ESTATUS_AREA
  FROM CAT_AREA_FOCALIZACION
  WHERE COD_EXTERNO = P_COD_EXTERNO_AREA;
  
  
END IF;

IF P_COD_EXTERNO_EJE IS NOT NULL THEN

OPEN RECORDSET_EJE FOR 

SELECT ID ID_EJE, DESCRIPCION DESCRIPCION_EJE,DESCRIPCION_CORTA DESCRIPCION_CORTA_EJE, COD_EXTERNO COD_EXTERNO_EJE, BAN_ESTATUS BAN_ESTATUS_EJE
FROM CAT_EJE_ESTRATEGICO
WHERE COD_EXTERNO = P_COD_EXTERNO_EJE;

END IF;

EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      P_CODIGO_RES := 0;
      P_MENSAJE :=
         'Error en el procedimiento Consultar Herramienta Clasificacion Estrategica (HCE), No existen datos!';
   WHEN OTHERS
   THEN
      P_CODIGO_RES := 0;
      P_MENSAJE := 'Error en el procedimiento Consultar Herramienta Clasificacion Estrategica (HCE)!';
END;