CREATE OR REPLACE VIEW VTA_TAREAS_ACTIVAS AS

	SELECT 
	TPO.ID_OPERACION, 
	TPO.NOMBRE_OPERACION, 
	TPO.ID_PROCESO,
	TPB.DESCRIPCION AS DESCRIPCION_PROCESO,
	TPO.ID_TAREA, 
	TTB.DESCRIPCION AS DESCRIPCION_TAREA,
	TRB.DESCRIPCION AS ROL,
	TPO.FECHA_REGISTRO AS FECHA_INICIO, 
	TPO.USUARIO
	FROM TBI_PROCESO_OPERACION TPO
	INNER JOIN TCA_PROCESO_BPM TPB ON(TPB.ID=TPO.ID_PROCESO)
	INNER JOIN TCA_TAREA_BPM TTB ON(TTB.ID=TPO.ID_TAREA)
	INNER JOIN TCA_ROL_BPM TRB ON(TRB.ID=TTB.ID_ROL_BPM)
	WHERE TPO.BAN_ES_PROCESO=0 AND TPO.BAN_ES_FIN_ACTIVIDAD=0 AND TPO.BAN_FINALIZADO=0
	ORDER BY 1 DESC;