<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/PrepagoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/PrepagoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:preMO="http://www.bcie.org/PrepagoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/PrepagoMO" schemaLocation="../../Schema/PrepagoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ReportePrepagoRequestMessage">
    <part name="request" element="preMO:ReportePrepagoRequest"/>
  </message>
  <message name="ReportePrepagoResponseMessage">
    <part name="response" element="preMO:ReportePrepagoResponse"/>
  </message>
  <portType name="ReportePrepagoPT">
    <operation name="ReportePrepago">
      <input message="tns:ReportePrepagoRequestMessage"/>
      <output message="tns:ReportePrepagoResponseMessage"/>
    </operation>
  </portType>
  <binding name="ReportePrepagoPTSOAP12Bnd" type="tns:ReportePrepagoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ReportePrepago">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/PrepagoService/ReportePrepago"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>