<wsdl:definitions name="CrearBitacoraReactivarOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearBitacoraReactivarOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearBitacoraReactivarOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearBitacoraReactivarOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearBitacoraReactivarOperacion_DB_plt">
    <plt:role name="CrearBitacoraReactivarOperacion_DB_role">
      <plt:portType name="tns:CrearBitacoraReactivarOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearBitacoraReactivarOperacion_DB" schemaLocation="../XSD/CrearBitacoraReactivarOperacion_DB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="TbiReactivaOperacionCollection_msg">
        <wsdl:part name="TbiReactivaOperacionCollection" element="top:TbiReactivaOperacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearBitacoraReactivarOperacion_DB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TbiReactivaOperacionCollection_msg"/>
            <wsdl:output message="tns:TbiReactivaOperacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>