<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="urn:ActualizarDetalleEnmiendaSAD" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="urn:ActualizarDetalleEnmiendaSAD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ActualizarDetalleEnmienda_SB">
      <plnk:role name="ActualizarDetalleEnmiendaRequest_PT" portType="tns:ActualizarDetalleEnmiendaRequest_PT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="urn:ActualizarDetalleEnmiendaSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/MatrizTCC/V1/Wsdl/ADAPTER/ActualizarDetalleEnmiendaSAD.wsdl"/>
</wsdl:definitions>
