<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarLineaCreditoFormalizacionSOR"
     targetNamespace="http://www.bcie.org/ConsultarLineaCreditoFormalizacionSOR"
     xmlns:tns="http://www.bcie.org/ConsultarLineaCreditoFormalizacionSOR"
     xmlns:linCreBO="http://www.bcie.org/LineaCreditoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestConsultarLineaCreditoFormalizacionMessage">
        <wsdl:part name="request" element="linCreBO:ConsultarLineaCreditoFormalizacionRequest"/>
    </wsdl:message>
    <wsdl:message name="responseConsultarLineaCreditoFormalizacionMessage">
        <wsdl:part name="response" element="linCreBO:ConsultarLineaCreditoFormalizacionResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarLineaCreditoFormalizacion_PT">
        <wsdl:operation name="ConsultarLineaCreditoFormalizacion">
            <wsdl:input message="tns:requestConsultarLineaCreditoFormalizacionMessage"/>
            <wsdl:output message="tns:responseConsultarLineaCreditoFormalizacionMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsultarLineaCreditoFormalizacion_PTSOAP12Binding" type="tns:ConsultarLineaCreditoFormalizacion_PT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ConsultarLineaCreditoFormalizacion">
            <soap12:operation style="document" soapAction="ConsultarLineaCreditoFormalizacion" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
