<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSB_BCIE/CANALES/GenerarReciboPago" name="GenerarReciboPago-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GenerarReciboPago.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSB_BCIE/CANALES/GenerarReciboPago"/>
    <wsdl:binding name="Consume_Message_ptt-binding" type="gen:Consume_Message_ptt" xmlns:gen="http://xmlns.oracle.com/pcbpel/adapter/jms/OSB_BCIE/CANALES/GenerarReciboPago">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Consume_Message">
            <soap:operation soapAction="Consume_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>