<?binding.jca InsertaContactosClienteService_db.jca?><wsdl:definitions name="InsertaContactosClienteService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/InsertaContacto/InsertaContactosClienteService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/InsertaContacto/InsertaContactosClienteService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertaContactosClienteService">
    <plt:partnerLinkType name="InsertaContactosClienteService_plt">
        <plt:role name="InsertaContactosClienteService_role">
            <plt:portType name="tns:InsertaContactosClienteService_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertaContactosClienteService" schemaLocation="../XSD/InsertaContactosClienteService_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ContactosClienteCollection_msg">
        <wsdl:part name="ContactosClienteCollection" element="top:ContactosClienteCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertaContactosClienteService_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ContactosClienteCollection_msg"/>
            <wsdl:output message="tns:ContactosClienteCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>