<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/DistributeCostChangeRequestProcess/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:cost="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/DistributeCostChangeRequestProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage">
   <plnk:partnerLinkType name="DistributeCostChangeRequestProcessBPEL">
      <plnk:role name="DistributeCostChangeRequestProcessPType" portType="cost:DistributeCostChangeRequestProcessPType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/DistributeCostChangeRequestProcess/v1.0" location="DistributeCostChangeRequestProcessWSDL.wsdl"/>
   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" schemaLocation="../Schemas/Commons/AGStandardMessageSchema.xsd"/>
      </xsd:schema>
   </wsdl:types>
</wsdl:definitions>
