<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/CrearComisionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearComisionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:comMO="http://www.bcie.org/ComisionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ComisionMO"
                  schemaLocation="../../../../Comision/V1/Schema/ComisionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CrearComisionRequestMessage">
    <wsdl:part name="request" element="comMO:CrearComisionRequest"/>
  </wsdl:message>
  <wsdl:message name="CrearComisionResponseMessage">
    <wsdl:part name="response" element="comMO:CrearComisionResponse"/>
  </wsdl:message>
  <wsdl:portType name="CrearComisionPT">
    <wsdl:operation name="crearComision">
      <wsdl:input message="tns:CrearComisionRequestMessage"/>
      <wsdl:output message="tns:CrearComisionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CrearComision12Bnd" type="tns:CrearComisionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearComision">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CrearComisionService/crearComision"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>