<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSFindItemDbReference" name="RMSFindItemDbReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSFindItemDbReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSFindItemDbReference"/>
    <wsdl:binding name="RMSFindItemDbReference_ptt-binding" type="rms:RMSFindItemDbReference_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSFindItemDbReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSFindItemDbReference">
            <soap:operation soapAction="RMSFindItemDbReference"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>