<wsdl:definitions name="RMSFindItemDbReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSFindItemDbReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Proyectos/Applications/RMSFindItemDbReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindItemDbReference" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="RMSFindItemDbReference_plt">
    <plt:role name="RMSFindItemDbReference_role">
      <plt:portType name="tns:RMSFindItemDbReference_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindItemDbReference" schemaLocation="RMSFindItemDbReference.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindItemDbReference" schemaLocation="RMSFindItemDbReference.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindItemDbReference" schemaLocation="RMSFindItemDbReference.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="RMSFindItemDbReferenceInput_msg">
        <wsdl:part name="RMSFindItemDbReferenceInput_msg" element="db:RMSFindItemDbReferenceInput"/>
    </wsdl:message>
    <wsdl:message name="RMSFindItemDbReferenceOutputCollection_msg">
        <wsdl:part name="RMSFindItemDbReferenceOutputCollection" element="db:RMSFindItemDbReferenceOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="RMSFindItemDbReference_ptt">
        <wsdl:operation name="RMSFindItemDbReference">
            <wsdl:input message="tns:RMSFindItemDbReferenceInput_msg"/>
            <wsdl:output message="tns:RMSFindItemDbReferenceOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>