<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="caseOneDb" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ItemCataloApp/ItemCatalogTranslate/caseOneDb" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ItemCataloApp/ItemCatalogTranslate/caseOneDb" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneDb" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="caseOneDb_plt">
      <plt:role name="caseOneDb_role">
         <plt:portType name="tns:caseOneDb_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneDb" schemaLocation="../Schemas/caseOneDb_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="caseOneDbSelect_inputParameters">
      <wsdl:part name="caseOneDbSelect_inputParameters" element="top:caseOneDbSelect_idC1_appCodeC1_catIdC1_targetAppCodeC1InputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmItemsCatalogsCollection_msg">
      <wsdl:part name="MdmItemsCatalogsCollection" element="top:MdmItemsCatalogsCollection"/>
   </wsdl:message>
   <wsdl:portType name="caseOneDb_ptt">
      <wsdl:operation name="caseOneDbSelect">
         <wsdl:input message="tns:caseOneDbSelect_inputParameters"/>
         <wsdl:output message="tns:MdmItemsCatalogsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
