<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidarLimitesLimSAD"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ValidarLimitesLimSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ValidarLimitesLimSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ValidarLimitesLIM">
        <plnk:role name="ValidarLimitesLim_ptt" portType="tns:ValidarLimitesLim_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ValidarLimitesLimSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ValidarLimitesLimSAD.wsdl"/>
</wsdl:definitions>
