<wsdl:definitions name="ActualizarContrato_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarContrato_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarContrato_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarContrato_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarContrato_DB_plt">
    <plt:role name="ActualizarContrato_DB_role">
      <plt:portType name="tns:ActualizarContrato_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarContrato_DB" schemaLocation="../XSD/ActualizarContrato_DB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ContratoCollection_msg">
        <wsdl:part name="ContratoCollection" element="top:ContratoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarContrato_DB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:ContratoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>