<wsdl:definitions name="consultarCodigoCliente_DB"
                  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/consultarCodigoCliente_DB"
                  xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/consultarCodigoCliente_DB"
                  xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                  xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/consultarCodigoCliente_DB"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="consultarCodigoCliente_DB_plt">
    <plt:role name="consultarCodigoCliente_DB_role">
      <plt:portType name="tns:consultarCodigoCliente_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultarCodigoCliente_DB" schemaLocation="../XSD/consultarCodigoCliente_DB.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="consultarCodigoCliente_DBInput_msg">
    <wsdl:part name="consultarCodigoCliente_DBInput_msg" element="db:consultarCodigoCliente_DBInput"/>
  </wsdl:message>
  <wsdl:message name="consultarCodigoCliente_DBOutputCollection_msg">
    <wsdl:part name="consultarCodigoCliente_DBOutputCollection" element="db:consultarCodigoCliente_DBOutputCollection"/>
  </wsdl:message>
  <wsdl:portType name="consultarCodigoCliente_DB_ptt">
    <wsdl:operation name="consultarCodigoCliente_DB">
      <wsdl:input message="tns:consultarCodigoCliente_DBInput_msg"/>
      <wsdl:output message="tns:consultarCodigoCliente_DBOutputCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>