<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDACreateBuyerProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDACreateBuyerProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N4="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDACreateBuyerProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="JDACreateBuyerProcessPXY">
      <plnk:role name="CreateBuyerPType" portType="WL5G3N4:CreateBuyerPType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDACreateBuyerProcess" location="http://172.16.19.34:7004/Capabilities/Core/Buyer/BuyerEntitySvc/PS/JDACreateBuyerProcessPXY?WSDL"/>
</wsdl:definitions>
