<wsdl:definitions
     name="consultarCodExterno"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarOperacion/consultarCodExterno"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarOperacion/consultarCodExterno"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/consultarCodExterno"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="consultarCodExterno_plt" >
    <plt:role name="consultarCodExterno_role" >
      <plt:portType name="tns:consultarCodExterno_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/consultarCodExterno" schemaLocation="../XSD/consultarCodExterno_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="consultarCodExternoSelect_inputParameters">
        <wsdl:part name="consultarCodExternoSelect_inputParameters" element="top:consultarCodExternoSelect_pIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="TcaProcesoBpmCollection_msg">
        <wsdl:part name="TcaProcesoBpmCollection" element="top:TcaProcesoBpmCollection"/>
    </wsdl:message>
    <wsdl:portType name="consultarCodExterno_ptt">
        <wsdl:operation name="consultarCodExternoSelect">
            <wsdl:input message="tns:consultarCodExternoSelect_inputParameters"/>
            <wsdl:output message="tns:TcaProcesoBpmCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
