<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ObtenerValidadoresActivos" name="ObtenerValidadoresActivos-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ObtenerValidadoresActivos.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ObtenerValidadoresActivos"/>
    <wsdl:binding name="ObtenerValidadoresActivos_ptt-binding" type="obt:ObtenerValidadoresActivos_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ObtenerValidadoresActivos">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerValidadoresActivos">
            <soap:operation soapAction="ObtenerValidadoresActivos"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>