<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/PurchaseOrder/PurchaseOrderEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrderResponseAcknowledgeEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/PurchaseOrder/PurchaseOrderEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="PurchaseOrderResponseAcknowledgeEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE SEP 22 01:00:28 CDT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Code"/>
   <xsl:param name="Messages"/>
   <xsl:param name="Detail"/>
   <xsl:param name="TrackingID"/>
   <xsl:param name="InstanceID"/>
   <xsl:template match="/">
      <ns0:PurchaseOrderResponseAcknowledgeEBM>
         <ns0:Acknowledge>
            <com:Code>
               <xsl:value-of select="$Code"/>
            </com:Code>
            <com:Message>
               <xsl:value-of select="$Messages"/>
            </com:Message>
            <com:Detail>
               <xsl:value-of select="$Detail"/>
            </com:Detail>
            <com:InstanceID>
               <xsl:value-of select="$InstanceID"/>
            </com:InstanceID>
            <com:TrackingID>
               <xsl:value-of select="$TrackingID"/>
            </com:TrackingID>
         </ns0:Acknowledge>
      </ns0:PurchaseOrderResponseAcknowledgeEBM>
   </xsl:template>
</xsl:stylesheet>