<wsdl:definitions
     name="InsertarGenerarDetalleGestionCobro"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/InsertarGenerarDetalleGestionCobro/InsertarGenerarDetalleGestionCobro"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/InsertarGenerarDetalleGestionCobro/InsertarGenerarDetalleGestionCobro"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertarGenerarDetalleGestionCobro"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InsertarGenerarDetalleGestionCobro_plt" >
    <plt:role name="InsertarGenerarDetalleGestionCobro_role" >
      <plt:portType name="tns:InsertarGenerarDetalleGestionCobro_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertarGenerarDetalleGestionCobro" schemaLocation="../XSD/InsertarGenerarDetalleGestionCobro_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DetalleLoteCollection_msg">
        <wsdl:part name="DetalleLoteCollection" element="top:DetalleLoteCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertarGenerarDetalleGestionCobro_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:DetalleLoteCollection_msg"/>
            <wsdl:output message="tns:DetalleLoteCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
