<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ComisionesDesembolsoSOR" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ComisionesDesembolsoSOR" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"  xmlns:desMO="http://www.bcie.org/DesembolsoMO">
    <types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </types>
    <message name="requestComisionesDesembolsoMessage">
        <part name="request" element="desMO:ComisionesDesembolsoRequest"/>
    </message>
    <message name="responseComisionesDesembolsoMessage">
        <part name="response" element="desMO:ComisionesDesembolsoResponse"/>
    </message>
    <portType name="ComisionesDesembolsoPT">
        <operation name="comisionesDesembolso">
            <input message="tns:requestComisionesDesembolsoMessage"/>
            <output message="tns:responseComisionesDesembolsoMessage"/>
        </operation>
    </portType>
    <binding name="ComisionesDesembolsoPT12Bnd" type="tns:ComisionesDesembolsoPT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="comisionesDesembolso">
            <soap12:operation style="document"
                              soapAction="http://www.bcie.org/ComisionesDesembolsoSOR/comisionesDesembolso"/>
            <input>
                <soap12:body use="literal" parts="request"/>
            </input>
            <output>
                <soap12:body use="literal" parts="response"/>
            </output>
        </operation>
    </binding>
</definitions>