<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarCondicion" name="EliminarCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarCondicion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarCondicion"/>
    <wsdl:binding name="EliminarCondicion_ptt-binding" type="elim:EliminarCondicion_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarCondicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarCondicion">
            <soap:operation soapAction="EliminarCondicion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>