<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project16/ConsultarEventoCondicion" name="ConsultarEventoCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarEventoCondicionV2.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project16/ConsultarEventoCondicion"/>
    <wsdl:binding name="ConsultarEventoCondicion_ptt-binding" type="con:ConsultarEventoCondicion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project16/ConsultarEventoCondicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarEventoCondicion">
            <soap:operation soapAction="ConsultarEventoCondicion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>