<wsdl:definitions
     name="ConsultarClienteEnProcesoByIdCliente"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClienteEnProcesoByIdCliente"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClienteEnProcesoByIdCliente"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarClienteEnProcesoByIdCliente"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarClienteEnProcesoByIdCliente_plt" >
    <plt:role name="ConsultarClienteEnProcesoByIdCliente_role" >
      <plt:portType name="tns:ConsultarClienteEnProcesoByIdCliente_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarClienteEnProcesoByIdCliente" schemaLocation="../XSD/ConsultarClienteEnProcesoByIdCliente.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarClienteEnProcesoByIdClienteInput_msg">
        <wsdl:part name="ConsultarClienteEnProcesoByIdClienteInput_msg" element="db:ConsultarClienteEnProcesoByIdClienteInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarClienteEnProcesoByIdClienteOutputCollection_msg">
        <wsdl:part name="ConsultarClienteEnProcesoByIdClienteOutputCollection" element="db:ConsultarClienteEnProcesoByIdClienteOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarClienteEnProcesoByIdCliente_ptt">
        <wsdl:operation name="ConsultarClienteEnProcesoByIdCliente">
            <wsdl:input message="tns:ConsultarClienteEnProcesoByIdClienteInput_msg"/>
            <wsdl:output message="tns:ConsultarClienteEnProcesoByIdClienteOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
