<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ClienteService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ClienteService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:cliMO="http://www.bcie.org/ClienteMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="requestEliminarClienteMessage">
    <part name="request" element="cliMO:EliminarClienteRequest"/>
  </message>
  <message name="responseEliminarClienteMessage">
    <part name="response" element="cliMO:EliminarClienteResponse"/>
  </message>
  <portType name="ClientePT">
    <operation name="eliminarCliente">
      <input message="tns:requestEliminarClienteMessage"/>
      <output message="tns:responseEliminarClienteMessage"/>
    </operation>
  </portType>
  <binding name="Cliente12Bnd" type="tns:ClientePT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarCliente">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ClienteService/eliminarCliente"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>