<wsdl:definitions
     name="ActualizarEstadoCondicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoCondicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoCondicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarEstadoCondicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarEstadoCondicion_plt" >
    <plt:role name="ActualizarEstadoCondicion_role" >
      <plt:portType name="tns:ActualizarEstadoCondicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarEstadoCondicion" schemaLocation="../XSD/ActualizarEstadoCondicion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarEstadoCondicionInput_msg">
        <wsdl:part name="ActualizarEstadoCondicionInput_msg" element="db:ActualizarEstadoCondicionInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarEstadoCondicion_ptt">
        <wsdl:operation name="ActualizarEstadoCondicion">
            <wsdl:input message="tns:ActualizarEstadoCondicionInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
