<wsdl:definitions
     name="ConsultarClienteByIdCliente"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClienteByIdCliente"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClienteByIdCliente"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarClienteByIdCliente"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarClienteByIdCliente_plt" >
    <plt:role name="ConsultarClienteByIdCliente_role" >
      <plt:portType name="tns:ConsultarClienteByIdCliente_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarClienteByIdCliente" schemaLocation="../XSD/ConsultarClienteByIdCliente.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarClienteByIdClienteInput_msg">
        <wsdl:part name="ConsultarClienteByIdClienteInput_msg" element="db:ConsultarClienteByIdClienteInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarClienteByIdClienteOutputCollection_msg">
        <wsdl:part name="ConsultarClienteByIdClienteOutputCollection" element="db:ConsultarClienteByIdClienteOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarClienteByIdCliente_ptt">
        <wsdl:operation name="ConsultarClienteByIdCliente">
            <wsdl:input message="tns:ConsultarClienteByIdClienteInput_msg"/>
            <wsdl:output message="tns:ConsultarClienteByIdClienteOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
