<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RPMExportPriceCostChangeApp/RPMExportPriceCostChange/RPMPriceCostChangeExport" name="RPMPriceCostChangeExport-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RPMPriceCostChangeExport.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RPMExportPriceCostChangeApp/RPMExportPriceCostChange/RPMPriceCostChangeExport"/>
    <wsdl:binding name="RPMPriceCostChangeExport_ptt-binding" type="rpm:RPMPriceCostChangeExport_ptt" xmlns:rpm="http://xmlns.oracle.com/pcbpel/adapter/db/RPMExportPriceCostChangeApp/RPMExportPriceCostChange/RPMPriceCostChangeExport">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RPMPriceCostChangeExport">
            <soap:operation soapAction="RPMPriceCostChangeExport"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>