<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarVotacion" name="ValidarVotacion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ValidarVotacion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarVotacion"/>
    <wsdl:binding name="ValidarVotacion_ptt-binding" type="val:ValidarVotacion_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarVotacion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ValidarVotacion">
            <soap:operation soapAction="ValidarVotacion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>