SET DEFINE OFF;
--1.CREATE_TCA_TIPO_CUESTIONARIO.sql
Prompt ./Secuencias/FEMIX.1.CREATE_TCA_TIPO_CUESTIONARIO_SEQ.sql
     @ ./Secuencias/FEMIX.1.CREATE_TCA_TIPO_CUESTIONARIO_SEQ.sql
Prompt ./Triggers/FEMIX.1.CREATE_TCA_TIPO_CUESTIONARIO_TRG.sql
     @ ./Triggers/FEMIX.1.CREATE_TCA_TIPO_CUESTIONARIO_TRG.sql
Prompt ./DDL/FEMIX.1.CREATE_TCA_TIPO_CUESTIONARIO_DDL.sql
     @ ./DDL/FEMIX.1.CREATE_TCA_TIPO_CUESTIONARIO_DDL.sql
--2.INSERT_TCA_TIPO_CUESTIONARIO.sql
Prompt ./Datos/FEMIX.2.INSERT_TCA_TIPO_CUESTIONARIO_DATOS.sql
     @ ./Datos/FEMIX.2.INSERT_TCA_TIPO_CUESTIONARIO_DATOS.sql
--3.CREATE_TCO_PROCESO_BPM_CUESTIONARIO.sql
-- n/a
--4.INSERT_TCO_PROCESO_BPM_CUESTIONARIO.sql
Prompt ./Datos/FEMIX.4.INSERT_TCO_PROCESO_BPM_CUESTIONARIO_DATOS.sql
     @ ./Datos/FEMIX.4.INSERT_TCO_PROCESO_BPM_CUESTIONARIO_DATOS.sql
--5.UPDATE_COLUMN_VERSION_CUESTIONARIO_Y_CUESTIONARIO.sql
Prompt ./DDL/FEMIX.5.UPDATE_COLUMN_VERSION_CUESTIONARIO_Y_CUESTIONARIO_DDL.sql
     @ ./DDL/FEMIX.5.UPDATE_COLUMN_VERSION_CUESTIONARIO_Y_CUESTIONARIO_DDL.sql
Prompt ./Datos/FEMIX.5.UPDATE_COLUMN_VERSION_CUESTIONARIO_Y_CUESTIONARIO_DATOS.sql
     @ ./Datos/FEMIX.5.UPDATE_COLUMN_VERSION_CUESTIONARIO_Y_CUESTIONARIO_DATOS.sql
--6.INSERT_UT_PLANTILLA.sql
Prompt ./Datos/FEMIX.6.INSERT_UT_PLANTILLA_DATOS.sql
     @ ./Datos/FEMIX.6.INSERT_UT_PLANTILLA_DATOS.sql
--7.INSERT_TCA_TAG_PLANTILLA.sql
Prompt ./Datos/FEMIX.7.INSERT_TCA_TAG_PLANTILLA_DATOS.sql
     @ ./Datos/FEMIX.7.INSERT_TCA_TAG_PLANTILLA_DATOS.sql
--8.UPDATE_UT_PLANTILLA.sql
Prompt ./Datos/FEMIX.8.UPDATE_UT_PLANTILLA_DATOS.sql
     @ ./Datos/FEMIX.8.UPDATE_UT_PLANTILLA_DATOS.sql
--9.INSERT_TCA_PLANTILLA_CORREO.sql
Prompt ./Datos/FEMIX.9.INSERT_TCA_PLANTILLA_CORREO_DATOS.sql
     @ ./Datos/FEMIX.9.INSERT_TCA_PLANTILLA_CORREO_DATOS.sql	
--10.INSERT_TRE_PLANTILLA_CORREO.sql
Prompt ./Datos/FEMIX.10.INSERT_TRE_PLANTILLA_CORREO_DATOS.sql
     @ ./Datos/FEMIX.10.INSERT_TRE_PLANTILLA_CORREO_DATOS.sql
--11.CREATE_TCO_PREGUNTA_OPCION_NOTIFICACION.sql
--N/A
--12.INSERT_CAT_PREGUNTAS_FORMULARIO.sql
Prompt ./Datos/FEMIX.12.INSERT_CAT_PREGUNTAS_FORMULARIO_DATOS.sql
     @ ./Datos/FEMIX.12.INSERT_CAT_PREGUNTAS_FORMULARIO_DATOS.sql
-- 13. SP_GENERAR_CUESTIONARIOS_PROCESO
Prompt ./Procedimientos/FENIX.13.SP_GENERAR_CUESTIONARIOS_PROCESO_SP.sql
     @ ./Procedimientos/FENIX.13.SP_GENERAR_CUESTIONARIOS_PROCESO_SP.sql
-- 13.1. F_GENERAR_CUESTIONARIO
Prompt ./Funciones/FENIX.13.1. F_GENERAR_CUESTIONARIO_FN
     @ ./Funciones/FENIX.13.1. F_GENERAR_CUESTIONARIO_FN
--13.2. F_GENERAR_FORMULARIO
Prompt ./Funciones/FENIX.13.2. F_GENERAR_CUESTIONARIO_FN
     @ ./Funciones/FENIX.13.2. F_GENERAR_CUESTIONARIO_FN