<definitions targetNamespace="http://msoffice.utils.ea.agarcia.mx/" name="ExcelParsingUtilService" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://msoffice.utils.ea.agarcia.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/">
<types>
<xsd:schema>
<xsd:import namespace="http://msoffice.utils.ea.agarcia.mx/" schemaLocation="../Schema/ExcelParsingUtilSchema.xsd"/>
</xsd:schema>
</types>
<message name="parse">
<part name="parameters" element="tns:parse"/>
</message>
<message name="parseResponse">
<part name="parameters" element="tns:parseResponse"/>
</message>
<message name="MSOfficeUtilException">
<part name="fault" element="tns:MSOfficeUtilException"/>
</message>
<portType name="ExcelParsingUtil">
<operation name="parse">
<input wsam:Action="http://msoffice.utils.ea.agarcia.mx/ExcelParsingUtil/parseRequest" message="tns:parse"/>
<output wsam:Action="http://msoffice.utils.ea.agarcia.mx/ExcelParsingUtil/parseResponse" message="tns:parseResponse"/>
<fault message="tns:MSOfficeUtilException" name="MSOfficeUtilException" wsam:Action="http://msoffice.utils.ea.agarcia.mx/ExcelParsingUtil/parse/Fault/MSOfficeUtilException"/>
</operation>
</portType>
<binding name="ExcelParsingUtilPortBinding" type="tns:ExcelParsingUtil">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="parse">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault name="MSOfficeUtilException">
<soap:fault name="MSOfficeUtilException" use="literal"/>
</fault>
</operation>
</binding>
<service name="ExcelParsingUtilService">
<port name="ExcelParsingUtilPort" binding="tns:ExcelParsingUtilPortBinding">
<soap:address location="http://gpsoaapp1.agarcia.com.mx:8005/AGMSOfficeUtils/ExcelParsingUtilPort"/>
</port>
</service>
</definitions>