<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:CrearContratoSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:CrearContratoSAD" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/ContratoMO" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ContratoMO"
                  schemaLocation="../../Schema/ContratoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="CrearContratoRequestMessage">
    <part name="CrearContratoRequest" element="conMO:CrearContratoRequest"/>
  </message>
  <message name="CrearContratoResponseMessage">
    <part name="CrearContratoResponse" element="conMO:CrearContratoResponse"/>
  </message>
  <portType name="CrearContratoPT">
    <operation name="crearContrato">
      <input message="tns:CrearContratoRequestMessage"/>
      <output message="tns:CrearContratoResponseMessage"/>
    </operation>
  </portType>
  <binding name="CrearContratoPTSOAP12Binding" type="tns:CrearContratoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearContrato">
      <soap12:operation style="document" soapAction="urn:CrearContratoSAD/crearContrato"/>
      <input>
        <soap12:body use="literal" parts="CrearContratoRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="CrearContratoResponse"/>
      </output>
    </operation>
  </binding>
</definitions>