<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/AprobacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:aproMO="http://www.bcie.org/AprobacionMO"
                  xmlns:tns="http://xmlns.bcie.com/AprobacionService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
  <wsdl:message name="requestActualizarAprobacionMessage">
    <wsdl:part name="request" element="aproMO:ActualizarAprobacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseActualizarAprobacionMessage">
    <wsdl:part name="response" element="aproMO:ActualizarAprobacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ActualizarAprobacionPT">
    <!-- Create -->
    <wsdl:operation name="ActualizarAprobacion">
      <wsdl:documentation>Actualizar una aprobación</wsdl:documentation>
      <wsdl:input message="tns:requestActualizarAprobacionMessage"/>
      <wsdl:output message="tns:responseActualizarAprobacionMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ActualizarAprobacion12Bnd" type="tns:ActualizarAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ActualizarAprobacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/AprobacionService/ActualizarAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ActualizarAprobacion">
    <wsdl:port name="ActualizarAprobacion12Bnd" binding="tns:ActualizarAprobacion12Bnd">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>






