<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/FulfillmentOrder" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns0="http://www.agarcia.mx/EnterpriseObjects/Custom">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source/>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/FulfillmentOrder/FulfillmentOrderEBM.xsd"/>
        <oracle-xsl-mapper:rootElement name="CreateFulfillmentOrderResponseEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/FulfillmentOrder"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED SEP 09 00:11:39 CDT 2020].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CreateFulfillmentOrderResponseEBM>
      <tns:Response>
        <com:Code>
          <xsl:value-of select="DVMFunctions:lookupValue (&quot;MetaData/dvm/ERROR_CODE.dvm&quot;, &quot;CODE&quot;, &quot;GEN-0000&quot;, &quot;ERROR_CODE&quot;, &quot;NOT FOUND&quot;)"/>
        </com:Code>
        <com:Message>
          <xsl:value-of select="DVMFunctions:lookupValue (&quot;MetaData/dvm/ERROR_CODE.dvm&quot;, &quot;CODE&quot;, &quot;GEN-0000&quot;, &quot;USER_MESSAGE&quot;, &quot;NOT FOUND&quot;)"/>
        </com:Message>
        <com:Detail>
          <xsl:value-of select="DVMFunctions:lookupValue (&quot;MetaData/dvm/ERROR_CODE.dvm&quot;, &quot;CODE&quot;, &quot;GEN-0000&quot;, &quot;CATEGORY&quot;, &quot;NOT FOUND&quot;)"/>
        </com:Detail>
        <com:TrackingID>
          <xsl:value-of select="oraext:generate-guid ( )"/>
        </com:TrackingID>
        <com:Operation>CreateReturnToVendor</com:Operation>
        <com:Interface>CreateReturnToVendorRMSAdapterService</com:Interface>
        <com:Application>
          <com:Name>RIB/RMS</com:Name>
        </com:Application>
      </tns:Response>
      <tns:FulfillmentOrderRecordHistory>
        <com:CreationDate>
          <xsl:value-of select="xp20:format-dateTime (xp20:current-dateTime(), &quot;[Y001]-[M01]-[D01]T[h01]:[m01]:[s01]&quot; )"/>
        </com:CreationDate>
        <com:CreatedBy>RIB</com:CreatedBy>
        <com:LastUpdateDate>
          <xsl:value-of select="xp20:format-dateTime (xp20:current-dateTime(), &quot;[Y001]-[M01]-[D01]T[h01]:[m01]:[s01]&quot; )"/>
        </com:LastUpdateDate>
        <com:LastUpdatedBy>RIB</com:LastUpdatedBy>
      </tns:FulfillmentOrderRecordHistory>
    </tns:CreateFulfillmentOrderResponseEBM>
  </xsl:template>
</xsl:stylesheet>