<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarProductoComisionByIdLineaCredito_DB" name="ConsultarProductoComisionByIdLineaCredito_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarProductoComisionByIdLineaCredito_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarProductoComisionByIdLineaCredito_DB"/>
    <wsdl:binding name="ConsultarProductoComisionByIdLineaCredito_DB_ptt-binding" type="con:ConsultarProductoComisionByIdLineaCredito_DB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarProductoComisionByIdLineaCredito_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarProductoComisionByIdLineaCredito_DB">
            <soap:operation soapAction="ConsultarProductoComisionByIdLineaCredito_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>