<wsdl:definitions name="ConsultarProductoComisionByIdLineaCredito_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarProductoComisionByIdLineaCredito_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarProductoComisionByIdLineaCredito_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarProductoComisionByIdLineaCredito_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarProductoComisionByIdLineaCredito_DB_plt">
    <plt:role name="ConsultarProductoComisionByIdLineaCredito_DB_role">
      <plt:portType name="tns:ConsultarProductoComisionByIdLineaCredito_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarProductoComisionByIdLineaCredito_DB" schemaLocation="../XSD/ConsultarProductoComisionByIdLineaCredito_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarProductoComisionByIdLineaCredito_DBInput_msg">
        <wsdl:part name="ConsultarProductoComisionByIdLineaCredito_DBInput_msg" element="db:ConsultarProductoComisionByIdLineaCredito_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarProductoComisionByIdLineaCredito_DBOutputCollection_msg">
        <wsdl:part name="ConsultarProductoComisionByIdLineaCredito_DBOutputCollection" element="db:ConsultarProductoComisionByIdLineaCredito_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarProductoComisionByIdLineaCredito_DB_ptt">
        <wsdl:operation name="ConsultarProductoComisionByIdLineaCredito_DB">
            <wsdl:input message="tns:ConsultarProductoComisionByIdLineaCredito_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarProductoComisionByIdLineaCredito_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>