<wsdl:definitions
     name="AuditReader_JMS_Service"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/BanescoT24SOA/COMP_Commons/AuditReader_JMS_Service"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/BanescoT24SOA/COMP_Commons/AuditReader_JMS_Service"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://xmlns.banesco.com/eopt/AuditAdd_V1.0"
    >
  <plt:partnerLinkType name="ConsumeAuditMsg_plt" >
    <plt:role name="ConsumeAuditMsg_role" >
      <plt:portType name="tns:ConsumeAuditMsg_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.banesco.com/eopt/AuditAdd_V1.0" schemaLocation="../Schemas/AuditAdd_V1.0.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsumeAuditMsg_msg">
        <wsdl:part name="body" element="imp1:AuditAddRq"/>
    </wsdl:message>
    <wsdl:portType name="ConsumeAuditMsg_ptt">
        <wsdl:operation name="ConsumeAuditMsg">
            <wsdl:input message="tns:ConsumeAuditMsg_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
