<wsdl:definitions name="RMSCreateRetailStore" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateRetailStore" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateRetailStore" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="http://www.oracle.com/retail/integration/base/bo/StoreDesc/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="RMSCreateRetailStoreMessage_plt">
    <plt:role name="RMSCreateRetailStoreMessage_role">
      <plt:portType name="tns:RMSCreateRetailStoreMessage_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://www.oracle.com/retail/integration/base/bo/StoreDesc/v1" schemaLocation="../../Schema/StoreDesc.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="RMSCreateRetailStoreMessage_msg">
        <wsdl:part name="body" element="imp1:StoreDesc"/>
    </wsdl:message>
    <wsdl:portType name="RMSCreateRetailStoreMessage_ptt">
        <wsdl:operation name="RMSCreateRetailStoreMessage">
            <wsdl:input message="tns:RMSCreateRetailStoreMessage_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>