<wsdl:definitions name="SyncStoreMDM" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/SyncStoreMDM" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/SyncStoreMDM" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SyncStoreMDM" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="SyncStoreMDM_plt">
    <plt:role name="SyncStoreMDM_role">
      <plt:portType name="tns:SyncStoreMDM_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SyncStoreMDM" schemaLocation="SyncStoreMDM_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="MdmRetailstoresCollection_msg">
        <wsdl:part name="MdmRetailstoresCollection" element="top:MdmRetailstoresCollection"/>
    </wsdl:message>
    <wsdl:portType name="SyncStoreMDM_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:MdmRetailstoresCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>