<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ConfirmOrderBUS/OrderConfirmService/ftpPaepsaCreateOrderConfirm" name="ftpPaepsaCreateOrderConfirm-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../OrderConfirmService/Resources/Paepsa/ftpPaepsaCreateOrderConfirm.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ConfirmOrderBUS/OrderConfirmService/ftpPaepsaCreateOrderConfirm"/>
    <wsdl:binding name="Process_ptt-binding" type="ftp:Process_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/ConfirmOrderBUS/OrderConfirmService/ftpPaepsaCreateOrderConfirm">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Process">
            <soap:operation soapAction="Process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>