<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarLineaCreditoByCondicion" name="ConsultarLineaCreditoByCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarLineaCreditoByCondicion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarLineaCreditoByCondicion"/>
    <wsdl:binding name="ConsultarLineaCreditoByCondicion_ptt-binding" type="con:ConsultarLineaCreditoByCondicion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarLineaCreditoByCondicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarLineaCreditoByCondicion">
            <soap:operation soapAction="ConsultarLineaCreditoByCondicion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>