<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSeguimientoCrediticioByIdClienteDB" name="ConsultarSeguimientoCrediticioByIdClienteDB_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarSeguimientoCrediticioByIdClienteDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSeguimientoCrediticioByIdClienteDB"/>
    <wsdl:binding name="ConsultarSeguimientoCrediticioByIdClienteDB_ptt-binding" type="con:ConsultarSeguimientoCrediticioByIdClienteDB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSeguimientoCrediticioByIdClienteDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarSeguimientoCrediticioByIdClienteDB">
            <soap:operation soapAction="ConsultarSeguimientoCrediticioByIdClienteDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>