<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/EnmiendasProcess"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1" xmlns:ns1="http://www.example.org"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:ns2="http://www.bcie.org/CatalogoBO"
                xmlns:ns3="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns4="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns6="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:ns5="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1"
                xmlns:eqTr="http://www.bcie.org/EqipoTrabajo/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PU01/ReasignacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ReasignacionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"/>
        <oracle-xsl-mapper:param name="reasignacionDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA04/EnmiendasProcess.xsd"/>
        <oracle-xsl-mapper:rootElement name="InicioEnmiendas"
                                       namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/EnmiendasProcess"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [FRI NOV 03 12:25:54 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:InicioEnmiendas>
      <tns:Header>
        <header:Operacion>
          <ns3:CodigoOperacion>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:CodigoOperacion"/>
          </ns3:CodigoOperacion>
          <ns3:NombreOperacion>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:NombreOperacion"/>
          </ns3:NombreOperacion>
          <ns3:ResponsableOperacion>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:ResponsableOperacion"/>
          </ns3:ResponsableOperacion>
          <ns3:CodigoCliente>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:CodigoCliente"/>
          </ns3:CodigoCliente>
          <ns3:NombreCliente>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:NombreCliente"/>
          </ns3:NombreCliente>
          <ns3:CodigoProducto>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:CodigoProducto"/>
          </ns3:CodigoProducto>
          <ns3:NombreProducto>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:NombreProducto"/>
          </ns3:NombreProducto>
          <ns3:MontoSolicitado>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:MontoSolicitado"/>
          </ns3:MontoSolicitado>
          <ns3:Pais>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns3:Pais"/>
          </ns3:Pais>
        </header:Operacion>
        <header:Tarea>
          <ns6:CodigoTarea>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns6:CodigoTarea"/>
          </ns6:CodigoTarea>
          <ns6:NombreTarea>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns6:NombreTarea"/>
          </ns6:NombreTarea>
          <ns6:CodigoRol>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns6:CodigoRol"/>
          </ns6:CodigoRol>
          <ns6:NombreRol>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns6:NombreRol"/>
          </ns6:NombreRol>
          <ns6:CodigoProceso>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns6:CodigoProceso"/>
          </ns6:CodigoProceso>
          <ns6:NombreProceso>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns6:NombreProceso"/>
          </ns6:NombreProceso>
        </header:Tarea>
        <parameter:ParameterType>
          <parameter:parameterName>TIPO_ENMIENDA</parameter:parameterName>
          <parameter:parameterValue>2</parameter:parameterValue>
        </parameter:ParameterType>
        <parameter:ParameterType>
          <parameter:parameterName>TIPO_INICIO</parameter:parameterName>
          <parameter:parameterValue>3</parameter:parameterValue>
        </parameter:ParameterType>
        <parameter:ParameterType>
          <parameter:parameterName>IDENMIENDA</parameter:parameterName>
          <parameter:parameterValue>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:IdEnmienda"/>
          </parameter:parameterValue>
        </parameter:ParameterType>
      </tns:Header>
    </tns:InicioEnmiendas>
  </xsl:template>
</xsl:stylesheet>
