<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="dbFenixInformeOtros" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdquisicionesWSFenix/AdquisicionWeb/dbFenixInformeOtros" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdquisicionesWSFenix/AdquisicionWeb/dbFenixInformeOtros" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbFenixInformeOtros" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="dbFenixInformeOtros_plt">
      <plt:role name="dbFenixInformeOtros_role">
         <plt:portType name="tns:dbFenixInformeOtros_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <plt:partnerLinkType name="dbFenixInformeOtros_plt">
      <plt:role name="dbFenixInformeOtros_role">
         <plt:portType name="tns:dbFenixInformeOtros_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <plt:partnerLinkType name="dbFenixInformeOtros_plt">
      <plt:role name="dbFenixInformeOtros_role">
         <plt:portType name="tns:dbFenixInformeOtros_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFenixInformeOtros" schemaLocation="../Schemas/dbFenixInformeOtros.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFenixInformeOtros" schemaLocation="../Schemas/dbFenixInformeOtros.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFenixInformeOtros" schemaLocation="../Schemas/dbFenixInformeOtros.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="dbFenixInformeOtrosInput_msg">
      <wsdl:part name="dbFenixInformeOtrosInput_msg" element="db:dbFenixInformeOtrosInput"/>
   </wsdl:message>
   <wsdl:message name="dbFenixInformeOtrosOutputCollection_msg">
      <wsdl:part name="dbFenixInformeOtrosOutputCollection" element="db:dbFenixInformeOtrosOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="dbFenixInformeOtros_ptt">
      <wsdl:operation name="dbFenixInformeOtros">
         <wsdl:input message="tns:dbFenixInformeOtrosInput_msg"/>
         <wsdl:output message="tns:dbFenixInformeOtrosOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
