<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="BPELProcess1" targetNamespace="http://xmlns.oracle.com/AdquisicionesWSFenix/AdquisicionWeb/BPELProcess1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/AdquisicionesWSFenix/AdquisicionWeb/BPELProcess1" xmlns:ns1="http://www.bcie.org/AdquisicionMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.bcie.org/AdquisicionMO" schemaLocation="../Schemas/AdquisicionMO.xsd"/>
      </schema>
   </wsdl:types>
</wsdl:definitions>
