<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDocumento/ConsultarDocumentosFenix" name="ConsultarDocumentosFenix_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarDocumentosFenix.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDocumento/ConsultarDocumentosFenix"/>
    <wsdl:binding name="ConsultarDocumentosFenix_ptt-binding" type="con:ConsultarDocumentosFenix_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDocumento/ConsultarDocumentosFenix">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarDocumentosFenix">
            <soap:operation soapAction="ConsultarDocumentosFenix"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>