<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://web.seg.mod.cgs.com"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://xmlns.banesco.com/eopt/PersonPartyRiskInq_V1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 wsdl apachesoap ns1 eoStatus wsdlsoap tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Common_V1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:apachesoap="http://xml.apache.org/xml-soap"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Party/PersonPartyRiskInq/PersonPartyRiskInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PersonPartyRiskInqRq"
                                       namespace="http://xmlns.banesco.com/eopt/PersonPartyRiskInq_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/SICG/resources/wsdl/CalculoManagerSoapBindingMock.wsdl"/>
        <oracle-xsl-mapper:rootElement name="calculoRiesgoN" namespace="http://web.seg.mod.cgs.com"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI AUG 05 11:49:12 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:calculoRiesgoN>
      <tns:tipo>
        <xsl:value-of select='"2"'/>
      </tns:tipo>
      <tns:tident>
        <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/AttrValues", "CANONICAL", string (/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PartyKey/eoPar:IssuedIdentType), "SICG", "CouldNotBeFound")'/>
      </tns:tident>
      <tns:creacion>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:EstablishedDt"/>
      </tns:creacion>
      <tns:cod_ind>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:Employment/eoPar:OrgData/eoPar:Sector"/>
      </tns:cod_ind>
      <tns:cod_neg>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:BusinessType"/>
      </tns:cod_neg>
      <tns:pais_rd>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:ResidenceCountry/ns2:CountryCodeValue"/>
      </tns:pais_rd>
      <tns:pais_or>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:CountryOfBirth"/>
      </tns:pais_or>
      <tns:prof>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:Profession/ns2:Type"/>
      </tns:prof>
      <tns:funt_ing>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:FinancialData/eoPar:Desc"/>
      </tns:funt_ing>
      <tns:cla_cli>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:ServiceLevel"/>
      </tns:cla_cli>
      <tns:rel_ban>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:OEDRelationship"/>
      </tns:rel_ban>
      <tns:nacionalidad>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:Nationality"/>
      </tns:nacionalidad>
      <tns:provincia>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:PersonData/eoPar:Contact/ns2:Locator/ns2:PostAddr/ns2:Province"/>
      </tns:provincia>
      <tns:distrito>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:PersonData/eoPar:Contact/ns2:Locator/ns2:PostAddr/ns2:CountyDistrict"/>
      </tns:distrito>
      <tns:corregimiento>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:PersonData/eoPar:Contact/ns2:Locator/ns2:PostAddr/ns2:Corregimiento"/>
      </tns:corregimiento>
      <tns:estado>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:PersonData/eoPar:Contact/ns2:Locator/ns2:PostAddr/ns2:State"/>
      </tns:estado>
      <tns:fch_nac_cons>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:BirthDt"/>
      </tns:fch_nac_cons>
      <tns:sexo>
        <xsl:value-of select="/ns0:PersonPartyRiskInqRq/ns0:Party/eoPar:PersonPartyInfo/eoPar:Gender"/>
      </tns:sexo>
    </tns:calculoRiesgoN>
  </xsl:template>
</xsl:stylesheet>
