<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ValidarClienteProceso/ValidarClienteProceso" name="ValidarClienteProceso_bs-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ValidarClienteProceso.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ValidarClienteProceso/ValidarClienteProceso"/>
    <wsdl:binding name="ValidarClienteProceso_ptt-binding" type="val:ValidarClienteProceso_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ValidarClienteProceso/ValidarClienteProceso">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ValidarClienteProceso">
            <soap:operation soapAction="ValidarClienteProceso"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>