<wsdl:definitions
     name="ActualizarContratoInstaciaProceso"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project10/ActualizarContratoInstaciaProceso"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project10/ActualizarContratoInstaciaProceso"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarContratoInstaciaProceso"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarContratoInstaciaProceso_plt" >
    <plt:role name="ActualizarContratoInstaciaProceso_role" >
      <plt:portType name="tns:ActualizarContratoInstaciaProceso_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarContratoInstaciaProceso" schemaLocation="../XSD/ActualizarContratoInstaciaProceso.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarContratoInstaciaProcesoInput_msg">
        <wsdl:part name="ActualizarContratoInstaciaProcesoInput_msg" element="db:ActualizarContratoInstaciaProcesoInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarContratoInstaciaProceso_ptt">
        <wsdl:operation name="ActualizarContratoInstaciaProceso">
            <wsdl:input message="tns:ActualizarContratoInstaciaProcesoInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
