<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ActualizarContratoService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ActualizarContratoService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ActualizarContrato">
        <plnk:role name="ActualizarContratoPT" portType="tns:ActualizarContratoPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ActualizarContratoService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Contrato/V1/Wsdl/ADAPTER/ActualizarContratoSAD.wsdl"/>
</wsdl:definitions>
