<wsdl:definitions
     name="ConsultarTreDeclaracionOperacion_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarTreDeclaracionOperacion_DB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarTreDeclaracionOperacion_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreDeclaracionOperacion_DB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarTreDeclaracionOperacion_DB_plt" >
    <plt:role name="ConsultarTreDeclaracionOperacion_DB_role" >
      <plt:portType name="tns:ConsultarTreDeclaracionOperacion_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreDeclaracionOperacion_DB"
                schemaLocation="../XSD/ConsultarTreDeclaracionOperacion_DB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTreDeclaracionOperacion_DBInput_msg">
        <wsdl:part name="ConsultarTreDeclaracionOperacion_DBInput_msg" element="db:ConsultarTreDeclaracionOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTreDeclaracionOperacion_DBOutputCollection_msg">
        <wsdl:part name="ConsultarTreDeclaracionOperacion_DBOutputCollection" element="db:ConsultarTreDeclaracionOperacion_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTreDeclaracionOperacion_DB_ptt">
        <wsdl:operation name="ConsultarTreDeclaracionOperacion_DB">
            <wsdl:input message="tns:ConsultarTreDeclaracionOperacion_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarTreDeclaracionOperacion_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
