<wsdl:definitions name="FTPPaepsaCreateCNRInvoiceReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/DownloadCNRInvoiceApp/FTPPaepsaCreateCNRInvoiceReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/DownloadCNRInvoiceApp/FTPPaepsaCreateCNRInvoiceReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:imp1="http://www.agarcia.mx/EnterpriseObjects/CNRInvoice" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Put_plt">
    <plt:role name="Put_role">
      <plt:portType name="tns:Put_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/DownloadCNRInvoiceApp/FTPPaepsaCreateCNRInvoiceReference" xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://www.agarcia.mx/EnterpriseObjects/CNRInvoice" schemaLocation="../../MetaData/Components/EnterpriseObjectLibrary/EBO/CNRInvoice/XSDToLinesFtpBuros.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Put_msg">
        <wsdl:part name="body" element="imp1:Root-Element"/>
    </wsdl:message>
    <wsdl:portType name="Put_ptt">
        <wsdl:operation name="Put">
            <wsdl:input message="tns:Put_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>