<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Cliente" targetNamespace="http://xmlns.bcie.com/ClienteService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cliMO="http://www.bcie.org/ClienteMO"
                  xmlns:tns="http://xmlns.bcie.com/ClienteService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
  <!-- Create -->
  <wsdl:message name="requestCrearClienteFLEXCUBEMessage">
    <wsdl:part name="request" element="cliMO:CrearClienteFLEXCUBERequest"/>
  </wsdl:message>
  <wsdl:message name="responseCrearClienteFLEXCUBEMessage">
    <wsdl:part name="response" element="cliMO:CrearClienteFLEXCUBEResponse"/>
  </wsdl:message>

  <wsdl:portType name="CrearClienteFLEXCUBEPT">
    <!-- Create -->
    <wsdl:operation name="crearCliente">
      <wsdl:documentation>Registra un Cliente en FLEXCUBE</wsdl:documentation>
      <wsdl:input message="tns:requestCrearClienteFLEXCUBEMessage"/>
      <wsdl:output message="tns:responseCrearClienteFLEXCUBEMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CrearClienteFLEXCUBE12Bnd" type="tns:CrearClienteFLEXCUBEPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <!-- Create -->
    <wsdl:operation name="crearCliente">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ClienteService/crearCliente"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
