<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:ConsultarOperacionesByIdCliente" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ConsultarOperacionesByIdCliente" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:cliMO="http://www.bcie.org/ClienteMO">
  <types>
       <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConsultarOperacionesByIdClienteRequestMessage">
    <part name="ConsultarOperacionesByIdClienteRequest" element="cliMO:ConsultarOperacionesByIdClienteRequest"/>
  </message>
  <message name="ConsultarOperacionesByIdClienteResponseMessage">
    <part name="ConsultarOperacionesByIdClienteResponse" element="cliMO:ConsultarOperacionesByIdClienteResponse"/>
  </message>
  <portType name="ConsultarOperacionesByIdClientePT">
    <operation name="consultarOperacionesByIdCliente">
      <input message="tns:ConsultarOperacionesByIdClienteRequestMessage"/>
      <output message="tns:ConsultarOperacionesByIdClienteResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarOperacionesByIdClientePT12Bnd" type="tns:ConsultarOperacionesByIdClientePT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarOperacionesByIdCliente">
      <soap12:operation style="document"
                        soapAction="urn:ConsultarOperacionesByIdCliente/consultarOperacionesByIdCliente"/>
      <input>
        <soap12:body use="literal" parts="ConsultarOperacionesByIdClienteRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ConsultarOperacionesByIdClienteResponse"/>
      </output>
    </operation>
  </binding>
</definitions>