<wsdl:definitions
     name="ConsultarLineaCreditoByCondicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarLineaCreditoByCondicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarLineaCreditoByCondicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLineaCreditoByCondicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarLineaCreditoByCondicion_plt" >
    <plt:role name="ConsultarLineaCreditoByCondicion_role" >
      <plt:portType name="tns:ConsultarLineaCreditoByCondicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLineaCreditoByCondicion" schemaLocation="../XSD/ConsultarLineaCreditoByCondicion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarLineaCreditoByCondicionInput_msg">
        <wsdl:part name="ConsultarLineaCreditoByCondicionInput_msg" element="db:ConsultarLineaCreditoByCondicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarLineaCreditoByCondicionOutputCollection_msg">
        <wsdl:part name="ConsultarLineaCreditoByCondicionOutputCollection" element="db:ConsultarLineaCreditoByCondicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarLineaCreditoByCondicion_ptt">
        <wsdl:operation name="ConsultarLineaCreditoByCondicion">
            <wsdl:input message="tns:ConsultarLineaCreditoByCondicionInput_msg"/>
            <wsdl:output message="tns:ConsultarLineaCreditoByCondicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
