<wsdl:definitions
     name="CrearActualizarTransferenciaRecursos"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CrearActualizarTransferenciaRecursos"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CrearActualizarTransferenciaRecursos"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarTransferenciaRecursos"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearActualizarTransferenciaRecursos_plt" >
    <plt:role name="CrearActualizarTransferenciaRecursos_role" >
      <plt:portType name="tns:CrearActualizarTransferenciaRecursos_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarTransferenciaRecursos" schemaLocation="../XSD/CrearActualizarTransferenciaRecursos_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TransferenciaRecursosCollection_msg">
        <wsdl:part name="TransferenciaRecursosCollection" element="top:TransferenciaRecursosCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearActualizarTransferenciaRecursos_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:TransferenciaRecursosCollection_msg"/>
            <wsdl:output message="tns:TransferenciaRecursosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
