<wsdl:definitions
     name="ActualizarComision_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarComision_DB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarComision_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarComision_DB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarComision_DB_plt" >
    <plt:role name="ActualizarComision_DB_role" >
      <plt:portType name="tns:ActualizarComision_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarComision_DB" schemaLocation="../XSD/ActualizarComision_DB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ComisionCollection_msg">
        <wsdl:part name="ComisionCollection" element="top:ComisionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarComision_DB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:ComisionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
