<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/MergeAgrupador" name="MergeAgrupador-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="MergeAgrupador.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/MergeAgrupador"/>
    <wsdl:binding name="MergeAgrupador_ptt-binding" type="mer:MergeAgrupador_ptt" xmlns:mer="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/MergeAgrupador">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="MergeAgrupador">
            <soap:operation soapAction="MergeAgrupador"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>