<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ExcelParsingUtilService" targetNamespace="http://msoffice.utils.ea.agarcia.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N1="http://msoffice.utils.ea.agarcia.mx/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ExcelParsingUtilPXY">
      <plnk:role name="ExcelParsingUtil" portType="WL5G3N1:ExcelParsingUtil"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://msoffice.utils.ea.agarcia.mx/" location="http://172.16.19.34:7004/Applications/Commons/MSOfficeUtil/PS/ExcelParsingUtilPXY/v1.0?wsdl"/>
</wsdl:definitions>
