<wsdl:definitions name="CreateReturnToVendorRMSAdapterService" targetNamespace="http://xmlns.oracle.com/OSBAGApp/ReturnToVendorApp/CreateReturnToVendorRMSAdapterService" xmlns:tns="http://xmlns.oracle.com/OSBAGApp/ReturnToVendorApp/CreateReturnToVendorRMSAdapterService" xmlns:inp1="http://www.agarcia.mx/EnterpriseObjects/FulfillmentOrder" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/FulfillmentOrder" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/FulfillmentOrder/FulfillmentOrderEBM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:SyncFulfillmentOrderEBM"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="response" element="inp1:SyncFulfillmentOrderResponseEBM"/>
    </wsdl:message>
    <wsdl:portType name="syncReturnToVendor_ptt">
        <wsdl:operation name="sync">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:syncReturnToVendor_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="sync">
            <soap12:operation style="document" soapAction="execute" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSBAGApp/ReturnToVendorApp/CreateReturnToVendorRMSAdapterService"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSBAGApp/ReturnToVendorApp/CreateReturnToVendorRMSAdapterService"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>