<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://mx.agarcia.ea/Applications/JDA/Items/ModifyItem/v1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N4="http://mx.agarcia.ea/Applications/JDA/Items/ModifyItem/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="JDAModifyStylePxy">
      <plnk:role name="modifyItemPort" portType="WL5G3N4:modifyItemPort"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Applications/JDA/Items/ModifyItem/v1.0" location="http://prd-osb.agarcia.com.mx:7004/Applications/JDA/JDAItem/PS/Style/JDAModifyStylePXY?WSDL"/>
</wsdl:definitions>
