<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:CrearAprobacionSOR" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:CrearAprobacionSOR" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:aproMO="http://www.bcie.org/AprobacionMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="CrearAprobacionRequestMessage">
    <part name="CrearAprobacionRequest" element="aproMO:CrearAprobacionRequest"/>
  </message>
  <message name="CrearAprobacionResponseMessage">
    <part name="CrearAprobacionResponse" element="aproMO:CrearAprobacionResponse"/>
  </message>
  <portType name="CrearAprobacionPT">
    <operation name="crearAprobacion">
      <input message="tns:CrearAprobacionRequestMessage"/>
      <output message="tns:CrearAprobacionResponseMessage"/>
    </operation>
  </portType>
  <binding name="CrearAprobacionPTSOAP12Binding" type="tns:CrearAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearAprobacion">
      <soap12:operation style="document" soapAction="urn:CrearAprobacionSOR/crearAprobacion"/>
      <input>
        <soap12:body use="literal" parts="CrearAprobacionRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="CrearAprobacionResponse"/>
      </output>
    </operation>
  </binding>
</definitions>