<wsdl:definitions
     name="AMLTRAMA345FT"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24Adapter/Inbound/AMLTRAMA345FT"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24Adapter/Inbound/AMLTRAMA345FT"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="EventPoll_plt" >
    <plt:role name="EventPoll_role" >
      <plt:portType name="tns:EventPoll_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
    <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
            xmlns="http://www.w3.org/2001/XMLSchema" >
      <element name="opaqueElement" type="base64Binary" />
    </schema>
    </wsdl:types>
    <wsdl:message name="EventPoll_msg">
        <wsdl:part name="opaque" element="opaque:opaqueElement"/>
    </wsdl:message>
    <wsdl:portType name="EventPoll_ptt">
        <wsdl:operation name="EventPoll">
            <wsdl:input message="tns:EventPoll_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="EventPoll_pttSOAP11Binding" type="tns:EventPoll_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="EventPoll">
            <soap:operation style="document"
                            soapAction="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24Adapter/Inbound/AMLTRAMA345FT/EventPoll"/>
            <wsdl:input>
                <soap:body use="literal" parts="opaque"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
