<wsdl:definitions
     name="AdditionalInfo"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/outbound/ApplicationSOABanesco/AcctAdd/AdditionalInfo"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/outbound/ApplicationSOABanesco/AcctAdd/AdditionalInfo"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="BanAAAdditionalInfoSvc_plt" >
    <plt:role name="BanAAAdditionalInfoSvc_role" >
      <plt:portType name="tns:BanAAAdditionalInfoSvcPort" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
    <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
            xmlns="http://www.w3.org/2001/XMLSchema" >
      <element name="opaqueElement" type="base64Binary" />
    </schema>
    </wsdl:types>
    <wsdl:message name="Outbound_msg">
        <wsdl:part name="opaque" element="opaque:opaqueElement"/>
    </wsdl:message>
    <wsdl:portType name="BanAAAdditionalInfoSvcPort">
        <wsdl:operation name="Outbound">
            <wsdl:input message="tns:Outbound_msg"/>
            <wsdl:output message="tns:Outbound_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BanAAAdditionalInfoSvcBinding_SOAP11" type="tns:BanAAAdditionalInfoSvcPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Outbound">
            <soap:operation style="document"
                            soapAction="http://xmlns.oracle.com/pcbpel/adapter/outbound/ApplicationSOABanesco/AcctAdd/AdditionalInfo/Outbound"/>
            <wsdl:input>
                <soap:body use="literal" parts="opaque"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="opaque"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
