<wsdl:definitions name="BS_T24_BPAENQCUSTOMERPJ"
                  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/outbound/T24Adapter/T24Adapter/BS_T24_BPAENQCUSTOMERPJ"
                  xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/outbound/T24Adapter/T24Adapter/BS_T24_BPAENQCUSTOMERPJ"
                  xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                  xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="Outbound_plt">
    <plt:role name="Outbound_role">
      <plt:portType name="tns:Outbound_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <xsd:schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/">
      <xsd:element name="opaqueElement" type="xsd:base64Binary"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="Outbound_msg">
    <wsdl:part name="opaque" element="opaque:opaqueElement"/>
  </wsdl:message>
  <wsdl:portType name="Outbound_ptt">
    <wsdl:operation name="Outbound">
      <wsdl:input message="tns:Outbound_msg"/>
      <wsdl:output message="tns:Outbound_msg"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Outbound_ptt-binding" type="bs:Outbound_ptt"
                xmlns:bs="http://xmlns.oracle.com/pcbpel/adapter/outbound/T24Adapter/T24Adapter/BS_T24_BPAENQCUSTOMERPJ">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="Outbound">
      <soap:operation soapAction="Outbound"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
