<wsdl:definitions name="consultarCondicionByRol" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/consultarCondicionByRol" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/consultarCondicionByRol" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/consultarCondicionByRol" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="consultarCondicionByRol_plt">
    <plt:role name="consultarCondicionByRol_role">
      <plt:portType name="tns:consultarCondicionByRol_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultarCondicionByRol" schemaLocation="../XSD/consultarCondicionByRol.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="consultarCondicionByRolInput_msg">
        <wsdl:part name="consultarCondicionByRolInput_msg" element="db:consultarCondicionByRolInput"/>
    </wsdl:message>
    <wsdl:message name="consultarCondicionByRolOutputCollection_msg">
        <wsdl:part name="consultarCondicionByRolOutputCollection" element="db:consultarCondicionByRolOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="consultarCondicionByRol_ptt">
        <wsdl:operation name="consultarCondicionByRol">
            <wsdl:input message="tns:consultarCondicionByRolInput_msg"/>
            <wsdl:output message="tns:consultarCondicionByRolOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>