<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.agarcia.mx/nxsd/SyncAllocationSaalmaRespMsg" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/Allocation" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns2="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../NXSDs/nxsd_SyncAllocationSaalmaResponse.xsd"/>
            <oracle-xsl-mapper:rootElement name="AllocationResponse" namespace="http://www.agarcia.mx/nxsd/SyncAllocationSaalmaRespMsg"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Allocation/AllocationEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="SyncAllocationResponseEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Allocation"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU OCT 01 14:23:20 CDT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:SyncAllocationResponseEBM>
         <tns:Response>
            <xsl:choose>
              <xsl:when test="/ns0:AllocationResponse/ns0:resultado='true'">
                 <com:Code>
                    <xsl:value-of select="dvm:lookupValue('MetaData/dvm/ERROR_CODE.dvm','CODE','GEN-0000','ERROR_CODE','Not Found')"/>
                 </com:Code>
              </xsl:when>
              <xsl:otherwise>
                 <com:Code>
                    <xsl:value-of select="dvm:lookupValue('MetaData/dvm/ERROR_CODE.dvm','CODE','GEN-0011','ERROR_CODE','Not Found')"/>
                 </com:Code>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:AllocationResponse/ns0:resultado='true'">
                <com:Message>
                 <xsl:value-of select="dvm:lookupValue('MetaData/dvm/ERROR_CODE.dvm','CODE','GEN-0000','USER_MESSAGE','Not Found')"/>
                </com:Message>
              </xsl:when>
              <xsl:otherwise>
                <com:Message>
                 <xsl:value-of select="dvm:lookupValue('MetaData/dvm/ERROR_CODE.dvm','CODE','GEN-0011','USER_MESSAGE','Not Found')"/>
                </com:Message>
              </xsl:otherwise>
            </xsl:choose>
            <com:Detail>
               <xsl:value-of select="/ns0:AllocationResponse/ns0:mensaje"/>
            </com:Detail>
            <com:Entity>
               <com:ID>
                  <xsl:value-of select="/ns0:AllocationResponse/ns0:claveOS"/>
               </com:ID>
            </com:Entity>
         </tns:Response>
      </tns:SyncAllocationResponseEBM>
   </xsl:template>
</xsl:stylesheet>