<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ExtraerReportePrepago" name="ExtraerReportePrepago_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ExtraerReportePrepago.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ExtraerReportePrepago"/>
    <wsdl:binding name="ExtraerReportePrepago_ptt-binding" type="ext:ExtraerReportePrepago_ptt" xmlns:ext="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ExtraerReportePrepago">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ExtraerReportePrepago">
            <soap:operation soapAction="ExtraerReportePrepago"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>