<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ClienteService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ClienteService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:cliMO="http://www.bcie.org/ClienteMO">
  <types>
    <xsd:schema targetNamespace="http://xmlns.bcie.com/ClienteService/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarClienteByIdMessage">
    <part name="request" element="cliMO:ConsultarClienteByIdClienteRequest"/>
  </message>
  <message name="responseConsultarClienteByIdMessage">
    <part name="response" element="cliMO:ConsultarClienteResponse"/>
  </message>
  <portType name="ConsultarClienteById_PT">
    <operation name="consultarClienteById">
      <input message="tns:requestConsultarClienteByIdMessage"/>
      <output message="tns:responseConsultarClienteByIdMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarClienteById_PTSOAP12Binding" type="tns:ConsultarClienteById_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarClienteById">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ClienteService/consultarClienteById"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>