<wsdl:definitions name="ConsultarComisionesAsignadas" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarComisionesAsignadas" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarComisionesAsignadas" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionesAsignadas" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarComisionesAsignadas_plt">
    <plt:role name="ConsultarComisionesAsignadas_role">
      <plt:portType name="tns:ConsultarComisionesAsignadas_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionesAsignadas" schemaLocation="../XSD/ConsultarComisionesAsignadas.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarComisionesAsignadasInput_msg">
        <wsdl:part name="ConsultarComisionesAsignadasInput_msg" element="db:ConsultarComisionesAsignadasInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarComisionesAsignadasOutputCollection_msg">
        <wsdl:part name="ConsultarComisionesAsignadasOutputCollection" element="db:ConsultarComisionesAsignadasOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarComisionesAsignadas_ptt">
        <wsdl:operation name="ConsultarComisionesAsignadas">
            <wsdl:input message="tns:ConsultarComisionesAsignadasInput_msg"/>
            <wsdl:output message="tns:ConsultarComisionesAsignadasOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>