REM INSERTING into TCA_PRODUCTO_TAREA
SET DEFINE OFF;
Insert into fenix.TCA_PRODUCTO_TAREA (ID_TAREA,ID_PRODUCTO,BAN_ESTATUS) values (220,1,1);
Insert into fenix.TCA_PRODUCTO_TAREA (ID_TAREA,ID_PRODUCTO,BAN_ESTATUS) values (55,1,1);
Insert into fenix.TCA_PRODUCTO_TAREA (ID_TAREA,ID_PRODUCTO,BAN_ESTATUS) values (220,28,1);
Insert into fenix.TCA_PRODUCTO_TAREA (ID_TAREA,ID_PRODUCTO,BAN_ESTATUS) values (55,28,1);
