<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CondicionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/CondicionMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarAgrupadorByCondicionRequestMessage">
    <part name="request" element="conMO:ConsultarAgrupadorByCondicionRequest"/>
  </message>
  <message name="ConsultarAgrupadorByCondicionResponseMessage">
    <part name="response" element="conMO:ConsultarAgrupadorByCondicionResponse"/>
  </message>
  <portType name="ConsultarAgrupadorByCondicionPT">
    <operation name="ConsultarAgrupadorByCondicion">
      <input message="tns:ConsultarAgrupadorByCondicionRequestMessage"/>
      <output message="tns:ConsultarAgrupadorByCondicionResponseMessage"/>
    </operation>
  </portType>
  <binding name="Condicion12Bnd" type="tns:ConsultarAgrupadorByCondicionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarAgrupadorByCondicion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CondicionService/consultarAgrupadorByCondicion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>