<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CondicionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:conMO="http://www.bcie.org/CondicionMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="UpsertTransaccionCondicionRequestMessage">
    <part name="request" element="conMO:UpsertTransaccionCondicionRequest"/>
  </message>
  <message name="UpsertTransaccionCondicionResponseMessage">
    <part name="response" element="conMO:UpsertTransaccionCondicionResponse"/>
  </message>
  <portType name="UpsertTransaccionCondicionPT">
    <operation name="UpsertTransaccionCondicion">
      <input message="tns:UpsertTransaccionCondicionRequestMessage"/>
      <output message="tns:UpsertTransaccionCondicionResponseMessage"/>
    </operation>
  </portType>
  <binding name="UpsertTransaccionCondicionPTSOAP12Bnd" type="tns:UpsertTransaccionCondicionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="UpsertTransaccionCondicion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CondicionService/UpsertTransaccionCondicion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>