<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/OperacionMO" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/OperacionMO" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/OperacionMO"
                  schemaLocation="../../Schema/OperacionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConsultarSoloOperacionRequestMessage">
    <part name="ConsultarSoloOperacionRequest" element="tns:ConsultarSoloOperacionRequest"/>
  </message>
  <message name="ConsultarSoloOperacionResponseMessage">
    <part name="ConsultarSoloOperacionResponse" element="tns:ConsultarSoloOperacionResponse"/>
  </message>
  <portType name="ConsultarSoloOperacionPT">
    <operation name="ConsultarSoloOperacion">
      <input message="tns:ConsultarSoloOperacionRequestMessage"/>
      <output message="tns:ConsultarSoloOperacionResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarSoloOperacionPTBnd" type="tns:ConsultarSoloOperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarSoloOperacion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/OperacionMO/ConsultarSoloOperacion"/>
      <input>
        <soap12:body use="literal" parts="ConsultarSoloOperacionRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ConsultarSoloOperacionResponse"/>
      </output>
    </operation>
  </binding>
</definitions>