<wsdl:definitions
     name="CrearMiembroReunion_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearMiembroReunion_DB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearMiembroReunion_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearMiembroReunion_DB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearMiembroReunion_DB_plt" >
    <plt:role name="CrearMiembroReunion_DB_role" >
      <plt:portType name="tns:CrearMiembroReunion_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearMiembroReunion_DB" schemaLocation="../XSD/CrearMiembroReunion_DB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TcaMiembroReunionCollection_msg">
        <wsdl:part name="TcaMiembroReunionCollection" element="top:TcaMiembroReunionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearMiembroReunion_DB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TcaMiembroReunionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
