<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarTreReglasDesembolso" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarTreReglasDesembolso"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarTreReglasDesembolso/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
                </xsd:schema>
                
  </types>
  <message name="requestConsultarReglasDesembolsoMessage">
    <part name="request" element="desMO:ConsultarReglasDesembolsoRequest"/>
  </message>
  <message name="responseConsultarReglasDesembolsoMessage">
    <part name="response" element="desMO:ConsultarReglasDesembolsoResponse"/>
  </message>
  <portType name="ConsultarReglasDesembolso_PT">
    <operation name="consultarReglasDesembolso">
      <input message="tns:requestConsultarReglasDesembolsoMessage"/>
      <output message="tns:responseConsultarReglasDesembolsoMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarTreReglasDesembolso_PTSOAP12Binding" type="tns:ConsultarReglasDesembolso_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarReglasDesembolso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarTreReglasDesembolso/consultarTreReglasDesembolso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>