<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarTransitoGrupoPaisSAD"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarTransitoGrupoPaisSAD"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarTransitoGrupoPaisSAD"
     xmlns:inp1="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="ConsultarTransitoGrupoPaisRequestMessage" element="inp1:ConsultarTransitoGrupoPaisRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="ConsultarTransitoGrupoPaisResponseMessage" element="inp1:ConsultarTransitoGrupoPaisResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTransitoGrupoPais_ptt">
        <wsdl:operation name="ConsultarTransitoGrupoPais">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsultarTransitoGrupoPais_bind" type="tns:ConsultarTransitoGrupoPais_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ConsultarTransitoGrupoPais">
            <soap12:operation style="document" soapAction="ConsultarTransitoGrupoPais" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarTransitoGrupoPaisSAD"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarTransitoGrupoPaisSAD"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
