<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http/www.bcie.org/CrearActualizarTransferenciaRecursosSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http/www.bcie.org/CrearActualizarTransferenciaRecursosSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
              xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http/www.bcie.org/CrearActualizarTransferenciaRecursosSAD/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestCrearActualizarTransferenciaRecursosMessage">
    <part name="request" element="desMO:CrearActualizarTransferenciaRecursosRequest"/>
  </message>
  <message name="responseCrearActualizarTransferenciaRecursosMessage">
    <part name="response" element="desMO:CrearActualizarTransferenciaRecursosResponse"/>
  </message>
  <portType name="CrearActualizarTransferenciaRecursosPT">
    <operation name="crearActualizarTransferenciaRecursos">
      <input message="tns:requestCrearActualizarTransferenciaRecursosMessage"/>
      <output message="tns:responseCrearActualizarTransferenciaRecursosMessage"/>
    </operation>
  </portType>
  <binding name="CrearActualizarTransferenciaRecursosPT12Bnd" type="tns:CrearActualizarTransferenciaRecursosPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearActualizarTransferenciaRecursos">
      <soap12:operation style="document"
                        soapAction="http/www.bcie.org/CrearActualizarTransferenciaRecursosSAD/crearActualizarTransferenciaRecursos"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>