<wsdl:definitions name="CrearAprobacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearAprobacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearAprobacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearAprobacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearAprobacion_plt">
    <plt:role name="CrearAprobacion_role">
      <plt:portType name="tns:CrearAprobacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearAprobacion" schemaLocation="../XSD/CrearAprobacion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="AprobacionCollection_msg">
        <wsdl:part name="AprobacionCollection" element="top:AprobacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearAprobacion_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:AprobacionCollection_msg"/>
            <wsdl:output message="tns:AprobacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>