<wsdl:definitions
     name="ConsultarEquipoTrabajoReunion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoReunion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoReunion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarEquipoTrabajoReunion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarEquipoTrabajoReunion_plt" >
    <plt:role name="ConsultarEquipoTrabajoReunion_role" >
      <plt:portType name="tns:ConsultarEquipoTrabajoReunion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarEquipoTrabajoReunion" schemaLocation="../XSD/ConsultarEquipoTrabajoReunion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarEquipoTrabajoReunionInput_msg">
        <wsdl:part name="ConsultarEquipoTrabajoReunionInput_msg" element="db:ConsultarEquipoTrabajoReunionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarEquipoTrabajoReunionOutputCollection_msg">
        <wsdl:part name="ConsultarEquipoTrabajoReunionOutputCollection" element="db:ConsultarEquipoTrabajoReunionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarEquipoTrabajoReunion_ptt">
        <wsdl:operation name="ConsultarEquipoTrabajoReunion">
            <wsdl:input message="tns:ConsultarEquipoTrabajoReunionInput_msg"/>
            <wsdl:output message="tns:ConsultarEquipoTrabajoReunionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
