<wsdl:definitions name="QueryUpdateMDM" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryUpdateMDM" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryUpdateMDM" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryUpdateMDM" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryUpdateMDM_plt">
    <plt:role name="QueryUpdateMDM_role">
      <plt:portType name="tns:QueryUpdateMDM_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryUpdateMDM" schemaLocation="QueryUpdateMDM_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryUpdateMDMSelect_inputParameters">
        <wsdl:part name="QueryUpdateMDMSelect_inputParameters" element="top:QueryUpdateMDMSelect_p_IDRMSInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmWarehouseCollection_msg">
        <wsdl:part name="MdmWarehouseCollection" element="top:MdmWarehouseCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryUpdateMDM_ptt">
        <wsdl:operation name="QueryUpdateMDMSelect">
            <wsdl:input message="tns:QueryUpdateMDMSelect_inputParameters"/>
            <wsdl:output message="tns:MdmWarehouseCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>