<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryUpdateMDM" name="QueryUpdateMDM-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryUpdateMDM.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryUpdateMDM"/>
    <wsdl:binding name="QueryUpdateMDM_ptt-binding" type="quer:QueryUpdateMDM_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryUpdateMDM">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryUpdateMDMSelect">
            <soap:operation soapAction="QueryUpdateMDMSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>