<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryStoreMDM" name="QueryStoreMDM-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryStoreMDM.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryStoreMDM"/>
    <wsdl:binding name="QueryStoreMDM_ptt-binding" type="quer:QueryStoreMDM_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/QueryStoreMDM">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryStoreMDMSelect">
            <soap:operation soapAction="QueryStoreMDMSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>