<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/SyncStoreMDM" name="SyncStoreMDM-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SyncStoreMDM.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/SyncStoreMDM"/>
    <wsdl:binding name="SyncStoreMDM_ptt-binding" type="syn:SyncStoreMDM_ptt" xmlns:syn="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/SyncStoreMDM">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>