<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/UpdateStoreRMSMDM" name="UpdateStoreRMSMDM-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UpdateStoreRMSMDM.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/UpdateStoreRMSMDM"/>
    <wsdl:binding name="UpdateStoreRMSMDM_ptt-binding" type="upd:UpdateStoreRMSMDM_ptt" xmlns:upd="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/UpdateStoreRMSMDM">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="update">
            <soap:operation soapAction="update"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>