<wsdl:definitions name="UpdateStoreMDM" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/UpdateStoreMDM" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreApp/UpdateStoreMDM" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStoreMDM" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="UpdateStoreMDM_plt">
    <plt:role name="UpdateStoreMDM_role">
      <plt:portType name="tns:UpdateStoreMDM_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStoreMDM" schemaLocation="UpdateStoreMDM_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="MdmWarehouseCollection_msg">
        <wsdl:part name="MdmWarehouseCollection" element="top:MdmWarehouseCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateStoreMDM_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:MdmWarehouseCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>