<wsdl:definitions name="LinkGroupDiffProcess" targetNamespace="http://xmlns.oracle.com/RetailOperMK/LinkGroupDiffProcess/LinkGroupDiffProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/RetailOperMK/LinkGroupDiffProcess/LinkGroupDiffProcess" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/LinkGroupDiffEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
<abstractWSDL>http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/RetailOperMK/LinkGroupDiffProcess!1.0/WSDLs/LinkGroupDiffProcess.wsdl</abstractWSDL>
</wsdl:documentation>
  <plnk:partnerLinkType name="LinkGroupDiffProcess">
    <plnk:role name="LinkGroupDiffProcessProvider" portType="client:LinkGroupDiffProcess"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/LinkGroupDiffEntity" schemaLocation="../Schemas/LinkGroupDiffEntitySchema.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="LinkGroupDiffProcessRequestMessage">
    <wsdl:part name="payload" element="ns1:linkGroupDiffRequest"/>
  </wsdl:message>
  <wsdl:message name="LinkGroupDiffProcessResponseMessage">
    <wsdl:part name="payload" element="ns1:linkGroupDiffResponse"/>
  </wsdl:message>
  <wsdl:portType name="LinkGroupDiffProcess">
    <wsdl:operation name="process">
      <wsdl:input message="client:LinkGroupDiffProcessRequestMessage"/>
      <wsdl:output message="client:LinkGroupDiffProcessResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LinkGroupDiffProcessBinding" type="client:LinkGroupDiffProcess">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation style="document" soapAction="process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="linkgroupdiffprocess_client_ep">
    <wsdl:port name="LinkGroupDiffProcess_pt" binding="client:LinkGroupDiffProcessBinding">
      <soap:address location="http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/RetailOperMK/LinkGroupDiffProcess/linkgroupdiffprocess_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>