<wsdl:definitions name="PROCreateSizeGroupProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Items/PROCreateSizeGroupProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Items/PROCreateSizeGroupProcess/v1.0" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeGroupEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
<abstractWSDL>http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/RetailOperMK/PROCreateSizeGroupProcess!1.0/WSDLs/PROCreateSizeGroupProcess.wsdl</abstractWSDL>
</wsdl:documentation>
  <plnk:partnerLinkType name="PROCreateSizeGroupProcess">
    <plnk:role name="PROCreateSizeGroupProcessProvider" portType="client:PROCreateSizeGroupProcess"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeGroupEntity" schemaLocation="../Schemas/CreateSizeGroupEntitySchema.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="PROCreateSizeGroupProcessRequestMessage">
    <wsdl:part name="payload" element="ns1:createSizeGroupRequest"/>
  </wsdl:message>
  <wsdl:message name="PROCreateSizeGroupProcessResponseMessage">
    <wsdl:part name="payload" element="ns1:createSizeGroupResponse"/>
  </wsdl:message>
  <wsdl:portType name="PROCreateSizeGroupProcess">
    <wsdl:operation name="create">
      <wsdl:input message="client:PROCreateSizeGroupProcessRequestMessage"/>
      <wsdl:output message="client:PROCreateSizeGroupProcessResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PROCreateSizeGroupProcessBinding" type="client:PROCreateSizeGroupProcess">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="create">
      <soap:operation style="document" soapAction="create"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="procreatesizegroupprocess_client_ep">
    <wsdl:port name="PROCreateSizeGroupProcess_pt" binding="client:PROCreateSizeGroupProcessBinding">
      <soap:address location="http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/RetailOperMK/PROCreateSizeGroupProcess/procreatesizegroupprocess_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>