<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/CorreoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/CorreoMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EnviarCorreoElectronicoBPEL">
        <plnk:role name="EnviarCorreoElectronicoPT" portType="tns:EnviarCorreoElectronicoPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/Utilidades/EnviarCorreoElectronico/bpelEnviarCorreo" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/EnviarCorreoElectronico/V1/WSDL/BPEL/EnviarCorreoElectronicoSOR.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/Utilidades/EnviarCorreoElectronico/V1/Schema/CorreoElectronicoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
