<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/UploadInvoiceEdiAPP/InvoiceServiceFTP" name="InvoiceServiceFTP-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../InvoiceService/Resources/WSDLs/InvoiceServiceFTP.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/UploadInvoiceEdiAPP/InvoiceServiceFTP"/>
    <wsdl:binding name="Get_ptt-binding" type="inv:Get_ptt" xmlns:inv="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/UploadInvoiceEdiAPP/InvoiceServiceFTP">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Get">
            <soap:operation soapAction="Get"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>