<wsdl:definitions name="QueryOrdersRmsDbAdapterService" targetNamespace="http://www.agarcia.mx/ServiceBus/QueryOrdersRmsDbAdapterService" xmlns:tns="http://www.agarcia.mx/ServiceBus/QueryOrdersRmsDbAdapterService" xmlns:inp1="http://www.agarcia.mx/EnterpriseObjects/Allocation" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Allocation" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Allocation/AllocationEBM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="requestPart" element="inp1:QueryAllocationEBM"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="responsePart" element="inp1:QueryAllocationResponseEBM"/>
    </wsdl:message>
    <wsdl:portType name="QueryOrdersRmsDb_ptt">
        <wsdl:operation name="QueryOrdersRmsDb">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="QueryOrdersRmsDb_bind" type="tns:QueryOrdersRmsDb_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="QueryOrdersRmsDb">
            <soap12:operation style="document" soapAction="QueryOrdersRmsDb" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/QueryOrdersRmsDbAdapterService"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/QueryOrdersRmsDbAdapterService"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>