<wsdl:definitions name="ItemDataSvcBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSItemDataService/ItemDataSvc/ItemDataSvcBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RMSItemDataService/ItemDataSvc/ItemDataSvcBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ItemDataSvcBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ItemDataSvcBS_plt">
    <plt:role name="ItemDataSvcBS_role">
      <plt:portType name="tns:ItemDataSvcBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ItemDataSvcBS" schemaLocation="ItemDataSvcBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:ItemMasterPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="ItemMasterCollection_msg">
        <wsdl:part name="ItemMasterCollection" element="top:ItemMasterCollection"/>
    </wsdl:message>
    <wsdl:portType name="ItemDataSvcBS_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:ItemMasterCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>