<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConfiguracionProcesos"
     targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.bcie.org/EvaluacionService"
     xmlns:ns2="http://xmlns.bcie.com/EvaluacionService"
    >
    <plnk:partnerLinkType name="ConfiguracionEvaluacion">
        <plnk:role name="ConfigurarEvaluacionPT" portType="tns:ConfigurarEvaluacionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/ConfiguracionProcesosService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/WSDL/BPEL/ConfiguracionEvaluacionSOR.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.org/EvaluacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Evaluacion/V1/Wsdl/ADAPTER/ConsultarEvaluacionFenixSAD.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/EvaluacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Evaluacion/V1/Wsdl/Evaluacion.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/EvaluacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Evaluacion/V1/Wsdl/ADAPTER/DuplicarEvaluacionSAD.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/EvaluacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Evaluacion/V1/Wsdl/BPEL/CrearEvaluacionSOR.wsdl"/>
</wsdl:definitions>
