<wsdl:definitions name="ConsultarAprobacionById" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarAprobacionById" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarAprobacionById" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAprobacionById" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarAprobacionById_plt">
    <plt:role name="ConsultarAprobacionById_role">
      <plt:portType name="tns:ConsultarAprobacionById_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAprobacionById" schemaLocation="../XSD/ConsultarAprobacionById.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAprobacionByIdInput_msg">
        <wsdl:part name="ConsultarAprobacionByIdInput_msg" element="db:ConsultarAprobacionByIdInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAprobacionByIdOutputCollection_msg">
        <wsdl:part name="ConsultarAprobacionByIdOutputCollection" element="db:ConsultarAprobacionByIdOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAprobacionById_ptt">
        <wsdl:operation name="ConsultarAprobacionById">
            <wsdl:input message="tns:ConsultarAprobacionByIdInput_msg"/>
            <wsdl:output message="tns:ConsultarAprobacionByIdOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>