<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerCumplimientoCondiciones" name="ObtenerCumplimientoCondiciones-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ObtenerCumplimientoCondiciones.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerCumplimientoCondiciones"/>
    <wsdl:binding name="ObtenerCumplimientoCondiciones_ptt-binding" type="obt:ObtenerCumplimientoCondiciones_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerCumplimientoCondiciones">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerCumplimientoCondiciones">
            <soap:operation soapAction="ObtenerCumplimientoCondiciones"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>