<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConfiguracionProcesos"
     targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/ConsultarInformacionReglaById"
     xmlns:ns2="http://www.bcie.com/ConsultarRolesPorProceso"
     xmlns:ns3="http://xmlns.oracle.com/ClienteEsIFI/ClienteEsIFI_DecisionService"
     xmlns:ns4="http://www.bcie.org/ConsultarDesembolsosByIdSAD"
    >
    <plnk:partnerLinkType name="ConfiguracionDesembolso">
        <plnk:role name="ConfiguracionDesembolsoPT" portType="tns:ConfiguracionDesembolsoPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/ConfiguracionProcesosService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/WSDL/BPEL/ConfiguracionDesembolsoSOR.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/ConsultarInformacionReglaById" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ConsultarInformacionReglaByIdSAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.com/ConsultarRolesPorProceso" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConsultarRolesPorProceso/V1/Wsdl/ConsultarRolesPorProceso.wsdl"/>
    <wsdl:import namespace="http://xmlns.oracle.com/ClienteEsIFI/ClienteEsIFI_DecisionService" location="oramds:/apps/Resources/ComponentesComunes/BusinessRules/ValidarClienteEsIFI/V1/Wsdl/ClienteEsIFI_DecisionService.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/ConsultarDesembolsosByIdSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ConsultarDesembolsosByIdSAD.wsdl"/>
</wsdl:definitions>
