<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/CommonTranslationAPP/ExecFuncIDRMS" name="ExecFuncIDRMS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ExecFuncIDRMS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/CommonTranslationAPP/ExecFuncIDRMS"/>
    <wsdl:binding name="ExecFuncIDRMS_ptt-binding" type="exec:ExecFuncIDRMS_ptt" xmlns:exec="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/CommonTranslationAPP/ExecFuncIDRMS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ExecFuncIDRMS">
            <soap:operation soapAction="ExecFuncIDRMS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>