<wsdl:definitions name="GetLocationSQL" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/CommonTranslationAPP/GetLocationSQL" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/CommonTranslationAPP/GetLocationSQL" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetLocationSQL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="GetLocationSQL_plt">
    <plt:role name="GetLocationSQL_role">
      <plt:portType name="tns:GetLocationSQL_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="GetLocationSQL_plt">
    <plt:role name="GetLocationSQL_role">
      <plt:portType name="tns:GetLocationSQL_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetLocationSQL" schemaLocation="GetLocationSQL.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetLocationSQL" schemaLocation="GetLocationSQL.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="GetLocationSQLInput_msg">
        <wsdl:part name="GetLocationSQLInput_msg" element="db:GetLocationSQLInput"/>
    </wsdl:message>
    <wsdl:message name="GetLocationSQLOutputCollection_msg">
        <wsdl:part name="GetLocationSQLOutputCollection" element="db:GetLocationSQLOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetLocationSQL_ptt">
        <wsdl:operation name="GetLocationSQL">
            <wsdl:input message="tns:GetLocationSQLInput_msg"/>
            <wsdl:output message="tns:GetLocationSQLOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>