<wsdl:definitions name="HierarchySQLDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/HierarchySQLDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/HierarchySQLDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/HierarchySQLDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="HierarchySQLDB_plt">
    <plt:role name="HierarchySQLDB_role">
      <plt:portType name="tns:HierarchySQLDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="HierarchySQLDB_plt">
    <plt:role name="HierarchySQLDB_role">
      <plt:portType name="tns:HierarchySQLDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="HierarchySQLDB_plt">
    <plt:role name="HierarchySQLDB_role">
      <plt:portType name="tns:HierarchySQLDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HierarchySQLDB" schemaLocation="HierarchySQLDB.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HierarchySQLDB" schemaLocation="HierarchySQLDB.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HierarchySQLDB" schemaLocation="HierarchySQLDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="HierarchySQLDBInput_msg">
        <wsdl:part name="HierarchySQLDBInput_msg" element="db:HierarchySQLDBInput"/>
    </wsdl:message>
    <wsdl:message name="HierarchySQLDBOutputCollection_msg">
        <wsdl:part name="HierarchySQLDBOutputCollection" element="db:HierarchySQLDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="HierarchySQLDB_ptt">
        <wsdl:operation name="HierarchySQLDB">
            <wsdl:input message="tns:HierarchySQLDBInput_msg"/>
            <wsdl:output message="tns:HierarchySQLDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>