<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/HierarchySQLDB" name="HierarchySQLDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="HierarchySQLDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/HierarchySQLDB"/>
    <wsdl:binding name="HierarchySQLDB_ptt-binding" type="hier:HierarchySQLDB_ptt" xmlns:hier="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/HierarchySQLDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="HierarchySQLDB">
            <soap:operation soapAction="HierarchySQLDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>