<wsdl:definitions name="RMSCreateSupplierMessage" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateSupplierMessage" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateSupplierMessage" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="http://www.oracle.com/retail/integration/base/bo/VendorDesc/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="RMSCreateSupplierMessage_plt">
    <plt:role name="RMSCreateSupplierMessage_role">
      <plt:portType name="tns:RMSCreateSupplierMessage_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://www.oracle.com/retail/integration/base/bo/VendorDesc/v1" schemaLocation="../../../../RMS/JMSSupplierConnectivity/Schema/VendorDesc.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="RMSCreateSupplierMessage_msg">
        <wsdl:part name="body" element="imp1:VendorDesc"/>
    </wsdl:message>
    <wsdl:portType name="RMSCreateSupplierMessage_ptt">
        <wsdl:operation name="RMSCreateSupplierMessage">
            <wsdl:input message="tns:RMSCreateSupplierMessage_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>