<wsdl:definitions name="SyncSupplierSAALMAABCSimplPipeline" targetNamespace="http://www.agarcia.mx/ServiceBus/SupplierParty" xmlns:tns="http://www.agarcia.mx/ServiceBus/SupplierParty" xmlns:inp1="http://www.agarcia.mx/EnterpriseObjects/SupplierParty" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/SupplierParty" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/SupplierParty/SupplierPartyEBM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="ReqMsg" element="inp1:SyncSupplierPartyEBM"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="ResMsg" element="inp1:SyncSupplierPartyResponseEBM"/>
    </wsdl:message>
    <wsdl:portType name="syncSupplier_ptt">
        <wsdl:operation name="sync">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:syncSupplier_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sync">
            <soap:operation style="document" soapAction="sync"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/SupplierParty"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/SupplierParty"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>