<wsdl:definitions name="ConsultarMomentoCobro_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarMomentoCobro_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarMomentoCobro_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarMomentoCobro_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarMomentoCobro_DB_plt">
    <plt:role name="ConsultarMomentoCobro_DB_role">
      <plt:portType name="tns:ConsultarMomentoCobro_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarMomentoCobro_DB" schemaLocation="../XSD/ConsultarMomentoCobro_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarMomentoCobro_DBInput_msg">
        <wsdl:part name="ConsultarMomentoCobro_DBInput_msg" element="db:ConsultarMomentoCobro_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarMomentoCobro_DBOutputCollection_msg">
        <wsdl:part name="ConsultarMomentoCobro_DBOutputCollection" element="db:ConsultarMomentoCobro_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarMomentoCobro_DB_ptt">
        <wsdl:operation name="ConsultarMomentoCobro_DB">
            <wsdl:input message="tns:ConsultarMomentoCobro_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarMomentoCobro_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>