<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/CreateDownloadOrderCarvajalAdapterService/ftpCreateDownloadOrderCarvajal" name="ftpCreateDownloadOrderCarvajal-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../CreateDownloadOrderCarvajalAdapterService/Resources/ftpCreateDownloadOrderCarvajal.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/CreateDownloadOrderCarvajalAdapterService/ftpCreateDownloadOrderCarvajal"/>
    <wsdl:binding name="Create_ptt-binding" type="ftp:Create_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/CreateDownloadOrderCarvajalAdapterService/ftpCreateDownloadOrderCarvajal">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Create">
            <soap:operation soapAction="Create"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>