<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/DownloadOrderService/ftpDownloarOrder" name="ftpDownloarOrder-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../DownloadOrderService/Resources/ftpDownloarOrder.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/DownloadOrderService/ftpDownloarOrder"/>
    <wsdl:binding name="Prcoess_ptt-binding" type="ftp:Prcoess_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/DownloadOrder/DownloadOrderService/ftpDownloarOrder">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Prcoess">
            <soap:operation soapAction="Prcoess"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>