<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DownloadOrderServiceAPP/DownloadOrderAPP/Orders_VW" name="Orders_VW-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Orders_VW.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DownloadOrderServiceAPP/DownloadOrderAPP/Orders_VW"/>
    <wsdl:binding name="Orders_VW_ptt-binding" type="ord:Orders_VW_ptt" xmlns:ord="http://xmlns.oracle.com/pcbpel/adapter/db/DownloadOrderServiceAPP/DownloadOrderAPP/Orders_VW">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Orders_VWSelect">
            <soap:operation soapAction="Orders_VWSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>