<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DownloadOrderServiceAPP/DownloadOrderAPP/xx_soa_orders_vw" name="xx_soa_orders_vw-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="xx_soa_orders_vw.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DownloadOrderServiceAPP/DownloadOrderAPP/xx_soa_orders_vw"/>
    <wsdl:binding name="xx_soa_orders_vw_ptt-binding" type="xx:xx_soa_orders_vw_ptt" xmlns:xx="http://xmlns.oracle.com/pcbpel/adapter/db/DownloadOrderServiceAPP/DownloadOrderAPP/xx_soa_orders_vw">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="xx_soa_orders_vwSelect">
            <soap:operation soapAction="xx_soa_orders_vwSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>