<wsdl:definitions name="GetHierarchyDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/GetHierarchyDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/GetHierarchyDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetHierarchyDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="GetHierarchyDB_plt">
    <plt:role name="GetHierarchyDB_role">
      <plt:portType name="tns:GetHierarchyDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetHierarchyDB" schemaLocation="../../../Resources/GetHierarchyDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="GetHierarchyDBSelect_inputParameters">
        <wsdl:part name="GetHierarchyDBSelect_inputParameters" element="top:GetHierarchyDBSelect_IdDeptoRMSInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmMerchandhierarTranslationsCollection_msg">
        <wsdl:part name="MdmMerchandhierarTranslationsCollection" element="top:MdmMerchandhierarTranslationsCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetHierarchyDB_ptt">
        <wsdl:operation name="GetHierarchyDBSelect">
            <wsdl:input message="tns:GetHierarchyDBSelect_inputParameters"/>
            <wsdl:output message="tns:MdmMerchandhierarTranslationsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>