<wsdl:definitions name="RMSSelectSupplierID" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSSearchSupplier/RMSSearchSupplier/RMSSelectSupplierID" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RMSSearchSupplier/RMSSearchSupplier/RMSSelectSupplierID" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/RMSSelectSupplierID" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="RMSSelectSupplierID_plt">
    <plt:role name="RMSSelectSupplierID_role">
      <plt:portType name="tns:RMSSelectSupplierID_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/RMSSelectSupplierID" schemaLocation="RMSSelectSupplierID_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="RMSSelectSupplierIDSelect_inputParameters">
        <wsdl:part name="RMSSelectSupplierIDSelect_inputParameters" element="top:RMSSelectSupplierIDSelect_IdSuppInputParameters"/>
    </wsdl:message>
    <wsdl:message name="SupsCollection_msg">
        <wsdl:part name="SupsCollection" element="top:SupsCollection"/>
    </wsdl:message>
    <wsdl:portType name="RMSSelectSupplierID_ptt">
        <wsdl:operation name="RMSSelectSupplierIDSelect">
            <wsdl:input message="tns:RMSSelectSupplierIDSelect_inputParameters"/>
            <wsdl:output message="tns:SupsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RMSSelectSupplierIDBinding" type="tns:RMSSelectSupplierID_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="RMSSelectSupplierIDSelect">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/pcbpel/adapter/db/RMSSearchSupplier/RMSSearchSupplier/RMSSelectSupplierID/RMSSelectSupplierIDSelect"/>
            <wsdl:input>
                <soap:body use="literal" parts="RMSSelectSupplierIDSelect_inputParameters"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="SupsCollection"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>