<wsdl:definitions
     name="ConsultarContrato"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarContrato"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarContrato"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContrato"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarContrato_plt" >
    <plt:role name="ConsultarContrato_role" >
      <plt:portType name="tns:ConsultarContrato_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContrato" schemaLocation="../XSD/ConsultarContrato.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContratoInput_msg">
        <wsdl:part name="ConsultarContratoInput_msg" element="db:ConsultarContratoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarContratoOutputCollection_msg">
        <wsdl:part name="ConsultarContratoOutputCollection" element="db:ConsultarContratoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContrato_ptt">
        <wsdl:operation name="ConsultarContrato">
            <wsdl:input message="tns:ConsultarContratoInput_msg"/>
            <wsdl:output message="tns:ConsultarContratoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
