<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarTransferenciasBancariasByIdSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarTransferenciasBancariasByIdSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarTransferenciasBancariasByIdSAD/types"
                elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarTransferenciasBancariasByIdMessage">
    <part name="request" element="desMO:ConsultarTransferenciasBancariasByIdRequest"/>
  </message>
  <message name="responseConsultarTransferenciasBancariasByIdMessage">
    <part name="response" element="desMO:ConsultarTransferenciasBancariasByIdResponse"/>
  </message>
  <portType name="ConsultarTransferenciasBancariasById_PT">
    <operation name="consultarTransferenciasBancariasById">
      <input message="tns:requestConsultarTransferenciasBancariasByIdMessage"/>
      <output message="tns:responseConsultarTransferenciasBancariasByIdMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarTransferenciasBancariasById_PTSOAP12Binding"
           type="tns:ConsultarTransferenciasBancariasById_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarTransferenciasBancariasById">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarTransferenciasBancariasByIdSAD/consultarTransferenciasBancariasById"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>