<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/CrearCliente" name="CrearCliente_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CrearCliente.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/CrearCliente"/>
    <wsdl:binding name="CrearCliente_ptt-binding" type="cre:CrearCliente_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/CrearCliente">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>