<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PriceChangeSaveProcess" targetNamespace="http://xmlns.oracle.com/PriceChangeProcessBackup/PriceChangeSave/PriceChangeSaveProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:AGSH="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" xmlns:client="http://xmlns.oracle.com/PriceChangeProcessBackup/PriceChangeSave/PriceChangeSaveProcess" xmlns:ns1="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeSaveProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://mx.agarcia.ea/Applications/Governance">
   <plnk:partnerLinkType name="PriceChangeSaveProcess">
      <plnk:role name="PriceChangeSaveProcessProvider" portType="client:PriceChangeSaveProcess"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Applications/Governance" location="http://172.16.19.26:7004/Applications/Governance/PS/GovernanceAPIPXY/v1.0?WSDL"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/PriceChangeProcessBackup/PriceChangeSave/PriceChangeSaveProcess" schemaLocation="../Schemas/PriceChangeSaveProcess.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" schemaLocation="../Schemas/Commons/AGStandardHeaderSchema.xsd"/>
         <import namespace="http://mx.agarcia.ea/RetailOperations/SellService/PriceChangeTaskSvc/PriceChangeProcess/BS/PriceChangeSaveProcess" schemaLocation="../Schemas/PriceChangeSaveSchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="PriceChangeSaveProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:SavePriceChangeRequest"/>
   </wsdl:message>
   <wsdl:message name="PriceChangeSaveProcessResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:message name="StandardHeaderMessage">
      <wsdl:part name="headerMessage" element="AGSH:headerMessage"/>
   </wsdl:message>
   <wsdl:portType name="PriceChangeSaveProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:PriceChangeSaveProcessRequestMessage"/>
         <wsdl:output message="client:PriceChangeSaveProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="PriceChangeSaveProcessBinding" type="client:PriceChangeSaveProcess">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="process">
         <soap:operation style="document" soapAction="http://xmlns.oracle.com/PriceChangeProcessBackup/PriceChangeSave/PriceChangeSaveProcess/process"/>
         <wsdl:input>
            <soap:body use="literal" parts="payload"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" parts="payload"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
