<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearDesembolsoLoanFLEXCUBESAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/CrearDesembolsoLoanFLEXCUBESAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearDesembolsoLoanFLEXCUBESAD/types"
                elementFormDefault="qualified">
  <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
  </xsd:schema>
                
  </types>
  <message name="requestCrearDesembolsoLoanFLEXCUBEMessage">
    <part name="request" element="desMO:CrearDesembolsoLoanFLEXCUBERequest"/>
  </message>
  <message name="responseCrearDesembolsoLoanFLEXCUBEMessage">
    <part name="response" element="desMO:CrearDesembolsoLoanFLEXCUBEResponse"/>
  </message>
  <portType name="CrearDesembolsoLoanFLEXCUBE_PT">
    <operation name="crearDesembolsoLoanFLEXCUBE">
      <input message="tns:requestCrearDesembolsoLoanFLEXCUBEMessage"/>
      <output message="tns:responseCrearDesembolsoLoanFLEXCUBEMessage"/>
    </operation>
  </portType>
  <binding name="CrearDesembolsoLoanFLEXCUBE_PTSOAP12Binding" type="tns:CrearDesembolsoLoanFLEXCUBE_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearDesembolsoLoanFLEXCUBE">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearDesembolsoLoanFLEXCUBESAD/crearDesembolsoLoanFLEXCUBE"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>