<wsdl:definitions name="JMSCreateSupplierProducer" targetNamespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/JMSCreateSupplierProducer" xmlns:tns="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/JMSCreateSupplierProducer" xmlns:inp1="http://www.oracle.com/retail/integration/base/bo/VendorDesc/v1" xmlns:inp2="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <plnk:partnerLinkType name="JMSCreateSupplierProducer">
        <plnk:role name="JMSCreateSupplierProducerProvider" portType="tns:JMSCreateSupplierProducerPort"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/VendorDesc/v1" schemaLocation="../Schema/VendorDesc.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" schemaLocation="../../../../../Capabilities/Foundation/Schemas/Commons/AGStandardMessageSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="JMSCreateSupplierProducerInput" element="inp1:VendorDesc"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="JMSCreateSupplierProducerOutput" element="inp2:messageResponse"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="JMSCreateSupplierProducerFault" element="inp2:messageError"/>
    </wsdl:message>
    <wsdl:portType name="JMSCreateSupplierProducerPort">
        <wsdl:operation name="JMSCreateSupplierProducerOperation">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="JMSCreateSupplierProducerOperationfault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="JMSCreateSupplierProducerBinding" type="tns:JMSCreateSupplierProducerPort">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="JMSCreateSupplierProducerOperation">
            <soap:operation style="document" soapAction="JMSCreateSupplierProducerOperation"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/JMSCreateSupplierProducer"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/JMSCreateSupplierProducer"/>
            </wsdl:output>
            <wsdl:fault name="JMSCreateSupplierProducerOperationfault">
                <soap:fault name="JMSCreateSupplierProducerOperationfault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>