<wsdl:definitions name="CrearOperacionBD" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/CreaOperacion/CrearOperacionBD" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/CreaOperacion/CrearOperacionBD" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearOperacionBD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearOperacionBD_plt">
    <plt:role name="CrearOperacionBD_role">
      <plt:portType name="tns:CrearOperacionBD_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearOperacionBD" schemaLocation="../XSD/CrearOperacionBD_table.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="OperacionCollection_msg">
    <wsdl:part name="OperacionCollection" element="top:OperacionCollection"/>
  </wsdl:message>
  <wsdl:portType name="CrearOperacionBD_ptt">
    <wsdl:operation name="insert">
      <wsdl:input message="tns:OperacionCollection_msg"/>
      <wsdl:output message="tns:OperacionCollection_msg"/>
    </wsdl:operation>
    <wsdl:operation name="merge">
      <wsdl:input message="tns:OperacionCollection_msg"/>
      <wsdl:output message="tns:OperacionCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>