<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarReactivarOperacion_DB" name="ActualizarReactivarOperacion_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ActualizarReactivarOperacion_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarReactivarOperacion_DB"/>
    <wsdl:binding name="ActualizarReactivarOperacion_DB_ptt-binding" type="act:ActualizarReactivarOperacion_DB_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarReactivarOperacion_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ActualizarReactivarOperacion_DB">
            <soap:operation soapAction="ActualizarReactivarOperacion_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>