<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Cuestionario/ObtenerCuestionario" name="ObtenerCuestionario_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ObtenerCuestionario.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Cuestionario/ObtenerCuestionario"/>
    <wsdl:binding name="ObtenerCuestionario_ptt-binding" type="obt:ObtenerCuestionario_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/Cuestionario/ObtenerCuestionario">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerCuestionario">
            <soap:operation soapAction="ObtenerCuestionario"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>