<wsdl:definitions
     name="ConsultarContratoByIdDesembolso"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarContratoByIdDesembolso"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarContratoByIdDesembolso"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContratoByIdDesembolso"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarContratoByIdDesembolsos_plt" >
    <plt:role name="ConsultarContratoByIdDesembolso_role" >
      <plt:portType name="tns:ConsultarContratoByIdDesembolso_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContratoByIdDesembolso" schemaLocation="../XSD/ConsultarContratoByIdDesembolso.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContratoByIdDesembolsoInput_msg">
        <wsdl:part name="ConsultarContratoByIdDesembolsoInput_msg" element="db:ConsultarContratoByIdDesembolsoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarContratoByIdDesembolsoOutputCollection_msg">
        <wsdl:part name="ConsultarContratoByIdDesembolsoOutputCollection" element="db:ConsultarContratoByIdDesembolsoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContratoByIdDesembolso_ptt">
        <wsdl:operation name="ConsultarContratoByIdDesembolso">
            <wsdl:input message="tns:ConsultarContratoByIdDesembolsoInput_msg"/>
            <wsdl:output message="tns:ConsultarContratoByIdDesembolsoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
