<wsdl:definitions name="ActualizarEstadoLeccion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoLeccion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoLeccion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarEstadoLeccion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarEstadoLeccion_plt">
    <plt:role name="ActualizarEstadoLeccion_role">
      <plt:portType name="tns:ActualizarEstadoLeccion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarEstadoLeccion" schemaLocation="../XSD/ActualizarEstadoLeccion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="LeccionCollection_msg">
        <wsdl:part name="LeccionCollection" element="top:LeccionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarEstadoLeccion_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:LeccionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>