<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/ComisionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:comMO="http://www.bcie.org/ComisionMO"
                  xmlns:tns="http://xmlns.bcie.com/ComisionService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ComisionMO"
                  schemaLocation="../../../../Comision/V1/Schema/ComisionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
  <wsdl:message name="requestCrearComisionFLEXCUBEMessage">
    <wsdl:part name="request" element="comMO:CrearComisionFLEXCUBERequest"/>
  </wsdl:message>
  <wsdl:message name="responseCrearComisionFLEXCUBEMessage">
    <wsdl:part name="response" element="comMO:CrearComisionFLEXCUBEResponse"/>
  </wsdl:message>
  <wsdl:portType name="CrearComisionFLEXCUBEPT">
    <!-- Create -->
    <wsdl:operation name="CrearComision">
      <wsdl:input message="tns:requestCrearComisionFLEXCUBEMessage"/>
      <wsdl:output message="tns:responseCrearComisionFLEXCUBEMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CrearComisionFLEXCUBE12Bnd" type="tns:CrearComisionFLEXCUBEPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CrearComision">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ComisionService/CrearComision"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CrearComisionFLEXCUBE">
    <wsdl:port name="CrearComisionFLEXCUBE12Bnd" binding="tns:CrearComisionFLEXCUBE12Bnd">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>






