<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.banesco.com/eopt/EmpPartyInq_V1.0" xmlns:ns0="http://xmlns.banesco.com/eopt/ObtenerUsuarioAD" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://xmlns.banesco.com/service/ADSvc" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../../../../Commons/backends/AD/resources/wsdl/ADSvc_V1.0.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ObtenerUsuarioADRs" namespace="http://xmlns.banesco.com/eopt/ObtenerUsuarioAD"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Party/EmpPartyInq/EmpPartyInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="EmpPartyInqRs" namespace="http://xmlns.banesco.com/eopt/EmpPartyInq_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU NOV 23 11:08:14 COT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:EmpPartyInqRs>
         <xsl:choose>
            <xsl:when test="string-length (/ns0:ObtenerUsuarioADRs/ns0:sAMAccountName ) > 0">
               <tns:Status>
                  <eoStatus:StatusCode>M0000</eoStatus:StatusCode>
                  <eoStatus:StatusDesc>OK</eoStatus:StatusDesc>
               </tns:Status>
            </xsl:when>
            <xsl:otherwise>
               <tns:Status>
                  <eoStatus:StatusCode>M0002</eoStatus:StatusCode>
                  <eoStatus:StatusDesc>SIN DATOS ASOCIADOS A LA OPERACÍON</eoStatus:StatusDesc>
               </tns:Status>
            </xsl:otherwise>
         </xsl:choose>
         <xsl:if test="string-length (/ns0:ObtenerUsuarioADRs/ns0:sAMAccountName ) > 0">
            <tns:Party>
               <eoPar:PersonPartyInfo>
                  <eoPar:PersonData>
                     <eoPar:Contact>
                        <ns3:Locator>
                           <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:mail/text() != &quot;&quot;">
                              <ns3:Email>
                                 <ns3:Value>
                                    <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:mail"/>
                                 </ns3:Value>
                              </ns3:Email>
                           </xsl:if>
                           <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:wWWHomePage/text() != &quot;&quot;">
                              <ns3:ResourceLocator>
                                 <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:wWWHomePage"/>
                              </ns3:ResourceLocator>
                           </xsl:if>
                           <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:streetAddress/text() != &quot;&quot; and /ns0:ObtenerUsuarioADRs/ns0:postOfficeBox/text() != &quot;&quot; and /ns0:ObtenerUsuarioADRs/ns0:postalCode/text() != &quot;&quot;">
                              <ns3:PostAddr>
                                 <xsl:if test='/ns0:ObtenerUsuarioADRs/ns0:streetAddress/text() != ""'>
                                    <ns3:Addr1>
                                       <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:streetAddress"/>
                                    </ns3:Addr1>
                                 </xsl:if>
                                 <xsl:if test='/ns0:ObtenerUsuarioADRs/ns0:postOfficeBox/text() != ""'>
                                    <ns3:Addr4>
                                       <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:postOfficeBox"/>
                                    </ns3:Addr4>
                                 </xsl:if>
                                 <xsl:if test='/ns0:ObtenerUsuarioADRs/ns0:postalCode/text() != ""'>
                                    <ns3:PostalCode>
                                       <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:postalCode"/>
                                    </ns3:PostalCode>
                                 </xsl:if>
                              </ns3:PostAddr>
                           </xsl:if>
                           <xsl:if test="string-length (/ns0:ObtenerUsuarioADRs/ns0:homePhone ) > 0">
                              <ns3:Phone>
                                 <ns3:PhoneNum>
                                    <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:homePhone"/>
                                 </ns3:PhoneNum>
                                 <ns3:PhoneType>LandLine</ns3:PhoneType>
                              </ns3:Phone>
                           </xsl:if>
                           <xsl:if test="string-length (/ns0:ObtenerUsuarioADRs/ns0:mobile ) > 0">
                              <ns3:Phone>
                                 <ns3:PhoneNum>
                                    <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:homePhone"/>
                                 </ns3:PhoneNum>
                                 <ns3:PhoneType>Mobile</ns3:PhoneType>
                              </ns3:Phone>
                           </xsl:if>
                           <xsl:if test="string-length (/ns0:ObtenerUsuarioADRs/ns0:telephoneNumber ) > 0">
                              <ns3:Phone>
                                 <ns3:PhoneNum>
                                    <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:homePhone"/>
                                 </ns3:PhoneNum>
                                 <ns3:PhoneType>LandLine</ns3:PhoneType>
                              </ns3:Phone>
                           </xsl:if>
                        </ns3:Locator>
                     </eoPar:Contact>
                     <eoPar:PersonName>
                        <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:givenName/text() != &quot;&quot;">
                           <eoPar:FirstName>
                              <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:givenName"/>
                           </eoPar:FirstName>
                        </xsl:if>
                        <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:displayName/text() != &quot;&quot;">
                           <eoPar:FullName>
                              <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:displayName"/>
                           </eoPar:FullName>
                        </xsl:if>
                        <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:sn/text() != &quot;&quot;">
                           <eoPar:LastName>
                              <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:sn"/>
                           </eoPar:LastName>
                        </xsl:if>
                     </eoPar:PersonName>
                  </eoPar:PersonData>
                  <eoPar:Employment>
                     <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:title/text() != &quot;&quot;">
                        <eoPar:JobTitle>
                           <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:title"/>
                        </eoPar:JobTitle>
                     </xsl:if>
                  </eoPar:Employment>
                  <eoPar:EmployeeData>
                     <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:department/text() != &quot;&quot;">
                        <eoPar:Department>
                           <ns3:Value>
                              <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:department"/>
                           </ns3:Value>
                        </eoPar:Department>
                     </xsl:if>
                     <eoPar:FIData>
                        <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:physicalDeliveryOfficeName/text() != &quot;&quot;">
                           <ns2:BranchName>
                              <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:physicalDeliveryOfficeName"/>
                           </ns2:BranchName>
                        </xsl:if>
                        <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:company/text() != &quot;&quot;">
                           <ns2:Agency>
                              <xsl:if test='/ns0:ObtenerUsuarioADRs/ns0:company/text() != ""'>
                                 <ns2:AgencyIdent>
                                    <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:company"/>
                                 </ns2:AgencyIdent>
                              </xsl:if>
                              <xsl:if test='/ns0:ObtenerUsuarioADRs/ns0:company/text() != ""'>
                                 <ns2:AgencyName>
                                    <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:company"/>
                                 </ns2:AgencyName>
                              </xsl:if>
                           </ns2:Agency>
                        </xsl:if>
                     </eoPar:FIData>
                     <xsl:if test="/ns0:ObtenerUsuarioADRs/ns0:manager/text() != &quot;&quot;">
                        <eoPar:SupervisorId>
                           <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:manager"/>
                        </eoPar:SupervisorId>
                     </xsl:if>
                  </eoPar:EmployeeData>
               </eoPar:PersonPartyInfo>
               <eoPar:PartyKey>
                  <eoPar:PartyId>
                     <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:userPrincipalName"/>
                  </eoPar:PartyId>
                  <eoPar:LoginIdent>
                     <eoPar:LoginName>
                        <xsl:value-of select="/ns0:ObtenerUsuarioADRs/ns0:sAMAccountName"/>
                     </eoPar:LoginName>
                  </eoPar:LoginIdent>
               </eoPar:PartyKey>
            </tns:Party>
         </xsl:if>
      </tns:EmpPartyInqRs>
   </xsl:template>
</xsl:stylesheet>
