<wsdl:definitions name="ActualizarStatusSolicitudAprobacionByOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarStatusSolicitudAprobacionByOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarStatusSolicitudAprobacionByOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarStatusSolicitudAprobacionByOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarStatusSolicitudAprobacionByOperacion_DB_plt">
    <plt:role name="ActualizarStatusSolicitudAprobacionByOperacion_DB_role">
      <plt:portType name="tns:ActualizarStatusSolicitudAprobacionByOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarStatusSolicitudAprobacionByOperacion_DB" schemaLocation="../XSD/ActualizarStatusSolicitudAprobacionByOperacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarStatusSolicitudAprobacionByOperacion_DBInput_msg">
        <wsdl:part name="ActualizarStatusSolicitudAprobacionByOperacion_DBInput_msg" element="db:ActualizarStatusSolicitudAprobacionByOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarStatusSolicitudAprobacionByOperacion_DB_ptt">
        <wsdl:operation name="ActualizarStatusSolicitudAprobacionByOperacion_DB">
            <wsdl:input message="tns:ActualizarStatusSolicitudAprobacionByOperacion_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>