<wsdl:definitions name="ConsultarVotacion_BD"
                  targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarVotacion_BD"
                  xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarVotacion_BD"
                  xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                  xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarVotacion_BD"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarVotacion_BD_plt">
    <plt:role name="ConsultarVotacion_BD_role">
      <plt:portType name="tns:ConsultarVotacion_BD_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarVotacion_BD"
              schemaLocation="../XSD/ConsultarAcumuladoVotacion_BD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="ConsultarVotacion_BDInput_msg">
    <wsdl:part name="ConsultarVotacion_BDInput_msg" element="db:ConsultarVotacion_BDInput"/>
  </wsdl:message>
  <wsdl:message name="ConsultarVotacion_BDOutputCollection_msg">
    <wsdl:part name="ConsultarVotacion_BDOutputCollection" element="db:ConsultarVotacion_BDOutputCollection"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarVotacion_BD_ptt">
    <wsdl:operation name="ConsultarVotacion_BD">
      <wsdl:input message="tns:ConsultarVotacion_BDInput_msg"/>
      <wsdl:output message="tns:ConsultarVotacion_BDOutputCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>