<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraProducto/ConsultaProductoService" name="ConsultarProducto_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarProducto.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraProducto/ConsultaProductoService"/>
    <wsdl:binding name="ConsultaProductoService_ptt-binding" type="con:ConsultaProductoService_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraProducto/ConsultaProductoService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultaProductoServiceSelect">
            <soap:operation soapAction="ConsultaProductoServiceSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>