<?binding.jca ConsultaProductoService_db.jca?><wsdl:definitions name="ConsultaProductoService" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraProducto/ConsultaProductoService" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/AdministraProducto/ConsultaProductoService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultaProductoService">
    <plt:partnerLinkType name="ConsultaProductoService_plt">
        <plt:role name="ConsultaProductoService_role">
            <plt:portType name="tns:ConsultaProductoService_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultaProductoService" schemaLocation="../XSD/ConsultarProducto_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaProductoServiceSelect_inputParameters">
        <wsdl:part name="ConsultaProductoServiceSelect_inputParameters" element="top:ConsultaProductoServiceSelect_idProductoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CatProductoCollection_msg">
        <wsdl:part name="CatProductoCollection" element="top:CatProductoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaProductoService_ptt">
        <wsdl:operation name="ConsultaProductoServiceSelect">
            <wsdl:input message="tns:ConsultaProductoServiceSelect_inputParameters"/>
            <wsdl:output message="tns:CatProductoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>