-- CREATE OR REPLACE TRIGGER FENIX.TCA_TIPO_CUESTIONARIO_TGR 
        -- BEFORE INSERT ON FENIX.TCA_TIPO_CUESTIONARIO
        -- FOR EACH ROW

        -- BEGIN
            -- SELECT FENIX.TCA_TIPO_CUESTIONARIO_SEQ.NEXTVAL
            -- INTO   :NEW.ID
            -- FROM   dual;
    -- END;