<definitions targetNamespace="http://www.bcie.org/Flexcube14/PrestamoService" 
xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/Flexcube14/PrestamoService" 
xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:preMO="http://www.bcie.org/FLEXCUBE14/PrestamoMO">
    <types>
        <xsd:schema targetNamespace="http://www.bcie.org/Flexcube14/Prestamo/types" elementFormDefault="qualified">
            <xsd:import namespace="http://www.bcie.org/FLEXCUBE14/PrestamoMO" schemaLocation="../Schema/PrestamoMO.xsd"/>
        </xsd:schema>
    </types>
    <message name="requestCrearContratoOLMessage">
        <part name="requestCrearContratoOL" element="preMO:CreaContratoOLRequest"/>
    </message>
    <message name="responseCrearContratoOLMessage">
        <part name="responseCrearContratoOL" element="preMO:CreaContratoOLResponse"/>
    </message>
    <portType name="PrestamoFlexcubePT">
        <operation name="CrearContratoOL">
            <input message="tns:requestCrearContratoOLMessage"/>
            <output message="tns:responseCrearContratoOLMessage"/>
        </operation>
    </portType>
    <binding name="PrestamoFlexcubePTSOAP12Bnd" type="tns:PrestamoFlexcubePT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CrearContratoOL">
            <soap12:operation style="document" soapAction="http://xmlns.bcie.com/Flexcube14/PrestamoService/crearContratoOL"/>
            <input>
                <soap12:body use="literal" parts="requestCrearContratoOL"/>
            </input>
            <output>
                <soap12:body use="literal" parts="responseCrearContratoOL"/>
            </output>
        </operation>
    </binding>
</definitions>