<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CrearNoObjecionPGA/ADAPTADORES/obtienePermisosUsuario" name="obtienePermisosUsuario-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="obtienePermisosUsuario.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CrearNoObjecionPGA/ADAPTADORES/obtienePermisosUsuario"/>
    <wsdl:binding name="obtienePermisosUsuario_ptt-binding" type="obt:obtienePermisosUsuario_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/CrearNoObjecionPGA/ADAPTADORES/obtienePermisosUsuario">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="obtienePermisosUsuario">
            <soap:operation soapAction="obtienePermisosUsuario"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>