<wsdl:definitions name="ConsultarResponsable" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarResponsable" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarResponsable" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarResponsable" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarResponsable_plt">
    <plt:role name="ConsultarResponsable_role">
      <plt:portType name="tns:ConsultarResponsable_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarResponsable" schemaLocation="../XSD/ConsultarResponsable_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarResponsableSelect_inputParameters">
        <wsdl:part name="ConsultarResponsableSelect_inputParameters" element="top:ConsultarResponsableSelect_idOperacionInputParameters"/>
    </wsdl:message>
    <wsdl:message name="OperacionCollection_msg">
        <wsdl:part name="OperacionCollection" element="top:OperacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarResponsable_ptt">
        <wsdl:operation name="ConsultarResponsableSelect">
            <wsdl:input message="tns:ConsultarResponsableSelect_inputParameters"/>
            <wsdl:output message="tns:OperacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>