<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/ReturnToVendorRequestApp/ReturnToVendorRequestJMS" name="ReturnToVendorRequestJMS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ReturnToVendorRequestJMS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/ReturnToVendorRequestApp/ReturnToVendorRequestJMS"/>
    <wsdl:binding name="Produce_Msg_ptt-binding" type="ret:Produce_Msg_ptt" xmlns:ret="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/ReturnToVendorRequestApp/ReturnToVendorRequestJMS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Msg">
            <soap:operation soapAction="Produce_Msg"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>