<wsdl:definitions
     name="ConsultarAtributoByCondicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarAtributoByCondicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarAtributoByCondicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAtributoByCondicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarAtributoByCondicion_plt" >
    <plt:role name="ConsultarAtributoByCondicion_role" >
      <plt:portType name="tns:ConsultarAtributoByCondicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAtributoByCondicion" schemaLocation="../XSD/ConsultarAtributoByCondicion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAtributoByCondicionInput_msg">
        <wsdl:part name="ConsultarAtributoByCondicionInput_msg" element="db:ConsultarAtributoByCondicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAtributoByCondicionOutputCollection_msg">
        <wsdl:part name="ConsultarAtributoByCondicionOutputCollection" element="db:ConsultarAtributoByCondicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAtributoByCondicion_ptt">
        <wsdl:operation name="ConsultarAtributoByCondicion">
            <wsdl:input message="tns:ConsultarAtributoByCondicionInput_msg"/>
            <wsdl:output message="tns:ConsultarAtributoByCondicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
