<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.banesco.com/eopt/AcctLoanInfoInq_V1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://www.temenos.com/T24/ofs/Response"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon"
                xmlns:ns1="http://www.temenos.com/T24/ofs/BPAWSLOANCONSULTATIONType"
                xmlns:ns7="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/BpaWsLoanConsultation/MetododeConsultadePrestamosResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="BPAWSLOANCONSULTATIONResponse"
                                       namespace="http://www.temenos.com/T24/ofs/Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanInfoInq/AcctLoanInfoInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctLoanInfoInqRs"
                                       namespace="http://xmlns.banesco.com/eopt/AcctLoanInfoInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JUL 10 11:23:35 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:include href="../../../../Commons/xslt/Template/TemplateServiceUtil.xsl"/>
  <xsl:template match="/">
    <tns:AcctLoanInfoInqRs>
      <xsl:variable name="statusCode">
        <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'T24', /ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Status, 'CNCODE', 'M0006' )"/>
      </xsl:variable>
      <xsl:choose>
        <xsl:when test="$statusCode='M0000' and /ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION">
          <tns:AcctLoan>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CATEGORY/text()">
              <eoAcct:AcctSubtype>
                <ns5:Cod>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CATEGORY"/>
                </ns5:Cod>
              </eoAcct:AcctSubtype>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACCOUNTTITLE1/text()">
              <eoAcct:AcctTitle>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACCOUNTTITLE1"/>
              </eoAcct:AcctTitle>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAAUTNOMIAS/text()">
              <eoAcct:AutonomyCode>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAAUTNOMIAS"/>
              </eoAcct:AutonomyCode>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/USERAUTONOMIA/text()">
              <eoAcct:AutonomyUser>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/USERAUTONOMIA"/>
              </eoAcct:AutonomyUser>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PRODUCT/text()">
              <eoAcct:Category>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PRODUCT"/>
              </eoAcct:Category>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/MATURITYDATE/text()">
              <eoAcct:ClosedDt>
                <xsl:call-template name="DatePattern">
                  <xsl:with-param name="date">
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/MATURITYDATE"/>
              </xsl:with-param>
                </xsl:call-template>
              </eoAcct:ClosedDt>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CLUBBAN/text()">
              <eoAcct:ClubBanesco>
                <!--<xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CLUBBAN"/>-->
                 <xsl:call-template name="Boolean_Regex">
                <xsl:with-param name="operation">INQ</xsl:with-param>
                <xsl:with-param name="parametro">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CLUBBAN"></xsl:value-of>
                </xsl:with-param>
              </xsl:call-template>
              </eoAcct:ClubBanesco>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CURRENCY/text()">
              <eoAcct:CurCode>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CURRENCY"/>
              </eoAcct:CurCode>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FECIPROPERTY/text()">
              <eoAcct:FeciProperty>
                <!--<xsl:call-template name="Si_No">
                  <xsl:with-param name="ResponseSiNo">
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FECIPROPERTY"/>
              </xsl:with-param>
                </xsl:call-template>-->
                   <xsl:call-template name="Boolean_Regex">
                <xsl:with-param name="operation">INQ</xsl:with-param>
                <xsl:with-param name="parametro">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FECIPROPERTY"></xsl:value-of>
                </xsl:with-param>
              </xsl:call-template>
              </eoAcct:FeciProperty>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/COMPANY/text()">
              <eoAcct:FIData>
                <ns4:Agency>
                  <ns4:AgencyIdent>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/COMPANY"/>
                  </ns4:AgencyIdent>
                </ns4:Agency>
              </eoAcct:FIData>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PRINPROPERTY/text()">
              <eoAcct:PrinProperty>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PRINPROPERTY"/>
              </eoAcct:PrinProperty>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSUBPRODUCT/text()">
              <eoAcct:SubCategory>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSUBPRODUCT"/>
              </eoAcct:SubCategory>
            </xsl:if>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/VARIATION/text()">
              <eoAcct:Variation>
                <ns5:Cod>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/VARIATION"/>
                </ns5:Cod>
              </eoAcct:Variation>
            </xsl:if>
            <eoAcct:AcctKey>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ARRID/text()">
                <eoAcct:AcctId>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ARRID"/>
                </eoAcct:AcctId>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACCOUNTREFERENCE/text()">
                <eoAcct:AcctReference>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACCOUNTREFERENCE"/>
                </eoAcct:AcctReference>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ALTID/text()">
                <eoAcct:AlternateId>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ALTID"/>
                </eoAcct:AlternateId>
              </xsl:if>
            </eoAcct:AcctKey>
            <eoAcct:IntRateData>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTDPFBASE/text()">
                <eoAcct:DepBase>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTDPFBASE"/>
                </eoAcct:DepBase>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/DAYBASIS/text()">
                <eoAcct:IntDayBasis>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/DAYBASIS"/>
                </eoAcct:IntDayBasis>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FIXEDRATE/text()">
                <eoAcct:IntRate>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FIXEDRATE"/>
                </eoAcct:IntRate>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSPREADPORC/text()">
                <eoAcct:SpreadPercentage>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSPREADPORC"/>
                </eoAcct:SpreadPercentage>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSPREADPOINT/text()">
                <eoAcct:SpreadPoint>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSPREADPOINT"/>
                </eoAcct:SpreadPoint>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTWOFRATE/text()">
                <eoAcct:WofRate>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTWOFRATE"/>
                </eoAcct:WofRate>
              </xsl:if>
            </eoAcct:IntRateData>
            <eoAcct:CreditAcctData>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/YOBSAPC/text()">
                <eoAcct:APCObs>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/YOBSAPC"/>
                </eoAcct:APCObs>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/AUTHTYPE/text()">
                <eoAcct:AuthType>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/AUTHTYPE"/>
                </eoAcct:AuthType>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/DESTINCODE/text()">
                <eoAcct:CodeDestination>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/DESTINCODE"/>
                </eoAcct:CodeDestination>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/COUNRISK/text()">
                <eoAcct:CountryDestination>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/COUNRISK"/>
                </eoAcct:CountryDestination>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/DSTNCREDIT/text()">
                <eoAcct:CreditDestination>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/DSTNCREDIT"/>
                </eoAcct:CreditDestination>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTDESTINO/text()">
                <eoAcct:FundsDestination>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTDESTINO"/>
                </eoAcct:FundsDestination>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/USEFOUND/text()">
                <eoAcct:FundsPurpose>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/USEFOUND"/>
                </eoAcct:FundsPurpose>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FECI/text()">
                <eoAcct:IntFeci>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FECI"/>
                </eoAcct:IntFeci>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PENALPROPERTY/text()">
                <eoAcct:LatePenalty>
                  <!--<xsl:call-template name="Si_No">
                    <xsl:with-param name="ResponseSiNo">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PENALPROPERTY"/>
                </xsl:with-param>
                  </xsl:call-template>-->
                     <xsl:call-template name="Boolean_Regex">
                <xsl:with-param name="operation">INQ</xsl:with-param>
                <xsl:with-param name="parametro">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PENALPROPERTY"></xsl:value-of>
                </xsl:with-param>
              </xsl:call-template>
              </eoAcct:LatePenalty>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ORIGINATIONREF/text()">
                <eoAcct:OriginationRef>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ORIGINATIONREF"/>
                </eoAcct:OriginationRef>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/STARTDATE/text()">
                <eoAcct:OriginationDt>
                  <xsl:call-template name="DatePattern">
                    <xsl:with-param name="date">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/STARTDATE"/>
                </xsl:with-param>
                  </xsl:call-template>
                </eoAcct:OriginationDt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/EXPDATE/text()">
                <eoAcct:PrefRateExpDt>
                  <xsl:call-template name="DatePattern">
                    <xsl:with-param name="date">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/EXPDATE"/>
                </xsl:with-param>
                  </xsl:call-template>
                </eoAcct:PrefRateExpDt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FINANPURPOSE/text()">
                <eoAcct:PurposeDesc>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FINANPURPOSE"/>
                </eoAcct:PurposeDesc>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/REFDATE/text()">
                <eoAcct:RefinanceDate>
                  <xsl:call-template name="DatePattern">
                    <xsl:with-param name="date">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/REFDATE"/>
                </xsl:with-param>
                  </xsl:call-template>
                </eoAcct:RefinanceDate>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/REFINANCENUM/text()">
                <eoAcct:RefinanceNum>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/REFINANCENUM"/>
                </eoAcct:RefinanceNum>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/RESTDATE/text()">
                <eoAcct:ResDt>
                  <xsl:call-template name="DatePattern">
                    <xsl:with-param name="date">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/RESTDATE"/>
                </xsl:with-param>
                  </xsl:call-template>
                </eoAcct:ResDt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/NUMRES/text()">
                <eoAcct:ResNum>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/NUMRES"/>
                </eoAcct:ResNum>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/EXPRESTR/text()">
                <eoAcct:RevResDt>
                  <xsl:call-template name="DatePattern">
                    <xsl:with-param name="date">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/EXPRESTR"/>
                </xsl:with-param>
                  </xsl:call-template>
                </eoAcct:RevResDt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/YFTASSALE/text()">
                <eoAcct:SourceSales>
                  <ns5:Cod>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/YFTASSALE"/>
                  </ns5:Cod>
                </eoAcct:SourceSales>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTWRITINGTYPE/text()">
                <eoAcct:TotalChargeAmt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/YCHARGEAMOUNT"/>
                  </ns5:Amt>
                </eoAcct:TotalChargeAmt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTWRITINGTYPE/text()">
                <eoAcct:WritingType>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTWRITINGTYPE"/>
                </eoAcct:WritingType>
              </xsl:if>
              <eoAcct:CreditRegularPmt>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACTUALAMT/text()">
                  <eoAcct:Amt>
                    <ns5:Amt>
                      <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACTUALAMT"/>
                    </ns5:Amt>
                  </eoAcct:Amt>
                </xsl:if>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAYMENTFREQ/text()">
                  <eoAcct:Freq>
                    <ns5:FreqValue>
                      <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAYMENTFREQ"/>
                    </ns5:FreqValue>
                  </eoAcct:Freq>
                </xsl:if>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAYMENTMETHOD/text()">
                  <eoAcct:PmtClass>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAYMENTMETHOD"/>
                  </eoAcct:PmtClass>
                </xsl:if>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAYMENTTYPE/text()">
                  <eoAcct:PmtType>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAYMENTTYPE"/>
                  </eoAcct:PmtType>
                </xsl:if>
              </eoAcct:CreditRegularPmt>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/TERM/text()">
                <eoAcct:Term>
                  <eoAcct:ProposedTerm>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/TERM"/>
                  </eoAcct:ProposedTerm>
                </eoAcct:Term>
              </xsl:if>
              <eoAcct:CreditAcctPmtInfo>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/NEXTPAYMENTDAY/text()">
                  <eoAcct:NextPmtDt>
                    <xsl:call-template name="DatePattern">
                      <xsl:with-param name="date">
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/NEXTPAYMENTDAY"/>
                  </xsl:with-param>
                    </xsl:call-template>
                  </eoAcct:NextPmtDt>
                </xsl:if>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAPAYMTYPE/text()">
                  <eoAcct:PmtMethod>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/PAPAYMTYPE"/>
                  </eoAcct:PmtMethod>
                </xsl:if>
              </eoAcct:CreditAcctPmtInfo>
              <eoAcct:Charge>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CHARGETYPE/text()">
                  <eoAcct:ChargeType>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CHARGETYPE"/>
                  </eoAcct:ChargeType>
                </xsl:if>
                <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FIXEDAMOUNT/text()">
                  <eoAcct:CurAmt>
                    <ns5:Amt>
                      <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/FIXEDAMOUNT"/>
                    </ns5:Amt>
                    <ns5:CurCode>
                      <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CHGCURRENCY"/>
                    </ns5:CurCode>
                  </eoAcct:CurAmt>
                </xsl:if>
              </eoAcct:Charge>
              <eoAcct:SettleInstruction>
                <xsl:for-each select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType">
                  <xsl:if test="PAYIN/text()">
                    <eoAcct:PayIn>                    
                      <eoAcct:PayInAcctRef>
                        <eoAcct:PayInAcct>
                          <eoAcct:AcctId>
                            <xsl:value-of select="PAYIN"/>
                          </eoAcct:AcctId>
                        </eoAcct:PayInAcct>
                      </eoAcct:PayInAcctRef>                    
                    </eoAcct:PayIn>
                  </xsl:if>
                </xsl:for-each>                
                <xsl:for-each select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType">
                  <xsl:if test="PAYOUT/text()">
                    <eoAcct:PayOut>
                      <eoAcct:PayOutAcct>
                        <eoAcct:AcctId>
                          <xsl:value-of select="PAYOUT"/>
                        </eoAcct:AcctId>
                      </eoAcct:PayOutAcct>
                    </eoAcct:PayOut>
                  </xsl:if>
                </xsl:for-each>                
              </eoAcct:SettleInstruction>
            </eoAcct:CreditAcctData>
            <eoAcct:AcctOpeningInfo>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/COSTCENTRE/text()">
                <eoAcct:CostCenter>
                  <ns5:CostCenterId>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/COSTCENTRE"/>
                  </ns5:CostCenterId>
                </eoAcct:CostCenter>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/EFECTIVEDATE/text()">
                <eoAcct:EffDt>
                  <xsl:call-template name="DatePattern">
                    <xsl:with-param name="date">
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/EFECTIVEDATE"/>
                </xsl:with-param>
                  </xsl:call-template>
                </eoAcct:EffDt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/AMOUNT/text()">
                <eoAcct:InitialAmt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/AMOUNT"/>
                  </ns5:Amt>
                </eoAcct:InitialAmt>
              </xsl:if>
              <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSALEOFFICER/text()">
                <eoAcct:SaleOfficer>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/LTSALEOFFICER"/>
                </eoAcct:SaleOfficer>
              </xsl:if>
            </eoAcct:AcctOpeningInfo>
            <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACTUALBAL/text()">
              <eoAcct:AcctBal>
                <eoAcct:CurAmt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/ACTUALBAL"/>
                  </ns5:Amt>
                </eoAcct:CurAmt>
              </eoAcct:AcctBal>
            </xsl:if>
          </tns:AcctLoan>
          <xsl:if test="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CUSID/text()">
            <tns:Party>
              <eoPar:PartyKey>
                <eoPar:PartyId>
                  <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/BPAWSLOANCONSULTATION/gBPAWSLOANCONSULTATIONDetailType/mBPAWSLOANCONSULTATIONDetailType/CUSID"/>
                </eoPar:PartyId>
              </eoPar:PartyKey>
            </tns:Party>
          </xsl:if>
          <tns:Status>
            <eoStatus:StatusCode>
              <xsl:value-of select="$statusCode"/>
            </eoStatus:StatusCode>
            <eoStatus:StatusDesc>
              <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'T24', /ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Status, 'CNDESC', 'FALLO EN LA OPERACION' )"/>
            </eoStatus:StatusDesc>
            <eoStatus:AdditionalStatus>
              <eoStatus:StatusCode>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Status"/>
              </eoStatus:StatusCode>
              <eoStatus:StatusDesc>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Message"/>
              </eoStatus:StatusDesc>
            </eoStatus:AdditionalStatus>
          </tns:Status>
        </xsl:when>
        <xsl:otherwise>
          <tns:Status>
            <eoStatus:StatusCode>
              <xsl:value-of select="$statusCode"/>
            </eoStatus:StatusCode>
            <eoStatus:StatusDesc>
              <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Message"/>
            </eoStatus:StatusDesc>
            <eoStatus:AdditionalStatus>
              <eoStatus:StatusCode>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Status"/>
              </eoStatus:StatusCode>
              <eoStatus:StatusDesc>
                <xsl:value-of select="/ns0:BPAWSLOANCONSULTATIONResponse/ResponseCommon/Message"/>
              </eoStatus:StatusDesc>
            </eoStatus:AdditionalStatus>
          </tns:Status>
        </xsl:otherwise>
      </xsl:choose>
      
    </tns:AcctLoanInfoInqRs>
  </xsl:template>
</xsl:stylesheet>