<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMFindPriceChangeEventDetailsDBBS" name="RPMFindPriceChangeEventDetailsDBBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RPMFindPriceChangeEventDetailsDBBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMFindPriceChangeEventDetailsDBBS"/>
    <wsdl:binding name="RPMFindPriceChangeEventDetailsDBBS_ptt-binding" type="rpm:RPMFindPriceChangeEventDetailsDBBS_ptt" xmlns:rpm="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMFindPriceChangeEventDetailsDBBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RPMFindPriceChangeEventDetailsDBBSSelect">
            <soap:operation soapAction="RPMFindPriceChangeEventDetailsDBBSSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>