<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarConfiguracion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarConfiguracion"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:confMO="http://www.bcie.org/ConsultarConfiguracionMO">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/ConsultarConfiguracion" schemaLocation="../Schema/ConsultarConfiguracionMO.xsd" />
    </xsd:schema>
  </types>
  <message name="ConsultarConfiguracionRequestMessage">
    <part name="request" element="tns:ConsultarConfiguracionRequest"/>
  </message>
  <message name="ConsultarConfiguracionResponseMessage">
    <part name="response" element="tns:ConsultarConfiguracionResponse"/>
  </message>
  <portType name="ConsultarConfiguracionPT">
    <operation name="ConsultarConfiguracion">
      <input message="tns:ConsultarConfiguracionRequestMessage"/>
      <output message="tns:ConsultarConfiguracionResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarConfiguracionPTSOAP12Bnd" type="tns:ConsultarConfiguracionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarConfiguracion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarConfiguracion/ConsultarConfiguracion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>