<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Evaluacion" targetNamespace="http://xmlns.bcie.com/EvaluacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:evaMO="http://www.bcie.org/EvaluacionMO"
                  xmlns:tns="http://xmlns.bcie.com/EvaluacionService"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/EvaluacionMO"
                  schemaLocation="../../Schema/EvaluacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
  <wsdl:message name="requestConsultarEvaluacionMessage">
    <wsdl:part name="request" element="evaMO:ConsultarEvaluacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseConsultarEvaluacionMessage">
    <wsdl:part name="response" element="evaMO:ConsultarEvaluacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarEvaluacionPT">
    <wsdl:operation name="ConsultarEvaluacion">
      <wsdl:input message="tns:requestConsultarEvaluacionMessage"/>
      <wsdl:output message="tns:responseConsultarEvaluacionMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Evaluacion12Bnd" type="tns:ConsultarEvaluacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarEvaluacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/EvaluacionService/ConsultarEvaluacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>




