<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/PublicarJMS" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/PublicarJMS"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:pubJMS="http://www.bcie.org/PublicarJMSMO">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/PublicarJMSMO"
                        schemaLocation="../../../PublicarJMS/V1/Schema/PublicarJMSMO.xsd"/>
        </xsd:schema>
    </types>
    <message name="PublicarJMSRequestMessage">
        <part name="PublicarJMSRequest" element="pubJMS:PublicarJMSRequest"/>
    </message>
    <message name="PublicarJMSResponseMessage">
        <part name="PublicarJMSResponse" element="pubJMS:PublicarJMSResponse"/>
    </message>
    <portType name="PublicarJMSPT">
        <operation name="publicarJMS">
            <input message="tns:PublicarJMSRequestMessage"/>
            <output message="tns:PublicarJMSResponseMessage"/>
        </operation>
    </portType>
    <binding name="PublicarJMSPT12Bnd" type="tns:PublicarJMSPT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="publicarJMS">
            <soap12:operation style="document" soapAction="http://www.bcie.org/PublicarJMS/publicarJMS"/>
            <input>
                <soap12:body use="literal" parts="PublicarJMSRequest"/>
            </input>
            <output>
                <soap12:body use="literal" parts="PublicarJMSResponse"/>
            </output>
        </operation>
    </binding>
</definitions>