<wsdl:definitions name="TranslateSupplierProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Suppliers/TranslateSupplierProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Suppliers/TranslateSupplierProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/TranslateSupplier!1.0/WSDLs/TranslateSupplierProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="TranslateSupplierProcess">
        <plnk:role name="TranslateSupplierProcessProvider" portType="client:TranslateSupplierProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" schemaLocation="../Schema/TranslateSupplierProcessSchema.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TranslateSupplierProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:oneCaseDbSelect_idC1_appCodeC1_targetAppCodeC1InputParameters"/>
    </wsdl:message>
    <wsdl:message name="TranslateSupplierProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:MdmSuppliersCollection"/>
    </wsdl:message>
    <wsdl:portType name="TranslateSupplierProcess">
        <wsdl:operation name="translate">
            <wsdl:input message="client:TranslateSupplierProcessRequestMessage"/>
            <wsdl:output message="client:TranslateSupplierProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="TranslateSupplierProcessBinding" type="client:TranslateSupplierProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="translate">
            <soap:operation style="document" soapAction="translate"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="TranslateSupplierServicio_ep">
        <wsdl:port name="TranslateSupplierProcess_pt" binding="client:TranslateSupplierProcessBinding">
            <soap:address location="http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/TranslateSupplier/TranslateSupplierServicio_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>