<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ObtenerTCCInicioService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://www.bcie.org/ObtenerTCCInicioService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns2="http://schemas.oracle.com/bpel/extension"
    >
    <plnk:partnerLinkType name="ObtenerTCCInicioPT_PLT">
        <plnk:role name="ObtenerTCCInicioPT_Role" portType="ns1:ObtenerTCCInicioPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ObtenerTCCInicioService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/MatrizTCC/V1/Wsdl/BPEL/ObtenerTCCInicioSOR.wsdl"/>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
</wsdl:definitions>
