<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/PropagarLineaCredito/ConsultarLineaCreditoByIdLineaCredito" name="ConsultarLineaCreditoByIdLineaCredito_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarLineaCreditoByIdLineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/PropagarLineaCredito/ConsultarLineaCreditoByIdLineaCredito"/>
    <wsdl:binding name="ConsultarLineaCreditoByIdLineaCredito_ptt-binding" type="con:ConsultarLineaCreditoByIdLineaCredito_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/PropagarLineaCredito/ConsultarLineaCreditoByIdLineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarLineaCreditoByIdLineaCredito">
            <soap:operation soapAction="ConsultarLineaCreditoByIdLineaCredito"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>