<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ActualizarContratoLineaCreditoService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://www.bcie.org/ActualizarContratoLineaCreditoService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ActualizarContratoLineaCreditoPT_PLT">
      <plnk:role name="ActualizarContratoLineaCreditoPT_Role" portType="ns1:ActualizarContratoLineaCreditoPT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bcie.org/ActualizarContratoLineaCreditoService" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/ActualizarContratoLineaCreditoServiceSOR.wsdl"/>
</wsdl:definitions>
