<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GenerarArchivosFenixV2SOR"
     targetNamespace="http://www.bcie.org/GestionCobroMO"
     xmlns:tns="http://www.bcie.org/GestionCobroMO"
     xmlns:inp1="http://www.bcie.org/GestionCobroMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/GestionCobroMO" schemaLocation="../../Schema/GestionCobroMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="GenerarArchivosFenixV2RequestMessage">
        <wsdl:part name="GenerarArchivosFenixV2Request" element="tns:GenerarArchivosFenixV2Request"/>
    </wsdl:message>
    <wsdl:message name="GenerarArchivosFenixV2ResponseMessage">
        <wsdl:part name="GenerarArchivosFenixV2Response" element="tns:GenerarArchivosFenixV2Response"/>
    </wsdl:message>
    <wsdl:portType name="GenerarArchivosFenixV2PT">
        <wsdl:operation name="generarArchivosFenixV2">
            <wsdl:input message="tns:GenerarArchivosFenixV2RequestMessage"/>
            <wsdl:output message="tns:GenerarArchivosFenixV2ResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GenerarArchivosFenixV2PTBnd" type="tns:GenerarArchivosFenixV2PT">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="generarArchivosFenixV2">
            <soap:operation style="document" soapAction="http://www.bcie.org/GestionCobroMO/generarArchivosFenixV2"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.bcie.org/GestionCobroMO"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.bcie.org/GestionCobroMO"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
