<wsdl:definitions
     name="ConsultarTreEventoCondicionByIdCondicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTreEventoCondicionByIdCondicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTreEventoCondicionByIdCondicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarTreEventoCondicionByIdCondicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarTreEventoCondicionByIdCondicion_plt" >
    <plt:role name="ConsultarTreEventoCondicionByIdCondicion_role" >
      <plt:portType name="tns:ConsultarTreEventoCondicionByIdCondicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarTreEventoCondicionByIdCondicion" schemaLocation="../XSD/ConsultarTreEventoCondicionByIdCondicion_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTreEventoCondicionByIdCondicionSelect_inputParameters">
        <wsdl:part name="ConsultarTreEventoCondicionByIdCondicionSelect_inputParameters" element="top:ConsultarTreEventoCondicionByIdCondicionSelect_idCondicion_idTcaEventoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="TreTcaEventoCondicionCollection_msg">
        <wsdl:part name="TreTcaEventoCondicionCollection" element="top:TreTcaEventoCondicionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTreEventoCondicionByIdCondicion_ptt">
        <wsdl:operation name="ConsultarTreEventoCondicionByIdCondicionSelect">
            <wsdl:input message="tns:ConsultarTreEventoCondicionByIdCondicionSelect_inputParameters"/>
            <wsdl:output message="tns:TreTcaEventoCondicionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
