<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ASNINBUS/ASNINAPP/JMS_ASNIN" name="JMS_ASNIN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="JMS_ASNIN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/ASNINBUS/ASNINAPP/JMS_ASNIN"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="jms:Produce_Message_ptt" xmlns:jms="http://xmlns.oracle.com/pcbpel/adapter/jms/ASNINBUS/ASNINAPP/JMS_ASNIN">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>