<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMSavePriceChangeDBBS" name="RPMSavePriceChangeDBBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RPMSavePriceChangeDBBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMSavePriceChangeDBBS"/>
    <wsdl:binding name="RPMSavePriceChangeDBBS_ptt-binding" type="rpm:RPMSavePriceChangeDBBS_ptt" xmlns:rpm="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/RPMSavePriceChangeDBBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RPMSavePriceChangeDBBS">
            <soap:operation soapAction="RPMSavePriceChangeDBBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>