<wsdl:definitions
     name="ConsultarUsuarioProcesoCliente_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarUsuarioProcesoCliente_DB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarUsuarioProcesoCliente_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarUsuarioProcesoCliente_DB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarUsuarioProcesoCliente_DB_plt" >
    <plt:role name="ConsultarUsuarioProcesoCliente_DB_role" >
      <plt:portType name="tns:ConsultarUsuarioProcesoCliente_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarUsuarioProcesoCliente_DB" schemaLocation="../XSD/ConsultarUsuarioProcesoCliente_DB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarUsuarioProcesoCliente_DBInput_msg">
        <wsdl:part name="ConsultarUsuarioProcesoCliente_DBInput_msg" element="db:ConsultarUsuarioProcesoCliente_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarUsuarioProcesoCliente_DBOutputCollection_msg">
        <wsdl:part name="ConsultarUsuarioProcesoCliente_DBOutputCollection" element="db:ConsultarUsuarioProcesoCliente_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarUsuarioProcesoCliente_DB_ptt">
        <wsdl:operation name="ConsultarUsuarioProcesoCliente_DB">
            <wsdl:input message="tns:ConsultarUsuarioProcesoCliente_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarUsuarioProcesoCliente_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
