<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ActualizarFuenteLCSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ActualizarFuenteLCSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ActualizarFuenteLC_SB">
        <plnk:role name="ActualizarFuenteLC_PT" portType="tns:ActualizarFuenteLC_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ActualizarFuenteLCSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/ADAPTER/ActualizarFuenteLCSAD.wsdl"/>
</wsdl:definitions>
