<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.banesco.com/appopt/T24CardTrnAppSvc/CardCrCashAdd_V1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoPmt="http://xmlns.banesco.com/eo/Pmt_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:ns9="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:eoBank="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Bill_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/T24CardTrn/CardCrCashAdd/CardCrCashAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="CardCrCashAddRq" namespace="http://xmlns.banesco.com/appopt/T24CardTrnAppSvc/CardCrCashAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardCr/CardCrCashAdd/CardCrCashAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="CardCrCashAddRq" namespace="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUN 18 12:41:35 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CardCrCashAddRq>
         <tns:FIData>
            <xsl:if test="/ns0:CardCrCashAddRq/ns0:FIData/ns0:FIIdent/text()">
               <eoBank:FIIdent>
                  <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:FIData/ns0:FIIdent"/>
               </eoBank:FIIdent>
            </xsl:if>
            <eoBank:Agency>
               <xsl:if test="/ns0:CardCrCashAddRq/ns0:FIData/ns0:Agency/ns0:AgencyIdent/text()">
                  <eoBank:AgencyIdent>
                     <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:FIData/ns0:Agency/ns0:AgencyIdent"/>
                  </eoBank:AgencyIdent>
               </xsl:if>
            </eoBank:Agency>
         </tns:FIData>
         <tns:PartyKey>
            <xsl:if test="/ns0:CardCrCashAddRq/ns0:PartyKey/ns0:PartyId/text()">
               <eoPar:PartyId>
                  <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:PartyKey/ns0:PartyId"/>
               </eoPar:PartyId>
            </xsl:if>
         </tns:PartyKey>
         <tns:Pmt>
            <eoPmt:PmtTrnDetail>
               <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:DebitId/text()">
                  <ns4:DebitId>
                     <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:DebitId"/>
                  </ns4:DebitId>
               </xsl:if>
               <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TotalCurAmt/text()">
                  <ns4:TotalCurAmt>
                     <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TotalCurAmt/appoptcommon:Amt/text()">
                        <ns8:Amt>
                           <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TotalCurAmt/appoptcommon:Amt"/>
                        </ns8:Amt>
                     </xsl:if>
                     <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TotalCurAmt/appoptcommon:CurCode/text()">
                        <ns8:CurCode>
                           <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TotalCurAmt/appoptcommon:CurCode"/>
                        </ns8:CurCode>
                     </xsl:if>
                  </ns4:TotalCurAmt>
               </xsl:if>
               <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TrnKey/text()">
                  <ns4:TrnKey>
                     <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TrnKey/ns0:TrnId/text()">
                        <ns4:TrnId>
                           <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:TrnKey/ns0:TrnId"/>
                        </ns4:TrnId>
                     </xsl:if>
                  </ns4:TrnKey>
               </xsl:if>
               <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:CardKey/text()">
                  <ns4:CardKey>
                     <xsl:if test="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:CardKey/ns0:CardNum/text()">
                        <ns5:CardNum>
                           <xsl:value-of select="/ns0:CardCrCashAddRq/ns0:Pmt/ns0:PmtTrnDetail/ns0:CardKey/ns0:CardNum"/>
                        </ns5:CardNum>
                     </xsl:if>
                  </ns4:CardKey>
               </xsl:if>
            </eoPmt:PmtTrnDetail>
         </tns:Pmt>
      </tns:CardCrCashAddRq>
   </xsl:template>
</xsl:stylesheet>
