<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:tns="http://xmlns.banesco.com/appopt/T24CardTrnAppSvc/CardCrCashAdd_V1.0"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns2="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoPmt="http://xmlns.banesco.com/eo/Pmt_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:ns9="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:eoBank="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Bill_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardCr/CardCrCashAdd/CardCrCashAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="CardCrCashAddRs"
                                       namespace="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/T24CardTrn/CardCrCashAdd/CardCrCashAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="CardCrCashAddRs"
                                       namespace="http://xmlns.banesco.com/appopt/T24CardTrnAppSvc/CardCrCashAdd_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUN 18 12:50:43 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CardCrCashAddRs>
      <tns:FIData>
        <xsl:if test="/ns0:CardCrCashAddRs/ns0:FIData/eoBank:FIIdent/text()">
          <tns:FIIdent>
            <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:FIData/eoBank:FIIdent"/>
          </tns:FIIdent>
        </xsl:if>
        <tns:Agency>
          <xsl:if test="/ns0:CardCrCashAddRs/ns0:FIData/eoBank:Agency/eoBank:AgencyIdent/text()">
            <tns:AgencyIdent>
              <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:FIData/eoBank:Agency/eoBank:AgencyIdent"/>
            </tns:AgencyIdent>
          </xsl:if>
        </tns:Agency>
      </tns:FIData>
      <tns:Pmt>
        <tns:PmtTrnDetail>
          <xsl:if test="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:DebitId/text()">
            <tns:DebitId>
              <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:DebitId"/>
            </tns:DebitId>
          </xsl:if>
          <tns:Status>
            <xsl:if test="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:Status/ns8:Cod/text()">
              <appoptcommon:Cod>
                <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:Status/ns8:Cod"/>
              </appoptcommon:Cod>
            </xsl:if>
            <xsl:if test="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:Status/ns8:Desc/text()">
              <appoptcommon:Desc>
                <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:Status/ns8:Desc"/>
              </appoptcommon:Desc>
            </xsl:if>
          </tns:Status>
          <tns:TotalCurAmt>
            <xsl:if test="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:TotalCurAmt/ns8:Amt/text()">
              <appoptcommon:Amt>
                <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:TotalCurAmt/ns8:Amt"/>
              </appoptcommon:Amt>
            </xsl:if>
          </tns:TotalCurAmt>
          <tns:TrnKey>
            <xsl:if test="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:TrnKey/ns4:TrnId/text()">
              <tns:TrnId>
                <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:TrnKey/ns4:TrnId"/>
              </tns:TrnId>
            </xsl:if>
          </tns:TrnKey>
          <tns:CardKey>
            <xsl:if test="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:CardKey/ns5:CardNum/text()">
              <tns:CardNum>
                <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:CardKey/ns5:CardNum"/>
              </tns:CardNum>
            </xsl:if>
          </tns:CardKey>
        </tns:PmtTrnDetail>
      </tns:Pmt>
      <tns:Status>
        <appoptcommon:StatusCode>
          <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Status/eoStatus:StatusCode"/>
        </appoptcommon:StatusCode>
        <appoptcommon:StatusDesc>
          <xsl:value-of select="/ns0:CardCrCashAddRs/ns0:Status/eoStatus:StatusDesc"/>
        </appoptcommon:StatusDesc>
      </tns:Status>
    </tns:CardCrCashAddRs>
  </xsl:template>
</xsl:stylesheet>
