<wsdl:definitions name="ConsultarBitacoraProcesoClienteDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoClienteDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoClienteDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoClienteDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarBitacoraProcesoClienteDB_plt">
    <plt:role name="ConsultarBitacoraProcesoClienteDB_role">
      <plt:portType name="tns:ConsultarBitacoraProcesoClienteDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoClienteDB" schemaLocation="../XSD/ConsultarBitacoraProcesoClienteDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarBitacoraProcesoClienteDBInput_msg">
        <wsdl:part name="ConsultarBitacoraProcesoClienteDBInput_msg" element="db:ConsultarBitacoraProcesoClienteDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarBitacoraProcesoClienteDBOutputCollection_msg">
        <wsdl:part name="ConsultarBitacoraProcesoClienteDBOutputCollection" element="db:ConsultarBitacoraProcesoClienteDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarBitacoraProcesoClienteDB_ptt">
        <wsdl:operation name="ConsultarBitacoraProcesoClienteDB">
            <wsdl:input message="tns:ConsultarBitacoraProcesoClienteDBInput_msg"/>
            <wsdl:output message="tns:ConsultarBitacoraProcesoClienteDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>