<wsdl:definitions name="ValidarEnProcesoExcepcion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnProcesoExcepcion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnProcesoExcepcion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarEnProcesoExcepcion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ValidarEnProcesoExcepcion_DB_plt">
    <plt:role name="ValidarEnProcesoExcepcion_DB_role">
      <plt:portType name="tns:ValidarEnProcesoExcepcion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarEnProcesoExcepcion_DB" schemaLocation="../XSD/ValidarEnProcesoExcepcion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ValidarEnProcesoExcepcion_DBInput_msg">
        <wsdl:part name="ValidarEnProcesoExcepcion_DBInput_msg" element="db:ValidarEnProcesoExcepcion_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ValidarEnProcesoExcepcion_DBOutputCollection_msg">
        <wsdl:part name="ValidarEnProcesoExcepcion_DBOutputCollection" element="db:ValidarEnProcesoExcepcion_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ValidarEnProcesoExcepcion_DB_ptt">
        <wsdl:operation name="ValidarEnProcesoExcepcion_DB">
            <wsdl:input message="tns:ValidarEnProcesoExcepcion_DBInput_msg"/>
            <wsdl:output message="tns:ValidarEnProcesoExcepcion_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>