<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderASN" name="DBRMSOrderASN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../QueryRMS/Resources/Resources/DBRMSOrderASN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderASN"/>
    <wsdl:binding name="DBRMSOrderASN_ptt-binding" type="dbr:DBRMSOrderASN_ptt" xmlns:dbr="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderASN">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBRMSOrderASNSelect">
            <soap:operation soapAction="DBRMSOrderASNSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>