<wsdl:definitions name="CrearBitacoraProceso" targetNamespace="http://www.bcie.com/CrearBitacoraProceso" xmlns:tns="http://www.bcie.com/CrearBitacoraProceso" xmlns:regBitMO="http://www.bcie.org/CrearBitacoraProcesoMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/CrearBitacoraProcesoMO" schemaLocation="../Schema/BitacoraProcesoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="consultarBitacorarequestMessage">
      <wsdl:part name="request" element="regBitMO:consultarBitacoraProcesoRequest"/>
    </wsdl:message>
    <wsdl:message name="consultarBitacorareplyMessage">
          <wsdl:part name="response" element="regBitMO:consultarBitacoraProcesoResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarBitacoraProceso_PT">
        <wsdl:operation name="consultarBitacoraProceso">
            <wsdl:input message="tns:consultarBitacorarequestMessage"/>
            <wsdl:output message="tns:consultarBitacorareplyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsultarBitacoraProceso_PT12Bnd" type="tns:ConsultarBitacoraProceso_PT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="consultarBitacoraProceso">
            <soap12:operation style="document"
                              soapAction="http://www.bcie.com/CrearBitacoraProceso/consultarBitacoraProceso"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>