<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/DeclaracionJuradaService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/DeclaracionJuradaService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:dJMO="http://www.bcie.org/DeclaracionJuradaMO">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/DeclaracionJuradaMO" schemaLocation="../../Schema/DeclaracionJuradaMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="requestConsultarDeclaracionJuradaByIdOperacionMessage">
    <part name="request" element="dJMO:ConsultarDeclaracionJuradaRequest"/>
  </message>
  <message name="responseConsultarDeclaracionJuradaByIdOperacionMessage">
    <part name="response" element="dJMO:ConsultarDeclaracionJuradaResponse"/>
  </message>
  <portType name="DeclaracionJuradaPT">
    <operation name="consultarDeclaracionJurada">
      <input message="tns:requestConsultarDeclaracionJuradaByIdOperacionMessage"/>
      <output message="tns:responseConsultarDeclaracionJuradaByIdOperacionMessage"/>
    </operation>
  </portType>
  <binding name="DeclaracionJurada12Bnd" type="tns:DeclaracionJuradaPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarDeclaracionJurada">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/DeclaracionJuradaService/consultarDeclaracion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>