<wsdl:definitions name="ConsultarEquipoTrabajoDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarEquipoTrabajoDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarEquipoTrabajoDB_plt">
    <plt:role name="ConsultarEquipoTrabajoDB_role">
      <plt:portType name="tns:ConsultarEquipoTrabajoDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarEquipoTrabajoDB" schemaLocation="../XSD/ConsultarEquipoTrabajoDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarEquipoTrabajoDBSelect_inputParameters">
        <wsdl:part name="ConsultarEquipoTrabajoDBSelect_inputParameters" element="top:ConsultarEquipoTrabajoDBSelect_idProductoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="TreEquipoTrabajoCollection_msg">
        <wsdl:part name="TreEquipoTrabajoCollection" element="top:TreEquipoTrabajoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarEquipoTrabajoDB_ptt">
        <wsdl:operation name="ConsultarEquipoTrabajoDBSelect">
            <wsdl:input message="tns:ConsultarEquipoTrabajoDBSelect_inputParameters"/>
            <wsdl:output message="tns:TreEquipoTrabajoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>