<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SendEmail" targetNamespace="http://mx.agarcia.ea/Utility/Email/SendEmailSrv/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Utility/Email/SendEmailSrv/v1.0" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://mx.agarcia.ea/Utility/Email/SendEmail" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Utility/Email/SendEmail" schemaLocation="../Schemas/SendEmailSchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="SendEmailRequestMessage">
      <wsdl:part name="SendEmailRequest" element="ns1:requestEmail"/>
   </wsdl:message>
   <plnk:partnerLinkType name="SendEmail">
      <plnk:role name="SendEmailProvider" portType="client:SendEmail"/>
   </plnk:partnerLinkType>
   <wsdl:portType name="SendEmail">
      <wsdl:operation name="send">
         <wsdl:input message="client:SendEmailRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="SendEmailBinding" type="client:SendEmail">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="send">
         <soap:operation style="document" soapAction="http://mx.agarcia.ea/Utility/Email/SendEmailSrv/v1.0/send"/>
         <wsdl:input>
            <soap:body use="literal" parts="SendEmailRequest"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
