<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/ItemApp/ItemJMSReference" name="ItemJMSReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ItemJMSReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/ItemApp/ItemJMSReference"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="item:Produce_Message_ptt" xmlns:item="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/ItemApp/ItemJMSReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>