<wsdl:definitions name="ConsultarOperacionesAsociadas_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacionesAsociadas_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacionesAsociadas_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionesAsociadas_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarOperacionesAsociadas_DB_plt" >
    <plt:role name="ConsultarOperacionesAsociadas_DB_role" >
      <plt:portType name="tns:ConsultarOperacionesAsociadas_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionesAsociadas_DB" schemaLocation="../XSD/ConsultarOperacionesAsociadas_DB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarOperacionesAsociadas_DBInput_msg">
        <wsdl:part name="ConsultarOperacionesAsociadas_DBInput_msg" element="db:ConsultarOperacionesAsociadas_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarOperacionesAsociadas_DBOutputCollection_msg">
        <wsdl:part name="ConsultarOperacionesAsociadas_DBOutputCollection" element="db:ConsultarOperacionesAsociadas_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarOperacionesAsociadas_DB_ptt">
        <wsdl:operation name="ConsultarOperacionesAsociadas_DB">
            <wsdl:input message="tns:ConsultarOperacionesAsociadas_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarOperacionesAsociadas_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>