<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://www.bcie.org/ConfiguracionProcesosMO"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/LeccionesAprendidas/Payload/V1"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:confBO="http://www.bcie.org/ConfiguracionProcesosBO" xmlns:ns2="http://www.bcie.org/TerminoBO"
                xmlns:ns3="http://www.bcie.org/ReglaBO" xmlns:operBO="http://www.bcie.org/OperacionBO"
                xmlns:resBO="http://www.bcie.org/ResultBO" xmlns:cmnBO="http://www.bcie.org/CommonBO"
                xmlns:ns4="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:lecciones="http://www.bcie.org/LeccionAprendidaBO" xmlns:ns7="http://www.bcie.org/MatrizTCCBO"
                xmlns:ns5="http://www.bcie.org/CrearBitacoraProcesoBO" xmlns:ns6="http://www.bcie.org/LineaCreditoBO"
                xmlns:ns8="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns9="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns11="http://www.bcie.org/ProductoBO" xmlns:ns10="http://www.bcie.org/CondicionBO"
                xmlns:ns12="http://www.bcie.org/DeclaracionJuradaBO"
                xmlns:ns13="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:ns14="http://www.bcie.org/ImplementacionPctBO" xmlns:ns15="http://www.bcie.org/DocumentoBO"
                xmlns:ns16="http://www.bcie.org/HerramientaCEBO" xmlns:ns17="http://www.bcie.org/ComisionBO"
                xmlns:ns18="http://www.bcie.org/CatalogoBO" xmlns:desBO="http://www.bcie.org/DesembolsoBO"
                xmlns:ns19="http://www.bcie.org/AdquisicionBO" xmlns:ns20="http://www.bcie.org/ContratoBO"
                xmlns:cteBO="http://www.bcie.org/ClienteBO" xmlns:ns21="http://www.bcie.org/AtributoBO"
                xmlns:ns23="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1"
                xmlns:ns22="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:ns24="http://www.bcie.org/ErrorBO">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/Schema/ConfiguracionProcesosMO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ConfiguracionLeccionesAprendidasResponse"
                                       namespace="http://www.bcie.org/ConfiguracionProcesosMO"/>
        <oracle-xsl-mapper:param name="configuracionLeccionesAprendidasResponse"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA17/LeccionesAprendidasPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="LeccionesAprendidasPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/LeccionesAprendidas/Payload/V1"/>
        <oracle-xsl-mapper:param name="leccionesAprendidasDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA17/LeccionesAprendidasPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="LeccionesAprendidasPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/LeccionesAprendidas/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAY 10 17:16:31 CST 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="leccionesAprendidasDO"/>
  <xsl:template match="/">
    <ns1:LeccionesAprendidasPayload>
      <ns1:Header>
        <ns13:Operacion>
          <ns8:CodigoOperacion>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:idOperacion"/>
          </ns8:CodigoOperacion>
          <ns8:NombreOperacion>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:nombre"/>
          </ns8:NombreOperacion>
          <ns8:ResponsableOperacion>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:responsable"/>
          </ns8:ResponsableOperacion>
          <ns8:CodigoCliente>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:cliente/cteBO:idCliente"/>
          </ns8:CodigoCliente>
          <ns8:NombreCliente>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:cliente/cteBO:razonSocial"/>
          </ns8:NombreCliente>
          <ns8:CodigoProducto>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:producto/ns11:idProducto"/>
          </ns8:CodigoProducto>
          <ns8:NombreProducto>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:producto/ns11:descripcion"/>
          </ns8:NombreProducto>
          <ns8:MontoSolicitado>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:montoOperacion/operBO:montoOperacion[operBO:id = 2]/operBO:monto"/>
          </ns8:MontoSolicitado>
          <ns8:Pais>
            <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:cliente/cteBO:pais/ns18:Descripcion"/>
          </ns8:Pais>
        </ns13:Operacion>
        <ns13:Proceso>
          <ns9:IdProceso>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:IdProceso"/>
          </ns9:IdProceso>
          <ns9:CodigoProceso>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:CodigoProceso"/>
          </ns9:CodigoProceso>
          <ns9:NombreProceso>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:NombreProceso"/>
          </ns9:NombreProceso>
          <ns9:EsProcesoCore>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:EsProcesoCore"/>
          </ns9:EsProcesoCore>
          <ns9:RolIniciaProceso>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:RolIniciaProceso"/>
          </ns9:RolIniciaProceso>
          <ns9:UsuarioIniciaProceso>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:UsuarioIniciaProceso"/>
          </ns9:UsuarioIniciaProceso>
          <ns9:InstanciaProceso>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:InstanciaProceso"/>
          </ns9:InstanciaProceso>
          <ns9:IdFlujo>
            <xsl:value-of select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns1:Header/ns13:Proceso/ns9:IdFlujo"/>
          </ns9:IdFlujo>
        </ns13:Proceso>
      </ns1:Header>
      <ns1:Configuration/>
      <ns1:LeccionesAprendidas>
        <xsl:for-each select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:LeccionAprendida">
          <ns1:LeccionAprendida>
            <lecciones:idLeccionAprendida>
              <xsl:value-of select="lecciones:idLeccionAprendida"/>
            </lecciones:idLeccionAprendida>
            <lecciones:descripcion>
              <xsl:value-of select="lecciones:descripcion"/>
            </lecciones:descripcion>
            <lecciones:recomendacion>
              <xsl:value-of select="lecciones:recomendacion"/>
            </lecciones:recomendacion>
            <lecciones:nivelIncidencia>
              <xsl:value-of select="lecciones:nivelIncidencia"/>
            </lecciones:nivelIncidencia>
            <lecciones:usuario>
              <xsl:value-of select="lecciones:usuario"/>
            </lecciones:usuario>
            <lecciones:estado>
              <xsl:if test="lecciones:estado/ns18:Id">
                <ns18:Id>
                  <xsl:value-of select="lecciones:estado/ns18:Id"/>
                </ns18:Id>
              </xsl:if>
              <xsl:if test="lecciones:estado/ns18:Descripcion">
                <ns18:Descripcion>
                  <xsl:value-of select="lecciones:estado/ns18:Descripcion"/>
                </ns18:Descripcion>
              </xsl:if>
              <xsl:if test="lecciones:estado/ns18:DescripcionCorta">
                <ns18:DescripcionCorta>
                  <xsl:value-of select="lecciones:estado/ns18:DescripcionCorta"/>
                </ns18:DescripcionCorta>
              </xsl:if>
              <xsl:if test="lecciones:estado/ns18:estatus">
                <ns18:estatus>
                  <xsl:value-of select="lecciones:estado/ns18:estatus"/>
                </ns18:estatus>
              </xsl:if>
              <xsl:if test="lecciones:estado/ns18:codigoExterno">
                <ns18:codigoExterno>
                  <xsl:value-of select="lecciones:estado/ns18:codigoExterno"/>
                </ns18:codigoExterno>
              </xsl:if>
            </lecciones:estado>
            <lecciones:producto>
              <ns11:idProducto>
                <xsl:value-of select="lecciones:producto/ns11:idProducto"/>
              </ns11:idProducto>
              <ns11:descripcion>
                <xsl:value-of select="lecciones:producto/ns11:descripcion"/>
              </ns11:descripcion>
              <ns11:descripcionCorta>
                <xsl:value-of select="lecciones:producto/ns11:descripcionCorta"/>
              </ns11:descripcionCorta>
              <ns11:fechaRegistro>
                <xsl:value-of select="lecciones:producto/ns11:fechaRegistro"/>
              </ns11:fechaRegistro>
              <ns11:codExterno>
                <xsl:value-of select="lecciones:producto/ns11:codExterno"/>
              </ns11:codExterno>
            </lecciones:producto>
            <lecciones:operacion>
              <operBO:idOperacion>
                <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:idOperacion"/>
              </operBO:idOperacion>
              <xsl:if test="lecciones:operacion/operBO:responsable">
                <operBO:responsable>
                  <xsl:value-of select="lecciones:operacion/operBO:responsable"/>
                </operBO:responsable>
              </xsl:if>
              <xsl:if test="lecciones:operacion/operBO:oficina">
                <operBO:oficina>
                  <xsl:value-of select="lecciones:operacion/operBO:oficina"/>
                </operBO:oficina>
              </xsl:if>
              <xsl:if test="lecciones:operacion/operBO:nombre">
                <operBO:nombre>
                  <xsl:value-of select="lecciones:operacion/operBO:nombre"/>
                </operBO:nombre>
              </xsl:if>
            </lecciones:operacion>
            <lecciones:proceso>
              <ns9:IdProceso>
                <xsl:value-of select="lecciones:proceso/ns9:IdProceso"/>
              </ns9:IdProceso>
              <xsl:if test="lecciones:proceso/ns9:CodigoProceso">
                <ns9:CodigoProceso>
                  <xsl:value-of select="lecciones:proceso/ns9:CodigoProceso"/>
                </ns9:CodigoProceso>
              </xsl:if>
              <xsl:if test="lecciones:proceso/ns9:NombreProceso">
                <ns9:NombreProceso>
                  <xsl:value-of select="lecciones:proceso/ns9:NombreProceso"/>
                </ns9:NombreProceso>
              </xsl:if>
              <xsl:if test="lecciones:proceso/ns9:EsProcesoCore">
                <ns9:EsProcesoCore>
                  <xsl:value-of select="lecciones:proceso/ns9:EsProcesoCore"/>
                </ns9:EsProcesoCore>
              </xsl:if>
              <xsl:if test="lecciones:proceso/ns9:RolIniciaProceso">
                <ns9:RolIniciaProceso>
                  <xsl:value-of select="lecciones:proceso/ns9:RolIniciaProceso"/>
                </ns9:RolIniciaProceso>
              </xsl:if>
              <xsl:if test="lecciones:proceso/ns9:UsuarioIniciaProceso">
                <ns9:UsuarioIniciaProceso>
                  <xsl:value-of select="lecciones:proceso/ns9:UsuarioIniciaProceso"/>
                </ns9:UsuarioIniciaProceso>
              </xsl:if>
              <xsl:if test="lecciones:proceso/ns9:InstanciaProceso">
                <ns9:InstanciaProceso>
                  <xsl:value-of select="lecciones:proceso/ns9:InstanciaProceso"/>
                </ns9:InstanciaProceso>
              </xsl:if>
              <xsl:if test="lecciones:proceso/ns9:IdFlujo">
                <ns9:IdFlujo>
                  <xsl:value-of select="lecciones:proceso/ns9:IdFlujo"/>
                </ns9:IdFlujo>
              </xsl:if>
            </lecciones:proceso>
            <lecciones:tarea>
              <ns22:CodigoTarea>
                <xsl:value-of select="lecciones:tarea/ns22:CodigoTarea"/>
              </ns22:CodigoTarea>
              <ns22:NombreTarea>
                <xsl:value-of select="lecciones:tarea/ns22:NombreTarea"/>
              </ns22:NombreTarea>
              <xsl:if test="lecciones:tarea/ns22:CodigoRol">
                <ns22:CodigoRol>
                  <xsl:value-of select="lecciones:tarea/ns22:CodigoRol"/>
                </ns22:CodigoRol>
              </xsl:if>
              <xsl:if test="lecciones:tarea/ns22:NombreRol">
                <ns22:NombreRol>
                  <xsl:value-of select="lecciones:tarea/ns22:NombreRol"/>
                </ns22:NombreRol>
              </xsl:if>
              <xsl:if test="lecciones:tarea/ns22:CodigoProceso">
                <ns22:CodigoProceso>
                  <xsl:value-of select="lecciones:tarea/ns22:CodigoProceso"/>
                </ns22:CodigoProceso>
              </xsl:if>
              <xsl:if test="lecciones:tarea/ns22:NombreProceso">
                <ns22:NombreProceso>
                  <xsl:value-of select="lecciones:tarea/ns22:NombreProceso"/>
                </ns22:NombreProceso>
              </xsl:if>
            </lecciones:tarea>
            <lecciones:categorias>
              <xsl:for-each select="lecciones:categorias/lecciones:categoria">
                <lecciones:categoria>
                  <xsl:if test="ns18:Id">
                    <ns18:Id>
                      <xsl:value-of select="ns18:Id"/>
                    </ns18:Id>
                  </xsl:if>
                  <xsl:if test="ns18:Descripcion">
                    <ns18:Descripcion>
                      <xsl:value-of select="ns18:Descripcion"/>
                    </ns18:Descripcion>
                  </xsl:if>
                  <xsl:if test="ns18:DescripcionCorta">
                    <ns18:DescripcionCorta>
                      <xsl:value-of select="ns18:DescripcionCorta"/>
                    </ns18:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns18:estatus">
                    <ns18:estatus>
                      <xsl:value-of select="ns18:estatus"/>
                    </ns18:estatus>
                  </xsl:if>
                  <xsl:if test="ns18:codigoExterno">
                    <ns18:codigoExterno>
                      <xsl:value-of select="ns18:codigoExterno"/>
                    </ns18:codigoExterno>
                  </xsl:if>
                  <lecciones:rol>
                    <xsl:if test="lecciones:rol/ns18:Id">
                      <ns18:Id>
                        <xsl:value-of select="lecciones:rol/ns18:Id"/>
                      </ns18:Id>
                    </xsl:if>
                    <xsl:if test="lecciones:rol/ns18:Descripcion">
                      <ns18:Descripcion>
                        <xsl:value-of select="lecciones:rol/ns18:Descripcion"/>
                      </ns18:Descripcion>
                    </xsl:if>
                    <xsl:if test="lecciones:rol/ns18:DescripcionCorta">
                      <ns18:DescripcionCorta>
                        <xsl:value-of select="lecciones:rol/ns18:DescripcionCorta"/>
                      </ns18:DescripcionCorta>
                    </xsl:if>
                    <xsl:if test="lecciones:rol/ns18:estatus">
                      <ns18:estatus>
                        <xsl:value-of select="lecciones:rol/ns18:estatus"/>
                      </ns18:estatus>
                    </xsl:if>
                    <xsl:if test="lecciones:rol/ns18:codigoExterno">
                      <ns18:codigoExterno>
                        <xsl:value-of select="lecciones:rol/ns18:codigoExterno"/>
                      </ns18:codigoExterno>
                    </xsl:if>
                  </lecciones:rol>
                  <lecciones:usuario>
                    <xsl:value-of select="lecciones:usuario"/>
                  </lecciones:usuario>
                  <lecciones:respuesta>
                    <xsl:value-of select="lecciones:respuesta"/>
                  </lecciones:respuesta>
                </lecciones:categoria>
              </xsl:for-each>
            </lecciones:categorias>
          </ns1:LeccionAprendida>
        </xsl:for-each>
      </ns1:LeccionesAprendidas>
      <ns1:EquipoPayload>
        <ns1:UsuarioInicio>
          <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:LeccionAprendida/lecciones:usuario"/>
        </ns1:UsuarioInicio>
        <xsl:choose>
          <xsl:when test="oraext:compare-ignore-case(/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:LeccionAprendida/lecciones:usuario,/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:responsable) = 0">
            <ns1:EmisorOpinion>
              <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:RolesEquipoTrabajo/confBO:Rol[ns18:Id=41]/ns18:DescripcionCorta"/>
            </ns1:EmisorOpinion>
          </xsl:when>
          <xsl:otherwise>
            <ns1:EmisorOpinion>
              <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:operacion/operBO:responsable"/>
            </ns1:EmisorOpinion>
          </xsl:otherwise>
        </xsl:choose>
        <ns1:RevisorResultados>
          <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:LeccionAprendida/lecciones:usuario"/>
        </ns1:RevisorResultados>
        <ns1:GerenteCredito>
          <xsl:value-of select="/ns0:ConfiguracionLeccionesAprendidasResponse/ns0:configuracionLeccionesAprendidas/confBO:RolesEquipoTrabajo/confBO:Rol[ns18:Id=41]/ns18:DescripcionCorta"/>
        </ns1:GerenteCredito>
      </ns1:EquipoPayload>
      <ns1:EquipoEjecucionPayload/>
      <xsl:for-each select="$leccionesAprendidasDO/ns1:LeccionesAprendidasPayload/ns4:ParameterType">
        <ns4:ParameterType>
          <ns4:parameterName>
            <xsl:value-of select="ns4:parameterName"/>
          </ns4:parameterName>
          <ns4:parameterValue>
            <xsl:value-of select="ns4:parameterValue"/>
          </ns4:parameterValue>
        </ns4:ParameterType>
      </xsl:for-each>
    </ns1:LeccionesAprendidasPayload>
  </xsl:template>
</xsl:stylesheet>
