<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDetalleTransaccionDesembolso/ConsultarDetalleTransaccionDesembolso_db" name="ConsultarDetalleTransaccionDesembolso_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarDetalleTransaccionByIdDesembolso.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDetalleTransaccionDesembolso/ConsultarDetalleTransaccionDesembolso_db"/>
    <wsdl:binding name="ConsultarDetalleTransaccionDesembolso_db_ptt-binding" type="con:ConsultarDetalleTransaccionDesembolso_db_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarDetalleTransaccionDesembolso/ConsultarDetalleTransaccionDesembolso_db">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarDetalleTransaccionDesembolso_db">
            <soap:operation soapAction="ConsultarDetalleTransaccionDesembolso_db"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>