<wsdl:definitions
     name="EliminarOperacionFisicoDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarOperacionFisicoDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarOperacionFisicoDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarOperacionFisicoDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EliminarOperacionFisicoDB_plt" >
    <plt:role name="EliminarOperacionFisicoDB_role" >
      <plt:portType name="tns:EliminarOperacionFisicoDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarOperacionFisicoDB"
                schemaLocation="../XSD/EliminarOperacionFisicoDB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarOperacionFisicoDBInput_msg">
        <wsdl:part name="EliminarOperacionFisicoDBInput_msg" element="db:EliminarOperacionFisicoDBInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarOperacionFisicoDB_ptt">
        <wsdl:operation name="EliminarOperacionFisicoDB">
            <wsdl:input message="tns:EliminarOperacionFisicoDBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
