<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/EvaluacionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/EvaluacionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:evaMO="http://www.bcie.org/EvaluacionMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/EvaluacionMO" schemaLocation="../../Schema/EvaluacionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="CompensarEvaluacionRequestMessage">
    <part name="request" element="evaMO:CompensarEvaluacionRequest"/>
  </message>
  <message name="CompensarEvaluacionResponseMessage">
    <part name="response" element="evaMO:CompensarEvaluacionResponse"/>
  </message>
  <portType name="CompensarEvaluacionPT">
    <operation name="CompensarEvaluacion">
      <input message="tns:CompensarEvaluacionRequestMessage"/>
      <output message="tns:CompensarEvaluacionResponseMessage"/>
    </operation>
  </portType>
  <binding name="CompensarEvaluacionPTSOAP12Bnd" type="tns:CompensarEvaluacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CompensarEvaluacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/EvaluacionService/CompensarEvaluacion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>