<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDAModifyBuyerProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDAModifyBuyerProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N4="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDAModifyBuyerProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="JDAModifyBuyerProcessPXY">
      <plnk:role name="ModifyBuyerPType" portType="WL5G3N4:ModifyBuyerPType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDAModifyBuyerProcess" location="http://172.16.19.26:7004/Capabilities/Core/Buyer/BuyerEntitySvc/PS/JDAModifyBuyerProcessPXY?wsdl"/>
</wsdl:definitions>
