<wsdl:definitions name="ActualizarUsuarioReunion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarUsuarioReunion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarUsuarioReunion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarUsuarioReunion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarUsuarioReunion_plt">
    <plt:role name="ActualizarUsuarioReunion_role">
      <plt:portType name="tns:ActualizarUsuarioReunion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarUsuarioReunion" schemaLocation="../XSD/ActualizarUsuarioReunion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarUsuarioReunionInput_msg">
        <wsdl:part name="ActualizarUsuarioReunionInput_msg" element="db:ActualizarUsuarioReunionInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarUsuarioReunion_ptt">
        <wsdl:operation name="ActualizarUsuarioReunion">
            <wsdl:input message="tns:ActualizarUsuarioReunionInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>