<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/CreateOrder" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://www.agarcia.mx/ftpNadroCreateOrder" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="ediupack.xsd"/>
            <oracle-xsl-mapper:rootElement name="body" namespace="http://www.agarcia.mx/ftpNadroCreateOrder"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../MetaData/Components/EnterpriseObjectLibrary/EBO/PurchaseOrder/CreateOrderEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessCreateOrderEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/CreateOrder"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON OCT 26 13:11:54 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ProcessCreateOrderEBM>
         <tns:DataArea>
            <tns:CreateOrderEBO>
               <tns:FileHead>
                  <tns:RecordDesc>
                     <xsl:value-of select="&quot;FHEAD&quot;"/>
                  </tns:RecordDesc>
                  <tns:LineID>
                     <xsl:value-of select="/ns0:body/ns0:FHEAD/ns0:LineId"/>
                  </tns:LineID>
                  <tns:GentranID>
                     <xsl:value-of select="/ns0:body/ns0:FHEAD/ns0:GentranID"/>
                  </tns:GentranID>
               </tns:FileHead>
               <xsl:for-each select="/ns0:body/ns0:THEAD">
                  <tns:HeadOrder>
                     <tns:RecordDesc>
                        <xsl:value-of select="&quot;THEAD&quot;"/>
                     </tns:RecordDesc>
                     <tns:LineID>
                        <xsl:value-of select="ns0:LineId"/>
                     </tns:LineID>
                     <tns:TransactionNum>
                        <xsl:value-of select="ns0:TransactionNumber"/>
                     </tns:TransactionNum>
                     <tns:AcknowledgeType>
                        <xsl:value-of select="ns0:AcknowledgeType"/>
                     </tns:AcknowledgeType>
                     <tns:OrderNum>
                        <com:ID>
                           <xsl:value-of select="ns0:OrderNum"/>
                        </com:ID>
                     </tns:OrderNum>
                     <tns:WrittenDate>
                        <xsl:value-of select="ns0:WrittenDate"/>
                     </tns:WrittenDate>
                     <tns:SupplierNum>
                        <com:ID>
                           <xsl:value-of select="ns0:SupplierNumber"/>
                        </com:ID>
                     </tns:SupplierNum>
                     <tns:NotBeforeDate>
                        <xsl:value-of select="ns0:NotBeforeDAte"/>
                     </tns:NotBeforeDate>
                     <tns:NotAfterDate>
                        <xsl:value-of select="ns0:NotAfterDate"/>
                     </tns:NotAfterDate>
                     <tns:PurchaseType>
                        <xsl:value-of select="ns0:PurchaseType"/>
                     </tns:PurchaseType>
                     <tns:PickupDate>
                        <xsl:value-of select="ns0:PickupDate"/>
                     </tns:PickupDate>
                  </tns:HeadOrder>
                  <xsl:for-each select="/ns0:body/ns0:TITEM">
                  <tns:ItemOrder>
                     <tns:RecordDesc>
                        <xsl:value-of select="&quot;TITEM&quot;"/>
                     </tns:RecordDesc>
                     <tns:LineID>
                        <xsl:value-of select="ns0:LineId"/>
                     </tns:LineID>
                     <tns:TransactionNum>
                        <xsl:value-of select="ns0:TransactionNumber"/>
                     </tns:TransactionNum>
                     <tns:Item>
                        <com:ID>
                           <xsl:value-of select="ns0:Item"/>
                        </com:ID>
                     </tns:Item>
                     <tns:RefItem>
                        <xsl:value-of select="ns0:RefItem"/>
                     </tns:RefItem>
                     <tns:VendorCatalogNum>
                        <xsl:value-of select="ns0:VendorCaralogNumber"/>
                     </tns:VendorCatalogNum>
                     <tns:UnitCost>
                        <xsl:value-of select="ns0:UnitCost"/>
                     </tns:UnitCost>
                     <tns:LocationType>
                        <xsl:value-of select="ns0:LocationType"/>
                     </tns:LocationType>
                     <tns:ShipToLocation>
                        <xsl:value-of select="ns0:ShipToLocation"/>
                     </tns:ShipToLocation>
                     <tns:PickUpLocation>
                        <xsl:value-of select="ns0:PickUpLocation"/>
                     </tns:PickUpLocation>
                  </tns:ItemOrder>
               </xsl:for-each>
               </xsl:for-each>
               
               <xsl:for-each select="/ns0:body/ns0:TSHIP">
                  <tns:ShipOrder>
                     <tns:RecordDesc>
                        <xsl:value-of select="&quot;TSHIP&quot;"/>
                     </tns:RecordDesc>
                     <tns:LineID>
                        <xsl:value-of select="ns0:LineId"/>
                     </tns:LineID>
                     <tns:TransactionNum>
                        <xsl:value-of select="ns0:TransactionNumber"/>
                     </tns:TransactionNum>
                     <tns:LocationType>
                        <xsl:value-of select="ns0:LocationType"/>
                     </tns:LocationType>
                     <tns:shipLocation>
                        <xsl:value-of select="ns0:ShipToLocation"/>
                     </tns:shipLocation>
                     <tns:Quantity>
                        <xsl:value-of select="ns0:Quantity"/>
                     </tns:Quantity>
                  </tns:ShipOrder>
               </xsl:for-each>
               <xsl:for-each select="/ns0:body/ns0:TTAIL">
                  <tns:TailOrder>
                     <tns:RecordDesc>
                        <xsl:value-of select="&quot;TTAIL&quot;"/>
                     </tns:RecordDesc>
                     <tns:LineID>
                        <xsl:value-of select="ns0:LineId"/>
                     </tns:LineID>
                     <tns:TransactionNum>
                        <xsl:value-of select="ns0:TransactionNumber"/>
                     </tns:TransactionNum>
                     <tns:TransactionLines>
                        <xsl:value-of select="ns0:TransactionLines"/>
                     </tns:TransactionLines>
                  </tns:TailOrder>
               </xsl:for-each>
               <tns:FileTail>
                  <tns:RecordDesc>
                     <xsl:value-of select="&quot;FTAIL&quot;"/>
                  </tns:RecordDesc>
                  <tns:LineID>
                     <xsl:value-of select="/ns0:body/ns0:FTAIL/ns0:LineId"/>
                  </tns:LineID>
                  <tns:NumberLines>
                     <xsl:value-of select="/ns0:body/ns0:FTAIL/ns0:NumberOfLines"/>
                  </tns:NumberLines>
               </tns:FileTail>
            </tns:CreateOrderEBO>
         </tns:DataArea>
      </tns:ProcessCreateOrderEBM>
   </xsl:template>
</xsl:stylesheet>