<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCondicionByIdOperacion" name="ConsultarCondicionByIdOperacion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarCondicionByIdOperacion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCondicionByIdOperacion"/>
    <wsdl:binding name="ConsultarCondicionByIdOperacion_ptt-binding" type="con:ConsultarCondicionByIdOperacion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCondicionByIdOperacion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarCondicionByIdOperacion">
            <soap:operation soapAction="ConsultarCondicionByIdOperacion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>