<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/CrearActualizarLoteImplementacion" name="CrearActualizarLoteImplementacion_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CrearActualizarLoteImplementacion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/CrearActualizarLoteImplementacion"/>
    <wsdl:binding name="CrearActualizarLoteImplementacion_ptt-binding" type="cre:CrearActualizarLoteImplementacion_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/CrearActualizarLoteImplementacion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>