<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/EliminarEvaluacion" name="EliminarEvaluacion_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarEvaluacion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/EliminarEvaluacion"/>
    <wsdl:binding name="EliminarEvaluacion_ptt-binding" type="elim:EliminarEvaluacion_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/EliminarEvaluacion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarEvaluacion">
            <soap:operation soapAction="EliminarEvaluacion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>