<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns0="http://xmlns.banesco.com/eopt/PmtCardCrFinancingCan_V1.0"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns2="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:ns4="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoPmt="http://xmlns.banesco.com/eo/Pmt_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:eoChk="http://xmlns.banesco.com/eo/Chk_V1.0"
                xmlns:eoBank="http://xmlns.banesco.com/eo/Banking_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Fee_V1.0"
                xmlns:eoCard="http://xmlns.banesco.com/eo/Card_V1.0" xmlns:ns6="http://xmlns.banesco.com/eo/Payee_V1.0"
                xmlns:ns7="http://xmlns.banesco.com/eo/Bill_V1.0" xmlns:ns8="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Payment/PmtCardCrFinancingCan/PmtCardCrFinancingCan_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PmtCardCrFinancingCanRq"
                                       namespace="http://xmlns.banesco.com/eopt/PmtCardCrFinancingCan_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUL 02 15:53:20 GMT-05:00 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <MFL_EVERTEC350_XML_to_TEXT>
      <EVERTEC350>
        <Type>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "CODIGO", "TipoPago.ReversoPagoEspecial", "TIPO.PAGO", "0350" )'/>
        </Type>
        <CardIssuer></CardIssuer>
        <CardAcct></CardAcct>
        <CardNum>
          <xsl:value-of select="/ns0:PmtCardCrFinancingCanRq/ns0:Card/eoCard:CardKey/eoCard:CardNum"/>
        </CardNum>
        <FIIdent>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "T24", /ns0:PmtCardCrFinancingCanRq/ns0:FIData/eoBank:FIIdent, "GENERAL", "BU" )'/>
        </FIIdent>
        <AgencyIdent>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "T24", /ns0:PmtCardCrFinancingCanRq/ns0:FIData/eoBank:Agency/eoBank:AgencyIdent, "AGENCIA", "" )'/>
        </AgencyIdent>
        <CurCode>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "T24", /ns0:PmtCardCrFinancingCanRq/ns0:Pmt/eoPmt:CurAmt/ns8:CurCode, "GENERAL", "840" )'/>
        </CurCode>
        <xsl:choose>
          <xsl:when test="/ns0:PmtCardCrFinancingCanRq/ns0:Chk/eoChk:ChkIssueKey/eoChk:ChkNum/text() and /ns0:PmtCardCrFinancingCanRq/ns0:Chk/eoChk:ChkData/eoChk:FIData/eoBank:FIIdent != DVMFunctions:lookupValue ('Commons/dvm/EvertecMapping', 'CODIGO', 'CodCheque.Banesco', 'T24', '')">
            <PmtType>
              <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "CODIGO", "FormaPago.Cheque", "GENERAL", "" )'/>
            </PmtType>
          </xsl:when>
          <xsl:otherwise>
            <PmtType>
              <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "CODIGO", "FormaPago.Efectivo", "GENERAL", "" )'/>
            </PmtType>
          </xsl:otherwise>
        </xsl:choose>
        <Amt>
          <xsl:value-of select='translate (string (/ns0:PmtCardCrFinancingCanRq/ns0:Pmt/eoPmt:CurAmt/ns8:Amt ), ".", "" )'/>
        </Amt>
        <xsl:choose>
          <xsl:when test="/ns0:PmtCardCrFinancingCanRq/ns0:Chk/eoChk:ChkIssueKey/eoChk:ChkNum/text()">
            <ChkFIIdent>
              <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "T24", /ns0:PmtCardCrFinancingCanRq/ns0:Chk/eoChk:ChkData/eoChk:FIData/eoBank:FIIdent, "COD.CHEQUE", "" )'/>
            </ChkFIIdent>
            <ChkNum>
              <xsl:value-of select="/ns0:PmtCardCrFinancingCanRq/ns0:Chk/eoChk:ChkIssueKey/eoChk:ChkNum"/>
            </ChkNum>
          </xsl:when>
          <xsl:otherwise>
            <ChkFIIdent></ChkFIIdent>
            <ChkNum></ChkNum>
          </xsl:otherwise>
        </xsl:choose>
        <ContractNum>
          <xsl:value-of select="/ns0:PmtCardCrFinancingCanRq/ns0:Card/eoCard:FinancingInfo/eoCard:ContractNum"/>
        </ContractNum>
        <DebitId>
          <xsl:value-of select="/ns0:PmtCardCrFinancingCanRq/ns0:Pmt/eoPmt:PmtTrnDetail/ns5:DebitId"/>
        </DebitId>
        <xsl:choose>
          <xsl:when test="/ns0:PmtCardCrFinancingCanRq/ns0:Chk/eoChk:ChkIssueKey/eoChk:ChkNum/text()">
            <ChkPlace>
              <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "CODIGO", "CodPlazaCheque.Local", "PLAZA.CHEQUE", "" )'/>
            </ChkPlace>
          </xsl:when>
          <xsl:otherwise>
            <ChkPlace></ChkPlace>
          </xsl:otherwise>
        </xsl:choose>
        <TrnId>
          <xsl:value-of select="/ns0:PmtCardCrFinancingCanRq/ns0:Pmt/eoPmt:PmtTrnDetail/ns5:TrnKey/ns5:TrnId"/>
        </TrnId>
        <UserId>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/ServiceProperties", "CODE", "Evertec.User", "VALUE", "BAN00018")'/>
        </UserId>
        <FinancingTrnType>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/EvertecMapping", "CODIGO", "MovimientoExtra.Abono", "GENERAL", "" )'/>
        </FinancingTrnType>
        <C2></C2>
      </EVERTEC350>
    </MFL_EVERTEC350_XML_to_TEXT>
  </xsl:template>
</xsl:stylesheet>
