<wsdl:definitions
     name="ConsultarOtrosAdquisicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/Adquisicion/ConsultarOtrosAdquisicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/Adquisicion/ConsultarOtrosAdquisicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOtrosAdquisicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarOtrosAdquisicion_plt" >
    <plt:role name="ConsultarOtrosAdquisicion_role" >
      <plt:portType name="tns:ConsultarOtrosAdquisicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOtrosAdquisicion" schemaLocation="../Schemas/ConsultarOtrosAdquisicion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarOtrosAdquisicionInput_msg">
        <wsdl:part name="ConsultarOtrosAdquisicionInput_msg" element="db:ConsultarOtrosAdquisicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarOtrosAdquisicionOutputCollection_msg">
        <wsdl:part name="ConsultarOtrosAdquisicionOutputCollection" element="db:ConsultarOtrosAdquisicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarOtrosAdquisicion_ptt">
        <wsdl:operation name="ConsultarOtrosAdquisicion">
            <wsdl:input message="tns:ConsultarOtrosAdquisicionInput_msg"/>
            <wsdl:output message="tns:ConsultarOtrosAdquisicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
