<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultarAvisoAdquisicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/Adquisicion/ConsultarAvisoAdquisicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/Adquisicion/ConsultarAvisoAdquisicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAvisoAdquisicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="ConsultarAvisoAdquisicion_plt">
      <plt:role name="ConsultarAvisoAdquisicion_role">
         <plt:portType name="tns:ConsultarAvisoAdquisicion_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAvisoAdquisicion" schemaLocation="../Schemas/ConsultarAvisoAdquisicion.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ConsultarAvisoAdquisicionInput_msg">
      <wsdl:part name="ConsultarAvisoAdquisicionInput_msg" element="db:ConsultarAvisoAdquisicionInput"/>
   </wsdl:message>
   <wsdl:message name="ConsultarAvisoAdquisicionOutputCollection_msg">
      <wsdl:part name="ConsultarAvisoAdquisicionOutputCollection" element="db:ConsultarAvisoAdquisicionOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="ConsultarAvisoAdquisicion_ptt">
      <wsdl:operation name="ConsultarAvisoAdquisicion">
         <wsdl:input message="tns:ConsultarAvisoAdquisicionInput_msg"/>
         <wsdl:output message="tns:ConsultarAvisoAdquisicionOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
