<wsdl:definitions
     name="ConsultarAdjudicadosAdquisicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/Adquisicion/ConsultarAdjudicadosAdquisicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/Adquisicion/ConsultarAdjudicadosAdquisicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAdjudicadosAdquisicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarAdjudicadosAdquisicion_plt" >
    <plt:role name="ConsultarAdjudicadosAdquisicion_role" >
      <plt:portType name="tns:ConsultarAdjudicadosAdquisicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAdjudicadosAdquisicion" schemaLocation="../Schemas/ConsultarAdjudicadosAdquisicion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAdjudicadosAdquisicionInput_msg">
        <wsdl:part name="ConsultarAdjudicadosAdquisicionInput_msg" element="db:ConsultarAdjudicadosAdquisicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAdjudicadosAdquisicionOutputCollection_msg">
        <wsdl:part name="ConsultarAdjudicadosAdquisicionOutputCollection" element="db:ConsultarAdjudicadosAdquisicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAdjudicadosAdquisicion_ptt">
        <wsdl:operation name="ConsultarAdjudicadosAdquisicion">
            <wsdl:input message="tns:ConsultarAdjudicadosAdquisicionInput_msg"/>
            <wsdl:output message="tns:ConsultarAdjudicadosAdquisicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
