<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO" schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConfiguracionGestionCobroRequestMessage">
    <part name="request" element="confMO:ConfiguracionGestionCobroRequest"/>
  </message>
  <message name="ConfiguracionGestionCobroResponseMessage">
    <part name="response" element="confMO:ConfiguracionGestionCobroResponse"/>
  </message>
  <portType name="ConfiguracionGestionCobroPT">
    <operation name="ConfiguracionGestionCobro">
      <input message="tns:ConfiguracionGestionCobroRequestMessage"/>
      <output message="tns:ConfiguracionGestionCobroResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConfiguracionGestionCobroPTSOAP12Bnd" type="tns:ConfiguracionGestionCobroPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConfiguracionGestionCobro">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ConfiguracionProcesosService/ConfiguracionGestionCobro"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>