<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO">
  <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO" schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
</xsd:schema>
</wsdl:types>
  <!--<types>
    <xsd:schema targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService/types"
                elementFormDefault="qualified"/>
  </types>-->
  <wsdl:message name="requestConfiguracionSupervisionMessage">
    <wsdl:part name="request" element="confMO:configuracionSupervisionAmbientalSocialRequest"/>
  </wsdl:message>
  <wsdl:message name="responseConfiguracionSupervisionMessage">
    <wsdl:part name="response" element="confMO:configuracionSupervisionAmbientalSocialResponse"/>
  </wsdl:message>
  <portType name="ConfiguracionSupervisionPT">
    <operation name="configuracionSupervision">
      <input message="tns:requestConfiguracionSupervisionMessage"/>
      <output message="tns:responseConfiguracionSupervisionMessage"/>
    </operation>
  </portType>
  <binding name="ConfiguracionSupervisionPTSOAP12Bnd" type="tns:ConfiguracionSupervisionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="configuracionSupervision">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ConfiguracionProcesosService/configuracionSupervision"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>