<wsdl:definitions
     name="ConsultarDeclaracionJuradaByIdDeclaracion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarDeclaracionJurada/ConsultarDeclaracionJuradaByIdDeclaracion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarDeclaracionJurada/ConsultarDeclaracionJuradaByIdDeclaracion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDeclaracionJuradaByIdDeclaracion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarDeclaracionJuradaByIdDeclaracion_plt" >
    <plt:role name="ConsultarDeclaracionJuradaByIdDeclaracion_role" >
      <plt:portType name="tns:ConsultarDeclaracionJuradaByIdDeclaracion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDeclaracionJuradaByIdDeclaracion" schemaLocation="../XSD/ConsultarDeclaracionJuradaByIdDeclaracion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarDeclaracionJuradaByIdDeclaracionInput_msg">
        <wsdl:part name="ConsultarDeclaracionJuradaByIdDeclaracionInput_msg" element="db:ConsultarDeclaracionJuradaByIdDeclaracionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarDeclaracionJuradaByIdDeclaracionOutputCollection_msg">
        <wsdl:part name="ConsultarDeclaracionJuradaByIdDeclaracionOutputCollection" element="db:ConsultarDeclaracionJuradaByIdDeclaracionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarDeclaracionJuradaByIdDeclaracion_ptt">
        <wsdl:operation name="ConsultarDeclaracionJuradaByIdDeclaracion">
            <wsdl:input message="tns:ConsultarDeclaracionJuradaByIdDeclaracionInput_msg"/>
            <wsdl:output message="tns:ConsultarDeclaracionJuradaByIdDeclaracionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
