<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:correoMO="http://www.bcie.org/CorreoMO" xmlns:tns="http://xmlns.bcie.com/CorreoElectronicoService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="CorreoElectronico" targetNamespace="http://xmlns.bcie.com/CorreoElectronicoService">
<wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/Utilidades/EnviarCorreoElectronico/V1/Schema/CorreoElectronicoMO.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="requestEnviarCorreoElectronicoMessage">
<wsdl:part name="request" element="correoMO:enviarCorreoElectronicoRequest"/>
</wsdl:message>
<wsdl:message name="responseEnviarCorreoElectronicoMessage">
<wsdl:part name="response" element="correoMO:enviarCorreoElectronicoResponse"/>
</wsdl:message>
<wsdl:portType name="CorreoElectronicoPT">
<wsdl:operation name="enviarCorreoElectronico">
<wsdl:input message="tns:requestEnviarCorreoElectronicoMessage"/>
<wsdl:output message="tns:responseEnviarCorreoElectronicoMessage"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="CorreoElectronico12Bnd" type="tns:CorreoElectronicoPT">
<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="enviarCorreoElectronico">
<soap12:operation soapAction="http://xmlns.bcie.com/DocumentoService/enviarCorreoElectronico" style="document"/>
<wsdl:input>
<soap12:body parts="request" use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body parts="response" use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
</wsdl:definitions>
