<wsdl:definitions
     name="EliminarMontoOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarMontoOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarMontoOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EliminarMontoOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EliminarMontoOperacion_plt" >
    <plt:role name="EliminarMontoOperacion_role" >
      <plt:portType name="tns:EliminarMontoOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EliminarMontoOperacion" schemaLocation="../XSD/EliminarMontoOperacion_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="MontoOperacionCollection_msg">
        <wsdl:part name="MontoOperacionCollection" element="top:MontoOperacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="EliminarMontoOperacion_ptt">
        <wsdl:operation name="delete">
            <wsdl:input message="tns:MontoOperacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
