package org.bcie.fenix.common.model.vo;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 02 15:24:15 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminContactosVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdContacto,
        Nombre,
        CorreoElectronico,
        Cargo,
        Telefono,
        FechaRegistro,
        IdCliente,
        RecibeAvisoCobro;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDCONTACTO = AttributesEnum.IdContacto.index();
    public static final int NOMBRE = AttributesEnum.Nombre.index();
    public static final int CORREOELECTRONICO = AttributesEnum.CorreoElectronico.index();
    public static final int CARGO = AttributesEnum.Cargo.index();
    public static final int TELEFONO = AttributesEnum.Telefono.index();
    public static final int FECHAREGISTRO = AttributesEnum.FechaRegistro.index();
    public static final int IDCLIENTE = AttributesEnum.IdCliente.index();
    public static final int RECIBEAVISOCOBRO = AttributesEnum.RecibeAvisoCobro.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AdminContactosVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute IdContacto.
     * @return the IdContacto
     */
    public Long getIdContacto() {
        return (Long) getAttributeInternal(IDCONTACTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdContacto.
     * @param value value to set the  IdContacto
     */
    public void setIdContacto(Long value) {
        setAttributeInternal(IDCONTACTO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Nombre.
     * @return the Nombre
     */
    public String getNombre() {
        return (String) getAttributeInternal(NOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Nombre.
     * @param value value to set the  Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CorreoElectronico.
     * @return the CorreoElectronico
     */
    public String getCorreoElectronico() {
        return (String) getAttributeInternal(CORREOELECTRONICO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CorreoElectronico.
     * @param value value to set the  CorreoElectronico
     */
    public void setCorreoElectronico(String value) {
        setAttributeInternal(CORREOELECTRONICO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Cargo.
     * @return the Cargo
     */
    public String getCargo() {
        return (String) getAttributeInternal(CARGO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Cargo.
     * @param value value to set the  Cargo
     */
    public void setCargo(String value) {
        setAttributeInternal(CARGO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Telefono.
     * @return the Telefono
     */
    public String getTelefono() {
        return (String) getAttributeInternal(TELEFONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Telefono.
     * @param value value to set the  Telefono
     */
    public void setTelefono(String value) {
        setAttributeInternal(TELEFONO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FechaRegistro.
     * @return the FechaRegistro
     */
    public String getFechaRegistro() {
        return (String) getAttributeInternal(FECHAREGISTRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FechaRegistro.
     * @param value value to set the  FechaRegistro
     */
    public void setFechaRegistro(String value) {
        setAttributeInternal(FECHAREGISTRO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdCliente.
     * @return the IdCliente
     */
    public Long getIdCliente() {
        return (Long) getAttributeInternal(IDCLIENTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdCliente.
     * @param value value to set the  IdCliente
     */
    public void setIdCliente(Long value) {
        setAttributeInternal(IDCLIENTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecibeAvisoCobro.
     * @return the RecibeAvisoCobro
     */
    public Boolean getRecibeAvisoCobro() {
        return (Boolean) getAttributeInternal(RECIBEAVISOCOBRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RecibeAvisoCobro.
     * @param value value to set the  RecibeAvisoCobro
     */
    public void setRecibeAvisoCobro(Boolean value) {
        setAttributeInternal(RECIBEAVISOCOBRO, value);
    }
}

