package org.bcie.fenix.common.model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 14 16:31:00 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VcaTasaDesembolsoFlexcubeVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DescripcionTasa,
        Codigo,
        Descripcion,
        CodigoMoneda,
        CodigoBranch,
        ValorActual,
        FechaEfectiva,
        Autorizado,
        Registro;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DESCRIPCIONTASA = AttributesEnum.DescripcionTasa.index();
    public static final int CODIGO = AttributesEnum.Codigo.index();
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();
    public static final int CODIGOMONEDA = AttributesEnum.CodigoMoneda.index();
    public static final int CODIGOBRANCH = AttributesEnum.CodigoBranch.index();
    public static final int VALORACTUAL = AttributesEnum.ValorActual.index();
    public static final int FECHAEFECTIVA = AttributesEnum.FechaEfectiva.index();
    public static final int AUTORIZADO = AttributesEnum.Autorizado.index();
    public static final int REGISTRO = AttributesEnum.Registro.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VcaTasaDesembolsoFlexcubeVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute DescripcionTasa.
     * @return the DescripcionTasa
     */
    public String getDescripcionTasa() {
        return (String) getAttributeInternal(DESCRIPCIONTASA);
    }

    /**
     * Gets the attribute value for the calculated attribute Codigo.
     * @return the Codigo
     */
    public String getCodigo() {
        return (String) getAttributeInternal(CODIGO);
    }

    /**
     * Gets the attribute value for the calculated attribute Descripcion.
     * @return the Descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }

    /**
     * Gets the attribute value for the calculated attribute CodigoMoneda.
     * @return the CodigoMoneda
     */
    public String getCodigoMoneda() {
        return (String) getAttributeInternal(CODIGOMONEDA);
    }

    /**
     * Gets the attribute value for the calculated attribute CodigoBranch.
     * @return the CodigoBranch
     */
    public String getCodigoBranch() {
        return (String) getAttributeInternal(CODIGOBRANCH);
    }

    /**
     * Gets the attribute value for the calculated attribute ValorActual.
     * @return the ValorActual
     */
    public BigDecimal getValorActual() {
        return (BigDecimal) getAttributeInternal(VALORACTUAL);
    }

    /**
     * Gets the attribute value for the calculated attribute FechaEfectiva.
     * @return the FechaEfectiva
     */
    public Timestamp getFechaEfectiva() {
        return (Timestamp) getAttributeInternal(FECHAEFECTIVA);
    }

    /**
     * Gets the attribute value for the calculated attribute Autorizado.
     * @return the Autorizado
     */
    public String getAutorizado() {
        return (String) getAttributeInternal(AUTORIZADO);
    }

    /**
     * Gets the attribute value for the calculated attribute Registro.
     * @return the Registro
     */
    public String getRegistro() {
        return (String) getAttributeInternal(REGISTRO);
    }
}

