<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/CrearAvisoCorbo/CrearAvisoCobro" name="CrearAvisoCobro_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CrearAvisoCobro.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/CrearAvisoCorbo/CrearAvisoCobro"/>
    <wsdl:binding name="CrearAvisoCobro_ptt-binding" type="cre:CrearAvisoCobro_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/CrearAvisoCorbo/CrearAvisoCobro">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CrearAvisoCobro">
            <soap:operation soapAction="CrearAvisoCobro"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>