<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="casePrimary" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SupplierFindByIdApp/TranslateSupplier/casePrimary" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SupplierFindByIdApp/TranslateSupplier/casePrimary" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/casePrimary" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="casePrimary_plt">
      <plt:role name="casePrimary_role">
         <plt:portType name="tns:casePrimary_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/casePrimary" schemaLocation="../Schemas/casePrimary_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="casePrimarySelect_inputParameters">
      <wsdl:part name="casePrimarySelect_inputParameters" element="top:casePrimarySelect_idC2_appCodeC2InputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmSuppliersCollection_msg">
      <wsdl:part name="MdmSuppliersCollection" element="top:MdmSuppliersCollection"/>
   </wsdl:message>
   <wsdl:portType name="casePrimary_ptt">
      <wsdl:operation name="casePrimarySelect">
         <wsdl:input message="tns:casePrimarySelect_inputParameters"/>
         <wsdl:output message="tns:MdmSuppliersCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
