<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="TranslateSupplierProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Suppliers/TranslateSupplierProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Suppliers/TranslateSupplierProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" schemaLocation="../Schemas/oneCaseDb_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="TranslateSupplierProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:oneCaseDbSelect_idC1_appCodeC1_targetAppCodeC1InputParameters"/>
   </wsdl:message>
   <wsdl:message name="TranslateSupplierProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:MdmSuppliersCollection"/>
   </wsdl:message>
   <wsdl:portType name="TranslateSupplierProcess">
      <wsdl:operation name="translate">
         <wsdl:input message="client:TranslateSupplierProcessRequestMessage"/>
         <wsdl:output message="client:TranslateSupplierProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="TranslateSupplierProcess">
      <plnk:role name="TranslateSupplierProcessProvider" portType="client:TranslateSupplierProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
