<?binding.jca ActualizaContactosDB_db.jca?><wsdl:definitions name="ActualizaContactosDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Operaciones_BCIE/AdministraContacto/ActualizaContactosDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Operaciones_BCIE/AdministraContacto/ActualizaContactosDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizaContactosDB">
    <plt:partnerLinkType name="ActualizaContactosDB_plt">
        <plt:role name="ActualizaContactosDB_role">
            <plt:portType name="tns:ActualizaContactosDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizaContactosDB" schemaLocation="../XSD/ActualizarContacto_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ContactosCollection_msg">
        <wsdl:part name="ContactosCollection" element="top:ContactosCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizaContactosDB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:ContactosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>