<wsdl:definitions name="CrearOperacionAsociadaBD" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearOperacionAsociadaBD" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearOperacionAsociadaBD" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearOperacionAsociadaBD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearOperacionAsociadaBD_plt">
    <plt:role name="CrearOperacionAsociadaBD_role">
      <plt:portType name="tns:CrearOperacionAsociadaBD_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearOperacionAsociadaBD" schemaLocation="../XSD/CrearOperacionAsociadaBD_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="AsociadasCollection_msg">
        <wsdl:part name="AsociadasCollection" element="top:AsociadasCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearOperacionAsociadaBD_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:AsociadasCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>