<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoByOperacionProceso" name="ConsultarEquipoTrabajoByOperacionProceso_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarEquipoTrabajoByOperacionProceso.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoByOperacionProceso"/>
    <wsdl:binding name="ConsultarEquipoTrabajoByOperacionProceso_ptt-binding" type="con:ConsultarEquipoTrabajoByOperacionProceso_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoByOperacionProceso">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarEquipoTrabajoByOperacionProcesoSelect">
            <soap:operation soapAction="ConsultarEquipoTrabajoByOperacionProcesoSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>