<wsdl:definitions name="ConsultarEquipoTrabajoByOperacionProceso" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoByOperacionProceso" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEquipoTrabajoByOperacionProceso" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarEquipoTrabajoByOperacionProceso" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarEquipoTrabajoByOperacionProceso_plt">
    <plt:role name="ConsultarEquipoTrabajoByOperacionProceso_role">
      <plt:portType name="tns:ConsultarEquipoTrabajoByOperacionProceso_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarEquipoTrabajoByOperacionProceso"
                schemaLocation="../XSD/ConsultarEquipoTrabajoByOperacionProceso_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarEquipoTrabajoByOperacionProcesoSelect_inputParameters">
        <wsdl:part name="ConsultarEquipoTrabajoByOperacionProcesoSelect_inputParameters" element="top:ConsultarEquipoTrabajoByOperacionProcesoSelect_idOperacion_idProcesoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EquipoTrabajoCollection_msg">
        <wsdl:part name="EquipoTrabajoCollection" element="top:EquipoTrabajoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarEquipoTrabajoByOperacionProceso_ptt">
        <wsdl:operation name="ConsultarEquipoTrabajoByOperacionProcesoSelect">
            <wsdl:input message="tns:ConsultarEquipoTrabajoByOperacionProcesoSelect_inputParameters"/>
            <wsdl:output message="tns:EquipoTrabajoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>