<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://mx.agarcia.ea/Capabilities/Foundation/Party/SupplierEntitySvc" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:supp="http://mx.agarcia.ea/Capabilities/Core/Suppliers/CreateSupplierProcess/v1.0" xmlns:ns3="http://mx.agarcia.ea/Canonical/Commons/Languages/v1" xmlns:ns4="http://mx.agarcia.ea/Canonical/Commons/Types/v1" xmlns:ns7="http://mx.agarcia.ea/Canonical/Commons/Currencies/v1" xmlns:ns8="http://mx.agarcia.ea/Canonical/Commons/Countries/v1" xmlns:AGSH="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://mx.agarcia.ea/Canonical/Commons/Enums/v1" xmlns:ns2="http://mx.agarcia.ea/Canonical/Commons/LocationsCommon/v1" xmlns:ns5="http://mx.agarcia.ea/Canonical/Commons/Suppliers/v1" xmlns:ns6="http://mx.agarcia.ea/Canonical/Commons/Items/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:AGSM="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateSupplierProcess.WSDL"/>
            <oracle-xsl-mapper:rootElement name="createSupplierRequest" namespace="http://mx.agarcia.ea/Capabilities/Foundation/Party/SupplierEntitySvc"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateSupplierProcess.WSDL"/>
            <oracle-xsl-mapper:rootElement name="createSupplierRequest" namespace="http://mx.agarcia.ea/Capabilities/Foundation/Party/SupplierEntitySvc"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE JUN 04 16:41:35 CDT 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:createSupplierRequest>
         <ns0:suppliers>
            <ns5:supplier>
               <ns5:supplierID>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:supplierID"/>
               </ns5:supplierID>
               <ns5:name>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:name"/>
               </ns5:name>
               <ns5:contactName/>
               <ns5:contactPhone>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:contactPhone"/>
               </ns5:contactPhone>
               <ns5:contactTelex>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:contactTelex"/>
               </ns5:contactTelex>
               <ns5:contactFax>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:contactFax"/>
               </ns5:contactFax>
               <ns5:contactEmail>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:contactEmail"/>
               </ns5:contactEmail>
               <ns5:contactNameOrder>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:contactNameOrder"/>
               </ns5:contactNameOrder>
               <ns5:website>
                  <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:website"/>
               </ns5:website>
               <ns5:address>
                  <ns2:addres>
                     <ns2:City>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:City"/>
                     </ns2:City>
                     <ns2:territory TypeCode="{/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:territory/@TypeCode}">
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:territory"/>
                     </ns2:territory>
                     <ns2:postalCode>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:postalCode"/>
                     </ns2:postalCode>
                     <ns2:country Code="{/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:country/@Code}">
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:country"/>
                     </ns2:country>
                     <ns2:add1>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:add1"/>
                     </ns2:add1>
                     <ns2:add2>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:add2"/>
                     </ns2:add2>
                     <ns2:add3>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:add3"/>
                     </ns2:add3>
                     <ns2:addressType>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:addressType"/>
                     </ns2:addressType>
                     <ns2:territoryType>
                        <xsl:value-of select="/ns0:createSupplierRequest/ns0:suppliers/ns5:supplier/ns5:address/ns2:addres/ns2:territoryType"/>
                     </ns2:territoryType>
                  </ns2:addres>
               </ns5:address>
            </ns5:supplier>
         </ns0:suppliers>
      </ns0:createSupplierRequest>
   </xsl:template>
</xsl:stylesheet>