<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.com/ValidarOperacionProceso"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.com/ValidarOperacionProceso"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"              
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:valProOp="http://www.bcie.org/ValidarOperacionProcesoMO">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/ValidarOperacionProcesoMO"
                        schemaLocation="../../../ValidarOperacionProceso/V1/Schema/ValidarOperacionProcesoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="valProOp:requestValidarOperacionProceso"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="response" element="valProOp:responseValidarOperacionProceso"/>
    </wsdl:message>
    <wsdl:portType name="ValidarOperacionProceso_PT">
        <wsdl:operation name="ValidarOperacionProceso">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarOperacionProceso12Bnd" type="tns:ValidarOperacionProceso_PT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ValidarOperacionProceso">
            <soap12:operation style="document"
                              soapAction="http://www.bcie.com/ValidarOperacionProceso/ValidarOperacionProceso"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>