<!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><definitions targetNamespace="http://org/bcie/ws/middle/LIMITES.wsdl" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://org/bcie/ws/middle/LIMITES.wsdl" xmlns:lim="http://org/bcie/ws/middle/LIMITES.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://org/bcie/ws/middle/LIMITES.wsdl" schemaLocation="../XSD/XMLSchema_Limites.xsd"/>
        </xsd:schema>
    </types>
    <message name="MensajeLimitesRequest">
        <part name="request" element="lim:ValidarLimitesRequest"/>
    </message>
    <message name="MensajeLimitesResponse">
        <part name="response" element="lim:ValidarLimitesResponse"/>
    </message>
    <portType name="LimitesServicePort">
        <operation name="operacionValidarLimites">
            <input message="lim:MensajeLimitesRequest"/>
            <output message="lim:MensajeLimitesResponse"/>
        </operation>
    </portType>
    <binding name="LimitesBinding" type="lim:LimitesServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="operacionValidarLimites">
            <soap:operation style="document" soapAction="BcieLimitesService/operacionValidarLimites"/>
            <input>
                <soap:body use="literal" parts="request"/>
            </input>
            <output>
                <soap:body use="literal" parts="response"/>
            </output>
        </operation>
    </binding>
    <service name="LIMITES">
        <port name="LIMITES" binding="lim:LimitesBinding">
            <soap:address location="http://172.16.49.23:7001/MIDDLE_TPDWN/LIMITES"/>
        </port>
    </service>
</definitions>