<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="urn:CrearTreLineaCreditoAprobacion"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="urn:CrearTreLineaCreditoAprobacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CrearTreLineaCreditoAprobacion">
        <plnk:role name="CrearTreLineaCreditoAprobacionPT" portType="tns:CrearTreLineaCreditoAprobacionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:CrearTreLineaCreditoAprobacion" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/ADAPTER/CrearTreLineaCreditoAprobacionSAD.wsdl"/>
</wsdl:definitions>
