<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ComposicionesService"
     targetNamespace="http://www.bcie.org/DocumentoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/DocumentoMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ComposicionesService">
        <plnk:role name="ComposicionesServicePT" portType="tns:ComposicionesServicePT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/DocumentoMO" location="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Wsdl/ADAPTER/ComposicionesServiceSAD.wsdl"/>
</wsdl:definitions>
