<wsdl:definitions
     name="ActualizarTerminosEsp"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project21/ActualizarTerminosEsp"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project21/ActualizarTerminosEsp"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarTerminosEsp"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarTerminosEsp_plt" >
    <plt:role name="ActualizarTerminosEsp_role" >
      <plt:portType name="tns:ActualizarTerminosEsp_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarTerminosEsp" schemaLocation="../XSD/ActualizarTerminosEsp.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarTerminosEspInput_msg">
        <wsdl:part name="ActualizarTerminosEspInput_msg" element="db:ActualizarTerminosEspInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarTerminosEsp_ptt">
        <wsdl:operation name="ActualizarTerminosEsp">
            <wsdl:input message="tns:ActualizarTerminosEspInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
