<wsdl:definitions name="QueryStoreAbroadRmsDbReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreAbroadSOAApp/QueryStoreAbroadRmsDbReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreAbroadSOAApp/QueryStoreAbroadRmsDbReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/QueryStoreAbroadRmsDbReference" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryStoreAbroadRmsDbReference_plt">
    <plt:role name="QueryStoreAbroadRmsDbReference_role">
      <plt:portType name="tns:QueryStoreAbroadRmsDbReference_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/QueryStoreAbroadRmsDbReference" schemaLocation="QueryStoreAbroadRmsDbReference.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryStoreAbroadRmsDbReferenceInput_msg">
        <wsdl:part name="QueryStoreAbroadRmsDbReferenceInput_msg" element="db:QueryStoreAbroadRmsDbReferenceInput"/>
    </wsdl:message>
    <wsdl:message name="QueryStoreAbroadRmsDbReferenceOutputCollection_msg">
        <wsdl:part name="QueryStoreAbroadRmsDbReferenceOutputCollection" element="db:QueryStoreAbroadRmsDbReferenceOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryStoreAbroadRmsDbReference_ptt">
        <wsdl:operation name="QueryStoreAbroadRmsDbReference">
            <wsdl:input message="tns:QueryStoreAbroadRmsDbReferenceInput_msg"/>
            <wsdl:output message="tns:QueryStoreAbroadRmsDbReferenceOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>