<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO" schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="requestConfiguracionSeguimientoCobroMessage">
    <wsdl:part name="request" element="confMO:configuracionSeguimientoCobroRequest"/>
  </wsdl:message>
  <wsdl:message name="responseConfiguracionSeguimientoCobroMessage">
    <wsdl:part name="response" element="confMO:configuracionSeguimientoCobroResponse"/>
  </wsdl:message>
  <portType name="ConfiguracionSeguimientoCobroPT">
    <operation name="configuracionSeguimientoCobro">
      <input message="tns:requestConfiguracionSeguimientoCobroMessage"/>
      <output message="tns:responseConfiguracionSeguimientoCobroMessage"/>
    </operation>
  </portType>
  <binding name="ConfiguracionSeguimientoCobroPTSOAP12Bnd" type="tns:ConfiguracionSeguimientoCobroPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="configuracionSeguimientoCobro">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ConfiguracionProcesosService/configuracionSeguimientoCobro"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>