<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConfiguracionReasignarClienteSOR"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConfiguracionReasignarClienteSOR"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ConfiguracionReasignarClienteSOR"
     xmlns:inp1="http://www.bcie.org/ConfiguracionProcesosMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO" schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="ConfiguracionReasignarClienteIn_Msg" element="inp1:configuracionReasignarClienteRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="ConfiguracionReasignarClienteOut_Msg" element="inp1:configuracionReasignarClienteResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConfiguracionReasignarCliente_ptt">
        <wsdl:operation name="ConfiguracionReasignarCliente">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConfiguracionReasignarCliente_bind" type="tns:ConfiguracionReasignarCliente_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ConfiguracionReasignarCliente">
            <soap12:operation style="document" soapAction="ConfiguracionReasignarCliente" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConfiguracionReasignarClienteSOR"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConfiguracionReasignarClienteSOR"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
