<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO"
                  xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  name="ConfiguracionProcesos"
                  targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO"
                  schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestconfiguracionAprobacionmessage">
    <wsdl:part name="request" element="confMO:configuracionAprobacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseconfiguracionAprobacionmessage">
    <wsdl:part name="response" element="confMO:configuracionAprobacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConfiguracionAprobacionPT">
    <wsdl:operation name="configuracionAprobacion">
      <wsdl:input message="tns:requestconfiguracionAprobacionmessage"/>
      <wsdl:output message="tns:responseconfiguracionAprobacionmessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConfiguracionAprobacionPT12Bnd" type="tns:ConfiguracionAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="configuracionAprobacion">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ConfiguracionProcesosService/configuracionAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
