<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="urn:ActualizarAprobacionSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="urn:ActualizarAprobacionSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:ns2="http://www.bcie.org/AprobacionMO"
     xmlns:ns3="urn:CrearLineaCreditoSAD"
    >
    <plnk:partnerLinkType name="ActualizarAprobacionBPEL">
        <plnk:role name="ActualizarAprobacionPT" portType="tns:ActualizarAprobacionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:ActualizarAprobacionSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Aprobacion/V1/Wsdl/BPEL/ActualizarAprobacionSOR.wsdl"/>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <!--wsdl:import namespace="urn:CrearLineaCreditoSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/ADAPTER/CrearLineaCreditoSAD.wsdl"/-->
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="urn:ActualizarAprobacionSOR"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.oracle.com/bpel/extension"
             xmlns:ns2="http://www.bcie.org/AprobacionMO">
            <xsd:import namespace="http://www.bcie.org/AprobacionMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Aprobacion/V1/Schema/AprobacionMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
