<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConfiguracionProcesos"
     targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/ProductoMO"
    >
    <plnk:partnerLinkType name="ConfiguracionFormalizacion">
        <plnk:role name="ConfiguracionFormalizacionPT" portType="tns:ConfiguracionFormalizacionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/ConfiguracionProcesosService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/WSDL/BPEL/ConfiguracionFormalizacionSOR.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.bcie.org/ProductoMO">
            <xsd:import namespace="http://www.bcie.org/ProductoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioProducto/Producto/V1/Schema/ProductoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
