<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/CrearActualizarSolicitudDesembolso"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/CrearActualizarSolicitudDesembolso"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CrearActualizarSolicitudDesembolso_PS">
        <plnk:role name="CrearActualizarSolicitudDesembolso_PT" portType="tns:CrearActualizarSolicitudDesembolso_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/CrearActualizarSolicitudDesembolso" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/CrearActualizarSolicitudDesembolsoSAD.wsdl"/>
</wsdl:definitions>
