<wsdl:definitions name="CrearActualizarEquipoTrabajo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearActualizarEquipoTrabajo" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearActualizarEquipoTrabajo" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarEquipoTrabajo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearActualizarEquipoTrabajo_plt">
    <plt:role name="CrearActualizarEquipoTrabajo_role">
      <plt:portType name="tns:CrearActualizarEquipoTrabajo_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarEquipoTrabajo" schemaLocation="../XSD/CrearActualizarEquipoTrabajo_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EquipoTrabajoCollection_msg">
        <wsdl:part name="EquipoTrabajoCollection" element="top:EquipoTrabajoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearActualizarEquipoTrabajo_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EquipoTrabajoCollection_msg"/>
            <wsdl:output message="tns:EquipoTrabajoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>