<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoColorTranslation" name="caseTwoColorTranslation-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="caseTwoColorTranslation.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoColorTranslation"/>
    <wsdl:binding name="caseTwoColorTranslation_ptt-binding" type="cas:caseTwoColorTranslation_ptt" xmlns:cas="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoColorTranslation">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="caseTwoColorTranslationSelect">
            <soap:operation soapAction="caseTwoColorTranslationSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>