<wsdl:definitions name="DB_RMS_CREATESTYLE" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/DB_RMS_CREATESTYLE" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/DB_RMS_CREATESTYLE" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_RMS_CREATESTYLE" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/DB_RMS_CREATESTYLE" schemaLocation="DB_RMS_CREATESTYLE.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="DB_RMS_CREATESTYLE_ptt">
        <wsdl:operation name="DB_RMS_CREATESTYLE">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DB_RMS_CREATESTYLE_Binding" type="tns:DB_RMS_CREATESTYLE_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="DB_RMS_CREATESTYLE">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/DB_RMS_CREATESTYLE/DB_RMS_CREATESTYLE"/>
            <wsdl:input>
                <soap:body use="literal" parts="InputParameters"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="OutputParameters"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>