<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/NotificarCancelarOperacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/NotificarCancelarOperacion"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:notiMO="http://www.bcie.org/NotificarCancelarOperacionMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/NotificarCancelarOperacion/types" elementFormDefault="qualified">
      <xsd:import schemaLocation="../Schema/NotificarCancelarOperacionMO.xsd"
                  namespace="http://www.bcie.org/NotificarCancelarOperacionMO"/>
    </xsd:schema>
  </types>
  <message name="requestNotificarCancelarOperacionMessage">
    <part name="request" element="notiMO:requestNotificarCancelarOperacion"/>
  </message>
  <message name="responseNotificarCancelarOperacionMessage">
    <part name="response" element="notiMO:responseNotificarCancelarOperacion"/>
  </message>
  <portType name="NotificarCancelarOperacion_PT">
    <operation name="NotificarCancelarOperacion">
      <input message="tns:requestNotificarCancelarOperacionMessage"/>
      <output message="tns:responseNotificarCancelarOperacionMessage"/>
    </operation>
  </portType>
  <binding name="NotificarCancelarOperacion_PTSOAP12Binding" type="tns:NotificarCancelarOperacion_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="NotificarCancelarOperacion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/NotificarCancelarOperacion/NotificarCancelarOperacion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>