<wsdl:definitions name="CostChangeFindDetailsByIDBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/RMSCostChange/CostChangeFindDetailsByIDBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/RMSCostChange/CostChangeFindDetailsByIDBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CostChangeFindDetailsByIDBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CostChangeFindDetailsByIDBS_plt">
    <plt:role name="CostChangeFindDetailsByIDBS_role">
      <plt:portType name="tns:CostChangeFindDetailsByIDBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CostChangeFindDetailsByIDBS" schemaLocation="CostChangeFindDetailsByIDBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="CostChangeFindDetailsByIDBSSelect_inputParameters">
        <wsdl:part name="CostChangeFindDetailsByIDBSSelect_inputParameters" element="top:CostChangeFindDetailsByIDBSSelect_pCostChangeIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CostSuspSupHeadCollection_msg">
        <wsdl:part name="CostSuspSupHeadCollection" element="top:CostSuspSupHeadCollection"/>
    </wsdl:message>
    <wsdl:portType name="CostChangeFindDetailsByIDBS_ptt">
        <wsdl:operation name="CostChangeFindDetailsByIDBSSelect">
            <wsdl:input message="tns:CostChangeFindDetailsByIDBSSelect_inputParameters"/>
            <wsdl:output message="tns:CostSuspSupHeadCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>