<wsdl:definitions
     name="ConsultarBitacoraProcesoOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarBitacoraProcesoOperacion_plt" >
    <plt:role name="ConsultarBitacoraProcesoOperacion_role" >
      <plt:portType name="tns:ConsultarBitacoraProcesoOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoOperacion" schemaLocation="../XSD/ConsultarBitacoraProcesoOperacion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarBitacoraProcesoOperacionInput_msg">
        <wsdl:part name="ConsultarBitacoraProcesoOperacionInput_msg" element="db:ConsultarBitacoraProcesoOperacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarBitacoraProcesoOperacionOutputCollection_msg">
        <wsdl:part name="ConsultarBitacoraProcesoOperacionOutputCollection" element="db:ConsultarBitacoraProcesoOperacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarBitacoraProcesoOperacion_ptt">
        <wsdl:operation name="ConsultarBitacoraProcesoOperacion">
            <wsdl:input message="tns:ConsultarBitacoraProcesoOperacionInput_msg"/>
            <wsdl:output message="tns:ConsultarBitacoraProcesoOperacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
