Prompt ./Datos/BCIE.CATALOGO_UT_V_SUB_SECTOR_IBCIE.sql
     @ ./Datos/BCIE.CATALOGO_UT_V_SUB_SECTOR_IBCIE.sql
Prompt ./Datos/FENIX.TCA_SECTOR_AMBIENTAL.sql
     @ ./Datos/FENIX.TCA_SECTOR_AMBIENTAL.sql
