<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE_SECURITY/ADAPTADORES/verificarEstadoUsuario" name="verificarEstadoUsuario-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="verificarEstadoUsuario.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE_SECURITY/ADAPTADORES/verificarEstadoUsuario"/>
  <wsdl:binding name="verificarEstadoUsuario_ptt-binding" type="ver:verificarEstadoUsuario_ptt" xmlns:ver="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE_SECURITY/ADAPTADORES/verificarEstadoUsuario">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="verificarEstadoUsuario">
      <soap:operation soapAction="verificarEstadoUsuario"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>