<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnProcesoExcepcion_DB" name="ValidarEnProcesoExcepcion_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ValidarEnProcesoExcepcion_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnProcesoExcepcion_DB"/>
    <wsdl:binding name="ValidarEnProcesoExcepcion_DB_ptt-binding" type="val:ValidarEnProcesoExcepcion_DB_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarEnProcesoExcepcion_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ValidarEnProcesoExcepcion_DB">
            <soap:operation soapAction="ValidarEnProcesoExcepcion_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>