<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GenerarAvisoCobroDemandaV2SOR"
     targetNamespace="http://www.bcie.org/GestionCobroMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/GestionCobroMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="GenerarAvisoCobroDemandaV2">
        <plnk:role name="GenerarAvisoCobroDemandaV2PT" portType="tns:GenerarAvisoCobroDemandaV2PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/GestionCobroMO" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/GestionCobro/V1/Wsdl/BPEL/GenerarAvisoCobroDemandaV2SOR.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/GestionCobroMO" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/GestionCobro/V1/Wsdl/ADAPTER/CrearAvisoCobroV2SAD.wsdl"/>
</wsdl:definitions>
