<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/GestionCobroMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/GestionCobroMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/GenerarArchivo"
    >
    <plnk:partnerLinkType name="GenerarReciboPagoProceso">
        <plnk:role name="GenerarReciboPagoProcesoPT" portType="tns:GenerarReciboPagoProcesoPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/GestionCobroMO" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/GestionCobro/V1/Wsdl/BPEL/GenerarReciboPagoProcesoSOR.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/GenerarArchivo" schemaLocation="../XSD/Recuperacion.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
