<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BanescoServiceBusApp/Commons/Siscardbd"
                  name="Siscardbd-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="Siscardbd.wsdl"
               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BanescoServiceBusApp/Commons/Siscardbd"/>
  <wsdl:binding name="Siscardbd_ptt-binding" type="sis:Siscardbd_ptt"
                xmlns:sis="http://xmlns.oracle.com/pcbpel/adapter/db/BanescoServiceBusApp/Commons/Siscardbd">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="Siscardbd">
      <soap:operation soapAction="Siscardbd"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>