<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarFechaCargo" name="ConsultarFechaCargo_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarFechaCargo.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarFechaCargo"/>
    <wsdl:binding name="ConsultarFechaCargo_ptt-binding" type="con:ConsultarFechaCargo_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarFechaCargo">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarFechaCargo">
            <soap:operation soapAction="ConsultarFechaCargo"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>