<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseOneSizeTranslation" name="caseOneSizeTranslation-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="caseOneSizeTranslation.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseOneSizeTranslation"/>
    <wsdl:binding name="caseOneSizeTranslation_ptt-binding" type="cas:caseOneSizeTranslation_ptt" xmlns:cas="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseOneSizeTranslation">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="caseOneSizeTranslationSelect">
            <soap:operation soapAction="caseOneSizeTranslationSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>