<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ExtraOSBGreat/ADAPTADORES/ObtenerPlanAmortizacion" name="ObtenerPlanAmortizacion-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ObtenerPlanAmortizacion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ExtraOSBGreat/ADAPTADORES/ObtenerPlanAmortizacion"/>
    <wsdl:binding name="ObtenerPlanAmortizacion_ptt-binding" type="obt:ObtenerPlanAmortizacion_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/ExtraOSBGreat/ADAPTADORES/ObtenerPlanAmortizacion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerPlanAmortizacion">
            <soap:operation soapAction="ObtenerPlanAmortizacion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>