<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/AllocationApp/AllocationJMSReference" name="AllocationJMSReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AllocationJMSReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/AllocationApp/AllocationJMSReference"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="all:Produce_Message_ptt" xmlns:all="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/AllocationApp/AllocationJMSReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>