<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ClienteService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cliMO="http://www.bcie.org/ClienteMO"
             xmlns:tns="http://xmlns.bcie.com/ClienteService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                         xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ClienteMO"
                  schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestValidarClienteDuplicadoMessage">
    <part name="part" element="cliMO:ValidarClienteDuplicadoRequest"/>
  </message>
  <message name="responseValidarClienteDuplicadoMessage">
    <part name="part" element="cliMO:ValidarClienteDuplicadoResponse"/>
  </message>
  <portType name="ValidarClientePT">
    <operation name="ValidarCliente">
      <input message="tns:requestValidarClienteDuplicadoMessage"/>
      <output message="tns:responseValidarClienteDuplicadoMessage"/>
    </operation>
  </portType>
  <binding name="ValidarClientePT12Bnd" type="tns:ValidarClientePT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ValidarCliente">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ClienteService/ValidarCliente"/>
      <input>
        <soap12:body use="literal" parts="part"/>
      </input>
      <output>
        <soap12:body use="literal" parts="part"/>
      </output>
    </operation>
  </binding>
</definitions>