<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarUsuarioProcesoClienteSAD"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarUsuarioProcesoClienteSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarUsuarioProcesoClienteSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarUsuarioProcesoCliente">
        <plnk:role name="ConsultarUsuarioProcesoCliente_ptt" portType="tns:ConsultarUsuarioProcesoCliente_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarUsuarioProcesoClienteSAD"
         location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConsultarUsuarioProcesoCliente/V1/WSDL/ConsultarUsuarioProcesoClienteSAD.wsdl"/>
</wsdl:definitions>
