<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/CrearTBILineaCredito" name="CrearTBILineaCredito-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CrearTBILineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/CrearTBILineaCredito"/>
    <wsdl:binding name="CrearTBILineaCredito_ptt-binding" type="cre:CrearTBILineaCredito_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/CrearTBILineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>