<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:CrearActualizarOperacionProceso" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:CrearActualizarOperacionProceso" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wboc="http://www.bcie.org/CrearActualizarOperacionProcesoMO">
  <types>
    <xsd:schema targetNamespace="urn:CrearActualizarOperacionProceso/types" elementFormDefault="qualified"/>
    <xsd:schema>
      <xsd:import schemaLocation="../V1/Schema/CrearActualizarOperacionProcesoMO.xsd"
                  namespace="http://www.bcie.org/CrearActualizarOperacionProcesoMO"/>
    </xsd:schema>
  </types>
  <portType name="CrearActualizarOperacionProceso_PT">
    <operation name="CrearActualizarOperacionProceso">
      <input message="tns:requestCreaActualizarOperacionProcesoMessage"/>
      <output message="tns:responseCreaActualizarOperacionProcesoMessage"/>
    </operation>
  </portType>
  <message name="requestCreaActualizarOperacionProcesoMessage">
    <part name="request" element="wboc:CrearActualizarOperacionProcesoRequest"/>
  </message>
  <message name="responseCreaActualizarOperacionProcesoMessage">
    <part name="response" element="wboc:CrearActualizarOperacionProcesoResponse"/>
  </message>
  <binding name="CrearActualizarOperacionProceso_PTSOAP12Binding" type="tns:CrearActualizarOperacionProceso_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CrearActualizarOperacionProceso">
      <soap12:operation style="document"
                        soapAction="urn:CrearActualizarOperacionProceso/CrearActualizarOperacionProceso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>