<wsdl:definitions name="QueryAllocationDBRMSReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationDBRMSReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationDBRMSReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationDBRMSReference" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryAllocationDBRMSReference_plt">
    <plt:role name="QueryAllocationDBRMSReference_role">
      <plt:portType name="tns:QueryAllocationDBRMSReference_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationDBRMSReference" schemaLocation="../XSDs/QueryAllocationDBRMSReference_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryAllocationDBRMSReferenceSelect_inputParameters">
        <wsdl:part name="QueryAllocationDBRMSReferenceSelect_inputParameters" element="top:QueryAllocationDBRMSReferenceSelect_allocParam_itemParamInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaAllocVwCollection_msg">
        <wsdl:part name="XxSoaAllocVwCollection" element="top:XxSoaAllocVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryAllocationDBRMSReference_ptt">
        <wsdl:operation name="QueryAllocationDBRMSReferenceSelect">
            <wsdl:input message="tns:QueryAllocationDBRMSReferenceSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaAllocVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>