<wsdl:definitions name="QueryAllocationsByOrdStore" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdStore" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdStore" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationsByOrdStore" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryAllocationsByOrdStore_plt">
    <plt:role name="QueryAllocationsByOrdStore_role">
      <plt:portType name="tns:QueryAllocationsByOrdStore_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationsByOrdStore" schemaLocation="../XSDs/QueryAllocationsByOrdStore_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryAllocationsByOrdStoreSelect_inputParameters">
        <wsdl:part name="QueryAllocationsByOrdStoreSelect_inputParameters" element="top:QueryAllocationsByOrdStoreSelect_pOrderNo_pTiendaInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaAllocVwCollection_msg">
        <wsdl:part name="XxSoaAllocVwCollection" element="top:XxSoaAllocVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryAllocationsByOrdStore_ptt">
        <wsdl:operation name="QueryAllocationsByOrdStoreSelect">
            <wsdl:input message="tns:QueryAllocationsByOrdStoreSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaAllocVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>