<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByAllocIdSku" name="QueryAllocationsByAllocIdSku-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryAllocationsByAllocIdSku.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByAllocIdSku"/>
    <wsdl:binding name="QueryAllocationsByAllocIdSku_ptt-binding" type="quer:QueryAllocationsByAllocIdSku_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByAllocIdSku">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryAllocationsByAllocIdSkuSelect">
            <soap:operation soapAction="QueryAllocationsByAllocIdSkuSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>