<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdStore" name="QueryAllocationsByOrdStore-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="QueryAllocationsByOrdStore.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdStore"/>
  <wsdl:binding name="QueryAllocationsByOrdStore_ptt-binding" type="quer:QueryAllocationsByOrdStore_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdStore">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="QueryAllocationsByOrdStoreSelect">
      <soap:operation soapAction="QueryAllocationsByOrdStoreSelect"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>