<wsdl:definitions name="QueryAllocationsByOrdSkuLoc" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdSkuLoc" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AllocationApp/QueryAllocationsByOrdSkuLoc" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationsByOrdSkuLoc" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryAllocationsByOrdSkuLoc_plt">
    <plt:role name="QueryAllocationsByOrdSkuLoc_role">
      <plt:portType name="tns:QueryAllocationsByOrdSkuLoc_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationsByOrdSkuLoc" schemaLocation="../XSDs/QueryAllocationsByOrdSkuLoc_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryAllocationsByOrdSkuLocSelect_inputParameters">
        <wsdl:part name="QueryAllocationsByOrdSkuLocSelect_inputParameters" element="top:QueryAllocationsByOrdSkuLocSelect_OrderNoParam_skuParam_localOrigenParam_tiendaParamInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaAllocVwCollection_msg">
        <wsdl:part name="XxSoaAllocVwCollection" element="top:XxSoaAllocVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryAllocationsByOrdSkuLoc_ptt">
        <wsdl:operation name="QueryAllocationsByOrdSkuLocSelect">
            <wsdl:input message="tns:QueryAllocationsByOrdSkuLocSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaAllocVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>