<definitions targetNamespace="http://www.bcie.org/CrearActualizarNoObjecionSAD" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/CrearActualizarNoObjecionSAD" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:adqMO="http://www.bcie.org/AdquisicionMO">
 <types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/AdquisicionMO" schemaLocation="../../Schema/AdquisicionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestCrearNoObjecionPGAMessage">
    <part name="request" element="adqMO:CrearNoObjecionPGA_Request"/>
  </message>
  <message name="responseCrearNoObjecionPGAMessage">
    <part name="response" element="adqMO:CrearNoObjecionPGA_Response"/>
  </message>
  <portType name="CrearNoObjecionPGAPT">
    <operation name="CrearNoObjecionPGA">
    <input message="tns:requestCrearNoObjecionPGAMessage"/>
    <output message="tns:responseCrearNoObjecionPGAMessage"/>
    </operation>
  </portType>
  <binding name="CrearNoObjecionPGAPT12Bnd" type="tns:CrearNoObjecionPGAPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CrearNoObjecionPGA">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CrearActualizarNoObjecionSAD/CrearNoObjecionPGA"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>