<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarFuenteByCondicion" name="ConsultarFuenteByCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarFuenteByCondicion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarFuenteByCondicion"/>
    <wsdl:binding name="ConsultarFuenteByCondicion_ptt-binding" type="con:ConsultarFuenteByCondicion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarFuenteByCondicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarFuenteByCondicion">
            <soap:operation soapAction="ConsultarFuenteByCondicion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>