<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://xmlns.banesco.com/eopt/AcctLoanPartyInq_V1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://www.temenos.com/T24/ofs/Response"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon"
                xmlns:ns1="http://www.temenos.com/T24/ofs/BPAWSCUSTLOANCONSULTType"
                xmlns:ns7="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/WSBPACUSTLOANCONSULT/ConsultadeclienteporprestamoResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="BPAWSCUSTLOANCONSULTResponse"
                                       namespace="http://www.temenos.com/T24/ofs/Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanPartyInq/AcctLoanPartyInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctLoanPartyInqRs"
                                       namespace="http://xmlns.banesco.com/eopt/AcctLoanPartyInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JUN 27 08:48:47 GMT-05:00 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="statusCode"
                  select='DVMFunctions:lookupValue ("Commons/dvm/StatusMappingBcknd", "T24", /ns0:BPAWSCUSTLOANCONSULTResponse/ResponseCommon/Status, "CNCODE", "M0006" )'/>
    <tns:AcctLoanPartyInqRs>
      <xsl:if test='$statusCode = "M0000"'>
        <xsl:for-each select="/ns0:BPAWSCUSTLOANCONSULTResponse/BPAWSCUSTLOANCONSULT/gBPAWSCUSTLOANCONSULTDetailType/mBPAWSCUSTLOANCONSULTDetailType">
          <tns:AcctLoanPartyRel>
            <tns:AcctMember>
              <xsl:if test="COMPANYCODE/text()">
                <eoAcct:CompanyId>
                  <xsl:value-of select="COMPANYCODE"/>
                </eoAcct:CompanyId>
              </xsl:if>
              <xsl:if test="NumerodeEmpleado/text()">
                <eoAcct:EmployeeNumber>
                  <xsl:value-of select="NumerodeEmpleado"/>
                </eoAcct:EmployeeNumber>
              </xsl:if>
              <eoAcct:PartyKey>
                <xsl:if test="IDENTIFICACIONDELCLIENTE/text()">
                  <eoPar:IssuedIdentValue>
                    <xsl:value-of select="IDENTIFICACIONDELCLIENTE"/>
                  </eoPar:IssuedIdentValue>
                </xsl:if>
                <xsl:if test="CUSTOMERID/text()">
                  <eoPar:PartyId>
                    <xsl:value-of select="CUSTOMERID"/>
                  </eoPar:PartyId>
                </xsl:if>
              </eoAcct:PartyKey>
              <eoAcct:PartyRole>
                <xsl:if test="Roldelcliente/text()">
                  <ns5:Cod>
                    <xsl:value-of select="Roldelcliente"/>
                  </ns5:Cod>
                </xsl:if>
              </eoAcct:PartyRole>
            </tns:AcctMember>
            <tns:CreditAcctData>
              <xsl:if test="DISCOUNTCODE/text()">
                <eoAcct:DiscountCode>
                  <xsl:value-of select="DISCOUNTCODE"/>
                </eoAcct:DiscountCode>
              </xsl:if>
              <xsl:if test="BIWEEKLYAMT/text()">
                <eoAcct:CreditRegularPmt>
                  <eoAcct:Amt>
                    <xsl:if test="BIWEEKLYAMT/text()">
                      <ns5:Amt>
                        <xsl:value-of select="BIWEEKLYAMT"/>
                      </ns5:Amt>
                    </xsl:if>
                  </eoAcct:Amt>
                  <eoAcct:Freq>
                    <ns5:FreqValue>Biweekly</ns5:FreqValue>
                  </eoAcct:Freq>
                </eoAcct:CreditRegularPmt>
              </xsl:if>
              <xsl:if test="MONTHLYAMT/text()">
                <eoAcct:CreditRegularPmt>
                  <eoAcct:Amt>
                    <xsl:if test="MONTHLYAMT/text()">
                      <ns5:Amt>
                        <xsl:value-of select="MONTHLYAMT"/>
                      </ns5:Amt>
                    </xsl:if>
                  </eoAcct:Amt>
                  <eoAcct:Freq>
                    <ns5:FreqValue>Monthly</ns5:FreqValue>
                  </eoAcct:Freq>
                </eoAcct:CreditRegularPmt>
              </xsl:if>
            </tns:CreditAcctData>
          </tns:AcctLoanPartyRel>
        </xsl:for-each>
      </xsl:if>
      <tns:Status>
        <eoStatus:StatusCode>
          <xsl:value-of select="$statusCode"/>
        </eoStatus:StatusCode>
        <eoStatus:StatusDesc>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/StatusMappingBcknd", "T24", /ns0:BPAWSCUSTLOANCONSULTResponse/ResponseCommon/Status, "CNDESC", "FALLO EN LA OPERACION" )'/>
        </eoStatus:StatusDesc>
        <eoStatus:AdditionalStatus>
          <xsl:if test="/ns0:BPAWSCUSTLOANCONSULTResponse/ResponseCommon/Status/text()">
            <eoStatus:StatusCode>
              <xsl:value-of select="/ns0:BPAWSCUSTLOANCONSULTResponse/ResponseCommon/Status"/>
            </eoStatus:StatusCode>
          </xsl:if>
          <xsl:if test="/ns0:BPAWSCUSTLOANCONSULTResponse/ResponseCommon/Message/text()">
            <eoStatus:StatusDesc>
              <xsl:value-of select="/ns0:BPAWSCUSTLOANCONSULTResponse/ResponseCommon/Message"/>
            </eoStatus:StatusDesc>
          </xsl:if>
        </eoStatus:AdditionalStatus>
      </tns:Status>
    </tns:AcctLoanPartyInqRs>
  </xsl:template>
</xsl:stylesheet>
