<wsdl:definitions name="ConsultarClasificacionAmbiental_BS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClasificacionAmbiental_BS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarClasificacionAmbiental_BS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarClasificacionAmbiental_BS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarClasificacionAmbiental_BS_plt">
    <plt:role name="ConsultarClasificacionAmbiental_BS_role">
      <plt:portType name="tns:ConsultarClasificacionAmbiental_BS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarClasificacionAmbiental_BS" schemaLocation="../XSD/ConsultarClasificacionAmbiental_BS.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarClasificacionAmbiental_BSInput_msg">
        <wsdl:part name="ConsultarClasificacionAmbiental_BSInput_msg" element="db:ConsultarClasificacionAmbiental_BSInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarClasificacionAmbiental_BSOutputCollection_msg">
        <wsdl:part name="ConsultarClasificacionAmbiental_BSOutputCollection" element="db:ConsultarClasificacionAmbiental_BSOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarClasificacionAmbiental_BS_ptt">
        <wsdl:operation name="ConsultarClasificacionAmbiental_BS">
            <wsdl:input message="tns:ConsultarClasificacionAmbiental_BSInput_msg"/>
            <wsdl:output message="tns:ConsultarClasificacionAmbiental_BSOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>