

CREATE TABLE FENIX.TMP_ERROR_USUARIOS
(
  USUARIO_ROL  VARCHAR2(65 BYTE)
);
/

CREATE INDEX FENIX.USUARIO_ROL_ERROR_IND ON FENIX.TMP_ERROR_USUARIOS
(USUARIO_ROL);
/

CREATE TABLE FENIX.TMP_PARA_USUARIOS
(
  USUARIO_ROL  VARCHAR2(65 BYTE)
);
/

CREATE INDEX FENIX.USUARIO_ROL_IND ON FENIX.TMP_PARA_USUARIOS
(USUARIO_ROL);
/

CREATE INDEX FENIX.DESCRIPCION_IND ON FENIX.TCA_PLANTILLA_CORREO
(DESCRIPCION);
/