CREATE OR REPLACE PROCEDURE SP_CONTRATO_DESEM_PROX_PAGO (
	P_ID_MONEDA       		IN NUMBER,
	P_ID_OPERACION    		IN NUMBER,
	P_CONTRATO_DESEMBOLSO 	IN VARCHAR2,
	P_F_SOLICITUD      		IN DATE,
	P_F_PREPAGO       		IN DATE,	
	P_CODIGO_RES      		OUT NUMBER,
	P_MENSAJE         		OUT VARCHAR2,
	RECORDSET         		OUT SYS_REFCURSOR)
AS
  
BEGIN
	OPEN RECORDSET FOR
		SELECT ROWNUM ID, 
			VCD.CODIGO_LINEA_CREDITO NUMERO_LINEA_CREDITO,
			VCD.NUMERO_CONTRATO AS CONTRATO_DESEMBOLSO,
			VCD.FECHA_APERTURA AS FECHA_EFECTIVA,
			VCD.FECHA_VENCIMIENTO AS VENCIMIENTO,
			VFP.Fecha_Proximo_Pago AS PROXIMO_PAGO,
			CON.FECHA_FIRMA ESCRITURACION,
			LC.FONDO FONDO_CONTABLE,
			VCD.USER_REF_NO,  			-- Es mostrado en lugar del CONTRATO_DESEMBOLSO
			 '0' as Moneda,'0' as Capital_No_Vencido, '0' as Pago_total, '0' as Monto_prepago
		FROM CONTRATO CON, LINEA_CREDITO LC,
			(SELECT cad.Contract_Ref_No,
				due_date Fecha_Proximo_Pago
				FROM MIDDLE.FC_V_PLAN_PAGO CAD,	MIDDLE.FC_V_FECHA_SISTEMA cal
				WHERE cad.Due_Date >= cal.Today
				AND NVL (cad.Amount_Due, 0) - NVL (cad.Amount_Settled, 0) > 0
				--AND cad.Due_Date >= NVL ( TO_DATE(P_F_SOLICITUD, 'dd/MM/YYYY'), due_date)
				--AND cad.Due_Date <= NVL ( TO_DATE(P_F_PREPAGO, 'dd/MM/YYYY'), due_date)
                AND cad.Due_Date >= NVL ( P_F_SOLICITUD, cad.due_date)
                AND cad.Due_Date <= NVL ( P_F_PREPAGO, cad.due_date)                                
				GROUP BY cad.Contract_Ref_No, cad.Due_Date 
				ORDER BY cad.DUE_DATE) VFP, TCA_TIPO_MONEDA TTM, VTA_CONTRATO_DESEMBOLSO VCD
		WHERE CON.ID = LC.ID_CONTRATO
		AND VFP.CONTRACT_REF_NO = VCD.NUMERO_CONTRATO
		AND CON.ID_OPERACION = P_ID_OPERACION 
		AND TTM.COD_EXTERNO = VCD.CODIGO_MONEDA
		AND VCD.CODIGO_LINEA_CREDITO = LC.NUMERO_LINEA_CREDITO
		AND TTM.ID = NVL (P_ID_MONEDA, TTM.ID)
		AND VCD.MODULE_CODE = 'LD'
		AND VCD.PRODUCT_TYPE = 'L' 
		AND VCD.NUMERO_CONTRATO = P_CONTRATO_DESEMBOLSO;


EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
		P_CODIGO_RES := SQLCODE;
		P_MENSAJE := SQLERRM;
		DBMS_OUTPUT.PUT_LINE (SQLERRM);
   WHEN OTHERS
   THEN
		P_CODIGO_RES := SQLCODE;
		P_MENSAJE := SQLERRM;
		DBMS_OUTPUT.PUT_LINE (SQLERRM);

		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,
                                         NOMBRE_INSUMO,
                                         DESCRIPCION_ERROR,
                                         FECHA_REGISTRO)
		VALUES ('SP',
				'SP_CONTRATO_DESEM_PROX_PAGO',
                SUBSTR (P_MENSAJE, 1, 500),
                SYSDATE);

		COMMIT;
END;