create or replace PROCEDURE SP_CONSULTAR_COMISION_MOMENTO (
   P_ID_MOMENTO_COBRO  IN    T_NUMBER_TAB,
   P_ID_OPERACION  IN    T_NUMBER_TAB,
   P_CODIGO_RES     OUT NUMBER,
   P_MENSAJE        OUT VARCHAR2,
   RECORDSET        OUT SYS_REFCURSOR)
AS
BEGIN

OPEN RECORDSET FOR 
SELECT 
  COMI.ID AS ID_COMISION,
  COMI.ID_OPERACION,
  COMI.NOMBRE,
  COMI.DESCRIPCION AS DESCRIPCION_COMISION,
  COMI.ID_TCA_COMISION,
  COMI.ID_TCA_MONEDA,
  COMI.MONTO_COMISION,
  COMI.ID_TCA_MONTO_BASE,
  COMI.FECHA_VALOR,
  COMI.FECHA_VENCIMIENTO,
  COMI.FECHA_INICIO_CAPITAL,
  COMI.FECHA_INICIO_COMISION,
  COMI.ID_TCA_TIPO_FRECUENCIA,
  COMI.FRECUENCIA_PAGO,
  COMI.ID_TCA_FONDO,
  COMI.COMISION_COMPARTIDA,
  COMI.CODIGO_DESEMBOLSO,
  COMI.NUMERO_TESORERIA,
  COMI.CODIGO_CONTRATO,
  COMI.ID_TCA_TIPO_TASA,
  COMI.ID_TCA_BASE_CALCULO,
  COMI.RESPONSABLE_COMISION,
  COMI.ID_TCA_SUB_ESTADO_TCC,
  COMI.FECHA_REGISTRO AS FECHA_REGISTRO_COMISION,
  COMI.BAN_ESTATUS AS BAN_ESTATUS_COMISION,
  COMI.ID_COMISION_ENMENDADA,
  COMI.FECHA_ENMIENDA,
  COMI.BAN_SUGERIDA,
  TMC.ID          AS ID_MOMENTO_COBRO,
  TMC.DESCRIPCION AS DESCRIPCION_MOMENTO_COBRO,
  TMC.DESCRIPCION_CORTA AS DESCRIP_CORTA_MOMENTO_COBRO,
  TMC.BAN_ESTATUS AS BAN_ESTATUS_MOMENTO_COBRO,
  TMC.COD_EXTERNO AS COD_EXTERNO_MOMENTO_COBRO,
  TET.ID AS ID_TCA_ESTADO_TCC,
  TET.DESCRIPCION AS DESCRIPCION_ESTADO,
  TET.DESCRIPCION_CORTA AS DESCRIPCION_CORTA_ESTADO,
  TET.FECHA_REGISTRO AS FECHA_REGISTRO_ESTADO,
  TET.BAN_ESTATUS AS BAN_ESTATUS_ESTADO,
  TET.COD_EXTERNO AS COD_EXTERNO_ESTADO
FROM COMISION COMI
INNER JOIN TCA_MOMENTO_COBRO TMC
ON COMI.ID_TCA_MOMENTO_COBRO = TMC.ID
INNER JOIN TCA_ESTADO_TCC TET
ON COMI.ID_TCA_ESTADO_TCC = TET.ID
WHERE TET.ID != 6
AND COMI.ID_OPERACION IN (SELECT * FROM TABLE(P_ID_OPERACION))
AND TMC.ID IN (SELECT * FROM TABLE(P_ID_MOMENTO_COBRO));

P_CODIGO_RES := 0;

EXCEPTION
WHEN OTHERS THEN

P_CODIGO_RES := SQLCODE;

P_MENSAJE := SQLERRM;

END;
/