<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarBitacoraProcesoCliente"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarBitacoraProcesoCliente"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarBitacoraProcesoCliente"
     xmlns:inp1="http://www.bcie.org/CrearBitacoraProcesoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/CrearBitacoraProcesoMO" schemaLocation="../Schema/BitacoraProcesoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="ConsultarBitacoraProcesoClienteIn_Msg" element="inp1:ConsultarBitacoraProcesoClienteRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="ConsultarBitacoraProcesoClienteOut_Msg" element="inp1:ConsultarBitacoraProcesoClienteResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarBitacoraProcesoCliente_ptt">
        <wsdl:operation name="ConsultarBitacoraProcesoCliente">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsultarBitacoraProcesoCliente_bind" type="tns:ConsultarBitacoraProcesoCliente_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ConsultarBitacoraProcesoCliente">
            <soap12:operation style="document" soapAction="ConsultarBitacoraProcesoCliente" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarBitacoraProcesoCliente"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ConsultarBitacoraProcesoCliente"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
