<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1" xmlns:ns1="http://www.example.org"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns3="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PU01/ReasignacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ReasignacionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"/>
        <oracle-xsl-mapper:param name="payload"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/Evaluacion/V1/EvaluacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="EvaluacionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [FRI JAN 08 11:50:14 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:EvaluacionPayload>
      <tns:Header>
        <header:Operacion>
          <ns2:CodigoOperacion>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:CodigoOperacion"/>
          </ns2:CodigoOperacion>
          <ns2:NombreOperacion>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:NombreOperacion"/>
          </ns2:NombreOperacion>
          <ns2:ResponsableOperacion>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:ResponsableOperacion"/>
          </ns2:ResponsableOperacion>
          <ns2:CodigoCliente>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:CodigoCliente"/>
          </ns2:CodigoCliente>
          <ns2:NombreCliente>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:NombreCliente"/>
          </ns2:NombreCliente>
          <ns2:CodigoProducto>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:CodigoProducto"/>
          </ns2:CodigoProducto>
          <ns2:NombreProducto>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:NombreProducto"/>
          </ns2:NombreProducto>
          <ns2:MontoSolicitado>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:MontoSolicitado"/>
          </ns2:MontoSolicitado>
          <ns2:Pais>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Operacion/ns2:Pais"/>
          </ns2:Pais>
        </header:Operacion>
        <header:Tarea>
          <ns3:CodigoTarea>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns3:CodigoTarea"/>
          </ns3:CodigoTarea>
          <ns3:NombreTarea>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns3:NombreTarea"/>
          </ns3:NombreTarea>
          <ns3:CodigoRol>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns3:CodigoRol"/>
          </ns3:CodigoRol>
          <ns3:NombreRol>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns3:NombreRol"/>
          </ns3:NombreRol>
          <ns3:CodigoProceso>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns3:CodigoProceso"/>
          </ns3:CodigoProceso>
          <ns3:NombreProceso>
            <xsl:value-of select="/ns0:ReasignacionPayload/ns0:Header/header:Tarea/ns3:NombreProceso"/>
          </ns3:NombreProceso>
        </header:Tarea>
        <xsl:for-each select="/ns0:ReasignacionPayload/ns0:Header/parameter:ParameterType">
          <parameter:ParameterType>
            <parameter:parameterName>
              <xsl:value-of select="parameter:parameterName"/>
            </parameter:parameterName>
            <parameter:parameterValue>
              <xsl:value-of select="parameter:parameterValue"/>
            </parameter:parameterValue>
          </parameter:ParameterType>
        </xsl:for-each>
      </tns:Header>
    </tns:EvaluacionPayload>
  </xsl:template>
</xsl:stylesheet>
