<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="RMSFindSKU" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreateItem/CreateItemProcess/RMSFindSKU" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreateItem/CreateItemProcess/RMSFindSKU" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindSKU" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="RMSFindSKU_plt">
      <plt:role name="RMSFindSKU_role">
         <plt:portType name="tns:RMSFindSKU_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindSKU" schemaLocation="../Schemas/RMSFindSKU.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="RMSFindSKUInput_msg">
      <wsdl:part name="RMSFindSKUInput_msg" element="db:RMSFindSKUInput"/>
   </wsdl:message>
   <wsdl:message name="RMSFindSKUOutputCollection_msg">
      <wsdl:part name="RMSFindSKUOutputCollection" element="db:RMSFindSKUOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="RMSFindSKU_ptt">
      <wsdl:operation name="RMSFindSKU">
         <wsdl:input message="tns:RMSFindSKUInput_msg"/>
         <wsdl:output message="tns:RMSFindSKUOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
