<wsdl:definitions name="PROCreateSizeProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Items/PROCreateSizeProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Items/PROCreateSizeProcess/v1.0" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plnk:partnerLinkType name="PROCreateSizeProcess">
    <plnk:role name="PROCreateSizeProcessProvider" portType="client:PROCreateSizeProcess"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeEntity" schemaLocation="../Schemas/CreateSizeEntitySchema.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="PROCreateSizeProcessRequestMessage">
    <wsdl:part name="payload" element="ns1:createSizeRequest"/>
  </wsdl:message>
  <wsdl:message name="PROCreateSizeProcessResponseMessage">
    <wsdl:part name="payload" element="ns1:createSizeResponse"/>
  </wsdl:message>
  <wsdl:portType name="PROCreateSizeProcess">
    <wsdl:operation name="create">
      <wsdl:input message="client:PROCreateSizeProcessRequestMessage"/>
      <wsdl:output message="client:PROCreateSizeProcessResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PROCreateSizeProcessBinding" type="client:PROCreateSizeProcess">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="create">
      <soap:operation style="document" soapAction="create"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="procreatesizeprocess_client_ep">
    <wsdl:port name="PROCreateSizeProcess_pt" binding="client:PROCreateSizeProcessBinding">
      <soap:address location="http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/RetailOperMK/PROCreateSizeProcess/procreatesizeprocess_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>