<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://www.bcie.org/DesembolsoMO"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://www.bcie.org/ReglaTareaBO" xmlns:ns4="http://www.bcie.org/TerminoBO"
                xmlns:ns5="http://www.bcie.org/ReglaBO" xmlns:ns6="http://www.bcie.org/OperacionBO"
                xmlns:ns8="http://www.bcie.org/CommonBO" xmlns:ns9="http://www.bcie.org/ResultBO"
                xmlns:ns13="http://www.bcie.org/PropagarTransferenciaSOR/types"
                xmlns:ns15="http://www.bcie.org/LineaCreditoBO" xmlns:ns14="http://www.bcie.org/MatrizTCCBO"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:tns="http://www.bcie.org/PropagarTransferenciaSOR"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns2="http://www.bcie.org/CondicionBO" xmlns:ns3="http://www.bcie.org/ProductoBO"
                xmlns:ns7="http://www.bcie.org/DeclaracionJuradaBO" xmlns:ns10="http://www.bcie.org/DocumentoBO"
                xmlns:ns11="http://www.bcie.org/HerramientaCEBO" xmlns:ns12="http://www.bcie.org/ComisionBO"
                xmlns:ns16="http://www.bcie.org/CatalogoBO" xmlns:ns17="http://www.bcie.org/DesembolsoBO"
                xmlns:ns18="http://www.bcie.org/ContratoBO" xmlns:ns19="http://www.bcie.org/ClienteBO"
                xmlns:ns20="http://www.bcie.org/AtributoBO" xmlns:ns21="http://www.bcie.org/ErrorBO">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/PropagarTransferenciaSOR.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ConsultarTransferenciasBancariasByIdResponse"
                                       namespace="http://www.bcie.org/DesembolsoMO"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/PropagarTransferenciaSOR.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ConsultarInformacionReglasByIdResponse"
                                       namespace="http://www.bcie.org/DesembolsoMO"/>
        <oracle-xsl-mapper:param name="ConsultarInformacionReglaById_OutputVariable.response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/PropagarTransferenciaSOR.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CrearTransferenciaFLEXCUBERequest"
                                       namespace="http://www.bcie.org/DesembolsoMO"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI NOV 11 16:14:56 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="ConsultarInformacionReglaById_OutputVariable.response"/>
  <xsl:template match="/">
    <ns0:CrearTransferenciaFLEXCUBERequest>
      <ns0:ContratoDesembolso>
        <ns17:idDesembolso>
          <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:idDesembolso"/>
        </ns17:idDesembolso>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:idFacturador">
          <ns17:idFacturador>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:idFacturador"/>
          </ns17:idFacturador>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:producto">
          <ns17:producto>
            <ns3:idProducto>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:producto/ns3:idProducto"/>
            </ns3:idProducto>
            <ns3:descripcion>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:producto/ns3:descripcion"/>
            </ns3:descripcion>
            <ns3:descripcionCorta>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:producto/ns3:descripcionCorta"/>
            </ns3:descripcionCorta>
            <ns3:fechaRegistro>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:producto/ns3:fechaRegistro"/>
            </ns3:fechaRegistro>
            <ns3:codExterno>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:producto/ns3:codExterno"/>
            </ns3:codExterno>
          </ns17:producto>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:referencia">
          <ns17:referencia>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:referencia"/>
          </ns17:referencia>
        </xsl:if>
        <xsl:for-each select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:monto">
          <ns17:monto>
            <ns8:tipo>
              <xsl:if test="ns8:tipo/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="ns8:tipo/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="ns8:tipo/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="ns8:tipo/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="ns8:tipo/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="ns8:tipo/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns8:tipo/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="ns8:tipo/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="ns8:tipo/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="ns8:tipo/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns8:tipo>
            <xsl:if test="ns8:importe">
              <ns8:importe>
                <xsl:value-of select="ns8:importe"/>
              </ns8:importe>
            </xsl:if>
            <xsl:if test="ns8:moneda">
              <ns8:moneda>
                <xsl:if test="ns8:moneda/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns8:moneda/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns8:moneda/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns8:moneda/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns8:moneda/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns8:moneda/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns8:moneda/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns8:moneda/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns8:moneda/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns8:moneda/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns8:moneda>
            </xsl:if>
          </ns17:monto>
        </xsl:for-each>
        <ns17:estado>
          <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:Id">
            <ns16:Id>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:Id"/>
            </ns16:Id>
          </xsl:if>
          <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:Descripcion">
            <ns16:Descripcion>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:Descripcion"/>
            </ns16:Descripcion>
          </xsl:if>
          <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:DescripcionCorta">
            <ns16:DescripcionCorta>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:DescripcionCorta"/>
            </ns16:DescripcionCorta>
          </xsl:if>
          <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:estatus">
            <ns16:estatus>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:estatus"/>
            </ns16:estatus>
          </xsl:if>
          <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:codigoExterno">
            <ns16:codigoExterno>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estado/ns16:codigoExterno"/>
            </ns16:codigoExterno>
          </xsl:if>
        </ns17:estado>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:programado">
          <ns17:programado>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:programado"/>
          </ns17:programado>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaEstimadaDesembolsar">
          <ns17:fechaEstimadaDesembolsar>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaEstimadaDesembolsar"/>
          </ns17:fechaEstimadaDesembolsar>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaEfectiva">
          <ns17:fechaEfectiva>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaEfectiva"/>
          </ns17:fechaEfectiva>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaAsignacion">
          <ns17:fechaAsignacion>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaAsignacion"/>
          </ns17:fechaAsignacion>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaRegistro">
          <ns17:fechaRegistro>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaRegistro"/>
          </ns17:fechaRegistro>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaVencimiento">
          <ns17:fechaVencimiento>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaVencimiento"/>
          </ns17:fechaVencimiento>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estatus">
          <ns17:estatus>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:estatus"/>
          </ns17:estatus>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras">
          <ns17:condicionesFinancieras>
            <ns17:tasa>
              <ns17:tipo>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:tipo/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns17:tipo>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:fija">
                <ns17:fija>
                  <ns17:valor>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:fija/ns17:valor"/>
                  </ns17:valor>
                </ns17:fija>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable">
                <ns17:variable>
                  <ns17:tasaReferencia>
                    <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:Id">
                      <ns16:Id>
                        <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:Id"/>
                      </ns16:Id>
                    </xsl:if>
                    <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:Descripcion">
                      <ns16:Descripcion>
                        <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:Descripcion"/>
                      </ns16:Descripcion>
                    </xsl:if>
                    <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:DescripcionCorta">
                      <ns16:DescripcionCorta>
                        <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:DescripcionCorta"/>
                      </ns16:DescripcionCorta>
                    </xsl:if>
                    <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:estatus">
                      <ns16:estatus>
                        <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:estatus"/>
                      </ns16:estatus>
                    </xsl:if>
                    <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:codigoExterno">
                      <ns16:codigoExterno>
                        <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns16:codigoExterno"/>
                      </ns16:codigoExterno>
                    </xsl:if>
                    <ns17:valor>
                      <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:tasaReferencia/ns17:valor"/>
                    </ns17:valor>
                  </ns17:tasaReferencia>
                  <ns17:spread>
                    <ns17:valor>
                      <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:variable/ns17:spread/ns17:valor"/>
                    </ns17:valor>
                  </ns17:spread>
                </ns17:variable>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:especial">
                <ns17:especial>
                  <ns17:valor>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:tasa/ns17:especial/ns17:valor"/>
                  </ns17:valor>
                </ns17:especial>
              </xsl:if>
            </ns17:tasa>
            <ns17:fondo>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
              <xsl:for-each select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:fondo/ns17:Validador">
                <ns17:Validador>
                  <xsl:if test="ns16:Id">
                    <ns16:Id>
                      <xsl:value-of select="ns16:Id"/>
                    </ns16:Id>
                  </xsl:if>
                  <xsl:if test="ns16:Descripcion">
                    <ns16:Descripcion>
                      <xsl:value-of select="ns16:Descripcion"/>
                    </ns16:Descripcion>
                  </xsl:if>
                  <xsl:if test="ns16:DescripcionCorta">
                    <ns16:DescripcionCorta>
                      <xsl:value-of select="ns16:DescripcionCorta"/>
                    </ns16:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns16:estatus">
                    <ns16:estatus>
                      <xsl:value-of select="ns16:estatus"/>
                    </ns16:estatus>
                  </xsl:if>
                  <xsl:if test="ns16:codigoExterno">
                    <ns16:codigoExterno>
                      <xsl:value-of select="ns16:codigoExterno"/>
                    </ns16:codigoExterno>
                  </xsl:if>
                </ns17:Validador>
              </xsl:for-each>
            </ns17:fondo>
            <ns17:baseCalculo>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:condicionesFinancieras/ns17:baseCalculo/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns17:baseCalculo>
          </ns17:condicionesFinancieras>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:idLinea">
          <ns17:idLinea>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:idLinea"/>
          </ns17:idLinea>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:recursosExternos">
          <ns17:recursosExternos>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:recursosExternos"/>
          </ns17:recursosExternos>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:cuentaCliente">
          <ns17:cuentaCliente>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:cuentaCliente"/>
          </ns17:cuentaCliente>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaDisponibilidadFondos">
          <ns17:fechaDisponibilidadFondos>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:fechaDisponibilidadFondos"/>
          </ns17:fechaDisponibilidadFondos>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:origenTransferenciaCte">
          <ns17:origenTransferenciaCte>
            <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:origenTransferenciaCte"/>
          </ns17:origenTransferenciaCte>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa">
          <ns17:Programa>
            <ns11:LineaFinanciera>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:LineaFinanciera/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns11:LineaFinanciera>
            <ns11:DestinoFinanciamiento>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:DestinoFinanciamiento/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns11:DestinoFinanciamiento>
            <ns11:ModalidadFinanciamiento>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ModalidadFinanciamiento/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns11:ModalidadFinanciamiento>
            <ns11:HerramientaCE>
              <ns11:ActividadEconomica>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:ActividadEconomica/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns11:ActividadEconomica>
              <ns11:EjeEstrategico>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:EjeEstrategico/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns11:EjeEstrategico>
              <ns11:AreaFocalizacion>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:HerramientaCE/ns11:AreaFocalizacion/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns11:AreaFocalizacion>
            </ns11:HerramientaCE>
            <ns11:ClasificacionGeneral>
              <ns11:SectorMercado>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorMercado/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns11:SectorMercado>
              <ns11:SectorInstitucional>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Programa/ns11:ClasificacionGeneral/ns11:SectorInstitucional/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns11:SectorInstitucional>
            </ns11:ClasificacionGeneral>
          </ns17:Programa>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso">
          <ns17:EstimadoDesembolso>
            <ns17:Plazo>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Plazo"/>
            </ns17:Plazo>
            <ns17:Frecuencia>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:EstimadoDesembolso/ns17:Frecuencia/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns17:Frecuencia>
          </ns17:EstimadoDesembolso>
        </xsl:if>
        <xsl:if test="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion">
          <ns17:Utilizacion>
            <ns15:idFuente>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:idFuente"/>
            </ns15:idFuente>
            <ns15:idLineaCredito>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:idLineaCredito"/>
            </ns15:idLineaCredito>
            <ns15:idLineaPasiva>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:idLineaPasiva"/>
            </ns15:idLineaPasiva>
            <ns15:codigoLineaPasiva>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:codigoLineaPasiva"/>
            </ns15:codigoLineaPasiva>
            <ns15:idFacturadorLineaPasiva>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:idFacturadorLineaPasiva"/>
            </ns15:idFacturadorLineaPasiva>
            <ns15:idFondo>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:idFondo"/>
            </ns15:idFondo>
            <ns15:Descripcion>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:Descripcion"/>
            </ns15:Descripcion>
            <ns15:FechaObtenido>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:FechaObtenido"/>
            </ns15:FechaObtenido>
            <ns15:MontoAsignado>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:MontoAsignado"/>
            </ns15:MontoAsignado>
            <ns15:montoDisponible>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:montoDisponible"/>
            </ns15:montoDisponible>
            <xsl:for-each select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:Monto">
              <ns15:Monto>
                <ns8:tipo>
                  <xsl:if test="ns8:tipo/ns16:Id">
                    <ns16:Id>
                      <xsl:value-of select="ns8:tipo/ns16:Id"/>
                    </ns16:Id>
                  </xsl:if>
                  <xsl:if test="ns8:tipo/ns16:Descripcion">
                    <ns16:Descripcion>
                      <xsl:value-of select="ns8:tipo/ns16:Descripcion"/>
                    </ns16:Descripcion>
                  </xsl:if>
                  <xsl:if test="ns8:tipo/ns16:DescripcionCorta">
                    <ns16:DescripcionCorta>
                      <xsl:value-of select="ns8:tipo/ns16:DescripcionCorta"/>
                    </ns16:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns8:tipo/ns16:estatus">
                    <ns16:estatus>
                      <xsl:value-of select="ns8:tipo/ns16:estatus"/>
                    </ns16:estatus>
                  </xsl:if>
                  <xsl:if test="ns8:tipo/ns16:codigoExterno">
                    <ns16:codigoExterno>
                      <xsl:value-of select="ns8:tipo/ns16:codigoExterno"/>
                    </ns16:codigoExterno>
                  </xsl:if>
                </ns8:tipo>
                <xsl:if test="ns8:importe">
                  <ns8:importe>
                    <xsl:value-of select="ns8:importe"/>
                  </ns8:importe>
                </xsl:if>
                <xsl:if test="ns8:moneda">
                  <ns8:moneda>
                    <xsl:if test="ns8:moneda/ns16:Id">
                      <ns16:Id>
                        <xsl:value-of select="ns8:moneda/ns16:Id"/>
                      </ns16:Id>
                    </xsl:if>
                    <xsl:if test="ns8:moneda/ns16:Descripcion">
                      <ns16:Descripcion>
                        <xsl:value-of select="ns8:moneda/ns16:Descripcion"/>
                      </ns16:Descripcion>
                    </xsl:if>
                    <xsl:if test="ns8:moneda/ns16:DescripcionCorta">
                      <ns16:DescripcionCorta>
                        <xsl:value-of select="ns8:moneda/ns16:DescripcionCorta"/>
                      </ns16:DescripcionCorta>
                    </xsl:if>
                    <xsl:if test="ns8:moneda/ns16:estatus">
                      <ns16:estatus>
                        <xsl:value-of select="ns8:moneda/ns16:estatus"/>
                      </ns16:estatus>
                    </xsl:if>
                    <xsl:if test="ns8:moneda/ns16:codigoExterno">
                      <ns16:codigoExterno>
                        <xsl:value-of select="ns8:moneda/ns16:codigoExterno"/>
                      </ns16:codigoExterno>
                    </xsl:if>
                  </ns8:moneda>
                </xsl:if>
              </ns15:Monto>
            </xsl:for-each>
            <ns15:NumeroAsignacion>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:NumeroAsignacion"/>
            </ns15:NumeroAsignacion>
            <ns15:Comentario>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:Comentario"/>
            </ns15:Comentario>
            <ns15:idContrato>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:idContrato"/>
            </ns15:idContrato>
            <ns15:FechaRegistro>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:FechaRegistro"/>
            </ns15:FechaRegistro>
            <ns15:Estado>
              <xsl:value-of select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Utilizacion/ns15:Estado"/>
            </ns15:Estado>
          </ns17:Utilizacion>
        </xsl:if>
        <xsl:for-each select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Cargo">
          <ns17:Cargo>
            <xsl:if test="ns16:Id">
              <ns16:Id>
                <xsl:value-of select="ns16:Id"/>
              </ns16:Id>
            </xsl:if>
            <xsl:if test="ns16:Descripcion">
              <ns16:Descripcion>
                <xsl:value-of select="ns16:Descripcion"/>
              </ns16:Descripcion>
            </xsl:if>
            <xsl:if test="ns16:DescripcionCorta">
              <ns16:DescripcionCorta>
                <xsl:value-of select="ns16:DescripcionCorta"/>
              </ns16:DescripcionCorta>
            </xsl:if>
            <xsl:if test="ns16:estatus">
              <ns16:estatus>
                <xsl:value-of select="ns16:estatus"/>
              </ns16:estatus>
            </xsl:if>
            <xsl:if test="ns16:codigoExterno">
              <ns16:codigoExterno>
                <xsl:value-of select="ns16:codigoExterno"/>
              </ns16:codigoExterno>
            </xsl:if>
            <ns17:Monto>
              <ns8:tipo>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns8:tipo>
              <xsl:if test="ns17:Monto/ns8:importe">
                <ns8:importe>
                  <xsl:value-of select="ns17:Monto/ns8:importe"/>
                </ns8:importe>
              </xsl:if>
              <xsl:if test="ns17:Monto/ns8:moneda">
                <ns8:moneda>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:Id">
                    <ns16:Id>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:Id"/>
                    </ns16:Id>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:Descripcion">
                    <ns16:Descripcion>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:Descripcion"/>
                    </ns16:Descripcion>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:DescripcionCorta">
                    <ns16:DescripcionCorta>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:DescripcionCorta"/>
                    </ns16:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:estatus">
                    <ns16:estatus>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:estatus"/>
                    </ns16:estatus>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:codigoExterno">
                    <ns16:codigoExterno>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:codigoExterno"/>
                    </ns16:codigoExterno>
                  </xsl:if>
                </ns8:moneda>
              </xsl:if>
            </ns17:Monto>
            <ns17:FechaRegistro>
              <xsl:value-of select="ns17:FechaRegistro"/>
            </ns17:FechaRegistro>
            <ns17:Status>
              <xsl:value-of select="ns17:Status"/>
            </ns17:Status>
            <ns17:SoloLectura>
              <xsl:value-of select="ns17:SoloLectura"/>
            </ns17:SoloLectura>
            <xsl:if test="ns17:TCC">
              <ns17:TCC>
                <ns14:id>
                  <xsl:value-of select="ns17:TCC/ns14:id"/>
                </ns14:id>
                <ns14:tipo>
                  <xsl:value-of select="ns17:TCC/ns14:tipo"/>
                </ns14:tipo>
                <ns14:estado>
                  <xsl:value-of select="ns17:TCC/ns14:estado"/>
                </ns14:estado>
                <ns14:subEstado>
                  <xsl:value-of select="ns17:TCC/ns14:subEstado"/>
                </ns14:subEstado>
              </ns17:TCC>
            </xsl:if>
          </ns17:Cargo>
        </xsl:for-each>
        <xsl:for-each select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Comision">
          <ns17:Comision>
            <ns12:idComision>
              <xsl:value-of select="ns12:idComision"/>
            </ns12:idComision>
            <ns12:idOperacion>
              <xsl:value-of select="ns12:idOperacion"/>
            </ns12:idOperacion>
            <xsl:if test="ns12:nombre">
              <ns12:nombre>
                <xsl:value-of select="ns12:nombre"/>
              </ns12:nombre>
            </xsl:if>
            <xsl:if test="ns12:descripcion">
              <ns12:descripcion>
                <xsl:value-of select="ns12:descripcion"/>
              </ns12:descripcion>
            </xsl:if>
            <xsl:if test="ns12:tipoComision">
              <ns12:tipoComision>
                <xsl:if test="ns12:tipoComision/ns12:idCatComision">
                  <ns12:idCatComision>
                    <xsl:value-of select="ns12:tipoComision/ns12:idCatComision"/>
                  </ns12:idCatComision>
                </xsl:if>
                <ns12:descripcion>
                  <xsl:value-of select="ns12:tipoComision/ns12:descripcion"/>
                </ns12:descripcion>
                <ns12:descripcionCorta>
                  <xsl:value-of select="ns12:tipoComision/ns12:descripcionCorta"/>
                </ns12:descripcionCorta>
                <xsl:if test="ns12:tipoComision/ns12:idTipoComision">
                  <ns12:idTipoComision>
                    <xsl:if test="ns12:tipoComision/ns12:idTipoComision/ns16:Id">
                      <ns16:Id>
                        <xsl:value-of select="ns12:tipoComision/ns12:idTipoComision/ns16:Id"/>
                      </ns16:Id>
                    </xsl:if>
                    <xsl:if test="ns12:tipoComision/ns12:idTipoComision/ns16:Descripcion">
                      <ns16:Descripcion>
                        <xsl:value-of select="ns12:tipoComision/ns12:idTipoComision/ns16:Descripcion"/>
                      </ns16:Descripcion>
                    </xsl:if>
                    <xsl:if test="ns12:tipoComision/ns12:idTipoComision/ns16:DescripcionCorta">
                      <ns16:DescripcionCorta>
                        <xsl:value-of select="ns12:tipoComision/ns12:idTipoComision/ns16:DescripcionCorta"/>
                      </ns16:DescripcionCorta>
                    </xsl:if>
                    <xsl:if test="ns12:tipoComision/ns12:idTipoComision/ns16:estatus">
                      <ns16:estatus>
                        <xsl:value-of select="ns12:tipoComision/ns12:idTipoComision/ns16:estatus"/>
                      </ns16:estatus>
                    </xsl:if>
                    <xsl:if test="ns12:tipoComision/ns12:idTipoComision/ns16:codigoExterno">
                      <ns16:codigoExterno>
                        <xsl:value-of select="ns12:tipoComision/ns12:idTipoComision/ns16:codigoExterno"/>
                      </ns16:codigoExterno>
                    </xsl:if>
                  </ns12:idTipoComision>
                </xsl:if>
                <ns12:esEditableEnFormalizacion>
                  <xsl:value-of select="ns12:tipoComision/ns12:esEditableEnFormalizacion"/>
                </ns12:esEditableEnFormalizacion>
                <ns12:requiereValidarCOFI>
                  <xsl:value-of select="ns12:tipoComision/ns12:requiereValidarCOFI"/>
                </ns12:requiereValidarCOFI>
                <ns12:sePuedeDispensar>
                  <xsl:value-of select="ns12:tipoComision/ns12:sePuedeDispensar"/>
                </ns12:sePuedeDispensar>
                <ns12:seRegistraEnFlexCube>
                  <xsl:value-of select="ns12:tipoComision/ns12:seRegistraEnFlexCube"/>
                </ns12:seRegistraEnFlexCube>
                <ns12:esPlantilla>
                  <xsl:value-of select="ns12:tipoComision/ns12:esPlantilla"/>
                </ns12:esPlantilla>
                <ns12:idComisionPrecarga>
                  <xsl:value-of select="ns12:tipoComision/ns12:idComisionPrecarga"/>
                </ns12:idComisionPrecarga>
                <ns12:fechaRegistro>
                  <xsl:value-of select="ns12:tipoComision/ns12:fechaRegistro"/>
                </ns12:fechaRegistro>
                <ns12:estado>
                  <xsl:value-of select="ns12:tipoComision/ns12:estado"/>
                </ns12:estado>
                <ns12:codigoExterno>
                  <xsl:value-of select="ns12:tipoComision/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </ns12:tipoComision>
            </xsl:if>
            <xsl:if test="ns12:moneda">
              <ns12:moneda>
                <xsl:if test="ns12:moneda/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns12:moneda/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns12:moneda/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns12:moneda/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns12:moneda/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns12:moneda/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns12:moneda/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns12:moneda/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns12:moneda/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns12:moneda/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns12:moneda>
            </xsl:if>
            <xsl:if test="ns12:montoComision">
              <ns12:montoComision>
                <xsl:value-of select="ns12:montoComision"/>
              </ns12:montoComision>
            </xsl:if>
            <xsl:if test="ns12:montoBase">
              <ns12:montoBase>
                <xsl:if test="ns12:montoBase/ns12:idMontoBase">
                  <ns12:idMontoBase>
                    <xsl:value-of select="ns12:montoBase/ns12:idMontoBase"/>
                  </ns12:idMontoBase>
                </xsl:if>
                <xsl:if test="ns12:montoBase/ns12:valorMontoBase">
                  <ns12:valorMontoBase>
                    <xsl:value-of select="ns12:montoBase/ns12:valorMontoBase"/>
                  </ns12:valorMontoBase>
                </xsl:if>
                <xsl:if test="ns12:montoBase/ns12:porcentajeMontoBase">
                  <ns12:porcentajeMontoBase>
                    <xsl:value-of select="ns12:montoBase/ns12:porcentajeMontoBase"/>
                  </ns12:porcentajeMontoBase>
                </xsl:if>
                <xsl:if test="ns12:montoBase/ns12:descripcionMontoBase">
                  <ns12:descripcionMontoBase>
                    <xsl:value-of select="ns12:montoBase/ns12:descripcionMontoBase"/>
                  </ns12:descripcionMontoBase>
                </xsl:if>
              </ns12:montoBase>
            </xsl:if>
            <xsl:if test="ns12:fechaValor">
              <ns12:fechaValor>
                <xsl:value-of select="ns12:fechaValor"/>
              </ns12:fechaValor>
            </xsl:if>
            <xsl:if test="ns12:fechaVencimiento">
              <ns12:fechaVencimiento>
                <xsl:value-of select="ns12:fechaVencimiento"/>
              </ns12:fechaVencimiento>
            </xsl:if>
            <xsl:if test="ns12:fechaInicioCapital">
              <ns12:fechaInicioCapital>
                <xsl:value-of select="ns12:fechaInicioCapital"/>
              </ns12:fechaInicioCapital>
            </xsl:if>
            <xsl:if test="ns12:fechaInicioComision">
              <ns12:fechaInicioComision>
                <xsl:value-of select="ns12:fechaInicioComision"/>
              </ns12:fechaInicioComision>
            </xsl:if>
            <xsl:if test="ns12:tipoFrecuencia">
              <ns12:tipoFrecuencia>
                <xsl:if test="ns12:tipoFrecuencia/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns12:tipoFrecuencia/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns12:tipoFrecuencia/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns12:tipoFrecuencia/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns12:tipoFrecuencia/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns12:tipoFrecuencia/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns12:tipoFrecuencia/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns12:tipoFrecuencia/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns12:tipoFrecuencia/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns12:tipoFrecuencia/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns12:tipoFrecuencia>
            </xsl:if>
            <xsl:if test="ns12:frecuenciaPago">
              <ns12:frecuenciaPago>
                <xsl:value-of select="ns12:frecuenciaPago"/>
              </ns12:frecuenciaPago>
            </xsl:if>
            <xsl:if test="ns12:fondo">
              <ns12:fondo>
                <xsl:value-of select="ns12:fondo"/>
              </ns12:fondo>
            </xsl:if>
            <xsl:if test="ns12:comisionCompartida">
              <ns12:comisionCompartida>
                <xsl:value-of select="ns12:comisionCompartida"/>
              </ns12:comisionCompartida>
            </xsl:if>
            <xsl:if test="ns12:codigoDesembolso">
              <ns12:codigoDesembolso>
                <xsl:value-of select="ns12:codigoDesembolso"/>
              </ns12:codigoDesembolso>
            </xsl:if>
            <xsl:if test="ns12:numeroTesoreria">
              <ns12:numeroTesoreria>
                <xsl:value-of select="ns12:numeroTesoreria"/>
              </ns12:numeroTesoreria>
            </xsl:if>
            <xsl:if test="ns12:codigoContrato">
              <ns12:codigoContrato>
                <xsl:value-of select="ns12:codigoContrato"/>
              </ns12:codigoContrato>
            </xsl:if>
            <xsl:if test="ns12:momentoCobro">
              <ns12:momentoCobro>
                <xsl:if test="ns12:momentoCobro/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns12:momentoCobro/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns12:momentoCobro/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns12:momentoCobro/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns12:momentoCobro/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns12:momentoCobro/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns12:momentoCobro/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns12:momentoCobro/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns12:momentoCobro/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns12:momentoCobro/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns12:momentoCobro>
            </xsl:if>
            <xsl:if test="ns12:tipoTasa">
              <ns12:tipoTasa>
                <xsl:if test="ns12:tipoTasa/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns12:tipoTasa/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns12:tipoTasa/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns12:tipoTasa/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns12:tipoTasa/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns12:tipoTasa/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns12:tipoTasa/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns12:tipoTasa/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns12:tipoTasa/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns12:tipoTasa/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns12:tipoTasa>
            </xsl:if>
            <xsl:if test="ns12:baseCalculo">
              <ns12:baseCalculo>
                <xsl:if test="ns12:baseCalculo/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns12:baseCalculo/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns12:baseCalculo/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns12:baseCalculo/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns12:baseCalculo/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns12:baseCalculo/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns12:baseCalculo/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns12:baseCalculo/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns12:baseCalculo/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns12:baseCalculo/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns12:baseCalculo>
            </xsl:if>
            <xsl:if test="ns12:responsableComision">
              <ns12:responsableComision>
                <xsl:value-of select="ns12:responsableComision"/>
              </ns12:responsableComision>
            </xsl:if>
            <ns12:estadoTCC>
              <xsl:if test="ns12:estadoTCC/ns20:id">
                <ns20:id>
                  <xsl:value-of select="ns12:estadoTCC/ns20:id"/>
                </ns20:id>
              </xsl:if>
              <xsl:if test="ns12:estadoTCC/ns20:descripcion">
                <ns20:descripcion>
                  <xsl:value-of select="ns12:estadoTCC/ns20:descripcion"/>
                </ns20:descripcion>
              </xsl:if>
              <xsl:if test="ns12:estadoTCC/ns20:descripcionCorta">
                <ns20:descripcionCorta>
                  <xsl:value-of select="ns12:estadoTCC/ns20:descripcionCorta"/>
                </ns20:descripcionCorta>
              </xsl:if>
              <xsl:if test="ns12:estadoTCC/ns20:estatus">
                <ns20:estatus>
                  <xsl:value-of select="ns12:estadoTCC/ns20:estatus"/>
                </ns20:estatus>
              </xsl:if>
              <xsl:if test="ns12:estadoTCC/ns20:codigoExterno">
                <ns20:codigoExterno>
                  <xsl:value-of select="ns12:estadoTCC/ns20:codigoExterno"/>
                </ns20:codigoExterno>
              </xsl:if>
              <xsl:if test="ns12:estadoTCC/ns20:esSubEstado">
                <ns20:esSubEstado>
                  <xsl:value-of select="ns12:estadoTCC/ns20:esSubEstado"/>
                </ns20:esSubEstado>
              </xsl:if>
            </ns12:estadoTCC>
            <ns12:subEstadoTCC>
              <xsl:if test="ns12:subEstadoTCC/ns20:id">
                <ns20:id>
                  <xsl:value-of select="ns12:subEstadoTCC/ns20:id"/>
                </ns20:id>
              </xsl:if>
              <xsl:if test="ns12:subEstadoTCC/ns20:descripcion">
                <ns20:descripcion>
                  <xsl:value-of select="ns12:subEstadoTCC/ns20:descripcion"/>
                </ns20:descripcion>
              </xsl:if>
              <xsl:if test="ns12:subEstadoTCC/ns20:descripcionCorta">
                <ns20:descripcionCorta>
                  <xsl:value-of select="ns12:subEstadoTCC/ns20:descripcionCorta"/>
                </ns20:descripcionCorta>
              </xsl:if>
              <xsl:if test="ns12:subEstadoTCC/ns20:estatus">
                <ns20:estatus>
                  <xsl:value-of select="ns12:subEstadoTCC/ns20:estatus"/>
                </ns20:estatus>
              </xsl:if>
              <xsl:if test="ns12:subEstadoTCC/ns20:codigoExterno">
                <ns20:codigoExterno>
                  <xsl:value-of select="ns12:subEstadoTCC/ns20:codigoExterno"/>
                </ns20:codigoExterno>
              </xsl:if>
              <xsl:if test="ns12:subEstadoTCC/ns20:esSubEstado">
                <ns20:esSubEstado>
                  <xsl:value-of select="ns12:subEstadoTCC/ns20:esSubEstado"/>
                </ns20:esSubEstado>
              </xsl:if>
            </ns12:subEstadoTCC>
            <ns12:fechaRegistro>
              <xsl:value-of select="ns12:fechaRegistro"/>
            </ns12:fechaRegistro>
            <ns12:estado>
              <xsl:value-of select="ns12:estado"/>
            </ns12:estado>
            <ns12:comisionEnmendada>
              <xsl:value-of select="ns12:comisionEnmendada"/>
            </ns12:comisionEnmendada>
            <ns12:fechaEnmienda>
              <xsl:value-of select="ns12:fechaEnmienda"/>
            </ns12:fechaEnmienda>
            <xsl:if test="ns12:banSugerida">
              <ns12:banSugerida>
                <xsl:value-of select="ns12:banSugerida"/>
              </ns12:banSugerida>
            </xsl:if>
            <xsl:if test="ns12:numeroCuentaCliente">
              <ns12:numeroCuentaCliente>
                <xsl:value-of select="ns12:numeroCuentaCliente"/>
              </ns12:numeroCuentaCliente>
            </xsl:if>
            <xsl:if test="ns12:observaciones">
              <ns12:observaciones>
                <xsl:value-of select="ns12:observaciones"/>
              </ns12:observaciones>
            </xsl:if>
            <xsl:for-each select="ns12:configAtributo">
              <ns12:configAtributo>
                <xsl:if test="ns20:id">
                  <ns20:id>
                    <xsl:value-of select="ns20:id"/>
                  </ns20:id>
                </xsl:if>
                <ns20:columna>
                  <xsl:value-of select="ns20:columna"/>
                </ns20:columna>
                <xsl:if test="ns20:ordenamiento">
                  <ns20:ordenamiento>
                    <xsl:value-of select="ns20:ordenamiento"/>
                  </ns20:ordenamiento>
                </xsl:if>
                <xsl:if test="ns20:soloLectura">
                  <ns20:soloLectura>
                    <xsl:value-of select="ns20:soloLectura"/>
                  </ns20:soloLectura>
                </xsl:if>
                <xsl:if test="ns20:esObligatorio">
                  <ns20:esObligatorio>
                    <xsl:value-of select="ns20:esObligatorio"/>
                  </ns20:esObligatorio>
                </xsl:if>
                <xsl:if test="ns20:etiqueta">
                  <ns20:etiqueta>
                    <xsl:value-of select="ns20:etiqueta"/>
                  </ns20:etiqueta>
                </xsl:if>
                <xsl:for-each select="ns20:valor">
                  <ns20:valor>
                    <xsl:value-of select="."/>
                  </ns20:valor>
                </xsl:for-each>
                <xsl:if test="ns20:tipoValor">
                  <ns20:tipoValor>
                    <xsl:value-of select="ns20:tipoValor"/>
                  </ns20:tipoValor>
                </xsl:if>
                <xsl:for-each select="ns20:catalogo">
                  <ns20:catalogo>
                    <xsl:if test="ns16:Id">
                      <ns16:Id>
                        <xsl:value-of select="ns16:Id"/>
                      </ns16:Id>
                    </xsl:if>
                    <xsl:if test="ns16:Descripcion">
                      <ns16:Descripcion>
                        <xsl:value-of select="ns16:Descripcion"/>
                      </ns16:Descripcion>
                    </xsl:if>
                    <xsl:if test="ns16:DescripcionCorta">
                      <ns16:DescripcionCorta>
                        <xsl:value-of select="ns16:DescripcionCorta"/>
                      </ns16:DescripcionCorta>
                    </xsl:if>
                    <xsl:if test="ns16:estatus">
                      <ns16:estatus>
                        <xsl:value-of select="ns16:estatus"/>
                      </ns16:estatus>
                    </xsl:if>
                    <xsl:if test="ns16:codigoExterno">
                      <ns16:codigoExterno>
                        <xsl:value-of select="ns16:codigoExterno"/>
                      </ns16:codigoExterno>
                    </xsl:if>
                  </ns20:catalogo>
                </xsl:for-each>
              </ns12:configAtributo>
            </xsl:for-each>
            <xsl:if test="ns12:Accion">
              <ns12:Accion>
                <xsl:value-of select="ns12:Accion"/>
              </ns12:Accion>
            </xsl:if>
          </ns17:Comision>
        </xsl:for-each>
        <xsl:for-each select="/ns0:ConsultarTransferenciasBancariasByIdResponse/ns0:ContratoDesembolso/ns17:Transferencia">
          <ns17:Transferencia>
            <ns17:idTransferencia>
              <xsl:value-of select="ns17:idTransferencia"/>
            </ns17:idTransferencia>
            <ns17:idDesembolso>
              <xsl:value-of select="ns17:idDesembolso"/>
            </ns17:idDesembolso>
            <xsl:if test="ns17:idFacturador">
              <ns17:idFacturador>
                <xsl:value-of select="ns17:idFacturador"/>
              </ns17:idFacturador>
            </xsl:if>
            <ns17:Monto>
              <ns8:tipo>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:Id">
                  <ns16:Id>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:Id"/>
                  </ns16:Id>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:Descripcion">
                  <ns16:Descripcion>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:Descripcion"/>
                  </ns16:Descripcion>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:DescripcionCorta">
                  <ns16:DescripcionCorta>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:DescripcionCorta"/>
                  </ns16:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:estatus">
                  <ns16:estatus>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:estatus"/>
                  </ns16:estatus>
                </xsl:if>
                <xsl:if test="ns17:Monto/ns8:tipo/ns16:codigoExterno">
                  <ns16:codigoExterno>
                    <xsl:value-of select="ns17:Monto/ns8:tipo/ns16:codigoExterno"/>
                  </ns16:codigoExterno>
                </xsl:if>
              </ns8:tipo>
              <xsl:if test="ns17:Monto/ns8:importe">
                <ns8:importe>
                  <xsl:value-of select="ns17:Monto/ns8:importe"/>
                </ns8:importe>
              </xsl:if>
              <xsl:if test="ns17:Monto/ns8:moneda">
                <ns8:moneda>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:Id">
                    <ns16:Id>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:Id"/>
                    </ns16:Id>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:Descripcion">
                    <ns16:Descripcion>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:Descripcion"/>
                    </ns16:Descripcion>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:DescripcionCorta">
                    <ns16:DescripcionCorta>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:DescripcionCorta"/>
                    </ns16:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:estatus">
                    <ns16:estatus>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:estatus"/>
                    </ns16:estatus>
                  </xsl:if>
                  <xsl:if test="ns17:Monto/ns8:moneda/ns16:codigoExterno">
                    <ns16:codigoExterno>
                      <xsl:value-of select="ns17:Monto/ns8:moneda/ns16:codigoExterno"/>
                    </ns16:codigoExterno>
                  </xsl:if>
                </ns8:moneda>
              </xsl:if>
            </ns17:Monto>
            <ns17:FormaTransferencia>
              <xsl:if test="ns17:FormaTransferencia/ns16:Id">
                <ns16:Id>
                  <xsl:value-of select="ns17:FormaTransferencia/ns16:Id"/>
                </ns16:Id>
              </xsl:if>
              <xsl:if test="ns17:FormaTransferencia/ns16:Descripcion">
                <ns16:Descripcion>
                  <xsl:value-of select="ns17:FormaTransferencia/ns16:Descripcion"/>
                </ns16:Descripcion>
              </xsl:if>
              <xsl:if test="ns17:FormaTransferencia/ns16:DescripcionCorta">
                <ns16:DescripcionCorta>
                  <xsl:value-of select="ns17:FormaTransferencia/ns16:DescripcionCorta"/>
                </ns16:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns17:FormaTransferencia/ns16:estatus">
                <ns16:estatus>
                  <xsl:value-of select="ns17:FormaTransferencia/ns16:estatus"/>
                </ns16:estatus>
              </xsl:if>
              <xsl:if test="ns17:FormaTransferencia/ns16:codigoExterno">
                <ns16:codigoExterno>
                  <xsl:value-of select="ns17:FormaTransferencia/ns16:codigoExterno"/>
                </ns16:codigoExterno>
              </xsl:if>
            </ns17:FormaTransferencia>
            <xsl:if test="ns17:referenciaMensaje">
              <ns17:referenciaMensaje>
                <xsl:value-of select="ns17:referenciaMensaje"/>
              </ns17:referenciaMensaje>
            </xsl:if>
            <xsl:if test="ns17:esConsolidada">
              <ns17:esConsolidada>
                <xsl:value-of select="ns17:esConsolidada"/>
              </ns17:esConsolidada>
            </xsl:if>
            <ns17:esConsolidacionPadre>
              <xsl:value-of select="ns17:esConsolidacionPadre"/>
            </ns17:esConsolidacionPadre>
            <ns17:idConsolidacionPadre>
              <xsl:value-of select="ns17:idConsolidacionPadre"/>
            </ns17:idConsolidacionPadre>
            <ns17:bhqTransferencia>
              <xsl:value-of select="ns17:bhqTransferencia"/>
            </ns17:bhqTransferencia>
            <xsl:if test="ns17:idBancoTransferencia">
              <ns17:idBancoTransferencia>
                <xsl:value-of select="ns17:idBancoTransferencia"/>
              </ns17:idBancoTransferencia>
            </xsl:if>
            <xsl:if test="ns17:numeroCuenta">
              <ns17:numeroCuenta>
                <xsl:value-of select="ns17:numeroCuenta"/>
              </ns17:numeroCuenta>
            </xsl:if>
            <ns17:nombreCuenta>
              <xsl:value-of select="ns17:nombreCuenta"/>
            </ns17:nombreCuenta>
            <xsl:if test="ns17:nombreBanco">
              <ns17:nombreBanco>
                <xsl:value-of select="ns17:nombreBanco"/>
              </ns17:nombreBanco>
            </xsl:if>
            <ns17:idOperacion>
              <xsl:value-of select="ns17:idOperacion"/>
            </ns17:idOperacion>
            <ns17:tipoMensaje>
              <xsl:value-of select="ns17:tipoMensaje"/>
            </ns17:tipoMensaje>
            <xsl:if test="ns17:estado">
              <ns17:estado>
                <xsl:value-of select="ns17:estado"/>
              </ns17:estado>
            </xsl:if>
            <ns17:fechaRegistro>
              <xsl:value-of select="ns17:fechaRegistro"/>
            </ns17:fechaRegistro>
            <xsl:if test="ns17:Beneficiario">
              <ns17:Beneficiario>
                <xsl:if test="ns17:Beneficiario/ns17:tipoOpcion">
                  <ns17:tipoOpcion>
                    <xsl:value-of select="ns17:Beneficiario/ns17:tipoOpcion"/>
                  </ns17:tipoOpcion>
                </xsl:if>
                <xsl:if test="ns17:Beneficiario/ns17:numeroCta">
                  <ns17:numeroCta>
                    <xsl:value-of select="ns17:Beneficiario/ns17:numeroCta"/>
                  </ns17:numeroCta>
                </xsl:if>
                <xsl:if test="ns17:Beneficiario/ns17:identificador">
                  <ns17:identificador>
                    <xsl:value-of select="ns17:Beneficiario/ns17:identificador"/>
                  </ns17:identificador>
                </xsl:if>
                <xsl:if test="ns17:Beneficiario/ns17:beneficiario">
                  <ns17:beneficiario>
                    <xsl:value-of select="ns17:Beneficiario/ns17:beneficiario"/>
                  </ns17:beneficiario>
                </xsl:if>
                <xsl:if test="ns17:Beneficiario/ns17:direccion">
                  <ns17:direccion>
                    <xsl:value-of select="ns17:Beneficiario/ns17:direccion"/>
                  </ns17:direccion>
                </xsl:if>
              </ns17:Beneficiario>
            </xsl:if>
            <xsl:if test="ns17:Banco">
              <ns17:Banco>
                <xsl:if test="ns17:Banco/ns17:tipoOpcion">
                  <ns17:tipoOpcion>
                    <xsl:value-of select="ns17:Banco/ns17:tipoOpcion"/>
                  </ns17:tipoOpcion>
                </xsl:if>
                <xsl:if test="ns17:Banco/ns17:numeroCta">
                  <ns17:numeroCta>
                    <xsl:value-of select="ns17:Banco/ns17:numeroCta"/>
                  </ns17:numeroCta>
                </xsl:if>
                <xsl:if test="ns17:Banco/ns17:identificador">
                  <ns17:identificador>
                    <xsl:value-of select="ns17:Banco/ns17:identificador"/>
                  </ns17:identificador>
                </xsl:if>
                <xsl:if test="ns17:Banco/ns17:beneficiario">
                  <ns17:beneficiario>
                    <xsl:value-of select="ns17:Banco/ns17:beneficiario"/>
                  </ns17:beneficiario>
                </xsl:if>
                <xsl:if test="ns17:Banco/ns17:direccion">
                  <ns17:direccion>
                    <xsl:value-of select="ns17:Banco/ns17:direccion"/>
                  </ns17:direccion>
                </xsl:if>
              </ns17:Banco>
            </xsl:if>
            <xsl:if test="ns17:Intermediario">
              <ns17:Intermediario>
                <xsl:if test="ns17:Intermediario/ns17:tipoOpcion">
                  <ns17:tipoOpcion>
                    <xsl:value-of select="ns17:Intermediario/ns17:tipoOpcion"/>
                  </ns17:tipoOpcion>
                </xsl:if>
                <xsl:if test="ns17:Intermediario/ns17:numeroCta">
                  <ns17:numeroCta>
                    <xsl:value-of select="ns17:Intermediario/ns17:numeroCta"/>
                  </ns17:numeroCta>
                </xsl:if>
                <xsl:if test="ns17:Intermediario/ns17:identificador">
                  <ns17:identificador>
                    <xsl:value-of select="ns17:Intermediario/ns17:identificador"/>
                  </ns17:identificador>
                </xsl:if>
                <xsl:if test="ns17:Intermediario/ns17:beneficiario">
                  <ns17:beneficiario>
                    <xsl:value-of select="ns17:Intermediario/ns17:beneficiario"/>
                  </ns17:beneficiario>
                </xsl:if>
                <xsl:if test="ns17:Intermediario/ns17:direccion">
                  <ns17:direccion>
                    <xsl:value-of select="ns17:Intermediario/ns17:direccion"/>
                  </ns17:direccion>
                </xsl:if>
              </ns17:Intermediario>
            </xsl:if>
          </ns17:Transferencia>
        </xsl:for-each>
      </ns0:ContratoDesembolso>
      <ns0:Parametros>
        <ns8:name>NUMERO_LINEA</ns8:name>
        <ns8:value>
          <xsl:value-of select="$ConsultarInformacionReglaById_OutputVariable.response/ns0:ConsultarInformacionReglasByIdResponse/ns0:LineaCredito/ns15:NumeroLineaCredito"/>
        </ns8:value>
      </ns0:Parametros>
      <ns0:Parametros>
        <ns8:name>TIPO_RECURSO</ns8:name>
        <ns8:value>S</ns8:value>
      </ns0:Parametros>
      <ns0:Parametros>
        <ns8:name>PAIS</ns8:name>
        <ns8:value>
          <xsl:value-of select="$ConsultarInformacionReglaById_OutputVariable.response/ns0:ConsultarInformacionReglasByIdResponse/ns0:Cliente/ns19:pais/ns16:codigoExterno"/>
        </ns8:value>
      </ns0:Parametros>
      <ns0:Parametros>
        <ns8:name>EJECUTIVO</ns8:name>
        <ns8:value>maparicio</ns8:value>
      </ns0:Parametros>
      <ns0:Parametros>
        <ns8:name>OBJETIVO_ESTRATEGICO</ns8:name>
        <ns8:value>
          <xsl:value-of select="$ConsultarInformacionReglaById_OutputVariable.response/ns0:ConsultarInformacionReglasByIdResponse/ns0:Operacion/ns6:objetivosEstrategicos"/>
        </ns8:value>
      </ns0:Parametros>
    </ns0:CrearTransferenciaFLEXCUBERequest>
  </xsl:template>
</xsl:stylesheet>
