<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/UCE/Payload/V1"
                xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/task"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns7="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:evidence="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:ns2="http://www.bcie.org/CatalogoBO"
                xmlns:ns3="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns4="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns6="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:ns5="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA13/UCEPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="UCEPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/UCE/Payload/V1"/>
        <oracle-xsl-mapper:param name="ucePayload"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/soa/shared/workflow/WorkflowTask.xsd"/>
        <oracle-xsl-mapper:rootElement name="task" namespace="http://xmlns.oracle.com/bpel/workflow/task"/>
        <oracle-xsl-mapper:param name="execData"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA13/UCEPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="UCEPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/UCE/Payload/V1"/>
        <oracle-xsl-mapper:param name="uceDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA13/UCEPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="UCEPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/UCE/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [MON JUL 25 12:59:31 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="execData"/>
  <xsl:param name="uceDO"/>
  <xsl:template match="/">
    <ns0:UCEPayload>
      <ns0:Header>
        <header:Cliente>
          <ns5:IdCliente>
            <xsl:value-of select="ns0:UCEPayload/ns0:Header/header:Cliente/ns5:IdCliente"/>
          </ns5:IdCliente>
          <ns5:IdFlexCube>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:IdFlexCube"/>
          </ns5:IdFlexCube>
          <ns5:RazonSocial>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:RazonSocial"/>
          </ns5:RazonSocial>
          <ns5:Abreviatura>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:Abreviatura"/>
          </ns5:Abreviatura>
          <ns5:IdSector>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:IdSector"/>
          </ns5:IdSector>
          <ns5:Sector>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:Sector"/>
          </ns5:Sector>
          <ns5:IdPais>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:IdPais"/>
          </ns5:IdPais>
          <ns5:Pais>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:Pais"/>
          </ns5:Pais>
          <ns5:IdOficina>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:IdOficina"/>
          </ns5:IdOficina>
          <ns5:Oficina>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:Oficina"/>
          </ns5:Oficina>
          <ns5:ResponsableCliente>
            <xsl:value-of select="$uceDO/ns0:UCEPayload/ns0:Header/header:Cliente/ns5:ResponsableCliente"/>
          </ns5:ResponsableCliente>
        </header:Cliente>
        <header:Tarea>
          <ns6:CodigoTarea>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Tarea/ns6:CodigoTarea"/>
          </ns6:CodigoTarea>
          <ns6:NombreTarea>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Tarea/ns6:NombreTarea"/>
          </ns6:NombreTarea>
          <ns6:CodigoRol>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Tarea/ns6:CodigoRol"/>
          </ns6:CodigoRol>
          <ns6:NombreRol>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Tarea/ns6:NombreRol"/>
          </ns6:NombreRol>
          <ns6:CodigoProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Tarea/ns6:CodigoProceso"/>
          </ns6:CodigoProceso>
          <ns6:NombreProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Tarea/ns6:NombreProceso"/>
          </ns6:NombreProceso>
        </header:Tarea>
        <header:Proceso>
          <ns4:IdProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:IdProceso"/>
          </ns4:IdProceso>
          <ns4:CodigoProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:CodigoProceso"/>
          </ns4:CodigoProceso>
          <ns4:NombreProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:NombreProceso"/>
          </ns4:NombreProceso>
          <ns4:EsProcesoCore>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:EsProcesoCore"/>
          </ns4:EsProcesoCore>
          <ns4:RolIniciaProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:RolIniciaProceso"/>
          </ns4:RolIniciaProceso>
          <ns4:UsuarioIniciaProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:UsuarioIniciaProceso"/>
          </ns4:UsuarioIniciaProceso>
          <ns4:InstanciaProceso>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:InstanciaProceso"/>
          </ns4:InstanciaProceso>
          <ns4:IdFlujo>
            <xsl:value-of select="/ns0:UCEPayload/ns0:Header/header:Proceso/ns4:IdFlujo"/>
          </ns4:IdFlujo>
        </header:Proceso>
        <xsl:for-each select="/ns0:UCEPayload/ns0:Header/parameter:ParameterType">
          <parameter:ParameterType>
            <parameter:parameterName>
              <xsl:value-of select="parameter:parameterName"/>
            </parameter:parameterName>
            <parameter:parameterValue>
              <xsl:value-of select="parameter:parameterValue"/>
            </parameter:parameterValue>
          </parameter:ParameterType>
        </xsl:for-each>
      </ns0:Header>
      <ns0:tipoInicio>
        <xsl:value-of select="/ns0:UCEPayload/ns0:tipoInicio"/>
      </ns0:tipoInicio>
      <ns0:clienteUCE>
        <xsl:value-of select="/ns0:UCEPayload/ns0:clienteUCE"/>
      </ns0:clienteUCE>
      <ns0:Equipo>
        <ns0:analistaUCE>
          <xsl:value-of select="/ns0:UCEPayload/ns0:Equipo/ns0:analistaUCE"/>
        </ns0:analistaUCE>
        <ns0:jefeUCE>
          <xsl:value-of select="/ns0:UCEPayload/ns0:Equipo/ns0:jefeUCE"/>
        </ns0:jefeUCE>
        <ns0:gerentePais>
          <xsl:value-of select="/ns0:UCEPayload/ns0:Equipo/ns0:gerentePais"/>
        </ns0:gerentePais>
      </ns0:Equipo>
      <ns0:EquipoEjecucion>
        <ns0:analistaUCE>
          <xsl:value-of select="$execData/ns1:task/ns1:systemAttributes/ns1:updatedBy/ns1:id"/>
        </ns0:analistaUCE>
        <ns0:jefeUCE>
          <xsl:value-of select="/ns0:UCEPayload/ns0:EquipoEjecucion/ns0:jefeUCE"/>
        </ns0:jefeUCE>
        <ns0:gerentePais>
          <xsl:value-of select="/ns0:UCEPayload/ns0:EquipoEjecucion/ns0:gerentePais"/>
        </ns0:gerentePais>
      </ns0:EquipoEjecucion>
      <xsl:for-each select="/ns0:UCEPayload/parameter:ParameterType">
        <parameter:ParameterType>
          <parameter:parameterName>
            <xsl:value-of select="parameter:parameterName"/>
          </parameter:parameterName>
          <parameter:parameterValue>
            <xsl:value-of select="parameter:parameterValue"/>
          </parameter:parameterValue>
        </parameter:ParameterType>
      </xsl:for-each>
    </ns0:UCEPayload>
  </xsl:template>
</xsl:stylesheet>
