<wsdl:definitions name="ConsultarLimitesPrograma_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarLimitesPrograma_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarLimitesPrograma_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLimitesPrograma_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarLimitesPrograma_DB_plt">
    <plt:role name="ConsultarLimitesPrograma_DB_role">
      <plt:portType name="tns:ConsultarLimitesPrograma_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLimitesPrograma_DB" schemaLocation="../XSD/ConsultarLimitesPrograma_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarLimitesPrograma_DBInput_msg">
        <wsdl:part name="ConsultarLimitesPrograma_DBInput_msg" element="db:ConsultarLimitesPrograma_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarLimitesPrograma_DBOutputCollection_msg">
        <wsdl:part name="ConsultarLimitesPrograma_DBOutputCollection" element="db:ConsultarLimitesPrograma_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarLimitesPrograma_DB_ptt">
        <wsdl:operation name="ConsultarLimitesPrograma_DB">
            <wsdl:input message="tns:ConsultarLimitesPrograma_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarLimitesPrograma_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>