<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/EliminarContrapartesTerminoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/EliminarContrapartesTerminoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:terMO="http://www.bcie.org/TerminoMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/TerminoMO" schemaLocation="../../Schema/TerminoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="EliminarContrapartesTerminoRequestMessage">
    <part name="request" element="terMO:EliminarTreContrapartesTerminoRequest"/>
  </message>
  <message name="EliminarContrapartesTerminoResponseMessage">
    <part name="response" element="terMO:EliminarTreContrapartesTerminoResponse"/>
  </message>
  <portType name="EliminarContrapartesPT">
    <operation name="eliminarContrapartesTermino">
      <input message="tns:EliminarContrapartesTerminoRequestMessage"/>
      <output message="tns:EliminarContrapartesTerminoResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarContrapartes12Bnd" type="tns:EliminarContrapartesPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarContrapartesTermino">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/EliminarContrapartesTerminoService/eliminarContrapartesTermino"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>