<wsdl:definitions name="ConsultarParticipantesByIdNoObjecion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarParticipantesByIdNoObjecion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarParticipantesByIdNoObjecion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarParticipantesByIdNoObjecion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarParticipantesByIdNoObjecion_plt">
    <plt:role name="ConsultarParticipantesByIdNoObjecion_role">
      <plt:portType name="tns:ConsultarParticipantesByIdNoObjecion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarParticipantesByIdNoObjecion" schemaLocation="../XSD/ConsultarParticipantesByIdNoObjecion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarParticipantesByIdNoObjecionInput_msg">
        <wsdl:part name="ConsultarParticipantesByIdNoObjecionInput_msg" element="db:ConsultarParticipantesByIdNoObjecionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarParticipantesByIdNoObjecionOutputCollection_msg">
        <wsdl:part name="ConsultarParticipantesByIdNoObjecionOutputCollection" element="db:ConsultarParticipantesByIdNoObjecionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarParticipantesByIdNoObjecion_ptt">
        <wsdl:operation name="ConsultarParticipantesByIdNoObjecion">
            <wsdl:input message="tns:ConsultarParticipantesByIdNoObjecionInput_msg"/>
            <wsdl:output message="tns:ConsultarParticipantesByIdNoObjecionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>