<wsdl:definitions name="ConsultarDesAproByIdNivelAprobacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarDesAproByIdNivelAprobacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarDesAproByIdNivelAprobacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDesAproByIdNivelAprobacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarDesAproByIdNivelAprobacion_plt">
    <plt:role name="ConsultarDesAproByIdNivelAprobacion_role">
      <plt:portType name="tns:ConsultarDesAproByIdNivelAprobacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDesAproByIdNivelAprobacion" schemaLocation="../XSD/ConsultarDesAproByIdNivelAprobacion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarDesAproByIdNivelAprobacionInput_msg">
        <wsdl:part name="ConsultarDesAproByIdNivelAprobacionInput_msg" element="db:ConsultarDesAproByIdNivelAprobacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarDesAproByIdNivelAprobacionOutputCollection_msg">
        <wsdl:part name="ConsultarDesAproByIdNivelAprobacionOutputCollection" element="db:ConsultarDesAproByIdNivelAprobacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarDesAproByIdNivelAprobacion_ptt">
        <wsdl:operation name="ConsultarDesAproByIdNivelAprobacion">
            <wsdl:input message="tns:ConsultarDesAproByIdNivelAprobacionInput_msg"/>
            <wsdl:output message="tns:ConsultarDesAproByIdNivelAprobacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>