<wsdl:definitions
     name="ActualizarDocumento"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ActualizarDocumento/ActualizarDocumento"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ActualizarDocumento/ActualizarDocumento"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarDocumento"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarDocumento_plt" >
    <plt:role name="ActualizarDocumento_role" >
      <plt:portType name="tns:ActualizarDocumento_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarDocumento" schemaLocation="../XSD/ActualizarDocumento_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DocumentoCollection_msg">
        <wsdl:part name="DocumentoCollection" element="top:DocumentoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarDocumento_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:DocumentoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
