<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="getSKUs" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/JDAUpdateStyleAPP/JDAUpdateStyle/getSKUs" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/JDAUpdateStyleAPP/JDAUpdateStyle/getSKUs" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getSKUs" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="getSKUs_plt">
      <plt:role name="getSKUs_role">
         <plt:portType name="tns:getSKUs_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getSKUs" schemaLocation="../Schemas/getSKUs.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="getSKUsInput_msg">
      <wsdl:part name="getSKUsInput_msg" element="db:getSKUsInput"/>
   </wsdl:message>
   <wsdl:message name="getSKUsOutputCollection_msg">
      <wsdl:part name="getSKUsOutputCollection" element="db:getSKUsOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="getSKUs_ptt">
      <wsdl:operation name="getSKUs">
         <wsdl:input message="tns:getSKUsInput_msg"/>
         <wsdl:output message="tns:getSKUsOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
