<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDAUpdateStyleProcess" targetNamespace="http://xmlns.oracle.com/AGCreateStyleProcess/JDAUpdateStyle/JDAUpdateStyleProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/AGCreateStyleProcess/JDAUpdateStyle/JDAUpdateStyleProcess" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/UpdateItemEntity/UpdateStyle" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://mx.agarcia.ea/Capabilities/Core/Items/UpdateItemEntitySvc/v1.0" xmlns:ns3="http://mx.agarcia.ea/Applications/Governance">
   <plnk:partnerLinkType name="JDAUpdateStyleProcess">
      <plnk:role name="JDAUpdateStyleProcessProvider" portType="client:JDAUpdateStyleProcess"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/UpdateItemEntitySvc/v1.0" location="UpdateStyleProcessWSDL.wsdl"/>
   <wsdl:import namespace="http://mx.agarcia.ea/Applications/Governance" location="http://172.16.19.26:7004/Applications/Governance/PS/GovernanceAPIPXY/v1.0?WSDL"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/UpdateItemEntity/UpdateStyle" schemaLocation="../Schemas/UpdateStyleSchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="JDAUpdateStyleProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:updateStyleRequest"/>
   </wsdl:message>
   <wsdl:message name="JDAUpdateStyleProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:updateStyleResponse"/>
   </wsdl:message>
   <wsdl:portType name="JDAUpdateStyleProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:JDAUpdateStyleProcessRequestMessage"/>
         <wsdl:output message="client:JDAUpdateStyleProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="JDAUpdateStyleProcessBinding" type="client:JDAUpdateStyleProcess">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="process">
         <soap:operation style="document" soapAction="http://xmlns.oracle.com/AGCreateStyleProcess/JDAUpdateStyle/JDAUpdateStyleProcess/process"/>
         <wsdl:input>
            <soap:body use="literal" parts="payload"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" parts="payload"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
