<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/PrepagoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/PrepagoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:preMO="http://www.bcie.org/PrepagoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/PrepagoMO" schemaLocation="../../Schema/PrepagoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="PlanAmortizacionRequestMessage">
    <part name="request" element="preMO:PlanArmotizacionRequest"/>
  </message>
  <message name="PlanAmortizacionResponseMessage">
    <part name="response" element="preMO:PlanArmotizacionResponse"/>
  </message>
  <portType name="PlanAmortizacionPT">
    <operation name="PlanAmortizacion">
      <input message="tns:PlanAmortizacionRequestMessage"/>
      <output message="tns:PlanAmortizacionResponseMessage"/>
    </operation>
  </portType>
  <binding name="PlanAmortizacionPTSOAP12Bnd" type="tns:PlanAmortizacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="PlanAmortizacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/PrepagoService/PlanAmortizacion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>