<wsdl:definitions name="MerchandiseHierarchyFindProcess" targetNamespace="http://xmlns.oracle.com/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindProcess/MerchandiseHierarchyFindProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindProcess/MerchandiseHierarchyFindProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/MerchandiseHierarchyFindProcess!1.0/WSDLs/MerchandiseHierarchyFindProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="MerchandiseHierarchyFindProcess">
        <plnk:role name="MerchandiseHierarchyFindProcessProvider" portType="client:MerchandiseHierarchyFindProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoDb" schemaLocation="../Schema/MerchandiseHierarchyFindProcessSchema.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MerchandiseHierarchyFindProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:caseTwoDbSelect_appCode_catId_parentId_parentAppCode_parentCatIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MerchandiseHierarchyFindProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:MdmMerchandHierarchiesCollection"/>
    </wsdl:message>
    <wsdl:portType name="MerchandiseHierarchyFindProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:MerchandiseHierarchyFindProcessRequestMessage"/>
            <wsdl:output message="client:MerchandiseHierarchyFindProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MerchandiseHierarchyFindProcessBinding" type="client:MerchandiseHierarchyFindProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MerchandiseHierarchyFindService_ep">
        <wsdl:port name="MerchandiseHierarchyFindProcess_pt" binding="client:MerchandiseHierarchyFindProcessBinding">
            <soap:address location="http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/MerchandiseHierarchyFindProcess/MerchandiseHierarchyFindService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>