<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ADAPTADORES/CrearTreLineaCredito" name="CrearTreLineaCredito-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CrearTreLineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ADAPTADORES/CrearTreLineaCredito"/>
    <wsdl:binding name="CrearTreLineaCredito_ptt-binding" type="cre:CrearTreLineaCredito_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ADAPTADORES/CrearTreLineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CrearTreLineaCredito">
            <soap:operation soapAction="CrearTreLineaCredito"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>