<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="RetailStoreTranslationProcess" targetNamespace="http://xmlns.oracle.com/RetailStoreApp/RetailStoreTranslate/RetailStoreTranslationProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/RetailStoreApp/RetailStoreTranslate/RetailStoreTranslationProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneDb" schemaLocation="../Schemas/caseOneDb_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="RetailStoreTranslationProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:caseOneDbSelect_idC1_appCodeC1_targetAppCodeC1InputParameters"/>
   </wsdl:message>
   <wsdl:message name="RetailStoreTranslationProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:MdmRetailstoresCollection"/>
   </wsdl:message>
   <wsdl:portType name="RetailStoreTranslationProcess">
      <wsdl:operation name="translate">
         <wsdl:input message="client:RetailStoreTranslationProcessRequestMessage"/>
         <wsdl:output message="client:RetailStoreTranslationProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="RetailStoreTranslationProcess">
      <plnk:role name="RetailStoreTranslationProcessProvider" portType="client:RetailStoreTranslationProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
