<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:ns0="http://xmlns.banesco.com/eopt/BillersInfoInq_V1.0" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.banesco.com/eopt/BillersInfoT24Inq_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoBill="http://xmlns.banesco.com/eo/Bill_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Payment/BillersInfoInq/BillersInfoInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="BillersInfoInqRq" namespace="http://xmlns.banesco.com/eopt/BillersInfoInq_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Payment/BillersInfoT24Inq/BillersInfoT24Inq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="BillersInfoT24InqRq" namespace="http://xmlns.banesco.com/eopt/BillersInfoT24Inq_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU MAY 10 14:41:28 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:BillersInfoT24InqRq>
         <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery">
            <tns:CategoryQuery>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:AcctNum/text()">
                  <eoBill:AcctNum>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:AcctNum"/>
                  </eoBill:AcctNum>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:BillerId/text()">
                  <eoBill:BillerId>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:BillerId"/>
                  </eoBill:BillerId>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Category/text()">
                  <eoBill:Category>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Category"/>
                  </eoBill:Category>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Desc/text()">
                  <eoBill:Desc>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Desc"/>
                  </eoBill:Desc>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:HasQuery/text()">
                  <eoBill:HasQuery>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:HasQuery"/>
                  </eoBill:HasQuery>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:HasTax/text()">
                  <eoBill:HasTax>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:HasTax"/>
                  </eoBill:HasTax>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Name/text()">
                  <eoBill:Name>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Name"/>
                  </eoBill:Name>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:PmtType/text()">
                  <eoBill:PmtType>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:PmtType"/>
                  </eoBill:PmtType>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Tax/text()">
                  <eoBill:Tax>
                     <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:Tax"/>
                  </eoBill:Tax>
               </xsl:if>
               <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:SvcProvider">
                  <eoBill:SvcProvider>
                     <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:SvcProvider/eoBill:LegalName/text()">
                        <eoBill:LegalName>
                           <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:SvcProvider/eoBill:LegalName"/>
                        </eoBill:LegalName>
                     </xsl:if>
                     <xsl:if test="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:SvcProvider/eoBill:SvcProviderId/text()">
                        <eoBill:SvcProviderId>
                           <xsl:value-of select="/ns0:BillersInfoInqRq/ns0:CategoryQuery/eoBill:SvcProvider/eoBill:SvcProviderId"/>
                        </eoBill:SvcProviderId>
                     </xsl:if>
                  </eoBill:SvcProvider>
               </xsl:if>
            </tns:CategoryQuery>
         </xsl:if>
      </tns:BillersInfoT24InqRq>
   </xsl:template>
</xsl:stylesheet>
