<wsdl:definitions
     name="ConsultarRolUsuario_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarRolUsuario_DB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarRolUsuario_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarRolUsuario_DB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarRolUsuario_DB_plt" >
    <plt:role name="ConsultarRolUsuario_DB_role" >
      <plt:portType name="tns:ConsultarRolUsuario_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarRolUsuario_DB"
                schemaLocation="../XSD/ConsultarRolUsuario_DB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarRolUsuario_DBInput_msg">
        <wsdl:part name="ConsultarRolUsuario_DBInput_msg" element="db:ConsultarRolUsuario_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarRolUsuario_DBOutputCollection_msg">
        <wsdl:part name="ConsultarRolUsuario_DBOutputCollection" element="db:ConsultarRolUsuario_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarRolUsuario_DB_ptt">
        <wsdl:operation name="ConsultarRolUsuario_DB">
            <wsdl:input message="tns:ConsultarRolUsuario_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarRolUsuario_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
