<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/CosultarLineaCredito" name="CosultarLineaCredito_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CosultarLineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/CosultarLineaCredito"/>
    <wsdl:binding name="CosultarLineaCredito_ptt-binding" type="cos:CosultarLineaCredito_ptt" xmlns:cos="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/CosultarLineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CosultarLineaCredito">
            <soap:operation soapAction="CosultarLineaCredito"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>