<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/AplicarCompensacionDesembolsoSOR"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/AplicarCompensacionDesembolsoSOR"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/AplicarCompensacionDesembolsoSOR/types"
                elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestAplicarCompensacionDesembolsoMessage">
    <part name="request" element="desMO:AplicarCompensacionDesembolsoRequest"/>
  </message>
  <message name="responseAplicarCompensacionDesembolsoMessage">
    <part name="response" element="desMO:AplicarCompensacionDesembolsoResponse"/>
  </message>
  <portType name="AplicarCompensacionDesembolso_PT">
    <operation name="AplicarCompensacionDesembolso">
      <input message="tns:requestAplicarCompensacionDesembolsoMessage"/>
      <output message="tns:responseAplicarCompensacionDesembolsoMessage"/>
    </operation>
  </portType>
  <binding name="AplicarCompensacionDesembolso_PTSOAP12Binding" type="tns:AplicarCompensacionDesembolso_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AplicarCompensacionDesembolso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/AplicarCompensacionDesembolsoSOR/AplicarCompensacionDesembolso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>