<wsdl:definitions
     name="ActualiizarClientes"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Cliente/ActualizarClientes/ActualiizarClientes"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Cliente/ActualizarClientes/ActualiizarClientes"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualiizarClientes"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualiizarClientes_plt" >
    <plt:role name="ActualiizarClientes_role" >
      <plt:portType name="tns:ActualiizarClientes_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualiizarClientes" schemaLocation="../XSD/ActualiizarClientes_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ClientesCollection_msg">
        <wsdl:part name="ClientesCollection" element="top:ClientesCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualiizarClientes_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:ClientesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
