<wsdl:definitions name="MerchandiseHierarchyTranslateProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Support/Commons/MerchandiseHierarchyTranslateProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Support/Commons/MerchandiseHierarchyTranslateProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/queryMerchadhierarTranslations" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/MerchandiseHierarchyTranslate!1.0/WSDLs/MerchandiseHierarchyTranslateProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="MerchandiseHierarchyTranslateProcess">
        <plnk:role name="MerchandiseHierarchyTranslateProcessProvider" portType="client:MerchandiseHierarchyTranslateProcess"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/queryMerchadhierarTranslations" location="MerchandiseHierarchyTranslateProcessAbstractWSDL.wsdl"/>
    <wsdl:message name="MerchandiseHierarchyTranslateProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:queryMerchadhierarTranslationsSelect_pDivision_pDepto_pClase_pTipoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MerchandiseHierarchyTranslateProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:MdmMerchandhierarTranslationsCollection"/>
    </wsdl:message>
    <wsdl:portType name="MerchandiseHierarchyTranslateProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:MerchandiseHierarchyTranslateProcessRequestMessage"/>
            <wsdl:output message="client:MerchandiseHierarchyTranslateProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MerchandiseHierarchyTranslateProcessBinding" type="client:MerchandiseHierarchyTranslateProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MerchandiseHierarchyTranslateService_ep">
        <wsdl:port name="MerchandiseHierarchyTranslateProcess_pt" binding="client:MerchandiseHierarchyTranslateProcessBinding">
            <soap:address location="http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/MerchandiseHierarchyTranslate/MerchandiseHierarchyTranslateService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>