<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioDocumento/CargarDocumento/ActualizarAdjunto" name="ActualizarAdjunto_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../WSDL/ActualizarAdjunto.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioDocumento/CargarDocumento/ActualizarAdjunto"/>
    <wsdl:binding name="ActualizarAdjunto_ptt-binding" type="act:ActualizarAdjunto_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/DominioDocumento/CargarDocumento/ActualizarAdjunto">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="update">
            <soap:operation soapAction="update"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>