<wsdl:definitions name="caseTwoSizeTranslation" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoSizeTranslation" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoSizeTranslation" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoSizeTranslation" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="caseTwoSizeTranslation_plt">
    <plt:role name="caseTwoSizeTranslation_role">
      <plt:portType name="tns:caseTwoSizeTranslation_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoSizeTranslation" schemaLocation="caseTwoSizeTranslation_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="caseTwoSizeTranslationSelect_inputParameters">
        <wsdl:part name="caseTwoSizeTranslationSelect_inputParameters" element="top:caseTwoSizeTranslationSelect_idC2_appCodeC2_catDefC2_parnIdC2_parnCatIdC2InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmItemsDiffsCollection_msg">
        <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
    </wsdl:message>
    <wsdl:portType name="caseTwoSizeTranslation_ptt">
        <wsdl:operation name="caseTwoSizeTranslationSelect">
            <wsdl:input message="tns:caseTwoSizeTranslationSelect_inputParameters"/>
            <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>