<wsdl:definitions name="caseOneSizeTranslation" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseOneSizeTranslation" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseOneSizeTranslation" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneSizeTranslation" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="caseOneSizeTranslation_plt">
    <plt:role name="caseOneSizeTranslation_role">
      <plt:portType name="tns:caseOneSizeTranslation_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneSizeTranslation" schemaLocation="caseOneSizeTranslation_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="caseOneSizeTranslationSelect_inputParameters">
        <wsdl:part name="caseOneSizeTranslationSelect_inputParameters" element="top:caseOneSizeTranslationSelect_idC1_appCodeC1_catDetC1_parIdC1_parCatIdC1_targetAppCodeC1InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmItemsDiffsCollection_msg">
        <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
    </wsdl:message>
    <wsdl:portType name="caseOneSizeTranslation_ptt">
        <wsdl:operation name="caseOneSizeTranslationSelect">
            <wsdl:input message="tns:caseOneSizeTranslationSelect_inputParameters"/>
            <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>