<wsdl:definitions
     name="ConsultarDeclaracionByIdOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/ConsultarDeclaracionByIdOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/ConsultarDeclaracionByIdOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDeclaracionByIdOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarDeclaracionByIdOperacion_plt" >
    <plt:role name="ConsultarDeclaracionByIdOperacion_role" >
      <plt:portType name="tns:ConsultarDeclaracionByIdOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDeclaracionByIdOperacion" schemaLocation="../XSD/ConsultarDeclaracionJuradaByIdOperacion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarDeclaracionByIdOperacionInput_msg">
        <wsdl:part name="ConsultarDeclaracionByIdOperacionInput_msg" element="db:ConsultarDeclaracionByIdOperacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarDeclaracionByIdOperacionOutputCollection_msg">
        <wsdl:part name="ConsultarDeclaracionByIdOperacionOutputCollection" element="db:ConsultarDeclaracionByIdOperacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarDeclaracionByIdOperacion_ptt">
        <wsdl:operation name="ConsultarDeclaracionByIdOperacion">
            <wsdl:input message="tns:ConsultarDeclaracionByIdOperacionInput_msg"/>
            <wsdl:output message="tns:ConsultarDeclaracionByIdOperacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
