<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/SP_Insertar_Declaracion" name="SP_Insertar_Declaracion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SP_Insertar_Declaracion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/SP_Insertar_Declaracion"/>
    <wsdl:binding name="SP_Insertar_Declaracion_ptt-binding" type="sp:SP_Insertar_Declaracion_ptt" xmlns:sp="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/SP_Insertar_Declaracion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SP_Insertar_Declaracion">
            <soap:operation soapAction="SP_Insertar_Declaracion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>