<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ConsultarAprobacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarAprobacion" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:aproMO="http://www.bcie.org/AprobacionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarAprobacionRequestMessage">
    <part name="request" element="aproMO:ConsultarAprobacionRequest"/>
  </message>
  <message name="ConsultarAprobacionResponseMessage">
    <part name="response" element="aproMO:ConsultarAprobacionResponse"/>
  </message>
  <wsdl:portType name="ConsultarAprobacion">
    <wsdl:operation name="consultarAprobacion">
      <wsdl:input message="tns:ConsultarAprobacionRequestMessage"/>
      <wsdl:output message="tns:ConsultarAprobacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarAprobacion12Bnd" type="tns:ConsultarAprobacion">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarAprobacion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ConsultarAprobacion/consultarAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>