<wsdl:definitions name="SyncStoreMDMAdapterService" targetNamespace="http://www.agarcia.mx/ServiceBus/Store" xmlns:tns="http://www.agarcia.mx/ServiceBus/Store" xmlns:ebm="http://www.agarcia.mx/EnterpriseObjects/Store" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Store" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Store/StoreEBM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="SyncStoreReqMsg">
        <wsdl:part name="SyncStoreReqMsg" element="ebm:SyncStoreEBM"/>
    </wsdl:message>
    <wsdl:message name="SyncStoreRespMsg">
        <wsdl:part name="SyncStoreRespMsg" element="ebm:SyncStoreResponseEBM"/>
    </wsdl:message>
    
    <wsdl:portType name="SyncStore_ptt">
        <wsdl:operation name="SyncStore">
            <wsdl:input message="tns:SyncStoreReqMsg"/>
            <wsdl:output message="tns:SyncStoreRespMsg"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="execute_bind" type="tns:SyncStore_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="SyncStore">
            <soap12:operation style="document" soapAction="execute" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/Store"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/Store"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>