<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/MDMApprovedPriceChangeListenerDBPXY" name="MDMApprovedPriceChangeListenerDBPXY-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="MDMApprovedPriceChangeListenerDBPXY.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/MDMApprovedPriceChangeListenerDBPXY"/>
    <wsdl:binding name="MDMApprovedPriceChangeListenerDBPXY_ptt-binding" type="mdm:MDMApprovedPriceChangeListenerDBPXY_ptt" xmlns:mdm="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/MDMApprovedPriceChangeListenerDBPXY">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="receive">
            <soap:operation soapAction="receive"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>