<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/ChaneNameFileTest/ftpServiceGet" name="ftpServiceGet-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ftpServiceGet.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/ChaneNameFileTest/ftpServiceGet"/>
    <wsdl:binding name="Get_ptt-binding" type="ftp:Get_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/ChaneNameFileTest/ftpServiceGet">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Get">
            <soap:operation soapAction="Get"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>