<wsdl:definitions name="ConsultaraprobacionByIdOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultaraprobacionByIdOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultaraprobacionByIdOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaraprobacionByIdOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultaraprobacionByIdOperacion_DB_plt">
    <plt:role name="ConsultaraprobacionByIdOperacion_DB_role">
      <plt:portType name="tns:ConsultaraprobacionByIdOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaraprobacionByIdOperacion_DB" schemaLocation="../XSD/ConsultaraprobacionByIdOperacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaraprobacionByIdOperacion_DBInput_msg">
        <wsdl:part name="ConsultaraprobacionByIdOperacion_DBInput_msg" element="db:ConsultaraprobacionByIdOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaraprobacionByIdOperacion_DBOutputCollection_msg">
        <wsdl:part name="ConsultaraprobacionByIdOperacion_DBOutputCollection" element="db:ConsultaraprobacionByIdOperacion_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaraprobacionByIdOperacion_DB_ptt">
        <wsdl:operation name="ConsultaraprobacionByIdOperacion_DB">
            <wsdl:input message="tns:ConsultaraprobacionByIdOperacion_DBInput_msg"/>
            <wsdl:output message="tns:ConsultaraprobacionByIdOperacion_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>