<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="ConsultarDesembolsoByIDV2SAD"
                  targetNamespace="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD"
                  xmlns:tns="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD"
                  xmlns:inp1="http://www.bcie.org/DesembolsoMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMOV2.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultarDesembolsoByIdV2RequestMessage">
    <wsdl:part name="ConsultarDesembolsoByIdV2Request" element="inp1:ConsultarDesembolsosByIdV2Request"/>
  </wsdl:message>
  <wsdl:message name="ConsultarDesembolsoByIdV2ResponseMessage">
    <wsdl:part name="ConsultarDesembolsoByIdV2Response" element="inp1:ConsultarDesembolsosByIdV2Response"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarDesembolsosByIdV2_PT">
    <wsdl:operation name="ConsultarDesembolsosByIdV2">
      <wsdl:input message="tns:ConsultarDesembolsoByIdV2RequestMessage"/>
      <wsdl:output message="tns:ConsultarDesembolsoByIdV2ResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarDesembolsosByIdV2_PTSOAP12Binding" type="tns:ConsultarDesembolsosByIdV2_PT">
    <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
    <wsdl:operation name="ConsultarDesembolsosByIdV2">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD/ConsultarDesembolsosByIdV2" soapActionRequired="false"/>
      <wsdl:input>
        <soap12:body use="literal" namespace="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" namespace="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
