<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://www.bcie.org/ConfiguracionProcesosMO"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.bcie.org/ObjetoProceso/Condiciones/Payload/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:confBO="http://www.bcie.org/ConfiguracionProcesosBO" xmlns:ns1="http://www.bcie.org/TerminoBO"
                xmlns:ns2="http://www.bcie.org/ReglaBO" xmlns:operBO="http://www.bcie.org/OperacionBO"
                xmlns:resBO="http://www.bcie.org/ResultBO" xmlns:cmnBO="http://www.bcie.org/CommonBO"
                xmlns:ns3="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:ns4="http://www.bcie.org/CrearBitacoraProcesoBO" xmlns:ns5="http://www.bcie.org/LineaCreditoBO"
                xmlns:ns6="http://www.bcie.org/MatrizTCCBO"
                xmlns:ns7="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns8="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns10="http://www.bcie.org/ProductoBO" xmlns:ns9="http://www.bcie.org/CondicionBO"
                xmlns:ns11="http://www.bcie.org/DeclaracionJuradaBO"
                xmlns:ns12="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:ns13="http://www.bcie.org/ImplementacionPctBO" xmlns:ns14="http://www.bcie.org/DocumentoBO"
                xmlns:ns15="http://www.bcie.org/HerramientaCEBO" xmlns:ns16="http://www.bcie.org/ComisionBO"
                xmlns:ns17="http://www.bcie.org/CatalogoBO" xmlns:desBO="http://www.bcie.org/DesembolsoBO"
                xmlns:ns18="http://www.bcie.org/AdquisicionBO" xmlns:ns19="http://www.bcie.org/ContratoBO"
                xmlns:cteBO="http://www.bcie.org/ClienteBO" xmlns:ns20="http://www.bcie.org/AtributoBO"
                xmlns:ns22="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1"
                xmlns:ns21="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1" xmlns:ns23="http://www.bcie.org/ErrorBO"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/Schema/ConfiguracionProcesosMO.xsd"/>
        <oracle-xsl-mapper:rootElement name="configuracionCondicionesResponse"
                                       namespace="http://www.bcie.org/ConfiguracionProcesosMO"/>
        <oracle-xsl-mapper:param name="configuracionCondicionesResponse"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA03/CondicionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="CondicionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Condiciones/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAR 22 23:34:22 CST 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CondicionPayload>
      <tns:Header>
        <ns12:Operacion>
          <ns7:CodigoOperacion>
            <xsl:value-of select="/ns0:configuracionCondicionesResponse/ns0:configuracionCondiciones/confBO:operacion/operBO:idOperacion"/>
          </ns7:CodigoOperacion>
        </ns12:Operacion>
      </tns:Header>
      <ns12:Operacion>
        <ns7:CodigoOperacion/>
      </ns12:Operacion>
    </tns:CondicionPayload>
  </xsl:template>
</xsl:stylesheet>
