<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/InventoryTransferStoreApp/PollInventoryTransferStoreRMSProxyService" name="PollInventoryTransferStoreRMSProxyService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PollInventoryTransferStoreRMSProxyService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/InventoryTransferStoreApp/PollInventoryTransferStoreRMSProxyService"/>
    <wsdl:binding name="PollInventoryTransferStoreRMSProxyService_ptt-binding" type="pol:PollInventoryTransferStoreRMSProxyService_ptt" xmlns:pol="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/InventoryTransferStoreApp/PollInventoryTransferStoreRMSProxyService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="receive">
            <soap:operation soapAction="receive"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>