<wsdl:definitions
     name="CrearActualizarImplementacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/CrearActualizarImplementacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/CrearActualizarImplementacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarImplementacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearActualizarImplementacion_plt" >
    <plt:role name="CrearActualizarImplementacion_role" >
      <plt:portType name="tns:CrearActualizarImplementacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarImplementacion"
                schemaLocation="../XSD/CrearActualizarImplementacion_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ImplementacionCollection_msg">
        <wsdl:part name="ImplementacionCollection" element="top:ImplementacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearActualizarImplementacion_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:ImplementacionCollection_msg"/>
            <wsdl:output message="tns:ImplementacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
