<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarRolesCategoriaLeccionAprendidaSAD"
     targetNamespace="http://xmlns.bcie.org/LeccionesAprendidasService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.org/LeccionesAprendidasService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarRolesCategoriaLeccionAprendida">
        <plnk:role name="ConsultarRolesCategoriaLeccionAprendidaPT" portType="tns:ConsultarRolesCategoriaLeccionAprendidaPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.org/LeccionesAprendidasService" location="oramds:/apps/Resources/ComponentesComunes/DominioLeccionesAprendidas/LeccionAprendida/V1/Wsdl/ADAPTER/ConsultarRolesCategoriaLeccionAprendidaSAD.wsdl"/>
</wsdl:definitions>
