<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarOperacion/consultarCodExterno" name="consultarCodExterno_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="consultarCodExterno.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarOperacion/consultarCodExterno"/>
    <wsdl:binding name="consultarCodExterno_ptt-binding" type="con:consultarCodExterno_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ActualizarOperacion/consultarCodExterno">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="consultarCodExternoSelect">
            <soap:operation soapAction="consultarCodExternoSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>