<wsdl:definitions name="ResponseItemProtosAdapterService" targetNamespace="http://www.agarcia.mx/ServiceBus/ResponseItemProtosAdapterService" xmlns:tns="http://www.agarcia.mx/ServiceBus/ResponseItemProtosAdapterService" xmlns:ebm="http://www.agarcia.mx/EnterpriseObjects/Item" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Item" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Item/ItemEBM.xsd"/>
        </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestMessage">
    <wsdl:part name="ebmin" element="ebm:CreateItemEBM"/>
  </wsdl:message>
  <wsdl:message name="replyMessage">
    <wsdl:part name="ebmout" element="ebm:CreateItemResponseEBM"/>
  </wsdl:message>
  <wsdl:portType name="responseItemProtosAdapterService_ptt">
    <wsdl:operation name="Create">
      <wsdl:input message="tns:requestMessage"/>
      <wsdl:output message="tns:replyMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="responseItemProtosAdapterService_bind" type="tns:responseItemProtosAdapterService_ptt">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Create">
      <soap:operation style="document" soapAction="Create"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/ResponseItemProtosAdapterService"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/ResponseItemProtosAdapterService"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>