<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://TargetNamespace.com/SyncItemSkuRestReference_Sync_request" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.agarcia.mx/EnterpriseObjects/Item" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Custom" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Item/ItemEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="SyncItemEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Item"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/inputSchema.xsd"/>
            <oracle-xsl-mapper:rootElement name="InputSyncSku" namespace="http://TargetNamespace.com/SyncItemSkuRestReference_Sync_request"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED NOV 18 17:47:25 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:InputSyncSku>
         <tns:code>
            <xsl:value-of select="/ns0:SyncItemEBM/ns0:DataArea/ns0:SyncItem/com:Identification/com:ID"/>
         </tns:code>
         <tns:descripcion>
            <xsl:value-of select="/ns0:SyncItemEBM/ns0:DataArea/ns0:SyncItem/ns0:Description"/>
         </tns:descripcion>
         <tns:depto>
            <xsl:value-of select="/ns0:SyncItemEBM/ns0:DataArea/ns0:SyncItem/ns0:Department"/>
         </tns:depto>
         <tns:status>
            <xsl:value-of select="/ns0:SyncItemEBM/ns0:DataArea/ns0:SyncItem/ns0:Status"/>
         </tns:status>
         <tns:estilo>
            <xsl:value-of select="/ns0:SyncItemEBM/ns0:DataArea/ns0:SyncItem/ns0:Detail"/>
         </tns:estilo>
         <tns:proveedor>
            <xsl:value-of select="/ns0:SyncItemEBM/ns0:DataArea/ns0:SyncItem/ns0:Supplier"/>
         </tns:proveedor>
      </tns:InputSyncSku>
   </xsl:template>
</xsl:stylesheet>