<wsdl:definitions
     name="ConsultarBitacoraProcesoSCR"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoSCR"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoSCR"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoSCR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarBitacoraProcesoSCR_plt" >
    <plt:role name="ConsultarBitacoraProcesoSCR_role" >
      <plt:portType name="tns:ConsultarBitacoraProcesoSCR_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoSCR" schemaLocation="../XSD/ConsultarBitacoraProcesoSCR.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarBitacoraProcesoSCRInput_msg">
        <wsdl:part name="ConsultarBitacoraProcesoSCRInput_msg" element="db:ConsultarBitacoraProcesoSCRInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarBitacoraProcesoSCROutputCollection_msg">
        <wsdl:part name="ConsultarBitacoraProcesoSCROutputCollection" element="db:ConsultarBitacoraProcesoSCROutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarBitacoraProcesoSCR_ptt">
        <wsdl:operation name="ConsultarBitacoraProcesoSCR">
            <wsdl:input message="tns:ConsultarBitacoraProcesoSCRInput_msg"/>
            <wsdl:output message="tns:ConsultarBitacoraProcesoSCROutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
