<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PriceChangeMicroTask" targetNamespace="http://mx.agarcia.ea/Applications/JDA/PriceChange/ProcessMicroTask" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N2="http://mx.agarcia.ea/Applications/JDA/PriceChange/ProcessMicroTask" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="JDAAPIPriceChangeSvc">
      <plnk:role name="MicroTaskPort" portType="WL5G3N2:MicroTaskPort"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Applications/JDA/PriceChange/ProcessMicroTask" location="http://prd-osb.agarcia.com.mx:7004/Applications/JDA/JDAPriceChange/PS/JDAAPIPriceChangeSvc?WSDL"/>
</wsdl:definitions>
