<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ValidarEstadoFlexcube" targetNamespace="http://www.bcie.org/ValidarEstadoFlexcubeMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.bcie.org/ValidarEstadoFlexcubeMO" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ValidarEstadoFlexcube_SB">
      <plnk:role name="ValidarEstadoFlexcubePT" portType="tns:ValidarEstadoFlexcubePT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bcie.org/ValidarEstadoFlexcubeMO" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ValidarEstadoFlexcube/V1/Wsdl/ValidarEstadoFlexcube.wsdl"/>
</wsdl:definitions>
