<wsdl:definitions name="ConsultarTareasActivas_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTareasActivas_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTareasActivas_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTareasActivas_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTareasActivas_DB_plt">
    <plt:role name="ConsultarTareasActivas_DB_role">
      <plt:portType name="tns:ConsultarTareasActivas_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTareasActivas_DB" schemaLocation="../XSD/ConsultarTareasActivas_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTareasActivas_DBInput_msg">
        <wsdl:part name="ConsultarTareasActivas_DBInput_msg" element="db:ConsultarTareasActivas_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTareasActivas_DBOutputCollection_msg">
        <wsdl:part name="ConsultarTareasActivas_DBOutputCollection" element="db:ConsultarTareasActivas_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTareasActivas_DB_ptt">
        <wsdl:operation name="ConsultarTareasActivas_DB">
            <wsdl:input message="tns:ConsultarTareasActivas_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarTareasActivas_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>