<wsdl:definitions name="CrearObservacionCondicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearObservacionCondicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearObservacionCondicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearObservacionCondicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearObservacionCondicion_plt">
    <plt:role name="CrearObservacionCondicion_role">
      <plt:portType name="tns:CrearObservacionCondicion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearObservacionCondicion" schemaLocation="../XSD/CrearObservacionCondicion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ObservacionCondicionCollection_msg">
        <wsdl:part name="ObservacionCondicionCollection" element="top:ObservacionCondicionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearObservacionCondicion_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ObservacionCondicionCollection_msg"/>
            <wsdl:output message="tns:ObservacionCondicionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>