<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.com/CrearActualizarBitacoraDocumento"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.com/CrearActualizarBitacoraDocumento"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:regBiDocMO="http://www.bcie.org/CrearActualizarBitacoraDocumentoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.com/CrearActualizarBitacoraDocumento/types" elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/CrearActualizarBitacoraDocumentoMO" schemaLocation="../Schema/CrearActualizarBitacoraDocumentoMO.xsd"/>
    </xsd:schema>
  </types>
  
  <message name="requestCrearActualizarBitacoraDocumento">
     <part name="request" element="regBiDocMO:requestCrearActualizarBitacoraDocumentoMessage"/>
  </message>
  <message name="responseCrearActualizarBitacoraDocumento">
     <part name="response" element="regBiDocMO:responseCrearActualizarBitacoraDocumentoMessage"/>
  </message>
  
  <portType name="CrearActualizarBitacoraDocumento">
    <operation name="CrearActualizarBitacoraDocumento">
      <input   message="tns:requestCrearActualizarBitacoraDocumento"/>
      <output  message="tns:responseCrearActualizarBitacoraDocumento"/>
    </operation>
  </portType>
  
  <binding name="CrearActualizarBitacoraDocumentoSOAP12Binding" type="tns:CrearActualizarBitacoraDocumento">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CrearActualizarBitacoraDocumento">
      <soap12:operation style="document" soapAction="http://www.bcie.com/CrearActualizarBitacoraDocumento/CrearActualizarBitacoraDocumento"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
  
</definitions>