<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CalcularPlazoCondiciones" name="CalcularPlazoCondiciones-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CalcularPlazoCondiciones.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CalcularPlazoCondiciones"/>
    <wsdl:binding name="CalcularPlazoCondiciones_ptt-binding" type="cal:CalcularPlazoCondiciones_ptt" xmlns:cal="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CalcularPlazoCondiciones">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CalcularPlazoCondiciones">
            <soap:operation soapAction="CalcularPlazoCondiciones"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>