<wsdl:definitions name="VerificarEstadoUsuarioSAD" targetNamespace="http://xmlns.bcie.com/SeguridadService" xmlns:tns="http://xmlns.bcie.com/SeguridadService" xmlns:inp1="http://www.bcie.org/SeguridadMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/SeguridadMO" schemaLocation="../../Schema/SeguridadMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestVerificarEstadoUsuarioMessage">
    <wsdl:part name="VerificarEstadoUsuarioRequest" element="inp1:VerificarEstadoUsuarioRequest"/>
  </wsdl:message>
  <wsdl:message name="responseVerificarEstadoUsuarioMessage">
    <wsdl:part name="VerificarEstadoUsuarioResponse" element="inp1:VerificarEstadoUsuarioResponse"/>
  </wsdl:message>
  <wsdl:portType name="VerificarEstadoUsuarioPT">
    <wsdl:operation name="VerificarEstadoUsuario">
      <wsdl:input message="tns:requestVerificarEstadoUsuarioMessage"/>
      <wsdl:output message="tns:responseVerificarEstadoUsuarioMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="VerificarDatosUsuario12Bnd" type="tns:VerificarEstadoUsuarioPT">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="VerificarEstadoUsuario">
      <soap:operation style="document" soapAction="http://xmlns.bcie.com/SeguridadService/VerificarEstadoUsuario"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://xmlns.bcie.com/SeguridadService"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://xmlns.bcie.com/SeguridadService"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>