<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/OperacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:operMO="http://www.bcie.org/OperacionMO"
                  xmlns:tns="http://xmlns.bcie.com/OperacionService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/OperacionMO" schemaLocation="../../Schema/OperacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
  <wsdl:message name="requestMergeMontoOperacionMessage">
    <wsdl:part name="request" element="operMO:ActualizarMontoOperacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseMergeMontoOperacionMessage">
    <wsdl:part name="response" element="operMO:ActualizarMontoOperacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="MergeMontoOperacionPT">
    <wsdl:operation name="mergeMontoOperacion">
      <wsdl:input message="tns:requestMergeMontoOperacionMessage"/>
      <wsdl:output message="tns:responseMergeMontoOperacionMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MergeMontoOperacionPT12Bnd" type="tns:MergeMontoOperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="mergeMontoOperacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/OperacionService/mergeMontoOperacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>