<wsdl:definitions name="EliminarTreLineaCreditoTCC_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarTreLineaCreditoTCC_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarTreLineaCreditoTCC_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTreLineaCreditoTCC_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarTreLineaCreditoTCC_DB_plt">
    <plt:role name="EliminarTreLineaCreditoTCC_DB_role">
      <plt:portType name="tns:EliminarTreLineaCreditoTCC_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTreLineaCreditoTCC_DB" schemaLocation="../XSD/EliminarTreLineaCreditoTCC_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarTreLineaCreditoTCC_DBInput_msg">
        <wsdl:part name="EliminarTreLineaCreditoTCC_DBInput_msg" element="db:EliminarTreLineaCreditoTCC_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarTreLineaCreditoTCC_DB_ptt">
        <wsdl:operation name="EliminarTreLineaCreditoTCC_DB">
            <wsdl:input message="tns:EliminarTreLineaCreditoTCC_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>