<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidarLoanComplejoSOR"
     targetNamespace="http://www.bcie.org/ValidarLoanComplejoSOR"
     xmlns:tns="http://www.bcie.org/ValidarLoanComplejoSOR"
     xmlns:inp1="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ValidarLoanComplejoBPELRequestMessage">
        <wsdl:part name="ValidarLoanComplejoBPELRequest" element="inp1:ValidarLoanComplejoBPELRequest"/>
    </wsdl:message>
    <wsdl:message name="ValidarLoanComplejoBPELResponseMessage">
        <wsdl:part name="ValidarLoanComplejoBPELResponse" element="inp1:ValidarLoanComplejoBPELResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarLoanComplejo_PT">
        <wsdl:operation name="ValidarLoanComplejoBPEL">
            <wsdl:input message="tns:ValidarLoanComplejoBPELRequestMessage"/>
            <wsdl:output message="tns:ValidarLoanComplejoBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarLoanComplejo_PTSOAP12Bnd" type="tns:ValidarLoanComplejo_PT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ValidarLoanComplejoBPEL">
            <soap12:operation style="document" soapAction="http://www.bcie.org/ValidarLoanComplejoSOR/ValidarLoanComplejoBPEL" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.bcie.org/ValidarLoanComplejoSOR"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.bcie.org/ValidarLoanComplejoSOR"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
