<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationDBRMSReference" xmlns:ns0="http://www.agarcia.mx/EnterpriseObjects/Allocation" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns2="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Allocation/AllocationEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="QueryAllocationEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Allocation"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSDs/QueryAllocationDBRMSReference_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="QueryAllocationDBRMSReferenceSelect_allocParam_itemParamInputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocationDBRMSReference"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE NOV 10 14:19:40 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:QueryAllocationDBRMSReferenceSelect_allocParam_itemParamInputParameters>
         <tns:allocParam>
            <xsl:value-of select="/ns0:QueryAllocationEBM/ns0:DataArea/ns0:QueryAllocation/ns0:POAllocationEBO/ns1:Identification/com:ID"/>
         </tns:allocParam>
         <tns:itemParam>
            <xsl:value-of select="/ns0:QueryAllocationEBM/ns0:DataArea/ns0:QueryAllocation/ns0:POAllocationEBO/ns1:PurchaseOrderLine/ns1:SKU"/>
         </tns:itemParam>
      </tns:QueryAllocationDBRMSReferenceSelect_allocParam_itemParamInputParameters>
   </xsl:template>
</xsl:stylesheet>