<wsdl:definitions name="MapearError" targetNamespace="http://www.bcie.com/MapearError" xmlns:tns="http://www.bcie.com/MapearError" xmlns:mapErrMO="http://www.bcie.org/MapeoErrorMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/MapeoErrorMO" schemaLocation="../Schema/MapeoErrorMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
      <wsdl:part name="request" element="mapErrMO:requestMapeoErrorMessage"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
          <wsdl:part name="response" element="mapErrMO:responseMapeoErrorMessage"/>
    </wsdl:message>
    <wsdl:portType name="MapearError_ptt">
        <wsdl:operation name="MapearError">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MapearError_pttSOAP12Binding" type="tns:MapearError_ptt">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="MapearError">
            <soap12:operation style="document" soapAction="http://www.bcie.com/MapearError/MapearError"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>