<wsdl:definitions
     name="ConsultarTransaccionCondicion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarTransaccionCondicion/ConsultarTransaccionCondicion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarTransaccionCondicion/ConsultarTransaccionCondicion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTransaccionCondicion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarTransaccionCondicion_plt" >
    <plt:role name="ConsultarTransaccionCondicion_role" >
      <plt:portType name="tns:ConsultarTransaccionCondicion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTransaccionCondicion" schemaLocation="../XSD/ConsultarTransaccionCondicion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTransaccionCondicionInput_msg">
        <wsdl:part name="ConsultarTransaccionCondicionInput_msg" element="db:ConsultarTransaccionCondicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTransaccionCondicionOutputCollection_msg">
        <wsdl:part name="ConsultarTransaccionCondicionOutputCollection" element="db:ConsultarTransaccionCondicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTransaccionCondicion_ptt">
        <wsdl:operation name="ConsultarTransaccionCondicion">
            <wsdl:input message="tns:ConsultarTransaccionCondicionInput_msg"/>
            <wsdl:output message="tns:ConsultarTransaccionCondicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
