<wsdl:definitions name="MDMApprovedPriceChangeListenerDBPXY" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/MDMApprovedPriceChangeListenerDBPXY" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeTaskSvcApp/PriceChangeTaskSvc/MDMApprovedPriceChangeListenerDBPXY" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MDMApprovedPriceChangeListenerDBPXY" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="MDMApprovedPriceChangeListenerDBPXY_plt">
    <plt:role name="MDMApprovedPriceChangeListenerDBPXY_role">
      <plt:portType name="tns:MDMApprovedPriceChangeListenerDBPXY_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MDMApprovedPriceChangeListenerDBPXY" schemaLocation="MDMApprovedPriceChangeListenerDBPXY_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="PrcEventsCollection_msg">
        <wsdl:part name="PrcEventsCollection" element="top:PrcEventsCollection"/>
    </wsdl:message>
    <wsdl:portType name="MDMApprovedPriceChangeListenerDBPXY_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:PrcEventsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>