<definitions targetNamespace="http://service.org.bcie.www/" 
name="AvisoCobroDetImplService" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://service.org.bcie.www/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/">
<types>
<xsd:schema>
<xsd:import namespace="http://service.org.bcie.www/" schemaLocation="../XSD/GenerarAvisoCobroDetallado.xsd"/>
</xsd:schema>
</types>
<message name="generarAvisoDet">
<part name="parameters" element="tns:generarAvisoDet"/>
</message>
<message name="generarAvisoDetResponse">
<part name="parameters" element="tns:generarAvisoDetResponse"/>
</message>
<portType name="AvisoCobroDetImpl">
<operation name="generarAvisoDet">
<input wsam:Action="http://service.org.bcie.www/AvisoCobroDetImpl/generarAvisoDetRequest" message="tns:generarAvisoDet"/>
<output wsam:Action="http://service.org.bcie.www/AvisoCobroDetImpl/generarAvisoDetResponse" message="tns:generarAvisoDetResponse"/>
</operation>
</portType>
<binding name="AvisoCobroDetImplPortBinding" type="tns:AvisoCobroDetImpl">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="generarAvisoDet">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="AvisoCobroDetImplService">
<port name="AvisoCobroDetImplPort" binding="tns:AvisoCobroDetImplPortBinding">
<soap:address location="http://hn-obpm-qa.bcie.org:7065/HerramientasOfimatica-context-root/AvisoCobroDetImplPort"/>
</port>
</service>
</definitions>