<wsdl:definitions name="PurchaseOrderService" targetNamespace="http://www.agarcia.mx/ServiceBus/PurchaseOrderService" xmlns:tns="http://www.agarcia.mx/ServiceBus/PurchaseOrderService" xmlns:abm="http://www.oracle.com/retail/integration/rib/RibMessages" xmlns:ebm="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.oracle.com/retail/integration/rib/RibMessages" schemaLocation="../../../../MetaData/Components/Custom/Schemas/RMS_XSD/RibMessages.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/PurchaseOrder" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/PurchaseOrder/PurchaseOrderEBM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="abm:RibMessages"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="response" element="ebm:PurchaseOrderResponseAcknowledgeEBM"/>
    </wsdl:message>
    <wsdl:portType name="purchaseOrder_ptt">
        <wsdl:operation name="proccess">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="purchaseOrder_bind" type="tns:purchaseOrder_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="proccess">
            <soap12:operation style="document" soapAction="proccess" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/PurchaseOrderService"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/PurchaseOrderService"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>