<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConfiguracionProcesos"
     targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/CondicionService"
     xmlns:ns2="http://www.bcie.org/MatrizTCCService"
    >
    <plnk:partnerLinkType name="ConfiguracionCondiciones_BPEL">
        <plnk:role name="ConfiguracionCondicionesPT" portType="tns:ConfiguracionCondicionesPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/ConfiguracionProcesosService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/WSDL/BPEL/ConfiguracionCondicionesSOR.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/CondicionService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Condicion/V1/Wsdl/ADAPTER/ConsultarCondicionByIdEventoSAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/CondicionService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Condicion/V1/Wsdl/ADAPTER/UpsertTransaccionCondicionSAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/CondicionService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Condicion/V1/Wsdl/ADAPTER/ConsultarCondicionByRolSAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/MatrizTCCService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/MatrizTCC/V1/Wsdl/ADAPTER/ActualizarEstadoTCCSAD.wsdl"/>
</wsdl:definitions>
