<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="urn:ConsultarProcesoBPM" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="urn:ConsultarProcesoBPM" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ConsultarCodExternoBPM">
      <plnk:role name="ProcesoBPMPT" portType="tns:ProcesoBPMPT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="urn:ConsultarProcesoBPM" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConsultarProcesoBPMProceso/V1/WSDL/ConsultarProcesoBPM.wsdl"/>
</wsdl:definitions>
