<wsdl:definitions name="ConsultarRolesCategoriaLeccion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarRolesCategoriaLeccion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarRolesCategoriaLeccion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarRolesCategoriaLeccion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarRolesCategoriaLeccion_plt">
    <plt:role name="ConsultarRolesCategoriaLeccion_role">
      <plt:portType name="tns:ConsultarRolesCategoriaLeccion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarRolesCategoriaLeccion" schemaLocation="../XSD/ConsultarRolesCategoriaLeccion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarRolesCategoriaLeccionInput_msg">
        <wsdl:part name="ConsultarRolesCategoriaLeccionInput_msg" element="db:ConsultarRolesCategoriaLeccionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarRolesCategoriaLeccionOutputCollection_msg">
        <wsdl:part name="ConsultarRolesCategoriaLeccionOutputCollection" element="db:ConsultarRolesCategoriaLeccionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarRolesCategoriaLeccion_ptt">
        <wsdl:operation name="ConsultarRolesCategoriaLeccion">
            <wsdl:input message="tns:ConsultarRolesCategoriaLeccionInput_msg"/>
            <wsdl:output message="tns:ConsultarRolesCategoriaLeccionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>