<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSolicitudAproByIdSolicitud" name="ConsultarSolicitudAproByIdSolicitudDB_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarSolicitudAproByIdSolicitud.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSolicitudAproByIdSolicitud"/>
    <wsdl:binding name="ConsultarSolicitudAproByIdSolicitud_ptt-binding" type="con:ConsultarSolicitudAproByIdSolicitud_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSolicitudAproByIdSolicitud">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarSolicitudAproByIdSolicitud">
            <soap:operation soapAction="ConsultarSolicitudAproByIdSolicitud"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>