<wsdl:definitions name="ConsultarValidadoresbyCategoria" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarValidadoresbyCategoria" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarValidadoresbyCategoria" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidadoresbyCategoria" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarValidadoresbyCategoria_plt">
    <plt:role name="ConsultarValidadoresbyCategoria_role">
      <plt:portType name="tns:ConsultarValidadoresbyCategoria_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidadoresbyCategoria" schemaLocation="../XSD/ConsultarValidadoresbyCategoriaV2.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidadoresbyCategoria" schemaLocation="../XSD/ConsultarValidadoresbyCategoriaV2.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarValidadoresbyCategoriaInput_msg">
        <wsdl:part name="ConsultarValidadoresbyCategoriaInput_msg" element="db:ConsultarValidadoresbyCategoriaInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarValidadoresbyCategoriaOutputCollection_msg">
        <wsdl:part name="ConsultarValidadoresbyCategoriaOutputCollection" element="db:ConsultarValidadoresbyCategoriaOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarValidadoresbyCategoria_ptt">
        <wsdl:operation name="ConsultarValidadoresbyCategoria">
            <wsdl:input message="tns:ConsultarValidadoresbyCategoriaInput_msg"/>
            <wsdl:output message="tns:ConsultarValidadoresbyCategoriaOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>