<wsdl:definitions
     name="EliminarMiembroReunion_DB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarMiembroReunion_DB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarMiembroReunion_DB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarMiembroReunion_DB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EliminarMiembroReunion_DB_plt" >
    <plt:role name="EliminarMiembroReunion_DB_role" >
      <plt:portType name="tns:EliminarMiembroReunion_DB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarMiembroReunion_DB" schemaLocation="../XSD/EliminarMiembroReunion_DB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarMiembroReunion_DBInput_msg">
        <wsdl:part name="EliminarMiembroReunion_DBInput_msg" element="db:EliminarMiembroReunion_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarMiembroReunion_DB_ptt">
        <wsdl:operation name="EliminarMiembroReunion_DB">
            <wsdl:input message="tns:EliminarMiembroReunion_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
