<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop">
   <vprop:property name="IdEnmiendaCP" type="xsd:int"/>
   <vprop:property name="IdInstanciaCP" type="xsd:int"/>
   <vprop:property name="IdOperacionCP" type="xsd:int"/>
   <vprop:property name="IdProcesoCP" type="xsd:int"/>
   <vprop:propertyAlias propertyName="tns:IdProcesoCP" part="parameters" messageType="tns2:InicioFormalizacionEnmiendas">
      <vprop:query xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
            36
        </vprop:query>
   </vprop:propertyAlias>
   <vprop:propertyAlias propertyName="tns:IdProcesoCP" part="parameters" messageType="tns2:InicioReasignarFormalizacionEnmiendas">
      <vprop:query xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
            36
        </vprop:query>
   </vprop:propertyAlias>
   <vprop:propertyAlias propertyName="tns:IdEnmiendaCP" part="parameters" messageType="tns2:InicioFormalizacionEnmiendas">
      <vprop:query xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
            /ns:InicioFormalizacionEnmiendas/ns:idEnmienda
        </vprop:query>
   </vprop:propertyAlias>
   <vprop:propertyAlias propertyName="tns:IdOperacionCP" part="parameters" messageType="tns2:InicioFormalizacionEnmiendas">
      <vprop:query xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1" xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1">
            /ns:InicioFormalizacionEnmiendas/ns:Header/ns1:Operacion/ns2:CodigoOperacion
        </vprop:query>
   </vprop:propertyAlias>
   <vprop:propertyAlias propertyName="tns:IdInstanciaCP" part="parameters" messageType="tns2:InicioFormalizacionEnmiendas">
      <vprop:query>
            1
        </vprop:query>
   </vprop:propertyAlias>
   <vprop:propertyAlias propertyName="tns:IdEnmiendaCP" part="parameters" messageType="tns2:InicioReasignarFormalizacionEnmiendas">
      <vprop:query xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
            /ns:InicioReasignarFormalizacionEnmiendas/ns:idEnmienda
        </vprop:query>
   </vprop:propertyAlias>
   <vprop:propertyAlias propertyName="tns:IdOperacionCP" part="parameters" messageType="tns2:InicioReasignarFormalizacionEnmiendas">
      <vprop:query xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PA15FormalizacionEnmiendasProcess" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns2="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1" xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1">
            /ns:InicioReasignarFormalizacionEnmiendas/ns:Header/ns1:Operacion/ns2:CodigoOperacion
        </vprop:query>
   </vprop:propertyAlias>
</wsdl:definitions>
