<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/actualizarCliente_DB" name="actualizarCliente_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="actualizarCliente_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/actualizarCliente_DB"/>
  <wsdl:binding name="actualizarCliente_DB_ptt-binding" type="act:actualizarCliente_DB_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/actualizarCliente_DB">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="actualizarCliente_DB">
      <soap:operation soapAction="actualizarCliente_DB"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>