<wsdl:definitions name="ItemDiffTranslateProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Support/Commons/ItemCatalogSvc/BS/ItemDiffTranslateProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Support/Commons/ItemCatalogSvc/BS/ItemDiffTranslateProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryItemDiff" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/ItemDiffTranslate!1.0/WSDLs/ItemDiffTranslateProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ItemDiffTranslateProcess">
        <plnk:role name="ItemDiffTranslateProcessProvider" portType="client:ItemDiffTranslateProcess"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryItemDiff" location="1ItemDiffTranslateProcessAbstractWSDL.wsdl"/>
    <wsdl:message name="ItemDiffTranslateProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:QueryItemDiffSelect_pTargetAppCode_pId_pAppCode_pCatDef_pParnId_pParnCatIdInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ItemDiffTranslateProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:MdmItemsDiffsCollection"/>
    </wsdl:message>
    <wsdl:portType name="ItemDiffTranslateProcess">
        <wsdl:operation name="translate">
            <wsdl:input message="client:ItemDiffTranslateProcessRequestMessage"/>
            <wsdl:output message="client:ItemDiffTranslateProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ItemDiffTranslateProcessBinding" type="client:ItemDiffTranslateProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="translate">
            <soap:operation style="document" soapAction="translate"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ItemDiffTranslateService_ep">
        <wsdl:port name="ItemDiffTranslateProcess_pt" binding="client:ItemDiffTranslateProcessBinding">
            <soap:address location="http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/ItemDiffTranslate/ItemDiffTranslateService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>