-- UPDATE Catalogo Aporte Ambiental
-- Tabla No.4 FENIX.TCA_APORTE_AMBIENTAL
INSERT INTO FENIX.TCA_APORTE_AMBIENTAL (DESCRIPCION, DESCRIPCION_CORTA, BAN_ESTATUS, CODIGO_EXTERNO, FECHA_REGISTRO) VALUES ('Mitigación al cambio climático','Mitigación al cambio climático',1,'APA-1005',SYSDATE);
INSERT INTO FENIX.TCA_APORTE_AMBIENTAL (DESCRIPCION, DESCRIPCION_CORTA, BAN_ESTATUS, CODIGO_EXTERNO, FECHA_REGISTRO) VALUES ('Adaptación al cambio climático','Adaptación al cambio climático',1,'APA-1006',SYSDATE);
INSERT INTO FENIX.TCA_APORTE_AMBIENTAL (DESCRIPCION, DESCRIPCION_CORTA, BAN_ESTATUS, CODIGO_EXTERNO, FECHA_REGISTRO) VALUES ('Ambos, mitigación y adaptación','Ambos, mitigación y adaptación',1,'APA-1007',SYSDATE);
INSERT INTO FENIX.TCA_APORTE_AMBIENTAL (DESCRIPCION, DESCRIPCION_CORTA, BAN_ESTATUS, CODIGO_EXTERNO, FECHA_REGISTRO) VALUES ('No aplica','No aplica',1,'APA-1008',SYSDATE);
COMMIT;

-- UPDATE Catalogo Aporte Ambiental
-- Tabla No.5 FENIX.TCA_APORTE_AMBIENTAL
UPDATE FENIX.TCA_APORTE_AMBIENTAL SET BAN_ESTATUS = 0 WHERE ID <= 4;
COMMIT;
