<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="urn:ActualizarDetalleEnmiendaSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ActualizarDetalleEnmiendaSAD" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:mtccMO="http://www.bcie.org/MatrizTCCMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/MatrizTCCMO"
                  schemaLocation="../../Schema/MatrizTCCMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ActualizarDetalleEnmiendaRequestMessage">
    <wsdl:part name="ActualizarDetalleEnmiendaRequest" element="mtccMO:ActualizarDetalleEnmiendaRequest"/>
  </wsdl:message>
  <wsdl:message name="ActualizarDetalleEnmiendaResponseMessage">
    <wsdl:part name="ActualizarDetalleEnmiendaResponse" element="mtccMO:ActualizarDetalleEnmiendaResponse"/>
  </wsdl:message>
  <wsdl:portType name="ActualizarDetalleEnmiendaRequest_PT">
    <wsdl:operation name="actualizarDetalleEnmiendaRequest">
      <wsdl:input message="tns:ActualizarDetalleEnmiendaRequestMessage"/>
      <wsdl:output message="tns:ActualizarDetalleEnmiendaResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ActualizarDetalleEnmiendaRequest_PT12Bnd" type="tns:ActualizarDetalleEnmiendaRequest_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizarDetalleEnmiendaRequest">
      <soap12:operation style="document"
                        soapAction="urn:ActualizarDetalleEnmiendaSAD/actualizarDetalleEnmiendaRequest"/>
      <wsdl:input>
        <soap12:body use="literal" parts="ActualizarDetalleEnmiendaRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="ActualizarDetalleEnmiendaResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>