<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarUsuarioAprobacionByIdAprobacion_DB" name="EliminarUsuarioAprobacionByIdAprobacion_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarUsuarioAprobacionByIdAprobacion_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarUsuarioAprobacionByIdAprobacion_DB"/>
    <wsdl:binding name="EliminarUsuarioAprobacionByIdAprobacion_DB_ptt-binding" type="elim:EliminarUsuarioAprobacionByIdAprobacion_DB_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarUsuarioAprobacionByIdAprobacion_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarUsuarioAprobacionByIdAprobacion_DB">
            <soap:operation soapAction="EliminarUsuarioAprobacionByIdAprobacion_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>