<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DesaCeterisMOMIIOSB/SBProjectDummiASN/BDQueryASNMDMDet" name="BDQueryASNMDMDet-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="BDQueryASNMDMDet.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DesaCeterisMOMIIOSB/SBProjectDummiASN/BDQueryASNMDMDet"/>
    <wsdl:binding name="BDQueryASNMDMDet_ptt-binding" type="bdq:BDQueryASNMDMDet_ptt" xmlns:bdq="http://xmlns.oracle.com/pcbpel/adapter/db/DesaCeterisMOMIIOSB/SBProjectDummiASN/BDQueryASNMDMDet">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BDQueryASNMDMDetSelect">
            <soap:operation soapAction="BDQueryASNMDMDetSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>