<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PRODiffRest" targetNamespace="http://xmlns.oracle.com/RetailOperMK/PROCreateSizeProcess/PRODiffRest" xmlns:tns="http://xmlns.oracle.com/RetailOperMK/PROCreateSizeProcess/PRODiffRest" xmlns:inp1="http://mx.agarcia.ea/Applications/Prototipos/CreateColorNXSD" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="PRODiffRest">
      <plnk:role name="PRODiffRestProvider" portType="tns:PRODiffRest_ptt"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://mx.agarcia.ea/Applications/Prototipos/CreateColorNXSD" schemaLocation="../Schemas/nxsd_diff.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="UpsertDiff_inputMessage">
      <wsdl:part name="request" element="inp1:upsertDiffRequest"/>
   </wsdl:message>
   <wsdl:message name="UpsertDiff_outputMessage">
      <wsdl:part name="reply" element="inp1:upsertDiffResponse"/>
   </wsdl:message>
   <wsdl:portType name="PRODiffRest_ptt">
      <wsdl:operation name="UpsertDiff">
         <wsdl:input message="tns:UpsertDiff_inputMessage"/>
         <wsdl:output message="tns:UpsertDiff_outputMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
