<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http//www.bcie.org/PropagarTransferenciaRecursosSOR"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http//www.bcie.org/PropagarTransferenciaRecursosSOR"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="http//www.bcie.org/PropagarTransferenciaRecursosSOR/types"
                elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestPropagarTransferenciaRecursosMessage">
    <part name="request" element="desMO:PropagarTransferenciaRecursosRequest"/>
  </message>
  <message name="responsePropagarTransferenciaRecursosMessage">
    <part name="response" element="desMO:PropagarTransferenciaRecursosResponse"/>
  </message>
  <portType name="PropagarTransferenciaRecursos_PT">
    <operation name="propagarTransferenciaRecursos">
      <input message="tns:requestPropagarTransferenciaRecursosMessage"/>
      <output message="tns:responsePropagarTransferenciaRecursosMessage"/>
    </operation>
  </portType>
  <binding name="PropagarTransferenciaRecursos_PTSOAP12Binding" type="tns:PropagarTransferenciaRecursos_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="propagarTransferenciaRecursos">
      <soap12:operation style="document"
                        soapAction="http//www.bcie.org/PropagarTransferenciaRecursosSOR/propagarTransferenciaRecursos"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>