<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:ns0="http://xmlns.banesco.com/eopt/AlertSmsQuanticAdv_V1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns3="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:ns5="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns9="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:eoAlert="http://xmlns.banesco.com/eo/Alert_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Fee_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Card_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Payee_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Utility/AlertSmsQuanticAdv/AlertSmsQuanticAdv_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AlertSmsQuanticAdvRq"
                                       namespace="http://xmlns.banesco.com/eopt/AlertSmsQuanticAdv_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [WED MAY 30 17:15:56 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <soap:createMessages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                         xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                         xmlns:soap="http://connections.quanticvision.com/banescobl/public/soap">
      <identity xsi:type="xsd:string">
        <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', 'AlertSMSQuantic.User', 'VALUE', '' )"/>
      </identity>
      <credential xsi:type="xsd:string">
        <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', 'AlertSMSQuantic.Password', 'VALUE', '' )"/>
      </credential>
      <data xsi:type="soap:ArrayOfMessageRequest">
        <!--Zero or more repetitions:-->
        <item xsi:type="soap:MessageRequest">
          <!--You may enter the following 18 items in any order-->
          <id xsi:type="xsd:string">
            <xsl:value-of select="string ( xp20:format-dateTime (xp20:current-dateTime ( ), '[Y0001][M01][D01]T[H01][m01][s01]' ))"/>
          </id>
          <from xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:From"/>
          </from>
          <destination xsi:type="xsd:string">
            <xsl:value-of select="concat (/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:DeliveryInstruction/eoAlert:Contact/ns8:Locator/ns8:Phone/ns8:AreaCode, /ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:DeliveryInstruction/eoAlert:Contact/ns8:Locator/ns8:Phone/ns8:PhoneNum )"/>
          </destination>
          <type xsi:type="xsd:string">sms</type>
          <!-- En caso de utilizar plantillas personalizadas por Quantic este campo buscara en un DVM la plantilla correspondiente -->
          <!--<template_name xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateIdent"/>
          </template_name>-->
          <template_name xsi:type="xsd:string">PruebaSMS</template_name>
          <tags xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:Tags"/>
          </tags>
          <attachments xsi:type="xsd:string"></attachments>
          <app_source xsi:type="xsd:string">
            <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', 'AlertSMSQuantic.AppSource', 'VALUE', '' )"/>
          </app_source>
          <P1 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:Text"/>
          </P1>
          <!--<P1 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter1']/eoAlert:Value"/>
          </P1>
          <P2 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter2']/eoAlert:Value"/>
          </P2>
          <P3 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter3']/eoAlert:Value"/>
          </P3>
          <P4 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter4']/eoAlert:Value"/>
          </P4>
          <P5 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter5']/eoAlert:Value"/>
          </P5>
          <P6 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter6']/eoAlert:Value"/>
          </P6>
          <P7 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter7']/eoAlert:Value"/>
          </P7>
          <P8 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter8']/eoAlert:Value"/>
          </P8>
          <P9 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter9']/eoAlert:Value"/>
          </P9>
          <P10 xsi:type="xsd:string">
            <xsl:value-of select="/ns0:AlertSmsQuanticAdvRq/ns0:Alert/eoAlert:MessageContent/eoAlert:TemplateParameters/eoAlert:Parameter[eoAlert:Key = 'Parameter10']/eoAlert:Value"/>
          </P10>-->
        </item>
      </data>
    </soap:createMessages>
  </xsl:template>
</xsl:stylesheet>