<wsdl:definitions name="ConsultarUsuarioTareasDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarUsuarioTareasDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarUsuarioTareasDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarUsuarioTareasDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarUsuarioTareasDB_plt">
    <plt:role name="ConsultarUsuarioTareasDB_role">
      <plt:portType name="tns:ConsultarUsuarioTareasDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarUsuarioTareasDB" schemaLocation="../XSD/ConsultarUsuarioTareasDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarUsuarioTareasDBInput_msg">
        <wsdl:part name="ConsultarUsuarioTareasDBInput_msg" element="db:ConsultarUsuarioTareasDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarUsuarioTareasDBOutputCollection_msg">
        <wsdl:part name="ConsultarUsuarioTareasDBOutputCollection" element="db:ConsultarUsuarioTareasDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarUsuarioTareasDB_ptt">
        <wsdl:operation name="ConsultarUsuarioTareasDB">
            <wsdl:input message="tns:ConsultarUsuarioTareasDBInput_msg"/>
            <wsdl:output message="tns:ConsultarUsuarioTareasDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>