<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Evaluacion"
     targetNamespace="http://xmlns.bcie.com/EvaluacionService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://xmlns.bcie.com/EvaluacionService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EliminarCuestionarioPT_PLT">
        <plnk:role name="EliminarCuestionarioPT_Role" portType="ns1:EliminarCuestionarioPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/EvaluacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Evaluacion/V1/Wsdl/BPEL/EliminarCuestionarioSOR.wsdl"/>
</wsdl:definitions>
