<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CrearReciboPagoSAD"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/CrearReciboPagoSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/CrearReciboPagoSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CrearReciboPago">
        <plnk:role name="CrearReciboPago_ptt" portType="tns:CrearReciboPago_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/CrearReciboPagoSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/GestionCobro/V1/Wsdl/ADAPTER/CrearReciboPagoSAD.wsdl"/>
</wsdl:definitions>
