<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.bcie.com/ClienteService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/ClienteService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarOperacionByIdCliente_SB">
        <plnk:role name="ClientePT" portType="tns:ClientePT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/ClienteService" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/Cliente/V1/Wsdl/ADAPTER/ConsultarClienteByIdSAD.wsdl"/>
</wsdl:definitions>
