<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="queryMerchadhierarTranslations" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslateApp/MerchandiseHierarchyTranslate/queryMerchadhierarTranslations" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslateApp/MerchandiseHierarchyTranslate/queryMerchadhierarTranslations" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/queryMerchadhierarTranslations" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="queryMerchadhierarTranslations_plt">
      <plt:role name="queryMerchadhierarTranslations_role">
         <plt:portType name="tns:queryMerchadhierarTranslations_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/queryMerchadhierarTranslations" schemaLocation="../Schemas/queryMerchadhierarTranslations_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="queryMerchadhierarTranslationsSelect_inputParameters">
      <wsdl:part name="queryMerchadhierarTranslationsSelect_inputParameters" element="top:queryMerchadhierarTranslationsSelect_pDivision_pDepto_pClase_pTipoInputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmMerchandhierarTranslationsCollection_msg">
      <wsdl:part name="MdmMerchandhierarTranslationsCollection" element="top:MdmMerchandhierarTranslationsCollection"/>
   </wsdl:message>
   <wsdl:portType name="queryMerchadhierarTranslations_ptt">
      <wsdl:operation name="queryMerchadhierarTranslationsSelect">
         <wsdl:input message="tns:queryMerchadhierarTranslationsSelect_inputParameters"/>
         <wsdl:output message="tns:MdmMerchandhierarTranslationsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
