<wsdl:definitions name="CrearBitacoraTarea" targetNamespace="http://www.bcie.com/CrearBitacoraTarea" xmlns:tns="http://www.bcie.com/CrearBitacoraTarea" xmlns:regBitMO="http://www.bcie.org/CrearBitacoraTareaMO" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/CrearBitacoraTareaMO"
                        schemaLocation="../../../CrearBitacoraTarea/V1/Schema/CrearBitacoraTareaMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
      <wsdl:part name="request" element="regBitMO:requestCrearBitacoraTareaMessage"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
          <wsdl:part name="response" element="regBitMO:responseCrearBitacoraTareaMessage"/>
    </wsdl:message>
    <wsdl:portType name="CrearBitacoraTarea_ptt">
        <wsdl:operation name="CrearBitacoraTarea">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CrearBitacoraTarea_pttSOAP12Binding" type="tns:CrearBitacoraTarea_ptt">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="CrearBitacoraTarea">
            <soap12:operation style="document" soapAction="http://www.bcie.com/CrearBitacoraTarea/CrearBitacoraTarea"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>