<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/CorreoElectronicoService" 
            xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/CorreoElectronicoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:correoMO="http://www.bcie.org/CorreoMO"
             >
             
 <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="../Schema/CorreoElectronicoMO.xsd"/>
		</xsd:schema>
	</wsdl:types>
 <message name="requestCrearBitacoraCorreoElectronicoMessage">
  <part name="requestCrearBitacoraCorreoElectronicoMessage"
        element="correoMO:crearBitacoraCorreoElectronicoRequest"/>
 </message>
 <message name="responseCrearBitacoraCorreoElectronicoMessage">
  <part name="responsetCrearBitacoraCorreoElectronicoMessage"
        element="correoMO:crearBitacoraCorreoElectronicoResponse"/>
 </message>
 <portType name="CrearBitacoraCorreoElectronicoPT">
  <operation name="CrearBitacoraCorreoElectronico">
   <input message="tns:requestCrearBitacoraCorreoElectronicoMessage"/>
   <output message="tns:responseCrearBitacoraCorreoElectronicoMessage"/>
  </operation>
 </portType>
 <binding name="CrearBitacoraCorreoElectronicoBnd" type="tns:CrearBitacoraCorreoElectronicoPT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="CrearBitacoraCorreoElectronico">
   <soap12:operation style="document"
                     soapAction="http://xmlns.bcie.com/CorreoElectronicoService/CrearBitacoraCorreoElectronico"/>
   <input>
    <soap12:body use="literal" parts="requestCrearBitacoraCorreoElectronicoMessage"/>
   </input>
   <output>
    <soap12:body use="literal" parts="responsetCrearBitacoraCorreoElectronicoMessage"/>
   </output>
  </operation>
 </binding>
</definitions>