<wsdl:definitions name="ActualizarOperacionProceso_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarOperacionProceso_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarOperacionProceso_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarOperacionProceso_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarOperacionProceso_DB_plt">
    <plt:role name="ActualizarOperacionProceso_DB_role">
      <plt:portType name="tns:ActualizarOperacionProceso_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarOperacionProceso_DB" schemaLocation="../XSD/ActualizarOperacionProceso_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarOperacionProceso_DBInput_msg">
        <wsdl:part name="ActualizarOperacionProceso_DBInput_msg" element="db:ActualizarOperacionProceso_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarOperacionProceso_DB_ptt">
        <wsdl:operation name="ActualizarOperacionProceso_DB">
            <wsdl:input message="tns:ActualizarOperacionProceso_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>