<wsdl:definitions name="RMSFindItem" targetNamespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMSFindItem" xmlns:tns="http://mx.agarcia.ea/Applications/RetailMerchandising/RMSFindItem" xmlns:inp1="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindItemDbReference" xmlns:inp2="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntity" xmlns:inp3="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <plnk:partnerLinkType name="RMSFindItem">
        <plnk:role name="RMSFindItemProvider" portType="tns:RMSFindItemPort"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSFindItemDbReference" schemaLocation="../Resources/JCA/RMSFindItem/RMSFindItemDbReference.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntity" schemaLocation="../../../../../Capabilities/Core/Items/CreateItemEntitySvc/Schemas/CreateItemEntitySchema.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" schemaLocation="../../../../../Capabilities/Foundation/Schemas/Commons/AGStandardMessageSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="RMSFindItemReq" element="inp1:RMSFindItemDbReferenceInput"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="RMSFindItemRes" element="inp2:createItemRequest"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="RMSFindItemError" element="inp3:messageError"/>
    </wsdl:message>
    <wsdl:portType name="RMSFindItemPort">
        <wsdl:operation name="RMSFindItemOperation">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="RMSFindItemOperationfault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RMSFindItemBinding" type="tns:RMSFindItemPort">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="RMSFindItemOperation">
            <soap:operation style="document" soapAction="RMSFindItemOperation"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMSFindItem"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMSFindItem"/>
            </wsdl:output>
            <wsdl:fault name="RMSFindItemOperationfault">
                <soap:fault name="RMSFindItemOperationfault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>