<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ClienteEsIFI_DecisionService"
     targetNamespace="http://xmlns.oracle.com/ClienteEsIFI/ClienteEsIFI_DecisionService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/ClienteEsIFI/ClienteEsIFI_DecisionService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ValidarTipoClienteIFI">
        <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/ClienteEsIFI/ClienteEsIFI_DecisionService" location="oramds:/apps/Resources/ComponentesComunes/BusinessRules/ValidarClienteEsIFI/V1/Wsdl/ClienteEsIFI_DecisionService.wsdl"/>
</wsdl:definitions>
