<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/QuerySupplierRMSReference" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/SupplierParty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:cust="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/QuerySupplierRMSReference_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxSoaVendorVwCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QuerySupplierRMSReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/SupplierParty/SupplierPartyEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="QuerySupplierPartyResponseEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/SupplierParty"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU DEC 10 14:17:44 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Code"/>
   <xsl:param name="Message"/>
   <xsl:param name="Detail"/>
   <xsl:param name="InstanceID"/>
   <xsl:param name="TrackingID"/>
   <xsl:param name="Operation"/>
   <xsl:param name="Interface"/>
   <xsl:param name="Target"/>
   <xsl:template match="/">
      <tns:QuerySupplierPartyResponseEBM>
         <tns:Response>
            <com:Code>
               <xsl:value-of select="$Code"/>
            </com:Code>
            <com:Message>
               <xsl:value-of select="$Message"/>
            </com:Message>
            <com:Detail>
               <xsl:value-of select="$Detail"/>
            </com:Detail>
            <com:InstanceID>
               <xsl:value-of select="$InstanceID"/>
            </com:InstanceID>
            <com:TrackingID>
               <xsl:value-of select="$TrackingID"/>
            </com:TrackingID>
            <com:Operation>
               <xsl:value-of select="$Operation"/>
            </com:Operation>
            <com:Interface>
               <xsl:value-of select="$Interface"/>
            </com:Interface>
            <com:Application>
               <com:Name>
                  <xsl:value-of select="$Target"/>
               </com:Name>
            </com:Application>
         </tns:Response>
         <tns:ProcessSupplierPartyEBO>
            <tns:Identification>
               <com:ID>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:supplier"/>
               </com:ID>
            </tns:Identification>
            <tns:PartyContact>
               <com:OrganizationName>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:supName"/>
               </com:OrganizationName>
               <com:ContactAddressCommunication>
                  <com:LineOne>
                     <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:add1"/>
                  </com:LineOne>
                  <com:CityName>
                     <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:city"/>
                  </com:CityName>
                  <com:StateName>
                     <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:state"/>
                  </com:StateName>
                  <com:PostalCode>
                     <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:post"/>
                  </com:PostalCode>
               </com:ContactAddressCommunication>
               <com:ContactPhoneCommunication>
                  <com:DialNumber>
                     <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:contactPhone"/>
                  </com:DialNumber>
               </com:ContactPhoneCommunication>
               <com:ContactFaxCommunication>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:contactFax"/>
               </com:ContactFaxCommunication>
               <com:ContactEmailCommunication>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:contactEmail"/>
               </com:ContactEmailCommunication>
            </tns:PartyContact>
            <tns:Status>
               <com:Code>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:supStatus"/>
               </com:Code>
            </tns:Status>
            <tns:Note>
               <com:Author>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:supplier"/>
               </com:Author>
               <com:LanguageCode>
                  <xsl:value-of select="/ns0:XxSoaVendorVwCollection/ns0:XxSoaVendorVw/ns0:supName"/>
               </com:LanguageCode>
            </tns:Note>
         </tns:ProcessSupplierPartyEBO>
      </tns:QuerySupplierPartyResponseEBM>
   </xsl:template>
</xsl:stylesheet>