<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/PropagarContratoDesembolsoSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/PropagarContratoDesembolsoSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/ConsultarDesembolsosByIdSAD"
     xmlns:ns2="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD"
     xmlns:ns3="http://www.bcie.org/CrearActualizarDesembolsoSAD"
     xmlns:ns4="http://www.bcie.org/DesembolsoMO"
    >
    <plnk:partnerLinkType name="PropagarContratoDesembolso">
        <plnk:role name="PropagarContratoDesembolso_PT" portType="tns:PropagarContratoDesembolso_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/PropagarContratoDesembolsoSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/PropagarContratoDesembolsoSOR.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/ConsultarDesembolsosByIdSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ConsultarDesembolsosByIdSAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/ConsultarDesembolsosByIdV2SAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V2/Wsdl/ADAPTER/ConsultarDesembolsoByIDV2SAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/CrearActualizarDesembolsoSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/CrearActualizarDesembolsosSAD.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
