<wsdl:definitions name="ObtenerCuestionario" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Cuestionario/ObtenerCuestionario" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Cuestionario/ObtenerCuestionario" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerCuestionario" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ObtenerCuestionario_plt">
    <plt:role name="ObtenerCuestionario_role">
      <plt:portType name="tns:ObtenerCuestionario_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerCuestionario" schemaLocation="../XSD/ObtenerCuestionario.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerCuestionarioInput_msg">
        <wsdl:part name="ObtenerCuestionarioInput_msg" element="db:ObtenerCuestionarioInput"/>
    </wsdl:message>
    <wsdl:message name="ObtenerCuestionarioOutputCollection_msg">
        <wsdl:part name="ObtenerCuestionarioOutputCollection" element="db:ObtenerCuestionarioOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerCuestionario_ptt">
        <wsdl:operation name="ObtenerCuestionario">
            <wsdl:input message="tns:ObtenerCuestionarioInput_msg"/>
            <wsdl:output message="tns:ObtenerCuestionarioOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>