CREATE TABLE TCA_TAREA_CON_BTN_DIN 
(
  ID NUMBER NOT NULL 
, COMPONENTE VARCHAR2(50) NOT NULL 
, ID_TAREA_BPM NUMBER NOT NULL 
, ID_PRPODUCTO NUMBER NOT NULL 
, ACCION VARCHAR2(50) NOT NULL 
, PRODUCTO_CONFIGURADO NUMBER(1) NOT NULL 
, RETORNO NUMBER(1) NOT NULL 
, VISIBLE NUMBER(1) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT SYSDATE 
, CONSTRAINT TCA_TAREA_CON_BTN_DIN_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE TCA_TAREA_CON_BTN_DIN
ADD CONSTRAINT TCA_TAR_CON_BTN_DIN_CAT_PRODUCTO_FK FOREIGN KEY
(
  ID_PRPODUCTO 
)
REFERENCES CAT_PRODUCTO
(
  ID 
)
ENABLE;

ALTER TABLE TCA_TAREA_CON_BTN_DIN
ADD CONSTRAINT TCA_TAR_CON_BTN_DIN_TCA_TAREA_BPM_FK FOREIGN KEY
(
  ID_TAREA_BPM 
)
REFERENCES TCA_TAREA_BPM
(
  ID 
)
ENABLE;

ALTER TABLE TCA_TAREA_CON_BTN_DIN
ADD CONSTRAINT TCA_TAREA_CON_BTN_DIN_PRO_CHK CHECK 
(PRODUCTO_CONFIGURADO IN(0, 1))
ENABLE;

ALTER TABLE TCA_TAREA_CON_BTN_DIN
ADD CONSTRAINT TCA_TAREA_CON_BTN_DIN_RET_CHK CHECK 
(RETORNO IN(0, 1))
ENABLE;

ALTER TABLE TCA_TAREA_CON_BTN_DIN
ADD CONSTRAINT TCA_TAREA_CON_BTN_DIN_VIS_CHK CHECK 
(VISIBLE IN(0, 1))
ENABLE;

COMMENT ON TABLE TCA_TAREA_CON_BTN_DIN IS 'Tabla de configuración para determinar el outcome del proceso BPM aplicable a cualquier proceso en turno';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.ID IS 'Identificador de la tabla';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.COMPONENTE IS 'Nombre del componente a mostrar BTN = Boton';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.ID_TAREA_BPM IS 'Identificador de Tarea a la que le pertenese la colexión del registro';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.ID_PRPODUCTO IS 'Identificador del producto que se vincula con el Proceso y Tarea correspondiente';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.ACCION IS 'Identificador de Accion del componente registrado';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.PRODUCTO_CONFIGURADO IS 'Bandera que determina si el producto a su izq esta activo o desactivado (1= true 0= false)';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.RETORNO IS 'Bandera que determina un retorno de actividad (1= true 0= false)';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.VISIBLE IS 'Bandera que determina la visibilidad del componente (1= true 0= false)';
COMMENT ON COLUMN TCA_TAREA_CON_BTN_DIN.FECHA_REGISTRO IS 'Fecha de alta del registro';




--Secuencia
CREATE SEQUENCE TCA_TAREA_CON_BTN_DIN_SEQ;

-- Disparador SIMPLE
CREATE OR REPLACE TRIGGER TCA_TAREA_CON_BTN_DIN_TRG
BEFORE INSERT ON TCA_TAREA_CON_BTN_DIN
FOR EACH ROW
DECLARE
    new_id NUMBER;

BEGIN
    SELECT TCA_TAREA_CON_BTN_DIN_SEQ.NEXTVAL
     INTO new_id FROM Dual;
    :NEW.ID := new_id;
END;



INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_1', '55', '1', 'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS', '1', '0', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_1', '55', '1', 'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS', '1', '1', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_1', '55', '1', 'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS', '0', '0', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_1', '55', '1', 'SOLICITAR_AJUSTE_POR_FUENTES_EXTERNAS', '0', '1', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_2', '55', '1', 'ENVIAR_COFI', '1', '0', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_2', '55', '1', 'ENVIAR_COFI', '1', '1', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_2', '55', '1', 'ENVIAR_COFI', '0', '0', '0');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_2', '55', '1', 'ENVIAR_COFI', '0', '1', '0');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_3', '55', '1', 'ENVIAR_RESPONSABLE', '1', '0', '0');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_3', '55', '1', 'ENVIAR_RESPONSABLE', '1', '1', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_3', '55', '1', 'ENVIAR_RESPONSABLE', '0', '0', '1');
INSERT INTO TCA_TAREA_CON_BTN_DIN (COMPONENTE, ID_TAREA_BPM, ID_PRPODUCTO, ACCION, PRODUCTO_CONFIGURADO, RETORNO, VISIBLE) VALUES ('BTN_3', '55', '1', 'ENVIAR_RESPONSABLE', '0', '1', '1');


