<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ums/BanescoServiceBusApp/Commons/UMS_Email_Notification" name="UMS_Email_Notification-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UMS_Email_Notification.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ums/BanescoServiceBusApp/Commons/UMS_Email_Notification"/>
    <wsdl:binding name="SendNotification_ptt-binding" type="ums:SendNotification_ptt" xmlns:ums="http://xmlns.oracle.com/pcbpel/adapter/ums/BanescoServiceBusApp/Commons/UMS_Email_Notification">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SendNotification">
            <soap:operation soapAction="SendNotification"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>