package org.bcie.fenix.common.model.vo.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 22 18:30:19 CDT 2016
// ---------------------------------------------------------------------
public interface ContratoDesembolsoTreeVO extends ViewObject {
    boolean desestimarContratoDesembolso(Long idContrato);

    Row getContratoSeleccionado();

    oracle.jbo.domain.Number getpIdContrato();

    Integer obtenerTipoMonedaMontoFormalizado(Long idOperacion);

    Boolean desestimarContratosEnCascada();

    Boolean verTcaEstadoContratosRegDesem();

    void getContratoPorSolicitud(Long idSolicitud);

    void filtraContratoByIdSolicitud(Long idSolicitud);

    Long getContratoDefault();

    void inicializarDatos(Long idSolicitud);

    void filtrarContratosParaTree(Long idSolicitud);

    void setpIdSolicitudDesembolso(Long value);
}

