package org.bcie.fenix.common.model.vo.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 25 19:53:15 CDT 2016
// ---------------------------------------------------------------------
public interface LineaCreditoDesembolsosVO extends ViewObject {
    Row getLineaCreditoDesembolso(oracle.jbo.domain.Number idLista);


    Row getRowSeleccionada();

    Long getLineasCreditoByIdOperacion(Long idOperacion);

    Long getpIdOperacion();

    oracle.jbo.domain.Number getpIdSolicitud();

    void setpIdOperacion(Long value);

    void setpIdSolicitud(oracle.jbo.domain.Number value);


    void establecerRowComoActual(Long idLinea, Long idSolicitud);

    Row[] getLineasCreditoSolicitud(Long idSolicitud);
}

