<wsdl:definitions
     name="CrearBitacoraReglasDesembolso"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearBitacoraReglasDesembolso"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearBitacoraReglasDesembolso"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearBitacoraReglasDesembolso"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearBitacoraReglasDesembolso_plt" >
    <plt:role name="CrearBitacoraReglasDesembolso_role" >
      <plt:portType name="tns:CrearBitacoraReglasDesembolso_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearBitacoraReglasDesembolso" schemaLocation="../XSD/CrearBitacoraReglasDesembolso_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TbiReglaDesembolsoCollection_msg">
        <wsdl:part name="TbiReglaDesembolsoCollection" element="top:TbiReglaDesembolsoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearBitacoraReglasDesembolso_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TbiReglaDesembolsoCollection_msg"/>
            <wsdl:output message="tns:TbiReglaDesembolsoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
