<wsdl:definitions name="ActualizarCondicion_BS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarCondicion_BS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ActualizarCondicion_BS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarCondicion_BS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarCondicion_BS_plt">
    <plt:role name="ActualizarCondicion_BS_role">
      <plt:portType name="tns:ActualizarCondicion_BS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarCondicion_BS" schemaLocation="../XSD/ActualizarCondicion_BS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="CondicionCollection_msg">
        <wsdl:part name="CondicionCollection" element="top:CondicionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarCondicion_BS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:CondicionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>