<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PROCreateColorProcess" targetNamespace="http://xmlns.oracle.com/RetailOperMK/PROCreateColorProcess/PROCreateColorProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/RetailOperMK/PROCreateColorProcess/PROCreateColorProcess" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateColorEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateColorEntity" schemaLocation="../Schemas/CreateColorEntitySchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="PROCreateColorProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:createColorRequest"/>
   </wsdl:message>
   <wsdl:message name="PROCreateColorProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:createColorResponse"/>
   </wsdl:message>
   <wsdl:portType name="PROCreateColorProcess">
      <wsdl:operation name="create">
         <wsdl:input message="client:PROCreateColorProcessRequestMessage"/>
         <wsdl:output message="client:PROCreateColorProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="PROCreateColorProcess">
      <plnk:role name="PROCreateColorProcessProvider" portType="client:PROCreateColorProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
