<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://ww.bcie.org/EliminarUsuarioAprobacionByIdSolicitudService"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://ww.bcie.org/EliminarUsuarioAprobacionByIdSolicitudService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="EliminarUsuarioAprobacionRequestMessage">
    <wsdl:part name="request" element="solAproMO:EliminarUsuarioAprobacionByIdSolicitudRequest"/>
  </wsdl:message>
  <wsdl:message name="EliminarUsuarioAprobacionResponseMessage">
    <wsdl:part name="response" element="solAproMO:EliminarUsuarioAprobacionByIdSolicitudResponse"/>
  </wsdl:message>
  <wsdl:portType name="EliminarUsuarioAprobacionByIdAprobacionPT">
    <wsdl:operation name="eliminarUsuarioAprobacion">
      <wsdl:input message="tns:EliminarUsuarioAprobacionRequestMessage"/>
      <wsdl:output message="tns:EliminarUsuarioAprobacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EliminarUsuarioAprobacionByIdAprobacion12Bnd"
                type="tns:EliminarUsuarioAprobacionByIdAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="eliminarUsuarioAprobacion">
      <soap12:operation style="document"
                        soapAction="http://ww.bcie.org/EliminarUsuarioAprobacionByIdSolicitudService/eliminarUsuarioAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>