<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/EliminarMiembroReunionService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/EliminarMiembroReunionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="EliminarMiembroReunionRequestMessage">
    <part name="request" element="solAproMO:EliminarMiembroReunionRequest"/>
  </message>
  <message name="EliminarMiembroReunionResponseMessage">
    <part name="response" element="solAproMO:EliminarMiembroReunionResponse"/>
  </message>
  <portType name="EliminarMiembroReunionPT">
    <operation name="eliminarMiembroReunion">
      <input message="tns:EliminarMiembroReunionRequestMessage"/>
      <output message="tns:EliminarMiembroReunionResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarMiembroReunion12Bnd" type="tns:EliminarMiembroReunionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarMiembroReunion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/EliminarMiembroReunionService/eliminarMiembroReunion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>