<wsdl:definitions name="ConsultarTcaComision" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaComision" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaComision" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTcaComision" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTcaComision_plt">
    <plt:role name="ConsultarTcaComision_role">
      <plt:portType name="tns:ConsultarTcaComision_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTcaComision" schemaLocation="../XSD/ConsultarTcaComision.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTcaComisionInput_msg">
        <wsdl:part name="ConsultarTcaComisionInput_msg" element="db:ConsultarTcaComisionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTcaComisionOutputCollection_msg">
        <wsdl:part name="ConsultarTcaComisionOutputCollection" element="db:ConsultarTcaComisionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTcaComision_ptt">
        <wsdl:operation name="ConsultarTcaComision">
            <wsdl:input message="tns:ConsultarTcaComisionInput_msg"/>
            <wsdl:output message="tns:ConsultarTcaComisionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>