<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateRetailStore" name="RMSCreateRetailStore-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSCreateRetailStore.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateRetailStore"/>
    <wsdl:binding name="RMSCreateRetailStoreMessage_ptt-binding" type="rms:RMSCreateRetailStoreMessage_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/jms/Proyectos/Applications/RMSCreateRetailStore">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSCreateRetailStoreMessage">
            <soap:operation soapAction="RMSCreateRetailStoreMessage"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>