<wsdl:definitions name="ConsultarAprobacion_LineasCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarAprobacion_LineasCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarAprobacion_LineasCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAprobacion_LineasCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarAprobacion_LineasCredito_plt">
    <plt:role name="ConsultarAprobacion_LineasCredito_role">
      <plt:portType name="tns:ConsultarAprobacion_LineasCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAprobacion_LineasCredito" schemaLocation="../XSD/ConsultarAprobacion_LineasCredito.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAprobacion_LineasCreditoInput_msg">
        <wsdl:part name="ConsultarAprobacion_LineasCreditoInput_msg" element="db:ConsultarAprobacion_LineasCreditoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAprobacion_LineasCreditoOutputCollection_msg">
        <wsdl:part name="ConsultarAprobacion_LineasCreditoOutputCollection" element="db:ConsultarAprobacion_LineasCreditoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAprobacion_LineasCredito_ptt">
        <wsdl:operation name="ConsultarAprobacion_LineasCredito">
            <wsdl:input message="tns:ConsultarAprobacion_LineasCreditoInput_msg"/>
            <wsdl:output message="tns:ConsultarAprobacion_LineasCreditoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>