<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/TerminoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/TerminoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:terMO="http://www.bcie.org/TerminoMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/TerminoMO" schemaLocation="../../Schema/TerminoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ActualizarTerminoRequestMessage">
    <part name="request" element="terMO:ActualizarTerminoRequest"/>
  </message>
  <message name="ActualizarTerminoResponseMessage">
    <part name="response" element="terMO:ActualizarTerminoResponse"/>
  </message>
  <portType name="ActualizarTerminoPT">
    <operation name="actualizarTermino">
      <input message="tns:ActualizarTerminoRequestMessage"/>
      <output message="tns:ActualizarTerminoResponseMessage"/>
    </operation>
  </portType>
  <binding name="Termino12Bnd" type="tns:ActualizarTerminoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="actualizarTermino">
      <soap12:operation style="document" soapAction="http://www.bcie.org/TerminoService/actualizarTermino"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>