<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/LeccionesAprendidas/Payload/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://www.bcie.org/TerminoBO" xmlns:ns2="http://www.bcie.org/ReglaBO"
                xmlns:ns3="http://www.bcie.org/OperacionBO" xmlns:ns4="http://www.bcie.org/CommonBO"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:leccion="http://www.bcie.org/LeccionAprendidaBO" xmlns:ns5="http://www.bcie.org/LineaCreditoBO"
                xmlns:ns6="http://www.bcie.org/MatrizTCCBO"
                xmlns:ns7="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns8="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns9="http://www.bcie.org/ProductoBO" xmlns:ns10="http://www.bcie.org/CondicionBO"
                xmlns:ns11="http://www.bcie.org/DeclaracionJuradaBO"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:ns12="http://www.bcie.org/DocumentoBO" xmlns:ns13="http://www.bcie.org/HerramientaCEBO"
                xmlns:ns14="http://www.bcie.org/ComisionBO" xmlns:ns15="http://www.bcie.org/CatalogoBO"
                xmlns:ns16="http://www.bcie.org/DesembolsoBO" xmlns:ns17="http://www.bcie.org/ContratoBO"
                xmlns:ns18="http://www.bcie.org/ClienteBO" xmlns:ns19="http://www.bcie.org/AtributoBO"
                xmlns:ns21="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:ns20="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA17/LeccionesAprendidasPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="LeccionesAprendidasPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/LeccionesAprendidas/Payload/V1"/>
        <oracle-xsl-mapper:param name="leccionesAprendidasDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA17/LeccionesAprendidasPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="LeccionesAprendidasPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/LeccionesAprendidas/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 11 17:39:12 CST 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:LeccionesAprendidasPayload>
      <ns0:Header>
        <header:Operacion>
          <ns7:CodigoOperacion>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:CodigoOperacion"/>
          </ns7:CodigoOperacion>
          <ns7:NombreOperacion>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:NombreOperacion"/>
          </ns7:NombreOperacion>
          <ns7:ResponsableOperacion>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:ResponsableOperacion"/>
          </ns7:ResponsableOperacion>
          <ns7:CodigoCliente>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:CodigoCliente"/>
          </ns7:CodigoCliente>
          <ns7:NombreCliente>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:NombreCliente"/>
          </ns7:NombreCliente>
          <ns7:CodigoProducto>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:CodigoProducto"/>
          </ns7:CodigoProducto>
          <ns7:NombreProducto>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:NombreProducto"/>
          </ns7:NombreProducto>
          <ns7:MontoSolicitado>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:MontoSolicitado"/>
          </ns7:MontoSolicitado>
          <ns7:Pais>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:Pais"/>
          </ns7:Pais>
          <ns7:idSectorInstitucional>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:idSectorInstitucional"/>
          </ns7:idSectorInstitucional>
          <ns7:idEncargado>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:idEncargado"/>
          </ns7:idEncargado>
          <ns7:idRol>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:idRol"/>
          </ns7:idRol>
          <ns7:descripcionRol>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Operacion/ns7:descripcionRol"/>
          </ns7:descripcionRol>
        </header:Operacion>
        <header:Tarea>
          <ns21:CodigoTarea>228</ns21:CodigoTarea>
          <ns21:NombreTarea>Validar Lección Aprendida</ns21:NombreTarea>
          <ns21:CodigoRol>90</ns21:CodigoRol>
          <ns21:NombreRol>Dinamico</ns21:NombreRol>
          <ns21:CodigoProceso>38</ns21:CodigoProceso>
          <ns21:NombreProceso>Lecciones Aprendidas</ns21:NombreProceso>
        </header:Tarea>
        <header:Proceso>
          <ns8:IdProceso>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:IdProceso"/>
          </ns8:IdProceso>
          <ns8:CodigoProceso>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:CodigoProceso"/>
          </ns8:CodigoProceso>
          <ns8:NombreProceso>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:NombreProceso"/>
          </ns8:NombreProceso>
          <ns8:EsProcesoCore>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:EsProcesoCore"/>
          </ns8:EsProcesoCore>
          <ns8:RolIniciaProceso>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:RolIniciaProceso"/>
          </ns8:RolIniciaProceso>
          <ns8:UsuarioIniciaProceso>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:UsuarioIniciaProceso"/>
          </ns8:UsuarioIniciaProceso>
          <ns8:InstanciaProceso>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:InstanciaProceso"/>
          </ns8:InstanciaProceso>
          <ns8:IdFlujo>
            <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Header/header:Proceso/ns8:IdFlujo"/>
          </ns8:IdFlujo>
        </header:Proceso>
        <xsl:for-each select="/ns0:LeccionesAprendidasPayload/ns0:Header/parameter:ParameterType">
          <parameter:ParameterType>
            <parameter:parameterName>
              <xsl:value-of select="parameter:parameterName"/>
            </parameter:parameterName>
            <parameter:parameterValue>
              <xsl:value-of select="parameter:parameterValue"/>
            </parameter:parameterValue>
          </parameter:ParameterType>
        </xsl:for-each>
      </ns0:Header>
      <ns0:Configuration>
        <ns0:retorno>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Configuration/ns0:retorno"/>
        </ns0:retorno>
        <ns0:resultado>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:Configuration/ns0:resultado"/>
        </ns0:resultado>
      </ns0:Configuration>
      <ns0:LeccionesAprendidas>
        <xsl:for-each select="/ns0:LeccionesAprendidasPayload/ns0:LeccionesAprendidas/ns0:LeccionAprendida">
          <ns0:LeccionAprendida>
            <leccion:idLeccionAprendida>
              <xsl:value-of select="leccion:idLeccionAprendida"/>
            </leccion:idLeccionAprendida>
            <leccion:descripcion>
              <xsl:value-of select="leccion:descripcion"/>
            </leccion:descripcion>
            <leccion:recomendacion>
              <xsl:value-of select="leccion:recomendacion"/>
            </leccion:recomendacion>
            <leccion:nivelIncidencia>
              <xsl:value-of select="leccion:nivelIncidencia"/>
            </leccion:nivelIncidencia>
            <leccion:usuario>
              <xsl:value-of select="leccion:usuario"/>
            </leccion:usuario>
            <leccion:estado>
              <ns15:Id>
                <xsl:value-of select="leccion:estado/ns15:Id"/>
              </ns15:Id>
              <ns15:Descripcion>
                <xsl:value-of select="leccion:estado/ns15:Descripcion"/>
              </ns15:Descripcion>
              <ns15:DescripcionCorta>
                <xsl:value-of select="leccion:estado/ns15:DescripcionCorta"/>
              </ns15:DescripcionCorta>
              <ns15:estatus>
                <xsl:value-of select="leccion:estado/ns15:estatus"/>
              </ns15:estatus>
              <ns15:codigoExterno>
                <xsl:value-of select="leccion:estado/ns15:codigoExterno"/>
              </ns15:codigoExterno>
            </leccion:estado>
            <leccion:producto>
              <ns9:idProducto>
                <xsl:value-of select="leccion:producto/ns9:idProducto"/>
              </ns9:idProducto>
              <ns9:descripcion>
                <xsl:value-of select="leccion:producto/ns9:descripcion"/>
              </ns9:descripcion>
              <ns9:descripcionCorta>
                <xsl:value-of select="leccion:producto/ns9:descripcionCorta"/>
              </ns9:descripcionCorta>
              <ns9:fechaRegistro>
                <xsl:value-of select="leccion:producto/ns9:fechaRegistro"/>
              </ns9:fechaRegistro>
              <ns9:codExterno>
                <xsl:value-of select="leccion:producto/ns9:codExterno"/>
              </ns9:codExterno>
            </leccion:producto>
            <leccion:operacion>
              <ns3:idOperacion>
                <xsl:value-of select="leccion:operacion/ns3:idOperacion"/>
              </ns3:idOperacion>
              <ns3:responsable>
                <xsl:value-of select="leccion:operacion/ns3:responsable"/>
              </ns3:responsable>
              <ns3:oficina>
                <xsl:value-of select="leccion:operacion/ns3:oficina"/>
              </ns3:oficina>
              <ns3:nombre>
                <xsl:value-of select="leccion:operacion/ns3:nombre"/>
              </ns3:nombre>
            </leccion:operacion>
            <leccion:proceso>
              <ns8:IdProceso>
                <xsl:value-of select="leccion:proceso/ns8:IdProceso"/>
              </ns8:IdProceso>
              <ns8:CodigoProceso>
                <xsl:value-of select="leccion:proceso/ns8:CodigoProceso"/>
              </ns8:CodigoProceso>
              <ns8:NombreProceso>
                <xsl:value-of select="leccion:proceso/ns8:NombreProceso"/>
              </ns8:NombreProceso>
              <ns8:EsProcesoCore>
                <xsl:value-of select="leccion:proceso/ns8:EsProcesoCore"/>
              </ns8:EsProcesoCore>
              <ns8:RolIniciaProceso>
                <xsl:value-of select="leccion:proceso/ns8:RolIniciaProceso"/>
              </ns8:RolIniciaProceso>
              <ns8:UsuarioIniciaProceso>
                <xsl:value-of select="leccion:proceso/ns8:UsuarioIniciaProceso"/>
              </ns8:UsuarioIniciaProceso>
              <ns8:InstanciaProceso>
                <xsl:value-of select="leccion:proceso/ns8:InstanciaProceso"/>
              </ns8:InstanciaProceso>
              <ns8:IdFlujo>
                <xsl:value-of select="leccion:proceso/ns8:IdFlujo"/>
              </ns8:IdFlujo>
            </leccion:proceso>
            <leccion:tarea>
              <ns21:CodigoTarea>
                <xsl:value-of select="leccion:tarea/ns21:CodigoTarea"/>
              </ns21:CodigoTarea>
              <ns21:NombreTarea>
                <xsl:value-of select="leccion:tarea/ns21:NombreTarea"/>
              </ns21:NombreTarea>
              <ns21:CodigoRol>
                <xsl:value-of select="leccion:tarea/ns21:CodigoRol"/>
              </ns21:CodigoRol>
              <ns21:NombreRol>
                <xsl:value-of select="leccion:tarea/ns21:NombreRol"/>
              </ns21:NombreRol>
              <ns21:CodigoProceso>
                <xsl:value-of select="leccion:tarea/ns21:CodigoProceso"/>
              </ns21:CodigoProceso>
              <ns21:NombreProceso>
                <xsl:value-of select="leccion:tarea/ns21:NombreProceso"/>
              </ns21:NombreProceso>
            </leccion:tarea>
            <leccion:categorias>
              <xsl:for-each select="leccion:categorias/leccion:categoria">
                <leccion:categoria>
                  <ns15:Id>
                    <xsl:value-of select="ns15:Id"/>
                  </ns15:Id>
                  <ns15:Descripcion>
                    <xsl:value-of select="ns15:Descripcion"/>
                  </ns15:Descripcion>
                  <ns15:DescripcionCorta>
                    <xsl:value-of select="ns15:DescripcionCorta"/>
                  </ns15:DescripcionCorta>
                  <ns15:estatus>
                    <xsl:value-of select="ns15:estatus"/>
                  </ns15:estatus>
                  <ns15:codigoExterno>
                    <xsl:value-of select="ns15:codigoExterno"/>
                  </ns15:codigoExterno>
                  <leccion:rol>
                    <ns15:Id>
                      <xsl:value-of select="leccion:rol/ns15:Id"/>
                    </ns15:Id>
                    <ns15:Descripcion>
                      <xsl:value-of select="leccion:rol/ns15:Descripcion"/>
                    </ns15:Descripcion>
                    <ns15:DescripcionCorta>
                      <xsl:value-of select="leccion:rol/ns15:DescripcionCorta"/>
                    </ns15:DescripcionCorta>
                    <ns15:estatus>
                      <xsl:value-of select="leccion:rol/ns15:estatus"/>
                    </ns15:estatus>
                    <ns15:codigoExterno>
                      <xsl:value-of select="leccion:rol/ns15:codigoExterno"/>
                    </ns15:codigoExterno>
                  </leccion:rol>
                  <leccion:usuario>
                    <xsl:value-of select="leccion:usuario"/>
                  </leccion:usuario>
                  <leccion:respuesta>
                    <xsl:value-of select="leccion:respuesta"/>
                  </leccion:respuesta>
                </leccion:categoria>
              </xsl:for-each>
            </leccion:categorias>
          </ns0:LeccionAprendida>
        </xsl:for-each>
      </ns0:LeccionesAprendidas>
      <ns0:EquipoPayload>
        <ns0:UsuarioInicio>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoPayload/ns0:UsuarioInicio"/>
        </ns0:UsuarioInicio>
        <ns0:EmisorOpinion>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoPayload/ns0:EmisorOpinion"/>
        </ns0:EmisorOpinion>
        <ns0:RevisorResultados>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoPayload/ns0:RevisorResultados"/>
        </ns0:RevisorResultados>
        <ns0:GerenteCredito>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoPayload/ns0:GerenteCredito"/>
        </ns0:GerenteCredito>
      </ns0:EquipoPayload>
      <ns0:EquipoEjecucionPayload>
        <ns0:UsuarioInicio>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoEjecucionPayload/ns0:UsuarioInicio"/>
        </ns0:UsuarioInicio>
        <ns0:EmisorOpinion>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoEjecucionPayload/ns0:EmisorOpinion"/>
        </ns0:EmisorOpinion>
        <ns0:RevisorResultados>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoEjecucionPayload/ns0:RevisorResultados"/>
        </ns0:RevisorResultados>
        <ns0:GerenteCredito>
          <xsl:value-of select="/ns0:LeccionesAprendidasPayload/ns0:EquipoEjecucionPayload/ns0:GerenteCredito"/>
        </ns0:GerenteCredito>
      </ns0:EquipoEjecucionPayload>
      <xsl:for-each select="/ns0:LeccionesAprendidasPayload/parameter:ParameterType">
        <parameter:ParameterType>
          <parameter:parameterName>
            <xsl:value-of select="parameter:parameterName"/>
          </parameter:parameterName>
          <parameter:parameterValue>
            <xsl:value-of select="parameter:parameterValue"/>
          </parameter:parameterValue>
        </parameter:ParameterType>
      </xsl:for-each>
    </ns0:LeccionesAprendidasPayload>
  </xsl:template>
</xsl:stylesheet>
