<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ElegibilidadProcess" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/ElegibilidadProcess" xmlns:tns6="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1" xmlns:param="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ElegibilidadProcessPortTypePartnerLinkType">
      <plnk:role name="ElegibilidadProcessPortTypeProvider">
         <plnk:portType name="tns:ElegibilidadProcessPortType"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:types>
      <xsd:schema targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ElegibilidadProcess" elementFormDefault="qualified">
         <xsd:import namespace="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1" schemaLocation="../../Schema/Comun/Header/V1/HeaderOPN.xsd"/>
         <xsd:import namespace="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1" schemaLocation="../../Schema/Comun/Parameter/V1/ParameterOPN.xsd"/>
         <xsd:element name="inicioElegibilidad">
            <xsd:complexType>
               <xsd:sequence>
                  <xsd:element name="Header" type="tns6:Header"/>
                  <xsd:element name="EsReactivacion" type="xsd:boolean"/>
                  <xsd:element ref="param:ParameterType" minOccurs="0" maxOccurs="unbounded"/>
               </xsd:sequence>
            </xsd:complexType>
         </xsd:element>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="inicioElegibilidad">
      <wsdl:part name="parameters" element="tns:inicioElegibilidad"/>
   </wsdl:message>
   <wsdl:portType name="ElegibilidadProcessPortType">
      <wsdl:operation name="inicioElegibilidad">
         <wsdl:input message="tns:inicioElegibilidad"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="ElegibilidadProcessBinding" type="tns:ElegibilidadProcessPortType">
      <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="inicioElegibilidad">
         <wsdlsoap:operation style="document" soapAction="inicioElegibilidad"/>
         <wsdl:input>
            <wsdlsoap:body use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
