<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarCumplimientoCondiciones/ConsultarCumplimientoCondiciones" name="ConsultarCumplimientoCondiciones_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarCumplimientoCondiciones.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarCumplimientoCondiciones/ConsultarCumplimientoCondiciones"/>
    <wsdl:binding name="ConsultarCumplimientoCondiciones_ptt-binding" type="con:ConsultarCumplimientoCondiciones_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarCumplimientoCondiciones/ConsultarCumplimientoCondiciones">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarCumplimientoCondiciones">
            <soap:operation soapAction="ConsultarCumplimientoCondiciones"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>