<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidarEstadoFlexcube"
     targetNamespace="http://www.bcie.org/ValidarEstadoFlexcubeMO"
     xmlns:tns="http://www.bcie.org/ValidarEstadoFlexcubeMO"
     xmlns:inp1="http://www.bcie.org/ValidarEstadoFlexcubeMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/ValidarEstadoFlexcubeMO" schemaLocation="../Schema/ValidarEstadoFlexcubeMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ValidarEstadoFlexcubeRequestMessage">
        <wsdl:part name="ValidarEstadoFlexcubeRequest" element="tns:ValidarEstadoFlexcubeRequest"/>
    </wsdl:message>
    <wsdl:message name="ValidarEstadoFlexcubeResponseMessage">
        <wsdl:part name="ValidarEstadoFlexcubeResponse" element="tns:ValidarEstadoFlexcubeResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarEstadoFlexcubePT">
        <wsdl:operation name="ValidarEstadoFlexcube">
            <wsdl:input message="tns:ValidarEstadoFlexcubeRequestMessage"/>
            <wsdl:output message="tns:ValidarEstadoFlexcubeResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarEstadoFlexcubePTSOAP12Bnd" type="tns:ValidarEstadoFlexcubePT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ValidarEstadoFlexcube">
            <soap12:operation style="document" soapAction="ValidarEstadoFlexcube" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.bcie.org/ValidarEstadoFlexcubeMO"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.bcie.org/ValidarEstadoFlexcubeMO"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
