<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/EvaluacionProcess"
                  xmlns:tns7="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"
                  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns6="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                  xmlns:param="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/EvaluacionProcess">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/EvaluacionProcess"
                  schemaLocation="../../Schema/PC06/EvaluacionProcess.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="InicioEvaluacion">
    <wsdl:part name="parameters" element="tns:InicioEvaluacion"/>
  </wsdl:message>
  <wsdl:message name="FinEvaluacion">
    <wsdl:part name="parameters" element="tns:FinEvaluacion"/>
  </wsdl:message>
  <wsdl:portType name="EvaluacionProcessPortType">
    <wsdl:operation name="InicioEvaluacion">
      <wsdl:input message="tns:InicioEvaluacion"/>
    </wsdl:operation>
    <wsdl:operation name="FinEvaluacion">
      <wsdl:input message="tns:FinEvaluacion"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EvaluacionProcessBinding" type="tns:EvaluacionProcessPortType">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="InicioEvaluacion">
      <wsdlsoap:operation style="document" soapAction="InicioEvaluacion"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="FinEvaluacion">
      <wsdlsoap:operation style="document" soapAction="FinEvaluacion"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <plnk:partnerLinkType name="EvaluacionProcessPortTypePartnerLinkType">
    <plnk:role name="EvaluacionProcessPortTypeProvider">
      <plnk:portType name="tns:EvaluacionProcessPortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
</wsdl:definitions>
