<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSBuyerApp/RMSBuyer/RMSBuyerDBBS" name="RMSBuyerDBBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSBuyerDBBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSBuyerApp/RMSBuyer/RMSBuyerDBBS"/>
    <wsdl:binding name="RMSBuyerDBBS_ptt-binding" type="rms:RMSBuyerDBBS_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/db/RMSBuyerApp/RMSBuyer/RMSBuyerDBBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="selectByPrimaryKey">
            <soap:operation soapAction="selectByPrimaryKey"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>