<wsdl:definitions name="RMSBuyerDBBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSBuyerApp/RMSBuyer/RMSBuyerDBBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RMSBuyerApp/RMSBuyer/RMSBuyerDBBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/RMSBuyerDBBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="RMSBuyerDBBS_plt">
    <plt:role name="RMSBuyerDBBS_role">
      <plt:portType name="tns:RMSBuyerDBBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/RMSBuyerDBBS" schemaLocation="RMSBuyerDBBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="selectByPrimaryKey_inputParameters">
        <wsdl:part name="selectByPrimaryKey_inputParameters" element="top:BuyerPrimaryKey"/>
    </wsdl:message>
    <wsdl:message name="BuyerCollection_msg">
        <wsdl:part name="BuyerCollection" element="top:BuyerCollection"/>
    </wsdl:message>
    <wsdl:portType name="RMSBuyerDBBS_ptt">
        <wsdl:operation name="selectByPrimaryKey">
            <wsdl:input message="tns:selectByPrimaryKey_inputParameters"/>
            <wsdl:output message="tns:BuyerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>