<wsdl:definitions
     name="ConsultarComisionByIdLineaCredito"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarComisionByIdLineaCredito"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarComisionByIdLineaCredito"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionByIdLineaCredito"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarComisionByIdLineaCredito_plt" >
    <plt:role name="ConsultarComisionByIdLineaCredito_role" >
      <plt:portType name="tns:ConsultarComisionByIdLineaCredito_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionByIdLineaCredito" schemaLocation="../XSD/ConsultarComisionByIdLineaCredito.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarComisionByIdLineaCreditoInput_msg">
        <wsdl:part name="ConsultarComisionByIdLineaCreditoInput_msg" element="db:ConsultarComisionByIdLineaCreditoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarComisionByIdLineaCreditoOutputCollection_msg">
        <wsdl:part name="ConsultarComisionByIdLineaCreditoOutputCollection" element="db:ConsultarComisionByIdLineaCreditoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarComisionByIdLineaCredito_ptt">
        <wsdl:operation name="ConsultarComisionByIdLineaCredito">
            <wsdl:input message="tns:ConsultarComisionByIdLineaCreditoInput_msg"/>
            <wsdl:output message="tns:ConsultarComisionByIdLineaCreditoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
