<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="MerchandiseHierarchyTranslateProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Support/Commons/MerchandiseHierarchyTranslateProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Support/Commons/MerchandiseHierarchyTranslateProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/queryMerchadhierarTranslations" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/queryMerchadhierarTranslations" location="../Schemas/queryMerchadhierarTranslations_table.xsd"/>
   <wsdl:message name="MerchandiseHierarchyTranslateProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:queryMerchadhierarTranslationsSelect_pDivision_pDepto_pClase_pTipoInputParameters"/>
   </wsdl:message>
   <wsdl:message name="MerchandiseHierarchyTranslateProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:MdmMerchandhierarTranslationsCollection"/>
   </wsdl:message>
   <wsdl:portType name="MerchandiseHierarchyTranslateProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:MerchandiseHierarchyTranslateProcessRequestMessage"/>
         <wsdl:output message="client:MerchandiseHierarchyTranslateProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="MerchandiseHierarchyTranslateProcess">
      <plnk:role name="MerchandiseHierarchyTranslateProcessProvider" portType="client:MerchandiseHierarchyTranslateProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
