<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://ww.bcie.org/EliminarTreLineaCreditoService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ww.bcie.org/EliminarTreLineaCreditoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="EliminarTreLineaCreditoTCCRequestMessage">
    <part name="request" element="linCrBO:EliminarTreLineaCreditoTCCRequest"/>
  </message>
  <message name="EliminarTreLineaCreditoTCCResponseMessage">
    <part name="response" element="linCrBO:EliminarTreLineaCreditoTCCResponse"/>
  </message>
  <portType name="EliminarTreLineaCreditoTCCPT">
    <operation name="eliminarTreLineaCreditoTCC">
      <input message="tns:EliminarTreLineaCreditoTCCRequestMessage"/>
      <output message="tns:EliminarTreLineaCreditoTCCResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarTreLineaCreditoTCC12Bnd" type="tns:EliminarTreLineaCreditoTCCPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarTreLineaCreditoTCC">
      <soap12:operation style="document"
                        soapAction="http://ww.bcie.org/EliminarTreLineaCreditoService/eliminarTreLineaCreditoTCC"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>