<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.bice.org/PropagarLineaCreditoService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.bice.org/PropagarLineaCreditoService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="PropagarLineaCredito">
      <plnk:role name="PropagarLineaCreditoPT" portType="tns:PropagarLineaCreditoPT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bice.org/PropagarLineaCreditoService" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/PropagarLineaCreditoSOR.wsdl"/>
</wsdl:definitions>
