<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/CostChange" xmlns:ns0="http://mx.agarcia.ea/Capabilities/Foundation/Party/CostChangeTask" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:ns3="http://mx.agarcia.ea/Canonical/Commons/Types/v1" xmlns:ns4="http://mx.agarcia.ea/Canonical/Commons/Languages/v1" xmlns:ns8="http://mx.agarcia.ea/Canonical/Commons/Currencies/v1" xmlns:ns10="http://mx.agarcia.ea/Canonical/Commons/Countries/v1" xmlns:AGSH="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" xmlns:ns11="http://mx.agarcia.ea/Canonical/Commons/RetailStore/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns13="http://mx.agarcia.ea/Canonical/Commons/ChangeCost/v1" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://mx.agarcia.ea/Canonical/Commons/Enums/v1" xmlns:ns2="http://mx.agarcia.ea/Canonical/Commons/LocationsCommon/v1" xmlns:ns5="http://mx.agarcia.ea/Canonical/Commons/Suppliers/v1" xmlns:ns6="http://mx.agarcia.ea/Canonical/Commons/Items/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns7="http://mx.agarcia.ea/BusinessAreas/Support/Enterprise/Commons/v1" xmlns:ns9="http://mx.agarcia.ea/BusinessAreas/Support/Enterprise/BusinessUnitTypeCodeEnum/v1" xmlns:cost="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/CostChangeRequestProcess/v1.0" xmlns:AGSM="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" xmlns:ns12="http://mx.agarcia.ea/Canonical/Commons/Persons/v1" xmlns:client="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/CostChange/v1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CostChangeRequestProcessWSDL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="costChangeExcelParsingResponse" namespace="http://mx.agarcia.ea/Capabilities/Foundation/Party/CostChangeTask"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://192.1.50.179:7003/Applications/RetailMerchandising/RMS/RMSCostChange/PS/RMSCreateCostChangePXY/v1.0?WSDL"/>
            <oracle-xsl-mapper:rootElement name="createCostChangeEventRequest" namespace="http://mx.agarcia.ea/Applications/RetailMerchandising/RMS/CostChange"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JUN 06 11:49:02 GMT-06:00 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:createCostChangeEventRequest>
         <tns:event>
            <ns13:effectiveDate>
               <xsl:value-of select="/ns0:costChangeExcelParsingResponse/ns0:event[2]/ns13:effectiveDate"/>
            </ns13:effectiveDate>
            <ns13:expirationDate>
               <xsl:value-of select="/ns0:costChangeExcelParsingResponse/ns0:event[2]/ns13:expirationDate"/>
            </ns13:expirationDate>
            <ns13:scope>
               <xsl:value-of select="/ns0:costChangeExcelParsingResponse/ns0:event[2]/ns13:scope"/>
            </ns13:scope>
            <ns13:cause>3</ns13:cause>
            <ns13:currency>MXN</ns13:currency>
            <ns13:percentage>0.3</ns13:percentage>
            <ns13:retailStores>
               <ns13:retailStore>
                  <ns11:storeID>
                     <xsl:value-of select="/ns0:costChangeExcelParsingResponse/ns0:event[2]/ns13:businessStores/ns13:businessUnit"/>
                  </ns11:storeID>
               </ns13:retailStore>
            </ns13:retailStores>
            <ns13:changes>
               <xsl:for-each select="/ns0:costChangeExcelParsingResponse/ns0:event">
                  <xsl:choose>
                     <xsl:when test="ns13:changes/ns13:change/ns13:cost != &quot;ECCOST&quot;">
                        <ns13:change>
                           <ns13:cost>
                              <xsl:value-of select="ns13:changes/ns13:change/ns13:cost"/>
                           </ns13:cost>
                           <ns13:item>
                              <ns6:id>
                                 <xsl:value-of select="ns13:changes/ns13:change/ns13:item/ns6:id"/>
                              </ns6:id>
                              <ns6:description>
                                 <xsl:value-of select="ns13:changes/ns13:change/ns13:item/ns6:name"/>
                              </ns6:description>
                           </ns13:item>
                        </ns13:change>
                     </xsl:when>
                  </xsl:choose>
               </xsl:for-each>
            </ns13:changes>
            <ns13:supplierID>
               <ns5:supplierID>
                  <xsl:value-of select="/ns0:costChangeExcelParsingResponse/ns0:event[2]/ns13:supplierID/ns5:supplierID"/>
               </ns5:supplierID>
            </ns13:supplierID>
         </tns:event>
      </tns:createCostChangeEventRequest>
   </xsl:template>
</xsl:stylesheet>