<wsdl:definitions
     name="ConsultarCatProducto"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCatProducto"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCatProducto"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCatProducto"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarCatProducto_plt" >
    <plt:role name="ConsultarCatProducto_role" >
      <plt:portType name="tns:ConsultarCatProducto_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCatProducto" schemaLocation="../XSD/ConsultarCatProducto.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarCatProductoInput_msg">
        <wsdl:part name="ConsultarCatProductoInput_msg" element="db:ConsultarCatProductoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarCatProductoOutputCollection_msg">
        <wsdl:part name="ConsultarCatProductoOutputCollection" element="db:ConsultarCatProductoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCatProducto_ptt">
        <wsdl:operation name="ConsultarCatProducto">
            <wsdl:input message="tns:ConsultarCatProductoInput_msg"/>
            <wsdl:output message="tns:ConsultarCatProductoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
