<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderDetail" name="DBRMSOrderDetail-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBRMSOrderDetail.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderDetail"/>
    <wsdl:binding name="DBRMSOrderDetail_ptt-binding" type="dbr:DBRMSOrderDetail_ptt" xmlns:dbr="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderDetail">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBRMSOrderDetailSelect">
            <soap:operation soapAction="DBRMSOrderDetailSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>