<wsdl:definitions name="DBRMSOrderDetail" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderDetail" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBRMSOrderDetail" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBRMSOrderDetail" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="DBRMSOrderDetail_plt">
    <plt:role name="DBRMSOrderDetail_role">
      <plt:portType name="tns:DBRMSOrderDetail_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBRMSOrderDetail" schemaLocation="DBRMSOrderDetail_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="DBRMSOrderDetailSelect_inputParameters">
        <wsdl:part name="DBRMSOrderDetailSelect_inputParameters" element="top:DBRMSOrderDetailSelect_OrderNumInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaOrdersVwCollection_msg">
        <wsdl:part name="XxSoaOrdersVwCollection" element="top:XxSoaOrdersVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBRMSOrderDetail_ptt">
        <wsdl:operation name="DBRMSOrderDetailSelect">
            <wsdl:input message="tns:DBRMSOrderDetailSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaOrdersVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>