<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ValidarLimiteDestinoSOR" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.bcie.org/ValidarLimiteDestinoSOR" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ValidaLimiteDestino_SB">
      <plnk:role name="ValidarLimiteDestinoPT" portType="tns:ValidarLimiteDestinoPT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bcie.org/ValidarLimiteDestinoSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/ValidarLimiteDestinoSOR.wsdl"/>
</wsdl:definitions>
