<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ValidarReglasDesembolso"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                  xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                  xmlns:tns="http://www.bcie.org/ValidarReglasDesembolso" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:ns1="http://www.bcie.org/ConsultarTreReglasDesembolso"
                  xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                  xmlns:ns3="http://www.bcie.org/CrearBitacoraReglasDesembolso">
  <plnk:partnerLinkType name="ValidarReglasDesembolso">
    <plnk:role name="ValidarReglasDesembolso_PT" portType="tns:ValidarReglasDesembolso_PT"/>
  </plnk:partnerLinkType>
  <wsdl:import namespace="http://www.bcie.org/ValidarReglasDesembolso"
               location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/ValidarReglasDesembolsoSOR.wsdl"/>
  <wsdl:import namespace="http://www.bcie.org/ConsultarTreReglasDesembolso"
               location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ConsultarReglasDesembolsoSAD.wsdl"/>
  <wsdl:import namespace="http://www.bcie.org/CrearBitacoraReglasDesembolso"
               location="oramds:/apps/Resources/ComponentesComunes/Utilidades/CrearBitacoraReglasDesembolso/V1/Wsdl/CrearBitacoraReglasDesembolso.wsdl"/>
</wsdl:definitions>
