<wsdl:definitions name="ConsultarRolesPorProceso" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarRolesPorProceso" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarRolesPorProceso" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarRolesPorProceso" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarRolesPorProceso_plt">
    <plt:role name="ConsultarRolesPorProceso_role">
      <plt:portType name="tns:ConsultarRolesPorProceso_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarRolesPorProceso" schemaLocation="../XSD/ConsultarRolesPorProceso.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarRolesPorProcesoInput_msg">
        <wsdl:part name="ConsultarRolesPorProcesoInput_msg" element="db:ConsultarRolesPorProcesoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarRolesPorProcesoOutputCollection_msg">
        <wsdl:part name="ConsultarRolesPorProcesoOutputCollection" element="db:ConsultarRolesPorProcesoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarRolesPorProceso_ptt">
        <wsdl:operation name="ConsultarRolesPorProceso">
            <wsdl:input message="tns:ConsultarRolesPorProcesoInput_msg"/>
            <wsdl:output message="tns:ConsultarRolesPorProcesoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>