<definitions targetNamespace="www.bcie.org/ofismatica" 
xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="www.bcie.org/ofismatica" 
xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:hom="http://www.bcie.org/herramientaOfismatica">
  <types>
    <xsd:schema>
        <xsd:import namespace="http://www.bcie.org/herramientaOfismatica" schemaLocation="../XSD/GenerarAvisoCobroConsolidado.xsd"/>
    </xsd:schema>
  </types>
  <message name="Entrada">
<part name="parameters" element="hom:aviso"/>
</message>
<message name="Salida">
<part name="parameters" element="hom:respuesta"/>
</message>

<portType name="avisoCobro">
<operation name="generarAvisoCobroConsolidado">
<input message="tns:Entrada"/>
<output message="tns:Salida"/>
</operation>
</portType>

<binding name="generarAvisoCobroConsolidadoPortBinding" type="tns:avisoCobro">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="generarAvisoCobroConsolidado">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="generAvisoCobroConsolidadoService">
<port name="generAvisoCobroConsolidadoPort" binding="tns:generarAvisoCobroConsolidadoPortBinding">
<soap:address location="http://hn-obpm-qa.bcie.org:7065/generAvisoDetalladoPort/generAvisoDetalladoService"/>
</port>
</service>


</definitions>