<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WsConsultaCrediticia" targetNamespace="http://tempuri.org/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC"/>
      <xs:element name="ConsultarAPC">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Model" nillable="true" type="q1:ConsultaAPC" xmlns:q1="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ConsultarAPCResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="ConsultarAPCResult" nillable="true" type="q2:ConsultaAPC" xmlns:q2="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetJsonAPC">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Model" nillable="true" type="q3:ConsultaAPC" xmlns:q3="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="GetJsonAPCResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="GetJsonAPCResult" nillable="true" type="q4:ConsultaAPC" xmlns:q4="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC" xmlns:tns="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model"/>
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
      <xs:complexType name="ConsultaAPC">
        <xs:sequence>
          <xs:element minOccurs="0" name="CodigoRespuesta" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="DescripcionRespuesta" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="DetCanceladasAPC" nillable="true" type="q1:ArrayOfDetCanceladasAPC" xmlns:q1="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model"/>
          <xs:element minOccurs="0" name="DetCompromisoAPC" nillable="true" type="q2:ArrayOfDetCompromisoAPC" xmlns:q2="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model"/>
          <xs:element minOccurs="0" name="DetMovimientosAPC" nillable="true" type="q3:ArrayOfDetMovimientosAPC" xmlns:q3="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model"/>
          <xs:element minOccurs="0" name="DetTipoRelacionAPC" nillable="true" type="q4:ArrayOfDetTipoRelacionAPC" xmlns:q4="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model"/>
          <xs:element minOccurs="0" name="EsPrueba" type="xs:boolean"/>
          <xs:element minOccurs="0" name="ForzarBusqueda" type="xs:boolean"/>
          <xs:element minOccurs="0" name="FueBusquedaForzadaAutomatica" type="xs:boolean"/>
          <xs:element minOccurs="0" name="IdentificacionConsulta" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="JsonAPC" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="PasswordAPC" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="TipoCliente" nillable="true" type="tns:TiposClientesAPC"/>
          <xs:element minOccurs="0" name="UsuarioAPC" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_fechaconsulta" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dg_fechacreacion" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dg_fechadefuncion" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dg_idcliente" type="xs:int"/>
          <xs:element minOccurs="0" name="dg_identificacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_max_dias_consulta" type="xs:int"/>
          <xs:element minOccurs="0" name="dg_pi" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_primer_apellido" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_primer_nombre" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_score" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="xmlAPC" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ConsultaAPC" nillable="true" type="tns:ConsultaAPC"/>
      <xs:simpleType name="TiposClientesAPC">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Cedula">
            <xs:annotation>
              <xs:appinfo>
                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">1</EnumerationValue>
              </xs:appinfo>
            </xs:annotation>
          </xs:enumeration>
          <xs:enumeration value="RUC">
            <xs:annotation>
              <xs:appinfo>
                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">2</EnumerationValue>
              </xs:appinfo>
            </xs:annotation>
          </xs:enumeration>
          <xs:enumeration value="Pasaporte">
            <xs:annotation>
              <xs:appinfo>
                <EnumerationValue xmlns="http://schemas.microsoft.com/2003/10/Serialization/">3</EnumerationValue>
              </xs:appinfo>
            </xs:annotation>
          </xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="TiposClientesAPC" nillable="true" type="tns:TiposClientesAPC"/>
    </xs:schema>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model" xmlns:tns="http://schemas.datacontract.org/2004/07/ULA.ServicioConsultaAPC.Model" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="ArrayOfDetCanceladasAPC">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="DetCanceladasAPC" nillable="true" type="tns:DetCanceladasAPC"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfDetCanceladasAPC" nillable="true" type="tns:ArrayOfDetCanceladasAPC"/>
      <xs:complexType name="DetCanceladasAPC">
        <xs:sequence>
          <xs:element minOccurs="0" name="DetGeneralesAPC" nillable="true" type="tns:DetGeneralesAPC"/>
          <xs:element minOccurs="0" name="dca_cod_grupo_econ" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dca_codigo" type="xs:int"/>
          <xs:element minOccurs="0" name="dca_descr_corta_rela" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dca_descr_obs_corta" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dca_fec_fin_rel" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dca_fec_inicio_rel" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dca_fec_liquidacion" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dca_historia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dca_idcliente" type="xs:int"/>
          <xs:element minOccurs="0" name="dca_monto_codificado" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dca_monto_original" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dca_nom_asoc" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dca_num_refer" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dca_tipo_asoc" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="DetCanceladasAPC" nillable="true" type="tns:DetCanceladasAPC"/>
      <xs:complexType name="DetGeneralesAPC">
        <xs:sequence>
          <xs:element minOccurs="0" name="DetCanceladasAPC" nillable="true" type="tns:ArrayOfDetCanceladasAPC"/>
          <xs:element minOccurs="0" name="DetCompromisoAPC" nillable="true" type="tns:ArrayOfDetCompromisoAPC"/>
          <xs:element minOccurs="0" name="DetMovimientosAPC" nillable="true" type="tns:ArrayOfDetMovimientosAPC"/>
          <xs:element minOccurs="0" name="DetTipoRelacionAPC" nillable="true" type="tns:ArrayOfDetTipoRelacionAPC"/>
          <xs:element minOccurs="0" name="JsonAPC" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_fechaconsulta" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dg_fechacreacion" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dg_fechadefuncion" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dg_idcliente" type="xs:int"/>
          <xs:element minOccurs="0" name="dg_identificacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_pi" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_primer_apellido" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_primer_nombre" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dg_prueba" nillable="true" type="xs:boolean"/>
          <xs:element minOccurs="0" name="dg_score" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="xmlAPC" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="DetGeneralesAPC" nillable="true" type="tns:DetGeneralesAPC"/>
      <xs:complexType name="ArrayOfDetCompromisoAPC">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="DetCompromisoAPC" nillable="true" type="tns:DetCompromisoAPC"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfDetCompromisoAPC" nillable="true" type="tns:ArrayOfDetCompromisoAPC"/>
      <xs:complexType name="DetCompromisoAPC">
        <xs:sequence>
          <xs:element minOccurs="0" name="DetGeneralesAPC" nillable="true" type="tns:DetGeneralesAPC"/>
          <xs:element minOccurs="0" name="dc_cod_grupo_econ" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_codigo" type="xs:int"/>
          <xs:element minOccurs="0" name="dc_descr_corta_rela" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_descr_forma_pago" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_descr_obs_corta" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_fec_actualizacion" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dc_fec_fin_rel" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dc_fec_inicio_rel" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dc_fec_ultimo_pago" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dc_historia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_idcliente" type="xs:int"/>
          <xs:element minOccurs="0" name="dc_importe_pago" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dc_monto_codificado" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dc_monto_original" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dc_monto_ultimo_pago" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dc_nom_asoc" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_num_dias_atraso" nillable="true" type="xs:int"/>
          <xs:element minOccurs="0" name="dc_num_pagos" nillable="true" type="xs:int"/>
          <xs:element minOccurs="0" name="dc_num_refer" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dc_saldo_actual" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dc_tipo_asoc" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="DetCompromisoAPC" nillable="true" type="tns:DetCompromisoAPC"/>
      <xs:complexType name="ArrayOfDetMovimientosAPC">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="DetMovimientosAPC" nillable="true" type="tns:DetMovimientosAPC"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfDetMovimientosAPC" nillable="true" type="tns:ArrayOfDetMovimientosAPC"/>
      <xs:complexType name="DetMovimientosAPC">
        <xs:sequence>
          <xs:element minOccurs="0" name="DetGeneralesAPC" nillable="true" type="tns:DetGeneralesAPC"/>
          <xs:element minOccurs="0" name="dm_Fec" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="dm_codigo" type="xs:int"/>
          <xs:element minOccurs="0" name="dm_idcliente" type="xs:int"/>
          <xs:element minOccurs="0" name="dm_identificacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dm_nom_asoc" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="DetMovimientosAPC" nillable="true" type="tns:DetMovimientosAPC"/>
      <xs:complexType name="ArrayOfDetTipoRelacionAPC">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="DetTipoRelacionAPC" nillable="true" type="tns:DetTipoRelacionAPC"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfDetTipoRelacionAPC" nillable="true" type="tns:ArrayOfDetTipoRelacionAPC"/>
      <xs:complexType name="DetTipoRelacionAPC">
        <xs:sequence>
          <xs:element minOccurs="0" name="DetGeneralesAPC" nillable="true" type="tns:DetGeneralesAPC"/>
          <xs:element minOccurs="0" name="dt_cantidad" nillable="true" type="xs:int"/>
          <xs:element minOccurs="0" name="dt_codigo" type="xs:int"/>
          <xs:element minOccurs="0" name="dt_idcliente" type="xs:int"/>
          <xs:element minOccurs="0" name="dt_monto" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="dt_relacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="dt_saldo_actual" nillable="true" type="xs:decimal"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="DetTipoRelacionAPC" nillable="true" type="tns:DetTipoRelacionAPC"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IWsConsultaCrediticia_GetJsonAPC_InputMessage">
    <wsdl:part name="parameters" element="tns:GetJsonAPC">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="IWsConsultaCrediticia_ConsultarAPC_InputMessage">
    <wsdl:part name="parameters" element="tns:ConsultarAPC">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="IWsConsultaCrediticia_ConsultarAPC_OutputMessage">
    <wsdl:part name="parameters" element="tns:ConsultarAPCResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="IWsConsultaCrediticia_GetJsonAPC_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetJsonAPCResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="IWsConsultaCrediticia">
    <wsdl:operation name="ConsultarAPC">
      <wsdl:input message="tns:IWsConsultaCrediticia_ConsultarAPC_InputMessage" wsaw:Action="http://tempuri.org/IWsConsultaCrediticia/ConsultarAPC">
    </wsdl:input>
      <wsdl:output message="tns:IWsConsultaCrediticia_ConsultarAPC_OutputMessage" wsaw:Action="http://tempuri.org/IWsConsultaCrediticia/ConsultarAPCResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetJsonAPC">
      <wsdl:input message="tns:IWsConsultaCrediticia_GetJsonAPC_InputMessage" wsaw:Action="http://tempuri.org/IWsConsultaCrediticia/GetJsonAPC">
    </wsdl:input>
      <wsdl:output message="tns:IWsConsultaCrediticia_GetJsonAPC_OutputMessage" wsaw:Action="http://tempuri.org/IWsConsultaCrediticia/GetJsonAPCResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IWsConsultaCrediticia" type="tns:IWsConsultaCrediticia">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarAPC">
      <soap:operation soapAction="http://tempuri.org/IWsConsultaCrediticia/ConsultarAPC" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetJsonAPC">
      <soap:operation soapAction="http://tempuri.org/IWsConsultaCrediticia/GetJsonAPC" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WsConsultaCrediticia">
    <wsdl:port name="BasicHttpBinding_IWsConsultaCrediticia" binding="tns:BasicHttpBinding_IWsConsultaCrediticia">
      <soap:address location="http://lenovo:8088/ConsultaCrediticia"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
