<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarPlazoComponenteSAD"
     targetNamespace="http://www.bcie.org/ConsultarPlazoComponenteSAD"
     xmlns:tns="http://www.bcie.org/ConsultarPlazoComponenteSAD"
     xmlns:desMO="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestConsultarPlazoComponenteMessage">
        <wsdl:part name="request" element="desMO:ConsultarPlazoComponenteRequest"/>
    </wsdl:message>
    <wsdl:message name="responseConsultarPlazoComponenteMessage">
        <wsdl:part name="response" element="desMO:ConsultarPlazoComponenteResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarPlazoComponente_PT">
        <wsdl:operation name="ConsultarPlazoComponente">
            <wsdl:input message="tns:requestConsultarPlazoComponenteMessage"/>
            <wsdl:output message="tns:responseConsultarPlazoComponenteMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsultarPlazoComponente_PTSOAP12Binding" type="tns:ConsultarPlazoComponente_PT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ConsultarPlazoComponente">
            <soap12:operation style="document" soapAction="ConsultarPlazoComponente" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
