<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarSolicitudDesembolsoSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/ConsultarSolicitudDesembolsoSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:desMO="http://www.bcie.org/DesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarSolicitudDesembolsoSAD/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestConsultarSolicitudDesembolsoMessage">
    <part name="request" element="desMO:ConsultarSolicitudDesembolsoRequest"/>
  </message>
  <message name="responseConsultarSolicitudDesembolsoMessage">
    <part name="response" element="desMO:ConsultarSolicitudDesembolsoResponse"/>
  </message>
  <portType name="ConsultarSolicitudDesembolso_PT">
    <operation name="consultarSolicitudDesembolso">
      <input message="tns:requestConsultarSolicitudDesembolsoMessage"/>
      <output message="tns:responseConsultarSolicitudDesembolsoMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarSolicitudDesembolso_PTSOAP12Binding" type="tns:ConsultarSolicitudDesembolso_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarSolicitudDesembolso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarSolicitudDesembolsoSAD/consultarSolicitudDesembolso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>