<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PropagarDesembolsosSAD"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/PropagarDesembolsosSAD"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/PropagarDesembolsosSAD"
     xmlns:inp1="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="PropagarDesembolsosRequestMessage" element="inp1:PropagarDesembolsosRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="PropagarDesembolsosResponseMessage" element="inp1:PropagarDesembolsosResponse"/>
    </wsdl:message>
    <wsdl:portType name="PropagarDesembolsos_ptt">
        <wsdl:operation name="PropagarDesembolsos">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PropagarDesembolsos_bind" type="tns:PropagarDesembolsos_ptt">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="PropagarDesembolsos">
            <soap12:operation style="document" soapAction="PropagarDesembolsos" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/PropagarDesembolsosSAD"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/PropagarDesembolsosSAD"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
