<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ItemDiffColorProcess" targetNamespace="http://xmlns.oracle.com/ItemCataloApp/ItemDiffColorProcess/ItemDiffColorProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ItemCataloApp/ItemDiffColorProcess/ItemDiffColorProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/getColorDB" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/getColorDB" schemaLocation="../Schemas/getColorDB_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ItemDiffColorProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:getColorDBSelect_pId_pAppCode_pCatDef_pParnId_pParnCatInputParameters"/>
   </wsdl:message>
   <wsdl:message name="ItemDiffColorProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:MdmItemsDiffsCollection"/>
   </wsdl:message>
   <wsdl:portType name="ItemDiffColorProcess">
      <wsdl:operation name="translateColor">
         <wsdl:input message="client:ItemDiffColorProcessRequestMessage"/>
         <wsdl:output message="client:ItemDiffColorProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ItemDiffColorProcess">
      <plnk:role name="ItemDiffColorProcessProvider" portType="client:ItemDiffColorProcess"/>
   </plnk:partnerLinkType>
   <wsdl:binding name="ItemDiffColorProcessBinding" type="client:ItemDiffColorProcess">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="translateColor">
         <soap:operation style="document" soapAction="http://xmlns.oracle.com/ItemCataloApp/ItemDiffColorProcess/ItemDiffColorProcess/translateColor"/>
         <wsdl:input>
            <soap:body use="literal" parts="payload"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" parts="payload"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>
