<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 mer UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:mer="http://www.agarcia.mx/EnterpriseObjects/MerchandiseHierarchy" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/BorrardbReference" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../Resources/BorrardbReference_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxSoaMerchVwCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BorrardbReference"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/MerchandiseHierarchy/MerchandiseHierarchyEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="MerchandiseHierarchyEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/MerchandiseHierarchy"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE SEP 22 19:56:44 CDT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <mer:MerchandiseHierarchyEBM>
         <mer:DataArea>
            <xsl:for-each select="//*:XxSoaMerchVwCollection/*:XxSoaMerchVw">
               <mer:MerchandiseHierarchy>
                  <mer:Division>
                     <com:ID>
                        <xsl:value-of select="ns0:division"/>
                     </com:ID>
                     <com:ApplicationObjectReference>
                        <com:ApplicationName>
                           <xsl:value-of select="ns0:divName"/>
                        </com:ApplicationName>
                     </com:ApplicationObjectReference>
                  </mer:Division>
                  <mer:Brand>
                     <com:ID>
                        <xsl:value-of select="ns0:groupNo"/>
                     </com:ID>
                     <com:ApplicationObjectReference>
                        <com:ApplicationName>
                           <xsl:value-of select="ns0:groupName"/>
                        </com:ApplicationName>
                     </com:ApplicationObjectReference>
                  </mer:Brand>
                  <mer:Department>
                     <com:ID>
                        <xsl:value-of select="ns0:dept"/>
                     </com:ID>
                     <com:ApplicationObjectReference>
                        <com:ApplicationName>
                           <xsl:value-of select="ns0:deptName"/>
                        </com:ApplicationName>
                     </com:ApplicationObjectReference>
                  </mer:Department>
                  <mer:Class>
                     <com:ID>
                        <xsl:value-of select="ns0:class"/>
                     </com:ID>
                     <com:ApplicationObjectReference>
                        <com:ApplicationName>
                           <xsl:value-of select="ns0:className"/>
                        </com:ApplicationName>
                     </com:ApplicationObjectReference>
                  </mer:Class>
                  <mer:Type>
                     <com:ID>
                        <xsl:value-of select="ns0:subclass"/>
                     </com:ID>
                     <com:ApplicationObjectReference>
                        <com:ApplicationName>
                           <xsl:value-of select="ns0:subName"/>
                        </com:ApplicationName>
                     </com:ApplicationObjectReference>
                  </mer:Type>
               </mer:MerchandiseHierarchy>
            </xsl:for-each>
         </mer:DataArea>
      </mer:MerchandiseHierarchyEBM>
   </xsl:template>
</xsl:stylesheet>