<wsdl:definitions name="CrearTreLineaCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ADAPTADORES/CrearTreLineaCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ADAPTADORES/CrearTreLineaCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CrearTreLineaCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearTreLineaCredito_plt">
    <plt:role name="CrearTreLineaCredito_role">
      <plt:portType name="tns:CrearTreLineaCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CrearTreLineaCredito" schemaLocation="../XSD/CrearTreLineaCredito.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="CrearTreLineaCreditoInput_msg">
        <wsdl:part name="CrearTreLineaCreditoInput_msg" element="db:CrearTreLineaCreditoInput"/>
    </wsdl:message>
    <wsdl:portType name="CrearTreLineaCredito_ptt">
        <wsdl:operation name="CrearTreLineaCredito">
            <wsdl:input message="tns:CrearTreLineaCreditoInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>