<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://mx.agarcia.ea/Capabilities/Core/RetailStore/RetailStoreEntitySvc/Schema" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:ns1="http://mx.agarcia.ea/Canonical/Commons/Enums/v1" xmlns:ns2="http://mx.agarcia.ea/Canonical/Commons/LocationsCommon/v1" xmlns:ns4="http://mx.agarcia.ea/Canonical/Commons/Languages/v1" xmlns:ns5="http://mx.agarcia.ea/Canonical/Commons/Types/v1" xmlns:ret="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/CreateRetailStoreProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns7="http://mx.agarcia.ea/Canonical/Commons/Currencies/v1" xmlns:ns3="http://mx.agarcia.ea/Canonical/Commons/Countries/v1" xmlns:AGSH="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" xmlns:ns6="http://mx.agarcia.ea/Canonical/Commons/RetailStore/v1" xmlns:AGSM="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateRetailStoreProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createRetailStoreRequest" namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/RetailStoreEntitySvc/Schema"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateRetailStoreProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="createRetailStoreRequest" namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/RetailStoreEntitySvc/Schema"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED JUN 19 09:44:26 CDT 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:createRetailStoreRequest>
         <ns0:retailStores>
            <ns6:retailStore>
               <ns6:storeID>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:storeID"/>
               </ns6:storeID>
               <ns6:name>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:name"/>
               </ns6:name>
               <ns6:store>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:store"/>
               </ns6:store>
               <ns6:store_name>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:store_name"/>
               </ns6:store_name>
               <ns6:store_type>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:store_type"/>
               </ns6:store_type>
               <ns6:fax_number>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:fax_number"/>
               </ns6:fax_number>
               <ns6:phone_number>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:phone_number"/>
               </ns6:phone_number>
               <ns6:store_open_date>
                  <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:store_open_date"/>
               </ns6:store_open_date>
               <ns6:address>
                  <ns2:addres>
                     <ns2:City>
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:City"/>
                     </ns2:City>
                     <ns2:territory TypeCode="{/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:territory/@TypeCode}">
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:territory"/>
                     </ns2:territory>
                     <ns2:postalCode>
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:postalCode"/>
                     </ns2:postalCode>
                     <ns2:country Code="{/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:country/@Code}">
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:country"/>
                     </ns2:country>
                     <ns2:add1>
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:add1"/>
                     </ns2:add1>
                     <ns2:add2>
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:add2"/>
                     </ns2:add2>
                     <ns2:add3>
                        <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:address/ns2:addres/ns2:add3"/>
                     </ns2:add3>
                  </ns2:addres>
               </ns6:address>
               <ns6:detail>
                  <ns6:store_class>
                     <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:detail/ns6:store_class"/>
                  </ns6:store_class>
                  <ns6:store_mgr_name>
                     <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:detail/ns6:store_mgr_name"/>
                  </ns6:store_mgr_name>
                  <ns6:total_square_ft>
                     <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:detail/ns6:total_square_ft"/>
                  </ns6:total_square_ft>
                  <ns6:district>
                     <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:detail/ns6:district"/>
                  </ns6:district>
                  <ns6:default_wh>
                     <xsl:value-of select="/ns0:createRetailStoreRequest/ns0:retailStores/ns6:retailStore/ns6:detail/ns6:default_wh"/>
                  </ns6:default_wh>
               </ns6:detail>
            </ns6:retailStore>
         </ns0:retailStores>
      </ns0:createRetailStoreRequest>
   </xsl:template>
</xsl:stylesheet>