<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://www.bcie.org/ConfiguracionProcesosMO"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 ns1 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:confBO="http://www.bcie.org/ConfiguracionProcesosBO" xmlns:ns4="http://www.bcie.org/TerminoBO"
                xmlns:operBO="http://www.bcie.org/OperacionBO" xmlns:ns14="http://www.example.org"
                xmlns:resBO="http://www.bcie.org/ResultBO"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:ns10="http://www.bcie.org/MatrizTCCBO" xmlns:ns8="http://www.bcie.org/LineaCreditoBO"
                xmlns:ns15="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns2="http://www.bcie.org/CondicionBO" xmlns:ns3="http://www.bcie.org/ProductoBO"
                xmlns:ns5="http://www.bcie.org/DeclaracionJuradaBO"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:ns6="http://www.bcie.org/DocumentoBO" xmlns:ns7="http://www.bcie.org/ComisionBO"
                xmlns:ns9="http://www.bcie.org/CatalogoBO" xmlns:ns11="http://www.bcie.org/ClienteBO"
                xmlns:ns12="http://www.bcie.org/AtributoBO"
                xmlns:ns16="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:ns13="http://www.bcie.org/ErrorBO" xmlns:ns17="http://www.bcie.org/ReglaBO"
                xmlns:cmnBO="http://www.bcie.org/CommonBO" xmlns:lecciones="http://www.bcie.org/LeccionAprendidaBO"
                xmlns:ns18="http://www.bcie.org/CrearBitacoraProcesoBO"
                xmlns:ns19="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns20="http://www.bcie.org/ImplementacionPctBO" xmlns:ns21="http://www.bcie.org/HerramientaCEBO"
                xmlns:desBO="http://www.bcie.org/DesembolsoBO" xmlns:ns22="http://www.bcie.org/AdquisicionBO"
                xmlns:ns23="http://www.bcie.org/ContratoBO"
                xmlns:ns24="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/Schema/ConfiguracionProcesosMO.xsd"/>
        <oracle-xsl-mapper:rootElement name="configuracionReasignarOperacionResponse"
                                       namespace="http://www.bcie.org/ConfiguracionProcesosMO"/>
        <oracle-xsl-mapper:param name="configuracionReasignarOperacionResponse"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PU01/ReasignacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ReasignacionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"/>
        <oracle-xsl-mapper:param name="reasignacionDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PU01/ReasignacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ReasignacionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Reasignacion/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [FRI MAR 18 11:41:11 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="reasignacionDO"/>
  <xsl:template match="/">
    <ns1:ReasignacionPayload>
      <ns1:Header>
        <header:Operacion>
          <ns15:CodigoOperacion>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:CodigoOperacion"/>
          </ns15:CodigoOperacion>
          <ns15:NombreOperacion>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:NombreOperacion"/>
          </ns15:NombreOperacion>
          <ns15:ResponsableOperacion>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:ResponsableOperacion"/>
          </ns15:ResponsableOperacion>
          <ns15:CodigoCliente>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:CodigoCliente"/>
          </ns15:CodigoCliente>
          <ns15:NombreCliente>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:NombreCliente"/>
          </ns15:NombreCliente>
          <ns15:CodigoProducto>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:CodigoProducto"/>
          </ns15:CodigoProducto>
          <ns15:NombreProducto>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:NombreProducto"/>
          </ns15:NombreProducto>
          <ns15:MontoSolicitado>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:MontoSolicitado"/>
          </ns15:MontoSolicitado>
          <ns15:Pais>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Operacion/ns15:Pais"/>
          </ns15:Pais>
        </header:Operacion>
        <header:Tarea>
          <ns16:CodigoTarea>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Tarea/ns16:CodigoTarea"/>
          </ns16:CodigoTarea>
          <ns16:NombreTarea>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Tarea/ns16:NombreTarea"/>
          </ns16:NombreTarea>
          <ns16:CodigoRol>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Tarea/ns16:CodigoRol"/>
          </ns16:CodigoRol>
          <ns16:NombreRol>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Tarea/ns16:NombreRol"/>
          </ns16:NombreRol>
          <ns16:CodigoProceso>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Tarea/ns16:CodigoProceso"/>
          </ns16:CodigoProceso>
          <ns16:NombreProceso>
            <xsl:value-of select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/header:Tarea/ns16:NombreProceso"/>
          </ns16:NombreProceso>
        </header:Tarea>
        <xsl:for-each select="$reasignacionDO/ns1:ReasignacionPayload/ns1:Header/parameter:ParameterType">
          <parameter:ParameterType>
            <parameter:parameterName>
              <xsl:value-of select="parameter:parameterName"/>
            </parameter:parameterName>
            <parameter:parameterValue>
              <xsl:value-of select="parameter:parameterValue"/>
            </parameter:parameterValue>
          </parameter:ParameterType>
        </xsl:for-each>
      </ns1:Header>
      <xsl:for-each select="/ns0:configuracionReasignarOperacionResponse/ns0:configuracionReasignarOperacion/confBO:Enmiendas/ns10:EnmiendaTCC">
        <ns1:Enmiendas>
          <ns1:idEnmienda>
            <xsl:value-of select="ns10:idEnmienda"/>
          </ns1:idEnmienda>
        </ns1:Enmiendas>
      </xsl:for-each>
      <xsl:for-each select="/ns0:configuracionReasignarOperacionResponse/ns0:configuracionReasignarOperacion/confBO:Comisiones">
        <ns1:Comisiones>
          <ns1:idComision>
            <xsl:value-of select="ns7:idComision"/>
          </ns1:idComision>
        </ns1:Comisiones>
      </xsl:for-each>
      <ns1:IdEnmienda/>
      <ns1:IdComision/>
    </ns1:ReasignacionPayload>
  </xsl:template>
</xsl:stylesheet>
