<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarCategoriaByCondicion" name="ConsultarCategoriaByCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarCategoriaByCondicion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarCategoriaByCondicion"/>
    <wsdl:binding name="ConsultarCategoriaByCondicion_ptt-binding" type="con:ConsultarCategoriaByCondicion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project14/ConsultarCategoriaByCondicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarCategoriaByCondicion">
            <soap:operation soapAction="ConsultarCategoriaByCondicion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>