<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/LavadoActivosProcess"
                  xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/LavadoActivosProcess"
                  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/LavadoActivosProcess"
                  schemaLocation="../../Schema/PA01/LavadoActivosProcess.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="InicioLAFT">
    <wsdl:part name="parameters" element="tns:InicioLAFT"/>
  </wsdl:message>
  <wsdl:message name="FinLAFT">
    <wsdl:part name="parameters" element="tns:FinLAFT"/>
  </wsdl:message>
  <wsdl:message name="CancelarLAFT">
    <wsdl:part name="parameters" element="tns:CancelarLAFT"/>
  </wsdl:message>
  <wsdl:portType name="LavadoActivosProcessPortType">
    <wsdl:operation name="InicioLAFT">
      <wsdl:input message="tns:InicioLAFT"/>
    </wsdl:operation>
    <wsdl:operation name="FinLAFT">
      <wsdl:input message="tns:FinLAFT"/>
    </wsdl:operation>
    <wsdl:operation name="CancelarLAFT">
      <wsdl:input message="tns:CancelarLAFT"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LavadoActivosProcessBinding" type="tns:LavadoActivosProcessPortType">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="InicioLAFT">
      <wsdlsoap:operation style="document" soapAction="InicioLAFT"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="FinLAFT">
      <wsdlsoap:operation style="document" soapAction="FinLAFT"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="CancelarLAFT">
      <wsdlsoap:operation style="document" soapAction="CancelarLAFT"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <plnk:partnerLinkType name="LavadoActivosProcessPortTypePartnerLinkType">
    <plnk:role name="LavadoActivosProcessPortTypeProvider">
      <plnk:portType name="tns:LavadoActivosProcessPortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
</wsdl:definitions>
