<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreateStyleOSB/Applications/RMSCreateStyleDBBS" name="RMSCreateStyleDBBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSCreateStyleDBBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreateStyleOSB/Applications/RMSCreateStyleDBBS"/>
    <wsdl:binding name="RMSCreateStyleDBBS_ptt-binding" type="rms:RMSCreateStyleDBBS_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/db/CreateStyleOSB/Applications/RMSCreateStyleDBBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSCreateStyleDBBS">
            <soap:operation soapAction="RMSCreateStyleDBBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>