<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerRolesCuestionario" name="ObtenerRolesCuestionario-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../WSDL/ObtenerRolesCuestionario.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerRolesCuestionario"/>
    <wsdl:binding name="ObtenerRolesCuestionario_ptt-binding" type="obt:ObtenerRolesCuestionario_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerRolesCuestionario">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerRolesCuestionario">
            <soap:operation soapAction="ObtenerRolesCuestionario"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>