<wsdl:definitions name="PROCreateColorProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Items/PROCreateColorProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Items/PROCreateColorProcess/v1.0" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateColorGroupEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<wsdl:documentation>
<abstractWSDL>
http://uat-soa.agarcia.com.mx:7004/soa-infra/services/RetailOperMK/PROCreateColorGroupProcess!1.0/WSDLs/PROCreateColorProcess.wsdl
</abstractWSDL>
</wsdl:documentation>
<plnk:partnerLinkType name="PROCreateColorProcess">
<plnk:role name="PROCreateColorProcessProvider" portType="client:PROCreateColorProcess"/>
</plnk:partnerLinkType>
<wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateColorGroupEntity" schemaLocation="../Schemas/CreateColorGroupEntitySchema.xsd"/>
</schema>
</wsdl:types>
<wsdl:message name="PROCreateColorProcessRequestMessage">
<wsdl:part name="payload" element="ns1:createColorGroupRequest"/>
</wsdl:message>
<wsdl:message name="PROCreateColorProcessResponseMessage">
<wsdl:part name="payload" element="ns1:createColorGroupResponse"/>
</wsdl:message>
<wsdl:portType name="PROCreateColorProcess">
<wsdl:operation name="create">
<wsdl:input message="client:PROCreateColorProcessRequestMessage"/>
<wsdl:output message="client:PROCreateColorProcessResponseMessage"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="PROCreateColorProcessBinding" type="client:PROCreateColorProcess">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="create">
<soap:operation style="document" soapAction="create"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="procreatecolorprocess_client_ep">
<wsdl:port name="PROCreateColorProcess_pt" binding="client:PROCreateColorProcessBinding">
<soap:address location="http://uat-soa.agarcia.com.mx:7004/soa-infra/services/RetailOperMK/PROCreateColorGroupProcess/procreatecolorprocess_client_ep"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>