<wsdl:definitions name="CreateStyleTaskREST" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntitySvc/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../../../../../Foundation/Schemas/Commons/AGStandardMessageSchema.xsd" namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage"/>
    <wsdl:import location="../../Schemas/CreateItemEntitySchema.xsd" namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntity"/>
    <wsdl:message name="create_inputMessage">
        <wsdl:part name="request" element="cre:createItemRequest" xmlns:cre="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntity"/>
    </wsdl:message>
    <wsdl:message name="create_outputMessage">
        <wsdl:part name="response" element="cre:createItemResponse" xmlns:cre="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntity"/>
    </wsdl:message>
    <wsdl:message name="create_faultMessage">
        <wsdl:part name="Fault_fault" element="ags:messageError" xmlns:ags="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage"/>
    </wsdl:message>
    <wsdl:portType name="CreateStyleTaskREST_ptt">
        <wsdl:operation name="create">
            <wsdl:input message="v1:create_inputMessage" xmlns:v1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntitySvc/v1.0"/>
            <wsdl:output message="v1:create_outputMessage" xmlns:v1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntitySvc/v1.0"/>
            <wsdl:fault name="fault" message="v1:create_faultMessage" xmlns:v1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntitySvc/v1.0"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="createItemBinding" type="v1:CreateStyleTaskREST_ptt" xmlns:v1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateItemEntitySvc/v1.0">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="create">
            <soap:operation soapAction="create"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>