<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ConsultarRolByPlantilla" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ConsultarRolByPlantilla" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:correoMO="http://www.bcie.org/CorreoMO">
 <types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="../Schema/CorreoElectronicoMO.xsd"/>
		</xsd:schema>
	</types>
 <message name="ConsultarRolByPlantillaRequestMessage">
  <part name="ConsultarRolByPlantillaRequest" element="correoMO:ConsultaRolByPlantillaRequest"/>
 </message>
 <message name="ConsultarRolByPlantillaResponseMessage">
  <part name="ConsultarRolByPlantillaResponse" element="correoMO:ConsultaRolByPlantillaResponse"/>
 </message>
 <portType name="consultarRolByPlantilla_pt">
  <operation name="ConsultarRolByPlantilla">
   <input message="tns:ConsultarRolByPlantillaRequestMessage"/>
   <output message="tns:ConsultarRolByPlantillaResponseMessage"/>
  </operation>
 </portType>
 <binding name="consultarRolByPlantilla_pt12Bnd" type="tns:consultarRolByPlantilla_pt">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="ConsultarRolByPlantilla">
   <soap12:operation style="document"
                     soapAction="http://xmlns.bcie.com/ConsultarRolByPlantilla/ConsultarRolByPlantilla"/>
   <input>
    <soap12:body use="literal" parts="ConsultarRolByPlantillaRequest"/>
   </input>
   <output>
    <soap12:body use="literal" parts="ConsultarRolByPlantillaResponse"/>
   </output>
  </operation>
 </binding>
</definitions>