<wsdl:definitions name="ConsultarLimiteByLineaFinanciera_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarLimiteByLineaFinanciera_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarLimiteByLineaFinanciera_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLimiteByLineaFinanciera_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarLimiteByLineaFinanciera_DB_plt">
    <plt:role name="ConsultarLimiteByLineaFinanciera_DB_role">
      <plt:portType name="tns:ConsultarLimiteByLineaFinanciera_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarLimiteByLineaFinanciera_DB" schemaLocation="../XSD/ConsultarLimiteByLineaFinanciera_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarLimiteByLineaFinanciera_DBInput_msg">
        <wsdl:part name="ConsultarLimiteByLineaFinanciera_DBInput_msg" element="db:ConsultarLimiteByLineaFinanciera_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarLimiteByLineaFinanciera_DBOutputCollection_msg">
        <wsdl:part name="ConsultarLimiteByLineaFinanciera_DBOutputCollection" element="db:ConsultarLimiteByLineaFinanciera_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarLimiteByLineaFinanciera_DB_ptt">
        <wsdl:operation name="ConsultarLimiteByLineaFinanciera_DB">
            <wsdl:input message="tns:ConsultarLimiteByLineaFinanciera_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarLimiteByLineaFinanciera_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>