<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ItemCatalogTaskSvcWSDL" targetNamespace="http://mx.agarcia.ea/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvcWSD" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N5="http://mx.agarcia.ea/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvcWSD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ItemCatalogTaskPXY">
      <plnk:role name="ItemCatalogEntitySvcPType" portType="WL5G3N5:ItemCatalogEntitySvcPType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvcWSD" location="http://prd-osb.agarcia.com.mx:7004/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvc/PS/ItemCatalogTaskPXY?WSDL"/>
</wsdl:definitions>
