<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDACreateSizeProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Items/JDACreateSizeProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Items/JDACreateSizeProcess/v1.0" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeEntity" schemaLocation="../Schemas/CreateSizeEntitySchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="JDACreateSizeProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:createSizeRequest"/>
   </wsdl:message>
   <wsdl:message name="JDACreateSizeProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:createSizeResponse"/>
   </wsdl:message>
   <wsdl:portType name="JDACreateSizeProcess">
      <wsdl:operation name="create">
         <wsdl:input message="client:JDACreateSizeProcessRequestMessage"/>
         <wsdl:output message="client:JDACreateSizeProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="JDACreateSizeProcess">
      <plnk:role name="JDACreateSizeProcessProvider" portType="client:JDACreateSizeProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
