<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="urn:ConsultarAprobacionByIdOperacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ConsultarAprobacionByIdOperacion" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:aproMO="http://www.bcie.org/AprobacionMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultarAprobacionByIdOperacionRequestMessage">
    <wsdl:part name="ConsultarAprobacionByIdOperacionRequest" element="aproMO:ConsultarAprobacionByIdOperacionRequest"/>
  </wsdl:message>
  <wsdl:message name="ConsultarAprobacionByIdOperacionResponseMessage">
    <wsdl:part name="ConsultarAprobacionByIdOperacionResponse" element="aproMO:ConsultarAprobacionByIdOperacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarAprobacionByIdOperacionPT">
    <wsdl:operation name="consultarAprobacionByIdOperacion">
      <wsdl:input message="tns:ConsultarAprobacionByIdOperacionRequestMessage"/>
      <wsdl:output message="tns:ConsultarAprobacionByIdOperacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarAprobacionByIdOperacionPT12Bnd" type="tns:ConsultarAprobacionByIdOperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarAprobacionByIdOperacion">
      <soap12:operation style="document"
                        soapAction="urn:ConsultarAprobacionByIdOperacion/consultarAprobacionByIdOperacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="ConsultarAprobacionByIdOperacionRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="ConsultarAprobacionByIdOperacionResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>