<wsdl:definitions
     name="ConsultarConfiguracion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarConfiguracion/ConsultarConfiguracion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarConfiguracion/ConsultarConfiguracion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarConfiguracion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarConfiguracion_plt" >
    <plt:role name="ConsultarConfiguracion_role" >
      <plt:portType name="tns:ConsultarConfiguracion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarConfiguracion" schemaLocation="../XSD/ConsultarConfiguracion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarConfiguracionInput_msg">
        <wsdl:part name="ConsultarConfiguracionInput_msg" element="db:ConsultarConfiguracionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarConfiguracionOutputCollection_msg">
        <wsdl:part name="ConsultarConfiguracionOutputCollection" element="db:ConsultarConfiguracionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarConfiguracion_ptt">
        <wsdl:operation name="ConsultarConfiguracion">
            <wsdl:input message="tns:ConsultarConfiguracionInput_msg"/>
            <wsdl:output message="tns:ConsultarConfiguracionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
