<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:ConsultarAprobacionById" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ConsultarAprobacionById" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:aproMO="http://www.bcie.org/AprobacionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarAprobacionByIdRequestMessage">
    <part name="ConsultarAprobacionByIdRequest" element="aproMO:ConsultarAprobacionByIdRequest"/>
  </message>
  <message name="ConsultarAprobacionByIdResponseMessage">
    <part name="ConsultarAprobacionByIdResponse" element="aproMO:ConsultarAprobacionByIdResponse"/>
  </message>
  <portType name="ConsultarAprobacionById">
    <operation name="consultarAprobacionByIdRequest">
      <input message="tns:ConsultarAprobacionByIdRequestMessage"/>
      <output message="tns:ConsultarAprobacionByIdResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarAprobacionById12Bnd" type="tns:ConsultarAprobacionById">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarAprobacionByIdRequest">
      <soap12:operation style="document" soapAction="urn:ConsultarAprobacionById/consultarAprobacionByIdRequest"/>
      <input>
        <soap12:body use="literal" parts="ConsultarAprobacionByIdRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ConsultarAprobacionByIdResponse"/>
      </output>
    </operation>
  </binding>
</definitions>