<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ClienteMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ClienteMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/DocumentoMO"
     xmlns:ns2="http://xmlns.bcie.org/ClienteService"
     xmlns:ns3="http://xmlns.bcie.com/CorreoElectronicoService"
     xmlns:ns4="http://xmlns.bcie.com/DocumentoService"
    >
    <plnk:partnerLinkType name="EnviarDocumentoCliente">
        <plnk:role name="EnviarDocumentoClientePT" portType="tns:EnviarDocumentoClientePT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ClienteMO" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/Cliente/V1/Wsdl/BPEL/EnviarDocumentoClienteSOR.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/DocumentoMO" location="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Wsdl/ADAPTER/ComposicionesServiceSAD.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.org/ClienteService" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/Cliente/V1/Wsdl/ADAPTER/ConsultarContactosSAD.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/CorreoElectronicoService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/EnviarCorreoElectronico/V1/WSDL/EnviarCorreoElectronico.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/DocumentoService" location="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Wsdl/ADAPTER/ConsultarDocumentosFenixSAD.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DocumentoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioDocumento/Documento/V1/Schema/DocumentoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
