<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:ns0="http://xmlns.banesco.com/appopt/WFAcctLoanAppSvc/AcctLoanCalcAdd_V1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://xmlns.banesco.com/eopt/AcctLoanCalcAdd_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns5="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:eoptAcctLoanCalcAdd="http://xmlns.banesco.com/eopt/AcctLoanCalcAdd_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/WFAcctLoan/AcctLoanCalcAdd/AcctLoanCalcAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctLoanCalcAddRq"
                                       namespace="http://xmlns.banesco.com/appopt/WFAcctLoanAppSvc/AcctLoanCalcAdd_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/AccountLoan/AcctLoanCalcAdd/AcctLoanCalcAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctLoanCalcAddRq"
                                       namespace="http://xmlns.banesco.com/eopt/AcctLoanCalcAdd_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON APR 30 16:43:29 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:AcctLoanCalcAddRq>
      <tns:AcctLoan>
        <eoAcct:AcctSubtype>
          <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctSubtype/appoptcommon:Cod/text()">
            <ns4:Cod>
              <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctSubtype/appoptcommon:Cod"/>
            </ns4:Cod>
          </xsl:if>
          <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctSubtype/appoptcommon:Desc/text()">
            <ns4:Desc>
              <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctSubtype/appoptcommon:Desc"/>
            </ns4:Desc>
          </xsl:if>
        </eoAcct:AcctSubtype>
        <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CurCode/text()">
          <eoAcct:CurCode>
            <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CurCode"/>
          </eoAcct:CurCode>
        </xsl:if>
        <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:IntRateData">
          <xsl:for-each select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:IntRateData">
            <eoAcct:IntRateData>
              <xsl:if test="ns0:IntRate">
                <eoAcct:IntRate>
                  <xsl:value-of select="ns0:IntRate"/>
                </eoAcct:IntRate>
              </xsl:if>
              <xsl:if test="ns0:IntRateType">
                <eoAcct:IntRateType>
                  <xsl:value-of select="ns0:IntRateType"/>
                </eoAcct:IntRateType>
              </xsl:if>
            </eoAcct:IntRateData>
          </xsl:for-each>
        </xsl:if>
        <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData">
          <eoAcct:CreditAcctData>
            <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CollOfficer/text()">
              <eoAcct:CollOfficer>
                <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CollOfficer"/>
              </eoAcct:CollOfficer>
            </xsl:if>
            <eoAcct:CreditRegularPmt>
              <eoAcct:PmtTargetDetail>
                <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CreditRegularPmt/ns0:PmtTargetDetail/ns0:StartDate/text()">
                  <eoAcct:StartDate>
                    <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CreditRegularPmt/ns0:PmtTargetDetail/ns0:StartDate"/>
                  </eoAcct:StartDate>
                </xsl:if> 
              </eoAcct:PmtTargetDetail>
            </eoAcct:CreditRegularPmt>
            <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:Term/text()">
              <eoAcct:Term>
                <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:Term/ns0:ProposedTerm/text()">
                  <eoAcct:ProposedTerm>
                    <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:Term/ns0:ProposedTerm"/>
                  </eoAcct:ProposedTerm>
                </xsl:if>
              </eoAcct:Term>
            </xsl:if>
            <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CreditRegularPmt/ns0:CreditAcctPmtInfo">
              <eoAcct:CreditAcctPmtInfo>
                <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CreditRegularPmt/ns0:CreditAcctPmtInfo/ns0:FirstPmtDt">
                  <eoAcct:FirstPmtDt>
                    <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:CreditAcctData/ns0:CreditRegularPmt/ns0:CreditAcctPmtInfo/ns0:FirstPmtDt"/>
                  </eoAcct:FirstPmtDt>
                </xsl:if>
              </eoAcct:CreditAcctPmtInfo>
            </xsl:if>
          </eoAcct:CreditAcctData>
        </xsl:if>
        <eoAcct:AcctMember>
          <eoAcct:PartyKey>
            <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctMember/ns0:PartyKey/ns0:PartyId/text()">
              <ns7:PartyId>
                <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctMember/ns0:PartyKey/ns0:PartyId"/>
              </ns7:PartyId>
            </xsl:if>
          </eoAcct:PartyKey>
        </eoAcct:AcctMember>
        <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo">
          <eoAcct:AcctOpeningInfo>
            <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:InitialAmt/text()">
              <eoAcct:InitialAmt>
                <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:InitialAmt/appoptcommon:Amt/text()">
                  <ns4:Amt>
                    <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:InitialAmt/appoptcommon:Amt"/>
                  </ns4:Amt>
                </xsl:if>
                <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:InitialAmt/appoptcommon:CurCode/text()">
                  <ns4:CurCode>
                    <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:InitialAmt/appoptcommon:CurCode"/>
                  </ns4:CurCode>
                </xsl:if>
              </eoAcct:InitialAmt>
            </xsl:if>
            <xsl:if test="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:SaleOfficer/text()">
              <eoAcct:SaleOfficer>
                <xsl:value-of select="/ns0:AcctLoanCalcAddRq/ns0:AcctLoan/ns0:AcctOpeningInfo/ns0:SaleOfficer"/>
              </eoAcct:SaleOfficer>
            </xsl:if>
          </eoAcct:AcctOpeningInfo>
        </xsl:if>
      </tns:AcctLoan>
    </tns:AcctLoanCalcAddRq>
  </xsl:template>
</xsl:stylesheet>