<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/ConsultarAdjunto" name="ConsultarAdjunto_db_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarAdjunto.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/ConsultarAdjunto"/>
    <wsdl:binding name="ConsultarAdjunto_ptt-binding" type="con:ConsultarAdjunto_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/ConsultarAdjunto">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarAdjunto">
            <soap:operation soapAction="ConsultarAdjunto"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>