<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="urn:ResponsableSolicitudMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="urn:ResponsableSolicitudMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarResponsableSolicitud">
        <plnk:role name="ResponsableSolicitudPT" portType="tns:ResponsableSolicitudPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:ResponsableSolicitudMO" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConsultarResponsableSolicitud/V1/WSDL/ResponsableSolicitud.wsdl"/>
</wsdl:definitions>
