<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerCuestionaroElegibilidadV2db" name="ObtenerCuestionaroElegibilidadV2db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ObtenerCuestionaroElegibilidadV2db.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerCuestionaroElegibilidadV2db"/>
    <wsdl:binding name="ObtenerCuestionaroElegibilidadV2db_ptt-binding" type="obt:ObtenerCuestionaroElegibilidadV2db_ptt" xmlns:obt="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerCuestionaroElegibilidadV2db">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ObtenerCuestionaroElegibilidadV2db">
            <soap:operation soapAction="ObtenerCuestionaroElegibilidadV2db"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>