<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/EliminarEventoCondicionByIdCondicionSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/EliminarEventoCondicionByIdCondicionSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EliminarEventoCondicionByIdCondicion_SB">
        <plnk:role name="EliminarEventoCondicionByIdCondicion_PT" portType="tns:EliminarEventoCondicionByIdCondicion_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/EliminarEventoCondicionByIdCondicionSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Condicion/V1/Wsdl/ADAPTER/EliminarEventoCondicionByIdCondicionSAD.wsdl"/>
</wsdl:definitions>
