<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AplicarEnvioCobroSOR"
     targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarEnvioCobroSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarEnvioCobroSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:ns2="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarAmpliacionSOR"
    >
    <plnk:partnerLinkType name="AplicarEnvioCobroSOAP">
        <plnk:role name="AplicarEnvioCobro_ptt" portType="tns:AplicarEnvioCobro_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarEnvioCobroSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Operacion/V1/Wsdl/BPEL/AplicarEnvioCobroSOR.wsdl"/>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarAmpliacionSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/AplicarAmpliacionSOR.wsdl"/>
</wsdl:definitions>
