<wsdl:definitions name="DecodificarParametros" targetNamespace="http://www.bcie.com/DecodificarParametros" 
  xmlns:tns="http://www.bcie.com/DecodificarParametros" 
  xmlns:DecPaMO="http://www.bcie.org/DecodificarParametrosMO" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/DecodificarParametrosMO" schemaLocation="../Schema/DecodificarParametrosMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="DecodificarParametrosrequest">
      <wsdl:part name="request" element="DecPaMO:DecodificarParametrosRequest"/>
    </wsdl:message>
    <wsdl:message name="DecodificarParametrosResponse">
          <wsdl:part name="response" element="DecPaMO:DecodificarParametrosResponse"/>
    </wsdl:message>
    <wsdl:portType name="DecodificarParametros_ptt">
        <wsdl:operation name="DecodificarParametros">
            <wsdl:input message="tns:DecodificarParametrosrequest"/>
            <wsdl:output message="tns:DecodificarParametrosResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DecodificarParametros_pttSOAP12Binding" type="tns:DecodificarParametros_ptt">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="DecodificarParametros">
            <soap12:operation style="document" soapAction="http://www.bcie.com/DecodificarParametros/DecodificarParametros"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>