<wsdl:definitions
     name="ConsultarSolicitudAprobacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConsultarSolicitudAprobacion/ConsultarSolicitudAprobacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConsultarSolicitudAprobacion/ConsultarSolicitudAprobacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSolicitudAprobacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarSolicitudAprobacion_plt" >
    <plt:role name="ConsultarSolicitudAprobacion_role" >
      <plt:portType name="tns:ConsultarSolicitudAprobacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSolicitudAprobacion" schemaLocation="../XSD/ConsultarSolicitudAprobacion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarSolicitudAprobacionInput_msg">
        <wsdl:part name="ConsultarSolicitudAprobacionInput_msg" element="db:ConsultarSolicitudAprobacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarSolicitudAprobacionOutputCollection_msg">
        <wsdl:part name="ConsultarSolicitudAprobacionOutputCollection" element="db:ConsultarSolicitudAprobacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarSolicitudAprobacion_ptt">
        <wsdl:operation name="ConsultarSolicitudAprobacion">
            <wsdl:input message="tns:ConsultarSolicitudAprobacionInput_msg"/>
            <wsdl:output message="tns:ConsultarSolicitudAprobacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
