<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/testFtpSinxml/TestMasterEDi" name="TestMasterEDi-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="TestMasterEDi.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/testFtpSinxml/TestMasterEDi"/>
    <wsdl:binding name="Put_ptt-binding" type="tes:Put_ptt" xmlns:tes="http://xmlns.oracle.com/pcbpel/adapter/ftp/ServiceBusApplication/testFtpSinxml/TestMasterEDi">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Put">
            <soap:operation soapAction="Put"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>