<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/GestionCobroMO" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/GestionCobroMO" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/GestionCobroMO/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/GestionCobroMO" schemaLocation="../../Schema/GestionCobroMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConsultarGestionCobroRequestMessage">
    <part name="request" element="tns:ConsultarGestionCobroRequest"/>
  </message>
  <message name="ConsultarGestionCobroResponseMessage">
    <part name="response" element="tns:ConsultarGestionCobroResponse"/>
  </message>
  <portType name="ConsultarGestionCobroPT">
    <operation name="ConsultarGestionCobro">
      <input message="tns:ConsultarGestionCobroRequestMessage"/>
      <output message="tns:ConsultarGestionCobroResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarGestionCobroPTSOAP12Bnd" type="tns:ConsultarGestionCobroPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarGestionCobro">
      <soap12:operation style="document" soapAction="http://www.bcie.org/GestionCobroMO/ConsultarGestionCobro"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>