<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://www.bcie.org/LineaCreditoMO"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns3="http://www.bcie.org/TerminoBO" xmlns:ns4="http://www.bcie.org/OperacionBO"
                xmlns:ns6="http://www.bcie.org/CommonBO" xmlns:ns7="http://www.bcie.org/ResultBO"
                xmlns:ns10="http://www.bcie.org/AprobacionBO" xmlns:ns11="http://www.bcie.org/LineaCreditoBO"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ns1="http://www.bcie.org/CondicionBO" xmlns:ns2="http://www.bcie.org/ProductoBO"
                xmlns:ns5="http://www.bcie.org/DeclaracionJuradaBO" xmlns:ns8="http://www.bcie.org/DocumentoBO"
                xmlns:ns9="http://www.bcie.org/ComisionBO" xmlns:tns="ConsultarLineaCredito"
                xmlns:ns12="http://www.bcie.org/CatalogoBO" xmlns:ns13="http://www.bcie.org/ContratoBO"
                xmlns:ns14="http://www.bcie.org/ClienteBO" xmlns:ns15="http://www.bcie.org/AtributoBO"
                xmlns:ns16="http://www.bcie.org/ErrorBO" xmlns:ns17="http://www.bcie.org/DesembolsoBO"
                xmlns:ns19="http://www.bcie.org/MatrizTCCBO" xmlns:ns18="http://www.bcie.org/HerramientaCEBO"
                xmlns:ns20="http://www.bcie.org/ReglaBO">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/ConsultarLineaCreditoSOR.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ConsultarLineaCreditoBPELResponse"
                                       namespace="http://www.bcie.org/LineaCreditoMO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/ConsultarLineaCreditoSOR.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ConsultarLineaCreditoBPELResponse"
                                       namespace="http://www.bcie.org/LineaCreditoMO"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED AUG 24 18:21:40 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:ConsultarLineaCreditoBPELResponse>
      <ns0:LineaCredito>
        <ns11:idLineaCredito>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:idLineaCredito"/>
        </ns11:idLineaCredito>
        <ns11:idContrato>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:idContrato"/>
        </ns11:idContrato>
        <ns11:NumeroLineaCredito>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:NumeroLineaCredito"/>
        </ns11:NumeroLineaCredito>
        <ns11:Descripcion>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Descripcion"/>
        </ns11:Descripcion>
        <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube">
          <ns11:Flexcube>
            <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube/ns11:id">
              <ns11:id>
                <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube/ns11:id"/>
              </ns11:id>
            </xsl:if>
            <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube/ns11:idProductoFlexcube">
              <ns11:idProductoFlexcube>
                <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube/ns11:idProductoFlexcube"/>
              </ns11:idProductoFlexcube>
            </xsl:if>
            <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube/ns11:idFlexcubePasivo">
              <ns11:idFlexcubePasivo>
                <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Flexcube/ns11:idFlexcubePasivo"/>
              </ns11:idFlexcubePasivo>
            </xsl:if>
          </ns11:Flexcube>
        </xsl:if>
        <ns11:Fondo>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Fondo"/>
        </ns11:Fondo>
		<ns11:IdTipoMonedaMontoLinea>
            <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:IdTipoMonedaMontoLinea"/>
        </ns11:IdTipoMonedaMontoLinea>
        <ns11:MontoLinea>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:MontoLinea"/>
        </ns11:MontoLinea>
        <ns11:EsRevolvente>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:EsRevolvente"/>
        </ns11:EsRevolvente>
        <ns11:TratamientoDiasFeriados>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:TratamientoDiasFeriados"/>
        </ns11:TratamientoDiasFeriados>
        <ns11:FechaValor>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:FechaValor"/>
        </ns11:FechaValor>
        <ns11:FechaVencimiento>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:FechaVencimiento"/>
        </ns11:FechaVencimiento>
        <ns11:CodigoPantallaLimite>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:CodigoPantallaLimite"/>
        </ns11:CodigoPantallaLimite>
        <ns11:CodigoSerialLimite>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:CodigoSerialLimite"/>
        </ns11:CodigoSerialLimite>
        <ns11:CodigoAsignacion>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:CodigoAsignacion"/>
        </ns11:CodigoAsignacion>
        <ns11:DescripcionAsignacion>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:DescripcionAsignacion"/>
        </ns11:DescripcionAsignacion>
        <ns11:CondicionEspecial>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:CondicionEspecial"/>
        </ns11:CondicionEspecial>
        <ns11:FechaRegistro>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:FechaRegistro"/>
        </ns11:FechaRegistro>
        <ns11:FechaMaximaDesembolso>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:FechaMaximaDesembolso"/>
        </ns11:FechaMaximaDesembolso>
        <ns11:Estado>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Estado"/>
        </ns11:Estado>
        <ns11:descCondEspecial>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:descCondEspecial"/>
        </ns11:descCondEspecial>
        <ns11:frecuenciaGracia>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:frecuenciaGracia"/>
        </ns11:frecuenciaGracia>
        <ns11:plazoGracia>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:plazoGracia"/>
        </ns11:plazoGracia>
        <ns11:frecuenciaFinanciamiento>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:frecuenciaFinanciamiento"/>
        </ns11:frecuenciaFinanciamiento>
        <ns11:plazoFinanciamiento>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:plazoFinanciamiento"/>
        </ns11:plazoFinanciamiento>
        <ns11:recursosExternos>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:recursosExternos"/>
        </ns11:recursosExternos>
        <ns11:tasaMinima>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:tasaMinima"/>
        </ns11:tasaMinima>
        <ns11:tasaMaxima>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:tasaMaxima"/>
        </ns11:tasaMaxima>
        <ns11:montoMinimo>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:montoMinimo"/>
        </ns11:montoMinimo>
        <ns11:montoMaximo>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:montoMaximo"/>
        </ns11:montoMaximo>
        <xsl:for-each select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Monto">
          <ns11:Monto>
            <ns6:tipo>
              <xsl:if test="ns6:tipo/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns6:tipo/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="ns6:tipo/ns12:Descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns6:tipo/ns12:Descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="ns6:tipo/ns12:DescripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="ns6:tipo/ns12:DescripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns6:tipo/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns6:tipo/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns6:tipo/ns12:codigoExterno"/>
              </ns12:codigoExterno>
            </ns6:tipo>
            <ns6:importe>
              <xsl:value-of select="ns6:importe"/>
            </ns6:importe>
            <xsl:if test="ns6:moneda">
              <ns6:moneda>
                <xsl:if test="ns6:moneda/ns12:Id">
                  <ns12:Id>
                    <xsl:value-of select="ns6:moneda/ns12:Id"/>
                  </ns12:Id>
                </xsl:if>
                <xsl:if test="ns6:moneda/ns12:Descripcion">
                  <ns12:Descripcion>
                    <xsl:value-of select="ns6:moneda/ns12:Descripcion"/>
                  </ns12:Descripcion>
                </xsl:if>
                <xsl:if test="ns6:moneda/ns12:DescripcionCorta">
                  <ns12:DescripcionCorta>
                    <xsl:value-of select="ns6:moneda/ns12:DescripcionCorta"/>
                  </ns12:DescripcionCorta>
                </xsl:if>
                <xsl:if test="ns6:moneda/ns12:estatus">
                  <ns12:estatus>
                    <xsl:value-of select="ns6:moneda/ns12:estatus"/>
                  </ns12:estatus>
                </xsl:if>
                <xsl:if test="ns6:moneda/ns12:codigoExterno">
                  <ns12:codigoExterno>
                    <xsl:value-of select="ns6:moneda/ns12:codigoExterno"/>
                  </ns12:codigoExterno>
                </xsl:if>
              </ns6:moneda>
            </xsl:if>
          </ns11:Monto>
        </xsl:for-each>
        <ns11:MoverEntreMeses>
          <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:MoverEntreMeses"/>
        </ns11:MoverEntreMeses>
        <xsl:for-each select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion">
          <ns11:Condicion>
            <ns1:idCondicion>
              <xsl:value-of select="ns1:idCondicion"/>
            </ns1:idCondicion>
            <ns1:operacion>
              <xsl:value-of select="ns1:operacion"/>
            </ns1:operacion>
            <xsl:if test="ns1:nombre">
              <ns1:nombre>
                <xsl:value-of select="ns1:nombre"/>
              </ns1:nombre>
            </xsl:if>
            <xsl:if test="ns1:descripcion">
              <ns1:descripcion>
                <xsl:value-of select="ns1:descripcion"/>
              </ns1:descripcion>
            </xsl:if>
            <xsl:if test="ns1:tipoCondicion">
              <ns1:tipoCondicion>
                <xsl:if test="ns1:tipoCondicion/ns1:idCatCondicion">
                  <ns1:idCatCondicion>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:idCatCondicion"/>
                  </ns1:idCatCondicion>
                </xsl:if>
                <xsl:if test="ns1:descripcion">
                  <ns1:descripcion>
                    <xsl:value-of select="ns1:descripcion"/>
                  </ns1:descripcion>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                  <ns1:descripcionCorta>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                  </ns1:descripcionCorta>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:idTipoCondicion">
                  <ns1:idTipoCondicion>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:idTipoCondicion"/>
                  </ns1:idTipoCondicion>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:esEditableEnFormalizacion">
                  <ns1:esEditableEnFormalizacion>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:esEditableEnFormalizacion"/>
                  </ns1:esEditableEnFormalizacion>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:requiereValidarCOFI">
                  <ns1:requiereValidarCOFI>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:requiereValidarCOFI"/>
                  </ns1:requiereValidarCOFI>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:sePuedeDispensar">
                  <ns1:sePuedeDispensar>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:sePuedeDispensar"/>
                  </ns1:sePuedeDispensar>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:esPlantilla">
                  <ns1:esPlantilla>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:esPlantilla"/>
                  </ns1:esPlantilla>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:idCondicionPrecarga">
                  <ns1:idCondicionPrecarga>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:idCondicionPrecarga"/>
                  </ns1:idCondicionPrecarga>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:fechaRegistro">
                  <ns1:fechaRegistro>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:fechaRegistro"/>
                  </ns1:fechaRegistro>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:estado">
                  <ns1:estado>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:estado"/>
                  </ns1:estado>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                  <ns1:codigoExterno>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                  </ns1:codigoExterno>
                </xsl:if>
              </ns1:tipoCondicion>
            </xsl:if>
            <xsl:for-each select="ns1:categoriaCondicion">
              <ns1:categoriaCondicion>
                <ns1:id>
                  <xsl:value-of select="ns1:id"/>
                </ns1:id>
                <ns1:descripcion>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion"/>
                </ns1:descripcion>
                <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta">
                  <ns1:descripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta"/>
                  </ns1:descripcionCorta>
                </xsl:if>
                <xsl:if test="ns1:estatus">
                  <ns1:estatus>
                    <xsl:value-of select="ns1:estatus"/>
                  </ns1:estatus>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno">
                  <ns1:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno"/>
                  </ns1:codigoExterno>
                </xsl:if>
                <ns1:validadores>
                  <ns12:Id>
                    <xsl:value-of select="ns1:id"/>
                  </ns12:Id>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion">
                    <ns12:Descripcion>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion"/>
                    </ns12:Descripcion>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta">
                    <ns12:DescripcionCorta>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta"/>
                    </ns12:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns1:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="ns1:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno">
                    <ns12:codigoExterno>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno"/>
                    </ns12:codigoExterno>
                  </xsl:if>
                </ns1:validadores>
              </ns1:categoriaCondicion>
            </xsl:for-each>
            <ns1:controlCondicion>
              <ns12:Id>
                <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
              </ns12:Id>
              <xsl:if test="ns1:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns1:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns1:controlCondicion>
            <ns1:eventoCondicion>
              <ns12:Id>
                <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
              </ns12:Id>
              <xsl:if test="ns1:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns1:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns1:eventoCondicion>
            <ns1:tipoFechaInicio>
              <ns12:Id>
                <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
              </ns12:Id>
              <xsl:if test="ns1:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns1:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns1:tipoFechaInicio>
            <xsl:if test="ns1:fechaInicio">
              <ns1:fechaInicio>
                <xsl:value-of select="ns1:fechaInicio"/>
              </ns1:fechaInicio>
            </xsl:if>
            <xsl:if test="ns1:plazo">
              <ns1:plazo>
                <xsl:value-of select="ns1:plazo"/>
              </ns1:plazo>
            </xsl:if>
            <ns1:frecuenciaPlazo>
              <ns12:Id>
                <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
              </ns12:Id>
              <xsl:if test="ns1:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns1:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns1:frecuenciaPlazo>
            <xsl:if test="ns1:fechaFinal">
              <ns1:fechaFinal>
                <xsl:value-of select="ns1:fechaFinal"/>
              </ns1:fechaFinal>
            </xsl:if>
            <xsl:if test="ns1:estadoTCC">
              <ns1:estadoTCC>
                <ns15:id>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
                </ns15:id>
                <xsl:if test="ns1:descripcion">
                  <ns15:descripcion>
                    <xsl:value-of select="ns1:descripcion"/>
                  </ns15:descripcion>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                  <ns15:descripcionCorta>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                  </ns15:descripcionCorta>
                </xsl:if>
                <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                  <ns15:estatus>
                    <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                  </ns15:estatus>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                  <ns15:codigoExterno>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                  </ns15:codigoExterno>
                </xsl:if>
                <xsl:if test="ns1:estadoTCC/ns15:esSubEstado">
                  <ns15:esSubEstado>
                    <xsl:value-of select="ns1:estadoTCC/ns15:esSubEstado"/>
                  </ns15:esSubEstado>
                </xsl:if>
              </ns1:estadoTCC>
            </xsl:if>
            <xsl:if test="ns1:estadoTCC">
              <ns1:subEstadoTCC>
                <ns15:id>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
                </ns15:id>
                <xsl:if test="ns1:descripcion">
                  <ns15:descripcion>
                    <xsl:value-of select="ns1:descripcion"/>
                  </ns15:descripcion>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:descripcionCorta">
                  <ns15:descripcionCorta>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:descripcionCorta"/>
                  </ns15:descripcionCorta>
                </xsl:if>
                <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                  <ns15:estatus>
                    <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                  </ns15:estatus>
                </xsl:if>
                <xsl:if test="ns1:tipoCondicion/ns1:codigoExterno">
                  <ns15:codigoExterno>
                    <xsl:value-of select="ns1:tipoCondicion/ns1:codigoExterno"/>
                  </ns15:codigoExterno>
                </xsl:if>
                <xsl:if test="ns1:estadoTCC/ns15:esSubEstado">
                  <ns15:esSubEstado>
                    <xsl:value-of select="ns1:estadoTCC/ns15:esSubEstado"/>
                  </ns15:esSubEstado>
                </xsl:if>
              </ns1:subEstadoTCC>
            </xsl:if>
            <xsl:if test="ns1:tipoCondicion/ns1:fechaRegistro">
              <ns1:fechaRegistro>
                <xsl:value-of select="ns1:tipoCondicion/ns1:fechaRegistro"/>
              </ns1:fechaRegistro>
            </xsl:if>
            <xsl:if test="ns1:tipoCondicion/ns1:estado">
              <ns1:estado>
                <xsl:value-of select="ns1:tipoCondicion/ns1:estado"/>
              </ns1:estado>
            </xsl:if>
            <xsl:if test="ns1:condicionEnmendada">
              <ns1:condicionEnmendada>
                <xsl:value-of select="ns1:condicionEnmendada"/>
              </ns1:condicionEnmendada>
            </xsl:if>
            <xsl:if test="ns1:fechaEnmienda">
              <ns1:fechaEnmienda>
                <xsl:value-of select="ns1:fechaEnmienda"/>
              </ns1:fechaEnmienda>
            </xsl:if>
            <xsl:for-each select="ns1:configAtributo">
              <ns1:configAtributo>
                <ns15:id>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:id"/>
                </ns15:id>
                <ns15:columna>
                  <xsl:value-of select="ns15:columna"/>
                </ns15:columna>
                <xsl:if test="ns15:ordenamiento">
                  <ns15:ordenamiento>
                    <xsl:value-of select="ns15:ordenamiento"/>
                  </ns15:ordenamiento>
                </xsl:if>
                <xsl:if test="ns15:soloLectura">
                  <ns15:soloLectura>
                    <xsl:value-of select="ns15:soloLectura"/>
                  </ns15:soloLectura>
                </xsl:if>
                <xsl:if test="ns15:esObligatorio">
                  <ns15:esObligatorio>
                    <xsl:value-of select="ns15:esObligatorio"/>
                  </ns15:esObligatorio>
                </xsl:if>
                <xsl:if test="ns15:etiqueta">
                  <ns15:etiqueta>
                    <xsl:value-of select="ns15:etiqueta"/>
                  </ns15:etiqueta>
                </xsl:if>
                <xsl:for-each select="ns15:valor">
                  <ns15:valor>
                    <xsl:value-of select="."/>
                  </ns15:valor>
                </xsl:for-each>
                <xsl:if test="ns15:tipoValor">
                  <ns15:tipoValor>
                    <xsl:value-of select="ns15:tipoValor"/>
                  </ns15:tipoValor>
                </xsl:if>
                <ns15:catalogo>
                  <ns12:Id>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:id"/>
                  </ns12:Id>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion">
                    <ns12:Descripcion>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion"/>
                    </ns12:Descripcion>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta">
                    <ns12:DescripcionCorta>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta"/>
                    </ns12:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno">
                    <ns12:codigoExterno>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno"/>
                    </ns12:codigoExterno>
                  </xsl:if>
                </ns15:catalogo>
              </ns1:configAtributo>
            </xsl:for-each>
            <xsl:if test="ns1:evidencia">
              <ns1:evidencia>
                <xsl:for-each select="ns1:evidencia/ns8:Documento">
                  <ns8:Documento>
                    <xsl:if test="ns8:idDocumento">
                      <ns8:idDocumento>
                        <xsl:value-of select="ns8:idDocumento"/>
                      </ns8:idDocumento>
                    </xsl:if>
                    <xsl:if test="ns8:idTipoDocumento">
                      <ns8:idTipoDocumento>
                        <xsl:value-of select="ns8:idTipoDocumento"/>
                      </ns8:idTipoDocumento>
                    </xsl:if>
                    <xsl:if test="ns8:idTipoDocumentoExterno">
                      <ns8:idTipoDocumentoExterno>
                        <xsl:value-of select="ns8:idTipoDocumentoExterno"/>
                      </ns8:idTipoDocumentoExterno>
                    </xsl:if>
                    <xsl:if test="ns8:nombreTipoDocumento">
                      <ns8:nombreTipoDocumento>
                        <xsl:value-of select="ns8:nombreTipoDocumento"/>
                      </ns8:nombreTipoDocumento>
                    </xsl:if>
                    <xsl:if test="ns8:etapa">
                      <ns8:etapa>
                        <xsl:value-of select="ns8:etapa"/>
                      </ns8:etapa>
                    </xsl:if>
                    <xsl:if test="ns8:codigoDocumento">
                      <ns8:codigoDocumento>
                        <xsl:value-of select="ns8:codigoDocumento"/>
                      </ns8:codigoDocumento>
                    </xsl:if>
                    <xsl:if test="ns8:idExterno">
                      <ns8:idExterno>
                        <xsl:value-of select="ns8:idExterno"/>
                      </ns8:idExterno>
                    </xsl:if>
                    <xsl:if test="ns8:idDocAreaTipo">
                      <ns8:idDocAreaTipo>
                        <xsl:value-of select="ns8:idDocAreaTipo"/>
                      </ns8:idDocAreaTipo>
                    </xsl:if>
                    <xsl:if test="ns8:idOperacion">
                      <ns8:idOperacion>
                        <xsl:value-of select="ns8:idOperacion"/>
                      </ns8:idOperacion>
                    </xsl:if>
                    <xsl:if test="ns8:idCliente">
                      <ns8:idCliente>
                        <xsl:value-of select="ns8:idCliente"/>
                      </ns8:idCliente>
                    </xsl:if>
                    <xsl:if test="ns8:idPais">
                      <ns8:idPais>
                        <xsl:value-of select="ns8:idPais"/>
                      </ns8:idPais>
                    </xsl:if>
                    <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:nombre">
                      <ns8:nombre>
                        <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:nombre"/>
                      </ns8:nombre>
                    </xsl:if>
                    <xsl:if test="ns8:filename">
                      <ns8:filename>
                        <xsl:value-of select="ns8:filename"/>
                      </ns8:filename>
                    </xsl:if>
                    <xsl:if test="ns8:mime_type">
                      <ns8:mime_type>
                        <xsl:value-of select="ns8:mime_type"/>
                      </ns8:mime_type>
                    </xsl:if>
                    <xsl:if test="ns8:tamanio">
                      <ns8:tamanio>
                        <xsl:value-of select="ns8:tamanio"/>
                      </ns8:tamanio>
                    </xsl:if>
                    <xsl:if test="ns8:idAdjunto">
                      <ns8:idAdjunto>
                        <xsl:value-of select="ns8:idAdjunto"/>
                      </ns8:idAdjunto>
                    </xsl:if>
                    <xsl:if test="ns8:esJustificacion">
                      <ns8:esJustificacion>
                        <xsl:value-of select="ns8:esJustificacion"/>
                      </ns8:esJustificacion>
                    </xsl:if>
                    <xsl:if test="ns8:comentario">
                      <ns8:comentario>
                        <xsl:value-of select="ns8:comentario"/>
                      </ns8:comentario>
                    </xsl:if>
                    <xsl:if test="ns8:fechaDocumento">
                      <ns8:fechaDocumento>
                        <xsl:value-of select="ns8:fechaDocumento"/>
                      </ns8:fechaDocumento>
                    </xsl:if>
                    <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:fechaRegistro">
                      <ns8:fechaRegistro>
                        <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:fechaRegistro"/>
                      </ns8:fechaRegistro>
                    </xsl:if>
                    <xsl:if test="ns8:status">
                      <ns8:status>
                        <xsl:value-of select="ns8:status"/>
                      </ns8:status>
                    </xsl:if>
                    <xsl:if test="ns8:estatusTipoDoc">
                      <ns8:estatusTipoDoc>
                        <xsl:value-of select="ns8:estatusTipoDoc"/>
                      </ns8:estatusTipoDoc>
                    </xsl:if>
                    <xsl:if test="ns8:codExtTipoDoc">
                      <ns8:codExtTipoDoc>
                        <xsl:value-of select="ns8:codExtTipoDoc"/>
                      </ns8:codExtTipoDoc>
                    </xsl:if>
                    <xsl:if test="ns8:tarea">
                      <ns8:tarea>
                        <xsl:value-of select="ns8:tarea"/>
                      </ns8:tarea>
                    </xsl:if>
                    <xsl:if test="ns8:idtarea">
                      <ns8:idtarea>
                        <xsl:value-of select="ns8:idtarea"/>
                      </ns8:idtarea>
                    </xsl:if>
                    <xsl:if test="ns8:content">
                      <ns8:content>
                        <xsl:value-of select="ns8:content"/>
                      </ns8:content>
                    </xsl:if>
                    <xsl:if test="ns8:PuedeModificar">
                      <ns8:PuedeModificar>
                        <xsl:value-of select="ns8:PuedeModificar"/>
                      </ns8:PuedeModificar>
                    </xsl:if>
                    <xsl:if test="ns8:PuedeBorrar">
                      <ns8:PuedeBorrar>
                        <xsl:value-of select="ns8:PuedeBorrar"/>
                      </ns8:PuedeBorrar>
                    </xsl:if>
                    <xsl:if test="ns8:usuarioAgrega">
                      <ns8:usuarioAgrega>
                        <xsl:value-of select="ns8:usuarioAgrega"/>
                      </ns8:usuarioAgrega>
                    </xsl:if>
                    <xsl:if test="ns8:usuarioUltimaActualizacion">
                      <ns8:usuarioUltimaActualizacion>
                        <xsl:value-of select="ns8:usuarioUltimaActualizacion"/>
                      </ns8:usuarioUltimaActualizacion>
                    </xsl:if>
                    <xsl:if test="ns8:accionARealizar">
                      <ns8:accionARealizar>
                        <xsl:value-of select="ns8:accionARealizar"/>
                      </ns8:accionARealizar>
                    </xsl:if>
                    <xsl:if test="ns8:idFlujoNegocio">
                      <ns8:idFlujoNegocio>
                        <xsl:value-of select="ns8:idFlujoNegocio"/>
                      </ns8:idFlujoNegocio>
                    </xsl:if>
                  </ns8:Documento>
                </xsl:for-each>
              </ns1:evidencia>
            </xsl:if>
            <xsl:for-each select="ns1:observaciones">
              <ns1:observaciones>
                <ns1:id>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:id"/>
                </ns1:id>
                <xsl:if test="ns1:observacion">
                  <ns1:observacion>
                    <xsl:value-of select="ns1:observacion"/>
                  </ns1:observacion>
                </xsl:if>
                <xsl:if test="ns1:loginUsuario">
                  <ns1:loginUsuario>
                    <xsl:value-of select="ns1:loginUsuario"/>
                  </ns1:loginUsuario>
                </xsl:if>
                <xsl:if test="ns1:nombreUsuario">
                  <ns1:nombreUsuario>
                    <xsl:value-of select="ns1:nombreUsuario"/>
                  </ns1:nombreUsuario>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:fechaRegistro">
                  <ns1:fechaRegistro>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:fechaRegistro"/>
                  </ns1:fechaRegistro>
                </xsl:if>
                <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:estatus">
                  <ns1:estatus>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:estatus"/>
                  </ns1:estatus>
                </xsl:if>
                <xsl:if test="ns1:esPrincipal">
                  <ns1:esPrincipal>
                    <xsl:value-of select="ns1:esPrincipal"/>
                  </ns1:esPrincipal>
                </xsl:if>
                <ns1:tareaBPM>
                  <ns12:Id>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:id"/>
                  </ns12:Id>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion">
                    <ns12:Descripcion>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:descripcion"/>
                    </ns12:Descripcion>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta">
                    <ns12:DescripcionCorta>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:descripcionCorta"/>
                    </ns12:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:categoriaCondicion/ns1:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno">
                    <ns12:codigoExterno>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Condicion/ns1:tipoCondicion/ns1:codigoExterno"/>
                    </ns12:codigoExterno>
                  </xsl:if>
                </ns1:tareaBPM>
              </ns1:observaciones>
            </xsl:for-each>
            <ns1:lineaCredito>
              <ns15:id>
                <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
              </ns15:id>
              <xsl:if test="ns1:descripcion">
                <ns15:descripcion>
                  <xsl:value-of select="ns1:descripcion"/>
                </ns15:descripcion>
              </xsl:if>
              <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                </ns15:estatus>
              </xsl:if>
            </ns1:lineaCredito>
            <ns1:fuente>
              <ns15:id>
                <xsl:value-of select="ns1:categoriaCondicion/ns1:id"/>
              </ns15:id>
              <xsl:if test="ns1:descripcion">
                <ns15:descripcion>
                  <xsl:value-of select="ns1:descripcion"/>
                </ns15:descripcion>
              </xsl:if>
              <xsl:if test="ns1:categoriaCondicion/ns1:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns1:categoriaCondicion/ns1:estatus"/>
                </ns15:estatus>
              </xsl:if>
            </ns1:fuente>
            <xsl:if test="ns1:Accion">
              <ns1:Accion>
                <xsl:value-of select="ns1:Accion"/>
              </ns1:Accion>
            </xsl:if>
          </ns11:Condicion>
        </xsl:for-each>
        <xsl:for-each select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino">
          <ns11:Termino>
            <ns3:idTermino>
              <xsl:value-of select="ns3:idTermino"/>
            </ns3:idTermino>
            <ns3:operacion>
              <xsl:value-of select="ns3:operacion"/>
            </ns3:operacion>
            <ns3:nombre>
              <xsl:value-of select="ns3:nombre"/>
            </ns3:nombre>
            <ns3:descripcion>
              <xsl:value-of select="ns3:descripcion"/>
            </ns3:descripcion>
            <ns3:tipoTermino>
              <xsl:if test="ns3:tipoTermino/ns3:idCatTermino">
                <ns3:idCatTermino>
                  <xsl:value-of select="ns3:tipoTermino/ns3:idCatTermino"/>
                </ns3:idCatTermino>
              </xsl:if>
              <ns3:descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns3:descripcion>
              <ns3:descripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns3:descripcionCorta>
              <xsl:if test="ns3:tipoTermino/ns3:idTipoTermino">
                <ns3:idTipoTermino>
                  <xsl:value-of select="ns3:tipoTermino/ns3:idTipoTermino"/>
                </ns3:idTipoTermino>
              </xsl:if>
              <ns3:esEditableEnFormalizacion>
                <xsl:value-of select="ns3:tipoTermino/ns3:esEditableEnFormalizacion"/>
              </ns3:esEditableEnFormalizacion>
              <ns3:requiereValidarCOFI>
                <xsl:value-of select="ns3:tipoTermino/ns3:requiereValidarCOFI"/>
              </ns3:requiereValidarCOFI>
              <ns3:sePuedeDispensar>
                <xsl:value-of select="ns3:tipoTermino/ns3:sePuedeDispensar"/>
              </ns3:sePuedeDispensar>
              <ns3:esPlantilla>
                <xsl:value-of select="ns3:tipoTermino/ns3:esPlantilla"/>
              </ns3:esPlantilla>
              <ns3:requiereOGC>
                <xsl:value-of select="ns3:tipoTermino/ns3:requiereOGC"/>
              </ns3:requiereOGC>
              <ns3:idTerminoPrecarga>
                <xsl:value-of select="ns3:tipoTermino/ns3:idTerminoPrecarga"/>
              </ns3:idTerminoPrecarga>
              <ns3:fechaRegistro>
                <xsl:value-of select="ns3:tipoTermino/ns3:fechaRegistro"/>
              </ns3:fechaRegistro>
              <ns3:estado>
                <xsl:value-of select="ns3:tipoTermino/ns3:estado"/>
              </ns3:estado>
              <ns3:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns3:codigoExterno>
            </ns3:tipoTermino>
            <ns3:tipoFechaInicio>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:tipoFechaInicio>
            <ns3:fechaInicio>
              <xsl:value-of select="ns3:fechaInicio"/>
            </ns3:fechaInicio>
            <ns3:plazo>
              <xsl:value-of select="ns3:plazo"/>
            </ns3:plazo>
            <ns3:frecuenciaPlazo>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:frecuenciaPlazo>
            <ns3:fechaVencimiento>
              <xsl:value-of select="ns3:fechaVencimiento"/>
            </ns3:fechaVencimiento>
            <ns3:moneda>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:moneda>
            <ns3:monto>
              <xsl:value-of select="ns3:monto"/>
            </ns3:monto>
            <ns3:tasa>
              <xsl:value-of select="ns3:tasa"/>
            </ns3:tasa>
            <ns3:tipoTasa>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:tipoTasa>
            <ns3:fecha>
              <xsl:value-of select="ns3:fecha"/>
            </ns3:fecha>
            <ns3:frecuenciaRevision>
              <xsl:value-of select="ns3:frecuenciaRevision"/>
            </ns3:frecuenciaRevision>
            <ns3:tipoFrecuenciaRevision>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:tipoFrecuenciaRevision>
            <ns3:fechaInicioRevision>
              <xsl:value-of select="ns3:fechaInicioRevision"/>
            </ns3:fechaInicioRevision>
            <ns3:frecuenciaPagoInteres>
              <xsl:value-of select="ns3:frecuenciaPagoInteres"/>
            </ns3:frecuenciaPagoInteres>
            <ns3:tipoFrecuenciaPagoInteres>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:tipoFrecuenciaPagoInteres>
            <ns3:fechaInicioPagoInteres>
              <xsl:value-of select="ns3:fechaInicioPagoInteres"/>
            </ns3:fechaInicioPagoInteres>
            <ns3:frecuenciaAmortizacion>
              <xsl:value-of select="ns3:frecuenciaAmortizacion"/>
            </ns3:frecuenciaAmortizacion>
            <ns3:tipoFrecuenciaAmortizacion>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <ns12:Descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns12:Descripcion>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <ns12:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns12:codigoExterno>
            </ns3:tipoFrecuenciaAmortizacion>
            <ns3:mora>
              <xsl:value-of select="ns3:mora"/>
            </ns3:mora>
            <ns3:porcentajeCobertura>
              <xsl:value-of select="ns3:porcentajeCobertura"/>
            </ns3:porcentajeCobertura>
            <ns3:seAplicanRecursosConcesion>
              <xsl:value-of select="ns3:seAplicanRecursosConcesion"/>
            </ns3:seAplicanRecursosConcesion>
            <ns3:seAplicanRecursosExternos>
              <xsl:value-of select="ns3:seAplicanRecursosExternos"/>
            </ns3:seAplicanRecursosExternos>
            <ns3:tipoContraparte>
              <xsl:value-of select="ns3:tipoContraparte"/>
            </ns3:tipoContraparte>
            <ns3:montoMinimoDesembolso>
              <xsl:value-of select="ns3:montoMinimoDesembolso"/>
            </ns3:montoMinimoDesembolso>
            <ns3:montoMaximoDesembolso>
              <xsl:value-of select="ns3:montoMaximoDesembolso"/>
            </ns3:montoMaximoDesembolso>
            <ns3:tasaMinimaDesembolso>
              <xsl:value-of select="ns3:tasaMinimaDesembolso"/>
            </ns3:tasaMinimaDesembolso>
            <ns3:tasaMaximaDesembolso>
              <xsl:value-of select="ns3:tasaMaximaDesembolso"/>
            </ns3:tasaMaximaDesembolso>
            <ns3:estadoTCC>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns15:id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns15:id>
              </xsl:if>
              <ns15:descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns15:descripcion>
              <ns15:descripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns15:descripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns15:estatus>
              </xsl:if>
              <ns15:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns15:codigoExterno>
              <xsl:if test="ns3:estadoTCC/ns15:esSubEstado">
                <ns15:esSubEstado>
                  <xsl:value-of select="ns3:estadoTCC/ns15:esSubEstado"/>
                </ns15:esSubEstado>
              </xsl:if>
            </ns3:estadoTCC>
            <ns3:subEstadoTCC>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns15:id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns15:id>
              </xsl:if>
              <ns15:descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns15:descripcion>
              <ns15:descripcionCorta>
                <xsl:value-of select="ns3:tipoTermino/ns3:descripcionCorta"/>
              </ns15:descripcionCorta>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns15:estatus>
              </xsl:if>
              <ns15:codigoExterno>
                <xsl:value-of select="ns3:tipoTermino/ns3:codigoExterno"/>
              </ns15:codigoExterno>
              <xsl:if test="ns3:estadoTCC/ns15:esSubEstado">
                <ns15:esSubEstado>
                  <xsl:value-of select="ns3:estadoTCC/ns15:esSubEstado"/>
                </ns15:esSubEstado>
              </xsl:if>
            </ns3:subEstadoTCC>
            <ns3:fechaRegistro>
              <xsl:value-of select="ns3:tipoTermino/ns3:fechaRegistro"/>
            </ns3:fechaRegistro>
            <ns3:estado>
              <xsl:value-of select="ns3:tipoTermino/ns3:estado"/>
            </ns3:estado>
            <ns3:terminoEnmendado>
              <xsl:value-of select="ns3:terminoEnmendado"/>
            </ns3:terminoEnmendado>
            <ns3:fechaEnmienda>
              <xsl:value-of select="ns3:fechaEnmienda"/>
            </ns3:fechaEnmienda>
            <xsl:for-each select="ns3:configAtributo">
              <ns3:configAtributo>
                <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoFechaInicio/ns12:Id">
                  <ns15:id>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoFechaInicio/ns12:Id"/>
                  </ns15:id>
                </xsl:if>
                <ns15:columna>
                  <xsl:value-of select="ns15:columna"/>
                </ns15:columna>
                <xsl:if test="ns15:ordenamiento">
                  <ns15:ordenamiento>
                    <xsl:value-of select="ns15:ordenamiento"/>
                  </ns15:ordenamiento>
                </xsl:if>
                <xsl:if test="ns15:soloLectura">
                  <ns15:soloLectura>
                    <xsl:value-of select="ns15:soloLectura"/>
                  </ns15:soloLectura>
                </xsl:if>
                <xsl:if test="ns15:esObligatorio">
                  <ns15:esObligatorio>
                    <xsl:value-of select="ns15:esObligatorio"/>
                  </ns15:esObligatorio>
                </xsl:if>
                <xsl:if test="ns15:etiqueta">
                  <ns15:etiqueta>
                    <xsl:value-of select="ns15:etiqueta"/>
                  </ns15:etiqueta>
                </xsl:if>
                <xsl:for-each select="ns15:valor">
                  <ns15:valor>
                    <xsl:value-of select="."/>
                  </ns15:valor>
                </xsl:for-each>
                <xsl:if test="ns15:tipoValor">
                  <ns15:tipoValor>
                    <xsl:value-of select="ns15:tipoValor"/>
                  </ns15:tipoValor>
                </xsl:if>
                <ns15:catalogo>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoFechaInicio/ns12:Id">
                    <ns12:Id>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoFechaInicio/ns12:Id"/>
                    </ns12:Id>
                  </xsl:if>
                  <ns12:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:descripcion"/>
                  </ns12:Descripcion>
                  <ns12:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoTermino/ns3:descripcionCorta"/>
                  </ns12:DescripcionCorta>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoFechaInicio/ns12:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoFechaInicio/ns12:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <ns12:codigoExterno>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Termino/ns3:tipoTermino/ns3:codigoExterno"/>
                  </ns12:codigoExterno>
                </ns15:catalogo>
              </ns3:configAtributo>
            </xsl:for-each>
            <xsl:if test="ns3:Accion">
              <ns3:Accion>
                <xsl:value-of select="ns3:Accion"/>
              </ns3:Accion>
            </xsl:if>
            <ns3:Contraparte>
              <xsl:if test="ns3:tipoFechaInicio/ns12:Id">
                <ns15:id>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:Id"/>
                </ns15:id>
              </xsl:if>
              <ns15:descripcion>
                <xsl:value-of select="ns3:descripcion"/>
              </ns15:descripcion>
              <xsl:if test="ns3:tipoFechaInicio/ns12:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns3:tipoFechaInicio/ns12:estatus"/>
                </ns15:estatus>
              </xsl:if>
            </ns3:Contraparte>
          </ns11:Termino>
        </xsl:for-each>
        <xsl:for-each select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision">
          <ns11:Comision>
            <ns9:idComision>
              <xsl:value-of select="ns9:idComision"/>
            </ns9:idComision>
            <ns9:idOperacion>
              <xsl:value-of select="ns9:idOperacion"/>
            </ns9:idOperacion>
            <xsl:if test="ns9:nombre">
              <ns9:nombre>
                <xsl:value-of select="ns9:nombre"/>
              </ns9:nombre>
            </xsl:if>
            <xsl:if test="ns9:descripcion">
              <ns9:descripcion>
                <xsl:value-of select="ns9:descripcion"/>
              </ns9:descripcion>
            </xsl:if>
            <xsl:if test="ns9:tipoComision">
              <ns9:tipoComision>
                <xsl:if test="ns9:tipoComision/ns9:idCatComision">
                  <ns9:idCatComision>
                    <xsl:value-of select="ns9:tipoComision/ns9:idCatComision"/>
                  </ns9:idCatComision>
                </xsl:if>
                <ns9:descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns9:descripcion>
                <ns9:descripcionCorta>
                  <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
                </ns9:descripcionCorta>
                <xsl:if test="ns9:tipoComision/ns9:idTipoComision">
                  <xsl:if test="ns9:tipoComision">
                    <ns9:idTipoComision>
                      <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                        <ns12:Id>
                          <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                        </ns12:Id>
                      </xsl:if>
                      <xsl:if test="ns9:descripcion">
                        <ns12:Descripcion>
                          <xsl:value-of select="ns9:descripcion"/>
                        </ns12:Descripcion>
                      </xsl:if>
                      <ns12:DescripcionCorta>
                        <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
                      </ns12:DescripcionCorta>
                      <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                        <ns12:estatus>
                          <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                        </ns12:estatus>
                      </xsl:if>
                      <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                        <ns12:codigoExterno>
                          <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                        </ns12:codigoExterno>
                      </xsl:if>
                    </ns9:idTipoComision>
                  </xsl:if>
                </xsl:if>
                <ns9:esEditableEnFormalizacion>
                  <xsl:value-of select="ns9:tipoComision/ns9:esEditableEnFormalizacion"/>
                </ns9:esEditableEnFormalizacion>
                <ns9:requiereValidarCOFI>
                  <xsl:value-of select="ns9:tipoComision/ns9:requiereValidarCOFI"/>
                </ns9:requiereValidarCOFI>
                <ns9:sePuedeDispensar>
                  <xsl:value-of select="ns9:tipoComision/ns9:sePuedeDispensar"/>
                </ns9:sePuedeDispensar>
                <ns9:seRegistraEnFlexCube>
                  <xsl:value-of select="ns9:tipoComision/ns9:seRegistraEnFlexCube"/>
                </ns9:seRegistraEnFlexCube>
                <ns9:esPlantilla>
                  <xsl:value-of select="ns9:tipoComision/ns9:esPlantilla"/>
                </ns9:esPlantilla>
                <ns9:idComisionPrecarga>
                  <xsl:value-of select="ns9:tipoComision/ns9:idComisionPrecarga"/>
                </ns9:idComisionPrecarga>
                <ns9:fechaRegistro>
                  <xsl:value-of select="ns9:tipoComision/ns9:fechaRegistro"/>
                </ns9:fechaRegistro>
                <ns9:estado>
                  <xsl:value-of select="ns9:tipoComision/ns9:estado"/>
                </ns9:estado>
                <ns9:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns9:codigoExterno>
              </ns9:tipoComision>
            </xsl:if>
            <ns9:moneda>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns9:moneda>
            <xsl:if test="ns9:montoComision">
              <ns9:montoComision>
                <xsl:value-of select="ns9:montoComision"/>
              </ns9:montoComision>
            </xsl:if>
            <xsl:if test="ns9:montoBase">
              <ns9:montoBase>
                <xsl:if test="ns9:montoBase/ns9:idMontoBase">
                  <ns9:idMontoBase>
                    <xsl:value-of select="ns9:montoBase/ns9:idMontoBase"/>
                  </ns9:idMontoBase>
                </xsl:if>
                <xsl:if test="ns9:montoBase/ns9:valorMontoBase">
                  <ns9:valorMontoBase>
                    <xsl:value-of select="ns9:montoBase/ns9:valorMontoBase"/>
                  </ns9:valorMontoBase>
                </xsl:if>
                <xsl:if test="ns9:montoBase/ns9:porcentajeMontoBase">
                  <ns9:porcentajeMontoBase>
                    <xsl:value-of select="ns9:montoBase/ns9:porcentajeMontoBase"/>
                  </ns9:porcentajeMontoBase>
                </xsl:if>
                <xsl:if test="ns9:montoBase/ns9:descripcionMontoBase">
                  <ns9:descripcionMontoBase>
                    <xsl:value-of select="ns9:montoBase/ns9:descripcionMontoBase"/>
                  </ns9:descripcionMontoBase>
                </xsl:if>
              </ns9:montoBase>
            </xsl:if>
            <xsl:if test="ns9:fechaValor">
              <ns9:fechaValor>
                <xsl:value-of select="ns9:fechaValor"/>
              </ns9:fechaValor>
            </xsl:if>
            <xsl:if test="ns9:fechaVencimiento">
              <ns9:fechaVencimiento>
                <xsl:value-of select="ns9:fechaVencimiento"/>
              </ns9:fechaVencimiento>
            </xsl:if>
            <xsl:if test="ns9:fechaInicioCapital">
              <ns9:fechaInicioCapital>
                <xsl:value-of select="ns9:fechaInicioCapital"/>
              </ns9:fechaInicioCapital>
            </xsl:if>
            <xsl:if test="ns9:fechaInicioComision">
              <ns9:fechaInicioComision>
                <xsl:value-of select="ns9:fechaInicioComision"/>
              </ns9:fechaInicioComision>
            </xsl:if>
            <ns9:tipoFrecuencia>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns9:tipoFrecuencia>
            <xsl:if test="ns9:frecuenciaPago">
              <ns9:frecuenciaPago>
                <xsl:value-of select="ns9:frecuenciaPago"/>
              </ns9:frecuenciaPago>
            </xsl:if>
            <xsl:if test="ns9:fondo">
              <ns9:fondo>
                <xsl:value-of select="ns9:fondo"/>
              </ns9:fondo>
            </xsl:if>
            <xsl:if test="ns9:comisionCompartida">
              <ns9:comisionCompartida>
                <xsl:value-of select="ns9:comisionCompartida"/>
              </ns9:comisionCompartida>
            </xsl:if>
            <xsl:if test="ns9:codigoDesembolso">
              <ns9:codigoDesembolso>
                <xsl:value-of select="ns9:codigoDesembolso"/>
              </ns9:codigoDesembolso>
            </xsl:if>
            <xsl:if test="ns9:numeroTesoreria">
              <ns9:numeroTesoreria>
                <xsl:value-of select="ns9:numeroTesoreria"/>
              </ns9:numeroTesoreria>
            </xsl:if>
            <xsl:if test="ns9:codigoContrato">
              <ns9:codigoContrato>
                <xsl:value-of select="ns9:codigoContrato"/>
              </ns9:codigoContrato>
            </xsl:if>
            <ns9:momentoCobro>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns9:momentoCobro>
            <ns9:tipoTasa>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns9:tipoTasa>
            <ns9:baseCalculo>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <ns12:DescripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns12:DescripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns9:baseCalculo>
            <xsl:if test="ns9:responsableComision">
              <ns9:responsableComision>
                <xsl:value-of select="ns9:responsableComision"/>
              </ns9:responsableComision>
            </xsl:if>
            <ns9:estadoTCC>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns15:id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns15:id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns15:descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns15:descripcion>
              </xsl:if>
              <ns15:descripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns15:descripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns15:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns15:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns15:codigoExterno>
              </xsl:if>
              <xsl:if test="ns9:estadoTCC/ns15:esSubEstado">
                <ns15:esSubEstado>
                  <xsl:value-of select="ns9:estadoTCC/ns15:esSubEstado"/>
                </ns15:esSubEstado>
              </xsl:if>
            </ns9:estadoTCC>
            <ns9:subEstadoTCC>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                <ns15:id>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                </ns15:id>
              </xsl:if>
              <xsl:if test="ns9:descripcion">
                <ns15:descripcion>
                  <xsl:value-of select="ns9:descripcion"/>
                </ns15:descripcion>
              </xsl:if>
              <ns15:descripcionCorta>
                <xsl:value-of select="ns9:tipoComision/ns9:descripcionCorta"/>
              </ns15:descripcionCorta>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                <ns15:estatus>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                </ns15:estatus>
              </xsl:if>
              <xsl:if test="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                <ns15:codigoExterno>
                  <xsl:value-of select="ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                </ns15:codigoExterno>
              </xsl:if>
              <xsl:if test="ns9:estadoTCC/ns15:esSubEstado">
                <ns15:esSubEstado>
                  <xsl:value-of select="ns9:estadoTCC/ns15:esSubEstado"/>
                </ns15:esSubEstado>
              </xsl:if>
            </ns9:subEstadoTCC>
            <ns9:fechaRegistro>
              <xsl:value-of select="ns9:tipoComision/ns9:fechaRegistro"/>
            </ns9:fechaRegistro>
            <ns9:estado>
              <xsl:value-of select="ns9:tipoComision/ns9:estado"/>
            </ns9:estado>
            <ns9:comisionEnmendada>
              <xsl:value-of select="ns9:comisionEnmendada"/>
            </ns9:comisionEnmendada>
            <ns9:fechaEnmienda>
              <xsl:value-of select="ns9:fechaEnmienda"/>
            </ns9:fechaEnmienda>
            <xsl:if test="ns9:banSugerida">
              <ns9:banSugerida>
                <xsl:value-of select="ns9:banSugerida"/>
              </ns9:banSugerida>
            </xsl:if>
            <xsl:if test="ns9:numeroCuentaCliente">
              <ns9:numeroCuentaCliente>
                <xsl:value-of select="ns9:numeroCuentaCliente"/>
              </ns9:numeroCuentaCliente>
            </xsl:if>
            <xsl:if test="ns9:observaciones">
              <ns9:observaciones>
                <xsl:value-of select="ns9:observaciones"/>
              </ns9:observaciones>
            </xsl:if>
            <xsl:for-each select="ns9:configAtributo">
              <ns9:configAtributo>
                <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                  <ns15:id>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                  </ns15:id>
                </xsl:if>
                <ns15:columna>
                  <xsl:value-of select="ns15:columna"/>
                </ns15:columna>
                <xsl:if test="ns15:ordenamiento">
                  <ns15:ordenamiento>
                    <xsl:value-of select="ns15:ordenamiento"/>
                  </ns15:ordenamiento>
                </xsl:if>
                <xsl:if test="ns15:soloLectura">
                  <ns15:soloLectura>
                    <xsl:value-of select="ns15:soloLectura"/>
                  </ns15:soloLectura>
                </xsl:if>
                <xsl:if test="ns15:esObligatorio">
                  <ns15:esObligatorio>
                    <xsl:value-of select="ns15:esObligatorio"/>
                  </ns15:esObligatorio>
                </xsl:if>
                <xsl:if test="ns15:etiqueta">
                  <ns15:etiqueta>
                    <xsl:value-of select="ns15:etiqueta"/>
                  </ns15:etiqueta>
                </xsl:if>
                <xsl:for-each select="ns15:valor">
                  <ns15:valor>
                    <xsl:value-of select="."/>
                  </ns15:valor>
                </xsl:for-each>
                <xsl:if test="ns15:tipoValor">
                  <ns15:tipoValor>
                    <xsl:value-of select="ns15:tipoValor"/>
                  </ns15:tipoValor>
                </xsl:if>
                <ns15:catalogo>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:Id">
                    <ns12:Id>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:Id"/>
                    </ns12:Id>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:descripcion">
                    <ns12:Descripcion>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:descripcion"/>
                    </ns12:Descripcion>
                  </xsl:if>
                  <ns12:DescripcionCorta>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:descripcionCorta"/>
                  </ns12:DescripcionCorta>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno">
                    <ns12:codigoExterno>
                      <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Comision/ns9:tipoComision/ns9:idTipoComision/ns12:codigoExterno"/>
                    </ns12:codigoExterno>
                  </xsl:if>
                </ns15:catalogo>
              </ns9:configAtributo>
            </xsl:for-each>
            <xsl:if test="ns9:Accion">
              <ns9:Accion>
                <xsl:value-of select="ns9:Accion"/>
              </ns9:Accion>
            </xsl:if>
          </ns11:Comision>
        </xsl:for-each>
        <xsl:for-each select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Fuente">
          <ns11:Fuente>
            <ns11:idFuente>
              <xsl:value-of select="ns11:idFuente"/>
            </ns11:idFuente>
            <ns11:idLineaCredito>
              <xsl:value-of select="ns11:idLineaCredito"/>
            </ns11:idLineaCredito>
            <ns11:idLineaPasiva>
              <xsl:value-of select="ns11:idLineaPasiva"/>
            </ns11:idLineaPasiva>
            <ns11:codigoLineaPasiva>
              <xsl:value-of select="ns11:codigoLineaPasiva"/>
            </ns11:codigoLineaPasiva>
            <ns11:Descripcion>
              <xsl:value-of select="ns11:Descripcion"/>
            </ns11:Descripcion>
            <ns11:FechaObtenido>
              <xsl:value-of select="ns11:FechaObtenido"/>
            </ns11:FechaObtenido>
            <ns11:MontoAsignado>
              <xsl:value-of select="ns11:MontoAsignado"/>
            </ns11:MontoAsignado>
            <ns11:montoDisponible>
              <xsl:value-of select="ns11:montoDisponible"/>
            </ns11:montoDisponible>
            <xsl:for-each select="ns11:Monto">
              <ns11:Monto>
                <ns6:tipo>
                  <xsl:if test="ns6:tipo/ns12:Id">
                    <ns12:Id>
                      <xsl:value-of select="ns6:tipo/ns12:Id"/>
                    </ns12:Id>
                  </xsl:if>
                  <ns12:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Fuente/ns11:Descripcion"/>
                  </ns12:Descripcion>
                  <xsl:if test="ns6:tipo/ns12:DescripcionCorta">
                    <ns12:DescripcionCorta>
                      <xsl:value-of select="ns6:tipo/ns12:DescripcionCorta"/>
                    </ns12:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns6:tipo/ns12:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="ns6:tipo/ns12:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <xsl:if test="ns6:tipo/ns12:codigoExterno">
                    <ns12:codigoExterno>
                      <xsl:value-of select="ns6:tipo/ns12:codigoExterno"/>
                    </ns12:codigoExterno>
                  </xsl:if>
                </ns6:tipo>
                <xsl:if test="ns6:importe">
                  <ns6:importe>
                    <xsl:value-of select="ns6:importe"/>
                  </ns6:importe>
                </xsl:if>
                <ns6:moneda>
                  <xsl:if test="ns6:tipo/ns12:Id">
                    <ns12:Id>
                      <xsl:value-of select="ns6:tipo/ns12:Id"/>
                    </ns12:Id>
                  </xsl:if>
                  <ns12:Descripcion>
                    <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:Fuente/ns11:Descripcion"/>
                  </ns12:Descripcion>
                  <xsl:if test="ns6:tipo/ns12:DescripcionCorta">
                    <ns12:DescripcionCorta>
                      <xsl:value-of select="ns6:tipo/ns12:DescripcionCorta"/>
                    </ns12:DescripcionCorta>
                  </xsl:if>
                  <xsl:if test="ns6:tipo/ns12:estatus">
                    <ns12:estatus>
                      <xsl:value-of select="ns6:tipo/ns12:estatus"/>
                    </ns12:estatus>
                  </xsl:if>
                  <xsl:if test="ns6:tipo/ns12:codigoExterno">
                    <ns12:codigoExterno>
                      <xsl:value-of select="ns6:tipo/ns12:codigoExterno"/>
                    </ns12:codigoExterno>
                  </xsl:if>
                </ns6:moneda>
              </ns11:Monto>
            </xsl:for-each>
            <ns11:NumeroAsignacion>
              <xsl:value-of select="ns11:NumeroAsignacion"/>
            </ns11:NumeroAsignacion>
            <ns11:Comentario>
              <xsl:value-of select="ns11:Comentario"/>
            </ns11:Comentario>
            <ns11:idContrato>
              <xsl:value-of select="ns11:idContrato"/>
            </ns11:idContrato>
            <ns11:FechaRegistro>
              <xsl:value-of select="ns11:FechaRegistro"/>
            </ns11:FechaRegistro>
            <ns11:Estado>
              <xsl:value-of select="ns11:Estado"/>
            </ns11:Estado>
          </ns11:Fuente>
        </xsl:for-each>
        <xsl:for-each select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:atributos">
          <ns11:atributos>
            <ns6:name>
              <xsl:value-of select="ns6:name"/>
            </ns6:name>
            <ns6:value>
              <xsl:value-of select="ns6:value"/>
            </ns6:value>
          </ns11:atributos>
        </xsl:for-each>
        <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE">
          <ns11:HerramientaCE>
            <ns18:ActividadEconomica>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:Descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:Descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:DescripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:DescripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:ActividadEconomica/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns18:ActividadEconomica>
            <ns18:EjeEstrategico>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:Descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:Descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:DescripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:DescripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:EjeEstrategico/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns18:EjeEstrategico>
            <ns18:AreaFocalizacion>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:Id">
                <ns12:Id>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:Id"/>
                </ns12:Id>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:Descripcion">
                <ns12:Descripcion>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:Descripcion"/>
                </ns12:Descripcion>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:DescripcionCorta">
                <ns12:DescripcionCorta>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:DescripcionCorta"/>
                </ns12:DescripcionCorta>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:estatus">
                <ns12:estatus>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:estatus"/>
                </ns12:estatus>
              </xsl:if>
              <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:codigoExterno">
                <ns12:codigoExterno>
                  <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:LineaCredito/ns11:HerramientaCE/ns18:AreaFocalizacion/ns12:codigoExterno"/>
                </ns12:codigoExterno>
              </xsl:if>
            </ns18:AreaFocalizacion>
          </ns11:HerramientaCE>
        </xsl:if>
      </ns0:LineaCredito>
      <ns11:idLineaCredito/>
      <ns0:Resultado>
        <ns7:result>OK</ns7:result>
        <ns7:message>Consulta Exitosa</ns7:message>
        <xsl:if test="/ns0:ConsultarLineaCreditoBPELResponse/ns0:Resultado/ns7:error">
          <ns7:error>
            <ns16:errorCode>
              <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:Resultado/ns7:error/ns16:errorCode"/>
            </ns16:errorCode>
            <ns16:errorDescription>
              <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:Resultado/ns7:error/ns16:errorDescription"/>
            </ns16:errorDescription>
            <ns16:errorType>
              <xsl:value-of select="/ns0:ConsultarLineaCreditoBPELResponse/ns0:Resultado/ns7:error/ns16:errorType"/>
            </ns16:errorType>
          </ns7:error>
        </xsl:if>
      </ns0:Resultado>
    </ns0:ConsultarLineaCreditoBPELResponse>
  </xsl:template>
</xsl:stylesheet>
