<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.banesco.com/appopt/UtilityAppSvc/OnlineBankTrnAdv_V1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://xmlns.banesco.com/eopt/OnlineBankTrnAdv_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoCom="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/Utility/OnlineBankTrnAdv/OnlineBankTrnAdv_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="OnlineBankTrnAdvRq" namespace="http://xmlns.banesco.com/appopt/UtilityAppSvc/OnlineBankTrnAdv_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Utility/OnlineBankTrnAdv/OnlineBankTrnAdv_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="OnlineBankTrnAdvRq" namespace="http://xmlns.banesco.com/eopt/OnlineBankTrnAdv_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI MAY 11 15:02:13 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:OnlineBankTrnAdvRq>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:BeneficiaryName">
            <tns:BeneficiaryName>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:BeneficiaryName"/>
            </tns:BeneficiaryName>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:BlockReason">
            <tns:BlockReason>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:BlockReason"/>
            </tns:BlockReason>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:ChkBookQty">
            <tns:ChkBookQty>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:ChkBookQty"/>
            </tns:ChkBookQty>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:ChkBookType">
            <tns:ChkBookType>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:ChkBookType"/>
            </tns:ChkBookType>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Commission">
            <tns:Commission>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Commission"/>
            </tns:Commission>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:ConfNumber">
            <tns:ConfNumber>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:ConfNumber"/>
            </tns:ConfNumber>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CountryVisit">
            <tns:CountryVisit>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CountryVisit/appoptcommon:CountryCode">
                  <eoCom:CountryCode>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:CountryVisit/appoptcommon:CountryCode"/>
                  </eoCom:CountryCode>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CountryVisit/appoptcommon:CountryName">
                  <eoCom:CountryName>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:CountryVisit/appoptcommon:CountryName"/>
                  </eoCom:CountryName>
               </xsl:if>
            </tns:CountryVisit>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CreditAcctId">
            <tns:CreditAcctId>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:CreditAcctId"/>
            </tns:CreditAcctId>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CreditAmt">
            <tns:CreditAmt>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CreditAmt/appoptcommon:Amt">
                  <eoCom:Amt>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:CreditAmt/appoptcommon:Amt"/>
                  </eoCom:Amt>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CreditAmt/appoptcommon:CurCode">
                  <eoCom:CurCode>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:CreditAmt/appoptcommon:CurCode"/>
                  </eoCom:CurCode>
               </xsl:if>
            </tns:CreditAmt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:CustomerName">
            <tns:CustomerName>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:CustomerName"/>
            </tns:CustomerName>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:DebitAcctId">
            <tns:DebitAcctId>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:DebitAcctId"/>
            </tns:DebitAcctId>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:DebitAmt">
            <tns:DebitAmt>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:DebitAmt/appoptcommon:Amt">
                  <eoCom:Amt>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:DebitAmt/appoptcommon:Amt"/>
                  </eoCom:Amt>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:DebitAmt/appoptcommon:CurCode">
                  <eoCom:CurCode>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:DebitAmt/appoptcommon:CurCode"/>
                  </eoCom:CurCode>
               </xsl:if>
            </tns:DebitAmt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:EffDt">
            <tns:EffDt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:EffDt"/>
            </tns:EffDt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:EffHr">
            <tns:EffHr>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:EffHr"/>
            </tns:EffHr>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Element1">
            <tns:Element1>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Element1"/>
            </tns:Element1>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Element2">
            <tns:Element2>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Element2"/>
            </tns:Element2>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Element3">
            <tns:Element3>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Element3"/>
            </tns:Element3>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Element4">
            <tns:Element4>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Element4"/>
            </tns:Element4>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Email">
            <tns:Email>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Email"/>
            </tns:Email>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Employee">
            <tns:Employee>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Employee"/>
            </tns:Employee>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:EventNum">
            <tns:EventNum>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:EventNum"/>
            </tns:EventNum>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:ExitDt">
            <tns:ExitDt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:ExitDt"/>
            </tns:ExitDt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:FreqPmt">
            <tns:FreqPmt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:FreqPmt"/>
            </tns:FreqPmt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:IdApp">
            <tns:IdApp>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:IdApp"/>
            </tns:IdApp>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:IdRef">
            <tns:IdRef>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:IdRef"/>
            </tns:IdRef>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:IdSendDt">
            <tns:IdSendDt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:IdSendDt"/>
            </tns:IdSendDt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:IngressDt">
            <tns:IngressDt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:IngressDt"/>
            </tns:IngressDt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:IntermediaryBank">
            <tns:IntermediaryBank>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:IntermediaryBank"/>
            </tns:IntermediaryBank>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:NotifyEmail">
            <tns:NotifyEmail>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:NotifyEmail"/>
            </tns:NotifyEmail>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:NotifyName">
            <tns:NotifyName>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:NotifyName"/>
            </tns:NotifyName>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:NotifyPhone">
            <tns:NotifyPhone>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:NotifyPhone"/>
            </tns:NotifyPhone>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:NumPmt">
            <tns:NumPmt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:NumPmt"/>
            </tns:NumPmt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:OrigDt">
            <tns:OrigDt>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:OrigDt"/>
            </tns:OrigDt>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:OrigHr">
            <tns:OrigHr>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:OrigHr"/>
            </tns:OrigHr>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey">
            <tns:PartyKey>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:IssuedIdentType">
                  <eoPar:IssuedIdentType>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:IssuedIdentType"/>
                  </eoPar:IssuedIdentType>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:IssuedIdentValue">
                  <eoPar:IssuedIdentValue>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:IssuedIdentValue"/>
                  </eoPar:IssuedIdentValue>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:PartyId">
                  <eoPar:PartyId>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:PartyId"/>
                  </eoPar:PartyId>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:PartyType">
                  <eoPar:PartyType>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:PartyKey/ns0:PartyType"/>
                  </eoPar:PartyType>
               </xsl:if>
            </tns:PartyKey>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo">
            <tns:SessionInfo>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:AccesDt">
                  <eoCom:AccesDt>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:AccesDt"/>
                  </eoCom:AccesDt>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:AccesHr">
                  <eoCom:AccesHr>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:AccesHr"/>
                  </eoCom:AccesHr>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:ActionType">
                  <eoCom:ActionType>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:ActionType"/>
                  </eoCom:ActionType>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Browser">
                  <eoCom:Browser>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Browser"/>
                  </eoCom:Browser>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:BrowserVersion">
                  <eoCom:BrowserVersion>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:BrowserVersion"/>
                  </eoCom:BrowserVersion>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:City">
                  <eoCom:City>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:City"/>
                  </eoCom:City>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Country">
                  <eoCom:Country>
                     <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Country/appoptcommon:CountryCode">
                        <eoCom:CountryCode>
                           <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Country/appoptcommon:CountryCode"/>
                        </eoCom:CountryCode>
                     </xsl:if>
                     <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Country/appoptcommon:CountryName">
                        <eoCom:CountryName>
                           <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Country/appoptcommon:CountryName"/>
                        </eoCom:CountryName>
                     </xsl:if>
                  </eoCom:Country>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:DNADevice">
                  <eoCom:DNADevice>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:DNADevice"/>
                  </eoCom:DNADevice>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:FailedAttempts">
                  <eoCom:FailedAttempts>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:FailedAttempts"/>
                  </eoCom:FailedAttempts>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:isNotified">
                  <eoCom:isNotified>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:isNotified"/>
                  </eoCom:isNotified>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:ISPCode">
                  <eoCom:ISPCode>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:ISPCode"/>
                  </eoCom:ISPCode>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Latitude">
                  <eoCom:Latitude>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Latitude"/>
                  </eoCom:Latitude>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Longitude">
                  <eoCom:Longitude>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Longitude"/>
                  </eoCom:Longitude>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NetworkTrnData">
                  <eoCom:NetworkTrnData>
                     <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NetworkTrnData/appoptcommon:HostName">
                        <eoCom:HostName>
                           <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NetworkTrnData/appoptcommon:HostName"/>
                        </eoCom:HostName>
                     </xsl:if>
                     <eoCom:IpAddress>
                        <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NetworkTrnData/appoptcommon:IpAddress"/>
                     </eoCom:IpAddress>
                     <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NetworkTrnData/appoptcommon:MacAddress">
                        <eoCom:MacAddress>
                           <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NetworkTrnData/appoptcommon:MacAddress"/>
                        </eoCom:MacAddress>
                     </xsl:if>
                  </eoCom:NetworkTrnData>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NotificationDt">
                  <eoCom:NotificationDt>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NotificationDt"/>
                  </eoCom:NotificationDt>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NotificationHr">
                  <eoCom:NotificationHr>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NotificationHr"/>
                  </eoCom:NotificationHr>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NotificationMethod">
                  <eoCom:NotificationMethod>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:NotificationMethod"/>
                  </eoCom:NotificationMethod>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Prefix">
                  <eoCom:Prefix>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Prefix"/>
                  </eoCom:Prefix>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:PrivateIp">
                  <eoCom:PrivateIp>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:PrivateIp"/>
                  </eoCom:PrivateIp>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Region">
                  <eoCom:Region>
                     <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Region/appoptcommon:Cod">
                        <eoCom:Cod>
                           <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Region/appoptcommon:Cod"/>
                        </eoCom:Cod>
                     </xsl:if>
                     <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Region/appoptcommon:Desc">
                        <eoCom:Desc>
                           <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:Region/appoptcommon:Desc"/>
                        </eoCom:Desc>
                     </xsl:if>
                  </eoCom:Region>
               </xsl:if>
               <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:UserStatus">
                  <eoCom:UserStatus>
                     <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:SessionInfo/appoptcommon:UserStatus"/>
                  </eoCom:UserStatus>
               </xsl:if>
            </tns:SessionInfo>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:TargetBank">
            <tns:TargetBank>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:TargetBank"/>
            </tns:TargetBank>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:Taxes">
            <tns:Taxes>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:Taxes"/>
            </tns:Taxes>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:TrnCode">
            <tns:TrnCode>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:TrnCode"/>
            </tns:TrnCode>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:TrnDesc">
            <tns:TrnDesc>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:TrnDesc"/>
            </tns:TrnDesc>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:TrnRef">
            <tns:TrnRef>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:TrnRef"/>
            </tns:TrnRef>
         </xsl:if>
         <xsl:if test="/ns0:OnlineBankTrnAdvRq/ns0:TrnStatus">
            <tns:TrnStatus>
               <xsl:value-of select="/ns0:OnlineBankTrnAdvRq/ns0:TrnStatus"/>
            </tns:TrnStatus>
         </xsl:if>
      </tns:OnlineBankTrnAdvRq>
   </xsl:template>
</xsl:stylesheet>
