package org.bcie.fenix.common.model.vo.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 01 10:59:30 CST 2017
// ---------------------------------------------------------------------
public interface SaldoPreinversionDesembolsoVO extends ViewObject {
    String actualizarRegistro(Row fila, BigDecimal montoPreinversion, BigDecimal tasainteres, BigDecimal montoTotal);

    String commit();

    String crearNuevoRegistro(Long idOperacion, Long idDesembolso, BigDecimal montoPreinversion, BigDecimal tasainteres,
                              BigDecimal montoTotal);


    String actualizarABanEstatusCero(Row fila);

    String recuperarRegistro(Long idOperacion, Long idDesembolso, BigDecimal montoPreinversion, BigDecimal tasainteres,
                             BigDecimal montoTotal, String operacion);
}

