<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeSizeTranslation" name="caseThreeSizeTranslation-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="caseThreeSizeTranslation.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeSizeTranslation"/>
    <wsdl:binding name="caseThreeSizeTranslation_ptt-binding" type="cas:caseThreeSizeTranslation_ptt" xmlns:cas="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeSizeTranslation">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="caseThreeSizeTranslationSelect">
            <soap:operation soapAction="caseThreeSizeTranslationSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>