<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project17/CargarDocumentoFenix" name="CargarDocumentoFenix_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CargarDocumentoFenix.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project17/CargarDocumentoFenix"/>
    <wsdl:binding name="CargarDocumentoFenix_ptt-binding" type="car:CargarDocumentoFenix_ptt" xmlns:car="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project17/CargarDocumentoFenix">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CargarDocumentoFenix">
            <soap:operation soapAction="CargarDocumentoFenix"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>