<wsdl:definitions name="ConsultarObservacionCondicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarObservacionCondicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarObservacionCondicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarObservacionCondicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarObservacionCondicion_plt">
    <plt:role name="ConsultarObservacionCondicion_role">
      <plt:portType name="tns:ConsultarObservacionCondicion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarObservacionCondicion" schemaLocation="../XSD/ConsultarObservacionCondicion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarObservacionCondicionSelect_inputParameters">
        <wsdl:part name="ConsultarObservacionCondicionSelect_inputParameters" element="top:ConsultarObservacionCondicionSelect_idObservacionInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ObservacionCondicionCollection_msg">
        <wsdl:part name="ObservacionCondicionCollection" element="top:ObservacionCondicionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarObservacionCondicion_ptt">
        <wsdl:operation name="ConsultarObservacionCondicionSelect">
            <wsdl:input message="tns:ConsultarObservacionCondicionSelect_inputParameters"/>
            <wsdl:output message="tns:ObservacionCondicionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>