package org.bcie.fenix.common.model.vo;

import oracle.jbo.server.ViewObjectImpl;

import org.bcie.fenix.common.model.vo.common.TcaModalidadFinanciamientoVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 28 11:43:34 CDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TcaModalidadFinanciamientoVOImpl extends ViewObjectImpl implements TcaModalidadFinanciamientoVO {
    /**
     * This is the default constructor (do not remove).
     */
    public TcaModalidadFinanciamientoVOImpl() {
    }

    /**
     * Returns the bind variable value for varIdPrograma.
     * @return bind variable value for varIdPrograma
     */
    public String getvarIdPrograma() {
        return (String) getNamedWhereClauseParam("varIdPrograma");
    }

    /**
     * Sets <code>value</code> for bind variable varIdPrograma.
     * @param value value to bind as varIdPrograma
     */
    public void setvarIdPrograma(String value) {
        setNamedWhereClauseParam("varIdPrograma", value);
    }
}

