package org.bcie.fenix.common.model.vo;

import java.math.BigDecimal;

import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.NameValuePairs;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewObjectImpl;

import org.bcie.atributobo.Accion;
import org.bcie.atributobo.EntidadMinima;
import org.bcie.atributobo.EstadoTCC;
import org.bcie.catalogobo.Catalogo;
import org.bcie.fenix.common.model.FenixModelConstants;
import static org.bcie.fenix.common.model.FenixModelConstants.BANESTATUS_FALSE;
import org.bcie.fenix.common.model.am.FenixAMImpl;
import org.bcie.fenix.common.model.utils.IWsdlLocation;
import org.bcie.fenix.common.model.utils.ModelUtils;
import org.bcie.fenix.common.model.vo.common.TccTerminoVO;
import org.bcie.matriztccbo.ListaTCC;
import org.bcie.matriztccbo.TCC;
import org.bcie.matriztccbo.Tipo;
import org.bcie.matriztccmo.ActualizarEstadoTCCRequestType;
import org.bcie.matriztccmo.ActualizarEstadoTCCResponseType;
import org.bcie.matriztccmo.ActualizarTCCRequestType;
import org.bcie.matriztccservice.MatrizTCC12BndQSService;
import org.bcie.matriztccservice.MatrizTCCPT;
import org.bcie.terminobo.CatalogoTermino;
import org.bcie.terminobo.Termino;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 04 11:51:15 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TccTerminoVOImpl extends ViewObjectImpl implements TccTerminoVO {
    
    /**
     * Log de la aplicacion
     */
    private static ADFLogger logger = ADFLogger.createADFLogger(TccTerminoVOImpl.class);
    
    private static final Integer TCA_TERMINO_FIRMA_CONTRATO = 30;
    
    /**
     * Define nombre de view criteria para realizar busqueda por Id de Termino
     */
    public static final String BUSCAR_POR_ID_VC = "TerminoByIdVC";
    
    /**
     * This is the default constructor (do not remove).
     */
    public TccTerminoVOImpl() {
    }

    /**
     * Returns the variable value for pId.
     * @return variable value for pId
     */
    public Number getpId() {
        return (Number) ensureVariableManager().getVariableValue("pId");
    }

    /**
     * Sets <code>value</code> for variable pId.
     * @param value value to bind as pId
     */
    public void setpId(Number value) {
        ensureVariableManager().setVariableValue("pId", value);
    }
    
    /**
     * Ejecuta la busqueda de Termino por Id aplicando
     * @param id contiene clave primaria del registro
     */
    public void buscarTerminoPorId(Number id){
        logger.entering(TccTerminoVOImpl.class.getName(), "buscarTerminoPorId", id);
        
        //Refresca VO
        executeQuery();
        Row row = null;
        if(id != null) {
            //Se sustituye busqueda por id a busqueda por criterio
            row = buscarTerminoPorIdVC(id);
            if(row != null){
                logger.warning("Asigna current row");
                
                setCurrentRow(row);
            }
        }
        
        logger.exiting(TccTerminoVOImpl.class.getName(), "buscarTerminoPorId");
    }
    
    private Row buscarTerminoPorIdVC(Number idTermino){
        logger.warning("Entra en buscarTerminoPorIdVC");
        Row row = null;
        ViewCriteria vc = null;
        try{
            vc = getViewCriteria(BUSCAR_POR_ID_VC);
            vc.ensureVariableManager().setVariableValue("pId", idTermino);
            applyViewCriteria(vc);
            executeQuery();
            
            if(this.getEstimatedRowCount() > 0){
                logger.warning("Se obtiene row de termino por criterio de busqueda");
                setCurrentRow(first());
                row = first();
            }else{
                logger.warning("No se encontro row por criterio de busqueda.");
            }
            
        }catch(Exception e){
            logger.warning("Error en buscarTerminoPorIdVC.", e);
        }finally{
            logger.warning("Se remueve criterio");
            vc.getViewCriteriaManager().removeApplyViewCriteriaName(BUSCAR_POR_ID_VC);
        }
        return row;
    }
    
    /**
     * Asigna a configuracion del catalogo tipo termino al registro actual de termino
     */
    public void asignarConfigTipoTermino(){
        
        TccTerminoVORowImpl row = null;
        row = (TccTerminoVORowImpl) getCurrentRow();
        if(row != null){
            
            FenixAMImpl fenixAM = null;
            fenixAM = (FenixAMImpl) getApplicationModule();
            
            if(fenixAM != null){
                
                Boolean esEditableForm = null;
                Boolean esDispensaEnm = null;
                
                if(fenixAM.getTccTcaTerminoVO() != null){
                    
                    oracle.jbo.domain.Number id = null;
                    try{
                        id = new oracle.jbo.domain.Number(row.getIdTcaTermino());    
                    }catch(Exception e){
                        logger.severe("Error al convertir el Id de Tca Termino a Number");
                    }
                    
                    if(id != null){
                        fenixAM.getTccTcaTerminoVO().buscarTcaTerminoPorId(id);    
                        if(fenixAM.getTccTcaTerminoVO().getCurrentRow() != null){
                            
                            TccTcaTerminoVORowImpl tcaRow = null;
                            tcaRow = (TccTcaTerminoVORowImpl) fenixAM.getTccTcaTerminoVO().getCurrentRow();
                            
                            if(tcaRow != null){
                                
                                if(tcaRow.getEsEditableEnFormalizacion() != null){
                                    if(tcaRow.getEsEditableEnFormalizacion().equals(new Integer(0))){
                                        logger.warning("El valor bandera de campo Es Editable en Formalizacion es negativo = 0");
                                        esEditableForm = false;
                                    }else{
                                        if(tcaRow.getEsEditableEnFormalizacion().equals(new Integer(1))){
                                            logger.warning("El valor bandera de campo Es Editable en Formalizacion es positivo = 1");
                                            esEditableForm = true;
                                        }else{
                                            logger.warning("Valor de campo Es Editable en Formalizacion no es valido");
                                        }
                                    }
                                }else{
                                    logger.warning("El valor del campo Es Editable en Formalizacion es NULL");
                                }
                                
                                
                                if(tcaRow.getSePuedeDispensar() != null){
                                    if(tcaRow.getSePuedeDispensar().equals(new Integer(0))){
                                        esDispensaEnm = false;
                                    }else{
                                        if(tcaRow.getSePuedeDispensar().equals(new Integer(1))){
                                            esDispensaEnm = true;
                                        }else{
                                            logger.warning("Valor de campo Se Puede Dispensar no es valido");
                                        }
                                    }
                                }else{
                                    logger.warning("El valor del campo Se Puede Dispensar en Enmiendas es NULL");
                                }
                            }
                        }else{
                            logger.warning("No se encontro registro de catalogo Termino");
                        }
                    }
                }
                
                if(esEditableForm != null){
                    logger.warning("Asigna configuracion de campo Es Editable en Formalizacion: " + esEditableForm);
                    row.setEditableFormalizacion(esEditableForm);    
                }
                if(esDispensaEnm != null){
                    logger.warning("Asigna configuracion de campo Es Dispensa en Enmienda: " + esDispensaEnm);
                    row.setDispensaEnmienda(esDispensaEnm);
                }
            }else{
                logger.warning("No se pudo obtener instancia de Application Module");    
            }
        }else{
            logger.warning("No hay registro actual que asignar configuracion de catalogo tcc");
        }
    }
    
    /**
     * Consume el WS para actualizar el estado TCC de Terminos
     * @return devuelve valor booleano, true indica que el proceso fue exitoso o false en caso contrario
     */
    public Boolean actualizarEstadoTermino(){
        logger.entering(TccTerminoVOImpl.class.getName(), 
                        "actualizarEstadoTermino");
        Boolean esError = Boolean.FALSE;
        ActualizarEstadoTCCRequestType request = null;
        ListaTCC listaTcc = null;
        List<TCC> tcc = null;
        String mensajeError = null;
        
        RowSetIterator iter = createRowSetIterator(null);
        if(iter != null){
            TccTerminoVORowImpl terminoRow = new TccTerminoVORowImpl();
            TCC element = null;
            
            iter.reset();
            logger.warning("Iniciando iteracion para seteo de atributos de elementos de TCC");
            while(iter.hasNext()){
                terminoRow = (TccTerminoVORowImpl) iter.next();
                element = new TCC();
                //Mapeo de atributos de VO con Objeto de WS
                element.setId(terminoRow.getId().longValue());
                element.setEstado(terminoRow.getIdTcaEstadoTcc());
                element.setSubEstado(terminoRow.getIdTcaSubEstadoTcc());
                element.setTipo(Tipo.TERMINO);
                
                if(tcc == null){
                    tcc = new ArrayList<TCC>();
                }
                tcc.add(element);
            }
            logger.warning("Finaliza iteracion para seteo de atributos de elementos de TCC");
            iter.closeRowSetIterator();
        }
        
        if(tcc != null){
            logger.warning("Añadiendo elementos de TCC a lista");
            listaTcc = new ListaTCC();
            listaTcc.getTCC().addAll(tcc);
        }
        
        if(listaTcc != null &&
           listaTcc.getTCC() != null &&
           listaTcc.getTCC().size() > 0){
            try{
                logger.warning("Invocacion a WS ActualizarEstadoTCC");
                //Invocacion a WS
                FenixAMImpl fenixAM = (FenixAMImpl)this.getRootApplicationModule();
                String wsdl = fenixAM.getWsdl(IWsdlLocation.MATRIZ);
                
               MatrizTCC12BndQSService matrizTCC12BndQSService = IWsdlLocation.Service.getInstance(MatrizTCC12BndQSService.class, wsdl);
               MatrizTCCPT matrizTccPT = matrizTCC12BndQSService.getMatrizTCC12BndQSPort();
               
               request = new ActualizarEstadoTCCRequestType();
               request.setListaTCC(listaTcc);
               
               Date horaInicio = ModelUtils.logStartWS(logger, request, "MatrizTCCService");
               ActualizarEstadoTCCResponseType response = null;
               //response = matrizTccPT.actualizarEstadoTCC(request);
               ModelUtils.logEndWS(logger, response, "Response", horaInicio);
               
               if(response.getResultado() != null &&
                  response.getResultado().getResult() != null &&
                  response.getResultado().getResult().value() != null &&
                  response.getResultado().getResult().value().equals("ERROR")){
                   esError = Boolean.TRUE;
                   mensajeError = response.getResultado().getMessage();
                   mensajeError = mensajeError.concat(". ");
                   mensajeError = mensajeError.concat(response.getResultado().getError().getErrorDescription());
                   logger.warning("Error en WS: " + mensajeError);
               }
            } catch(Exception e){
                logger.severe("Error al actualizar estado de terminos", e);
                esError = Boolean.TRUE;
            }
        }
        logger.exiting(TccTerminoVOImpl.class.getName(), 
                        "actualizarEstadoTermino");
        return esError;
    }
    
    public Long crearTerminoEnmendado(Number idTcc, Integer idTcaEstadoTcc, Integer idTcaSubEstadoTcc) {
        logger.warning("Inside crearTerminoEnmendado");
        logger.warning("idTcc :"+idTcc);
        logger.warning("idTcaEstadoTcc :"+idTcaEstadoTcc);
        logger.warning("idTcaSubEstadoTcc :"+idTcaSubEstadoTcc);
        // Creamos un nuevo Termino Enmendado en base al idTerminoEnmendado enviado (debe ser un clon de él)
        oracle.jbo.domain.Number idTermino = null;
        NameValuePairs nvpTermino = null;
        SequenceImpl seqTermino = null;
        Row rowPadre = null;
        Row rowEnmendado = null;
        
        // Obtenemos row padre
        rowPadre = buscarTerminoPorIdVC(idTcc);
        
        // Asignamos todos los atributos del row padre al row enmendado 
        // (excepto BanEstatus, FechaRegistro, Id, IdTcaEstadoTcc, IdTcaSubEstadoTcc y IdTerminoEnmendado)
        if(rowPadre != null) {
            
            seqTermino = new SequenceImpl("TERMINO_SEQ", getDBTransaction());
            idTermino = seqTermino.getSequenceNumber();
            nvpTermino = new NameValuePairs();
            
            for(String nombreAtributo : rowPadre.getAttributeNames()) {
                // Clonamos row
                nvpTermino.setAttribute(nombreAtributo, rowPadre.getAttribute(nombreAtributo));
            }
            
            // Sobreescribimos atributos diferentes, específicos al enmendado
            nvpTermino.setAttribute("BanEstatus", BANESTATUS_FALSE);
            nvpTermino.setAttribute("FechaRegistro", new java.sql.Timestamp(System.currentTimeMillis()));
            nvpTermino.setAttribute("Id", idTermino);
            
            if(idTcaEstadoTcc != null) // Si el estado es null, le dejamos el mismo que el del padre
                nvpTermino.setAttribute("IdTcaEstadoTcc", idTcaEstadoTcc);
            
            nvpTermino.setAttribute("IdTcaSubEstadoTcc", idTcaSubEstadoTcc);
            nvpTermino.setAttribute("IdTerminoEnmendado", idTcc);
            
            rowEnmendado = this.createAndInitRow(nvpTermino); 
            
            // Se replica la informacion de contrapartes obtenida del row padre
            FenixAMImpl am = (FenixAMImpl) getApplicationModule();
            
            if (null != am) {
                Long idTerminoPadre = (Long) rowPadre.getAttribute(TccTerminoVORowImpl.ID);
                Long idTerminoEnmendado = idTermino.longValue();
                TreContrapartesTerminoVOImpl treContrapartesTerminoVO = am.getTreContrapartesTerminoVO();
                
                // Se replican contrapartes
                treContrapartesTerminoVO.replicarContrapartesPadre(idTerminoPadre, idTerminoEnmendado);
            }
            
            getDBTransaction().commit();        
            
            // Re-ejecutamos el query debido a que se creó un nuevo registro
            this.executeQuery();
        }
        
        // Regresamos el id del Término Enmendado
        if(rowEnmendado != null)
            return Long.valueOf(rowEnmendado.getAttribute("Id").toString());
        else
            return null;
    }
    
    public Long crearTerminoEnmendado(Number idTcc, Integer idTcaEstadoTcc, Integer idTcaSubEstadoTcc, 
                                            String nombreUsuario, String loginUsuario) {
        logger.warning("Inside crearTerminoEnmendado");
        logger.warning("idTcc :"+idTcc);
        logger.warning("idTcaEstadoTcc :"+idTcaEstadoTcc);
        logger.warning("idTcaSubEstadoTcc :"+idTcaSubEstadoTcc);
        logger.warning("nombreUsuario :"+nombreUsuario);
        logger.warning("loginUsuario :"+loginUsuario);
        // Creamos un nuevo Termino Enmendado en base al idTerminoEnmendado enviado (debe ser un clon de él)
        oracle.jbo.domain.Number idTermino = null;
        NameValuePairs nvpTermino = null;
        SequenceImpl seqTermino = null;
        Row rowPadre = null;
        Row rowEnmendado = null;
        
        // Obtenemos row padre
        rowPadre = buscarTerminoPorIdVC(idTcc);
        // Asignamos todos los atributos del row padre al row enmendado 
        // (excepto BanEstatus, FechaRegistro, Id, IdTcaEstadoTcc, IdTcaSubEstadoTcc y IdTerminoEnmendado)
        if(rowPadre != null) {
            
            seqTermino = new SequenceImpl("TERMINO_SEQ", getDBTransaction());
            idTermino = seqTermino.getSequenceNumber();
            nvpTermino = new NameValuePairs();
            
            for(String nombreAtributo : rowPadre.getAttributeNames()) {
                // Clonamos row
                nvpTermino.setAttribute(nombreAtributo, rowPadre.getAttribute(nombreAtributo));
            }
            
            // Sobreescribimos atributos diferentes, específicos al enmendado
            nvpTermino.setAttribute("BanEstatus", BANESTATUS_FALSE);
            nvpTermino.setAttribute("FechaRegistro", new java.sql.Timestamp(System.currentTimeMillis()));
            nvpTermino.setAttribute("Id", idTermino);
            
            if(idTcaEstadoTcc != null) // Si el estado es null, le dejamos el mismo que el del padre
                nvpTermino.setAttribute("IdTcaEstadoTcc", idTcaEstadoTcc);
            
            nvpTermino.setAttribute("IdTcaSubEstadoTcc", idTcaSubEstadoTcc);
            nvpTermino.setAttribute("IdTerminoEnmendado", idTcc);
            nvpTermino.setAttribute("IdTerminoEnmendado", idTcc);
            nvpTermino.setAttribute("LoginUsuario", loginUsuario);
            nvpTermino.setAttribute("NombreUsuario", nombreUsuario);
            
            rowEnmendado = this.createAndInitRow(nvpTermino);        
            getDBTransaction().commit();        
            
            // Re-ejecutamos el query debido a que se creó un nuevo registro
            this.executeQuery();
        }
        
        // Regresamos el id del Término Enmendado
        if(rowEnmendado != null)
            return Long.valueOf(rowEnmendado.getAttribute("Id").toString());
        else
            return null;
    }
    
    /**
     * sirve para probar updateTermino(Long id, Map atributos)
     * @param idTermino
     */
    public void updateTerminoTest(Long idTermino){
        logger.warning("Dentro updateTerminoTest");
        Map<String, Object> atributos = new HashMap<String, Object>();
        BigDecimal monto = new BigDecimal("7777777");
        atributos.put("Monto", monto);
        updateTermino(idTermino,atributos);
        logger.warning("Fuera updateTerminoTest");
    }
    
    public void updateTermino(Long id, Map atributos) {
        logger.warning("Entra updateTermino");
        logger.warning("id"+id);
        Row row = null;
        oracle.jbo.domain.Number idNumber = new oracle.jbo.domain.Number(id);
        row = buscarTerminoPorIdVC(idNumber);
        
        if (row != null && atributos != null && !atributos.isEmpty()) {
            Iterator iter = atributos.entrySet().iterator();
            while(iter.hasNext()){
                @SuppressWarnings("unchecked")
                Map.Entry<String, Object> atributo = (Map.Entry<String, Object>) iter.next();
                if(atributo != null){
                    logger.warning("key atributo :"+atributo.getKey());
                    logger.warning("Value atributo :"+atributo.getValue());
                    row.setAttribute(atributo.getKey(), atributo.getValue());
                }
            }
            getDBTransaction().commit();
        }else{
            if(null == row){
                logger.warning("row es nulo");
            }
            if(null == atributos){
                logger.warning("atributos es nulo");
            }
        }
        logger.warning("Fuera updateTermino");
    }
    
    public void updateTerminoLogin(Long id, Map atributos, String loginUsuarioUltimo, String nombreUsuarioUltimo) {
        logger.warning("Entra updateTerminoLogin");
        logger.warning("id"+id);
        Row row = null;
        oracle.jbo.domain.Number idNumber = new oracle.jbo.domain.Number(id);
        row = buscarTerminoPorIdVC(idNumber);
        
        if (row != null && atributos != null && !atributos.isEmpty()) {
            Iterator iter = atributos.entrySet().iterator();
            while(iter.hasNext()){
                @SuppressWarnings("unchecked")
                Map.Entry<String, Object> atributo = (Map.Entry<String, Object>) iter.next();
                if(atributo != null){
                    logger.warning("key atributo :"+atributo.getKey());
                    logger.warning("Value atributo :"+atributo.getValue());
                    row.setAttribute(atributo.getKey(), atributo.getValue());
                    row.setAttribute("NombreUsuarioUltimoCambio", nombreUsuarioUltimo);
                    row.setAttribute("LoginUsuarioUltimoCambio", loginUsuarioUltimo);
                    row.setAttribute("FechaUltimoCambio", new java.sql.Timestamp(System.currentTimeMillis()));
                }
            }
            getDBTransaction().commit();
        }else{
            if(null == row){
                logger.warning("row es nulo");
            }
            if(null == atributos){
                logger.warning("atributos es nulo");
            }
        }
        logger.warning("Fuera updateTermino");
    }
    
    public Long existeTerminoByIdOperacionAndIdTcaTermino(Long idOperacion, Integer idTcaTermino) {
        Long termino = null;
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(idTcaTermino);
        try{
            ViewCriteria vc = getViewCriteria(CRITERIA_BY_ID_TCA_TERMINO_AND_ID_OPERACION);
            applyViewCriteria(vc);
            executeQuery();
            hasNext();
            Row row = next();
            
            if (row != null) {
                termino = (Long) row.getAttribute(TccTerminoVORowImpl.ID);
            }
        }catch(Exception e){
            logger.severe("Error en la ejecucion del view criteria: " + CRITERIA_BY_ID_TCA_TERMINO_AND_ID_OPERACION);
            termino = null;
        }
        return termino;
    }
    
    public Long crearTermino(Long idOperacion, String nombreTermino, Integer idTcaTermino, Integer idTcaEstadoTcc, 
                             Integer idTcaSubEstadoTcc, Integer banEstatus) {
        logger.log(ADFLogger.TRACE, "Inside crearTermino.");
        return crearTerminoCompleto(idOperacion, nombreTermino, idTcaTermino, idTcaEstadoTcc, idTcaSubEstadoTcc, banEstatus, null);
    }
    
    public Long crearTerminoCompleto(Long idOperacion, String nombreTermino, Integer idTcaTermino, Integer idTcaEstadoTcc, 
                             Integer idTcaSubEstadoTcc, Integer banEstatus, Map atributos) {
        logger.warning("Dentro crearTerminoCompleto");
        logger.warning("idOperacion :"+idOperacion);
        logger.warning("nombreTermino :"+nombreTermino);
        logger.warning("idTcaTermino :"+idTcaTermino);
        logger.warning("idTcaEstadoTcc :"+idTcaEstadoTcc);
        logger.warning("idTcaSubEstadoTcc :"+idTcaSubEstadoTcc);
        logger.warning("banEstatus :"+banEstatus);
        
        oracle.jbo.domain.Number idTermino = null;
        NameValuePairs nvpTermino = null;
        SequenceImpl seqTermino = null;
        Row rowNuevo = null;
                
        // Asignación de variables      
        seqTermino = new SequenceImpl("TERMINO_SEQ", getDBTransaction());
        idTermino = seqTermino.getSequenceNumber();
        nvpTermino = new NameValuePairs();
                
        // Creamos un nuevo Termino en base a los parámetros enviados
        nvpTermino.setAttribute("BanEstatus", banEstatus);
        nvpTermino.setAttribute("FechaRegistro", new java.sql.Timestamp(System.currentTimeMillis()));
        nvpTermino.setAttribute("Id", idTermino);
        nvpTermino.setAttribute("IdOperacion", idOperacion);
        nvpTermino.setAttribute("IdTcaEstadoTcc", idTcaEstadoTcc);
        nvpTermino.setAttribute("IdTcaSubEstadoTcc", idTcaSubEstadoTcc);
        nvpTermino.setAttribute("IdTcaTermino", idTcaTermino);
        nvpTermino.setAttribute("Nombre", nombreTermino);
         
        if(atributos != null && !atributos.isEmpty()) {
            
            Iterator iter = atributos.entrySet().iterator();
            while(iter.hasNext()){
                @SuppressWarnings("unchecked")
                Map.Entry<String, Object> atributo = (Map.Entry<String, Object>) iter.next();
                if(atributo != null){
                    nvpTermino.setAttribute(atributo.getKey(), atributo.getValue());
                }
            }
        }

        rowNuevo = this.createAndInitRow(nvpTermino);
        
        try{
            getDBTransaction().commit();
        }catch(Exception e){
            logger.severe("Error en commit :",e);
        }
        
        // Re-ejecutamos el query debido a que se creó un nuevo registro
        this.executeQuery();
        logger.warning("Fuera crearTerminoCompleto");
        // Regresamos el id del nuevo Término
        if(rowNuevo != null)
            return Long.valueOf(rowNuevo.getAttribute("Id").toString());
        else
            return null;
    }
    
    public Long crearTermino(Long idOperacion, String nombreTermino, Integer idTcaTermino, Integer idTcaEstadoTcc, 
                             Integer idTcaSubEstadoTcc, Integer banEstatus, String nombreUsuario, String loginUsuario) {
        logger.log(ADFLogger.WARNING, "Inside crearTermino.");
        return crearTerminoCompleto(idOperacion, nombreTermino, idTcaTermino, idTcaEstadoTcc, idTcaSubEstadoTcc, banEstatus, null, nombreUsuario, loginUsuario);
    }
    
    public Long crearTerminoCompleto(Long idOperacion, String nombreTermino, Integer idTcaTermino, Integer idTcaEstadoTcc, 
                             Integer idTcaSubEstadoTcc, Integer banEstatus, Map atributos, String nombreUsuario, String loginUsuario) {
        logger.warning("Dentro crearTerminoCompleto");
        logger.warning("idOperacion :"+idOperacion);
        logger.warning("nombreTermino :"+nombreTermino);
        logger.warning("idTcaTermino :"+idTcaTermino);
        logger.warning("idTcaEstadoTcc :"+idTcaEstadoTcc);
        logger.warning("idTcaSubEstadoTcc :"+idTcaSubEstadoTcc);
        logger.warning("banEstatus :"+banEstatus);
        logger.warning("nombreUsuario :"+nombreUsuario);
        logger.warning("loginUsuario :"+loginUsuario);

        
        oracle.jbo.domain.Number idTermino = null;
        NameValuePairs nvpTermino = null;
        SequenceImpl seqTermino = null;
        Row rowNuevo = null;
                
        // Asignación de variables      
        seqTermino = new SequenceImpl("TERMINO_SEQ", getDBTransaction());
        idTermino = seqTermino.getSequenceNumber();
        nvpTermino = new NameValuePairs();
                
        // Creamos un nuevo Termino en base a los parámetros enviados
        nvpTermino.setAttribute("BanEstatus", banEstatus);
        nvpTermino.setAttribute("FechaRegistro", new java.sql.Timestamp(System.currentTimeMillis()));
        nvpTermino.setAttribute("Id", idTermino);
        nvpTermino.setAttribute("IdOperacion", idOperacion);
        nvpTermino.setAttribute("IdTcaEstadoTcc", idTcaEstadoTcc);
        nvpTermino.setAttribute("IdTcaSubEstadoTcc", idTcaSubEstadoTcc);
        nvpTermino.setAttribute("IdTcaTermino", idTcaTermino);
        nvpTermino.setAttribute("Nombre", nombreTermino);
        nvpTermino.setAttribute("LoginUsuario", loginUsuario);
        nvpTermino.setAttribute("NombreUsuario", nombreUsuario);
         
        if(atributos != null && !atributos.isEmpty()) {
            
            Iterator iter = atributos.entrySet().iterator();
            while(iter.hasNext()){
                @SuppressWarnings("unchecked")
                Map.Entry<String, Object> atributo = (Map.Entry<String, Object>) iter.next();
                if(atributo != null){
                    nvpTermino.setAttribute(atributo.getKey(), atributo.getValue());
                }
            }
        }

        rowNuevo = this.createAndInitRow(nvpTermino);
        try{
            getDBTransaction().commit();
        }catch(Exception e){
            logger.severe("Error en commit de crearTerminoCompleto :",e);
        }
        
        // Re-ejecutamos el query debido a que se creó un nuevo registro
        this.executeQuery();
        
        
        logger.warning("Fuera crearTerminoCompleto");
        // Regresamos el id del nuevo Término
        if(rowNuevo != null)
            return Long.valueOf(rowNuevo.getAttribute("Id").toString());
        else
            return null;
    }
    
    public void mappingTerminoRequestType(ActualizarTCCRequestType request, Accion accion) {
        TccTerminoVORowImpl row = (TccTerminoVORowImpl) getCurrentRow();

        request.setTipo(Tipo.TERMINO);
        
        Termino termino = new Termino();
        
        //TODO Mapeo de datos del Termino validando si los datos son NULL
        if (row != null) {
            try {
                termino.setAccion(accion);
                
                if (row.getId() != null) {
                    termino.setIdTermino(row.getId().longValue());
                }
                if (row.getNombre() != null && !row.getNombre().isEmpty()) {
                    termino.setNombre(row.getNombre());
                }
                if (row.getDescripcion() != null && !row.getDescripcion().isEmpty()) {
                    termino.setDescripcion(row.getDescripcion());
                }
                if (row.getPlazo() != null) {
                    termino.setPlazo(row.getPlazo());
                }
                if (row.getMonto() != null) {
                    termino.setMonto(row.getMonto().doubleValue());
                }
                if (row.getTasa() != null) {
                    termino.setTasa(row.getTasa().doubleValue());
                }
                if (row.getFrecuenciaRevision() != null) {
                    termino.setFrecuenciaRevision(row.getFrecuenciaRevision());
                }
                if (row.getFrecuenciaPagoInteres() != null) {
                    termino.setFrecuenciaPagoInteres(row.getFrecuenciaPagoInteres());
                }
                if (row.getFrecuenciaAmortizacion() != null) {
                    termino.setFrecuenciaAmortizacion(row.getFrecuenciaAmortizacion());
                }
                if (row.getMora() != null) {
                    termino.setMora(row.getMora().doubleValue());
                }
                if (row.getPorcentajeCobertura() != null) {
                    termino.setPorcentajeCobertura(row.getPorcentajeCobertura().doubleValue());
                }
                if (row.getSeAplicanRecursosConcesion() != null) {
                    termino.setSeAplicanRecursosConcesion(row.getSeAplicanRecursosConcesion().intValue() == 1 ? Boolean.TRUE : Boolean.FALSE);
                }
                if (row.getSeAplicanRecursosExternos() != null) {
                    termino.setSeAplicanRecursosExternos(row.getSeAplicanRecursosExternos().intValue() == 1 ? Boolean.TRUE : Boolean.FALSE);
                }
                if (row.getTipoContraparte() != null) {
                    termino.setTipoContraparte(row.getTipoContraparte());
                }
                if (row.getMontoMinimoDesembolso() != null) {
                    termino.setMontoMinimoDesembolso(row.getMontoMinimoDesembolso().doubleValue());
                }
                if (row.getMontoMaximoDesembolso() != null) {
                    termino.setMontoMaximoDesembolso(row.getMontoMaximoDesembolso().doubleValue());
                }
                if (row.getTasaMinimaDesembolso() != null) {
                    termino.setTasaMinimaDesembolso(row.getTasaMinimaDesembolso().doubleValue());
                }
                if (row.getTasaMaximaDesembolso() != null) {
                    termino.setTasaMaximaDesembolso(row.getTasaMaximaDesembolso().doubleValue());                
                }
                if (row.getFechaInicio() != null) {
                    termino.setFechaInicio(this.getXMLGregorianCalendar(row.getFechaInicio().getTime()));
                }
                if (row.getFechaVencimiento() != null) {
                    termino.setFechaVencimiento(this.getXMLGregorianCalendar(row.getFechaVencimiento().getTime()));
                }
                if (row.getFecha() != null) {
                    termino.setFecha(this.getXMLGregorianCalendar(row.getFecha().getTime()));
                }
                if (row.getFechaInicioRevision() != null) {
                    termino.setFechaInicioRevision(this.getXMLGregorianCalendar(row.getFechaInicioRevision().getTime()));
                }
                if (row.getFechaInicioPagoInteres() != null) {
                    termino.setFechaInicioPagoInteres(this.getXMLGregorianCalendar(row.getFechaInicioPagoInteres().getTime()));
                }
                if (row.getFechaRegistro() != null) {
                    termino.setFechaRegistro(this.getXMLGregorianCalendar(row.getFechaRegistro().getTime()));
                }
                if (row.getFechaEnmienda() != null) {
                    termino.setFechaEnmienda(this.getXMLGregorianCalendar(row.getFechaEnmienda().getTime()));
                }
                if (row.getIdTcaTipoFechaInicio() != null) {
                    termino.setTipoFechaInicio(this.getCatalogo(row.getIdTcaTipoFechaInicio().longValue()));
                }
                if (row.getIdTcaFrecuenciaPlazo() != null) {
                    termino.setFrecuenciaPlazo(this.getCatalogo(row.getIdTcaFrecuenciaPlazo().longValue()));
                }
                if (row.getIdTcaMoneda() != null) {
                    termino.setMoneda(this.getCatalogo(row.getIdTcaMoneda().longValue()));
                }
                if (row.getIdTcaTipoTasa() != null) {
                    termino.setTipoTasa(this.getCatalogo(row.getIdTcaTipoTasa().longValue()));
                }
                if (row.getIdTcaFrecuenciaRevision() != null) {
                    termino.setTipoFrecuenciaRevision(this.getCatalogo(row.getIdTcaFrecuenciaRevision().longValue()));
                }
                if (row.getIdTcaFrecuenciaPagoInteres() != null) {
                    termino.setTipoFrecuenciaPagoInteres(this.getCatalogo(row.getIdTcaFrecuenciaPagoInteres().longValue()));
                }
                if (row.getIdTcaFrecuenciaAmortizacion() != null) {
                    termino.setTipoFrecuenciaAmortizacion(this.getCatalogo(row.getIdTcaFrecuenciaAmortizacion().longValue()));
                }
                if (row.getIdTcaEstadoTcc() != null) {
                    termino.setEstadoTCC(this.getEstadoTCC(row.getIdTcaEstadoTcc().longValue()));
                }
                if (row.getIdTcaSubEstadoTcc() != null) {
                    termino.setSubEstadoTCC(this.getEstadoTCC(row.getIdTcaSubEstadoTcc().longValue()));
                }
                if (row.getIdOperacion() != null) {
                    termino.setOperacion(row.getIdOperacion());
                }
                if (row.getBanEstatus() != null) {
                    termino.setEstado(row.getBanEstatus().intValue() == 1 ? Boolean.TRUE : Boolean.FALSE);
                }
                if (row.getIdTerminoEnmendado() != null) {
                    termino.setTerminoEnmendado(row.getIdTerminoEnmendado());
                }
                if (row.getPorcentajeModificacion() != null) {
                    termino.setPorcentajeModificacion(row.getPorcentajeModificacion().doubleValue());
                }
                if (row.getIdTcaTipoAvance() != null) {
                    termino.setIdTcaTipoAvance(row.getIdTcaTipoAvance().doubleValue());
                }
                if (row.getIdTcaTipoPorcentaje() != null) {
                    termino.setIdTcaTipoPorcentaje(row.getIdTcaTipoAvance().doubleValue());
                }
                if (row.getPorcentaje() != null) {
                    termino.setPorcentaje(row.getPorcentaje().doubleValue());
                }
                if (row.getPorcentajeInicial() != null) {
                    termino.setPorcentajeInicial(row.getPorcentajeInicial().doubleValue());
                }
                if (row.getPorcentajeFinal() != null) {
                    termino.setPorcentajeFinal(row.getPorcentajeFinal().doubleValue());
                }
                
                //Mapeo de Instancia de Proceso
                if(row.getIdInstanciaProceso() != null){
                    request.setInstanciaProceso(row.getIdInstanciaProceso());
                }
                
                FenixAMImpl am = (FenixAMImpl) getApplicationModule();
                
                if (am != null) {
                    ContrapartesTerminoVOImpl contrapartesTerminoVOImpl = am.getContrapartesTerminoVO();
                    
                    if (contrapartesTerminoVOImpl != null) {
                        RowIterator iterator = contrapartesTerminoVOImpl.createRowSetIterator(null);
                        
                        if (iterator != null) {
                
                            iterator.reset();
                            while (iterator.hasNext()) {
                                ContrapartesTerminoVORowImpl contraparte = (ContrapartesTerminoVORowImpl) iterator.next();
                                
                                if (contraparte != null) {
                                    Long idContraparte = (Long) contraparte.getAttribute(ContrapartesTerminoVORowImpl.IDCONTRAPARTE);
                                    
                                    if (idContraparte != null) {
                                        EntidadMinima em = new EntidadMinima();
                                        em.setId(idContraparte.longValue());
                                        termino.getContraparte().add(em);
                                    }
                                }
                            }
                        }
                    }
                }
                
                if (row.getIdTcaTermino() != null && row.getIdTipoTermino() != null) {
                    CatalogoTermino catalogoTermino = new CatalogoTermino();
                    catalogoTermino.setIdCatTermino(row.getIdTcaTermino().longValue());
                    catalogoTermino.setIdTipoTermino(row.getIdTipoTermino().longValue());
                    termino.setTipoTermino(catalogoTermino);
                }
            } catch (DatatypeConfigurationException e) {
                e.printStackTrace();
            }
        }
        
        request.getTermino().add(termino);
        
    }
    
    private XMLGregorianCalendar getXMLGregorianCalendar(long millis) throws DatatypeConfigurationException {
        Date date = new Date(millis);
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String stringDate = simpleDateFormat.format(date);
        logger.warning("La fecha con formato es: " + stringDate);
        return DatatypeFactory.newInstance().newXMLGregorianCalendar(stringDate);
    }
    
    private Catalogo getCatalogo(Long id) {
        Catalogo catalogo = new Catalogo();
        catalogo.setId(id);
        return catalogo;
    }
    
    private EstadoTCC getEstadoTCC(Long id) {
        EstadoTCC estadoTCC = new EstadoTCC();
        estadoTCC.setId(id);
        return estadoTCC;
    }
    
    /**
     * Consulta termino por IdOperacion y IdTcaTermino
     * @param idOperacion
     * @param idTcaTermino
     * @since 07/04/2016 
    */
    public RowSetIterator buscarTerminoPorIdOperacionTcaTermino(Long idOperacion, Integer idTipoFechaInicio){
        logger.warning("Dentro buscarTerminoPorIdOperacionTcaTermino");
        logger.warning("idOperacion :"+idOperacion);
        logger.warning("idTipoFechaInicio :"+idTipoFechaInicio);
        RowSetIterator rowsetTerminos = null;
        
        try{
            ViewCriteria vc = getViewCriteria("TccTerminoPorOperTcaTerminoTipoFechaIniVC");
            
            if(vc != null) {
                setpIdOperacion(idOperacion);
                setpIdTipoFechaInicio(idTipoFechaInicio);
                applyViewCriteria(vc);
                executeQuery();
                
                rowsetTerminos = this.createRowSetIterator(null);
                
                setpIdOperacion(null);
                setpIdTipoFechaInicio(null);
            }
            
        }catch(Exception e){
            logger.severe("Error en la ejecucion del view criteria: " + "TccTerminoPorOperTcaTerminoTipoFechaIniVC");
        }
        
        logger.warning("Fuera buscarTerminoPorIdOperacionTcaTermino");
        return rowsetTerminos;
    }

    /**
     * Returns the variable value for pIdOperacion.
     * @return variable value for pIdOperacion
     */
    public Long getpIdOperacion() {
        return (Long) ensureVariableManager().getVariableValue("pIdOperacion");
    }

    /**
     * Sets <code>value</code> for variable pIdOperacion.
     * @param value value to bind as pIdOperacion
     */
    public void setpIdOperacion(Long value) {
        ensureVariableManager().setVariableValue("pIdOperacion", value);
    }

    /**
     * Returns the variable value for pIdTcaTermino.
     * @return variable value for pIdTcaTermino
     */
    public Integer getpIdTcaTermino() {
        return (Integer) ensureVariableManager().getVariableValue("pIdTcaTermino");
    }

    /**
     * Sets <code>value</code> for variable pIdTcaTermino.
     * @param value value to bind as pIdTcaTermino
     */
    public void setpIdTcaTermino(Integer value) {
        ensureVariableManager().setVariableValue("pIdTcaTermino", value);
    }

    /**
     * Returns the variable value for pIdTipoFechaInicio.
     * @return variable value for pIdTipoFechaInicio
     */
    public Integer getpIdTipoFechaInicio() {
        return (Integer) ensureVariableManager().getVariableValue("pIdTipoFechaInicio");
    }

    /**
     * Sets <code>value</code> for variable pIdTipoFechaInicio.
     * @param value value to bind as pIdTipoFechaInicio
     */
    public void setpIdTipoFechaInicio(Integer value) {
        ensureVariableManager().setVariableValue("pIdTipoFechaInicio", value);
    }
    
    /**
     * Método genérico para eliminar el current row de la VO.
     * Si falla la eliminación, hace rollback y regresa el current row al elemento que no pudo ser eliminado.
     * 
     * @author Francisco Cuevas Pineda 
     * @since 23/junio/2016
     */
    public void eliminarTerminoActual() {
        logger.log(ADFLogger.WARNING, "Inside eliminarTerminoActual.");
        boolean esError = false;
        Long idCurrentRow = null;
        Row currentRow = null;
        
        try {
            currentRow = this.getCurrentRow();
            if(currentRow != null) {
                idCurrentRow = (Long)currentRow.getAttribute("Id");
                
                logger.warning("Id de Termino a eliminar: " + String.valueOf(idCurrentRow));
                currentRow.remove();
                this.getDBTransaction().commit();
            }
        }
        catch(Exception ex){
            logger.log(ADFLogger.ERROR, "Error al eliminar el Término actual: " + ex.getMessage());
            this.getDBTransaction().rollback();
            esError = true;
            
            throw new JboException(ex); // Mandamos excepción a pantalla
        }
        finally{
            if(esError) {
                logger.warning("Existe un error,hacer currentRow el idtermino:"+idCurrentRow);
                // Regresa el current row al elemento que no pudo ser eliminado
                oracle.jbo.domain.Number idNumber = new oracle.jbo.domain.Number(idCurrentRow);
                Row row = buscarTerminoPorIdVC(idNumber);
                setCurrentRow(row); 
            }
        }
    }
    
    public Integer obtenerTipoMonedaMontoFormalizado(Long idOperacion){
        logger.warning("Inicia metodo obtenerTipoMonedaMontoFormalizado");
        Integer idTipoMoneda = null;
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(12);       //12: ID Termino Monto Formalizado - T203
        
        ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
        applyViewCriteria(vc);
        executeQuery();
        
        if(this.getEstimatedRowCount() > 0){
            setCurrentRow(first());
            
            Row row = getCurrentRow();
            logger.warning("IdTipoMoneda: " + row.getAttribute("IdTcaMoneda"));
            if(null != row.getAttribute("IdTcaMoneda")){
                idTipoMoneda = Integer.parseInt(row.getAttribute("IdTcaMoneda").toString());
            }else{
                logger.warning("IdTipoMoneda es NULL");
            }
        }else{
            logger.warning("No se encontró registro de Monto Formalizado para obtener el tipo de moneda.");
        }
        
        logger.warning("Removiendo ViewCriteria");
        this.getViewCriteriaManager().removeApplyViewCriteriaName("TccTerminoVOByOperacionTcaTerminoCriteria");
        logger.warning("Termina metodo obtenerTipoMonedaMontoFormalizado");
        return idTipoMoneda;
    }

    @SuppressWarnings("unchecked")
    public Map obtenerTccTerminoEnDesembolsos(Long idOperacion){
        logger.warning("Inicia metodo obtenerTccTerminoEnDesembolsos");
        double TInicio, TFin, tiempo; //Variables para determinar el tiempo de ejecución
        TInicio = System.currentTimeMillis(); //Tomamos la hora en que inicio el algoritmo y la almacenamos en la variable inicio

        Map mapaDatosEnDesembolso = new HashMap();
        BigDecimal montoMaximo = null;
        BigDecimal montoMinimo = null;
        BigDecimal tasaMaxima = null;
        BigDecimal tasaMinima = null;
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(26);
        
        ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
        applyViewCriteria(vc);
        executeQuery();
        
        if(this.getEstimatedRowCount() > 0){
            setCurrentRow(first());
            
            Row row = getCurrentRow();
            logger.warning("Monto Maximo Desembolso: " + row.getAttribute("MontoMaximoDesembolso"));
            logger.warning("Monto Minimo Desembolso: " + row.getAttribute("MontoMinimoDesembolso"));
            logger.warning("Tasa Maxima Desembolso: " + row.getAttribute("TasaMaximaDesembolso"));
            logger.warning("Tasa Minimo Desembolso: " + row.getAttribute("TasaMinimaDesembolso"));
            
            if(null != row.getAttribute("MontoMaximoDesembolso")){
                try{
                    montoMaximo = (BigDecimal) row.getAttribute("MontoMaximoDesembolso");
                }catch(Exception e){
                    logger.warning("Error al castear el atributo MontoMaximoDesembolso");
                }
                mapaDatosEnDesembolso.put("montoMaximo", montoMaximo);
            }else{
                logger.warning("MontoMaximoDesembolso es NULL");
            }
            
            if(null != row.getAttribute("MontoMinimoDesembolso")){
                try{
                    montoMinimo = (BigDecimal) row.getAttribute("MontoMinimoDesembolso");
                }catch(Exception e){
                    logger.warning("Error al castear el atributo MontoMinimoDesembolso");
                }
                mapaDatosEnDesembolso.put("montoMinimo", montoMinimo);
            }else{
                logger.warning("MontoMinimoDesembolso es NULL");
            }
            
            if(null != row.getAttribute("TasaMaximaDesembolso")){
                try{
                    tasaMaxima = (BigDecimal) row.getAttribute("TasaMaximaDesembolso");
                }catch(Exception e){
                    logger.warning("Error al castear el atributo TasaMaximaDesembolso");
                }
                mapaDatosEnDesembolso.put("tasaMaxima", tasaMaxima);
            }else{
                logger.warning("TasaMaximaDesembolso es NULL");
            }
            
            if(null != row.getAttribute("TasaMinimaDesembolso")){
                try{
                    tasaMinima = (BigDecimal) row.getAttribute("TasaMinimaDesembolso");
                }catch(Exception e){
                    logger.warning("Error al castear el atributo TasaMinimaDesembolso");
                }
                mapaDatosEnDesembolso.put("tasaMinima", tasaMinima);
            }else{
                logger.warning("TasaMinimaDesembolso es NULL");
            }
            
        }else{
            logger.warning("No se encontró registro de Termino En Desembolsos para obtener Monto maximo y minimo y Tasa maxima y minima.");
        }
        
        logger.warning("Removiendo ViewCriteria");
        this.getViewCriteriaManager().removeApplyViewCriteriaName("TccTerminoVOByOperacionTcaTerminoCriteria");
        logger.warning("Termino metodo obtenerTccTerminoEnDesembolsos");
        
        TFin = System.currentTimeMillis(); //Tomamos la hora en que finalizó el algoritmo y la almacenamos en la variable T
        tiempo = (TFin - TInicio)/ 1000; //Calculamos los milisegundos de diferencia
        logger.warning("termina el metodo obtenerTccTerminoEnDesembolsos con una duracion de: "+tiempo+" segundos");
        return mapaDatosEnDesembolso;
    }
    
    public Map actualizarMontoMaximoMinimoEnDesembolsos(Long idOperacion, BigDecimal montoDesembolsarCOntrato){
        logger.warning("Inicia metodo actualizarMontoMaximoMinimoEnDesembolsos");
        Map mapaDatosEnDesembolso = new HashMap();
        BigDecimal montoMaximo = null;
        BigDecimal montoMinimo = null;
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(26);
        
        ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
        applyViewCriteria(vc);
        executeQuery();
        
        if(this.getEstimatedRowCount() > 0){
            setCurrentRow(first());
            
            Row row = getCurrentRow();
            logger.warning("Monto Maximo Desembolso: " + row.getAttribute("MontoMaximoDesembolso"));
            logger.warning("Monto Minimo Desembolso: " + row.getAttribute("MontoMinimoDesembolso"));
            
            if(null != row.getAttribute("MontoMaximoDesembolso")){
                try{
                    montoMaximo = (BigDecimal) row.getAttribute("MontoMaximoDesembolso");
                }catch(Exception e){
                    logger.warning("Error al castear el atributo MontoMaximoDesembolso");
                }
            }else{
                logger.warning("MontoMaximoDesembolso es NULL");
            }
            
            if(null != row.getAttribute("MontoMinimoDesembolso")){
                try{
                    montoMinimo = (BigDecimal) row.getAttribute("MontoMinimoDesembolso");
                }catch(Exception e){
                    logger.warning("Error al castear el atributo MontoMinimoDesembolso");
                }
            }else{
                logger.warning("MontoMinimoDesembolso es NULL");
            }
            
            if(montoDesembolsarCOntrato.compareTo(montoMaximo)==1){
                logger.warning("Actualizando monto maximo del termino En DEsembolsos");
                row.setAttribute("MontoMaximoDesembolso", montoDesembolsarCOntrato);
            }
            
            if(montoDesembolsarCOntrato.compareTo(montoMinimo)==-1){
                logger.warning("Actualizando monto minimo del termino En DEsembolsos");
                row.setAttribute("MontoMinimoDesembolso", montoDesembolsarCOntrato);
            }  
            
            try{
                logger.warning("Ejecutando COMMIT.");
                getDBTransaction().commit();
            }catch(Exception e){
                logger.warning("ERROR al realizar el COMMIT para actualizar el termino En desembolso");
                getDBTransaction().rollback();
            }
        }
        logger.warning("Removiendo ViewCriteria");
        this.getViewCriteriaManager().removeApplyViewCriteriaName("TccTerminoVOByOperacionTcaTerminoCriteria");
        
        mapaDatosEnDesembolso = obtenerTccTerminoEnDesembolsos(idOperacion);
        logger.warning("Termina metodo actualizarMontoMaximoMinimoEnDesembolsos");
        return mapaDatosEnDesembolso;
    }
    
    
    public Date obtenerFechaTerminoPorId(Integer idTcaTermino, Long idOperacion){
        logger.entering(TccTerminoVOImpl.class.getName(), "obtenerFechaTerminoPorId", idTcaTermino);
        Date fechaTermino = null;
        
        if(null == idTcaTermino || null == idOperacion){
            logger.warning("Parametros requeridos son NULL, IdTermino: " + idTcaTermino + " idOperacion: " + idOperacion);
            return fechaTermino;
        }
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(idTcaTermino);
        
        ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
        applyViewCriteria(vc);
                
        //Refresca VO
        executeQuery();
        
        RowSetIterator iter = createRowSetIterator(null);
        if(iter != null){
            Row terminoRow = null;
            
            iter.reset();
            logger.warning("Iniciando iteracion para seteo de atributos de elementos de TCC");
            while(iter.hasNext()){
                terminoRow = iter.next();
                Integer idTcaTerminoRow = null;
                Long idOperacionTermino = null;
                
                try{
                    idTcaTerminoRow = (Integer) terminoRow.getAttribute("IdTcaTermino");
                }catch(Exception e){
                    logger.warning("ERROR al castear idTcaTerminoRow.", e);
                    return fechaTermino;
                }
                
                try{
                    idOperacionTermino = (Long) terminoRow.getAttribute("IdOperacion");
                }catch(Exception e){
                    logger.warning("ERROR al castear idOperacionTermino.", e);
                    return fechaTermino;    
                }
                
                //logger.warning("Comparando idTcaTermino y idOperacion");
                if(idTcaTermino.compareTo(idTcaTerminoRow)==0 && idOperacion.compareTo(idOperacionTermino)==0){
                    logger.warning("Recuperando atributo fecha");
                    try{
                        fechaTermino = (Date) terminoRow.getAttribute("FechaVencimiento");
                        if(null == fechaTermino){
                            logger.warning("El termino no tiene el dato de fecha.");
                        }
                    }catch(Exception e){
                        logger.warning("ERROR al castear la fechaTermino", e);
                    }
                    break;
                }
            }
            logger.warning("Finaliza iteracion para seteo de atributos de elementos de TCC");
            iter.closeRowSetIterator();
        }
        
        logger.exiting(TccTerminoVOImpl.class.getName(), "obtenerFechaTerminoPorId");
        return fechaTermino;
    }
    
    
    public String obtenerMonedaTerminoPorId(Integer idTcaTermino, Long idOperacion){
        logger.entering(TccTerminoVOImpl.class.getName(), "obtenerMonedaTerminoPorId", idTcaTermino);
        String moneda = FenixModelConstants.MONEDA_DESCRIPCION_USD;
        
        if(null == idTcaTermino || null == idOperacion){
            logger.warning("Parametros requeridos son NULL, IdTermino: " + idTcaTermino + " idOperacion: " + idOperacion);
            return moneda;
        }
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(idTcaTermino);
        
        ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
        applyViewCriteria(vc);
                
        //Refresca VO
        executeQuery();
        
        RowSetIterator iter = createRowSetIterator(null);
        if(iter != null){
            Row terminoRow = null;
            
            iter.reset();
            logger.warning("Iniciando iteracion para seteo de atributos de elementos de TCC");
            while(iter.hasNext()){
                terminoRow = iter.next();
                Integer idTcaTerminoRow = null;
                Long idOperacionTermino = null;
                
                try{
                    idTcaTerminoRow = (Integer) terminoRow.getAttribute("IdTcaTermino");
                }catch(Exception e){
                    logger.warning("ERROR al castear idTcaTerminoRow.", e);
                    return moneda;
                }
                
                try{
                    idOperacionTermino = (Long) terminoRow.getAttribute("IdOperacion");
                }catch(Exception e){
                    logger.warning("ERROR al castear idOperacionTermino.", e);
                    return moneda;    
                }
                
                //logger.warning("Comparando idTcaTermino y idOperacion");
                if(idTcaTermino.compareTo(idTcaTerminoRow)==0 && idOperacion.compareTo(idOperacionTermino)==0){
                    logger.warning("Recuperando atributo fecha");
                    try{
                        Integer tipoMoneda=null;
                        if(null!=terminoRow.getAttribute("IdTcaMoneda")){
                            tipoMoneda=(Integer) terminoRow.getAttribute("IdTcaMoneda");
                            FenixAMImpl fenixAMImpl = (FenixAMImpl) this.getRootApplicationModule();
                            String nombreMoneda=fenixAMImpl.getTcaTipoMonedaVO().obtenerCodigoExternoMoneda(tipoMoneda);
                            if(null!=nombreMoneda){
                                    moneda=nombreMoneda;
                                }
                            }
                        moneda = (String) terminoRow.getAttribute("IdTcaMoneda");
                        if(null == moneda){
                            logger.warning("El termino no tiene el dato de fecha.");
                        }
                    }catch(Exception e){
                        logger.warning("ERROR al castear la fechaTermino", e);
                        return moneda;
                    }
                    break;
                }
            }
            logger.warning("Finaliza iteracion para seteo de atributos de elementos de TCC");
            iter.closeRowSetIterator();
        }
        
        logger.exiting(TccTerminoVOImpl.class.getName(), "obtenerMonedaTerminoPorId");
        
        if (moneda == null || moneda == "") {
            moneda = FenixModelConstants.MONEDA_DESCRIPCION_USD;
        }
        
        logger.warning("resultado: "+ moneda);
        return moneda;
    }
    
    public Row obtenerTerminoPorIdOperacionTcaTermino(Long idOperacion, Integer idTcaTermino){
        logger.warning("Inicia metodo obtenerTerminoPorIdOperacionTcaTermino.");
        Row row = null;
        
        if(null == idOperacion || null == idTcaTermino){
            logger.warning("Valores requeridos para buscar termino son null." +
                "IdOperacion: " + idOperacion + ", TcaTermino: " + idTcaTermino);
            return row;
        }
        
        setpIdOperacion(idOperacion);
        setpIdTcaTermino(idTcaTermino);
        
        ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
        try{
            if(vc != null) {
                applyViewCriteria(vc);
                executeQuery();
            }
        }catch(Exception e){
            logger.severe("Error en la ejecucion del view criteria TccTerminoVOByOperacionTcaTerminoCriteria", e);
        }
        
        logger.warning("Registros de terminos encontrados: " + getEstimatedRowCount());
        if(getEstimatedRowCount() > 0){
            row = first();
        }
        
        logger.warning("Removiendo criteria.");
        this.getViewCriteriaManager().removeApplyViewCriteriaName("TccTerminoVOByOperacionTcaTerminoCriteria");
        logger.warning("Termina metodo obtenerTerminoPorIdOperacionTcaTermino.");
        return row;
    }
    
    /**
     * Se valida que la operacion cuente con el termino T603 (Se considera que la operacion ya esta formalizada)
     * @param idOperacion
     * @return
     * 29/11/2017
     */
    public Boolean validarTcaTipoTerminoFirmaContrato(Long idOperacion){
        logger.warning("Entra en validarTcaTipoTerminoFirmaContrato");
        Boolean existeTermino = Boolean.FALSE;
        
        try{
            ViewCriteria vc = getViewCriteria("TccTerminoVOByOperacionTcaTerminoCriteria");
            vc.ensureVariableManager().setVariableValue("pIdOperacion", idOperacion);
            vc.ensureVariableManager().setVariableValue("pIdTcaTermino", TCA_TERMINO_FIRMA_CONTRATO);//30: ID TCA Termino Firma Contrato - T603
            applyViewCriteria(vc);
            executeQuery();
            
            logger.warning("Numero de registros encontrados : " + this.getEstimatedRowCount());
            if(this.getEstimatedRowCount() > 0){
                
                logger.warning("La operacion se encuentra formalizada.");
                existeTermino = Boolean.TRUE;
                
            }else{
                logger.warning("No se encontraron terminos, la operacion no se encuentra formalizada");
            } 
        }catch(Exception e){
           logger.warning("Error en validarTcaTipoTerminoFirmaContrato.", e);
        }finally{
            logger.warning("Removiendo ViewCriteria");
            this.getViewCriteriaManager().removeApplyViewCriteriaName("TccTerminoVOByOperacionTcaTerminoCriteria");
            logger.warning("Termina metodo validarTcaTipoTerminoFirmaContrato");
        }
        return existeTermino;
    }
    
    /**
     *Metodo que valida si el porcentaje es unico o rango
     *
     * @return true si es unico o false si es rango
     */
    public Boolean validarTipoPorcentaje(){
        logger.warning("Inicia metodo validarTipoPorcentaje.");
        Boolean esUnico = null;
        Row row = null;
        Integer idTcaTipoPorcentaje = null;
        
        row = getCurrentRow();
        if(null != row){
            try{
                idTcaTipoPorcentaje = (Integer) row.getAttribute("IdTcaTipoPorcentaje");
            }catch(Exception e){
                logger.warning("ERROR al recuperar el atributo IdTcaTipoPorcentaje.", e);
            }
            
            if(null != idTcaTipoPorcentaje){
                switch(idTcaTipoPorcentaje){
                case 1:
                    logger.warning("idTcaTipoPorcentaje es unico");
                    esUnico = Boolean.TRUE;
                    break;
                case 2:
                    logger.warning("idTcaTipoPorcentaje es rango");
                    esUnico = Boolean.FALSE;
                    break;
                }
            }else{
                logger.warning("El IdTcaTipoPorcentaje es NULL.");
            }
        }else{
            logger.warning("El CurrentRow es NULL.");
        }
        
        logger.warning("Termina metodo validarTipoPorcentaje.");
        return esUnico;
    }
}

