<wsdl:definitions
     name="CrearEquipoTrabajoCliente"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/CrearEquipoTrabajoCliente/CrearEquipoTrabajoCliente"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/CrearEquipoTrabajoCliente/CrearEquipoTrabajoCliente"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearEquipoTrabajoCliente"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearEquipoTrabajoCliente_plt" >
    <plt:role name="CrearEquipoTrabajoCliente_role" >
      <plt:portType name="tns:CrearEquipoTrabajoCliente_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearEquipoTrabajoCliente" schemaLocation="../XSD/CrearEquipoTrabajoCliente_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EquipoTrabajoCollection_msg">
        <wsdl:part name="EquipoTrabajoCollection" element="top:EquipoTrabajoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearEquipoTrabajoCliente_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EquipoTrabajoCollection_msg"/>
            <wsdl:output message="tns:EquipoTrabajoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
