<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ConsultarOperacionEnProcesoService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:tns="http://www.bcie.org/ConsultarOperacionEnProcesoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:copMO="http://www.bcie.org/ConsultarOperacionEnProcesoMO">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/ConsultarOperacionEnProcesoMO"
                  schemaLocation="../Schema/ConsultarOperacionEnProcesoMO.xsd" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="consultarOperacionEnProcesoRequestMessage">
    <wsdl:part name="request" element="copMO:ConsultarOperacionEnProcesoRequest"/>
  </wsdl:message>
  <wsdl:message name="consultarOperacionEnProcesoResponseMessage">
    <wsdl:part name="response" element="copMO:ConsultarOperacionEnProcesoResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarOperacionEnProcesoPT">
    <wsdl:operation name="consultarOperacionEnProceso">
      <wsdl:input message="tns:consultarOperacionEnProcesoRequestMessage"/>
      <wsdl:output message="tns:consultarOperacionEnProcesoResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarOperacionEnProceso12Bnd" type="tns:ConsultarOperacionEnProcesoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarOperacionEnProceso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarOperacionEnProcesoService/consultarOperacionEnProceso"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>