<wsdl:definitions name="ObtenerRolesCuestionario" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerRolesCuestionario" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ObtenerRolesCuestionario" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerRolesCuestionario" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ObtenerRolesCuestionario_plt">
    <plt:role name="ObtenerRolesCuestionario_role">
      <plt:portType name="tns:ObtenerRolesCuestionario_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerRolesCuestionario"
                schemaLocation="../XSD/ObtenerRolesCuestionario.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerRolesCuestionarioInput_msg">
        <wsdl:part name="ObtenerRolesCuestionarioInput_msg" element="db:ObtenerRolesCuestionarioInput"/>
    </wsdl:message>
    <wsdl:message name="ObtenerRolesCuestionarioOutputCollection_msg">
        <wsdl:part name="ObtenerRolesCuestionarioOutputCollection" element="db:ObtenerRolesCuestionarioOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerRolesCuestionario_ptt">
        <wsdl:operation name="ObtenerRolesCuestionario">
            <wsdl:input message="tns:ObtenerRolesCuestionarioInput_msg"/>
            <wsdl:output message="tns:ObtenerRolesCuestionarioOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>