package org.bcie.fenix.common.model.vo.common;

import java.util.List;
import java.util.Map;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 16:53:13 CDT 2016
// ---------------------------------------------------------------------
public interface DocumentosAdjuntadosClientesVO extends ViewObject {

    void limpiarCacheDocumentosAdjuntadosClientesVO();

    void setidCliente(oracle.jbo.domain.Number value);

    void setidTarea(oracle.jbo.domain.Number value);

    void cargarDocumentosCliente();

    void setnumeroSerieDocumento(oracle.jbo.domain.Number value);

    void recargaDocumentos();

    Boolean eliminarDocumentosAviso(Long idCliente, String idTarea, Long idFlujo);


    Map currentDocumentsClient();

    Boolean verificarEstadoDocumento();

    List<Long> obtenerDocumentoIdAdjunto(Integer idTarea, Long idCliente, Long numSerie);

    Map enviarDocumentoOnBaseCliente(String usuario);

    void crearRegistroTbiDocumentoPorDB(Long idDocumento, String usuario, Integer idTarea);
}

