package org.bcie.fenix.common.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 12:07:37 CDT 2016
// ---------------------------------------------------------------------
public interface TransferenciasConsolidarVO extends ViewObject {

    Boolean validarTransferenciasAplicadas();

    void setpIdSolicitud(Long value);

    Boolean validarTransferenciasAplicadasPorContrato(Long idContrato);
}

