<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ValidarEnProcesoExcepcion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ValidarEnProcesoExcepcion"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:proExcMO="http://www.bcie.org/ValidarEnProcesoExcepcionMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ValidarEnProcesoExcepcion/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/ValidarEnProcesoExcepcionMO" schemaLocation="../Schema/ValidarEnProcesoExcepcionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestValidarEnProcesoExcepcionMessage">
    <part name="request" element="proExcMO:ValidarEnProcesoExcepcionRequest"/>
  </message>
  <message name="responseValidarEnProcesoExcepcionMessage">
    <part name="response" element="proExcMO:ValidarEnProcesoExcepcionResponse"/>
  </message>
  <portType name="ValidarEnProcesoExcepcion_PT">
    <operation name="ValidarEnProcesoExcepcion">
      <input message="tns:requestValidarEnProcesoExcepcionMessage"/>
      <output message="tns:responseValidarEnProcesoExcepcionMessage"/>
    </operation>
  </portType>
  <binding name="ValidarEnProcesoExcepcion_PTSOAP12Binding" type="tns:ValidarEnProcesoExcepcion_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ValidarEnProcesoExcepcion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ValidarEnProcesoExcepcion/ValidarEnProcesoExcepcion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>