<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/AdministrarOperacionProcess"
  xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/AdministrarOperacionProcess"
  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/AdministrarOperacionProcess"
        schemaLocation="../../Schema/PA16/AdministrarOperacionProcess.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="InicioAdministrarOperacion">
    <wsdl:part name="parameters" element="tns:InicioAdministrarOperacion"/>
  </wsdl:message>
  
  <wsdl:message name="FinAdministrarOperacion">
    <wsdl:part name="parameters" element="tns:FinAdministrarOperacion"/>
  </wsdl:message>
  
  <wsdl:portType name="AdministrarOperacionProcessPortType">
    <wsdl:operation name="InicioAdministrarOperacion">
      <wsdl:input message="tns:InicioAdministrarOperacion"/>
    </wsdl:operation>
    <wsdl:operation name="FinAdministrarOperacion">
      <wsdl:input message="tns:FinAdministrarOperacion"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="AdministrarOperacionProcessBinding" type="tns:AdministrarOperacionProcessPortType">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="InicioAdministrarOperacion">
      <wsdlsoap:operation style="document" soapAction="InicioAdministrarOperacion"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="FinAdministrarOperacion">
      <wsdlsoap:operation style="document" soapAction="FinAdministrarOperacion"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <plnk:partnerLinkType name="AdministrarOperacionProcessPortTypePartnerLinkType">
    <plnk:role name="AdministrarOperacionProcessPortTypeProvider">
      <plnk:portType name="tns:AdministrarOperacionProcessPortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
  
</wsdl:definitions>
