<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAdquisicion" name="ConsultarAdquisicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarAdquisicion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAdquisicion"/>
    <wsdl:binding name="ConsultarAdquisicion_ptt-binding" type="con:ConsultarAdquisicion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAdquisicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarAdquisicion">
            <soap:operation soapAction="ConsultarAdquisicion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>