<wsdl:definitions name="ConsultarOperacionProceso_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacionProceso_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacionProceso_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionProceso_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarOperacionProceso_DB_plt">
    <plt:role name="ConsultarOperacionProceso_DB_role">
      <plt:portType name="tns:ConsultarOperacionProceso_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionProceso_DB" schemaLocation="../XSD/ConsultarOperacionProceso_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarOperacionProceso_DBInput_msg">
        <wsdl:part name="ConsultarOperacionProceso_DBInput_msg" element="db:ConsultarOperacionProceso_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarOperacionProceso_DBOutputCollection_msg">
        <wsdl:part name="ConsultarOperacionProceso_DBOutputCollection" element="db:ConsultarOperacionProceso_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarOperacionProceso_DB_ptt">
        <wsdl:operation name="ConsultarOperacionProceso_DB">
            <wsdl:input message="tns:ConsultarOperacionProceso_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarOperacionProceso_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>