<wsdl:definitions name="OperacionProcesoDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/OperacionProcesoDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/OperacionProcesoDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/OperacionProcesoDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="OperacionProcesoDB_plt">
    <plt:role name="OperacionProcesoDB_role">
      <plt:portType name="tns:OperacionProcesoDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/OperacionProcesoDB" schemaLocation="../XSD/OperacionProcesoDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="TreOperacionProcesoBpmCollection_msg">
        <wsdl:part name="TreOperacionProcesoBpmCollection" element="top:TreOperacionProcesoBpmCollection"/>
    </wsdl:message>
    <wsdl:portType name="OperacionProcesoDB_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:TreOperacionProcesoBpmCollection_msg"/>
            <wsdl:output message="tns:TreOperacionProcesoBpmCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>