<wsdl:definitions name="ConsultarTreCategoriaCondicionByIdCondicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTreCategoriaCondicionByIdCondicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTreCategoriaCondicionByIdCondicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarTreCategoriaCondicionByIdCondicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTreCategoriaCondicionByIdCondicion_plt">
    <plt:role name="ConsultarTreCategoriaCondicionByIdCondicion_role">
      <plt:portType name="tns:ConsultarTreCategoriaCondicionByIdCondicion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarTreCategoriaCondicionByIdCondicion" schemaLocation="../XSD/ConsultarTreCategoriaCondicionByIdCondicion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTreCategoriaCondicionByIdCondicionSelect_inputParameters">
        <wsdl:part name="ConsultarTreCategoriaCondicionByIdCondicionSelect_inputParameters" element="top:ConsultarTreCategoriaCondicionByIdCondicionSelect_idCondicion_idCategoriaInputParameters"/>
    </wsdl:message>
    <wsdl:message name="TreCategoriaCondicionCollection_msg">
        <wsdl:part name="TreCategoriaCondicionCollection" element="top:TreCategoriaCondicionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTreCategoriaCondicionByIdCondicion_ptt">
        <wsdl:operation name="ConsultarTreCategoriaCondicionByIdCondicionSelect">
            <wsdl:input message="tns:ConsultarTreCategoriaCondicionByIdCondicionSelect_inputParameters"/>
            <wsdl:output message="tns:TreCategoriaCondicionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>