<wsdl:definitions
     name="ConsultarTreComiteRol"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConfigurarSolicitudAprobacion/ConsultarTreComiteRol"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/ConfigurarSolicitudAprobacion/ConsultarTreComiteRol"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreComiteRol"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarTreComiteRol_plt" >
    <plt:role name="ConsultarTreComiteRol_role" >
      <plt:portType name="tns:ConsultarTreComiteRol_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTreComiteRol" schemaLocation="../XSD/ConsultarTreComiteRol.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTreComiteRolInput_msg">
        <wsdl:part name="ConsultarTreComiteRolInput_msg" element="db:ConsultarTreComiteRolInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTreComiteRolOutputCollection_msg">
        <wsdl:part name="ConsultarTreComiteRolOutputCollection" element="db:ConsultarTreComiteRolOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTreComiteRol_ptt">
        <wsdl:operation name="ConsultarTreComiteRol">
            <wsdl:input message="tns:ConsultarTreComiteRolInput_msg"/>
            <wsdl:output message="tns:ConsultarTreComiteRolOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
