<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:docMO="http://www.bcie.org/DocumentoMO"
xmlns:tns="http://xmlns.bcie.com/DocumentoService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="Documento" 
targetNamespace="http://xmlns.bcie.com/DocumentoService">
  <wsdl:types>
  
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/DocumentoMO" schemaLocation="../../Schema/DocumentoMO.xsd"/>
		</xsd:schema>
  </wsdl:types>
  <wsdl:message name="RequestConsultarDocumentoOnBaseMessages">
    <wsdl:part name="ConsultarDocumentoOnBaseRequest" element="docMO:ConsultaDocumentosRequest"/>
  </wsdl:message>
  <wsdl:message name="ResponseConsultarDocumentosOnBaseMessage">
    <wsdl:part name="ConsultarDocumentosOnBaseResponse" element="docMO:ConsultaDocumentosResponse"/>
  </wsdl:message>
  <wsdl:portType name="DocumentoOnbasePT">
    <wsdl:operation name="ConsultarDocumentosOnBase">
      <wsdl:input message="tns:RequestConsultarDocumentoOnBaseMessages"/>
      <wsdl:output message="tns:ResponseConsultarDocumentosOnBaseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="DocumentoPTSOAP12Binding" type="tns:DocumentoOnbasePT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarDocumentosOnBase">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/DocumentoService/ConsultarDocumentosOnBase"/>
      <wsdl:input>
        <soap12:body use="literal" parts="ConsultarDocumentoOnBaseRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="ConsultarDocumentosOnBaseResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>