<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/DocumentoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/DocumentoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:docMO="http://www.bcie.org/DocumentoMO">
  <types>
    <xsd:schema targetNamespace="http://xmlns.bcie.com/DocumentoService/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/DocumentoMO" schemaLocation="../../Schema/DocumentoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ObtenerDocumentoRequestMessage">
    <part name="ObtenerDocumentoRequest" element="docMO:ObtenerDocumentoRequest"/>
  </message>
  <message name="ObtenerDocumentoResponseMessage">
    <part name="ObtenerDocumentoResponse" element="docMO:ObtenerDocumentoResponse"/>
  </message>
  <portType name="ObtenerDocumentoPT">
    <operation name="obtenerDocumento">
      <input message="tns:ObtenerDocumentoRequestMessage"/>
      <output message="tns:ObtenerDocumentoResponseMessage"/>
    </operation>
  </portType>
  <binding name="ObtenerDocumentoPT12Bnd" type="tns:ObtenerDocumentoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="obtenerDocumento">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/DocumentoService/obtenerDocumento"/>
      <input>
        <soap12:body use="literal" parts="ObtenerDocumentoRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ObtenerDocumentoResponse"/>
      </output>
    </operation>
  </binding>
</definitions>