<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarBitacoraProcesoOperacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarBitacoraProcesoOperacion" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:bitaProcMO="http://www.bcie.org/CrearBitacoraProcesoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarBitacoraProcesoSCR/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/CrearBitacoraProcesoMO" schemaLocation="../Schema/BitacoraProcesoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarBitacoraProcesoOperacionMessage">
    <part name="request" element="bitaProcMO:ConsultarBitacoraProcesoOperacionRequest"/>
  </message>
  <message name="responseConsultarBitacoraProcesoOperacionMessage">
    <part name="response" element="bitaProcMO:ConsultarBitacoraProcesoOperacionResponse"/>
  </message>
  <portType name="ConsultarBitacoraProcesoOperacionPT">
    <operation name="consultarBitacoraProcesoOperacion">
      <input message="tns:requestConsultarBitacoraProcesoOperacionMessage"/>
      <output message="tns:responseConsultarBitacoraProcesoOperacionMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarBitacoraProcesoOperacionPT12Bnd" type="tns:ConsultarBitacoraProcesoOperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarBitacoraProcesoOperacion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarBitacoraProcesoOperacion/consultarBitacoraProcesoOperacion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>