<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:ActualizarAprobacionSOR" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ActualizarAprobacionSOR" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:aproMO="http://www.bcie.org/AprobacionMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ActualizarAprobacionRequestMessage">
    <part name="ActualizarAprobacionRequest" element="aproMO:ActualizarAprobacionRequest"/>
  </message>
  <message name="ActualizarAprobacionResponseMessage">
    <part name="ActualizarAprobacionResponse" element="aproMO:ActualizarAprobacionResponse"/>
  </message>
  <portType name="ActualizarAprobacionPT">
    <operation name="ActualizarAprobacion">
      <input message="tns:ActualizarAprobacionRequestMessage"/>
      <output message="tns:ActualizarAprobacionResponseMessage"/>
    </operation>
  </portType>
  <binding name="ActualizarAprobacionPTSOAP12Binding" type="tns:ActualizarAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ActualizarAprobacion">
      <soap12:operation style="document" soapAction="urn:ActualizarAprobacionSOR/ActualizarAprobacion"/>
      <input>
        <soap12:body use="literal" parts="ActualizarAprobacionRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ActualizarAprobacionResponse"/>
      </output>
    </operation>
  </binding>
</definitions>