<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:correoMO="http://www.bcie.org/CorreoMO" xmlns:tns="http://xmlns.bcie.com/CorreoElectronicoService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="CorreoElectronico" targetNamespace="http://xmlns.bcie.com/CorreoElectronicoService">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="../Schema/CorreoElectronicoMO.xsd"/>
		</xsd:schema>
	</wsdl:types>


         <wsdl:message name="requestValidarEnvioNotifSupervTCCRequestMessage">
            <wsdl:part name="ValidarEnvioNotifSupervTCCRequest" element="correoMO:ValidarEnvioNotifSupervTCCRequest"/>
        </wsdl:message>
        
	<wsdl:message name="responseValidarEnvioNotifSupervTCCResponseMessage">
            <wsdl:part name="ValidarEnvioNotifSupervTCCResponse" element="correoMO:ValidarEnvioNotifSupervTCCResponse"/>
        </wsdl:message>

	<wsdl:portType name="ValidarEnvioNotifSupervTCCPT">
		<!-- Create -->
		<wsdl:operation name="validarEnvioNotifSupervTCC">
			<wsdl:input message="tns:requestValidarEnvioNotifSupervTCCRequestMessage"/>
                        <wsdl:output message="tns:responseValidarEnvioNotifSupervTCCResponseMessage"/>
		</wsdl:operation>
	
	</wsdl:portType>
	<wsdl:binding name="ValidarEnvioNotifSupervTCCPTBnd" type="tns:ValidarEnvioNotifSupervTCCPT">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="validarEnvioNotifSupervTCC">
			<soap12:operation soapAction="http://xmlns.bcie.com/DocumentoService/enviarCorreoElectronico" style="document"/>
			<wsdl:input>
				<soap12:body parts="ValidarEnvioNotifSupervTCCRequest" use="literal"/>
			</wsdl:input>
                        <wsdl:output>
				<soap12:body parts="ValidarEnvioNotifSupervTCCResponse" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	
	</wsdl:binding>
</wsdl:definitions>
