<wsdl:definitions name="CrearActualizarComisionDesembolso" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CrearActualizarComisionDesembolso" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/CrearActualizarComisionDesembolso" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarComisionDesembolso" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearActualizarComisionDesembolso_plt">
    <plt:role name="CrearActualizarComisionDesembolso_role">
      <plt:portType name="tns:CrearActualizarComisionDesembolso_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearActualizarComisionDesembolso" schemaLocation="../XSD/CrearActualizarComisionDesembolso_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ComisionDesembolsoCollection_msg">
        <wsdl:part name="ComisionDesembolsoCollection" element="top:ComisionDesembolsoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearActualizarComisionDesembolso_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:ComisionDesembolsoCollection_msg"/>
            <wsdl:output message="tns:ComisionDesembolsoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>