<definitions targetNamespace="http://xmlns.banesco.com/BizLayer/CardDbSvc_V1.0" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.banesco.com/BizLayer/CardDbSvc_V1.0"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
             xmlns:eoptCardDbAdd="http://xmlns.banesco.com/eopt/CardDbAdd_V1.0">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="../../../xsd/EO/Status/Status_V1.0.xsd"
                  namespace="http://xmlns.banesco.com/eo/Status_V1.0"/>
      <xsd:import schemaLocation="../../../xsd/EOpt/CardDb/CardDbAdd/CardDbAdd_V1.0.xsd"
                  namespace="http://xmlns.banesco.com/eopt/CardDbAdd_V1.0"/>            
    </xsd:schema>
  </types>
  <message name="SystemFault">
    <part name="SystemFault" element="eoStatus:SystemFault"/>
  </message>
  <message name="CardDbAddRq">
    <part name="CardDbAddRq" element="eoptCardDbAdd:CardDbAddRq"/>
  </message>
  <message name="CardDbAddRs">
    <part name="CardDbAddRs" element="eoptCardDbAdd:CardDbAddRs"/>
  </message>
  <portType name="CardDbSvc_V1.0PortType">
    <operation name="CardDbAdd">
      <input message="tns:CardDbAddRq"/>
      <output message="tns:CardDbAddRs"/>
      <fault name="SystemFault" message="tns:SystemFault"/>
    </operation>
  </portType>
  <service name="CardDbSvc_V1.0">
    <port name="CardDbSvcPort" binding="tns:CardDbSvc_V1.0SOAPBinding">
      <soap:address location="http://www.example.com"/>
    </port>
  </service>
  <binding name="CardDbSvc_V1.0SOAPBinding" type="tns:CardDbSvc_V1.0PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CardDbAdd">
      <soap:operation style="document" soapAction="http://xmlns.banesco.com/BizLayer/CardDbSvc_V1.0/CardDbAdd"/>
      <input>
        <soap:body use="literal" parts="CardDbAddRq"/>
      </input>
      <output>
        <soap:body use="literal" parts="CardDbAddRs"/>
      </output>
      <fault name="SystemFault">
        <soap:fault name="SystemFault" use="literal"/>
      </fault>
    </operation>
  </binding>
</definitions>