<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://ww.bcie.org/EliminarTreLineaCreditoService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://ww.bcie.org/EliminarTreLineaCreditoService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="EliminarTreLineaCreditoTCC_SB">
      <plnk:role name="EliminarTreLineaCreditoTCCPT" portType="tns:EliminarTreLineaCreditoTCCPT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://ww.bcie.org/EliminarTreLineaCreditoService" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/ADAPTER/EliminarTreLineaCreditoTCC.wsdl"/>
</wsdl:definitions>
