/*
----------------------------------
ARCHIVO: 2-DB UPDATES 1.5.sql
DESCRIPCION: Registrar los cambios a la tabla operación
FECHA: 10 DE FEBRERO DE 2016
AUTOR: LATBC 
VERSION: 1.0
----------------------------------/
*/

-- CAMBIO #1: Agregar columnas adicionales

ALTER TABLE OPERACION  ADD  JUSTIFICACION_CANCELA VARCHAR2(1024);
ALTER TABLE OPERACION  ADD  OBSERVACION_CANCELA VARCHAR2(1024);

-- CAMBIO #2: Eliminar los campos de elegibilidad

ALTER TABLE OPERACION DROP COLUMN  OPINION_ELEGIBILIDAD;
ALTER TABLE OPERACION DROP COLUMN  COMENTARIO_ELEGIBILIDAD;
ALTER TABLE OPERACION DROP COLUMN  OPINION_DETERMINAR;
ALTER TABLE OPERACION DROP COLUMN  COMENTARIO_DETERMINAR;
ALTER TABLE OPERACION DROP COLUMN  LINEA_CREDITO;

-- CAMBIO #3: Asignar valores not null 
ALTER TABLE OPERACION MODIFY BAN_ESTATUS  NOT NULL;
ALTER TABLE OPERACION MODIFY ESTADO  NOT NULL;

-- CAMBIO #4: Agregar llave foranea hacia CAT_SECTOR_MERCADO 
ALTER TABLE OPERACION ADD CONSTRAINT OPERACION_CAT_SECTOR_MERC_FK FOREIGN KEY (SECTOR_MERCADO) REFERENCES CAT_SECTOR_MERCADO (ID);

-- CAMBIO #5: Renombrar la columna REQUIERE_RECURSOS_EXT
 ALTER TABLE OPERACION RENAME COLUMN REQUIERE_RECUSROS_EXT TO REQUIERE_RECURSOS_EXT;   
 
 