CREATE OR REPLACE TRIGGER FENIX.CLIENTE_UPD_TGR 
	AFTER UPDATE ON FENIX.CLIENTES FOR EACH ROW
	DECLARE 
	v_id_tbi_cliente NUMBER;	
	v_ban_estatus    NUMBER; 

	BEGIN

	  SELECT TBI_CLIENTE_SEQ.NEXTVAL INTO v_id_tbi_cliente FROM DUAL;
	  
	  v_ban_estatus := :NEW.BAN_ESTATUS;
	  
	IF ( v_ban_estatus = 0) THEN

		INSERT INTO TBI_CLIENTE  VALUES(v_id_tbi_cliente,:NEW.ID_CLIENTE,:NEW.ID_FLEXCUBE,'ELIMINAR_CLIENTE',:NEW.EJECUTIVO,SYSDATE,:NEW.AUTORIZO,NULL,NULL); 
		INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'BAN_ESTATUS',:NEW.BAN_ESTATUS,:OLD.BAN_ESTATUS);
	ELSE    

		INSERT INTO TBI_CLIENTE  VALUES(v_id_tbi_cliente,:NEW.ID_CLIENTE,:NEW.ID_FLEXCUBE,'MODIFICAR_CLIENTE',:NEW.EJECUTIVO,SYSDATE,:NEW.AUTORIZO,NULL,NULL); 
		
	IF UPDATING ('ID_FLEXCUBE') THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES (v_id_tbi_cliente,'ID_FLEXCUBE',:NEW.ID_FLEXCUBE,:OLD.ID_FLEXCUBE);
	END IF;  
	IF UPDATING ('RAZON_SOCIAL')THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'RAZON_SOCIAL',:NEW.RAZON_SOCIAL,:OLD.RAZON_SOCIAL);
	END IF;  
	IF UPDATING('ABREVIATURA')THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'ABREVIATURA',:NEW.ABREVIATURA,:OLD.ABREVIATURA);
	END IF;  
	IF UPDATING('TIPO_PERSONA')THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'TIPO_PERSONA',:NEW.TIPO_PERSONA,:OLD.TIPO_PERSONA);
	END IF;  
	IF UPDATING('TIPO_CLIENTE')THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'TIPO_CLIENTE',:NEW.TIPO_CLIENTE,:OLD.TIPO_CLIENTE);
	END IF;  
	IF UPDATING('SECTOR')THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'SECTOR',:NEW.SECTOR,:OLD.SECTOR);
	END IF;  
	IF UPDATING('TIPO_INSTITUCION')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'TIPO_INSTITUCION',:NEW.TIPO_INSTITUCION,:OLD.TIPO_INSTITUCION);
	END IF;  
	IF UPDATING('PAIS')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'PAIS',:NEW.PAIS,:OLD.PAIS);
	END IF;  
	IF UPDATING('GRUPO_ECONOMICO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'GRUPO_ECONOMICO',:NEW.GRUPO_ECONOMICO,:OLD.GRUPO_ECONOMICO);
	END IF;  
	IF UPDATING('TIPO_IDENTIFICACION')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'TIPO_IDENTIFICACION',:NEW.TIPO_IDENTIFICACION,:OLD.TIPO_IDENTIFICACION);
	END IF;  
	IF UPDATING('NUMERO_IDENTIFICACION')THEN
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'NUMERO_IDENTIFICACION',:NEW.NUMERO_IDENTIFICACION,:OLD.NUMERO_IDENTIFICACION);
	END IF;  
	IF UPDATING('OFICINA')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'OFICINA',:NEW.OFICINA,:OLD.OFICINA);
	END IF;  
	IF UPDATING('FECHA_REGISTRO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,:OLD.FECHA_REGISTRO);
	END IF;  
	IF UPDATING('FECHA_APROBACION')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'FECHA_APROBACION',:NEW.FECHA_APROBACION,:OLD.FECHA_APROBACION);
	END IF;  
	IF UPDATING('EJECUTIVO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'EJECUTIVO',:NEW.EJECUTIVO,:OLD.EJECUTIVO);
	END IF;  
	IF UPDATING('COMENTARIO_APROBACION')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'COMENTARIO_APROBACION',:NEW.COMENTARIO_APROBACION,:OLD.COMENTARIO_APROBACION);
	END IF;  
	IF UPDATING('AUTORIZO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'AUTORIZO',:NEW.AUTORIZO,:OLD.AUTORIZO);
	END IF;  
	IF UPDATING('BAN_ESTATUS')THEN 
	   INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'BAN_ESTATUS',:NEW.BAN_ESTATUS,:OLD.BAN_ESTATUS);
	END IF;  
	IF UPDATING('FECHA_BAJA')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'FECHA_BAJA',:NEW.FECHA_BAJA,:OLD.FECHA_BAJA);
	END IF;  
	IF UPDATING('DIA_PAGO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'DIA_PAGO',:NEW.DIA_PAGO,:OLD.DIA_PAGO);
	END IF;
	IF UPDATING('ESTA_DETERIORADO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'ESTA_DETERIORADO',:NEW.ESTA_DETERIORADO,:OLD.ESTA_DETERIORADO);
	END IF;
	IF UPDATING('ID_TCA_SCR')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'ID_TCA_SCR',:NEW.ID_TCA_SCR,:OLD.ID_TCA_SCR);
	END IF;
	IF UPDATING('ID_TCA_PERSPECTIVA')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'ID_TCA_PERSPECTIVA',:NEW.ID_TCA_PERSPECTIVA,:OLD.ID_TCA_PERSPECTIVA);
	END IF;
	IF UPDATING('REQUIERE_ENVIO_AUTOMATICO')THEN  
	  INSERT INTO TBI_CLIENTE_CAMPO VALUES(v_id_tbi_cliente,'REQUIERE_ENVIO_AUTOMATICO',:NEW.REQUIERE_ENVIO_AUTOMATICO,:OLD.REQUIERE_ENVIO_AUTOMATICO);
	END IF;

	END IF;

	END;