CREATE OR REPLACE PACKAGE LINEAS_CREDITO_PKG
IS
   PROCEDURE ACTUALIZAR_LINEAS (
      P_ID_APROBACION    IN     NUMBER,
      P_ID_CONTRATO      IN     NUMBER,
      P_LINEAS_CREDITO   IN     T_LINEASCREDITO_APRO,
      P_RESULTADO           OUT VARCHAR2,
      P_MENSAJE             OUT VARCHAR2);

END LINEAS_CREDITO_PKG;
/
