CREATE OR REPLACE PROCEDURE migrar_config_visibilidad AS 

	TYPE CAMPOS_CUR_TYPE IS REF CURSOR;
	CAMPOS			CAMPOS_CUR_TYPE;
	ID_COLUMNA		NUMBER;
	NOMBRE_COLUMNA	VARCHAR2(30);
	QUERY			VARCHAR2(2000);
	QUERY_INSERT	VARCHAR2(2000);
	V_ID_PRODUCTO	NUMBER(5);
	V_VALOR			VARCHAR(1);
	
	CURSOR COLUMNAS
	IS
		SELECT COLUMN_ID-2, COLUMN_NAME
		FROM   all_tab_cols
		WHERE  table_name = 'CONFIG_VISIBILIDAD'
		AND COLUMN_ID>2
		ORDER BY COLUMN_ID;


	BEGIN
		OPEN COLUMNAS;
		LOOP
			FETCH COLUMNAS INTO ID_COLUMNA,NOMBRE_COLUMNA;
			EXIT WHEN COLUMNAS%notfound;
			
			QUERY:='SELECT ID_PRODUCTO, '||NOMBRE_COLUMNA||' AS VALOR FROM CONFIG_VISIBILIDAD';
			--DBMS_OUTPUT.PUT_LINE(QUERY);
		
			OPEN CAMPOS FOR QUERY;
			LOOP
				FETCH CAMPOS INTO V_ID_PRODUCTO, V_VALOR;
				EXIT WHEN CAMPOS%notfound;
				IF (V_VALOR='1') THEN
					QUERY_INSERT:='INSERT INTO TRE_CAT_PRODUCTO_TCA_CAMPOS (ID, ID_CAT_PRODUCTO, ID_CAMPO)VALUES(NULL, '||V_ID_PRODUCTO||','||ID_COLUMNA||')';
					EXECUTE IMMEDIATE QUERY_INSERT;
				END IF;
			END LOOP;
			CLOSE CAMPOS;
		END LOOP;
		CLOSE COLUMNAS;
	END migrar_config_visibilidad;
