create or replace PROCEDURE SP_CONSULTAR_CUMPLIMIENTO 
(
  P_ID_CONDICION     IN T_NUMBER_TAB,
  P_CODIGO_RES       OUT NUMBER, 
  P_MENSAJE          OUT VARCHAR2, 
  RECORDSET          OUT SYS_REFCURSOR) 
AS 
BEGIN
  
  OPEN RECORDSET FOR 
  SELECT
  ID,
  ID_OPERACION,
  ID_SOLICITUD,
  ID_CONTRATO_DESEMBOLSO,
  ID_CONDICION,
  ID_TCA_ESTADO_TCC,
  ID_TCA_EVENTO_CONDICION,
  AGRUPADOR,
  BAN_ESTATUS,
  ID_TCA_SUB_ESTADO_TCC,
  EN_PROCESO
  FROM
  TRE_TRANSACCION_CONDICION
  WHERE ID_CONDICION IN (SELECT * FROM TABLE(P_ID_CONDICION)) AND BAN_ESTATUS = 1;
  
  P_CODIGO_RES := 0;
  
  EXCEPTION
WHEN OTHERS THEN

P_CODIGO_RES := SQLCODE;

P_MENSAJE := SQLERRM;

  
END SP_CONSULTAR_CUMPLIMIENTO;