

CREATE OR REPLACE TRIGGER TERMINO_INS_TGR
AFTER INSERT ON TERMINO
FOR EACH ROW

DECLARE
	v_id_tbi_termino NUMBER;	
	err_num NUMBER;
	err_msg VARCHAR2(255);
	
BEGIN

	SELECT TBI_TERMINO_SEQ.NEXTVAL INTO v_id_tbi_termino FROM DUAL;
	
	-- ID_TCA_TERMINO = 1 - T101, 30 - T603
  
	IF (:NEW.ID_TCA_TERMINO = 1) THEN 
		INSERT INTO TBI_TERMINO(ID, ID_TERMINO, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_termino,:NEW.ID,'AGREGAR TERMINO T101',:NEW.LOGIN_USUARIO,:NEW.NOMBRE_USUARIO,SYSDATE);  
	ELSIF (:NEW.ID_TCA_TERMINO = 30) THEN
		INSERT INTO TBI_TERMINO(ID, ID_TERMINO, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_termino,:NEW.ID,'AGREGAR TERMINO T603',:NEW.LOGIN_USUARIO,:NEW.NOMBRE_USUARIO,SYSDATE);  
	END IF;
	
	IF (:NEW.ID_TCA_TERMINO = 1) OR (:NEW.ID_TCA_TERMINO = 30)
	THEN 
			  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID',:NEW.ID,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_OPERACION',:NEW.ID_OPERACION,NULL);	  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'NOMBRE',:NEW.NOMBRE,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'DESCRIPCION',:NEW.DESCRIPCION,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TERMINO',:NEW.ID_TCA_TERMINO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_FECHA_INICIO',:NEW.ID_TCA_TIPO_FECHA_INICIO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_INICIO',:NEW.FECHA_INICIO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PLAZO',:NEW.PLAZO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_PLAZO',:NEW.ID_TCA_FRECUENCIA_PLAZO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_VENCIMIENTO',:NEW.FECHA_VENCIMIENTO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_MONEDA',:NEW.ID_TCA_MONEDA,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MONTO',:NEW.MONTO,NULL);    
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TASA',:NEW.TASA,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_TASA',:NEW.ID_TCA_TIPO_TASA,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA',:NEW.FECHA,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FRECUENCIA_REVISION',:NEW.FRECUENCIA_REVISION,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_REVISION',:NEW.ID_TCA_FRECUENCIA_REVISION,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_INICIO_REVISION',:NEW.FECHA_INICIO_REVISION,NULL); 
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FRECUENCIA_PAGO_INTERES',:NEW.FRECUENCIA_PAGO_INTERES,NULL);  	  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_PAGO_INTERES',:NEW.ID_TCA_FRECUENCIA_PAGO_INTERES,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_INICIO_PAGO_INTERES',:NEW.FECHA_INICIO_PAGO_INTERES,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FRECUENCIA_AMORTIZACION',:NEW.FRECUENCIA_AMORTIZACION,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_FRECUENCIA_AMORTIZACION',:NEW.ID_TCA_FRECUENCIA_AMORTIZACION,NULL); 
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MORA',:NEW.MORA,NULL);  	  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_COBERTURA',:NEW.PORCENTAJE_COBERTURA,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'SE_APLICAN_RECURSOS_CONCESION',:NEW.SE_APLICAN_RECURSOS_CONCESION,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'SE_APLICAN_RECURSOS_EXTERNOS',:NEW.SE_APLICAN_RECURSOS_EXTERNOS,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TIPO_CONTRAPARTE',:NEW.TIPO_CONTRAPARTE,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MONTO_MINIMO_DESEMBOLSO',:NEW.MONTO_MINIMO_DESEMBOLSO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'MONTO_MAXIMO_DESEMBOLSO',:NEW.MONTO_MAXIMO_DESEMBOLSO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TASA_MINIMA_DESEMBOLSO',:NEW.TASA_MINIMA_DESEMBOLSO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'TASA_MAXIMA_DESEMBOLSO',:NEW.TASA_MAXIMA_DESEMBOLSO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_ESTADO_TCC',:NEW.ID_TCA_ESTADO_TCC,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_SUB_ESTADO_TCC',:NEW.ID_TCA_SUB_ESTADO_TCC,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'BAN_ESTATUS',:NEW.BAN_ESTATUS,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TERMINO_ENMENDADO',:NEW.ID_TERMINO_ENMENDADO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_ENMIENDA',:NEW.FECHA_ENMIENDA,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'CLIENTE_GESTIONA_CONTRATACION',:NEW.CLIENTE_GESTIONA_CONTRATACION,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'REQUIERE_FONDO_PRESUPUESTARIO',:NEW.REQUIERE_FONDO_PRESUPUESTARIO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'REQ_FORMALIZACION_AUTOMATICA',:NEW.REQ_FORMALIZACION_AUTOMATICA,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'REQUIERE_ORDEN_INICIO',:NEW.REQUIERE_ORDEN_INICIO,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_MODIFICACION',:NEW.PORCENTAJE_MODIFICACION,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_AVANCE',:NEW.ID_TCA_TIPO_AVANCE,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'ID_TCA_TIPO_PORCENTAJE',:NEW.ID_TCA_TIPO_PORCENTAJE,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE',:NEW.PORCENTAJE,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_INICIAL',:NEW.PORCENTAJE_INICIAL,NULL);  
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'PORCENTAJE_FINAL',:NEW.PORCENTAJE_FINAL,NULL);  		
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'LOGIN_USUARIO',:NEW.LOGIN_USUARIO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'NOMBRE_USUARIO',:NEW.NOMBRE_USUARIO,NULL);		
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'LOGIN_USUARIO_ULTIMO_CAMBIO',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'NOMBRE_USUARIO_ULTIMO_CAMBIO',:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,NULL);
		INSERT INTO TBI_TERMINO_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_termino,'FECHA_ULTIMO_CAMBIO',:NEW.FECHA_ULTIMO_CAMBIO,NULL);
	END IF;
	
EXCEPTION
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SUBSTR(SQLERRM,1,250);
		
		
		DBMS_OUTPUT.put_line('Error al insertar en la tabla de bitácora de término');
		DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
		DBMS_OUTPUT.put_line(err_msg);
		
        INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','TERMINO_INS_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
		COMMIT;
	
END;