
-- SE MODIFICA LA VISTA VTA_TRAZABILIDAD_OPERACION, PARA INCORPORAR LOS NUEVOS CAMBIOS DE TBI_PROCESO_OPERACION, EN LA QUE SE REGISTRA EL NUM DE INSTANCIA DE PROCESO TANTO EN EL PROCESO COMO EN LAS TAREAS BPM.

CREATE OR REPLACE VIEW VTA_TRAZABILIDAD_OPERACION AS 
	SELECT INICIO.ID_OPERACION AS ID_OPERACION,
		INICIO.NOMBRE_OPERACION AS NOMBRE_OPERACION,
		INICIO.ID_PROCESO AS ID_PROCESO,
        INICIO.INSTANCIA_PROCESO AS INSTANCIA_PROCESO,
		TPB.DESCRIPCION AS DESCRIPCION_PROCESO,
		INICIO.FECHA_REGISTRO AS FECHA_INICIO,
		INICIO.USUARIO AS USUARIO_INICIA,
		FIN.FECHA_REGISTRO AS FECHA_FIN,
		FIN.USUARIO AS USUARIO_FIN,
		FIN.TIEMPO_PROCESO AS TIEMPO_PROCESO
		FROM (				
                (
                    -- Recupera los registros que hayan generado tareas con el num. de instancia
                    SELECT TPO.ID, TPO.ID_OPERACION, TPO.NOMBRE_OPERACION, TPO.ID_PROCESO, TPO.FECHA_REGISTRO, TPO.USUARIO, TPO.INSTANCIA_PROCESO  FROM FENIX.TBI_PROCESO_OPERACION TPO
                    INNER JOIN FENIX.TCA_PROCESO_BPM TPB ON(TPO.ID_PROCESO=TPB.ID)
                    WHERE BAN_ES_PROCESO=1 AND BAN_ES_FIN_ACTIVIDAD=0				
                    AND ((SELECT COUNT(T1.INSTANCIA_PROCESO) FROM FENIX.TBI_PROCESO_OPERACION T1 WHERE T1.BAN_ES_PROCESO=0 AND T1.INSTANCIA_PROCESO = TPO.INSTANCIA_PROCESO) > 0)                				
                    UNION
                    -- Recupera los registros del proceso 21, pero sin la generación de tareas, con el num. de instancia
                    SELECT TPO.ID, TPO.ID_OPERACION, TPO.NOMBRE_OPERACION, TPO.ID_PROCESO, TPO.FECHA_REGISTRO, TPO.USUARIO, TPO.INSTANCIA_PROCESO FROM FENIX.TBI_PROCESO_OPERACION TPO
                    INNER JOIN FENIX.TCA_PROCESO_BPM TPB ON(TPO.ID_PROCESO=TPB.ID)
                    WHERE BAN_ES_PROCESO=1 AND BAN_ES_FIN_ACTIVIDAD=0				
                    AND TPO.ID_PROCESO in (21)	AND TPO.INSTANCIA_PROCESO IS NOT NULL 			
                    UNION
                    -- Recupera los registros que hayan generado tareas sin el num. de instancia, exluyendo los procesos que se listaron con anterioridad del operador UNION
                    SELECT TPO.ID, TPO.ID_OPERACION, TPO.NOMBRE_OPERACION, TPO.ID_PROCESO, TPO.FECHA_REGISTRO, TPO.USUARIO, TPO.INSTANCIA_PROCESO FROM FENIX.TBI_PROCESO_OPERACION TPO
                    INNER JOIN FENIX.TCA_PROCESO_BPM TPB ON(TPO.ID_PROCESO=TPB.ID)
                    WHERE BAN_ES_PROCESO=1 AND BAN_ES_FIN_ACTIVIDAD=0		
                    AND (
                            (  --- Muestra los inicios de proceso, que no tienen num de instancia, excluyendo los procesos que se listaron con anterioridad
								ID_PROCESO IN (
									SELECT TPO.ID_PROCESO FROM DUAL
                  WHERE TPO.ID_PROCESO NOT IN (SELECT ID_PROCESO FROM TBI_PROCESO_OPERACION T2 WHERE BAN_ES_PROCESO=1 AND BAN_ES_FIN_ACTIVIDAD=0 AND T2.INSTANCIA_PROCESO IS NOT NULL)
									MINUS
									SELECT TPO2.ID_PROCESO FROM FENIX.TBI_PROCESO_OPERACION TPO2
									WHERE TPO2.BAN_ES_PROCESO=1 AND TPO2.BAN_ES_FIN_ACTIVIDAD=0 AND TPO2.ID_OPERACION = TPO.ID_OPERACION
									AND ((SELECT COUNT(T1.INSTANCIA_PROCESO) FROM FENIX.TBI_PROCESO_OPERACION T1 WHERE T1.BAN_ES_PROCESO=0 AND T1.INSTANCIA_PROCESO = TPO2.INSTANCIA_PROCESO) > 0)                				
								)
							) 
							OR
							(   -- Recupera los registros sin instancia de proceso que ya fueron cerrados
								TPO.ID IN (
									SELECT TPO2.ID_INICIO FROM FENIX.TBI_PROCESO_OPERACION TPO2
									 WHERE TPO2.BAN_ES_PROCESO=1 AND TPO2.BAN_ES_FIN_ACTIVIDAD=1 AND TPO2.ID_OPERACION = TPO.ID_OPERACION AND TPO2.INSTANCIA_PROCESO IS NULL
								)
							)
						)                    
                )							
			) INICIO
		LEFT OUTER JOIN
		(
			SELECT TPO.ID, TPO.ID_OPERACION, TPO.NOMBRE_OPERACION, TPO.ID_INICIO, TPO.FECHA_REGISTRO, TPO.TIEMPO_PROCESO, TPO.USUARIO FROM FENIX.TBI_PROCESO_OPERACION TPO
			INNER JOIN FENIX.TCA_PROCESO_BPM TPB ON(TPO.ID_PROCESO=TPB.ID)
			WHERE BAN_ES_PROCESO=1 AND BAN_ES_FIN_ACTIVIDAD=1
		) FIN
		ON(INICIO.ID=FIN.ID_INICIO)
		INNER JOIN FENIX.TCA_PROCESO_BPM TPB ON(TPB.ID=INICIO.ID_PROCESO)
        ORDER BY 3, 6;

	/