<wsdl:definitions name="ConsultarBitacoraProcesoByIdIOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoByIdIOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarBitacoraProcesoByIdIOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoByIdIOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarBitacoraProcesoByIdIOperacion_DB_plt">
    <plt:role name="ConsultarBitacoraProcesoByIdIOperacion_DB_role">
      <plt:portType name="tns:ConsultarBitacoraProcesoByIdIOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarBitacoraProcesoByIdIOperacion_DB" schemaLocation="../XSD/ConsultarBitacoraProcesoByIdIOperacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarBitacoraProcesoByIdIOperacion_DBInput_msg">
        <wsdl:part name="ConsultarBitacoraProcesoByIdIOperacion_DBInput_msg" element="db:ConsultarBitacoraProcesoByIdIOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarBitacoraProcesoByIdIOperacion_DBOutputCollection_msg">
        <wsdl:part name="ConsultarBitacoraProcesoByIdIOperacion_DBOutputCollection" element="db:ConsultarBitacoraProcesoByIdIOperacion_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarBitacoraProcesoByIdIOperacion_DB_ptt">
        <wsdl:operation name="ConsultarBitacoraProcesoByIdIOperacion_DB">
            <wsdl:input message="tns:ConsultarBitacoraProcesoByIdIOperacion_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarBitacoraProcesoByIdIOperacion_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>