<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:ConsultarProcesoBPM" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ConsultarProcesoBPM" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
              xmlns:conBPM="http://www.bcie.org/ConsultarProcesoBPMProcesoMO">
  <types>
      <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/ConsultarProcesoBPMProcesoMO"
                        schemaLocation="../../../ConsultarProcesoBPMProceso/V1/Schema/ConsultarProcesoBPMProcesoMO.xsd"/>
        </xsd:schema>
  </types>
  <message name="requestConsultarBPMmessage">
    <part name="request" element="conBPM:requestConsultarProcesoBPM"/>
  </message>
  <message name="responseConsultarBPMmessage">
    <part name="response" element="conBPM:responseConsultarProcesoBPM"/>
  </message>
  <portType name="ProcesoBPMPT">
    <operation name="ConsultatBPM">
      <input message="tns:requestConsultarBPMmessage"/>
      <output message="tns:responseConsultarBPMmessage"/>
    </operation>
  </portType>
  <binding name="ProcesoBPMPT12Bnd" type="tns:ProcesoBPMPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultatBPM">
      <soap12:operation style="document" soapAction="urn:ConsultarProcesoBPM/ConsultatBPM"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>