<wsdl:definitions name="caseTwoColorTranslation" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoColorTranslation" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoColorTranslation" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoColorTranslation" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="caseTwoColorTranslation_plt">
    <plt:role name="caseTwoColorTranslation_role">
      <plt:portType name="tns:caseTwoColorTranslation_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoColorTranslation" schemaLocation="caseTwoColorTranslation_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="caseTwoColorTranslationSelect_inputParameters">
        <wsdl:part name="caseTwoColorTranslationSelect_inputParameters" element="top:caseTwoColorTranslationSelect_idC2_appCodeC2_catDefC2_parnIdC2_parnCatIdC2InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmItemsDiffsCollection_msg">
        <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
    </wsdl:message>
    <wsdl:portType name="caseTwoColorTranslation_ptt">
        <wsdl:operation name="caseTwoColorTranslationSelect">
            <wsdl:input message="tns:caseTwoColorTranslationSelect_inputParameters"/>
            <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>