<wsdl:definitions name="caseThreeColorTranslation" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeColorTranslation" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeColorTranslation" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseThreeColorTranslation" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="caseThreeColorTranslation_plt">
    <plt:role name="caseThreeColorTranslation_role">
      <plt:portType name="tns:caseThreeColorTranslation_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseThreeColorTranslation" schemaLocation="caseThreeColorTranslation_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="caseThreeColorTranslationSelect_inputParameters">
        <wsdl:part name="caseThreeColorTranslationSelect_inputParameters" element="top:caseThreeColorTranslationSelect_idC3_appCodeC3_catDefC3_parIdC3_parCatIdC3_targetAppCodeC3InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmItemsDiffsCollection_msg">
        <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
    </wsdl:message>
    <wsdl:portType name="caseThreeColorTranslation_ptt">
        <wsdl:operation name="caseThreeColorTranslationSelect">
            <wsdl:input message="tns:caseThreeColorTranslationSelect_inputParameters"/>
            <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>