<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeColorTranslation" name="caseThreeColorTranslation-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="caseThreeColorTranslation.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeColorTranslation"/>
    <wsdl:binding name="caseThreeColorTranslation_ptt-binding" type="cas:caseThreeColorTranslation_ptt" xmlns:cas="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseThreeColorTranslation">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="caseThreeColorTranslationSelect">
            <soap:operation soapAction="caseThreeColorTranslationSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>