<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpASNINWrite" name="ftpASNINWrite-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ftpASNINWrite.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpASNINWrite"/>
    <wsdl:binding name="Put_ptt-binding" type="ftp:Put_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpASNINWrite">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Put">
            <soap:operation soapAction="Put"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>