<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpMasterEDIA" name="ftpMasterEDIA-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ftpMasterEDIA.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpMasterEDIA"/>
    <wsdl:binding name="Get_ptt-binding" type="ftp:Get_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpMasterEDIA">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Get">
            <soap:operation soapAction="Get"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>