<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpService" name="ftpService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ftpService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpService"/>
    <wsdl:binding name="FileListing_ptt-binding" type="ftp:FileListing_ptt" xmlns:ftp="http://xmlns.oracle.com/pcbpel/adapter/ftp/ASNINBUS/ASNINFTPAPP/ftpService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="FileListing">
            <soap:operation soapAction="FileListing"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>