<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINFTPAPP/PKG_MDM_ASNIN" name="PKG_MDM_ASNIN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PKG_MDM_ASNIN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINFTPAPP/PKG_MDM_ASNIN"/>
    <wsdl:binding name="PKG_MDM_ASNIN_ptt-binding" type="pkg:PKG_MDM_ASNIN_ptt" xmlns:pkg="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINFTPAPP/PKG_MDM_ASNIN">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="PKG_MDM_ASNIN">
            <soap:operation soapAction="PKG_MDM_ASNIN"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>