<wsdl:definitions name="PKG_MDM_ASNIN" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINFTPAPP/PKG_MDM_ASNIN" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINFTPAPP/PKG_MDM_ASNIN" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/PKG_MDM_ASNIN" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="PKG_MDM_ASNIN_plt">
    <plt:role name="PKG_MDM_ASNIN_role">
      <plt:portType name="tns:PKG_MDM_ASNIN_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/PKG_MDM_ASNIN" schemaLocation="PKG_MDM_ASNIN_sp.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="PKG_MDM_ASNIN_ptt">
        <wsdl:operation name="PKG_MDM_ASNIN">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>