<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarParametrosEnBitacoraProceso_DB" name="ConsultarParametrosEnBitacoraProceso_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarParametrosEnBitacoraProceso_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarParametrosEnBitacoraProceso_DB"/>
    <wsdl:binding name="ConsultarParametrosEnBitacoraProceso_DB_ptt-binding" type="con:ConsultarParametrosEnBitacoraProceso_DB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarParametrosEnBitacoraProceso_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarParametrosEnBitacoraProceso_DB">
            <soap:operation soapAction="ConsultarParametrosEnBitacoraProceso_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>