<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.agarcia.mx/EnterpriseObjects/Inventory" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Inventory/InventoryEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessInventoryEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Inventory"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Inventory/InventoryEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessInventoryEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Inventory"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU OCT 15 16:21:53 CDT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InstanceID"/>
   <xsl:param name="TargetName"/>
   <xsl:param name="Interface"/>
   <xsl:template match="/">
      <ns0:ProcessInventoryEBM>
         <ns0:Header>
            <com:TrackingID>
               <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:Header/com:TrackingID"/>
            </com:TrackingID>
            <com:InstanceID>
               <xsl:value-of select="$InstanceID"/>
            </com:InstanceID>
            <com:User>
               <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:Header/com:User"/>
            </com:User>
            <com:SourceID>
               <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:Header/com:SourceID"/>
            </com:SourceID>
            <com:Target>
               <com:Applications>
                  <com:Name>
                     <xsl:value-of select="$TargetName"/>
                  </com:Name>
               </com:Applications>
            </com:Target>
            <com:Operation>
               <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:Header/com:Operation"/>
            </com:Operation>
            <com:Interface>
               <xsl:value-of select="$Interface"/>
            </com:Interface>
         </ns0:Header>
         <ns0:DataArea>
            <ns0:ProcessInventory>
               <com:Identification>
                  <com:ID>
                     <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:ProcessInventory/com:Identification/com:ID"/>
                  </com:ID>
               </com:Identification>
               <ns0:DueDate>
                  <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:ProcessInventory/ns0:DueDate"/>
               </ns0:DueDate>
               <ns0:ShipFromPartyReference>
                  <com:LocationId>
                     <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:ProcessInventory/ns0:ShipFromPartyReference/com:LocationId"/>
                  </com:LocationId>
               </ns0:ShipFromPartyReference>
               <xsl:for-each select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:ProcessInventory/ns0:InventoryLine">
                  <ns0:InventoryLine>
                     <com:Identification>
                        <com:ID>
                           <xsl:value-of select="com:Identification/com:ID"/>
                        </com:ID>
                     </com:Identification>
                     <ns0:Quantity>
                        <xsl:value-of select="ns0:Quantity"/>
                     </ns0:Quantity>
                  </ns0:InventoryLine>
               </xsl:for-each>
            </ns0:ProcessInventory>
            <ns0:InventoryHistoryRecord>
               <com:CreationDate>
                  <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:InventoryHistoryRecord/com:CreationDate"/>
               </com:CreationDate>
               <com:CreatedBy>
                  <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:InventoryHistoryRecord/com:CreatedBy"/>
               </com:CreatedBy>
               <com:LastUpdateDate>
                  <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:InventoryHistoryRecord/com:LastUpdateDate"/>
               </com:LastUpdateDate>
               <com:LastUpdatedBy>
                  <xsl:value-of select="/ns0:ProcessInventoryEBM/ns0:DataArea/ns0:InventoryHistoryRecord/com:LastUpdatedBy"/>
               </com:LastUpdatedBy>
            </ns0:InventoryHistoryRecord>
         </ns0:DataArea>
      </ns0:ProcessInventoryEBM>
   </xsl:template>
</xsl:stylesheet>