<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_PublicacionNoObjecion/ADAPTADORES/Validar_Condiciones_Desembolso" name="Validar_Condiciones_Desembolso-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Validar_Condiciones_Desembolso.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_PublicacionNoObjecion/ADAPTADORES/Validar_Condiciones_Desembolso"/>
    <wsdl:binding name="Validar_Condiciones_Desembolso_ptt-binding" type="val:Validar_Condiciones_Desembolso_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_PublicacionNoObjecion/ADAPTADORES/Validar_Condiciones_Desembolso">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Validar_Condiciones_Desembolso">
            <soap:operation soapAction="Validar_Condiciones_Desembolso"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>