<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/AplicarFactibilidadSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/AplicarFactibilidadSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/DesembolsoMO"
    >
    <plnk:partnerLinkType name="AplicarFactibilidad">
        <plnk:role name="AplicarFactibilidad_PT" portType="tns:AplicarFactibilidad_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/AplicarFactibilidadSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/AplicarFactibilidadSOR.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
