<wsdl:definitions name="EliminarLineaCreditoByIdContrato" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCreditoByIdContrato" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCreditoByIdContrato" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarLineaCreditoByIdContrato" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarLineaCreditoByIdContrato_plt">
    <plt:role name="EliminarLineaCreditoByIdContrato_role">
      <plt:portType name="tns:EliminarLineaCreditoByIdContrato_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarLineaCreditoByIdContrato" schemaLocation="../XSD/EliminarLineaCreditoByIdContrato.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarLineaCreditoByIdContratoInput_msg">
        <wsdl:part name="EliminarLineaCreditoByIdContratoInput_msg" element="db:EliminarLineaCreditoByIdContratoInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarLineaCreditoByIdContrato_ptt">
        <wsdl:operation name="EliminarLineaCreditoByIdContrato">
            <wsdl:input message="tns:EliminarLineaCreditoByIdContratoInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>