<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="LinkGroupDiffProcess" targetNamespace="http://xmlns.oracle.com/RetailOperMK/LinkGroupDiffProcess/LinkGroupDiffProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/RetailOperMK/LinkGroupDiffProcess/LinkGroupDiffProcess" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/LinkGroupDiffEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://mx.agarcia.ea/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvcWSD">
   <plnk:partnerLinkType name="LinkGroupDiffProcess">
      <plnk:role name="LinkGroupDiffProcessProvider" portType="client:LinkGroupDiffProcess"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvcWSD" location="http://uat-osb.agarcia.com.mx:7004/RetailOperations/Make/ProductDevelopment/ItemCatalogTaskSvc/PS/ItemCatalogTaskPXY?WSDL"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/LinkGroupDiffEntity" schemaLocation="../Schemas/LinkGroupDiffEntitySchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="LinkGroupDiffProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:linkGroupDiffRequest"/>
   </wsdl:message>
   <wsdl:message name="LinkGroupDiffProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:linkGroupDiffResponse"/>
   </wsdl:message>
   <wsdl:portType name="LinkGroupDiffProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:LinkGroupDiffProcessRequestMessage"/>
         <wsdl:output message="client:LinkGroupDiffProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
