<wsdl:definitions name="CreateSizeProcess" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeProcess/v1.0" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeEntity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plnk:partnerLinkType name="CreateSizeProcess">
    <plnk:role name="CreateSizeProcessProvider" portType="client:CreateSizeProcess"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/CreateSizeEntity" schemaLocation="../Schemas/CreateSizeEntitySchema.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="CreateSizeProcessRequestMessage">
    <wsdl:part name="payload" element="ns1:createSizeRequest"/>
  </wsdl:message>
  <wsdl:message name="CreateSizeProcessResponseMessage">
    <wsdl:part name="payload" element="ns1:createSizeResponse"/>
  </wsdl:message>
  <wsdl:portType name="CreateSizeProcess">
    <wsdl:operation name="create">
      <wsdl:input message="client:CreateSizeProcessRequestMessage"/>
      <wsdl:output message="client:CreateSizeProcessResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CreateSizeProcessBinding" type="client:CreateSizeProcess">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="create">
      <soap:operation style="document" soapAction="create"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="createsizeprocess_client_ep">
    <wsdl:port name="CreateSizeProcess_pt" binding="client:CreateSizeProcessBinding">
      <soap:address location="http://uat-soa.agarcia.com.mx:7004/soa-infra/services/RetailOperMK/CreateSizeProcess/createsizeprocess_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>