<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/DocumentoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/DocumentoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:docMO="http://www.bcie.org/DocumentoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/DocumentoMO" schemaLocation="../../Schema/DocumentoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="EliminarDocumentoFenixRequestMessage">
    <part name="EliminarDocumentoFenixRequest" element="docMO:EliminarDocumentoFenixRequest"/>
  </message>
  <message name="EliminarDocumentoFenixResponseMessage">
    <part name="EliminarDocumentoFenixResponse" element="docMO:EliminarDocumentoFenixResponse"/>
  </message>
  <portType name="EliminarDocumentoFenix">
    <operation name="eliminarDocumentoFenix">
      <input message="tns:EliminarDocumentoFenixRequestMessage"/>
      <output message="tns:EliminarDocumentoFenixResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarDocumentoFenix12Bnd" type="tns:EliminarDocumentoFenix">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarDocumentoFenix">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/DocumentoService/eliminarDocumentoFenix"/>
      <input>
        <soap12:body use="literal" parts="EliminarDocumentoFenixRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="EliminarDocumentoFenixResponse"/>
      </output>
    </operation>
  </binding>
</definitions>