<wsdl:definitions name="ActualizarAprobacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarAprobacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarAprobacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarAprobacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarAprobacion_DB_plt">
    <plt:role name="ActualizarAprobacion_DB_role">
      <plt:portType name="tns:ActualizarAprobacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarAprobacion_DB"
                schemaLocation="../../../../DominioOperacion/Aprobacion/ActualizarAprobacion/XSD/ActualizarAprobacion_DB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="AprobacionCollection_msg">
        <wsdl:part name="AprobacionCollection" element="top:AprobacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarAprobacion_DB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:AprobacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>