<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarAprobacion_DB" name="ActualizarAprobacion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../../../../DominioOperacion/Aprobacion/ActualizarAprobacion/WSDL/ActualizarAprobacion_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarAprobacion_DB"/>
    <wsdl:binding name="ActualizarAprobacion_DB_ptt-binding" type="act:ActualizarAprobacion_DB_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarAprobacion_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="update">
            <soap:operation soapAction="update"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>