<wsdl:definitions name="ActualizarDetalleEnmienda_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarDetalleEnmienda_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarDetalleEnmienda_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarDetalleEnmienda_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarDetalleEnmienda_DB_plt">
    <plt:role name="ActualizarDetalleEnmienda_DB_role">
      <plt:portType name="tns:ActualizarDetalleEnmienda_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarDetalleEnmienda_DB" schemaLocation="../XSD/ActualizarDetalleEnmienda_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarDetalleEnmienda_DBInput_msg">
        <wsdl:part name="ActualizarDetalleEnmienda_DBInput_msg" element="db:ActualizarDetalleEnmienda_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarDetalleEnmienda_DB_ptt">
        <wsdl:operation name="ActualizarDetalleEnmienda_DB">
            <wsdl:input message="tns:ActualizarDetalleEnmienda_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>