<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="GetDiffDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RetailOperMK/LinkGroupDiffProcess/GetDiffDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RetailOperMK/LinkGroupDiffProcess/GetDiffDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetDiffDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="GetDiffDB_plt">
      <plt:role name="GetDiffDB_role">
         <plt:portType name="tns:GetDiffDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetDiffDB" schemaLocation="../Schemas/GetDiffDB_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="GetDiffDBSelect_inputParameters">
      <wsdl:part name="GetDiffDBSelect_inputParameters" element="top:GetDiffDBSelect_vId_vCatDef_vParentId_vPrimaryId_vPrimAppcode_vAppCode_vParentCatIdInputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmItemsDiffsCollection_msg">
      <wsdl:part name="MdmItemsDiffsCollection" element="top:MdmItemsDiffsCollection"/>
   </wsdl:message>
   <wsdl:portType name="GetDiffDB_ptt">
      <wsdl:operation name="GetDiffDBSelect">
         <wsdl:input message="tns:GetDiffDBSelect_inputParameters"/>
         <wsdl:output message="tns:MdmItemsDiffsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
