<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ContratoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ContratoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:conMO="http://www.bcie.org/ContratoMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ContratoMO"
                  schemaLocation="../../Schema/ContratoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarContratoRequestMessage">
    <part name="request" element="conMO:ConsultarContratoByIdOperacionRequest"/>
  </message>
  <message name="ConsultarContratoResponseMessage">
    <part name="response" element="conMO:ConsultarContratoByIdOperacionResponse"/>
  </message>
  <portType name="ContratoPT">
    <operation name="consultarContrato">
      <input message="tns:ConsultarContratoRequestMessage"/>
      <output message="tns:ConsultarContratoResponseMessage"/>
    </operation>
  </portType>
  <binding name="Contrato12Bnd" type="tns:ContratoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarContrato">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ContratoService/consultarContrato"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>