<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:tns="http://xmlns.banesco.com/eopt/PersonAcctInfoInq_V1.0"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://www.temenos.com/T24/ofs/Response"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon"
                xmlns:ns1="http://www.temenos.com/T24/ofs/BPAENQACCOUNTPNType"
                xmlns:ns7="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/BPAENQACCOUNTPN_V1.0/EnquiryaccountNaturalesConsultaCuentasNaturalesResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="BPAENQACCOUNTPNResponse"
                                       namespace="http://www.temenos.com/T24/ofs/Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/PersonAcctInfoInq/PersonAcctInfoInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PersonAcctInfoInqRs"
                                       namespace="http://xmlns.banesco.com/eopt/PersonAcctInfoInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED MAY 02 10:40:13 GMT-05:00 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:include href="../../../../Commons/xslt/Template/TemplateServiceUtil.xsl"/>
  <xsl:variable name="statusCode"
                select='DVMFunctions:lookupValue ("Commons/dvm/StatusMappingBcknd", "T24", /ns0:BPAENQACCOUNTPNResponse/ResponseCommon/Status, "CNCODE", "M0006" )'/>
  <xsl:template match="/">
    <tns:PersonAcctInfoInqRs>
      <xsl:if test='$statusCode = "M0000" and count(/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN)'>
        <tns:Acct>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PRODUCT/text()">
            <eoAcct:AcctSubtype>
              <ns5:Cod>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PRODUCT"/>
              </ns5:Cod>
            </eoAcct:AcctSubtype>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/ACCTTYPE/text()">
            <eoAcct:AcctType>
              <ns5:Cod>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/ACCTTYPE"/>
              </ns5:Cod>
            </eoAcct:AcctType>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/EsclubBanesco/text()">
            <eoAcct:ClubBanesco>
              <xsl:call-template name="Boolean_Regex">
                <xsl:with-param name="operation">INQ</xsl:with-param>
                <xsl:with-param name="parametro">
                     <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/EsclubBanesco"></xsl:value-of>
                </xsl:with-param>
              </xsl:call-template>
            </eoAcct:ClubBanesco>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/CURRENCY/text()">
            <eoAcct:CurCode>
              <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/CURRENCY"/>
            </eoAcct:CurCode>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTMOBILIZATION/text()">
            <eoAcct:MovType>
              <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTMOBILIZATION"/>
            </eoAcct:MovType>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/TYPEACTSIB/text()">
            <eoAcct:SIBActivityType>
              <ns5:Cod>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/TYPEACTSIB"/>
              </ns5:Cod>
            </eoAcct:SIBActivityType>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTSUBPRODUCT/text()">
            <eoAcct:SubCategory>
              <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTSUBPRODUCT"/>
            </eoAcct:SubCategory>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PRODUCTVARIATION/text()">
            <eoAcct:Variation>
              <ns5:Cod>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PRODUCTVARIATION"/>
              </ns5:Cod>
            </eoAcct:Variation>
          </xsl:if>
          <eoAcct:AcctTransfer>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SRTRNSFEXTRP/text()">
              <eoAcct:AllowsIntTransf>
                <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SRTRNSFEXTRP, 'VALUE', '2' )"/>
              </eoAcct:AllowsIntTransf>
            </xsl:if>
            <!-- Multivalor T24 -->
            <xsl:for-each select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType">
              <xsl:if test="TRNSFCOUNTRYINT/text()">
                <eoAcct:Country>
                  <ns5:CountryCode>
                    <xsl:value-of select="TRNSFCOUNTRYINT"/>
                  </ns5:CountryCode>
                </eoAcct:Country>
              </xsl:if>
            </xsl:for-each>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/TRANSFERTYPE/text()">
              <eoAcct:TransfNature>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/TRANSFERTYPE"/>
              </eoAcct:TransfNature>
            </xsl:if>
          </eoAcct:AcctTransfer>
          <xsl:for-each select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType">
            <eoAcct:ChkBook>
              <xsl:if test="NombreChequera1/text()">
                <ns8:FirstHolder>
                  <xsl:value-of select="NombreChequera1"/>
                </ns8:FirstHolder>
              </xsl:if>
              <xsl:if test="Relacion/text()">
                <ns8:HolderCondition>
                  <xsl:value-of select="Relacion"/>
                </ns8:HolderCondition>
              </xsl:if>
              <xsl:if test="NombreChequera2/text()">
                <ns8:SecondHolder>
                  <xsl:value-of select="NombreChequera2"/>
                </ns8:SecondHolder>
              </xsl:if>
              <!-- Multivalor -->
              <xsl:if test="CHQTYPE/text()">
                <ns8:Type>
                  <xsl:value-of select="CHQTYPE"/>
                </ns8:Type>
              </xsl:if>
            </eoAcct:ChkBook>
          </xsl:for-each>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/ID/text()">
            <eoAcct:AcctKey>
              <eoAcct:AcctId>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/ID"/>
              </eoAcct:AcctId>
            </eoAcct:AcctKey>
          </xsl:if>
          <!-- Multivalor T24 -->
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTSTACCT/text()">
            <eoAcct:AcctStatus>
              <eoAcct:AcctStatusCode>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTSTACCT"/>
              </eoAcct:AcctStatusCode>
            </eoAcct:AcctStatus>
          </xsl:if>
          <xsl:for-each select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType">
            <eoAcct:AcctMember>
              <xsl:if test="CUSTOMER/text()">
                <eoAcct:PartyKey>
                  <eoPar:PartyId>
                    <xsl:value-of select="CUSTOMER"/>
                  </eoPar:PartyId>
                  <eoPar:PartyType>
                    <xsl:value-of select="TYPEOFPERSON"/>
                  </eoPar:PartyType>
                </eoAcct:PartyKey>
              </xsl:if>
              <xsl:if test="CUSTOMERROLE/text()">
                <eoAcct:PartyRole>
                  <ns5:Cod>
                    <xsl:value-of select="CUSTOMERROLE"/>
                  </ns5:Cod>
                </eoAcct:PartyRole>
              </xsl:if>
            </eoAcct:AcctMember>
          </xsl:for-each>
          <eoAcct:AcctProfile>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTOTING/text()">
              <eoAcct:AvgBalance>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTOTING"/>
                </ns5:Amt>
              </eoAcct:AvgBalance>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTOTPMD/text()">
              <eoAcct:AvgDepositAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTOTPMD"/>
                </ns5:Amt>
              </eoAcct:AvgDepositAmt>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PRECMDCH/text()">
              <eoAcct:PercentageDepChk>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PRECMDCH"/>
              </eoAcct:PercentageDepChk>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTDEPCASH/text() and /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NODEPCASH/text()">
              <eoAcct:AcctProfileTrn>
                <eoAcct:Amt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTDEPCASH"/>
                  </ns5:Amt>
                </eoAcct:Amt>
                <eoAcct:Count>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NODEPCASH"/>
                </eoAcct:Count>
                <eoAcct:TrnType>CashDeposit</eoAcct:TrnType>
              </eoAcct:AcctProfileTrn>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/DEPOTHERS/text() and /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NODEPOTH/text()">
              <eoAcct:AcctProfileTrn>
                <eoAcct:Amt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/DEPOTHERS"/>
                  </ns5:Amt>
                </eoAcct:Amt>
                <eoAcct:Count>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NODEPOTH"/>
                </eoAcct:Count>
                <eoAcct:TrnType>ChkDeposit</eoAcct:TrnType>
              </eoAcct:AcctProfileTrn>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTWTWCASH/text() and /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOWTWLCASH/text()">
              <eoAcct:AcctProfileTrn>
                <eoAcct:Amt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTWTWCASH"/>
                  </ns5:Amt>
                </eoAcct:Amt>
                <eoAcct:Count>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOWTWLCASH"/>
                </eoAcct:Count>
                <eoAcct:TrnType>CashWithdrawal</eoAcct:TrnType>
              </eoAcct:AcctProfileTrn>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTPAYCHQ/text() and /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOPAYCHQ/text()">
              <eoAcct:AcctProfileTrn>
                <eoAcct:Amt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTPAYCHQ"/>
                  </ns5:Amt>
                </eoAcct:Amt>
                <eoAcct:Count>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOPAYCHQ"/>
                </eoAcct:Count>
                <eoAcct:TrnType>ChkPay</eoAcct:TrnType>
              </eoAcct:AcctProfileTrn>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTRNSFSND/text() and /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOTRNSFSND/text()">
              <eoAcct:AcctProfileTrn>
                <eoAcct:Amt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTRNSFSND"/>
                  </ns5:Amt>
                </eoAcct:Amt>
                <eoAcct:Count>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOTRNSFSND"/>
                </eoAcct:Count>
                <eoAcct:TrnType>LocalTransfSend</eoAcct:TrnType>
              </eoAcct:AcctProfileTrn>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTRNSFREC/text() and /ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOTRNSFREC/text()">
              <eoAcct:AcctProfileTrn>
                <eoAcct:Amt>
                  <ns5:Amt>
                    <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTTRNSFREC"/>
                  </ns5:Amt>
                </eoAcct:Amt>
                <eoAcct:Count>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/NOTRNSFREC"/>
                </eoAcct:Count>
                <eoAcct:TrnType>LocalTransfRec</eoAcct:TrnType>
              </eoAcct:AcctProfileTrn>
            </xsl:if>
          </eoAcct:AcctProfile>
          <eoAcct:AcctOpeningInfo>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/USEACCTPA/text()">
              <eoAcct:AcctUse>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/USEACCTPA"/>
              </eoAcct:AcctUse>
            </xsl:if>
            <!-- Multivalor T24 -->
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTBUSUNIT/text()">
              <eoAcct:BusinessUnit>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTBUSUNIT"/>
              </eoAcct:BusinessUnit>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/FUNDSOUACCPA/text()">
              <eoAcct:FundsOrigin>
                <ns5:Cod>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/FUNDSOUACCPA"/>
                </ns5:Cod>
              </eoAcct:FundsOrigin>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTGOAL/text()">
              <eoAcct:GoalAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTGOAL"/>
                </ns5:Amt>
              </eoAcct:GoalAmt>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTOPENNING/text()">
              <eoAcct:InitialAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/AMTOPENNING"/>
                </ns5:Amt>
              </eoAcct:InitialAmt>
            </xsl:if>
            <!-- Multivalor T24 -->
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/EFFECTIVEDATE/text()">
              <eoAcct:OpenDt>
                <xsl:value-of select="concat(substring(/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/EFFECTIVEDATE, 1, 4), '-', substring(/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/EFFECTIVEDATE, 5, 2), '-', substring(/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/EFFECTIVEDATE, 7, 2))"/>
              </eoAcct:OpenDt>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/OPENMODEPA/text()">
              <eoAcct:OpenMode>
                <ns5:Cod>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/OPENMODEPA"/>
                </ns5:Cod>
              </eoAcct:OpenMode>
            </xsl:if>
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PROPACCT/text()">
              <eoAcct:Purpose>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/PROPACCT"/>
              </eoAcct:Purpose>
            </xsl:if>
            <!-- Multivalor T24 -->
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/REASONSERV/text()">
              <eoAcct:RqReason>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/REASONSERV"/>
              </eoAcct:RqReason>
            </xsl:if>
            <!-- Multivalor T24 -->
            <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTSALEOFFICER/text()">
              <eoAcct:SaleOfficer>
                <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/LTSALEOFFICER"/>
              </eoAcct:SaleOfficer>
            </xsl:if>
          </eoAcct:AcctOpeningInfo>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/IDCARDISSUE/text()">
            <eoAcct:AcctCard>
              <eoAcct:CardKey>
                <ns2:CardNum>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/IDCARDISSUE"/>
                </ns2:CardNum>
              </eoAcct:CardKey>
            </eoAcct:AcctCard>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SaldoDisponible/text()">
            <eoAcct:AcctBal>
              <eoAcct:BalType>AvailBalance</eoAcct:BalType>
              <eoAcct:CurAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SaldoDisponible"/>
                </ns5:Amt>
              </eoAcct:CurAmt>
            </eoAcct:AcctBal>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SaldoActual/text()">
            <eoAcct:AcctBal>
              <eoAcct:BalType>Balance</eoAcct:BalType>
              <eoAcct:CurAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SaldoActual"/>
                </ns5:Amt>
              </eoAcct:CurAmt>
            </eoAcct:AcctBal>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SaldoNeto/text()">
            <eoAcct:AcctBal>
              <eoAcct:BalType>NetBalance</eoAcct:BalType>
              <eoAcct:CurAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/SaldoNeto"/>
                </ns5:Amt>
              </eoAcct:CurAmt>
            </eoAcct:AcctBal>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/Limit/text()">
            <eoAcct:AcctBal>
              <eoAcct:BalType>OverdrtLimit</eoAcct:BalType>
              <eoAcct:CurAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/Limit"/>
                </ns5:Amt>
              </eoAcct:CurAmt>
            </eoAcct:AcctBal>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/Saldodetrabajo/text()">
            <eoAcct:AcctBal>
              <eoAcct:BalType>WorkingBalance</eoAcct:BalType>
              <eoAcct:CurAmt>
                <ns5:Amt>
                  <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/BPAENQACCOUNTPN/gBPAENQACCOUNTPNDetailType/mBPAENQACCOUNTPNDetailType/Saldodetrabajo"/>
                </ns5:Amt>
              </eoAcct:CurAmt>
            </eoAcct:AcctBal>
          </xsl:if>
        </tns:Acct>
      </xsl:if>
      <tns:Status>
        <eoStatus:StatusCode>
          <xsl:value-of select="$statusCode"/>
        </eoStatus:StatusCode>
        <eoStatus:StatusDesc>
          <xsl:value-of select='DVMFunctions:lookupValue ("Commons/dvm/StatusMappingBcknd", "T24", /ns0:BPAENQACCOUNTPNResponse/ResponseCommon/Status, "CNDESC", "FALLO EN LA OPERACION" )'/>
        </eoStatus:StatusDesc>
        <eoStatus:AdditionalStatus>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/ResponseCommon/Status/text()">
            <eoStatus:StatusCode>
              <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/ResponseCommon/Status"/>
            </eoStatus:StatusCode>
          </xsl:if>
          <xsl:if test="/ns0:BPAENQACCOUNTPNResponse/ResponseCommon/Message/text()">
            <eoStatus:StatusDesc>
              <xsl:value-of select="/ns0:BPAENQACCOUNTPNResponse/ResponseCommon/Message"/>
            </eoStatus:StatusDesc>
          </xsl:if>
        </eoStatus:AdditionalStatus>
      </tns:Status>
    </tns:PersonAcctInfoInqRs>
  </xsl:template>
</xsl:stylesheet>
