<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="urn:DefaultNamespace" 
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:apachesoap="http://xml.apache.org/xml-soap" 
             xmlns:impl="urn:DefaultNamespace" 
             xmlns:intf="urn:DefaultNamespace" 
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<message name="CREARRequest">
    <part name="CODIGONEGOCIACION" type="xsd:int"/>
    <part name="SUBJECT" type="xsd:string"/>
    <part name="BODY" type="xsd:string"/>
    <part name="MONTO" type="xsd:double"/>
    <part name="SOLICITANTE" type="xsd:string"/>
    <part name="PAIS" type="xsd:string"/>
    <part name="TYPESTR" type="xsd:string"/>
    <part name="CODIGO_ETAPA_INICAL" type="xsd:double"/>
</message>
<message name="CREARResponse">
    <part name="CREARReturn" type="xsd:string"/>
</message>
<portType name="AprobacionInterface">
    <operation name="CREAR" parameterOrder="CODIGONEGOCIACION SUBJECT BODY MONTO SOLICITANTE PAIS TYPESTR CODIGO_ETAPA_INICAL">
      <input message="impl:CREARRequest" name="CREARRequest"/>
      <output message="impl:CREARResponse" name="CREARResponse"/>
    </operation>
</portType>
<binding name="DominoSoapBinding" type="impl:AprobacionInterface"><wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CREAR"><wsdlsoap:operation soapAction=""/>
      <input name="CREARRequest">
              <wsdlsoap:body namespace="urn:DefaultNamespace" use="literal"/>
      </input>
      <output name="CREARResponse">
              <wsdlsoap:body namespace="urn:DefaultNamespace" use="literal"/>
      </output>
    </operation>
</binding>
<service name="AprobacionInterfaceService">
    <port binding="impl:DominoSoapBinding" name="Domino">
      <wsdlsoap:address location="http://notes.bcie.org/ws.nsf/AprobacionDEV"/>
    </port>
</service>
</definitions>