<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:tns="http://xmlns.banesco.com/eopt/CardCrInfoInq_V1.0"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://xmlns.banesco.com/appopt/T24CardCrAppSvc/CardCrInfoInq_V1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
                xmlns:ns4="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:eoBank="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:eoCard="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns2="http://xmlns.banesco.com/eo/Common_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/T24CardCr/CardCrInfoInq/CardCrInfoInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="CardCrInfoInqRq"
                                       namespace="http://xmlns.banesco.com/appopt/T24CardCrAppSvc/CardCrInfoInq_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardCr/CardCrInfoInq/CardCrInfoInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="CardCrInfoInqRq"
                                       namespace="http://xmlns.banesco.com/eopt/CardCrInfoInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [WED SEP 05 16:46:41 CDT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CardCrInfoInqRq>
      <xsl:if test="/ns0:CardCrInfoInqRq/ns0:CardKey">
        <tns:CardKey>
          <xsl:if test="/ns0:CardCrInfoInqRq/ns0:CardKey/ns0:CardNum">
            <eoCard:CardNum>
              <xsl:value-of select="/ns0:CardCrInfoInqRq/ns0:CardKey/ns0:CardNum"/>
            </eoCard:CardNum>
          </xsl:if>
        </tns:CardKey>
      </xsl:if>
      <xsl:if test="/ns0:CardCrInfoInqRq/ns0:FIData">
        <tns:FIData>
          <xsl:if test="/ns0:CardCrInfoInqRq/ns0:FIData/ns0:FIIdent">
            <eoBank:FIIdent>
              <xsl:value-of select="/ns0:CardCrInfoInqRq/ns0:FIData/ns0:FIIdent"/>
            </eoBank:FIIdent>
          </xsl:if>
          <xsl:if test="/ns0:CardCrInfoInqRq/ns0:FIData/ns0:Agency">
            <eoBank:Agency>
              <xsl:if test="/ns0:CardCrInfoInqRq/ns0:FIData/ns0:Agency/ns0:AgencyIdent">
                <eoBank:AgencyIdent>
                  <xsl:value-of select="/ns0:CardCrInfoInqRq/ns0:FIData/ns0:Agency/ns0:AgencyIdent"/>
                </eoBank:AgencyIdent>
              </xsl:if>
            </eoBank:Agency>
          </xsl:if>
        </tns:FIData>
      </xsl:if>
      <xsl:if test="/ns0:CardCrInfoInqRq/ns0:PartyKey">
        <tns:PartyKey>
          <xsl:if test="/ns0:CardCrInfoInqRq/ns0:PartyKey/ns0:IssuedIdentType">
            <eoPar:IssuedIdentType>
              <xsl:value-of select="/ns0:CardCrInfoInqRq/ns0:PartyKey/ns0:IssuedIdentType"/>
            </eoPar:IssuedIdentType>
          </xsl:if>
          <xsl:if test="/ns0:CardCrInfoInqRq/ns0:PartyKey/ns0:IssuedIdentValue">
            <eoPar:IssuedIdentValue>
              <xsl:value-of select="/ns0:CardCrInfoInqRq/ns0:PartyKey/ns0:IssuedIdentValue"/>
            </eoPar:IssuedIdentValue>
          </xsl:if>
          <xsl:if test="/ns0:CardCrInfoInqRq/ns0:PartyKey/ns0:PartyId">
            <eoPar:PartyId>
              <xsl:value-of select="/ns0:CardCrInfoInqRq/ns0:PartyKey/ns0:PartyId"/>
            </eoPar:PartyId>
          </xsl:if>
        </tns:PartyKey>
      </xsl:if>
    </tns:CardCrInfoInqRq>
  </xsl:template>
</xsl:stylesheet>
