<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ConfiguracionValidacionAsignacionSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ConfiguracionValidacionAsignacionSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/ConsultarSolicitudDesembolsoSAD"
    >
    <plnk:partnerLinkType name="ConfiguracionValidacionAsignacion">
        <plnk:role name="ConfiguracionValidacionAsignacion_PT" portType="tns:ConfiguracionValidacionAsignacion_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ConfiguracionValidacionAsignacionSOR" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/WSDL/BPEL/ConfiguracionValidacionAsignacionSOR.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/ConsultarSolicitudDesembolsoSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/ADAPTER/ConsultarSolicitudDesembolsoSAD.wsdl"/>
</wsdl:definitions>
