<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ConsultarTreComisionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarTreComisionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:comMO="http://www.bcie.org/ComisionMO">
             
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ComisionMO"
                  schemaLocation="../../../../Comision/V1/Schema/ComisionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ConsultarTreComisionRequestMessage">
    <wsdl:part name="request" element="comMO:ConsultarTreComisionRequest"/>
  </wsdl:message>
  <wsdl:message name="ConsultarTreComisionResponseMessage">
    <wsdl:part name="response" element="comMO:ConsultarTreComisionResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarTreComisionPT">
    <wsdl:operation name="consultarTreComision">
      <wsdl:input message="tns:ConsultarTreComisionRequestMessage"/>
      <wsdl:output message="tns:ConsultarTreComisionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarTreComision12Bnd" type="tns:ConsultarTreComisionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarTreComision">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarTreComisionService/consultarTreComision"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>