<wsdl:definitions name="ConsultarCargoByProducto_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCargoByProducto_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCargoByProducto_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCargoByProducto_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarCargoByProducto_DB_plt">
    <plt:role name="ConsultarCargoByProducto_DB_role">
      <plt:portType name="tns:ConsultarCargoByProducto_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCargoByProducto_DB" schemaLocation="../XSD/ConsultarCargoByProducto_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarCargoByProducto_DBInput_msg">
        <wsdl:part name="ConsultarCargoByProducto_DBInput_msg" element="db:ConsultarCargoByProducto_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarCargoByProducto_DBOutputCollection_msg">
        <wsdl:part name="ConsultarCargoByProducto_DBOutputCollection" element="db:ConsultarCargoByProducto_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCargoByProducto_DB_ptt">
        <wsdl:operation name="ConsultarCargoByProducto_DB">
            <wsdl:input message="tns:ConsultarCargoByProducto_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarCargoByProducto_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>