<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultarTreTermino_BPEL" targetNamespace="http://xmlns.oracle.com/DominioLineaCredito/ActualizarLineaCredito/ConsultarTreTermino_BPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/DominioLineaCredito/ActualizarLineaCredito/ConsultarTreTermino_BPEL" xmlns:ns1="http://www.bcie.org/TerminoMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.bcie.org/TerminoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Termino/V1/Schema/TerminoMO.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ConsultarTreTermino_BPELRequestMessage">
      <wsdl:part name="payload" element="ns1:ConsultarTreTerminoRequest"/>
   </wsdl:message>
   <wsdl:message name="ConsultarTreTermino_BPELResponseMessage">
      <wsdl:part name="payload" element="ns1:ConsultarTreTerminoResponse"/>
   </wsdl:message>
   <wsdl:portType name="ConsultarTreTermino_BPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ConsultarTreTermino_BPELRequestMessage"/>
         <wsdl:output message="client:ConsultarTreTermino_BPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ConsultarTreTermino_BPEL">
      <plnk:role name="ConsultarTreTermino_BPELProvider" portType="client:ConsultarTreTermino_BPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
