<wsdl:definitions name="ConsultarNoObjecion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarNoObjecion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarNoObjecion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarNoObjecion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarNoObjecion_DB_plt">
    <plt:role name="ConsultarNoObjecion_DB_role">
      <plt:portType name="tns:ConsultarNoObjecion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarNoObjecion_DB" schemaLocation="../XSD/ConsultarNoObjecion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarNoObjecion_DBInput_msg">
        <wsdl:part name="ConsultarNoObjecion_DBInput_msg" element="db:ConsultarNoObjecion_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarNoObjecion_DBOutputCollection_msg">
        <wsdl:part name="ConsultarNoObjecion_DBOutputCollection" element="db:ConsultarNoObjecion_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarNoObjecion_DB_ptt">
        <wsdl:operation name="ConsultarNoObjecion_DB">
            <wsdl:input message="tns:ConsultarNoObjecion_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarNoObjecion_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>