<wsdl:definitions
     name="ConsultarContactos"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarContactos/ConsultarContactos"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarContactos/ConsultarContactos"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContactos"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarContactos_plt" >
    <plt:role name="ConsultarContactos_role" >
      <plt:portType name="tns:ConsultarContactos_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContactos" schemaLocation="../XSD/ConsultarContactos.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContactosInput_msg">
        <wsdl:part name="ConsultarContactosInput_msg" element="db:ConsultarContactosInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarContactosOutputCollection_msg">
        <wsdl:part name="ConsultarContactosOutputCollection" element="db:ConsultarContactosOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContactos_ptt">
        <wsdl:operation name="ConsultarContactos">
            <wsdl:input message="tns:ConsultarContactosInput_msg"/>
            <wsdl:output message="tns:ConsultarContactosOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
