<wsdl:definitions name="DBASNDet" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNQueryDB/DBASNDet" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNQueryDB/DBASNDet" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBASNDet" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="DBASNDet_plt">
    <plt:role name="DBASNDet_role">
      <plt:portType name="tns:DBASNDet_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBASNDet" schemaLocation="DBASNDet_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="DBASNDetSelect_inputParameters">
        <wsdl:part name="DBASNDetSelect_inputParameters" element="top:DBASNDetSelect_asnInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaAsninDetViewCollection_msg">
        <wsdl:part name="XxSoaAsninDetViewCollection" element="top:XxSoaAsninDetViewCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBASNDet_ptt">
        <wsdl:operation name="DBASNDetSelect">
            <wsdl:input message="tns:DBASNDetSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaAsninDetViewCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>