<wsdl:definitions
     name="ConsultarContratoBySolicitud"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarContratoBySolicitud"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarContratoBySolicitud"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContratoBySolicitud"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarContratoBySolicitud_plt" >
    <plt:role name="ConsultarContratoBySolicitud_role" >
      <plt:portType name="tns:ConsultarContratoBySolicitud_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarContratoBySolicitud" schemaLocation="../XSD/ConsultarContratoBySolicitud.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarContratoBySolicitudInput_msg">
        <wsdl:part name="ConsultarContratoBySolicitudInput_msg" element="db:ConsultarContratoBySolicitudInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarContratoBySolicitudOutputCollection_msg">
        <wsdl:part name="ConsultarContratoBySolicitudOutputCollection" element="db:ConsultarContratoBySolicitudOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarContratoBySolicitud_ptt">
        <wsdl:operation name="ConsultarContratoBySolicitud">
            <wsdl:input message="tns:ConsultarContratoBySolicitudInput_msg"/>
            <wsdl:output message="tns:ConsultarContratoBySolicitudOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>