<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarEventoCondicionByidCondicion_BS" name="EliminarEventoCondicionByidCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarEventoCondicionByidCondicion_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarEventoCondicionByidCondicion_BS"/>
    <wsdl:binding name="EliminarEventoCondicionByidCondicion_BS_ptt-binding" type="elim:EliminarEventoCondicionByidCondicion_BS_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarEventoCondicionByidCondicion_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarEventoCondicionByidCondicion_BS">
            <soap:operation soapAction="EliminarEventoCondicionByidCondicion_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>