<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.banesco.com/eopt/PartyMod_V1.0" xmlns:tns="http://xmlns.banesco.com/appopt/WFPartyAppSvc/PartyMod_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Party/PartyMod/PartyMod_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="PartyModRs" namespace="http://xmlns.banesco.com/eopt/PartyMod_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/WFParty/PartyMod/PartyMod_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="PartyModRs" namespace="http://xmlns.banesco.com/appopt/WFPartyAppSvc/PartyMod_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU APR 19 17:08:56 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:PartyModRs>
         <tns:PartyKey>
            <xsl:if test="/ns0:PartyModRs/ns0:Party/eoPar:PartyKey/eoPar:PartyId/text()">
               <tns:PartyId>
                  <xsl:value-of select="/ns0:PartyModRs/ns0:Party/eoPar:PartyKey/eoPar:PartyId"/>
               </tns:PartyId>
            </xsl:if>
         </tns:PartyKey>
         <tns:Status>
            <appoptcommon:StatusCode>
               <xsl:value-of select="/ns0:PartyModRs/ns0:Status/eoStatus:StatusCode"/>
            </appoptcommon:StatusCode>
            <xsl:choose>
               <xsl:when test="/ns0:PartyModRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc/text()">
                  <appoptcommon:StatusDesc>
                     <xsl:value-of select="/ns0:PartyModRs/ns0:Status/eoStatus:AdditionalStatus/eoStatus:StatusDesc"/>
                  </appoptcommon:StatusDesc>
               </xsl:when>
               <xsl:otherwise>
                  <appoptcommon:StatusDesc>
                     <xsl:value-of select="/ns0:PartyModRs/ns0:Status/eoStatus:StatusDesc"/>
                  </appoptcommon:StatusDesc>
               </xsl:otherwise>
            </xsl:choose>
         </tns:Status>
      </tns:PartyModRs>
   </xsl:template>
</xsl:stylesheet>
