<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/NotificarCancelarOperacion"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/NotificarCancelarOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/OperacionMO"
     xmlns:ns2="http://www.bcie.org/ConsultarTareasActivas"
     xmlns:ns3="http://schemas.oracle.com/bpel/extension"
    >
    <plnk:partnerLinkType name="NotificarCancelarOperacion">
        <plnk:role name="NotificarCancelarOperacion_PT" portType="tns:NotificarCancelarOperacion_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/NotificarCancelarOperacion" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/NotificarCancelarOperacion/V1/Wsdl/NotificarCancelarOperacion.wsdl"/>
    <wsdl:import namespace="http://www.bcie.org/ConsultarTareasActivas" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConsultarTareasActivas/V1/Wsdl/ConsultarTareasActivas.wsdl"/>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/OperacionMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Operacion/V1/Schema/OperacionMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
