<wsdl:definitions name="ConsultarSolicitudAproByIdSolicitud" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSolicitudAproByIdSolicitud" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarSolicitudAproByIdSolicitud" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSolicitudAproByIdSolicitud" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarSolicitudAproByIdSolicitud_plt">
    <plt:role name="ConsultarSolicitudAproByIdSolicitud_role">
      <plt:portType name="tns:ConsultarSolicitudAproByIdSolicitud_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarSolicitudAproByIdSolicitud" schemaLocation="../XSD/ConsultarSolicitudAproByIdSolicitud.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarSolicitudAproByIdSolicitudInput_msg">
        <wsdl:part name="ConsultarSolicitudAproByIdSolicitudInput_msg" element="db:ConsultarSolicitudAproByIdSolicitudInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarSolicitudAproByIdSolicitudOutputCollection_msg">
        <wsdl:part name="ConsultarSolicitudAproByIdSolicitudOutputCollection" element="db:ConsultarSolicitudAproByIdSolicitudOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarSolicitudAproByIdSolicitud_ptt">
        <wsdl:operation name="ConsultarSolicitudAproByIdSolicitud">
            <wsdl:input message="tns:ConsultarSolicitudAproByIdSolicitudInput_msg"/>
            <wsdl:output message="tns:ConsultarSolicitudAproByIdSolicitudOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>