<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ObtenerTCCInicioService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ObtenerTCCInicioService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:mtccMO="http://www.bcie.org/MatrizTCCMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/MatrizTCCMO" schemaLocation="../../Schema/MatrizTCCMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="obtenerTCCInicioRequestMessage">
    <part name="request" element="mtccMO:ObtenerTCCInicioRequest"/>
  </message>
  <message name="obtenerTCCInicioResponseMessage">
    <part name="response" element="mtccMO:ObtenerTCCInicioResponse"/>
  </message>
  <portType name="ObtenerTCCInicioPT">
    <operation name="obtenerTCCInicio">
      <input message="tns:obtenerTCCInicioRequestMessage"/>
      <output message="tns:obtenerTCCInicioResponseMessage"/>
    </operation>
  </portType>
  <binding name="ObtenerTCCInicio12Bnd" type="tns:ObtenerTCCInicioPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="obtenerTCCInicio">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ObtenerTCCInicioService/obtenerTCCInicio"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>