<wsdl:definitions name="SyncStoreMDMAdapter" targetNamespace="http://www.agarcia.mx/ServiceBus/Store" xmlns:tns="http://www.agarcia.mx/ServiceBus/Store" xmlns:ebm="http://www.agarcia.mx/EnterpriseObjects/Store" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Store" schemaLocation="../../EnterpriseObjectLibrary/EBO/Store/StoreEBM.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/Common" schemaLocation="../../EnterpriseObjectLibrary/Common/CommonComponents.xsd"/>
    </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="SyncStoreReqMsg">
        <wsdl:part name="SyncStoreReqMsg" element="ebm:SyncStoreEBM"/>
    </wsdl:message>
    <wsdl:message name="SyncStoreRespMsg">
        <wsdl:part name="SyncStoreRespMsg" element="ebm:SyncStoreResponseEBM"/>
    </wsdl:message>
        <wsdl:message name="FaultMessage">
        <wsdl:part name="FaultMessage" element="com:FaultMessage"/>
    </wsdl:message>
    
    <wsdl:portType name="SyncStore_ptt">
        <wsdl:operation name="SyncStore">
            <wsdl:input message="tns:SyncStoreReqMsg"/>
            <wsdl:output message="tns:SyncStoreRespMsg"/>
             <wsdl:fault message="tns:FaultMessage" name="FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>