<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <wsdl:types>
      <xsd:schema targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/FormalizacionEnmiendasProcess">
         <xsd:element name="start">
            <xsd:complexType>
               <xsd:sequence/>
            </xsd:complexType>
         </xsd:element>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="start">
      <wsdl:part name="parameters" element="tns:start"/>
   </wsdl:message>
   <wsdl:portType name="FormalizacionEnmiendasProcessPortType">
      <wsdl:operation name="start">
         <wsdl:input message="tns:start"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="FormalizacionEnmiendasProcessPortTypePartnerLinkType">
      <plnk:role name="FormalizacionEnmiendasProcessPortTypeProvider">
         <plnk:portType name="tns:FormalizacionEnmiendasProcessPortType"/>
      </plnk:role>
   </plnk:partnerLinkType>
</wsdl:definitions>
