<wsdl:definitions name="ActualizarOperacionProcesoByIdOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarOperacionProcesoByIdOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarOperacionProcesoByIdOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarOperacionProcesoByIdOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarOperacionProcesoByIdOperacion_DB_plt">
    <plt:role name="ActualizarOperacionProcesoByIdOperacion_DB_role">
      <plt:portType name="tns:ActualizarOperacionProcesoByIdOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarOperacionProcesoByIdOperacion_DB" schemaLocation="../XSD/ActualizarOperacionProcesoByIdOperacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarOperacionProcesoByIdOperacion_DBInput_msg">
        <wsdl:part name="ActualizarOperacionProcesoByIdOperacion_DBInput_msg" element="db:ActualizarOperacionProcesoByIdOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarOperacionProcesoByIdOperacion_DB_ptt">
        <wsdl:operation name="ActualizarOperacionProcesoByIdOperacion_DB">
            <wsdl:input message="tns:ActualizarOperacionProcesoByIdOperacion_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>