<wsdl:definitions
     name="ActualizarUsuarioReunionAprob"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project12/ActualizarUsuarioReunionAprob"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project12/ActualizarUsuarioReunionAprob"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarUsuarioReunionAprob"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarUsuarioReunionAprob_plt" >
    <plt:role name="ActualizarUsuarioReunionAprob_role" >
      <plt:portType name="tns:ActualizarUsuarioReunionAprob_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarUsuarioReunionAprob" schemaLocation="../XSD/ActualizarUsuarioReunionAprob.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarUsuarioReunionAprobInput_msg">
        <wsdl:part name="ActualizarUsuarioReunionAprobInput_msg" element="db:ActualizarUsuarioReunionAprobInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarUsuarioReunionAprob_ptt">
        <wsdl:operation name="ActualizarUsuarioReunionAprob">
            <wsdl:input message="tns:ActualizarUsuarioReunionAprobInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
