<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project12/ActualizarUsuarioReunionAprob" name="ActualizarUsuarioReunionAprob_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ActualizarUsuarioReunionAprob.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project12/ActualizarUsuarioReunionAprob"/>
    <wsdl:binding name="ActualizarUsuarioReunionAprob_ptt-binding" type="act:ActualizarUsuarioReunionAprob_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project12/ActualizarUsuarioReunionAprob">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ActualizarUsuarioReunionAprob">
            <soap:operation soapAction="ActualizarUsuarioReunionAprob"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>