<wsdl:definitions name="caseTwoCatalogTranslate" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoCatalogTranslate" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoCatalogTranslate" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoCatalogTranslate" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="caseTwoCatalogTranslate_plt">
    <plt:role name="caseTwoCatalogTranslate_role">
      <plt:portType name="tns:caseTwoCatalogTranslate_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoCatalogTranslate" schemaLocation="caseTwoCatalogTranslate_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="caseTwoCatalogTranslateSelect_inputParameters">
        <wsdl:part name="caseTwoCatalogTranslateSelect_inputParameters" element="top:caseTwoCatalogTranslateSelect_idC2_appCodeC2_catIdC2InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmItemsCatalogsCollection_msg">
        <wsdl:part name="MdmItemsCatalogsCollection" element="top:MdmItemsCatalogsCollection"/>
    </wsdl:message>
    <wsdl:portType name="caseTwoCatalogTranslate_ptt">
        <wsdl:operation name="caseTwoCatalogTranslateSelect">
            <wsdl:input message="tns:caseTwoCatalogTranslateSelect_inputParameters"/>
            <wsdl:output message="tns:MdmItemsCatalogsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>