<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.banesco.com/eopt/AcctStmtInq_V1.0" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://tempuri.org/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns3="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:eoAcctStmt="http://xmlns.banesco.com/eo/AcctStmt_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns7="http://xmlns.banesco.com/eo/Payee_V1.0"
                xmlns:eoCom="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/AcctStmtInq/AcctStmtInq_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="AcctStmtInqRq" namespace="http://xmlns.banesco.com/eopt/AcctStmtInq_V1.0"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/AOptCommon/AOptCommon_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="MsgHdrRq" namespace="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"/>
            <oracle-xsl-mapper:param name="varHeader"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../../../Commons/backends/ONBASE/resources/wsdl/OnBase_EstadosCuentaWS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ConsultarEstadoCuenta" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED MAY 23 16:58:40 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varHeader"/>
   <xsl:template match="/">
      <tns:ConsultarEstadoCuenta>
         <xsl:if test="/ns0:AcctStmtInqRq/ns0:Acct/ns0:AcctKey/eoAcct:AcctId/text()">
            <tns:numCuenta>
               <xsl:value-of select="/ns0:AcctStmtInqRq/ns0:Acct/ns0:AcctKey/eoAcct:AcctId"/>
            </tns:numCuenta>
         </xsl:if>
         <xsl:if test="/ns0:AcctStmtInqRq/ns0:Acct/ns0:AcctType/eoCom:Cod/text()">
            <tns:tipoCuenta>
               <xsl:value-of select="/ns0:AcctStmtInqRq/ns0:Acct/ns0:AcctType/eoCom:Cod"/>
            </tns:tipoCuenta>
         </xsl:if>
         <xsl:if test="/ns0:AcctStmtInqRq/ns0:CustomDate/eoCom:Month/text()">
            <tns:mes>
               <xsl:value-of select="/ns0:AcctStmtInqRq/ns0:CustomDate/eoCom:Month"/>
            </tns:mes>
         </xsl:if>
         <xsl:if test="/ns0:AcctStmtInqRq/ns0:CustomDate/eoCom:Year/text()">
            <tns:anio>
               <xsl:value-of select="/ns0:AcctStmtInqRq/ns0:CustomDate/eoCom:Year"/>
            </tns:anio>
         </xsl:if>
      </tns:ConsultarEstadoCuenta>
   </xsl:template>
</xsl:stylesheet>
