<wsdl:definitions name="ConsultarEnmiendasTCCByIdOperacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEnmiendasTCCByIdOperacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarEnmiendasTCCByIdOperacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarEnmiendasTCCByIdOperacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarEnmiendasTCCByIdOperacion_plt">
    <plt:role name="ConsultarEnmiendasTCCByIdOperacion_role">
      <plt:portType name="tns:ConsultarEnmiendasTCCByIdOperacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarEnmiendasTCCByIdOperacion" schemaLocation="../XSD/ConsultarEnmiendasTCCByIdOperacion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarEnmiendasTCCByIdOperacionSelect_inputParameters">
        <wsdl:part name="ConsultarEnmiendasTCCByIdOperacionSelect_inputParameters" element="top:ConsultarEnmiendasTCCByIdOperacionSelect_idOperacionInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EnmiendaTccCollection_msg">
        <wsdl:part name="EnmiendaTccCollection" element="top:EnmiendaTccCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarEnmiendasTCCByIdOperacion_ptt">
        <wsdl:operation name="ConsultarEnmiendasTCCByIdOperacionSelect">
            <wsdl:input message="tns:ConsultarEnmiendasTCCByIdOperacionSelect_inputParameters"/>
            <wsdl:output message="tns:EnmiendaTccCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>