<wsdl:definitions
     name="ActualizarEstadoComision"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoComision"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoComision"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarEstadoComision"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarEstadoComision_plt" >
    <plt:role name="ActualizarEstadoComision_role" >
      <plt:portType name="tns:ActualizarEstadoComision_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarEstadoComision" schemaLocation="../XSD/ActualizarEstadoComision.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarEstadoComisionInput_msg">
        <wsdl:part name="ActualizarEstadoComisionInput_msg" element="db:ActualizarEstadoComisionInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarEstadoComision_ptt">
        <wsdl:operation name="ActualizarEstadoComision">
            <wsdl:input message="tns:ActualizarEstadoComisionInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
