<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/SolicitudAprobacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO"
                  xmlns:tns="http://xmlns.bcie.com/SolicitudAprobacionService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Read -->
  <wsdl:message name="requestConsultarVotacionesMessage">
    <wsdl:part name="request" element="solAproMO:ConsultarVotacionesRequest"/>
  </wsdl:message>
  <wsdl:message name="responseConsultarVotacionesMessage">
    <wsdl:part name="response" element="solAproMO:ConsultarVotacionesResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarVotacionesPT">
    <wsdl:operation name="consultarVotaciones">
      <wsdl:input message="tns:requestConsultarVotacionesMessage"/>
      <wsdl:output message="tns:responseConsultarVotacionesMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarVotacionesPT12Bnd" type="tns:ConsultarVotacionesPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarVotaciones">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/SolicitudAprobacionService/consultarVotaciones"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>