<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarTreComiteRolService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarTreComiteRolService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:solAproMO="http://www.bcie.org/SolicitudAprobacionMO" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/SolicitudAprobacionMO"
                  schemaLocation="../../../../SolicitudAprobacion/V1/Schema/SolicitudAprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarTreComiteRolRequestMessage">
    <part name="request" element="solAproMO:ConsultarTreComiteRolRequest"/>
  </message>
  <message name="ConsultarTreComiteRolResponseMessage">
    <part name="response" element="solAproMO:ConsultarTreComiteRolResponse"/>
  </message>
  <portType name="ConsultarTreComiteRolPT">
    <operation name="consultarTreComiteRol">
      <input message="tns:ConsultarTreComiteRolRequestMessage"/>
      <output message="tns:ConsultarTreComiteRolResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarTreComiteRol12Bnd" type="tns:ConsultarTreComiteRolPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarTreComiteRol">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/SolicitudAprobacionService/consultarTreComiteRol"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>