<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/DeclaracionJuradaService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:djMO="http://www.bcie.org/DeclaracionJuradaMO" xmlns:tns="http://xmlns.bcie.com/DeclaracionJuradaService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/DeclaracionJuradaMO" schemaLocation="../../Schema/DeclaracionJuradaMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
 
  
   <wsdl:message name="requestCrearDeclaracionOperacionMessage">
    <wsdl:part name="request" element="djMO:CrearDeclaracionOperacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseCrearDeclaracionOperacionMessage">
    <wsdl:part name="response" element="djMO:CrearDeclaracionOperacionResponse"/>
  </wsdl:message>
  
  
  <wsdl:portType name="CrearDeclaracionOperacionPT">
    <!-- Create -->
   
    <wsdl:operation name="CrearDeclaracionOperacion">
      <wsdl:documentation>Crea la relacion entre operacion y declaracion</wsdl:documentation>
      <wsdl:input message="tns:requestCrearDeclaracionOperacionMessage"/>
      <wsdl:output message="tns:responseCrearDeclaracionOperacionMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="DeclaracionJurada12Bnd" type="tns:CrearDeclaracionOperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
   
     <wsdl:operation name="CrearDeclaracionOperacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/DeclaracionJuradaService/CrearDeclaracionOperacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="DeclaracionJurada">
    <wsdl:port name="DeclaracionJurada12Bnd" binding="tns:DeclaracionJurada12Bnd">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>