<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="InsertCostChange" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/CostChangeApprovedProcess/InsertCostChange" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CostChangeApp/CostChangeApprovedProcess/InsertCostChange" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertCostChange" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="InsertCostChange_plt">
      <plt:role name="InsertCostChange_role">
         <plt:portType name="tns:InsertCostChange_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertCostChange" schemaLocation="../Schemas/InsertCostChange_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CchEventsCollection_msg">
      <wsdl:part name="CchEventsCollection" element="top:CchEventsCollection"/>
   </wsdl:message>
   <wsdl:portType name="InsertCostChange_ptt">
      <wsdl:operation name="insert">
         <wsdl:input message="tns:CchEventsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
