<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/CreaOperacion/CrearOperacionBD" 
                  name="CrearOperacionBD_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
		  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="CrearOperacionBD.wsdl" 
               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/CreaOperacion/CrearOperacionBD"/>
  <wsdl:binding name="CrearOperacionBD_ptt-binding" type="cre:CrearOperacionBD_ptt" 
                xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/DominioOperacion/CreaOperacion/CrearOperacionBD">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>