<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarObservacionCondicion" name="ConsultarObservacionCondicion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarObservacionCondicion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarObservacionCondicion"/>
    <wsdl:binding name="ConsultarObservacionCondicion_ptt-binding" type="con:ConsultarObservacionCondicion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarObservacionCondicion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarObservacionCondicionSelect">
            <soap:operation soapAction="ConsultarObservacionCondicionSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>