<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsolidarFlujoCaja"
     targetNamespace="http://xmlns.oracle.com/DominioDesembolso/PropagarTransferencia/ConsolidarFlujoCaja"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/DominioDesembolso/PropagarTransferencia/ConsolidarFlujoCaja"
     xmlns:ns1="http://www.bcie.org/DesembolsoMO"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns2="http:/www.bcie.org/PropagarTransferenciaXSD"
     xmlns:ns3="http://schemas.oracle.com/bpel/extension"
    >
    <plnk:partnerLinkType name="ConsolidarFlujoCaja">
        <plnk:role name="ConsolidarFlujoCajaProvider" portType="client:ConsolidarFlujoCaja"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/DominioDesembolso/PropagarTransferencia/ConsolidarFlujoCaja"
             xmlns:ns1="http://www.bcie.org/DesembolsoMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http:/www.bcie.org/PropagarTransferenciaXSD">
            <xsd:import namespace="http:/www.bcie.org/PropagarTransferenciaXSD" schemaLocation="../Schemas/PropagarTransferenciaXSD.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:client="http://xmlns.oracle.com/DominioDesembolso/PropagarTransferencia/ConsolidarFlujoCaja"
             xmlns:ns1="http://www.bcie.org/DesembolsoMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:ns2="http:/www.bcie.org/PropagarTransferenciaXSD">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ConsolidarFlujoCajaRequestMessage">
        <wsdl:part name="payload" element="ns1:ConsolidarFlujoCajaRequest"/>
    </wsdl:message>
    <wsdl:portType name="ConsolidarFlujoCaja">
        <wsdl:operation name="process">
            <wsdl:input message="client:ConsolidarFlujoCajaRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
