<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ActualizarFuenteLCSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ActualizarFuenteLCSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ActualizarFuenteLCSAD/types" elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ActualizarFuenteLCRequest">
    <part name="ActualizarFuenteRequest" element="linCrBO:ActualizarFuenteLCRequest"/>
  </message>
  <message name="ActualizarFuenteLCResponse">
    <part name="ActualizarFuenteLCResponse" element="linCrBO:ActualizarFuenteLCResponse"/>
  </message>
  <portType name="ActualizarFuenteLC_PT">
    <operation name="actualizarFuenteLC">
      <input message="tns:ActualizarFuenteLCRequest"/>
      <output message="tns:ActualizarFuenteLCResponse"/>
    </operation>
  </portType>
  <binding name="ActualizarFuenteLC_PTSOAP12Binding" type="tns:ActualizarFuenteLC_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="actualizarFuenteLC">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ActualizarFuenteLCSAD/actualizarFuenteLC"/>
      <input>
        <soap12:body use="literal" parts="ActualizarFuenteRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ActualizarFuenteLCResponse"/>
      </output>
    </operation>
  </binding>
</definitions>