<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarLineaCreditoByIdOperacionSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarLineaCreditoByIdOperacionSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarLineaCreditoByIdOperacionSAD/types"
                elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConsultarLineaCreditoByIdOperacionRequest">
    <part name="ConsultarLineaCreditoByIdOperacionRequest" element="linCrBO:ConsultarLineaCreditoByIdOperacionRequest"/>
  </message>
  <message name="ConsultarLineaCreditoByIdOperacionResponse">
    <part name="ConsultarLineaCreditoByIdOperacionResponse"
          element="linCrBO:ConsultarLineaCreditoByIdOperacionResponse"/>
  </message>
  <portType name="ConsultarLineaCreditoByIdOperacion_PT">
    <operation name="ConsultarLineaCreditoByIdOperacion">
      <input message="tns:ConsultarLineaCreditoByIdOperacionRequest"/>
      <output message="tns:ConsultarLineaCreditoByIdOperacionResponse"/>
    </operation>
  </portType>
  <binding name="ConsultarLineaCreditoByIdOperacion_PTSOAP12Binding" type="tns:ConsultarLineaCreditoByIdOperacion_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarLineaCreditoByIdOperacion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConsultarLineaCreditoByIdOperacionSAD/ConsultarLineaCreditoByIdOperacion"/>
      <input>
        <soap12:body use="literal" parts="ConsultarLineaCreditoByIdOperacionRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="ConsultarLineaCreditoByIdOperacionResponse"/>
      </output>
    </operation>
  </binding>
</definitions>