<wsdl:definitions name="ConsultarUsuarioReunionDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarUsuarioReunionDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarUsuarioReunionDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarUsuarioReunionDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarUsuarioReunionDB_plt">
    <plt:role name="ConsultarUsuarioReunionDB_role">
      <plt:portType name="tns:ConsultarUsuarioReunionDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarUsuarioReunionDB" schemaLocation="../XSD/ConsultarUsuarioReunionDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarUsuarioReunionDBInput_msg">
        <wsdl:part name="ConsultarUsuarioReunionDBInput_msg" element="db:ConsultarUsuarioReunionDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarUsuarioReunionDBOutputCollection_msg">
        <wsdl:part name="ConsultarUsuarioReunionDBOutputCollection" element="db:ConsultarUsuarioReunionDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarUsuarioReunionDB_ptt">
        <wsdl:operation name="ConsultarUsuarioReunionDB">
            <wsdl:input message="tns:ConsultarUsuarioReunionDBInput_msg"/>
            <wsdl:output message="tns:ConsultarUsuarioReunionDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>