<wsdl:definitions name="ConsultarOperacionByIdOperacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/ConsultarOperacionByIdOperacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/ConsultarOperacionByIdOperacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionByIdOperacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarOperacionByIdOperacion_plt">
    <plt:role name="ConsultarOperacionByIdOperacion_role">
      <plt:portType name="tns:ConsultarOperacionByIdOperacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarOperacionByIdOperacion" schemaLocation="../XSD/ConsultarOperacionByIdOperacion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarOperacionByIdOperacionInput_msg">
        <wsdl:part name="ConsultarOperacionByIdOperacionInput_msg" element="db:ConsultarOperacionByIdOperacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarOperacionByIdOperacionOutputCollection_msg">
        <wsdl:part name="ConsultarOperacionByIdOperacionOutputCollection" element="db:ConsultarOperacionByIdOperacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarOperacionByIdOperacion_ptt">
        <wsdl:operation name="ConsultarOperacionByIdOperacion">
            <wsdl:input message="tns:ConsultarOperacionByIdOperacionInput_msg"/>
            <wsdl:output message="tns:ConsultarOperacionByIdOperacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>