<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/CreateStockCountSIMReference" name="CreateStockCountSIMReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CreateStockCountSIMReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/CreateStockCountSIMReference"/>
    <wsdl:binding name="PutStockCount_ptt-binding" type="cre:PutStockCount_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/CreateStockCountSIMReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="PutStockCount">
            <soap:operation soapAction="PutStockCount"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>