<wsdl:definitions name="CreateStockCountSIMReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/CreateStockCountSIMReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/CreateStockCountSIMReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:imp1="http://www.agarcia.mx/StockCount" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="PutStockCount_plt">
    <plt:role name="PutStockCount_role">
      <plt:portType name="tns:PutStockCount_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/CreateStockCountSIMReference" xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://www.agarcia.mx/StockCount" schemaLocation="../../../Resources/nxsd_stockcountOUT.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="PutStockCount_msg">
        <wsdl:part name="body" element="imp1:StockCount"/>
    </wsdl:message>
    <wsdl:portType name="PutStockCount_ptt">
        <wsdl:operation name="PutStockCount">
            <wsdl:input message="tns:PutStockCount_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>