<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarComisionByIdLineaCredito" name="ConsultarComisionByIdLineaCredito_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarComisionByIdLineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarComisionByIdLineaCredito"/>
    <wsdl:binding name="ConsultarComisionByIdLineaCredito_ptt-binding" type="con:ConsultarComisionByIdLineaCredito_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/CrearCargoTramite/ConsultarComisionByIdLineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarComisionByIdLineaCredito">
            <soap:operation soapAction="ConsultarComisionByIdLineaCredito"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>