<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:EliminarAprobacion" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:EliminarAprobacion" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:aproMO="http://www.bcie.org/AprobacionMO">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="EliminarAprobacionRequestMessage">
    <part name="EliminarAprobacionRequest" element="aproMO:EliminarAprobacionRequest"/>
  </message>
  <message name="EliminarAprobacionResponseMessage">
    <part name="EliminarAprobacionResponse" element="aproMO:EliminarAprobacionResponse"/>
  </message>
  <portType name="EliminarAprobacionPT">
    <operation name="eliminarAprobacion">
      <input message="tns:EliminarAprobacionRequestMessage"/>
      <output message="tns:EliminarAprobacionResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarAprobacionPTSOAP12Binding" type="tns:EliminarAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarAprobacion">
      <soap12:operation style="document" soapAction="urn:EliminarAprobacion/eliminarAprobacion"/>
      <input>
        <soap12:body use="literal" parts="EliminarAprobacionRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="EliminarAprobacionResponse"/>
      </output>
    </operation>
  </binding>
</definitions>