<wsdl:definitions
     name="ActualizarTerminoDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarTerminoDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarTerminoDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarTerminoDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarTerminoDB_plt" >
    <plt:role name="ActualizarTerminoDB_role" >
      <plt:portType name="tns:ActualizarTerminoDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarTerminoDB" schemaLocation="../XSD/ActualizarTerminoDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TerminoCollection_msg">
        <wsdl:part name="TerminoCollection" element="top:TerminoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarTerminoDB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:TerminoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
