<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearActualizarLoteImplementacionSAD"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearActualizarLoteImplementacionSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:impMO="http://www.bcie.org/ImplementacionPctMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearActualizarLoteImplementacionSAD/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/ImplementacionPctMO" schemaLocation="../../Schema/ImplementacionPctMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestCrearActualizarLoteImplementacionPCTMessage">
    <part name="request" element="impMO:CrearActualizarLoteImplementacionRequest"/>
  </message>
  <message name="responseCrearActualizarLoteImplementacionPCTMessage">
    <part name="response" element="impMO:CrearActualizarLoteImplementacionResponse"/>
  </message>
  <portType name="CrearActualizarLoteImplementacionPCT_PT">
    <operation name="crearActualizarLoteImplementacionPCT">
      <input message="tns:requestCrearActualizarLoteImplementacionPCTMessage"/>
      <output message="tns:responseCrearActualizarLoteImplementacionPCTMessage"/>
    </operation>
  </portType>
  <binding name="CrearActualizarLoteImplementacionPCT_PTSOAP12Binding" type="tns:CrearActualizarLoteImplementacionPCT_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearActualizarLoteImplementacionPCT">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearActualizarLoteImplementacionSAD/crearActualizarLoteImplementacionPCT"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>