<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/PrepagoProcess"
                  xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/PrepagoProcess"
                  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/PrepagoProcess"
                  schemaLocation="../../Schema/PA12/PrepagoProcess.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="InicioPrepago">
    <wsdl:part name="parameters" element="tns:InicioPrepago"/>
  </wsdl:message>
  <wsdl:message name="FinPrepago">
    <wsdl:part name="parameters" element="tns:FinPrepago"/>
  </wsdl:message>
   <wsdl:message name="InicioReasignarPrepago">
    <wsdl:part name="parameters" element="tns:InicioReasignarRO"/>
  </wsdl:message>
  <wsdl:portType name="PrepagoProcessPortType">
    <wsdl:operation name="InicioPrepago">
      <wsdl:input message="tns:InicioPrepago"/>
    </wsdl:operation>
    <wsdl:operation name="FinPrepago">
      <wsdl:input message="tns:FinPrepago"/>
    </wsdl:operation>
    <wsdl:operation name="InicioReasignarPrepago">
      <wsdl:input message="tns:InicioReasignarPrepago"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PrepagoProcessBinding" type="tns:PrepagoProcessPortType">
    <wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="InicioPrepago">
      <wsdlsoap:operation style="document" soapAction="InicioPrepago"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="FinPrepago">
      <wsdlsoap:operation style="document" soapAction="FinPrepago"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="InicioReasignarPrepago">
      <wsdlsoap:operation style="document" soapAction="InicioReasignarPrepago"/>
      <wsdl:input>
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <plnk:partnerLinkType name="PrepagoProcessPortTypePartnerLinkType">
    <plnk:role name="PrepagoProcessPortTypeProvider">
      <plnk:portType name="tns:PrepagoProcessPortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
</wsdl:definitions>
