<wsdl:definitions name="ConsultarReactivarOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarReactivarOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarReactivarOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarReactivarOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarReactivarOperacion_DB_plt">
    <plt:role name="ConsultarReactivarOperacion_DB_role">
      <plt:portType name="tns:ConsultarReactivarOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarReactivarOperacion_DB" schemaLocation="../XSD/ConsultarReactivarOperacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarReactivarOperacion_DBInput_msg">
        <wsdl:part name="ConsultarReactivarOperacion_DBInput_msg" element="db:ConsultarReactivarOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarReactivarOperacion_DBOutputCollection_msg">
        <wsdl:part name="ConsultarReactivarOperacion_DBOutputCollection" element="db:ConsultarReactivarOperacion_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarReactivarOperacion_DB_ptt">
        <wsdl:operation name="ConsultarReactivarOperacion_DB">
            <wsdl:input message="tns:ConsultarReactivarOperacion_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarReactivarOperacion_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>