<wsdl:definitions name="CrearTBILineaCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/CrearTBILineaCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/06-OSB-SERVICE/ADAPTADORES/CrearTBILineaCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearTBILineaCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CrearTBILineaCredito_plt">
    <plt:role name="CrearTBILineaCredito_role">
      <plt:portType name="tns:CrearTBILineaCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearTBILineaCredito" schemaLocation="../XSD/TBILineaCredito.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="TbiLineaCreditoCollection_msg">
        <wsdl:part name="TbiLineaCreditoCollection" element="top:TbiLineaCreditoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearTBILineaCredito_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:TbiLineaCreditoCollection_msg"/>
            <wsdl:output message="tns:TbiLineaCreditoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>