<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GenerarAvisoCobroDemandaV2SOR"
     targetNamespace="http://www.bcie.org/GestionCobroMO"
     xmlns:tns="http://www.bcie.org/GestionCobroMO"
     xmlns:inp1="http://www.bcie.org/GestionCobroMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/GestionCobroMO" schemaLocation="../../Schema/GestionCobroMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="GenerarAvisoCobroDemandaV2RequestMessage">
        <wsdl:part name="GenerarAvisoCobroDemandaV2Request" element="tns:GenerarAvisoCobroDemandaV2Request"/>
    </wsdl:message>
    <wsdl:message name="GenerarAvisoCobroDemandaV2ResponseMessage">
        <wsdl:part name="GenerarAvisoCobroDemandaV2Response" element="tns:GenerarAvisoCobroDemandaV2Response"/>
    </wsdl:message>
    <wsdl:portType name="GenerarAvisoCobroDemandaV2PT">
        <wsdl:operation name="generarAvisoCobroDemandaV2">
            <wsdl:input message="tns:GenerarAvisoCobroDemandaV2RequestMessage"/>
            <wsdl:output message="tns:GenerarAvisoCobroDemandaV2ResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GenerarAvisoCobroDemandaV2PT12Bnd" type="tns:GenerarAvisoCobroDemandaV2PT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="generarAvisoCobroDemandaV2">
            <soap12:operation style="document" soapAction="http://www.bcie.org/GestionCobroMO/generarAvisoCobroDemandaV2" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.bcie.org/GestionCobroMO"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.bcie.org/GestionCobroMO"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
