<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="MDMUpdateCostChange" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AGSOABpelApplication/CostChangeApprovedProcess/MDMUpdateCostChange" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AGSOABpelApplication/CostChangeApprovedProcess/MDMUpdateCostChange" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MDMUpdateCostChange" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="MDMUpdateCostChange_plt">
      <plt:role name="MDMUpdateCostChange_role">
         <plt:portType name="tns:MDMUpdateCostChange_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MDMUpdateCostChange" schemaLocation="../Schemas/MDMUpdateCostChange_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CchEventsCollection_msg">
      <wsdl:part name="CchEventsCollection" element="top:CchEventsCollection"/>
   </wsdl:message>
   <wsdl:portType name="MDMUpdateCostChange_ptt">
      <wsdl:operation name="update">
         <wsdl:input message="tns:CchEventsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
