<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/OperacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:operMO="http://www.bcie.org/OperacionMO"
                  xmlns:tns="http://xmlns.bcie.com/OperacionService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
   <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/OperacionMO"
                  schemaLocation="../../Schema/OperacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
    <wsdl:message name="requestValidarInicioFormalizacion">
    <wsdl:part name="request" element="operMO:ValidarInicioFormalizacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseValidarInicioFormalizacion">
    <wsdl:part name="response" element="operMO:ValidarInicioFormalizacionResponse"/>
  </wsdl:message>
  
  <wsdl:portType name="OperacionPT">
    
   <wsdl:operation name="ValidarInicioFormalizacion">
      <wsdl:documentation>Valida el inicio automatico de formalizacion</wsdl:documentation>
      <wsdl:input message="tns:requestValidarInicioFormalizacion"/>
      <wsdl:output message="tns:responseValidarInicioFormalizacion"/>
    </wsdl:operation>
    
    
  </wsdl:portType>
  <wsdl:binding name="Operacion12Bnd" type="tns:OperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    
     <wsdl:operation name="ValidarInicioFormalizacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/OperacionService/ValidarInicioFormalizacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
 
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>