--TRE_TAREA_BPM_MENSAJE_PRODUCTO
INSERT INTO "FENIX"."TRE_TAREA_BPM_MENSAJE_PRODUCTO" (ID_TAREA_BPM_MENSAJE_PRODUCTO, ID_TAREA_BPM_MENSAJE, ID_PRODUCTO, FECHA_REGISTRO, BAN_ESTATUS) 
VALUES (SELECT COUNT(*)+1 FROM FENIX.TRE_TAREA_BPM_MENSAJE_PRODUCTO, SELECT ID_TAREA_BPM_MENSAJE FROM FENIX.TCO_TAREA_BPM_MENSAJE 
WHERE ID_TCA_TAREA_BPM=(SELECT ID FROM FENIX.TCA_TAREA_BPM WHERE DESCRIPCION_CORTA='HT01SolicitarElaboracionDocContractual')
AND ID_TCA_ACCION_BPM=(SELECT ID FROM FENIX.TCA_ACCION_BPM WHERE ID_TAREA_BPM=(SELECT ID FROM FENIX.TCA_TAREA_BPM WHERE DESCRIPCION_CORTA='HT01SolicitarElaboracionDocContractual'));
, '1', TO_DATE('2021-05-18 14:15:52', 'YYYY-MM-DD HH24:MI:SS'), '1')