<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ActualizarTCCAprobacionService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/ActualizarTCCAprobacionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/ContratoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ActualizarTCCAprobacionService/types"
                elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/ContratoMO" schemaLocation="../../Schema/ContratoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestActualizarTCCAprobacionMessage">
    <part name="requestActualizarTCCAprobacionMessage" element="conMO:ActualizarTCCAprobacionRequest"/>
  </message>
  <message name="responseActualizarTCCAprobacionMessage">
    <part name="responseActualizarTCCAprobacionMessage" element="conMO:ActualizarTCCAprobacionResponse"/>
  </message>
  <portType name="ActualizarTCCAprobacion_ptt">
    <operation name="actualizarTCCAprobacion">
      <input message="tns:requestActualizarTCCAprobacionMessage"/>
      <output message="tns:responseActualizarTCCAprobacionMessage"/>
    </operation>
  </portType>
  <binding name="ActualizarTCCAprobacion_pttSOAP12Binding" type="tns:ActualizarTCCAprobacion_ptt">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="actualizarTCCAprobacion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ActualizarTCCAprobacionService/actualizarTCCAprobacion"/>
      <input>
        <soap12:body use="literal" parts="requestActualizarTCCAprobacionMessage"/>
      </input>
      <output>
        <soap12:body use="literal" parts="responseActualizarTCCAprobacionMessage"/>
      </output>
    </operation>
  </binding>
</definitions>