<wsdl:definitions name="ConsultarTCCConfiguracion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTCCConfiguracion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTCCConfiguracion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTCCConfiguracion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTCCConfiguracion_plt">
    <plt:role name="ConsultarTCCConfiguracion_role">
      <plt:portType name="tns:ConsultarTCCConfiguracion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTCCConfiguracion" schemaLocation="../XSD/ConsultarTCCConfiguracion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTCCConfiguracionInput_msg">
        <wsdl:part name="ConsultarTCCConfiguracionInput_msg" element="db:ConsultarTCCConfiguracionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTCCConfiguracionOutputCollection_msg">
        <wsdl:part name="ConsultarTCCConfiguracionOutputCollection" element="db:ConsultarTCCConfiguracionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTCCConfiguracion_ptt">
        <wsdl:operation name="ConsultarTCCConfiguracion">
            <wsdl:input message="tns:ConsultarTCCConfiguracionInput_msg"/>
            <wsdl:output message="tns:ConsultarTCCConfiguracionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>