<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="caseTwoGetPrimary" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindByIdProcess/caseTwoGetPrimary" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindByIdProcess/caseTwoGetPrimary" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoGetPrimary" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="caseTwoGetPrimary_plt">
      <plt:role name="caseTwoGetPrimary_role">
         <plt:portType name="tns:caseTwoGetPrimary_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseTwoGetPrimary" schemaLocation="../Schemas/caseTwoGetPrimary_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="caseTwoGetPrimarySelect_inputParameters">
      <wsdl:part name="caseTwoGetPrimarySelect_inputParameters" element="top:caseTwoGetPrimarySelect_idC2_appCodeC2_catIdC2InputParameters"/>
   </wsdl:message>
   <wsdl:message name="MdmMerchandHierarchiesCollection_msg">
      <wsdl:part name="MdmMerchandHierarchiesCollection" element="top:MdmMerchandHierarchiesCollection"/>
   </wsdl:message>
   <wsdl:portType name="caseTwoGetPrimary_ptt">
      <wsdl:operation name="caseTwoGetPrimarySelect">
         <wsdl:input message="tns:caseTwoGetPrimarySelect_inputParameters"/>
         <wsdl:output message="tns:MdmMerchandHierarchiesCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
