<wsdl:definitions name="ConsultarComisionDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/ConsultarComision/ConsultarComisionDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioLineaCredito/ConsultarComision/ConsultarComisionDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

  <plt:partnerLinkType name="ConsultarComisionDB_plt">
    <plt:role name="ConsultarComisionDB_role">
      <plt:portType name="tns:ConsultarComisionDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionDB" schemaLocation="../XSD/ConsultarComisionDB.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComisionDB" schemaLocation="../XSD/ConsultarComisionDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarComisionDBInput_msg">
        <wsdl:part name="ConsultarComisionDBInput_msg" element="db:ConsultarComisionDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarComisionDBOutputCollection_msg">
        <wsdl:part name="ConsultarComisionDBOutputCollection" element="db:ConsultarComisionDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarComisionDB_ptt">
        <wsdl:operation name="ConsultarComisionDB">
            <wsdl:input message="tns:ConsultarComisionDBInput_msg"/>
            <wsdl:output message="tns:ConsultarComisionDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>