<wsdl:definitions name="ConsultarCondicionByIdLineaCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCondicionByIdLineaCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarCondicionByIdLineaCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCondicionByIdLineaCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarCondicionByIdLineaCredito_plt">
    <plt:role name="ConsultarCondicionByIdLineaCredito_role">
      <plt:portType name="tns:ConsultarCondicionByIdLineaCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarCondicionByIdLineaCredito" schemaLocation="../XSD/ConsultarCondicionByIdLineaCredito.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarCondicionByIdLineaCreditoInput_msg">
        <wsdl:part name="ConsultarCondicionByIdLineaCreditoInput_msg" element="db:ConsultarCondicionByIdLineaCreditoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarCondicionByIdLineaCreditoOutputCollection_msg">
        <wsdl:part name="ConsultarCondicionByIdLineaCreditoOutputCollection" element="db:ConsultarCondicionByIdLineaCreditoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCondicionByIdLineaCredito_ptt">
        <wsdl:operation name="ConsultarCondicionByIdLineaCredito">
            <wsdl:input message="tns:ConsultarCondicionByIdLineaCreditoInput_msg"/>
            <wsdl:output message="tns:ConsultarCondicionByIdLineaCreditoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>