<wsdl:definitions
     name="ActualizarAdjunto"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DominioDocumento/CargarDocumento/ActualizarAdjunto"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DominioDocumento/CargarDocumento/ActualizarAdjunto"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarAdjunto"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarAdjunto_plt" >
    <plt:role name="ActualizarAdjunto_role" >
      <plt:portType name="tns:ActualizarAdjunto_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ActualizarAdjunto" schemaLocation="../XSD/ActualizarAdjunto_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="AdjuntoCollection_msg">
        <wsdl:part name="AdjuntoCollection" element="top:AdjuntoCollection"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarAdjunto_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:AdjuntoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
