<wsdl:definitions name="ConsultarReglasTarea_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarReglasTarea_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarReglasTarea_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarReglasTarea_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarReglasTarea_DB_plt">
    <plt:role name="ConsultarReglasTarea_DB_role">
      <plt:portType name="tns:ConsultarReglasTarea_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarReglasTarea_DB" schemaLocation="../XSD/ConsultarReglasTarea_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarReglasTarea_DBInput_msg">
        <wsdl:part name="ConsultarReglasTarea_DBInput_msg" element="db:ConsultarReglasTarea_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarReglasTarea_DBOutputCollection_msg">
        <wsdl:part name="ConsultarReglasTarea_DBOutputCollection" element="db:ConsultarReglasTarea_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarReglasTarea_DB_ptt">
        <wsdl:operation name="ConsultarReglasTarea_DB">
            <wsdl:input message="tns:ConsultarReglasTarea_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarReglasTarea_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>