<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeasonAPP/SeasonService/DBSeasonRMS" name="DBSeasonRMS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBSeasonRMS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeasonAPP/SeasonService/DBSeasonRMS"/>
    <wsdl:binding name="DBSeasonRMS_ptt-binding" type="dbs:DBSeasonRMS_ptt" xmlns:dbs="http://xmlns.oracle.com/pcbpel/adapter/db/SeasonAPP/SeasonService/DBSeasonRMS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBSeasonRMSSelect">
            <soap:operation soapAction="DBSeasonRMSSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>