<wsdl:definitions name="ConsultarTerminoByIdOperacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTerminoByIdOperacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarTerminoByIdOperacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTerminoByIdOperacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTerminoByIdOperacion_plt">
    <plt:role name="ConsultarTerminoByIdOperacion_role">
      <plt:portType name="tns:ConsultarTerminoByIdOperacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTerminoByIdOperacion" schemaLocation="../XSD/ConsultarTerminoByIdOperacion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTerminoByIdOperacionInput_msg">
        <wsdl:part name="ConsultarTerminoByIdOperacionInput_msg" element="db:ConsultarTerminoByIdOperacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTerminoByIdOperacionOutputCollection_msg">
        <wsdl:part name="ConsultarTerminoByIdOperacionOutputCollection" element="db:ConsultarTerminoByIdOperacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTerminoByIdOperacion_ptt">
        <wsdl:operation name="ConsultarTerminoByIdOperacion">
            <wsdl:input message="tns:ConsultarTerminoByIdOperacionInput_msg"/>
            <wsdl:output message="tns:ConsultarTerminoByIdOperacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>