<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="EnvioCobroSOR"
     targetNamespace="http://www.bcie.org/EnvioCobroSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/EnvioCobroSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EnvioCobro">
        <plnk:role name="EnvioCobro_PT" portType="tns:EnvioCobro_PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/EnvioCobroSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/EnvioCobroSOR.wsdl"/>
</wsdl:definitions>
