<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConsultarCumplimientoCondicionSAD"
     targetNamespace="http://www.bcie.org/ConsultarCumplimientoCondicionSAD"
     xmlns:tns="http://www.bcie.org/ConsultarCumplimientoCondicionSAD"
     xmlns:conBO="http://www.bcie.org/CondicionMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestConsultarCumplimientoCondicionMessage">
        <wsdl:part name="request" element="conBO:ConsultarCumplimientoCondicionRequest"/>
    </wsdl:message>
    <wsdl:message name="responseConsultarCumplimientoCondicionMessage">
        <wsdl:part name="response" element="conBO:ConsultarCumplimientoCondicionResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarCumplimientoCondicion_PT">
        <wsdl:operation name="ConsultarCumplimientoCondicion">
            <wsdl:input message="tns:requestConsultarCumplimientoCondicionMessage"/>
            <wsdl:output message="tns:responseConsultarCumplimientoCondicionMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsultarCumplimientoCondicion_PTSOAP12Binding" type="tns:ConsultarCumplimientoCondicion_PT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ConsultarCumplimientoCondicion">
            <soap12:operation style="document" soapAction="ConsultarCumplimientoCondicion" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
