<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/EvaluacionError/Payload/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PC06/EvaluacionErrorPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="EvaluacionErrorPayloadType"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/EvaluacionError/Payload/V1"/>
        <oracle-xsl-mapper:param name="payload"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/Evaluacion/V1/EvaluacionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="EvaluacionErrorPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [TUE JAN 19 20:35:54 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:EvaluacionErrorPayload>
      <tns:Header>
        <header:Operacion>
          <ns1:CodigoOperacion>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:CodigoOperacion"/>
          </ns1:CodigoOperacion>
          <ns1:NombreOperacion>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:NombreOperacion"/>
          </ns1:NombreOperacion>
          <ns1:ResponsableOperacion>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:ResponsableOperacion"/>
          </ns1:ResponsableOperacion>
          <ns1:CodigoCliente>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:CodigoCliente"/>
          </ns1:CodigoCliente>
          <ns1:NombreCliente>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:NombreCliente"/>
          </ns1:NombreCliente>
          <ns1:CodigoProducto>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:CodigoProducto"/>
          </ns1:CodigoProducto>
          <ns1:NombreProducto>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:NombreProducto"/>
          </ns1:NombreProducto>
          <ns1:MontoSolicitado>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:MontoSolicitado"/>
          </ns1:MontoSolicitado>
          <ns1:Pais>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Operacion/ns1:Pais"/>
          </ns1:Pais>
        </header:Operacion>
        <header:Tarea>
          <ns2:CodigoTarea>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Tarea/ns2:CodigoTarea"/>
          </ns2:CodigoTarea>
          <ns2:NombreTarea>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Tarea/ns2:NombreTarea"/>
          </ns2:NombreTarea>
          <ns2:CodigoRol>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Tarea/ns2:CodigoRol"/>
          </ns2:CodigoRol>
          <ns2:NombreRol>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Tarea/ns2:NombreRol"/>
          </ns2:NombreRol>
          <ns2:CodigoProceso>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Tarea/ns2:CodigoProceso"/>
          </ns2:CodigoProceso>
          <ns2:NombreProceso>
            <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Header/header:Tarea/ns2:NombreProceso"/>
          </ns2:NombreProceso>
        </header:Tarea>
        <xsl:for-each select="/ns0:EvaluacionErrorPayloadType/ns0:Header/parameter:ParameterType">
          <parameter:ParameterType>
            <parameter:parameterName>
              <xsl:value-of select="parameter:parameterName"/>
            </parameter:parameterName>
            <parameter:parameterValue>
              <xsl:value-of select="parameter:parameterValue"/>
            </parameter:parameterValue>
          </parameter:ParameterType>
        </xsl:for-each>
      </tns:Header>
      <tns:Configuration>
        <tns:requiereSIEMAS>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:requiereSIEMAS"/>
        </tns:requiereSIEMAS>
        <tns:requiereIBCIE>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:requiereIBCIE"/>
        </tns:requiereIBCIE>
        <tns:requiereModificarSIEMAS>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:requiereModificarSIEMAS"/>
        </tns:requiereModificarSIEMAS>
        <tns:requiereModificarIBCIE>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:requiereModificarIBCIE"/>
        </tns:requiereModificarIBCIE>
        <tns:retorno>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:retorno"/>
        </tns:retorno>
        <tns:resultado>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:resultado"/>
        </tns:resultado>
        <tns:tipoEvaluacion>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Configuration/ns0:tipoEvaluacion"/>
        </tns:tipoEvaluacion>
      </tns:Configuration>
      <tns:EquipoPayload>
        <tns:AnalistaAED>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:EquipoPayload/ns0:AnalistaAED"/>
        </tns:AnalistaAED>
        <tns:Control>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:EquipoPayload/ns0:Control"/>
        </tns:Control>
      </tns:EquipoPayload>
      <tns:EquipoEjecucionPayload>
        <tns:AnalistaAED>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:EquipoEjecucion/ns0:AnalistaAED"/>
        </tns:AnalistaAED>
        <tns:Control>
          <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:EquipoEjecucion/ns0:Control"/>
        </tns:Control>
      </tns:EquipoEjecucionPayload>
      <xsl:for-each select="/ns0:EvaluacionErrorPayloadType/parameter:ParameterType">
        <parameter:ParameterType>
          <parameter:parameterName>
            <xsl:value-of select="parameter:parameterName"/>
          </parameter:parameterName>
          <parameter:parameterValue>
            <xsl:value-of select="parameter:parameterValue"/>
          </parameter:parameterValue>
        </parameter:ParameterType>
      </xsl:for-each>
      <tns:ErrorMsg>
        <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:ErrorMsg"/>
      </tns:ErrorMsg>
      <tns:ErrorNamespace>
        <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:ErrorNamespace"/>
      </tns:ErrorNamespace>
      <tns:ErrorFault>
        <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:ErrorFault"/>
      </tns:ErrorFault>
      <tns:Accion>
        <xsl:value-of select="/ns0:EvaluacionErrorPayloadType/ns0:Accion"/>
      </tns:Accion>
    </tns:EvaluacionErrorPayload>
  </xsl:template>
</xsl:stylesheet>
