<wsdl:definitions name="MerchandiseHierarchyTranslationBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslationApp/MerchandiseHierarchyTranslation/MerchandiseHierarchyTranslationBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslationApp/MerchandiseHierarchyTranslation/MerchandiseHierarchyTranslationBS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/MerchandiseHierarchyTranslationBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="MerchandiseHierarchyTranslationBS_plt">
    <plt:role name="MerchandiseHierarchyTranslationBS_role">
      <plt:portType name="tns:MerchandiseHierarchyTranslationBS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/MerchandiseHierarchyTranslationBS" schemaLocation="MerchandiseHierarchyTranslationBS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="MerchandiseHierarchyTranslationBSSelect_inputParameters">
        <wsdl:part name="MerchandiseHierarchyTranslationBSSelect_inputParameters" element="top:MerchandiseHierarchyTranslationBSSelect_pDepartment_pClass_pSubClassInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmMerchandhierarTranslationsCollection_msg">
        <wsdl:part name="MdmMerchandhierarTranslationsCollection" element="top:MdmMerchandhierarTranslationsCollection"/>
    </wsdl:message>
    <wsdl:portType name="MerchandiseHierarchyTranslationBS_ptt">
        <wsdl:operation name="MerchandiseHierarchyTranslationBSSelect">
            <wsdl:input message="tns:MerchandiseHierarchyTranslationBSSelect_inputParameters"/>
            <wsdl:output message="tns:MdmMerchandhierarTranslationsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>