<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslationApp/MerchandiseHierarchyTranslation/MerchandiseHierarchyTranslationBS" name="MerchandiseHierarchyTranslationBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="MerchandiseHierarchyTranslationBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslationApp/MerchandiseHierarchyTranslation/MerchandiseHierarchyTranslationBS"/>
    <wsdl:binding name="MerchandiseHierarchyTranslationBS_ptt-binding" type="mer:MerchandiseHierarchyTranslationBS_ptt" xmlns:mer="http://xmlns.oracle.com/pcbpel/adapter/db/MerchandiseHierarchyTranslationApp/MerchandiseHierarchyTranslation/MerchandiseHierarchyTranslationBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="MerchandiseHierarchyTranslationBSSelect">
            <soap:operation soapAction="MerchandiseHierarchyTranslationBSSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>