<wsdl:definitions
     name="ConsultarEquipoTrabajoByClienteProceso"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarEquipoTrabajoByClienteProceso/ConsultarEquipoTrabajoByClienteProceso"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarEquipoTrabajoByClienteProceso/ConsultarEquipoTrabajoByClienteProceso"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarEquipoTrabajoByClienteProceso"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarEquipoTrabajoByClienteProceso_plt" >
    <plt:role name="ConsultarEquipoTrabajoByClienteProceso_role" >
      <plt:portType name="tns:ConsultarEquipoTrabajoByClienteProceso_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarEquipoTrabajoByClienteProceso" schemaLocation="../XSD/ConsultarEquipoTrabajoByClienteProceso.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarEquipoTrabajoByClienteProcesoInput_msg">
        <wsdl:part name="ConsultarEquipoTrabajoByClienteProcesoInput_msg" element="db:ConsultarEquipoTrabajoByClienteProcesoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarEquipoTrabajoByClienteProcesoOutputCollection_msg">
        <wsdl:part name="ConsultarEquipoTrabajoByClienteProcesoOutputCollection" element="db:ConsultarEquipoTrabajoByClienteProcesoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarEquipoTrabajoByClienteProceso_ptt">
        <wsdl:operation name="ConsultarEquipoTrabajoByClienteProceso">
            <wsdl:input message="tns:ConsultarEquipoTrabajoByClienteProcesoInput_msg"/>
            <wsdl:output message="tns:ConsultarEquipoTrabajoByClienteProcesoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
