<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="AplicarAmpliacionSOR" targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarAmpliacionSOR" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarAmpliacionSOR" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.oracle.com/bpel/extension" xmlns:ns2="http://www.bcie.org/LineaCreditoMO">
   <plnk:partnerLinkType name="AplicarAmpliacionSOAP">
      <plnk:role name="AplicarAmpliacion_ptt" portType="tns:AplicarAmpliacion_ptt"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/AplicarAmpliacionSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/AplicarAmpliacionSOR.wsdl"/>
   <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Schema/LineaCreditoMO.xsd"/>
      </xsd:schema>
   </wsdl:types>
</wsdl:definitions>
