<wsdl:definitions name="GetFullHierarchyDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/GetFullHierarchyDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/CommonTranslationAPP/GetFullHierarchyDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetFullHierarchyDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="GetFullHierarchyDB_plt">
    <plt:role name="GetFullHierarchyDB_role">
      <plt:portType name="tns:GetFullHierarchyDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetFullHierarchyDB" schemaLocation="../../../Resources/GetFullHierarchyDB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="GetFullHierarchyDBSelect_inputParameters">
        <wsdl:part name="GetFullHierarchyDBSelect_inputParameters" element="top:GetFullHierarchyDBSelect_IdDeptoRms_IdClaseRMS_IdTipoRMSInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmMerchandhierarTranslationsCollection_msg">
        <wsdl:part name="MdmMerchandhierarTranslationsCollection" element="top:MdmMerchandhierarTranslationsCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetFullHierarchyDB_ptt">
        <wsdl:operation name="GetFullHierarchyDBSelect">
            <wsdl:input message="tns:GetFullHierarchyDBSelect_inputParameters"/>
            <wsdl:output message="tns:MdmMerchandhierarTranslationsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>