<wsdl:definitions name="RetailStoreTranslationProcess" targetNamespace="http://xmlns.oracle.com/RetailStoreApp/RetailStoreTranslate/RetailStoreTranslationProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/RetailStoreApp/RetailStoreTranslate/RetailStoreTranslationProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/RetailStoreTranslate!1.0/WSDLs/RetailStoreTranslationProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="RetailStoreTranslationProcess">
        <plnk:role name="RetailStoreTranslationProcessProvider" portType="client:RetailStoreTranslationProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/caseOneDb" schemaLocation="Schema/RetailStoreTranslationProcessSchema.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="RetailStoreTranslationProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:caseOneDbSelect_idC1_appCodeC1_targetAppCodeC1InputParameters"/>
    </wsdl:message>
    <wsdl:message name="RetailStoreTranslationProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:MdmRetailstoresCollection"/>
    </wsdl:message>
    <wsdl:portType name="RetailStoreTranslationProcess">
        <wsdl:operation name="translate">
            <wsdl:input message="client:RetailStoreTranslationProcessRequestMessage"/>
            <wsdl:output message="client:RetailStoreTranslationProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RetailStoreTranslationProcessBinding" type="client:RetailStoreTranslationProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="translate">
            <soap:operation style="document" soapAction="translate"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="RetailStoreTranslationService_ep">
        <wsdl:port name="RetailStoreTranslationProcess_pt" binding="client:RetailStoreTranslationProcessBinding">
            <soap:address location="http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/RetailStoreTranslate/RetailStoreTranslationService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>