<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarOperacionLogico" name="EliminarOperacionLogico-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarOperacionLogicoDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarOperacionLogico"/>
    <wsdl:binding name="EliminarOperacionLogico_ptt-binding" type="elim:EliminarOperacionLogico_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarOperacionLogico">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarOperacionLogico">
            <soap:operation soapAction="EliminarOperacionLogico"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>