<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ReasignacionRCProcess" 
				  xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/ReasignacionRCProcess" 
				  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" 
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
				  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ReasignacionRCProcess" schemaLocation="../../Schema/PU02/ReasignacionRCProcess.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="InicioReasignacionRC">
		<wsdl:part name="parameters" element="tns:InicioReasignacionRC"/>
	</wsdl:message>
	<wsdl:message name="FinReasignacionRC">
		<wsdl:part name="parameters" element="tns:FinReasignacionRC"/>
	</wsdl:message>
	<wsdl:portType name="ReasignacionRCProcessPortType">
		<wsdl:operation name="InicioReasignacionRC">
			<wsdl:input message="tns:InicioReasignacionRC"/>
		</wsdl:operation>
		<wsdl:operation name="FinReasignacionRC">
			<wsdl:input message="tns:FinReasignacionRC"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ReasignacionRCProcessBinding" type="tns:ReasignacionRCProcessPortType">
		<wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="InicioReasignacionRC">
			<wsdlsoap:operation style="document" soapAction="InicioReasignacionRC"/>
			<wsdl:input>
				<wsdlsoap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="FinReasignacionRC">
			<wsdlsoap:operation style="document" soapAction="FinReasignacionRC"/>
			<wsdl:input>
				<wsdlsoap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<plnk:partnerLinkType name="ReasignacionRCProcessPortTypePartnerLinkType">
		<plnk:role name="ReasignacionRCProcessPortTypeProvider">
			<plnk:portType name="tns:ReasignacionRCProcessPortType"/>
		</plnk:role>
	</plnk:partnerLinkType>
</wsdl:definitions>
