<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AdvancedShipmentNoticeApp/SynAbroadAdvancedShipmentNoticeRMSDbReference" name="SynAbroadAdvancedShipmentNoticeRMSDbReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SynAbroadAdvancedShipmentNoticeRMSDbReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AdvancedShipmentNoticeApp/SynAbroadAdvancedShipmentNoticeRMSDbReference"/>
    <wsdl:binding name="SynAbroadAdvancedShipmentNoticeRMSDbReference_ptt-binding" type="syn:SynAbroadAdvancedShipmentNoticeRMSDbReference_ptt" xmlns:syn="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/AdvancedShipmentNoticeApp/SynAbroadAdvancedShipmentNoticeRMSDbReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SynAbroadAdvancedShipmentNoticeRMSDbReference">
            <soap:operation soapAction="SynAbroadAdvancedShipmentNoticeRMSDbReference"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>