<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://xmlns.banesco.com/eopt/PartyStaffInq_V1.0"
                xmlns:ns0="http://www.temenos.com/T24/ofs/Response"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon"
                xmlns:ns1="http://www.temenos.com/T24/ofs/BPAENQSTAFFPJType"
                xmlns:ns2="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Common_V1.0" xmlns:fn="http://www.w3.org/2005/xpath-functions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/BpaEnqStaffPJ/EnquiryCustomerRepCorpPJConsultaClienteRepCorpPJResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="BPAENQSTAFFPJResponse"
                                       namespace="http://www.temenos.com/T24/ofs/Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Party/PartyStaffInq/PartyStaffInq_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="PartyStaffInqRs"
                                       namespace="http://xmlns.banesco.com/eopt/PartyStaffInq_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON MAR 19 11:53:08 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:include href="../../../../Commons/xslt/Template/TemplateServiceUtil.xsl"/>
  <xsl:template match="/">
    <tns:PartyStaffInqRs>
      <xsl:variable name="statusCode">
        <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'T24', /ns0:BPAENQSTAFFPJResponse/ResponseCommon/Status, 'CNCODE', 'M0006' )"/>
      </xsl:variable>
      <xsl:choose>
        <xsl:when test="$statusCode = &quot;M0000&quot; and /ns0:BPAENQSTAFFPJResponse/BPAENQSTAFFPJ">
          <tns:Party>
            <tns:PartyKey>
              <xsl:if test="/ns0:BPAENQSTAFFPJResponse/BPAENQSTAFFPJ/gBPAENQSTAFFPJDetailType/mBPAENQSTAFFPJDetailType[1]/ID/text()">
                <eoPar:PartyId>
                  <xsl:value-of select="/ns0:BPAENQSTAFFPJResponse/BPAENQSTAFFPJ/gBPAENQSTAFFPJDetailType/mBPAENQSTAFFPJDetailType[1]/ID"/>
                </eoPar:PartyId>
              </xsl:if>
            </tns:PartyKey>
            <tns:OrgPartyInfo>
              <tns:OrgData>                
                <xsl:for-each select="/ns0:BPAENQSTAFFPJResponse/BPAENQSTAFFPJ/gBPAENQSTAFFPJDetailType/mBPAENQSTAFFPJDetailType">
                  <eoPar:Staff>
                    <xsl:if test="BIRTHDATE/text()">
                      <eoPar:BirthDt>
                        <xsl:value-of select="BIRTHDATE"/>
                      </eoPar:BirthDt>
                    </xsl:if>
                    <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                    <xsl:if test="COUNTRYCONSTI/text()">
                      <eoPar:CountryBirth>
                        <ns3:CountryCode>
                          <xsl:value-of select="COUNTRYCONSTI"/>
                        </ns3:CountryCode>
                      </eoPar:CountryBirth>
                    </xsl:if>                    
                    <eoPar:FATCA>
                      <!-- Se elimina conforme al cambio solicitado por negocio, Ejecución 21-05-2018 -->
                      <!--xsl:if test="CLIENTTYPE/text()">
                        <eoPar:FatcaType>
                          <xsl:value-of select="CLIENTTYPE"/>
                        </eoPar:FatcaType>
                      </xsl:if>
                      <xsl:if test="FORMTYPE/text()">
                        <eoPar:FormId>
                          <xsl:value-of select="FORMTYPE"/>
                        </eoPar:FormId>
                      </xsl:if>                      
                      <xsl:if test="GREENCARD/text()">
                        <eoPar:GreenCard>
                          <xsl:value-of select="GREENCARD"/>
                        </eoPar:GreenCard>
                      </xsl:if-->
                      <xsl:if test="FATCANATIONAL/text()">
                        <eoPar:OtherNationality>
                          <!--xsl:value-of select="FATCANATIONAL"/-->
                          <xsl:call-template name="Boolean_Regex">
                            <xsl:with-param name="operation">INQ</xsl:with-param>
                            <xsl:with-param name="parametro">
                              <xsl:value-of select="FATCANATIONAL"></xsl:value-of>
                            </xsl:with-param>
                          </xsl:call-template>
                          <!--xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCANATIONAL, 'VALUE', '2')"/-->
                          <!--xsl:value-of select="dvm:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCANATIONAL, 'VALUE', '2', 'TARGET', 'T24' )"/-->
                        </eoPar:OtherNationality>
                      </xsl:if>
                      <!-- Se elimina conforme al cambio solicitado por negocio, Ejecución 21-05-2018 -->
                      <!--xsl:if test="SOCIALSECNO/text()">
                        <eoPar:SSN>
                          <xsl:value-of select="SOCIALSECNO"/>
                        </eoPar:SSN>
                      </xsl:if>
                      <xsl:if test="TINCODE/text()">
                        <eoPar:TIN>
                          <xsl:value-of select="TINCODE"/>
                        </eoPar:TIN>
                      </xsl:if-->
                      <xsl:if test="FATCAUS183/text()">
                        <eoPar:US183Permanence>
                          <xsl:call-template name="Boolean_Regex">
                            <xsl:with-param name="operation">INQ</xsl:with-param>
                            <xsl:with-param name="parametro">
                              <xsl:value-of select="FATCAUS183"></xsl:value-of>
                            </xsl:with-param>
                          </xsl:call-template>
                          <!--xsl:value-of select="FATCAUS183"/-->
                          <!--xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUS183, 'VALUE', '2')"/-->
                          <!--xsl:value-of select="dvm:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUS183, 'VALUE', '2', 'TARGET', 'T24' )"/-->
                        </eoPar:US183Permanence>
                      </xsl:if>
                      <xsl:if test="FATCAUSRELATED/text()">
                        <eoPar:USRelated>
                          <xsl:call-template name="Boolean_Regex">
                            <xsl:with-param name="operation">INQ</xsl:with-param>
                            <xsl:with-param name="parametro">
                              <xsl:value-of select="FATCAUSRELATED"></xsl:value-of>
                            </xsl:with-param>
                          </xsl:call-template>
                          <!--xsl:value-of select="FATCAUSRELATED"/-->
                          <!--xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUSRELATED, 'VALUE', '2')"/-->
                          <!--xsl:value-of select="dvm:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUSRELATED, 'VALUE', '2', 'TARGET', 'T24' )"/-->
                        </eoPar:USRelated>
                      </xsl:if>
                      <xsl:if test="FATCAUSRESID/text()">
                        <eoPar:USResid>
                          <xsl:call-template name="Boolean_Regex">
                            <xsl:with-param name="operation">INQ</xsl:with-param>
                            <xsl:with-param name="parametro">
                              <xsl:value-of select="FATCAUSRESID"></xsl:value-of>
                            </xsl:with-param>
                          </xsl:call-template>
                          <!--xsl:value-of select="FATCAUSRESID"/-->
                          <!--xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUSRESID, 'VALUE', '2') "/-->
                          <!--xsl:value-of select="dvm:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUSRESID, 'VALUE', '2', 'TARGET', 'T24') "/-->
                        </eoPar:USResid>
                      </xsl:if>
                      <xsl:if test="FATCAUSSIGNOR/text()">
                        <eoPar:USSignor>
                          <xsl:call-template name="Boolean_Regex">
                            <xsl:with-param name="operation">INQ</xsl:with-param>
                            <xsl:with-param name="parametro">
                              <xsl:value-of select="FATCAUSSIGNOR"></xsl:value-of>
                            </xsl:with-param>
                          </xsl:call-template>
                          <!--xsl:value-of select="FATCAUSSIGNOR"/-->
                          <!--xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUSSIGNOR, 'VALUE', '2')"/-->
                          <!--xsl:value-of select="dvm:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', FATCAUSSIGNOR, 'VALUE', '2', 'TARGET', 'T24')"/-->
                        </eoPar:USSignor>
                      </xsl:if>
                    </eoPar:FATCA>
                    <xsl:if test="GENDER/text()">
                      <eoPar:Gender>
                        <xsl:value-of select="GENDER"/>
                      </eoPar:Gender>
                    </xsl:if>
                    <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                    <xsl:if test="DATECONSTITUTION/text()">
                      <eoPar:OrgEstablishDt>
                        <xsl:value-of select="DATECONSTITUTION"/>
                      </eoPar:OrgEstablishDt>
                    </xsl:if>
                    <xsl:variable name="TipoPersona">
                      <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', PERSONTYPE, 'VALUE', '0')"></xsl:value-of>
                    </xsl:variable>
                    <eoPar:PartyData>
                      <eoPar:Contact>
                        <ns3:Locator>
                          <ns3:PostAddr>
                            <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                            <xsl:if test="ADDRESSREFERENCE/text()">
                              <ns3:AddrDesc>                                
                                  <xsl:value-of select="ADDRESSREFERENCE"/>                                
                              </ns3:AddrDesc>
                            </xsl:if>
                            <xsl:if test="BUILDING/text()">
                              <ns3:Building>
                                <ns3:Desc>
                                  <xsl:value-of select="BUILDING"/>
                                </ns3:Desc>
                              </ns3:Building>
                            </xsl:if>
                            <xsl:if test="TOWN/text()">
                              <ns3:City>
                                <ns3:Cod>
                                  <xsl:value-of select="TOWN"/>
                                </ns3:Cod>
                              </ns3:City>
                            </xsl:if>
                            <xsl:if test="DISTRICT/text()">
                              <ns3:CountyDistrict>
                                <ns3:Cod>
                                  <xsl:value-of select="DISTRICT"/>
                                </ns3:Cod>
                              </ns3:CountyDistrict>
                            </xsl:if>
                            <xsl:if test="HOUSENO/text()">
                              <ns3:HouseNumber>
                                <xsl:value-of select="HOUSENO"/>
                              </ns3:HouseNumber>
                            </xsl:if>
                            <xsl:if test="SECTOR/text()">
                              <ns3:Jurisdiction>
                                <ns3:Cod>
                                  <xsl:value-of select="SECTOR"/>
                                </ns3:Cod>
                              </ns3:Jurisdiction>
                            </xsl:if>
                            <xsl:if test="POSTCODE/text()">
                              <ns3:PostalCode>
                                <xsl:value-of select="POSTCODE"/>
                              </ns3:PostalCode>
                            </xsl:if>
                            <xsl:if test="PROVINCE/text()">
                              <ns3:Province>
                                <ns3:Cod>
                                  <xsl:value-of select="PROVINCE"/>
                                </ns3:Cod>
                              </ns3:Province>
                            </xsl:if>
                            <xsl:if test="STREET/text()">
                              <ns3:Street>
                                <xsl:value-of select="STREET"/>
                              </ns3:Street>
                            </xsl:if>
                            <xsl:if test="COMPCOUNTRY/text()">
                              <ns3:Country>
                                <ns3:CountryCode>
                                  <xsl:value-of select="COMPCOUNTRY"/>
                                </ns3:CountryCode>
                              </ns3:Country>
                            </xsl:if>
                          </ns3:PostAddr>
                          <xsl:if test="PHONE/text()">
                            <ns3:Phone>
                              <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                              <xsl:if test="PHONECODE/text()">
                                <ns3:AreaCode>
                                  <xsl:value-of select="PHONECODE"/>
                                </ns3:AreaCode>
                              </xsl:if> 
                              <xsl:if test="PHONE/text()">
                                <ns3:PhoneNum>
                                  <xsl:value-of select="PHONE"/>
                                </ns3:PhoneNum>
                              </xsl:if>                            
                              <ns3:PhoneType>Home</ns3:PhoneType>
                            </ns3:Phone>  
                          </xsl:if>                          
                          <xsl:if test="OFFICEPHONE/text()">
                            <ns3:Phone>
                              <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                              <xsl:if test="OFFICECODE/text()">
                                <ns3:AreaCode>
                                  <xsl:value-of select="OFFICECODE"/>
                                </ns3:AreaCode>
                              </xsl:if> 
                              <xsl:if test="OFFICEPHONE">
                                <ns3:PhoneNum>
                                  <xsl:value-of select="OFFICEPHONE"/>
                                </ns3:PhoneNum>
                              </xsl:if>                              
                              <ns3:PhoneType>Office</ns3:PhoneType>
                            </ns3:Phone>
                          </xsl:if>
                          <xsl:if test="OTHERPHONE/text()">
                            <ns3:Phone>
                              <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                              <xsl:if test="OTHERCODE/text()">
                                <ns3:AreaCode>
                                  <xsl:value-of select="OTHERCODE"/>
                                </ns3:AreaCode>
                              </xsl:if> 
                              <xsl:if test="OTHERPHONE/text()">
                                <ns3:PhoneNum>
                                  <xsl:value-of select="OTHERPHONE"/>
                                </ns3:PhoneNum>
                              </xsl:if>                              
                              <ns3:PhoneType>Other</ns3:PhoneType>
                            </ns3:Phone>
                          </xsl:if>
                        </ns3:Locator>
                      </eoPar:Contact>
                      <xsl:if test="NATIONALITY/text()">
                        <eoPar:Nationality>
                          <xsl:value-of select="NATIONALITY"/>
                        </eoPar:Nationality>
                      </xsl:if>
                      
                      <xsl:choose>
                        <xsl:when test="$TipoPersona='1'">
                          <eoPar:IssuedIdent>
                            <eoPar:Ident>
                              <eoPar:IssuedIdentValue>
                                <xsl:value-of select="IDMAINSTAFF"/>
                              </eoPar:IssuedIdentValue>
                            </eoPar:Ident>
                          </eoPar:IssuedIdent>
                        </xsl:when>
                        <xsl:when test="$TipoPersona='2'">
                          <eoPar:IssuedIdent>
                            <eoPar:Ident>
                              <eoPar:IssuedIdentValue>
                                <xsl:value-of select="LEGALID"/>
                              </eoPar:IssuedIdentValue>
                            </eoPar:Ident>
                          </eoPar:IssuedIdent>
                        </xsl:when>
                      </xsl:choose>                     
                    </eoPar:PartyData>
                    <eoPar:PartyKey>
                      <xsl:if test="selFldID/text()">
                        <eoPar:PartyId>
                          <xsl:value-of select="selFldID"/>
                        </eoPar:PartyId>
                      </xsl:if>
                      <eoPar:PartyType>
                        <xsl:value-of select="$TipoPersona"/>
                        <!--xsl:value-of select="PERSONTYPE"/-->
                      </eoPar:PartyType>
                    </eoPar:PartyKey>
                    <eoPar:PEPData>
                      <eoPar:IsPEP>
                        <!--xsl:value-of select="PEP"/-->  
                        <xsl:call-template name="Boolean_Regex">
                          <xsl:with-param name="operation">INQ</xsl:with-param>
                          <xsl:with-param name="parametro">
                            <xsl:value-of select="PEP"></xsl:value-of>
                          </xsl:with-param>
                        </xsl:call-template>
                        <!--xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', PEP, 'VALUE', '2')"/-->
                        <!--xsl:value-of select="dvm:lookupValue ('Commons/dvm/ServiceProperties', 'CODE', PEP, 'VALUE', '2','TARGET','T24' )"/-->
                      </eoPar:IsPEP>
                      <!-- Se elimina conforme al cambio solicitado por negocio, Ejecución 21-05-2018 -->
                      <!--eoPar:PEPRelated>
                        <eoPar:PersonData>
                          <xsl:if test="PEPCOUNTRYID/text()">
                            <eoPar:Contact>
                              <ns3:Locator>
                                <ns3:PostAddr>
                                  <ns3:Country>
                                    <ns3:CountryCode>
                                      <xsl:value-of select="PEPCOUNTRYID"/>
                                    </ns3:CountryCode>
                                  </ns3:Country>
                                </ns3:PostAddr>
                              </ns3:Locator>
                            </eoPar:Contact>
                          </xsl:if>                          
                          <xsl:if test="PEPNATIONALITY/text()">
                            <eoPar:Nationality>
                              <xsl:value-of select="PEPNATIONALITY"/>
                            </eoPar:Nationality>
                          </xsl:if>
                          <xsl:if test="PEPNAME/text()">
                            <eoPar:PersonName>
                              <eoPar:FullName>
                                <xsl:value-of select="PEPNAME"/>
                              </eoPar:FullName>
                            </eoPar:PersonName>
                          </xsl:if>
                        </eoPar:PersonData>                       
                        <xsl:if test="PEPPUBLICPOS/text()">
                          <eoPar:PublicPos>
                            <xsl:value-of select="PEPPUBLICPOS"/>
                          </eoPar:PublicPos>
                        </xsl:if>                        
                        <xsl:if test="PEPRELTYPE/text()">
                          <eoPar:RelType>
                            <xsl:value-of select="PEPRELTYPE"/>
                          </eoPar:RelType>
                        </xsl:if>
                      </eoPar:PEPRelated-->
                    </eoPar:PEPData>                    
                    <xsl:if test="NAMEMAINSTAFF/text()">
                      <eoPar:PersonName>                        
                        <xsl:if test="NAMEMAINSTAFF/text()">
                          <eoPar:FirstName>
                            <xsl:value-of select="NAMEMAINSTAFF"/>
                          </eoPar:FirstName>
                        </xsl:if> 
                        <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                        <xsl:if test="FIRSTSURNAME/text()">
                          <eoPar:LastName>
                            <xsl:value-of select="FIRSTSURNAME"/>
                          </eoPar:LastName>
                        </xsl:if>
                        <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                        <xsl:if test="SECONSURNAME/text()">
                          <eoPar:SecondLastName>
                            <xsl:value-of select="SECONSURNAME"/>
                          </eoPar:SecondLastName>
                        </xsl:if>                        
                        <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                        <xsl:if test="SECMAINSTAFF/text()">
                          <eoPar:SecondName>
                            <xsl:value-of select="SECMAINSTAFF"/>
                          </eoPar:SecondName>
                        </xsl:if>                       
                      </eoPar:PersonName>
                    </xsl:if>
                    <xsl:if test="PROFESSION/text()">
                      <eoPar:Profession>
                        <ns3:Value>
                          <xsl:value-of select="PROFESSION"/>
                        </ns3:Value>
                      </eoPar:Profession>
                    </xsl:if>
                    <!-- Agregado por cambio solicitado, ejecución 22-05-2018 -->
                    <xsl:if test="LTSHARESPERCENT/text()">
                      <eoPar:Shareholding>
                        <xsl:value-of select="LTSHARESPERCENT"/>
                      </eoPar:Shareholding>
                    </xsl:if>
                    <!-- Agregado por cambio solicitado, ejecución 23-05-2018 -->                    
                    <xsl:if test="SHARETYPE/text()">
                      <eoPar:SharesType>
                        <ns3:Cod>
                          <xsl:value-of select="SHARETYPE"/>
                        </ns3:Cod>
                      </eoPar:SharesType>
                    </xsl:if>                    
                    <!--xsl:if test="SHARETYPE/text()">
                      <eoPar:Shareholding>
                        <xsl:value-of select="SHARETYPE"/>                        
                      </eoPar:Shareholding>
                    </xsl:if-->
                    <xsl:if test="POSITIONMAINSTAFF/text()">
                      <eoPar:StaffPosition>
                        <xsl:value-of select="POSITIONMAINSTAFF"/>
                      </eoPar:StaffPosition>
                    </xsl:if>
                  </eoPar:Staff>
                </xsl:for-each>
              </tns:OrgData>
            </tns:OrgPartyInfo>
          </tns:Party>
        </xsl:when>
      </xsl:choose>
      <tns:Status>
        <eoStatus:StatusCode>
          <xsl:value-of select="$statusCode"/>
        </eoStatus:StatusCode>
        <eoStatus:StatusDesc>
          <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'T24', /ns0:BPAENQSTAFFPJResponse/ResponseCommon/Status, 'CNDESC', 'FALLO EN LA OPERACION' )"/>
        </eoStatus:StatusDesc>
        <eoStatus:AdditionalStatus>
          <eoStatus:StatusCode>
            <xsl:value-of select="/ns0:BPAENQSTAFFPJResponse/ResponseCommon/Status"/>
          </eoStatus:StatusCode>
          <eoStatus:StatusDesc>
            <xsl:value-of select="/ns0:BPAENQSTAFFPJResponse/ResponseCommon/Message"/>
          </eoStatus:StatusDesc>
        </eoStatus:AdditionalStatus>
      </tns:Status>
    </tns:PartyStaffInqRs>
  </xsl:template>
</xsl:stylesheet>