<wsdl:definitions
     name="CrearCliente"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/CrearCliente"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OperacionesBusinessServices/PropagaOperacion/CrearCliente"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearCliente"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearCliente_plt" >
    <plt:role name="CrearCliente_role" >
      <plt:portType name="tns:CrearCliente_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearCliente" schemaLocation="../XSD/CrearCliente_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ClientesCollection_msg">
        <wsdl:part name="ClientesCollection" element="top:ClientesCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearCliente_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ClientesCollection_msg"/>
            <wsdl:output message="tns:ClientesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
