package org.bcie.fenix.common.model.vo;

import oracle.jbo.server.ViewObjectImpl;

import org.bcie.fenix.common.model.vo.common.CargoVO;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 10 20:04:21 CDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CargoVOImpl extends ViewObjectImpl implements CargoVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CargoVOImpl() {
    }


    public void setOperacionId(String param) {
        System.out.println("Operacion: "+ param);
                if(null!= param && param.trim().length()>0){
                     setNamedWhereClauseParam("OperacionId", param);
                }
    }

    /**
     * Returns the bind variable value for OperacionId.
     * @return bind variable value for OperacionId
     */
    public String getOperacionId() {
        return (String) getNamedWhereClauseParam("OperacionId");
    }

    /**
     * Returns the variable value for estadoPagado.
     * @return variable value for estadoPagado
     */
    public Integer getestadoPagado() {
        return (Integer) ensureVariableManager().getVariableValue("estadoPagado");
    }

    /**
     * Sets <code>value</code> for variable estadoPagado.
     * @param value value to bind as estadoPagado
     */
    public void setestadoPagado(Integer value) {
        ensureVariableManager().setVariableValue("estadoPagado", value);
    }


    /**
     * Returns the variable value for estadoDispensado.
     * @return variable value for estadoDispensado
     */
    public Integer getestadoDispensado() {
        return (Integer) ensureVariableManager().getVariableValue("estadoDispensado");
    }

    /**
     * Sets <code>value</code> for variable estadoDispensado.
     * @param value value to bind as estadoDispensado
     */
    public void setestadoDispensado(Integer value) {
        ensureVariableManager().setVariableValue("estadoDispensado", value);
    }

    /**
     * Returns the variable value for momentoCobroActual.
     * @return variable value for momentoCobroActual
     */
    public Integer getmomentoCobroActual() {
        return (Integer) ensureVariableManager().getVariableValue("momentoCobroActual");
    }

    /**
     * Sets <code>value</code> for variable momentoCobroActual.
     * @param value value to bind as momentoCobroActual
     */
    public void setmomentoCobroActual(Integer value) {
        ensureVariableManager().setVariableValue("momentoCobroActual", value);
    }
}

