<wsdl:definitions name="ConsultarAcciones" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAcciones" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAcciones" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAcciones" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarAcciones_plt">
    <plt:role name="ConsultarAcciones_role">
      <plt:portType name="tns:ConsultarAcciones_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAcciones" schemaLocation="../XSD/ConsultarAcciones.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAccionesInput_msg">
        <wsdl:part name="ConsultarAccionesInput_msg" element="db:ConsultarAccionesInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAccionesOutputCollection_msg">
        <wsdl:part name="ConsultarAccionesOutputCollection" element="db:ConsultarAccionesOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAcciones_ptt">
        <wsdl:operation name="ConsultarAcciones">
            <wsdl:input message="tns:ConsultarAccionesInput_msg"/>
            <wsdl:output message="tns:ConsultarAccionesOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>