<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://www.temenos.com/T24/ofs/Request"
                xmlns:ns0="http://xmlns.banesco.com/eopt/AcctSignatureGrpAdd_V1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns1="http://www.temenos.com/T24/ofs/EBSIGNATORYGROUPWFSIGNGROUPType"
                xmlns:reqcns="http://www.temenos.com/T24/ofs/RequestCommon"
                xmlns:ns2="http://xmlns.banesco.com/eo/Banking_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns3="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:eoSignGrp="http://xmlns.banesco.com/eo/SignatureGrp_V1.0"
                xmlns:head="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Account/AcctSignatureGrpAdd/AcctSignatureGrpAdd_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctSignatureGrpAddRq"
                                       namespace="http://xmlns.banesco.com/eopt/AcctSignatureGrpAdd_V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/WfSignGroup/GroupSignatureGrupodeFirmantesRequest.xsd"/>
        <oracle-xsl-mapper:rootElement name="EBSIGNATORYGROUPWFSIGNGROUPRequest"
                                       namespace="http://www.temenos.com/T24/ofs/Request"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON MAY 07 16:20:56 COT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="varHeader"/>
  <xsl:template match="/">
    <opaq:opaqueElement xmlns:opaq="http://xmlns.oracle.com/pcbpel/adapter/opaque/">
      <tns:EBSIGNATORYGROUPWFSIGNGROUPRequest>
        <RequestCommon>
          <UserName>
            <xsl:value-of select="$varHeader/head:ClientApp/head:UserId"/>
          </UserName>
        </RequestCommon>
        <EBSIGNATORYGROUPWFSIGNGROUP>
        <xsl:if test="/ns0:AcctSignatureGrpAddRq/ns0:SignatureGrp/eoSignGrp:SignGrpKey/eoSignGrp:SignGrpId">
          <xsl:attribute name="id">
            <xsl:value-of select="/ns0:AcctSignatureGrpAddRq/ns0:SignatureGrp/eoSignGrp:SignGrpKey/eoSignGrp:SignGrpId"/>
          </xsl:attribute>
        </xsl:if>
        <gDESCRIPTION>
            <xsl:if test="/ns0:AcctSignatureGrpAddRq/ns0:SignatureGrp/eoSignGrp:Desc/text()">
              <DESCRIPTION>
                <xsl:value-of select="/ns0:AcctSignatureGrpAddRq/ns0:SignatureGrp/eoSignGrp:Desc"/>
              </DESCRIPTION>
            </xsl:if>
          </gDESCRIPTION>
          <gSIGNATORYCUSTOMER>
            <xsl:for-each select="/ns0:AcctSignatureGrpAddRq/ns0:SignatureGrp/eoSignGrp:Signatories/eoSignGrp:Signatory">
              <mSIGNATORYCUSTOMER>
                <xsl:if test="eoSignGrp:PartyKey/ns4:PartyId/text()">
                  <SIGNATORYCUSTOMER>
                    <xsl:value-of select="eoSignGrp:PartyKey/ns4:PartyId"/>
                  </SIGNATORYCUSTOMER>
                </xsl:if>
                <xsl:if test="eoSignGrp:StartDt/text()">
                  <STARTDATE>
                    <!--<xsl:value-of select="StartDt"/>-->
                    <xsl:value-of select="xp20:format-dateTime(eoSignGrp:StartDt,'[YYYY]-[M01]-[D01]')"/>
                  </STARTDATE>
                </xsl:if>
                <xsl:if test="eoSignGrp:EndDt/text()">
                  <ENDDATE>
                    <!--<xsl:value-of select="EndDt"/>-->
                    <xsl:value-of select="xp20:format-dateTime(eoSignGrp:EndDt,'[YYYY]-[M01]-[D01]')"/>
                  </ENDDATE>
                </xsl:if>
              </mSIGNATORYCUSTOMER>
            </xsl:for-each>
          </gSIGNATORYCUSTOMER>
        </EBSIGNATORYGROUPWFSIGNGROUP>
      </tns:EBSIGNATORYGROUPWFSIGNGROUPRequest>
    </opaq:opaqueElement>
  </xsl:template>
</xsl:stylesheet>
