<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/StockCountApp/StockCountJMSReference" name="StockCountJMSReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="StockCountJMSReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/StockCountApp/StockCountJMSReference"/>
    <wsdl:binding name="ProduceMsg_ptt-binding" type="stoc:ProduceMsg_ptt" xmlns:stoc="http://xmlns.oracle.com/pcbpel/adapter/jms/OSBAGApp/StockCountApp/StockCountJMSReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ProduceMsg">
            <soap:operation soapAction="ProduceMsg"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>