<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/StockCountServiceIN" name="StockCountServiceIN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="StockCountServiceIN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/StockCountServiceIN"/>
  <wsdl:binding name="GetStockCount_ptt-binding" type="stoc:GetStockCount_ptt" xmlns:stoc="http://xmlns.oracle.com/pcbpel/adapter/ftp/OSBAGApp/StockCountApp/StockCountServiceIN">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="GetStockCount">
      <soap:operation soapAction="GetStockCount"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>