<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:ns2="http://xmlns.bcie.com/OperacionService"
     xmlns:ns3="http://www.bcie.com/ConsultarRolesPorProceso"
    >
    <plnk:partnerLinkType name="ConfiguracionSupervision">
        <plnk:role name="ConfiguracionSupervisionPT" portType="tns:ConfiguracionSupervisionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/ConfiguracionProcesosService" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConfiguracionProcesos/V1/WSDL/BPEL/ConfiguracionSupervisionAmbientalSocialSOR.wsdl"/>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/OperacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Operacion/V1/Wsdl/ADAPTER/ConsultarOperacionByIdSAD.wsdl"/>
    <wsdl:import namespace="http://www.bcie.com/ConsultarRolesPorProceso" location="oramds:/apps/Resources/ComponentesComunes/Utilidades/ConsultarRolesPorProceso/V1/Wsdl/ConsultarRolesPorProceso.wsdl"/>
</wsdl:definitions>
