<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/FinalizarOperacionProcesoDB" name="FinalizarOperacionProcesoDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="FinalizarOperacionProcesoDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/FinalizarOperacionProcesoDB"/>
    <wsdl:binding name="FinalizarOperacionProcesoDB_ptt-binding" type="fin:FinalizarOperacionProcesoDB_ptt" xmlns:fin="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/FinalizarOperacionProcesoDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="FinalizarOperacionProcesoDB">
            <soap:operation soapAction="FinalizarOperacionProcesoDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>