<definitions targetNamespace="http://www.bcie.org/CondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/CondicionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:conMO="http://www.bcie.org/CondicionMO" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../ConsultarValidacionCondicionByRol/XSD/CondicionMOV2.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarCondicionbyRolRequestMessage">
    <part name="request" element="conMO:ConsultarCondicionByRolRequest"/>
  </message>
  <message name="ConsultarCondicionbyRolResponseMessage">
    <part name="response" element="conMO:ConsultarCondicionByRolResponse"/>
  </message>
  <portType name="ConsultarCondicionbyRolPT">
    <operation name="consultarCondicionbyRol">
      <input message="tns:ConsultarCondicionbyRolRequestMessage"/>
      <output message="tns:ConsultarCondicionbyRolResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarCondicionbyRolPT12Bnd" type="tns:ConsultarCondicionbyRolPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarCondicionbyRol">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CondicionService/consultarCondicionbyRol"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>