<wsdl:definitions name="EliminarTreLineaCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/COMPOSICIONES/EliminarTreLineaCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/COMPOSICIONES/EliminarTreLineaCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTreLineaCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarTreLineaCredito_plt">
    <plt:role name="EliminarTreLineaCredito_role">
      <plt:portType name="tns:EliminarTreLineaCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTreLineaCredito" schemaLocation="../XSD/EliminarTreLineaCreditoAprobacionByIdLinea_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarTreLineaCreditoInput_msg">
        <wsdl:part name="EliminarTreLineaCreditoInput_msg" element="db:EliminarTreLineaCreditoInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarTreLineaCredito_ptt">
        <wsdl:operation name="EliminarTreLineaCredito">
            <wsdl:input message="tns:EliminarTreLineaCreditoInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>