<wsdl:definitions name="MerchandiseHierarchyFindByIdProcess" targetNamespace="http://xmlns.oracle.com/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindByIdProcess/MerchandiseHierarchyFindByIdProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/MerchandiseHierarchyFindApp/MerchandiseHierarchyFindByIdProcess/MerchandiseHierarchyFindByIdProcess" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/MerchandiseHierarchyFindByIdProcess!1.0/WSDLs/MerchandiseHierarchyFindByIdProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="MerchandiseHierarchyFindByIdProcess">
        <plnk:role name="MerchandiseHierarchyFindByIdProcessProvider" portType="client:MerchandiseHierarchyFindByIdProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/oneCaseDb" schemaLocation="../Schema/MerchandiseHierarchyFindByIdProcessSchema.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MerchandiseHierarchyFindByIdProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:oneCaseDbSelect_IdC1_appCodeC1_CatIdC1_targetAppCodeC1InputParameters"/>
    </wsdl:message>
    <wsdl:message name="MerchandiseHierarchyFindByIdProcessResponseMessage">
        <wsdl:part name="payload" element="ns1:MdmMerchandHierarchiesCollection"/>
    </wsdl:message>
    <wsdl:portType name="MerchandiseHierarchyFindByIdProcess">
        <wsdl:operation name="findById">
            <wsdl:input message="client:MerchandiseHierarchyFindByIdProcessRequestMessage"/>
            <wsdl:output message="client:MerchandiseHierarchyFindByIdProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MerchandiseHierarchyFindByIdProcessBinding" type="client:MerchandiseHierarchyFindByIdProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="findById">
            <soap:operation style="document" soapAction="findById"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MerchandiseHierarchyFindByIdService_ep">
        <wsdl:port name="MerchandiseHierarchyFindByIdProcess_pt" binding="client:MerchandiseHierarchyFindByIdProcessBinding">
            <soap:address location="http://gdsoaapp.agarcia.com.mx:7006/soa-infra/services/RetailOperMK/MerchandiseHierarchyFindByIdProcess/MerchandiseHierarchyFindByIdService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>