<wsdl:definitions
     name="ValidarClienteProceso"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ValidarClienteProceso/ValidarClienteProceso"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ValidarClienteProceso/ValidarClienteProceso"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarClienteProceso"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ValidarClienteProceso_plt" >
    <plt:role name="ValidarClienteProceso_role" >
      <plt:portType name="tns:ValidarClienteProceso_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarClienteProceso" schemaLocation="../XSD/ValidarClienteProceso.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ValidarClienteProcesoInput_msg">
        <wsdl:part name="ValidarClienteProcesoInput_msg" element="db:ValidarClienteProcesoInput"/>
    </wsdl:message>
    <wsdl:message name="ValidarClienteProcesoOutputCollection_msg">
        <wsdl:part name="ValidarClienteProcesoOutputCollection" element="db:ValidarClienteProcesoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ValidarClienteProceso_ptt">
        <wsdl:operation name="ValidarClienteProceso">
            <wsdl:input message="tns:ValidarClienteProcesoInput_msg"/>
            <wsdl:output message="tns:ValidarClienteProcesoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
