<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSCreateChangeEvent/RMSCreateChangeEvent/RMSCreateChangeEvent" name="RMSCreateChangeEventBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RMSCreateChangeEvent.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RMSCreateChangeEvent/RMSCreateChangeEvent/RMSCreateChangeEvent"/>
    <wsdl:binding name="RMSCreateChangeEvent_ptt-binding" type="rms:RMSCreateChangeEvent_ptt" xmlns:rms="http://xmlns.oracle.com/pcbpel/adapter/db/RMSCreateChangeEvent/RMSCreateChangeEvent/RMSCreateChangeEvent">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RMSCreateChangeEvent">
            <soap:operation soapAction="RMSCreateChangeEvent"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>