<wsdl:definitions
     name="ConsultarMontoOperacion_db"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project6/ConsultarMontoOperacion_db"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project6/ConsultarMontoOperacion_db"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarMontoOperacion_db"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarMontoOperacion_db_plt" >
    <plt:role name="ConsultarMontoOperacion_db_role" >
      <plt:portType name="tns:ConsultarMontoOperacion_db_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarMontoOperacion_db" schemaLocation="../XSD/ConsultarMontoOperacion_db.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarMontoOperacion_dbInput_msg">
        <wsdl:part name="ConsultarMontoOperacion_dbInput_msg" element="db:ConsultarMontoOperacion_dbInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarMontoOperacion_dbOutputCollection_msg">
        <wsdl:part name="ConsultarMontoOperacion_dbOutputCollection" element="db:ConsultarMontoOperacion_dbOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarMontoOperacion_db_ptt">
        <wsdl:operation name="ConsultarMontoOperacion_db">
            <wsdl:input message="tns:ConsultarMontoOperacion_dbInput_msg"/>
            <wsdl:output message="tns:ConsultarMontoOperacion_dbOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
