<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="urn:ConsultarEnmiendasTCCByIdOperacionSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:ConsultarEnmiendasTCCByIdOperacionSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
              xmlns:mtccMO="http://www.bcie.org/MatrizTCCMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
 <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/MatrizTCCMO"
                  schemaLocation="../../Schema/MatrizTCCMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
 <wsdl:message name="ConsultarEnmiendasTCCByIdOperacionRequestMessage">
  <wsdl:part name="ConsultarEnmiendasTCCByIdOperacionRequest"
             element="mtccMO:ConsultarEnmiendasTCCByIdOperacionRequest"/>
 </wsdl:message>
 <wsdl:message name="ConsultarEnmiendasTCCByIdOperacionResponseMessage">
  <wsdl:part name="ConsultarEnmiendasTCCByIdOperacionResponse"
             element="mtccMO:ConsultarEnmiendasTCCByIdOperacionResponse"/>
 </wsdl:message>
 <wsdl:portType name="ConsultarEnmiendasTCCByIdOperacionPT">
  <wsdl:operation name="consultarEnmiendasTCCByIdOperacion">
   <wsdl:input message="tns:ConsultarEnmiendasTCCByIdOperacionRequestMessage"/>
   <wsdl:output message="tns:ConsultarEnmiendasTCCByIdOperacionResponseMessage"/>
  </wsdl:operation>
 </wsdl:portType>
 <wsdl:binding name="ConsultarEnmiendasTCCByIdOperacionPT12Bnd" type="tns:ConsultarEnmiendasTCCByIdOperacionPT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="consultarEnmiendasTCCByIdOperacion">
   <soap12:operation style="document"
                     soapAction="urn:ConsultarEnmiendasTCCByIdOperacionSAD/consultarEnmiendasTCCByIdOperacion"/>
   <wsdl:input>
    <soap12:body use="literal" parts="ConsultarEnmiendasTCCByIdOperacionRequest"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="ConsultarEnmiendasTCCByIdOperacionResponse"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
</wsdl:definitions>