<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CierreProcess" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/CierreProcess" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:types>
<xsd:schema>
<xsd:import namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/CierreProcess" schemaLocation="../../Schema/PC08/CierreProcess.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="InicioCierre">
<wsdl:part name="parameters" element="tns:InicioCierre"/>
</wsdl:message>
<wsdl:message name="FinCierre">
<wsdl:part name="parameters" element="tns:FinCierre"/>
</wsdl:message>
<wsdl:portType name="CierreProcessPortType">
<wsdl:operation name="InicioCierre">
<wsdl:input message="tns:InicioCierre"/>
</wsdl:operation>
<wsdl:operation name="FinCierre">
<wsdl:input message="tns:FinCierre"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="CierreProcessBinding" type="tns:CierreProcessPortType">
<wsdlsoap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="InicioCierre">
<wsdlsoap:operation style="document" soapAction="InicioCierre"/>
<wsdl:input>
<wsdlsoap:body use="literal"/>
</wsdl:input>
</wsdl:operation>
<wsdl:operation name="FinCierre">
<wsdlsoap:operation style="document" soapAction="FinCierre"/>
<wsdl:input>
<wsdlsoap:body use="literal"/>
</wsdl:input>
</wsdl:operation>
</wsdl:binding>
<plnk:partnerLinkType name="CierreProcessPortTypePartnerLinkType">
<plnk:role name="CierreProcessPortTypeProvider">
<plnk:portType name="tns:CierreProcessPortType"/>
</plnk:role>
</plnk:partnerLinkType>
</wsdl:definitions>
