<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarCoberturaSAD" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarCoberturaSAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linMO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarCoberturaSAD/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarCoberturaMessage">
    <part name="request" element="linMO:ConsultarCoberturaRequest"/>
  </message>
  <message name="responseConsultarCoberturaMessage">
    <part name="response" element="linMO:ConsultarCoberturaResponse"/>
  </message>
  <portType name="ConsultarCobertura_PT">
    <operation name="consultarCobertura">
      <input message="tns:requestConsultarCoberturaMessage"/>
      <output message="tns:responseConsultarCoberturaMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarCobertura_PTSOAP12Binding" type="tns:ConsultarCobertura_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarCobertura">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ConsultarCoberturaSAD/consultarCobertura"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>