<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/LineaCreditoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/LineaCreditoService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/LineaCreditoMO" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="ConsultarLineaCreditoRequestMessage">
    <part name="request" element="conMO:ConsultarLineaCreditoRequest"/>
  </message>
  <message name="ConsultarLineaCreditoResponseMessage">
    <part name="response" element="conMO:ConsultarLineaCreditoResponse"/>
  </message>
  <portType name="consultarLineaCreditoPT">
    <operation name="consultarLineaCredito">
      <input message="tns:ConsultarLineaCreditoRequestMessage"/>
      <output message="tns:ConsultarLineaCreditoResponseMessage"/>
    </operation>
  </portType>
  <binding name="consultarLineaCreditoPT12Bnd" type="tns:consultarLineaCreditoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarLineaCredito">
      <soap12:operation style="document" soapAction="http://www.bcie.org/LineaCreditoService/consultarLineaCredito"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>