<wsdl:definitions name="EliminarLineaCredito" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCredito" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarLineaCredito" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EliminarLineaCredito" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarLineaCredito_plt">
    <plt:role name="EliminarLineaCredito_role">
      <plt:portType name="tns:EliminarLineaCredito_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EliminarLineaCredito" schemaLocation="../XSD/EliminarLineaCredito_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="LineaCreditoCollection_msg">
        <wsdl:part name="LineaCreditoCollection" element="top:LineaCreditoCollection"/>
    </wsdl:message>
    <wsdl:portType name="EliminarLineaCredito_ptt">
        <wsdl:operation name="delete">
            <wsdl:input message="tns:LineaCreditoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>