<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertMDMPriceEventDet"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/RPMPriceCostChangeExport"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/RPMExportPriceCostChangeApp/RPMExportPriceCostChange/RPMPriceCostChangeExport"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeProcessBackup/PriceChangeSave/insertMDMPriceEventDet">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="http://uat-osb.agarcia.com.mx:7004/Applications/RetailMerchandising/RPMExportPriceCostChange/RPMPriceCostChangeExportPXY?WSDL%2FApplications%2FRetailMerchandising%2FRPM%2FRPMExportPriceCostChange%2FResources%2FRPMPriceCostChangeExport"/>
        <oracle-xsl-mapper:rootElement name="RPMPriceCostChangeExportOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RPMPriceCostChangeExport"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/insertMDMPriceEventDet.wsdl"/>
        <oracle-xsl-mapper:rootElement name="PrcEventsDetailsCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertMDMPriceEventDet"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI JUL 12 12:49:08 CDT 2019].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:PrcEventsDetailsCollection>
      <xsl:for-each select="/ns0:RPMPriceCostChangeExportOutputCollection/ns0:RPMPriceCostChangeExportOutput">
        <tns:PrcEventsDetails>
          <tns:id>
            <xsl:value-of select='oraext:sequence-next-val ("PRC_EVENTS_SEQ", "jdbc/MDMSOA" )'/>
          </tns:id>
          <tns:eventId>
            <xsl:value-of select="ns0:PC_EXPORT_ID"/>
          </tns:eventId>
          <tns:price>
            <xsl:value-of select="ns0:SELL_PRICE"/>
          </tns:price>
          <tns:percent>
            <xsl:value-of select="ns0:PCT_CHANGE"/>
          </tns:percent>
          <xsl:if test="string-length(ns0:STYLE)> 1">
            <tns:itemId>
              <xsl:value-of select="ns0:STYLE"/>
            </tns:itemId>
            <tns:styleId>
              <xsl:value-of select="ns0:STYLE"/>
            </tns:styleId>
          </xsl:if>
          <xsl:if test="string-length(ns0:SKU)> 1">
            <tns:itemId>
              <xsl:value-of select="ns0:SKU"/>
            </tns:itemId>
            <tns:skuId>
              <xsl:value-of select="ns0:SKU"/>
            </tns:skuId>
          </xsl:if>
          <tns:exportFlag>1</tns:exportFlag>
          <tns:rpmId>0</tns:rpmId>
          <tns:jdaId>0<xsl:value-of select="ns0:SUPPLIER"/></tns:jdaId>
          <tns:buId>0</tns:buId>
        </tns:PrcEventsDetails>
      </xsl:for-each>
    </tns:PrcEventsDetailsCollection>
  </xsl:template>
</xsl:stylesheet>
