<wsdl:definitions name="ConsultarConfiguracionCobroComision" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarConfiguracionCobroComision" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarConfiguracionCobroComision" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarConfiguracionCobroComision" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarConfiguracionCobroComision_plt">
    <plt:role name="ConsultarConfiguracionCobroComision_role">
      <plt:portType name="tns:ConsultarConfiguracionCobroComision_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarConfiguracionCobroComision" schemaLocation="../XSD/ConsultarConfiguracionCobroComision.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarConfiguracionCobroComisionInput_msg">
        <wsdl:part name="ConsultarConfiguracionCobroComisionInput_msg" element="db:ConsultarConfiguracionCobroComisionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarConfiguracionCobroComisionOutputCollection_msg">
        <wsdl:part name="ConsultarConfiguracionCobroComisionOutputCollection" element="db:ConsultarConfiguracionCobroComisionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarConfiguracionCobroComision_ptt">
        <wsdl:operation name="ConsultarConfiguracionCobroComision">
            <wsdl:input message="tns:ConsultarConfiguracionCobroComisionInput_msg"/>
            <wsdl:output message="tns:ConsultarConfiguracionCobroComisionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>