-- Disparador SIMPLE
CREATE OR REPLACE TRIGGER TCA_TAREA_CON_BTN_DIN_TRG
BEFORE INSERT ON TCA_TAREA_CON_BTN_DIN
FOR EACH ROW
DECLARE
    new_id NUMBER;

BEGIN
    SELECT TCA_TAREA_CON_BTN_DIN_SEQ.NEXTVAL
     INTO new_id FROM Dual;
    :NEW.ID := new_id;
END;