<wsdl:definitions name="ConsultarMiembroReunionDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarMiembroReunionDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarMiembroReunionDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarMiembroReunionDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarMiembroReunionDB_plt">
    <plt:role name="ConsultarMiembroReunionDB_role">
      <plt:portType name="tns:ConsultarMiembroReunionDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarMiembroReunionDB" schemaLocation="../XSD/ConsultarMiembroReunionDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarMiembroReunionDBInput_msg">
        <wsdl:part name="ConsultarMiembroReunionDBInput_msg" element="db:ConsultarMiembroReunionDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarMiembroReunionDBOutputCollection_msg">
        <wsdl:part name="ConsultarMiembroReunionDBOutputCollection" element="db:ConsultarMiembroReunionDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarMiembroReunionDB_ptt">
        <wsdl:operation name="ConsultarMiembroReunionDB">
            <wsdl:input message="tns:ConsultarMiembroReunionDBInput_msg"/>
            <wsdl:output message="tns:ConsultarMiembroReunionDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>