<wsdl:definitions
     name="ActualizarMontoOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project7/ActualizarMontoOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project7/ActualizarMontoOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarMontoOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ActualizarMontoOperacion_plt" >
    <plt:role name="ActualizarMontoOperacion_role" >
      <plt:portType name="tns:ActualizarMontoOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarMontoOperacion" schemaLocation="../XSD/ActualizarMontoOperacion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarMontoOperacionInput_msg">
        <wsdl:part name="ActualizarMontoOperacionInput_msg" element="db:ActualizarMontoOperacionInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarMontoOperacion_ptt">
        <wsdl:operation name="ActualizarMontoOperacion">
            <wsdl:input message="tns:ActualizarMontoOperacionInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
