<wsdl:definitions name="ProcessPurchaseReceiptEBF" targetNamespace="http://xmlns.oracle.com/PurchaseReceiptSOAApp/ProcessPurchaseReceiptEBF/ProcessPurchaseReceiptEBF" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/PurchaseReceiptSOAApp/ProcessPurchaseReceiptEBF/ProcessPurchaseReceiptEBF" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Receipt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/EnterpriseBusinessFlows/ProcessPurchaseReceiptEBF!1.0/WSDLs/ProcessPurchaseReceiptEBF.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ProcessPurchaseReceiptEBF">
        <plnk:role name="ProcessPurchaseReceiptEBFProvider" portType="client:ProcessPurchaseReceiptEBF"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.agarcia.mx/EnterpriseObjects/Receipt" schemaLocation="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Receipt/ReceiptEBM.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ProcessPurchaseReceiptEBFRequestMessage">
        <wsdl:part name="payload" element="ns1:ProcessReceiptEBM"/>
    </wsdl:message>
    <wsdl:message name="ProcessPurchaseReceiptEBFResponseMessage">
        <wsdl:part name="payload" element="ns1:ProcessReceiptResponseEBM"/>
    </wsdl:message>
    <wsdl:portType name="ProcessPurchaseReceiptEBF">
        <wsdl:operation name="process">
            <wsdl:input message="client:ProcessPurchaseReceiptEBFRequestMessage"/>
            <wsdl:output message="client:ProcessPurchaseReceiptEBFResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ProcessPurchaseReceiptEBFBinding" type="client:ProcessPurchaseReceiptEBF">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="processpurchasereceiptebf_client_ep">
        <wsdl:port name="ProcessPurchaseReceiptEBF_pt" binding="client:ProcessPurchaseReceiptEBFBinding">
            <soap:address location="http://gdsoaapp2.agarcia.com.mx:9005/soa-infra/services/EnterpriseBusinessFlows/ProcessPurchaseReceiptEBF/processpurchasereceiptebf_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>