<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions targetNamespace="http://xmlns.banesco.com/TechLayer/PartyTechSvc_V1.0"
                     xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/"
                     xmlns:WL5G3N1="http://xmlns.banesco.com/eo/Status_V1.0"
                     xmlns:WL5G3N7="http://xmlns.banesco.com/eopt/EmpPartyStatusMod_V1.0"
                     xmlns:WL5G3N10="http://xmlns.banesco.com/TechLayer/PartyTechSvc_V1.0"
                     xmlns:WL5G3N11="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoptEmpPartyStatusMod="http://xmlns.banesco.com/eopt/EmpPartyStatusMod_V1.0"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:tns="http://xmlns.banesco.com/TechLayer/PartyTechSvc_V1.0"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
      <xsd:import schemaLocation="../Schemas/EmpPartyStatusMod/EmpPartyStatusMod_V1.0.xsd"
                  namespace="http://xmlns.banesco.com/eopt/EmpPartyStatusMod_V1.0"/>
      <xsd:import schemaLocation="../Schemas/EmpPartyStatusMod/Status_V1.0.xsd" namespace="http://xmlns.banesco.com/eo/Status_V1.0"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="SystemFault">
    <WL5G3N0:part name="SystemFault" element="WL5G3N1:SystemFault"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="EmpPartyStatusModRq">
    <WL5G3N0:part name="EmpPartyStatusModRq" element="WL5G3N7:EmpPartyStatusModRq"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="EmpPartyStatusModRs">
    <WL5G3N0:part name="EmpPartyStatusModRs" element="WL5G3N7:EmpPartyStatusModRs"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="PartyTechSvcPort">
    <WL5G3N0:operation name="EmpPartyStatusMod">
      <WL5G3N0:input message="WL5G3N10:EmpPartyStatusModRq"/>
      <WL5G3N0:output message="WL5G3N10:EmpPartyStatusModRs"/>
      <WL5G3N0:fault name="SystemFault" message="WL5G3N10:SystemFault"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="PartyTechSvBinding_SOAP11" type="WL5G3N10:PartyTechSvcPort">
    <WL5G3N11:binding transport="http://www.bea.com/transport/2007/05/sb" style="document"/>
    <WL5G3N0:operation name="EmpPartyStatusMod">
      <WL5G3N11:operation style="document"
                          soapAction="http://xmlns.banesco.com/TechLayer/PartyTechSvc_V1.0/EmpPartyStatusMod"/>
      <WL5G3N0:input>
        <WL5G3N11:body use="literal" parts="EmpPartyStatusModRq"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N11:body use="literal" parts="EmpPartyStatusModRs"/>
      </WL5G3N0:output>
      <WL5G3N0:fault name="SystemFault">
        <WL5G3N11:fault name="SystemFault" use="literal"/>
      </WL5G3N0:fault>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="PartyTechSvBinding_SOAP11QSService">
    <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
    <WL5G3N0:port name="PartyTechSvBinding_SOAP11QSPort" binding="WL5G3N10:PartyTechSvBinding_SOAP11">
      <WL5G3N11:address location="sb://172.30.2.36:8011/PX_Party_V1.1"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>
