<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarConfiguracion/ConsultarConfiguracion" name="ConsultarConfiguracion_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarConfiguracion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarConfiguracion/ConsultarConfiguracion"/>
    <wsdl:binding name="ConsultarConfiguracion_ptt-binding" type="con:ConsultarConfiguracion_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarConfiguracion/ConsultarConfiguracion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarConfiguracion">
            <soap:operation soapAction="ConsultarConfiguracion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>