<wsdl:definitions name="ValidarEstadoFlexcube_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/ValidarEstadoFlexcube_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/Pruebas/ValidarEstadoFlexcube_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ValidarEstadoFlexcube_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ValidarEstadoFlexcube_DB_plt">
    <plt:role name="ValidarEstadoFlexcube_DB_role">
      <plt:portType name="tns:ValidarEstadoFlexcube_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ValidarEstadoFlexcube_DB" schemaLocation="../XSD/ValidarEstadoFlexcube_DB_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ValidarEstadoFlexcube_DBSelect_inputParameters">
        <wsdl:part name="ValidarEstadoFlexcube_DBSelect_inputParameters" element="top:ValidarEstadoFlexcube_DBSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="VtaEstadoFlexcubeCollection_msg">
        <wsdl:part name="VtaEstadoFlexcubeCollection" element="top:VtaEstadoFlexcubeCollection"/>
    </wsdl:message>
    <wsdl:portType name="ValidarEstadoFlexcube_DB_ptt">
        <wsdl:operation name="ValidarEstadoFlexcube_DBSelect">
            <wsdl:input message="tns:ValidarEstadoFlexcube_DBSelect_inputParameters"/>
            <wsdl:output message="tns:VtaEstadoFlexcubeCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>