<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoCatalogTranslate" name="caseTwoCatalogTranslate-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="caseTwoCatalogTranslate.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoCatalogTranslate"/>
    <wsdl:binding name="caseTwoCatalogTranslate_ptt-binding" type="cas:caseTwoCatalogTranslate_ptt" xmlns:cas="http://xmlns.oracle.com/pcbpel/adapter/db/CapabilitiesOSBAPP/Applications/caseTwoCatalogTranslate">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="caseTwoCatalogTranslateSelect">
            <soap:operation soapAction="caseTwoCatalogTranslateSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>