<wsdl:definitions name="CardTechSvc_V1.0" targetNamespace="http://xmlns.banesco.com/TechLayer/CardTechSvc_V1.0"
                  xmlns:tns="http://xmlns.banesco.com/TechLayer/CardTechSvc_V1.0"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:eoptCardValidInq="http://xmlns.banesco.com/eopt/CardValidInq_V1.0"
                  xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://xmlns.banesco.com/eopt/CardValidInq_V1.0"
                  schemaLocation="../../../xsd/EOpt/Card/CardValidInq/CardValidInq_V1.0.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://xmlns.banesco.com/eo/Status_V1.0"
                  schemaLocation="../../../xsd/EO/Status/Status_V1.0.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="SystemFault">
    <wsdl:part name="SystemFault" element="eoStatus:SystemFault"/>
  </wsdl:message>
  <wsdl:message name="CardValidInqRq">
    <wsdl:part name="CardValidInqRq" element="eoptCardValidInq:CardValidInqRq"/>
  </wsdl:message>
  <wsdl:message name="CardValidInqRs">
    <wsdl:part name="CardValidInqRs" element="eoptCardValidInq:CardValidInqRs"/>
  </wsdl:message>
  <wsdl:portType name="CardTechSvc_V1.0PortType">
    <wsdl:operation name="CardValidInq">
      <wsdl:input message="tns:CardValidInqRq"/>
      <wsdl:output message="tns:CardValidInqRs"/>
      <wsdl:fault name="SystemFault" message="tns:SystemFault"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CardTechSvc_V1.0SOAPBinding" type="tns:CardTechSvc_V1.0PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CardValidInq">
      <soap:operation style="document" 
      soapAction="http://xmlns.banesco.com/TechLayer/CardTechSvc_V1.0/CardValidInq"/>
      <wsdl:input>
        <soap:body use="literal" parts="CardValidInqRq"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="CardValidInqRs"/>
      </wsdl:output>
      <wsdl:fault name="SystemFault">
        <soap:fault name="SystemFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CardTechSvc_V1.0">
    <wsdl:port name="CardTechSvcPort" binding="tns:CardTechSvc_V1.0SOAPBinding">
      <soap:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>