<wsdl:definitions name="MergeAgrupador" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/MergeAgrupador" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/MergeAgrupador" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/MergeAgrupador" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="MergeAgrupador_plt">
    <plt:role name="MergeAgrupador_role">
      <plt:portType name="tns:MergeAgrupador_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MergeAgrupador" schemaLocation="../XSD/MergeAgrupador.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="MergeAgrupadorInput_msg">
        <wsdl:part name="MergeAgrupadorInput_msg" element="db:MergeAgrupadorInput"/>
    </wsdl:message>
    <wsdl:portType name="MergeAgrupador_ptt">
        <wsdl:operation name="MergeAgrupador">
            <wsdl:input message="tns:MergeAgrupadorInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>