<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://xmlns.bcie.com/CorreoElectronicoService" xmlns:tns="http://xmlns.bcie.com/CorreoElectronicoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:correoMO="http://www.bcie.org/CorreoMO">
      
        <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="../Schema/CorreoElectronicoMO.xsd"/>
		</xsd:schema>
	</wsdl:types>
        
 <wsdl:message name="ConstruirCorreoElectronicoRequestMessage">
  <wsdl:part name="ConstruirCorreoElectronicoRequest" element="correoMO:ConstruirCorreoElectronicoRequest"/>
 </wsdl:message>
 <wsdl:message name="ConstruirCorreoElectronicoResponseMessage">
  <wsdl:part name="ConstruirCorreoElectronicoResponse" element="correoMO:ConstruirCorreoElectronicoResponse"/>
 </wsdl:message>
 <wsdl:portType name="ConstruirCorreoElectronicoPT">
  <wsdl:operation name="construirCorreoElectronico">
   <wsdl:input message="tns:ConstruirCorreoElectronicoRequestMessage"/>
   <wsdl:output message="tns:ConstruirCorreoElectronicoResponseMessage"/>
  </wsdl:operation>
 </wsdl:portType>
 <wsdl:binding name="construirCorreoElectronicoPT12Bnd" type="tns:ConstruirCorreoElectronicoPT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="construirCorreoElectronico">
   <soap12:operation style="document"
                     soapAction="http://xmlns.bcie.com/CorreoElectronicoService/construirCorreoElectronico_pt"/>
   <wsdl:input>
    <soap12:body use="literal" parts="ConstruirCorreoElectronicoRequest"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="ConstruirCorreoElectronicoResponse"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
</wsdl:definitions>