<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ObtenerRolesUsuariosByPlantilla" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ObtenerRolesUsuariosByPlantilla" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:correoMO="http://www.bcie.org/CorreoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CorreoMO" schemaLocation="../Schema/CorreoElectronicoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestObtenerRolesUsuariosByPlantillaMessage">
    <part name="request" element="correoMO:ObtenerRolesUsuariosByPlantillaRequest"/>
  </message>
  <message name="responseObtenerRolesUsuariosByPlantillaMessage">
    <part name="response" element="correoMO:ObtenerRolesUsuariosByPlantillaResponse"/>
  </message>
  <portType name="ObtenerRolesUsuariosByPlantillaPT">
    <operation name="obtenerRolesUsuariosByPlantilla">
      <input message="tns:requestObtenerRolesUsuariosByPlantillaMessage"/>
      <output message="tns:responseObtenerRolesUsuariosByPlantillaMessage"/>
    </operation>
  </portType>
  <binding name="ObtenerRolesUsuariosByPlantillaPTSOAPBnd" type="tns:ObtenerRolesUsuariosByPlantillaPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="obtenerRolesUsuariosByPlantilla">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ObtenerRolesUsuariosByPlantilla/obtenerRolesUsuariosByPlantilla"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>