<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarUsuarioReunion" name="ActualizarUsuarioReunion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ActualizarUsuarioReunion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarUsuarioReunion"/>
    <wsdl:binding name="ActualizarUsuarioReunion_ptt-binding" type="act:ActualizarUsuarioReunion_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarUsuarioReunion">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ActualizarUsuarioReunion">
            <soap:operation soapAction="ActualizarUsuarioReunion"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>