<definitions targetNamespace="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
             xmlns:eoptCardCrCashAdd="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0"
             xmlns:eoptCardCrTrnInq="http://xmlns.banesco.com/eopt/CardCrTrnInq_V1.0"
             xmlns:eoptCardCrTrnTransitInq="http://xmlns.banesco.com/eopt/CardCrTrnInq_V1.0"
             xmlns:eoptCardCrFinancingAdd="http://xmlns.banesco.com/eopt/CardCrFinancingAdd_V1.0"
             xmlns:eoptCardCrFinancingInq="http://xmlns.banesco.com/eopt/CardCrFinancingInq_V1.0"
             xmlns:eoptCardCrPledgeAdd="http://xmlns.banesco.com/eopt/CardCrPledgeAdd_V1.0"
             xmlns:eoptCardCrTransferAdd="http://xmlns.banesco.com/eopt/CardCrTransferAdd_V1.0">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="../Schemas/CardCrFinancingInq/Status_V1.0.xsd"
                  namespace="http://xmlns.banesco.com/eo/Status_V1.0"/>
      <xsd:import schemaLocation="../Schemas/CardCrFinancingInq/CardCrFinancingInq_V1.0.xsd"
                  namespace="http://xmlns.banesco.com/eopt/CardCrFinancingInq_V1.0"/>
    </xsd:schema>
  </types>
  <message name="SystemFault">
    <part name="SystemFault" element="eoStatus:SystemFault"/>
  </message>

  <message name="CardCrFinancingInqRq">
    <part name="CardCrFinancingInqRq" element="eoptCardCrFinancingInq:CardCrFinancingInqRq"/>
  </message>
  <message name="CardCrFinancingInqRs">
    <part name="CardCrFinancingInqRs" element="eoptCardCrFinancingInq:CardCrFinancingInqRs"/>
  </message>
 
  <portType name="CardCrTechSvc_V1.0PortType">
    <operation name="CardCrFinancingInq">
      <input message="tns:CardCrFinancingInqRq"/>
      <output message="tns:CardCrFinancingInqRs"/>
      <fault message="tns:SystemFault" name="SystemFault"/>
    </operation>
  </portType>
  <service name="CardCrTechSvc_V1.0">
    <port name="CardCrTechSvcPort" binding="tns:CardCrTechSvc_V1.0SOAPBinding">
      <soap:address location="http://www.example.com"/>
    </port>
  </service>
  <binding name="CardCrTechSvc_V1.0SOAPBinding" type="tns:CardCrTechSvc_V1.0PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
   
    <operation name="CardCrFinancingInq">
      <soap:operation style="document"
                      soapAction="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0/CardCrFinancingInq"/>
      <input>
        <soap:body use="literal" parts="CardCrFinancingInqRq"/>
      </input>
      <output>
        <soap:body use="literal" parts="CardCrFinancingInqRs"/>
      </output>
      <fault name="SystemFault">
        <soap:fault name="SystemFault" use="literal"/>
      </fault>
    </operation>
  </binding>
</definitions>