<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CardCrFinancingInqSvc_V1.0"
     targetNamespace="http://xmlns.banesco.com/ProcessService/BPEL_CardCr/CardCrFinancingInqSvc_V1.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.banesco.com/ProcessService/BPEL_CardCr/CardCrFinancingInqSvc_V1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CardCrFinancingInq_DirectB">
        <plnk:role name="CardCrFinancingInqSvcPort" portType="tns:CardCrFinancingInqSvcPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.banesco.com/ProcessService/BPEL_CardCr/CardCrFinancingInqSvc_V1.0"
         location="CardCrFinancingInqSvc_V1.0.wsdl"/>
</wsdl:definitions>
