<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
    >
    <plnk:partnerLinkType name="CardCrTechSvc_DRef">
        <plnk:role name="CardCrTechSvc_V1.0PortType" portType="tns:CardCrTechSvc_V1.0PortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0" location="CardCrTechSvc_V1.0.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
             xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.banesco.com/TechLayer/CardCrTechSvc_V1.0"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://xmlns.banesco.com/appopt/AOptCommon_V1.0">
            <xsd:import namespace="http://xmlns.banesco.com/appopt/AOptCommon_V1.0" schemaLocation="../Schemas/AOptCommon_V1.0.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
