<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.bcie.org/ProductoService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.org/ProductoService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ConsultarProductoByIdOperacion_PS">
        <plnk:role name="ConsultarProductoByIdOperacionPT" portType="tns:ConsultarProductoByIdOperacionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.org/ProductoService" location="oramds:/apps/Resources/ComponentesComunes/DominioProducto/Producto/V1/Wsdl/ADAPTER/ConsultarProductoByIdOperacionSAD.wsdl"/>
</wsdl:definitions>
