<wsdl:definitions name="EliminarTerminoFisico_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarTerminoFisico_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarTerminoFisico_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTerminoFisico_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarTerminoFisico_DB_plt">
    <plt:role name="EliminarTerminoFisico_DB_role">
      <plt:portType name="tns:EliminarTerminoFisico_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTerminoFisico_DB" schemaLocation="../XSD/EliminarTerminoFisico_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarTerminoFisico_DBInput_msg">
        <wsdl:part name="EliminarTerminoFisico_DBInput_msg" element="db:EliminarTerminoFisico_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarTerminoFisico_DB_ptt">
        <wsdl:operation name="EliminarTerminoFisico_DB">
            <wsdl:input message="tns:EliminarTerminoFisico_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>