<wsdl:definitions name="EliminarTermino" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarTermino" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarTermino" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTermino" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarTermino_plt">
    <plt:role name="EliminarTermino_role">
      <plt:portType name="tns:EliminarTermino_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarTermino" schemaLocation="../XSD/EliminarTermino.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarTerminoInput_msg">
        <wsdl:part name="EliminarTerminoInput_msg" element="db:EliminarTerminoInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarTermino_ptt">
        <wsdl:operation name="EliminarTermino">
            <wsdl:input message="tns:EliminarTerminoInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>