<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarTermino" name="EliminarTermino_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarTermino.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarTermino"/>
    <wsdl:binding name="EliminarTermino_ptt-binding" type="elim:EliminarTermino_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/EliminarTermino">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarTermino">
            <soap:operation soapAction="EliminarTermino"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>