<wsdl:definitions name="RetailStoreEntitySvc" targetNamespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/CreateRetailStoreProcess" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ret="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/CreateRetailStoreProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <plnk:partnerLinkType name="CreateRetailStoreProcess">
        <plnk:role name="CreateRetailStorePType" portType="ret:CreateRetailStorePType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/RetailStore/WSDL/CreateRetailStoreProcess" location="CreateRetailStoreProcessWSDL.wsdl"/>
</wsdl:definitions>