<wsdl:definitions name="ConsultarValidacionCondicionByRol" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project1/ConsultarValidacionCondicionByRol" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project1/ConsultarValidacionCondicionByRol" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidacionCondicionByRol" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarValidacionCondicionByRol_plt">
    <plt:role name="ConsultarValidacionCondicionByRol_role">
      <plt:portType name="tns:ConsultarValidacionCondicionByRol_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidacionCondicionByRol" schemaLocation="../XSD/ConsultarValidacionCondicionByRol.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarValidacionCondicionByRolInput_msg">
        <wsdl:part name="ConsultarValidacionCondicionByRolInput_msg" element="db:ConsultarValidacionCondicionByRolInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarValidacionCondicionByRolOutputCollection_msg">
        <wsdl:part name="ConsultarValidacionCondicionByRolOutputCollection" element="db:ConsultarValidacionCondicionByRolOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarValidacionCondicionByRol_ptt">
        <wsdl:operation name="ConsultarValidacionCondicionByRol">
            <wsdl:input message="tns:ConsultarValidacionCondicionByRolInput_msg"/>
            <wsdl:output message="tns:ConsultarValidacionCondicionByRolOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>