<?xml version="1.0" encoding="UTF-8" ?>
<definitions name="ConsultarAccionByIdSAD" 
             targetNamespace="http://xmlns.bcie.com/ConsultarAccionByIdSAD" 
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:operMO="http://www.bcie.org/OperacionMO"
             xmlns:tns="http://xmlns.bcie.com/ConsultarAccionByIdSAD" 
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/OperacionMO" schemaLocation="../../Schema/OperacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="requestConsultarAccionesMessage">
    <part name="request" element="operMO:ConsultarAccionesRequest"/>
  </message>
  <message name="responseConsultarAccionesMessage">
    <part name="response" element="operMO:ConsultarAccionesResponse"/>
  </message>
  <portType name="ConsultarAccionesById12Port">
    <operation name="ConsultarAccionesById">
      <input message="tns:requestConsultarAccionesMessage"/>
      <output message="tns:responseConsultarAccionesMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarAccionesById12Bnd" type="tns:ConsultarAccionesById12Port">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarAccionesById">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/OperacionService/ConsultarAccionesById"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>


                 
                