<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/OperacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:operMO="http://www.bcie.org/OperacionMO"
                  xmlns:tns="http://xmlns.bcie.com/OperacionService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/OperacionMO"
                  schemaLocation="../../Schema/OperacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
 
  <wsdl:message name="requestReactivarOperacionMessage">
    <wsdl:part name="request" element="operMO:ReactivarOperacionRequest"/>
  </wsdl:message>
  <wsdl:message name="responseReactivarOperacionMessage">
    <wsdl:part name="response" element="operMO:ReactivarOperacionResponse"/>
  </wsdl:message>
  
  <wsdl:portType name="OperacionPT">
    
   <wsdl:operation name="reactivarOperacion">
      <wsdl:documentation>Consulta uno Operacion por id del Operacion</wsdl:documentation>
      <wsdl:input message="tns:requestReactivarOperacionMessage"/>
      <wsdl:output message="tns:responseReactivarOperacionMessage"/>
    </wsdl:operation>
    
    
  </wsdl:portType>
  <wsdl:binding name="Operacion12Bnd" type="tns:OperacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    
     <wsdl:operation name="reactivarOperacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/OperacionService/reactivarOperacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
 
   
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
