<wsdl:definitions name="ConsultarValidacionCondicionByIdCondicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarValidacionCondicionByIdCondicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarValidacionCondicionByIdCondicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidacionCondicionByIdCondicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarValidacionCondicionByIdCondicion_plt">
    <plt:role name="ConsultarValidacionCondicionByIdCondicion_role">
      <plt:portType name="tns:ConsultarValidacionCondicionByIdCondicion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarValidacionCondicionByIdCondicion" schemaLocation="../XSD/ConsultarValidacionCondicionByIdCondicion.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="ConsultarValidacionCondicionByIdCondicionInput_msg">
    <wsdl:part name="ConsultarValidacionCondicionByIdCondicionInput_msg" element="db:ConsultarValidacionCondicionByIdCondicionInput"/>
  </wsdl:message>
  <wsdl:message name="ConsultarValidacionCondicionByIdCondicionOutputCollection_msg">
    <wsdl:part name="ConsultarValidacionCondicionByIdCondicionOutputCollection" element="db:ConsultarValidacionCondicionByIdCondicionOutputCollection"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarValidacionCondicionByIdCondicion_ptt">
    <wsdl:operation name="ConsultarValidacionCondicionByIdCondicion">
      <wsdl:input message="tns:ConsultarValidacionCondicionByIdCondicionInput_msg"/>
      <wsdl:output message="tns:ConsultarValidacionCondicionByIdCondicionOutputCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>