<wsdl:definitions name="QueryRMS" targetNamespace="http://www.agarcia.mx/ServiceBus/QueryRMS" xmlns:tns="http://www.agarcia.mx/ServiceBus/QueryRMS" xmlns:inp1="http://www.agarcia.mx/EnterpriseObjects/ASNIN" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.agarcia.mx/EnterpriseObjects/ASNIN" schemaLocation="../../../MetaData/Components/EnterpriseObjectLibrary/EBO/ASNIN/ASNINEBM.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Input" element="inp1:ProcessASNINEBM"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Output" element="inp1:ProcessASNINEBM"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:execute_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute">
            <soap:operation style="document" soapAction="execute"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/QueryRMS"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.agarcia.mx/ServiceBus/QueryRMS"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>