<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/TransferRequestApp/QueryTransferRequestRMSReference" name="QueryTransferRequestRMSReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryTransferRequestRMSReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/TransferRequestApp/QueryTransferRequestRMSReference"/>
    <wsdl:binding name="QueryTransferRequestRMSReference_ptt-binding" type="quer:QueryTransferRequestRMSReference_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/TransferRequestApp/QueryTransferRequestRMSReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryTransferRequestRMSReferenceSelect">
            <soap:operation soapAction="QueryTransferRequestRMSReferenceSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>