<wsdl:definitions name="QueryTransferRequestRMSReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/TransferRequestApp/QueryTransferRequestRMSReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/TransferRequestApp/QueryTransferRequestRMSReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryTransferRequestRMSReference" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryTransferRequestRMSReference_plt">
    <plt:role name="QueryTransferRequestRMSReference_role">
      <plt:portType name="tns:QueryTransferRequestRMSReference_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryTransferRequestRMSReference" schemaLocation="../XSD/QueryTransferRequestRMSReference_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryTransferRequestRMSReferenceSelect_inputParameters">
        <wsdl:part name="QueryTransferRequestRMSReferenceSelect_inputParameters" element="top:QueryTransferRequestRMSReferenceSelect_Transfer_No_Local_OrInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaTsfreqVwCollection_msg">
        <wsdl:part name="XxSoaTsfreqVwCollection" element="top:XxSoaTsfreqVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryTransferRequestRMSReference_ptt">
        <wsdl:operation name="QueryTransferRequestRMSReferenceSelect">
            <wsdl:input message="tns:QueryTransferRequestRMSReferenceSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaTsfreqVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>