<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDACreateBuyerProcessBPEL" targetNamespace="http://xmlns.oracle.com/JDACreateBuyerProcess/JDACreateBuyerProcess/JDACreateBuyerProcessBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/JDACreateBuyerProcess/JDACreateBuyerProcess/JDACreateBuyerProcessBPEL" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Foundation/Party/BuyerEntitySvc" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDACreateBuyerProcess">
   <plnk:partnerLinkType name="JDACreateBuyerProcessBPEL">
      <plnk:role name="JDACreateBuyerProcessBPELProvider" portType="client:JDACreateBuyerProcessBPEL"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://mx.agarcia.ea/Capabilities/Core/Buyer/JDACreateBuyerProcess" location="JDACreateBuyerProcess.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Foundation/Party/BuyerEntitySvc" schemaLocation="../Schemas/BuyerEntitySchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="JDACreateBuyerProcessBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:createBuyerRequest"/>
   </wsdl:message>
   <wsdl:message name="JDACreateBuyerProcessBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:createBuyerResponse"/>
   </wsdl:message>
   <wsdl:portType name="JDACreateBuyerProcessBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:JDACreateBuyerProcessBPELRequestMessage"/>
         <wsdl:output message="client:JDACreateBuyerProcessBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
