<wsdl:definitions
     name="CrearComentarioVotacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearComentarioVotacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/CrearComentarioVotacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearComentarioVotacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CrearComentarioVotacion_plt" >
    <plt:role name="CrearComentarioVotacion_role" >
      <plt:portType name="tns:CrearComentarioVotacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CrearComentarioVotacion" schemaLocation="../XSD/CrearComentarioVotacion_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ComentarioReunionCollection_msg">
        <wsdl:part name="ComentarioReunionCollection" element="top:ComentarioReunionCollection"/>
    </wsdl:message>
    <wsdl:portType name="CrearComentarioVotacion_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ComentarioReunionCollection_msg"/>
            <wsdl:output message="tns:ComentarioReunionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
