<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ValidarLimitesSOR" targetNamespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ValidarLimitesSOR" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.oracle.com/OSB_BCIE/MDS/ValidarLimitesSOR" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ValidarLimites_SB">
      <plnk:role name="ValidarLimites_ptt" portType="tns:ValidarLimites_ptt"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.oracle.com/OSB_BCIE/MDS/ValidarLimitesSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/ValidarLimitesSOR.wsdl"/>
</wsdl:definitions>
