<?xml version='1.0' encoding='UTF-8'?>
<definitions targetNamespace="http://www.bcie.org/ValidarLimiteDestinoSOR" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/ValidarLimiteDestinoSOR" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:desBO="http://www.bcie.org/DesembolsoMO">
   <types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
      </xsd:schema>
   </types>
   <message name="requestValidarLimiteDestinoMessage">
      <part name="request" element="desBO:ValidarLimiteDestinoRequest"/>
   </message>
   <message name="responseValidarLimiteDestinoMessage">
      <part name="response" element="desBO:ValidarLimiteDestinoResponse"/>
   </message>
   <portType name="ValidarLimiteDestinoPT">
      <operation name="validarLimiteDestino">
         <input message="tns:requestValidarLimiteDestinoMessage"/>
         <output message="tns:responseValidarLimiteDestinoMessage"/>
      </operation>
   </portType>
   <binding name="ValidarLimiteDestinoPT12Bnd" type="tns:ValidarLimiteDestinoPT">
      <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="validarLimiteDestino">
         <soap12:operation style="document" soapAction="http://www.bcie.org/ValidarLimiteDestinoSOR/validarLimiteDestino" soapActionRequired="false"/>
         <input>
            <soap12:body use="literal" parts="request"/>
         </input>
         <output>
            <soap12:body use="literal" parts="response"/>
         </output>
      </operation>
   </binding>
</definitions>
