<definitions targetNamespace="http://www.bcie.org/RegistrarSCRREPSAD" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/RegistrarSCRREPSAD" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:cteMO="http://www.bcie.org/ClienteMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/RegistrarSCRREPSAD/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestRegistrarSCRREPMessage">
    <part name="request" element="cteMO:RegistrarSCRREPRequest"/>
  </message>
  <message name="responseRegistrarSCRREPMessage">
    <part name="response" element="cteMO:RegistrarSCRREPResponse"/>
  </message>
  <portType name="RegistrarSCRREP_PT">
    <operation name="RegistrarSCRREP">
      <input message="tns:requestRegistrarSCRREPMessage"/>
      <output message="tns:responseRegistrarSCRREPMessage"/>
    </operation>
  </portType>
  <binding name="RegistrarSCRREP_PTSOAP12Binding" type="tns:RegistrarSCRREP_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="RegistrarSCRREP">
      <soap12:operation style="document" soapAction="http://www.bcie.org/RegistrarSCRREPSAD/RegistrarSCRREP"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>