<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConsultarFuentesSOR" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConsultarFuentesSOR" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linMO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConsultarFuentesSOR/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConsultarFuentesMessage">
    <part name="request" element="linMO:ConsultarFuentesRequest"/>
  </message>
  <message name="responseConsultarFuentesMessage">
    <part name="response" element="linMO:ConsultarFuentesResponse"/>
  </message>
  <portType name="ConsultarFuentes_PT">
    <operation name="ConsultarFuentes">
      <input message="tns:requestConsultarFuentesMessage"/>
      <output message="tns:responseConsultarFuentesMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarFuentes_PTSOAP12Binding" type="tns:ConsultarFuentes_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarFuentes">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ConsultarFuentesSOR/ConsultarFuentes"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>