<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/AprobacionService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:aproMO="http://www.bcie.org/AprobacionMO"
                  xmlns:tns="http://xmlns.bcie.com/AprobacionService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/AprobacionMO"
                  schemaLocation="../../../../Aprobacion/V1/Schema/AprobacionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
  <wsdl:message name="CrearAprobacionRequestMessage">
    <wsdl:part name="request" element="aproMO:CrearAprobacionRequest"/>
  </wsdl:message>
  <wsdl:message name="CrearAprobacionResponseMessage">
    <wsdl:part name="response" element="aproMO:CrearAprobacionResponse"/>
  </wsdl:message>
  <wsdl:portType name="CrearAprobacionPT">
    <wsdl:operation name="crearAprobacion">
      <wsdl:input message="tns:CrearAprobacionRequestMessage"/>
      <wsdl:output message="tns:CrearAprobacionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CrearAprobacion12Bnd" type="tns:CrearAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearAprobacion">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/AprobacionService/crearAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>






