<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoContratoDesembolso_DB" name="ActualizarEstadoContratoDesembolso_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ActualizarEstadoContratoDesembolso_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoContratoDesembolso_DB"/>
    <wsdl:binding name="ActualizarEstadoContratoDesembolso_DB_ptt-binding" type="act:ActualizarEstadoContratoDesembolso_DB_ptt" xmlns:act="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarEstadoContratoDesembolso_DB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ActualizarEstadoContratoDesembolso_DB">
            <soap:operation soapAction="ActualizarEstadoContratoDesembolso_DB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>