<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://www.agarcia.mx/ServiceBus/ABM/PollItemRMSDBService" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/Item" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common" xmlns:ns1="http://www.agarcia.mx/EnterpriseObjects/Custom">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/nxsd_abmRMS_to_ebmItem.xsd"/>
            <oracle-xsl-mapper:rootElement name="RMSNuevosSkus" namespace="http://www.agarcia.mx/ServiceBus/ABM/PollItemRMSDBService"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../MetaData/Components/EnterpriseObjectLibrary/EBO/Item/ItemEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessItemEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/Item"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [TUE OCT 20 19:09:11 CDT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Operation"/>
   <xsl:param name="SourcesID"/>
   <xsl:param name="Interface"/>
   <xsl:param name="TrackingID"/>
   <xsl:param name="InstanceID"/>
   <xsl:param name="TargetID"/>
   <xsl:param name="StatusID"/>
   <xsl:template match="/">
      <tns:ProcessItemEBM>
         <tns:Header>
            <com:TrackingID>
               <xsl:value-of select="$TrackingID"/>
            </com:TrackingID>
            <com:InstanceID>
               <xsl:value-of select="$InstanceID"/>
            </com:InstanceID>
            <com:SourceID>
               <xsl:value-of select="$SourcesID"/>
            </com:SourceID>
            <com:Target>
               <com:Applications>
                  <com:Name>
                     <xsl:value-of select="$TargetID"/>
                  </com:Name>
               </com:Applications>
            </com:Target>
            <com:Operation>
               <xsl:value-of select="$Operation"/>
            </com:Operation>
            <com:Interface>
               <xsl:value-of select="$Interface"/>
            </com:Interface>
         </tns:Header>
         <tns:DataArea>
            <xsl:for-each select="/ns0:RMSNuevosSkus">
               <tns:ProcessItem>
                  <com:Identification>
                     <com:ID>
                        <xsl:value-of select="ns0:estilo"/>
                     </com:ID>
                  </com:Identification>
                  <xsl:for-each select="ns0:listaSKU">
                     <tns:SKU>
                        <tns:Identification>
                           <com:ID>
                              <xsl:value-of select="ns0:sku"/>
                           </com:ID>
                        </tns:Identification>
                        <tns:Detail>
                           <tns:Colors>
                              <tns:Color>
                                 <xsl:value-of select="ns0:color"/>
                              </tns:Color>
                           </tns:Colors>
                           <tns:Sizes>
                              <tns:Size>
                                 <xsl:value-of select="ns0:talla"/>
                              </tns:Size>
                           </tns:Sizes>
                        </tns:Detail>
                     </tns:SKU>
                  </xsl:for-each>
                  <tns:Status>
                     <com:Code>
                        <xsl:value-of select="$StatusID"/>
                     </com:Code>
                     <com:Description>
                        <xsl:value-of select="ns0:mensaje"/>
                     </com:Description>
                     <com:CodeBolean>
                        <xsl:value-of select="ns0:exito"/>
                     </com:CodeBolean>
                  </tns:Status>
               </tns:ProcessItem>
            </xsl:for-each>
         </tns:DataArea>
      </tns:ProcessItemEBM>
   </xsl:template>
</xsl:stylesheet>