<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Operacion"
     targetNamespace="http://xmlns.bcie.com/OperacionService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.bcie.com/OperacionService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://www.bcie.org/DesembolsoMO"
    >
    <plnk:partnerLinkType name="ObtenerFactibilidad">
        <plnk:role name="ObtenerFactibilidadPT" portType="tns:ObtenerFactibilidadPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.bcie.com/OperacionService" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Operacion/V1/Wsdl/BPEL/ObtenerFactibilidadSOR.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
