<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/crearCommitment_DB" name="crearCommitment_DB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="crearCommitment_DB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/crearCommitment_DB"/>
  <wsdl:binding name="crearCommitment_DB_ptt-binding" type="cre:crearCommitment_DB_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_FLEXCUBE/ADAPTADORES/crearCommitment_DB">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="crearCommitment_DB">
      <soap:operation soapAction="crearCommitment_DB"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>