<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:tns="http://xmlns.banesco.com/eopt/AcctCardRelMod_V1.0"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://www.temenos.com/T24/ofs/Response"
                xmlns:rescns="http://www.temenos.com/T24/ofs/ResponseCommon"
                xmlns:ns1="http://www.temenos.com/T24/ofs/CARDISSUEType"
                xmlns:ns6="http://xmlns.banesco.com/eo/Product_V1.0"
                xmlns:eoAcct="http://xmlns.banesco.com/eo/Acct_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns5="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:eoCard="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Common_V1.0"
                xmlns:eoptAcctCardRelMod="http://xmlns.banesco.com/eopt/AcctCardRelMod_V1.0">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/backends/T24/resources/xsd/GestionTDD/AfiliacionTDDResponse.xsd"/>
        <oracle-xsl-mapper:rootElement name="CARDISSUEBANCARDTDDResponse"
                                       namespace="http://www.temenos.com/T24/ofs/Response"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardDb/AcctCardRelMod/AcctCardRelMod_V1.0.xsd"/>
        <oracle-xsl-mapper:rootElement name="AcctCardRelModRs"
                                       namespace="http://xmlns.banesco.com/eopt/AcctCardRelMod_V1.0"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON JUL 09 16:11:33 CDT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:variable name="statusCode"
                select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'T24', /ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Status/text(), 'CNCODE', 'M0006' )"/>
  <xsl:template match="/">
    <tns:AcctCardRelModRs>
      <xsl:if test="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Status != 'T24 ERROR'">
        <tns:Acct>
          <eoAcct:AcctTitle>
            <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/CARDISSUE/gNAME/NAME"/>
          </eoAcct:AcctTitle>
          <eoAcct:AcctKey>
            <eoAcct:AcctReference>
              <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/CARDISSUE/gACCOUNT/ACCOUNT"/>
            </eoAcct:AcctReference>
          </eoAcct:AcctKey>
          <eoAcct:DepAcctData>
            <eoAcct:SignatureReqd>
              <eoAcct:SignatureTransaction>
                <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/TransactionId"/>
              </eoAcct:SignatureTransaction>
            </eoAcct:SignatureReqd>
          </eoAcct:DepAcctData>
        </tns:Acct>
      </xsl:if>
      <xsl:if test="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Status != 'T24 ERROR'">
        <tns:Card>
          <eoCard:PlasticInfo>
            <eoCard:ExpDt>
              <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/CARDISSUE/EXPIRYDATE"/>
            </eoCard:ExpDt>
            <eoCard:IssueDt>
              <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/CARDISSUE/ISSUEDATE"/>
            </eoCard:IssueDt>
            <eoCard:Issuer>
              <ns4:Cod>
                <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/CARDISSUE/@id"/>
              </ns4:Cod>
            </eoCard:Issuer>
          </eoCard:PlasticInfo>
          <eoCard:CardStatus>
            <eoCard:CardStatusCode>
              <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/CARDISSUE/CARDSTATUS"/>
            </eoCard:CardStatusCode>
          </eoCard:CardStatus>
        </tns:Card>
      </xsl:if>
      <tns:Status>
        <eoStatus:StatusCode>
          <xsl:value-of select="$statusCode"/>
        </eoStatus:StatusCode>
        <eoStatus:StatusDesc>
          <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'T24', /ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Status/text(), 'CNDESC', 'FALLO EN LA OPERACION' )"/>
        </eoStatus:StatusDesc>
        <eoStatus:AdditionalStatus>
          <xsl:if test="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Status">
            <eoStatus:StatusCode>
              <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Status"/>
            </eoStatus:StatusCode>
          </xsl:if>
          <xsl:if test="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Message">
            <eoStatus:StatusDesc>
              <xsl:value-of select="/ns0:CARDISSUEBANCARDTDDResponse/ResponseCommon/Message"/>
            </eoStatus:StatusDesc>
          </xsl:if>
        </eoStatus:AdditionalStatus>
      </tns:Status>
    </tns:AcctCardRelModRs>
  </xsl:template>
</xsl:stylesheet>