<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBMDMDetASN" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://www.agarcia.mx/EnterpriseObjects/ASNIN" xmlns:com="http://www.agarcia.mx/EnterpriseObjects/Common">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="Resources/DBMDMDetASN_table.xsd"/>
            <oracle-xsl-mapper:rootElement name="XxSoaAsninDetViewCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBMDMDetASN"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../MetaData/Components/EnterpriseObjectLibrary/EBO/ASNIN/ASNINEBM.xsd"/>
            <oracle-xsl-mapper:rootElement name="ProcessASNINEBM" namespace="http://www.agarcia.mx/EnterpriseObjects/ASNIN"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [WED NOV 11 15:20:01 CST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ProcessASNINEBM>
         <tns:DataArea>
            <tns:ProcessASNIN>
               <xsl:for-each select="//*:XxSoaAsninDetViewCollection/*:XxSoaAsninDetView">
                  <tns:DetalleASN>
                     <tns:LPN>
                        <com:ID>
                           <xsl:value-of select="ns0:lpn"/>
                        </com:ID>
                     </tns:LPN>
                     <tns:Transferencia>
                        <com:ID>
                           <xsl:value-of select="ns0:transferencia"/>
                        </com:ID>
                     </tns:Transferencia>
                     <tns:NumTotalCajas>
                        <xsl:value-of select="ns0:nototalcajas"/>
                     </tns:NumTotalCajas>
                     <tns:NumCaja>
                        <xsl:value-of select="ns0:nodecaja"/>
                     </tns:NumCaja>
                     <tns:DestinoFinal>
                        <xsl:value-of select="ns0:destinofinal"/>
                     </tns:DestinoFinal>
                     <tns:TipoCaja>
                        <xsl:value-of select="ns0:tipocaja"/>
                     </tns:TipoCaja>
                  </tns:DetalleASN>
               </xsl:for-each>
            </tns:ProcessASNIN>
         </tns:DataArea>
      </tns:ProcessASNINEBM>
   </xsl:template>
</xsl:stylesheet>