<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMHeaderASN" name="DBMDMHeaderASN-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBMDMHeaderASN.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMHeaderASN"/>
    <wsdl:binding name="DBMDMHeaderASN_ptt-binding" type="dbm:DBMDMHeaderASN_ptt" xmlns:dbm="http://xmlns.oracle.com/pcbpel/adapter/db/ASNINBUS/ASNINAPP/DBMDMHeaderASN">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBMDMHeaderASNSelect">
            <soap:operation soapAction="DBMDMHeaderASNSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>