<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ActualizarComponenteSAD"
     targetNamespace="http://www.bcie.org/ActualizarComponenteSAD"
     xmlns:tns="http://www.bcie.org/ActualizarComponenteSAD"
     xmlns:inp1="http://www.bcie.org/DesembolsoMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMOV2.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ActualizarComponenteRequestMessage">
        <wsdl:part name="requestActualizarComponente" element="inp1:ActualizarComponenteRequest"/>
    </wsdl:message>
    <wsdl:message name="ActualizarComponenteResponseMessage">
        <wsdl:part name="responseActualizarComponente" element="inp1:ActualizarComponenteResponse"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarComponentePT">
        <wsdl:operation name="ActualizarComponente">
            <wsdl:input message="tns:ActualizarComponenteRequestMessage"/>
            <wsdl:output message="tns:ActualizarComponenteResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ActualizarComponentePT12Bnd" type="tns:ActualizarComponentePT">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"/>
        <wsdl:operation name="ActualizarComponente">
            <soap12:operation style="document" soapAction="http://www.bcie.org/ActualizarComponenteSAD/ActualizarComponente" soapActionRequired="false"/>
            <wsdl:input>
                <soap12:body use="literal" namespace="http://www.bcie.org/ActualizarComponenteSAD"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" namespace="http://www.bcie.org/ActualizarComponenteSAD"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
