<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CrearNoObjecionPGA/ADAPTADORES/CrearActualizarPrepago" name="CrearActualizarPrepago-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CrearActualizarPrepago.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CrearNoObjecionPGA/ADAPTADORES/CrearActualizarPrepago"/>
    <wsdl:binding name="CrearActualizarPrepago_ptt-binding" type="cre:CrearActualizarPrepago_ptt" xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/CrearNoObjecionPGA/ADAPTADORES/CrearActualizarPrepago">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CrearActualizarPrepago">
            <soap:operation soapAction="CrearActualizarPrepago"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>