package org.bcie.fenix.common.model.vo;

import oracle.jbo.server.ViewObjectImpl;

import org.bcie.fenix.common.model.vo.common.DatosActividadF1VO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 05 17:06:25 CDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DatosActividadF1VOImpl extends ViewObjectImpl implements DatosActividadF1VO {
    /**
     * This is the default constructor (do not remove).
     */
    public DatosActividadF1VOImpl() {
    }

    /**
     * Returns the bind variable value for varPrograma.
     * @return bind variable value for varPrograma
     */
    public String getvarPrograma() {
        return (String) getNamedWhereClauseParam("varPrograma");
    }

    /**
     * Sets <code>value</code> for bind variable varPrograma.
     * @param value value to bind as varPrograma
     */
    public void setvarPrograma(String value) {
        if(null!=value){
        setNamedWhereClauseParam("varPrograma", value);
            }
    }
}

