<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="dbFnxAvisos" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdquisicionesSOA/ADAPTADORES/dbFnxAvisos" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdquisicionesSOA/ADAPTADORES/dbFnxAvisos" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxAvisos" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="dbFnxAvisos_plt">
      <plt:role name="dbFnxAvisos_role">
         <plt:portType name="tns:dbFnxAvisos_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <plt:partnerLinkType name="dbFnxAvisos_plt">
      <plt:role name="dbFnxAvisos_role">
         <plt:portType name="tns:dbFnxAvisos_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <plt:partnerLinkType name="dbFnxAvisos_plt">
      <plt:role name="dbFnxAvisos_role">
         <plt:portType name="tns:dbFnxAvisos_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxAvisos" schemaLocation="../Schemas/dbFnxAvisos.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxAvisos" schemaLocation="../Schemas/dbFnxAvisos.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxAvisos" schemaLocation="../Schemas/dbFnxAvisos.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="dbFnxAvisosInput_msg">
      <wsdl:part name="dbFnxAvisosInput_msg" element="db:dbFnxAvisosInput"/>
   </wsdl:message>
   <wsdl:message name="dbFnxAvisosOutputCollection_msg">
      <wsdl:part name="dbFnxAvisosOutputCollection" element="db:dbFnxAvisosOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="dbFnxAvisos_ptt">
      <wsdl:operation name="dbFnxAvisos">
         <wsdl:input message="tns:dbFnxAvisosInput_msg"/>
         <wsdl:output message="tns:dbFnxAvisosOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
