<wsdl:definitions name="ftpMasterEDICreateOrder" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/ConfirmOrderBUS/OrderConfirmService/ftpMasterEDICreateOrder" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/ConfirmOrderBUS/OrderConfirmService/ftpMasterEDICreateOrder" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:imp1="http://www.agarcia.mx/ftpNadroCreateOrder">
  <plt:partnerLinkType name="Process_plt">
    <plt:role name="Process_role">
      <plt:portType name="tns:Process_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://www.agarcia.mx/ftpNadroCreateOrder" schemaLocation="../ediupack.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Process_msg">
        <wsdl:part name="body" element="imp1:body"/>
    </wsdl:message>
    <wsdl:portType name="Process_ptt">
        <wsdl:operation name="Process">
            <wsdl:input message="tns:Process_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>