<wsdl:definitions name="QueryAllocByParam" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication_Test/SBProject/QueryAllocByParam" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication_Test/SBProject/QueryAllocByParam" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocByParam" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QueryAllocByParam_plt">
    <plt:role name="QueryAllocByParam_role">
      <plt:portType name="tns:QueryAllocByParam_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryAllocByParam" schemaLocation="QueryAllocByParam_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryAllocByParamSelect_inputParameters">
        <wsdl:part name="QueryAllocByParamSelect_inputParameters" element="top:QueryAllocByParamSelect_skuParam_localOrigenParam_tiendaParam_OrderNoParamInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaAllocVwCollection_msg">
        <wsdl:part name="XxSoaAllocVwCollection" element="top:XxSoaAllocVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryAllocByParam_ptt">
        <wsdl:operation name="QueryAllocByParamSelect">
            <wsdl:input message="tns:QueryAllocByParamSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaAllocVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>