<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication_Test/SBProject/QueryAllocByParam" name="QueryAllocByParam-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryAllocByParam.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication_Test/SBProject/QueryAllocByParam"/>
    <wsdl:binding name="QueryAllocByParam_ptt-binding" type="quer:QueryAllocByParam_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication_Test/SBProject/QueryAllocByParam">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryAllocByParamSelect">
            <soap:operation soapAction="QueryAllocByParamSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>