<wsdl:definitions
     name="ConsultarTermino"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project17/ConsultarTermino"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project17/ConsultarTermino"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTermino"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarTermino_plt" >
    <plt:role name="ConsultarTermino_role" >
      <plt:portType name="tns:ConsultarTermino_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTermino" schemaLocation="../XSD/ConsultarTermino.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTerminoInput_msg">
        <wsdl:part name="ConsultarTerminoInput_msg" element="db:ConsultarTerminoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTerminoOutputCollection_msg">
        <wsdl:part name="ConsultarTerminoOutputCollection" element="db:ConsultarTerminoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTermino_ptt">
        <wsdl:operation name="ConsultarTermino">
            <wsdl:input message="tns:ConsultarTerminoInput_msg"/>
            <wsdl:output message="tns:ConsultarTerminoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
