<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bice.org/CrearPrestamoFLEXCUBEService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bice.org/CrearPrestamoFLEXCUBEService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linMO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bice.org/CrearPrestamoFLEXCUBEService/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/LineaCreditoMO" schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestCrearPrestamoFLEXCUBEMessage">
    <part name="request" element="linMO:CrearPrestamoFLEXCUBERequest"/>
  </message>
  <message name="responseCrearPrestamoFLEXCUBEMessage">
    <part name="response" element="linMO:CrearPrestamoFLEXCUBEResponse"/>
  </message>
  <portType name="CrearPrestamoFLEXCUBE_PT">
    <operation name="CrearPrestamosFLEXCUBE">
      <input message="tns:requestCrearPrestamoFLEXCUBEMessage"/>
      <output message="tns:responseCrearPrestamoFLEXCUBEMessage"/>
    </operation>
  </portType>
  <binding name="CrearPrestamoFLEXCUBE_PTSOAP12Binding" type="tns:CrearPrestamoFLEXCUBE_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CrearPrestamosFLEXCUBE">
      <soap12:operation style="document"
                        soapAction="http://www.bice.org/CrearPrestamoFLEXCUBEService/CrearPrestamosFLEXCUBE"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>