<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:EliminarTreLineaCreditoAprobacionByIdLineaCreditoIdAprobacion"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:EliminarTreLineaCreditoAprobacionByIdLineaCreditoIdAprobacion"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="EliminarTreLineaCreditoAprobacionByIdLineaRequestMessage">
    <part name="EliminarTreLineaCreditoAprobacionByIdLineaRequest"
          element="linCrBO:EliminarTreLineaCreditoAprobacionByIdLineaRequest"/>
  </message>
  <message name="EliminarTreLineaCreditoAprobacionByIdLineaResponseMessage">
    <part name="EliminarTreLineaCreditoAprobacionByIdLineaResponse"
          element="linCrBO:EliminarTreLineaCreditoAprobacionByIdLineaResponse"/>
  </message>
  <portType name="EliminarTreLineaCreditoAprobacionByIdLineaCreditoAprobacionPT">
    <operation name="EliminarTreLineaCreditoAprobacionByIdLineaCreditoAprobacion">
      <input message="tns:EliminarTreLineaCreditoAprobacionByIdLineaRequestMessage"/>
      <output message="tns:EliminarTreLineaCreditoAprobacionByIdLineaResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarTreLineaCreditoAprobacionByIdLineaCreditoAprobacionPTSOAP12Binding"
           type="tns:EliminarTreLineaCreditoAprobacionByIdLineaCreditoAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="EliminarTreLineaCreditoAprobacionByIdLineaCreditoAprobacion">
      <soap12:operation style="document"
                        soapAction="urn:EliminarTreLineaCreditoAprobacionByIdLineaCreditoIdAprobacion/EliminarTreLineaCreditoAprobacionByIdLineaCreditoAprobacion"/>
      <input>
        <soap12:body use="literal" parts="EliminarTreLineaCreditoAprobacionByIdLineaRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="EliminarTreLineaCreditoAprobacionByIdLineaResponse"/>
      </output>
    </operation>
  </binding>
</definitions>