<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ValidarRegistroFLEXCUBESAD" 
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ValidarRegistroFLEXCUBESAD"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:liMO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ValidarRegistroFLEXCUBESAD/types" elementFormDefault="qualified">
   <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ValidarRegistroRequestMessage">
    <part name="inMsg" element="liMO:ValidarRegistroFLEXCUBERequest"/>
  </message>
  <message name="ValidarRegistroResponseMessage">
    <part name="outMsg" element="liMO:ValidarRegistroFLEXCUBEResponse"/>
  </message>
  <portType name="ValidarRegistroFLEX_PT">
        <operation name="validarRegistros">
            <input message="tns:ValidarRegistroRequestMessage"/>
            <output message="tns:ValidarRegistroResponseMessage"/>
        </operation>
    </portType>
     <binding name="ValidarRegistro_PT12Bnd" type="tns:ValidarRegistroFLEX_PT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="validarRegistros">
            <soap12:operation style="document"
                              soapAction="http://www.bcie.org/LineaCreditoService/validarRegistros"/>
            <input>
                <soap12:body use="literal" parts="inMsg"/>
            </input>
            <output>
                <soap12:body use="literal" parts="outMsg"/>
            </output>
        </operation>
    </binding>
</definitions>