<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ClienteService" 
            xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ClienteService" 
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:cliMO="http://www.bcie.org/ClienteMO" >
   <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ClienteMO" schemaLocation="../../Schema/ClienteMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
 <message name="requestValidarReservaMessage">
  <part name="request" element="cliMO:ValidarReservaRequest"/>
 </message>
 <message name="responseValidarReservaMessage">
  <part name="response" element="cliMO:ValidarReservaResponse"/>
 </message>
 <portType name="ValidarReservaPT">
  <operation name="validarReserva">
   <input message="tns:requestValidarReservaMessage"/>
   <output message="tns:responseValidarReservaMessage"/>
  </operation>
 </portType>
 <binding name="ValidarReservaPTSOAP12Binding" type="tns:ValidarReservaPT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="validarReserva">
   <soap12:operation style="document" soapAction="http://xmlns.bcie.com/ClienteService/validarReserva"/>
   <input>
    <soap12:body use="literal" parts="request"/>
   </input>
   <output>
    <soap12:body use="literal" parts="response"/>
   </output>
  </operation>
 </binding>
</definitions>