<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="JDAModifyBuyerProcessBPEL" targetNamespace="http://xmlns.oracle.com/JDAModifyBuyerProcess/JDAModifyBuyerProcess/JDAModifyBuyerProcessBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/JDAModifyBuyerProcess/JDAModifyBuyerProcess/JDAModifyBuyerProcessBPEL" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Foundation/Party/BuyerEntitySvc" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Foundation/Party/BuyerEntitySvc" schemaLocation="../Schemas/BuyerEntitySchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="JDAModifyBuyerProcessBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:modifyBuyerRequest"/>
   </wsdl:message>
   <wsdl:message name="JDAModifyBuyerProcessBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:modifyBuyerResponse"/>
   </wsdl:message>
   <wsdl:portType name="JDAModifyBuyerProcessBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:JDAModifyBuyerProcessBPELRequestMessage"/>
         <wsdl:output message="client:JDAModifyBuyerProcessBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="JDAModifyBuyerProcessBPEL">
      <plnk:role name="JDAModifyBuyerProcessBPELProvider" portType="client:JDAModifyBuyerProcessBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
