<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreAbroadApp/QueryStoreAbroadRmsDbReference" name="QueryStoreAbroadRmsDbReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QueryStoreAbroadRmsDbReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreAbroadApp/QueryStoreAbroadRmsDbReference"/>
    <wsdl:binding name="QueryStoreAbroadRmsDbReference_ptt-binding" type="quer:QueryStoreAbroadRmsDbReference_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/StoreAbroadApp/QueryStoreAbroadRmsDbReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QueryStoreAbroadRmsDbReferenceSelect">
            <soap:operation soapAction="QueryStoreAbroadRmsDbReferenceSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>