<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarHoraCierreMoneda/ConsultarHoraCierreMoneda" name="ConsultarHoraCierreMoneda_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarHoraCierreMoneda.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarHoraCierreMoneda/ConsultarHoraCierreMoneda"/>
    <wsdl:binding name="ConsultarHoraCierreMoneda_ptt-binding" type="con:ConsultarHoraCierreMoneda_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/AdaptadoresBCIE/ConsultarHoraCierreMoneda/ConsultarHoraCierreMoneda">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarHoraCierreMoneda">
            <soap:operation soapAction="ConsultarHoraCierreMoneda"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>