<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/QueueAGRIBApp/Governance/ProduceMessage" name="ProduceMessageWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ProduceMessage.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/QueueAGRIBApp/Governance/ProduceMessage"/>
    <wsdl:binding name="Produce_Message_ptt-binding" type="prod:Produce_Message_ptt" xmlns:prod="http://xmlns.oracle.com/pcbpel/adapter/jms/QueueAGRIBApp/Governance/ProduceMessage">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Produce_Message">
            <soap:operation soapAction="Produce_Message"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>