<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/Capabilities/ItemCatalogsList" name="ItemCatalogsList-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ItemCatalogsList.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/Capabilities/ItemCatalogsList"/>
    <wsdl:binding name="ItemCatalogsList_ptt-binding" type="item:ItemCatalogsList_ptt" xmlns:item="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/Capabilities/ItemCatalogsList">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ItemCatalogsListSelect">
            <soap:operation soapAction="ItemCatalogsListSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>