<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/RetailOperations/ItemApplicationsList" name="ItemApplicationsList-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ItemApplicationsList.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/RetailOperations/ItemApplicationsList"/>
    <wsdl:binding name="ItemApplicationsList_ptt-binding" type="item:ItemApplicationsList_ptt" xmlns:item="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/RetailOperations/ItemApplicationsList">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ItemApplicationsListSelect">
            <soap:operation soapAction="ItemApplicationsListSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>