<wsdl:definitions name="ItemApplicationsList" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/RetailOperations/ItemApplicationsList" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/RetailOperations/ItemApplicationsList" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ItemApplicationsList" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ItemApplicationsList" schemaLocation="ItemApplicationsList_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ItemApplicationsListSelect_inputParameters">
        <wsdl:part name="ItemApplicationsListSelect_inputParameters" element="top:ItemApplicationsListSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="MdmApplicationsCollection_msg">
        <wsdl:part name="MdmApplicationsCollection" element="top:MdmApplicationsCollection"/>
    </wsdl:message>
    <wsdl:portType name="ItemApplicationsList_ptt">
        <wsdl:operation name="ItemApplicationsListSelect">
            <wsdl:input message="tns:ItemApplicationsListSelect_inputParameters"/>
            <wsdl:output message="tns:MdmApplicationsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ItemApplicationsListBinding" type="tns:ItemApplicationsList_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ItemApplicationsListSelect">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/pcbpel/adapter/db/TaskActionPXY/RetailOperations/ItemApplicationsList/ItemApplicationsListSelect"/>
            <wsdl:input>
                <soap:body use="literal" parts="ItemApplicationsListSelect_inputParameters"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="MdmApplicationsCollection"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>