
package org.bcie.desembolso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.bcie.desembolsomo.ActualizarEstadoContratoDesembolsoRequestType;
import org.bcie.desembolsomo.ActualizarEstadoContratoDesembolsoResponseType;
import org.bcie.desembolsomo.AplicarCompensacionDesembolsoRequestType;
import org.bcie.desembolsomo.AplicarCompensacionDesembolsoResponseType;
import org.bcie.desembolsomo.CalcularCuotasRequestType;
import org.bcie.desembolsomo.CalcularCuotasResponseType;
import org.bcie.desembolsomo.CondicionesDesembolsoRequestType;
import org.bcie.desembolsomo.CondicionesDesembolsoResponseType;
import org.bcie.desembolsomo.ConsultarCargoComisionRequestType;
import org.bcie.desembolsomo.ConsultarCargoComisionResponseType;
import org.bcie.desembolsomo.ConsultarDesembolsoBPELRequestType;
import org.bcie.desembolsomo.ConsultarDesembolsoBPELResponseType;
import org.bcie.desembolsomo.ConsultarSaldoRequestType;
import org.bcie.desembolsomo.ConsultarSaldoResponseType;
import org.bcie.desembolsomo.CrearActualizarDesembolsosRequestType;
import org.bcie.desembolsomo.CrearActualizarDesembolsosResponseType;
import org.bcie.desembolsomo.EnvioGastoBPELRequestType;
import org.bcie.desembolsomo.EnvioGastoBPELResponseType;
import org.bcie.desembolsomo.ExceptuarSolicitudRequestType;
import org.bcie.desembolsomo.ExceptuarSolicitudResponseType;
import org.bcie.desembolsomo.GeneraReportePlanAmortizacionRequestType;
import org.bcie.desembolsomo.GeneraReportePlanAmortizacionResponseType;
import org.bcie.desembolsomo.PropagarContratoDesembolsoRequestType;
import org.bcie.desembolsomo.PropagarContratoDesembolsoResponseType;
import org.bcie.desembolsomo.PropagarReservaRequestType;
import org.bcie.desembolsomo.PropagarReservaResponseType;
import org.bcie.desembolsomo.PropagarTransSinSalidaRecursosRequestType;
import org.bcie.desembolsomo.PropagarTransSinSalidaRecursosResponseType;
import org.bcie.desembolsomo.PropagarTransferenciaRequestType;
import org.bcie.desembolsomo.PropagarTransferenciaResponseType;
import org.bcie.desembolsomo.PropagarUtilizacionRequestType;
import org.bcie.desembolsomo.PropagarUtilizacionResponseType;
import org.bcie.desembolsomo.ValidarFechaVencimientoRequestType;
import org.bcie.desembolsomo.ValidarFechaVencimientoResponseType;
import org.bcie.desembolsomo.ValidarMontoMaximoDesembolsoRequestType;
import org.bcie.desembolsomo.ValidarMontoMaximoDesembolsoResponseType;
import org.bcie.desembolsomo.ValidarReglasDesembolsoRequestType;
import org.bcie.desembolsomo.ValidarReglasDesembolsoResponseType;
import org.bcie.desembolsomo.VerificarValidacionAsignacionRequestType;
import org.bcie.desembolsomo.VerificarValidacionAsignacionResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Desembolso_PT", targetNamespace = "http://www.bcie.org/Desembolso")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.bcie.desembolsobo.ObjectFactory.class,
    org.bcie.atributobo.ObjectFactory.class,
    org.bcie.catalogobo.ObjectFactory.class,
    org.bcie.clientebo.ObjectFactory.class,
    org.bcie.comisionbo.ObjectFactory.class,
    org.bcie.commonbo.ObjectFactory.class,
    org.bcie.condicionbo.ObjectFactory.class,
    org.bcie.contratobo.ObjectFactory.class,
    org.bcie.declaracionjuradabo.ObjectFactory.class,
    org.bcie.desembolsomo.ObjectFactory.class,
    org.bcie.documentobo.ObjectFactory.class,
    org.bcie.errorbo.ObjectFactory.class,
    org.bcie.herramientacebo.ObjectFactory.class,
    org.bcie.lineacreditobo.ObjectFactory.class,
    org.bcie.matriztccbo.ObjectFactory.class,
    org.bcie.operacionbo.ObjectFactory.class,
    org.bcie.productobo.ObjectFactory.class,
    org.bcie.reglabo.ObjectFactory.class,
    org.bcie.reglatareabo.ObjectFactory.class,
    org.bcie.resultbo.ObjectFactory.class,
    org.bcie.terminobo.ObjectFactory.class
})
public interface DesembolsoPT {


    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.AplicarCompensacionDesembolsoResponseType
     */
    @WebMethod(operationName = "AplicarCompensacionDesembolso", action = "http://www.bcie.org/Desembolso/AplicarCompensacionDesembolso")
    @WebResult(name = "AplicarCompensacionDesembolsoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public AplicarCompensacionDesembolsoResponseType aplicarCompensacionDesembolso(
        @WebParam(name = "AplicarCompensacionDesembolsoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        AplicarCompensacionDesembolsoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.PropagarUtilizacionResponseType
     */
    @WebMethod(operationName = "PropagarUtilizacion", action = "http://www.bcie.org/Desembolso/PropagarUtilizacion")
    @WebResult(name = "PropagarUtilizacionResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public PropagarUtilizacionResponseType propagarUtilizacion(
        @WebParam(name = "PropagarUtilizacionRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        PropagarUtilizacionRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ConsultarCargoComisionResponseType
     */
    @WebMethod(operationName = "ConsultarCargoComision", action = "http://www.bcie.org/Desembolso/ConsultarCargoComision")
    @WebResult(name = "ConsultarCargoComisionResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ConsultarCargoComisionResponseType consultarCargoComision(
        @WebParam(name = "ConsultarCargoComisionRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ConsultarCargoComisionRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ValidarReglasDesembolsoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ValidarReglasDesembolso/validarReglasDesembolso")
    @WebResult(name = "ValidarReglasDesembolsoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ValidarReglasDesembolsoResponseType validarReglasDesembolso(
        @WebParam(name = "ValidarReglasDesembolsoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ValidarReglasDesembolsoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ConsultarDesembolsoBPELResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ConsultarDesembolsoSOR/consultarDesembolso")
    @WebResult(name = "ConsultarDesembolsoBPELResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ConsultarDesembolsoBPELResponseType consultarDesembolso(
        @WebParam(name = "ConsultarDesembolsoBPELRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ConsultarDesembolsoBPELRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ExceptuarSolicitudResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ExceptuarSolicitudSAD/exceptuarSolicitud")
    @WebResult(name = "ExceptuarSolicitudResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ExceptuarSolicitudResponseType exceptuarSolicitud(
        @WebParam(name = "ExceptuarSolicitudRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ExceptuarSolicitudRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.PropagarReservaResponseType
     */
    @WebMethod(action = "http://www.bcie.org/PropagarReservaSOR/propagarReserva")
    @WebResult(name = "PropagarReservaResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public PropagarReservaResponseType propagarReserva(
        @WebParam(name = "PropagarReservaRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        PropagarReservaRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.PropagarTransferenciaResponseType
     */
    @WebMethod(action = "http://www.bcie.org/PropagarTransferenciaSOR/propagarTransferencia")
    @WebResult(name = "PropagarTransferenciaResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public PropagarTransferenciaResponseType propagarTransferencia(
        @WebParam(name = "PropagarTransferenciaRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        PropagarTransferenciaRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.PropagarContratoDesembolsoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/PropagarContratoDesembolsoSOR/propagarContratoDesembolso")
    @WebResult(name = "PropagarContratoDesembolsoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public PropagarContratoDesembolsoResponseType propagarContratoDesembolso(
        @WebParam(name = "PropagarContratoDesembolsoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        PropagarContratoDesembolsoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.PropagarTransSinSalidaRecursosResponseType
     */
    @WebMethod(action = "http://www.bcie.org/PropagarTransSinSalidaRecursosSOR/propagarTransSinSalidaRecursos")
    @WebResult(name = "PropagarTransSinSalidaRecursosResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public PropagarTransSinSalidaRecursosResponseType propagarTransSinSalidaRecursos(
        @WebParam(name = "PropagarTransSinSalidaRecursosRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        PropagarTransSinSalidaRecursosRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ConsultarSaldoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ConsultarSaldoSAD/consultarSaldo")
    @WebResult(name = "ConsultarSaldoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ConsultarSaldoResponseType consultarSaldo(
        @WebParam(name = "ConsultarSaldoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ConsultarSaldoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.EnvioGastoBPELResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ConsultarSaldoSAD/consultarSaldo")
    @WebResult(name = "EnvioGastoBPELResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public EnvioGastoBPELResponseType liquidarContrato(
        @WebParam(name = "EnvioGastoBPELRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        EnvioGastoBPELRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.VerificarValidacionAsignacionResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ConsultarSaldoSAD/verificarValidacionAsignacion")
    @WebResult(name = "VerificarValidacionAsignacionResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public VerificarValidacionAsignacionResponseType verificarValidacionAsignacion(
        @WebParam(name = "VerificarValidacionAsignacionRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        VerificarValidacionAsignacionRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.CalcularCuotasResponseType
     */
    @WebMethod(action = "http://www.bcie.org/calcularCuotasSAD/calcularCuotas")
    @WebResult(name = "CalcularCuotasResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public CalcularCuotasResponseType calcularCuotas(
        @WebParam(name = "CalcularCuotasRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        CalcularCuotasRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.CrearActualizarDesembolsosResponseType
     */
    @WebMethod(action = "http://www.bcie.org/CrearActualizarDesembolsoSAD/crearActualizarDesembolso")
    @WebResult(name = "CrearActualizarDesembolsosResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public CrearActualizarDesembolsosResponseType actualizarDesembolso(
        @WebParam(name = "CrearActualizarDesembolsosRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        CrearActualizarDesembolsosRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.GeneraReportePlanAmortizacionResponseType
     */
    @WebMethod(action = "http://www.bcie.org/GenerarReportePlanAmortizacionSAD/GenerarReportePlanAmortizacion")
    @WebResult(name = "GeneraReportePlanAmortizacionResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public GeneraReportePlanAmortizacionResponseType generarReportePlanAmortizacion(
        @WebParam(name = "GeneraReportePlanAmortizacionRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        GeneraReportePlanAmortizacionRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ValidarMontoMaximoDesembolsoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ValidarMontoMaximoDesembolsoSAD/ValidarMontoMaximoDesembolso")
    @WebResult(name = "ValidarMontoMaximoDesembolsoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ValidarMontoMaximoDesembolsoResponseType validarMontoMaximoDesembolso(
        @WebParam(name = "ValidarMontoMaximoDesembolsoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ValidarMontoMaximoDesembolsoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ValidarFechaVencimientoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ValidarFechaVencimientoSAD/ValidarFechaVencimiento")
    @WebResult(name = "ValidarFechaVencimientoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ValidarFechaVencimientoResponseType validarFechaVencimiento(
        @WebParam(name = "ValidarFechaVencimientoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ValidarFechaVencimientoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.ActualizarEstadoContratoDesembolsoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/ValidarFechaVencimientoSAD/ActualizarEstadoContratoDesembolso")
    @WebResult(name = "ActualizarEstadoContratoDesembolsoResponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public ActualizarEstadoContratoDesembolsoResponseType actualizarEstadoContratoDesembolso(
        @WebParam(name = "ActualizarEstadoContratoDesembolsoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        ActualizarEstadoContratoDesembolsoRequestType request);

    /**
     * 
     * @param request
     * @return
     *     returns org.bcie.desembolsomo.CondicionesDesembolsoResponseType
     */
    @WebMethod(action = "http://www.bcie.org/CondicionesDesmbolsoSOR/CondicionesDesembolso")
    @WebResult(name = "CondicionesDesembolsoReponse", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "response")
    public CondicionesDesembolsoResponseType condicionesDesembolso(
        @WebParam(name = "CondicionesDesembolsoRequest", targetNamespace = "http://www.bcie.org/DesembolsoMO", partName = "request")
        CondicionesDesembolsoRequestType request);

}
