<wsdl:definitions
     name="FTPPriceChangeMonitorPXY"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/AGPriceChangeAppV2/FTPPriceChange/FTPPriceChangeMonitorPXY"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/AGPriceChangeAppV2/FTPPriceChange/FTPPriceChangeMonitorPXY"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
    <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
            xmlns="http://www.w3.org/2001/XMLSchema" >
      <element name="opaqueElement" type="base64Binary" />
    </schema>
    </wsdl:types>
    <wsdl:message name="Get_msg">
        <wsdl:part name="opaque" element="opaque:opaqueElement"/>
    </wsdl:message>
    <wsdl:portType name="Get_ptt">
        <wsdl:operation name="Get">
            <wsdl:input message="tns:Get_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>