<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidarLimiteProgramaSOR"
     targetNamespace="http://www.bcie.org/ValidarLimiteProgramaSOR"
     xmlns:tns="http://www.bcie.org/ValidarLimiteProgramaSOR"
     xmlns:desBO="http://www.bcie.org/DesembolsoMO"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.bcie.org/DesembolsoMO" schemaLocation="../../Schema/DesembolsoMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestValidarLimiteProgramaBPELMessage">
        <wsdl:part name="request" element="desBO:ValidarLimiteProgramaBPELRequest"/>
    </wsdl:message>
    <wsdl:message name="responseValidarLimiteProgramaBPELMessage">
        <wsdl:part name="response" element="desBO:ValidarLimiteProgramaBPELResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarLimitePrograma_PT">
        <wsdl:operation name="ValidarLimitePrograma">
            <wsdl:input message="tns:requestValidarLimiteProgramaBPELMessage"/>
            <wsdl:output message="tns:responseValidarLimiteProgramaBPELMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarLimitePrograma_PTSOAP12Binding" type="tns:ValidarLimitePrograma_PT">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ValidarLimitePrograma">
            <soap12:operation style="document"
                              soapAction="http://www.bcie.org/ValidarLimiteProgramaSOR/ValidarLimitePrograma"/>
            <wsdl:input>
                <soap12:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" parts="response"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
