<wsdl:definitions name="ActualizarReactivarOperacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarReactivarOperacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ActualizarReactivarOperacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarReactivarOperacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ActualizarReactivarOperacion_DB_plt">
    <plt:role name="ActualizarReactivarOperacion_DB_role">
      <plt:portType name="tns:ActualizarReactivarOperacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarReactivarOperacion_DB" schemaLocation="../XSD/ActualizarReactivarOperacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarReactivarOperacion_DBInput_msg">
        <wsdl:part name="ActualizarReactivarOperacion_DBInput_msg" element="db:ActualizarReactivarOperacion_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarReactivarOperacion_DB_ptt">
        <wsdl:operation name="ActualizarReactivarOperacion_DB">
            <wsdl:input message="tns:ActualizarReactivarOperacion_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>