<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/ComisionesDesembolsoSOR"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/ComisionesDesembolsoSOR"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.bcie.com/ComisionService"
    >
    <plnk:partnerLinkType name="ComisionesDesembolso">
        <plnk:role name="ComisionesDesembolsoPT" portType="tns:ComisionesDesembolsoPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/ComisionesDesembolsoSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioDesembolso/Desembolso/V1/Wsdl/BPEL/ComisionesDesembolsoSOR.wsdl"/>
    <wsdl:import namespace="http://xmlns.bcie.com/ComisionService" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/Comision/V1/Wsdl/ADAPTER/ConsultarComisionSAD.wsdl"/>
</wsdl:definitions>
