<wsdl:definitions name="EliminarUsuarioAprobacionByIdAprobacion_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarUsuarioAprobacionByIdAprobacion_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/EliminarUsuarioAprobacionByIdAprobacion_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarUsuarioAprobacionByIdAprobacion_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="EliminarUsuarioAprobacionByIdAprobacion_DB_plt">
    <plt:role name="EliminarUsuarioAprobacionByIdAprobacion_DB_role">
      <plt:portType name="tns:EliminarUsuarioAprobacionByIdAprobacion_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EliminarUsuarioAprobacionByIdAprobacion_DB" schemaLocation="../XSD/EliminarUsuarioAprobacionByIdAprobacion_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EliminarUsuarioAprobacionByIdAprobacion_DBInput_msg">
        <wsdl:part name="EliminarUsuarioAprobacionByIdAprobacion_DBInput_msg" element="db:EliminarUsuarioAprobacionByIdAprobacion_DBInput"/>
    </wsdl:message>
    <wsdl:portType name="EliminarUsuarioAprobacionByIdAprobacion_DB_ptt">
        <wsdl:operation name="EliminarUsuarioAprobacionByIdAprobacion_DB">
            <wsdl:input message="tns:EliminarUsuarioAprobacionByIdAprobacion_DBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>