<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             name="ConfiguracionProcesos"
             xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO" >
             
 <wsdl:types>
    <xsd:schema   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO"
                  schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
 <wsdl:message name="ConfiguracionCierreRequestMessage">
  <wsdl:part name="ConfiguracionCierreRequest" element="confMO:configuracionCierreRequest"/>
 </wsdl:message>
 <wsdl:message name="ConfiguracionCierreResponseMessage">
  <wsdl:part name="ConfiguracionCierreResponse" element="confMO:configuracionCierreResponse"/>
 </wsdl:message>
 <wsdl:portType name="ConfiguracionCierrePT">
  <wsdl:operation name="ConfiguracionCierre">
   <wsdl:input message="tns:ConfiguracionCierreRequestMessage"/>
   <wsdl:output message="tns:ConfiguracionCierreResponseMessage"/>
  </wsdl:operation>
 </wsdl:portType>
 <wsdl:binding name="ConfiguracionCierrePTSOAP12Binding" type="tns:ConfiguracionCierrePT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="ConfiguracionCierre">
   <soap12:operation style="document"
                     soapAction="http://xmlns.bcie.com/ConfiguracionProcesosService/ConfiguracionCierre"/>
   <wsdl:input>
    <soap12:body use="literal" parts="ConfiguracionCierreRequest"/>
   </wsdl:input>
   <wsdl:output>
    <soap12:body use="literal" parts="ConfiguracionCierreResponse"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
</wsdl:definitions>