<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions name="Operacion" targetNamespace="http://xmlns.bcie.com/CargoTramiteService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:comMO="http://www.bcie.org/ComisionMO"
                  xmlns:tns="http://xmlns.bcie.com/CargoTramiteService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ComisionMO"
                  schemaLocation="../../Schema/ComisionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <!-- Create -->
  <wsdl:message name="requestCrearCargoTramiteMessage">
    <wsdl:part name="request" element="comMO:CrearCargoTramiteRequest"/>
  </wsdl:message>
  <wsdl:message name="responseCrearCargoTramiteMessage">
    <wsdl:part name="response" element="comMO:CrearCargoTramiteResponse"/>
  </wsdl:message>
  <wsdl:portType name="CrearCargoTramitePT">
    <!-- Create -->
    <wsdl:operation name="crearCargoTramite">
      <wsdl:input message="tns:requestCrearCargoTramiteMessage"/>
      <wsdl:output message="tns:responseCrearCargoTramiteMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CrearCargoTramite12Bnd" type="tns:CrearCargoTramitePT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearCargoTramite">
      <soap12:operation style="document" soapAction="http://xmlns.bcie.com/CargoTramiteService/crearCargoTramite"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CargoTramite">
    <wsdl:port name="CrearCargoTramite12Bnd" binding="tns:CrearCargoTramite12Bnd">
      <soap12:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>






