
CREATE OR REPLACE TRIGGER CONTRATO_DESEMBOLSO_TGR
AFTER INSERT   ON CONTRATO_DESEMBOLSO FOR EACH ROW
DECLARE
	CONTRATO NUMBER(12,0);
	ID_REGLA NUMBER(5,0);
	err_num NUMBER;
	err_msg VARCHAR2(255);
   
	CURSOR c1 IS
		SELECT ID 
		FROM TCA_REGLA_PROCESO
		WHERE TIPO = 'DESEMBOLSO';

BEGIN
	-- A cada contrato de desembolso que se inserte, se le asignan las reglas a verificar para el proceso de desembolsos
	CONTRATO := :NEW.ID;
	--SELECT :NEW.ID INTO CONTRATO FROM DUAL;
	OPEN c1;
		LOOP
			FETCH c1 INTO ID_REGLA;
			EXIT WHEN c1%notfound;
      
			INSERT INTO TRE_REGLA_DESEMBOLSO (ID,ID_DESEMBOLSO,ID_TCA_REGLA,EXCEPTUADO,USUARIOEXCEPTUA,FECHA_EXCEPCION)
            VALUES (TRE_REGLA_DESEMBOLSO_SEQ.NEXTVAL,CONTRATO,ID_REGLA,0,NULL,NULL);

		END LOOP;
   CLOSE c1;

EXCEPTION 
	WHEN OTHERS THEN
		err_num := SQLCODE;
		err_msg := SQLERRM;
		
		INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
		VALUES('TRG','TRIGGER CONTRATO_DESEMBOLSO_TRG','Contrato: '||CONTRATO||' Error:'||TO_CHAR(err_num)||' '||SUBSTR(err_msg,1,520),TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
	END;
/