
  CREATE OR REPLACE FUNCTION F_VALIDA_AGRUPADOR 
(
  AGRUPADOR IN NUMBER DEFAULT 0 
) RETURN NUMBER AS 
BEGIN
  IF AGRUPADOR = 0
    THEN 
      RETURN NULL;
  ELSE 
      RETURN AGRUPADOR;
  END IF;
END F_VALIDA_AGRUPADOR;

/
