CREATE OR REPLACE TRIGGER FENIX.SUPERVISION_UPD_TGR 
	AFTER UPDATE ON FENIX.SUPERVISION FOR EACH ROW
	DECLARE 
	v_id_tbi_supervision NUMBER;	
	err_num NUMBER;
	err_msg VARCHAR2(255);

	BEGIN
		IF (:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO IS NOT NULL) 
		THEN

			SELECT TBI_SUPERVISION_SEQ.NEXTVAL INTO v_id_tbi_supervision FROM DUAL;
		  
			INSERT INTO TBI_SUPERVISION (ID, ID_SUPERVISION, TIPO_ACCION, LOGIN_SOLICITANTE, NOMBRE_SOLICITANTE, FECHA_REGISTRO) VALUES(v_id_tbi_supervision,:NEW.ID,'MODIFICAR_SUPERVISION',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,SYSDATE);  
					
			IF UPDATING ('ID_OPERACION') THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES (v_id_tbi_supervision,'ID_OPERACION',:NEW.ID_OPERACION,:OLD.ID_OPERACION);
			END IF;  
			IF UPDATING ('ID_TCA_SCT')THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'ID_TCA_SCT',:NEW.ID_TCA_SCT,:OLD.ID_TCA_SCT);
			END IF;  
			IF UPDATING('CALIFICACION_FINAL')THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'CALIFICACION_FINAL',:NEW.CALIFICACION_FINAL,:OLD.CALIFICACION_FINAL);
			END IF;  
			IF UPDATING('FECHA_REGISTRO')THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'FECHA_REGISTRO',:NEW.FECHA_REGISTRO,:OLD.FECHA_REGISTRO);
			END IF;  
			IF UPDATING('FECHA_VISITA')THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'FECHA_VISITA',:NEW.FECHA_VISITA,:OLD.FECHA_VISITA);
			END IF;  
			IF UPDATING('FECHA_AVANCE')THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'FECHA_AVANCE',:NEW.FECHA_AVANCE,:OLD.FECHA_AVANCE);
			END IF;  
			IF UPDATING('FECHA_INFORME')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'FECHA_INFORME',:NEW.FECHA_INFORME,:OLD.FECHA_INFORME);
			END IF;  
			IF UPDATING('AVANCE_FISICO')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'AVANCE_FISICO',:NEW.AVANCE_FISICO,:OLD.AVANCE_FISICO);
			END IF;  
			IF UPDATING('AVANCE_FINANCIERO')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'AVANCE_FINANCIERO',:NEW.AVANCE_FINANCIERO,:OLD.AVANCE_FINANCIERO);
			END IF;  
			IF UPDATING('TIPO_ACTUALIZACION')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'TIPO_ACTUALIZACION',:NEW.TIPO_ACTUALIZACION,:OLD.TIPO_ACTUALIZACION);
			END IF;  
			IF UPDATING('ES_PROYECTO_EN_OPERACION')THEN
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'ES_PROYECTO_EN_OPERACION',:NEW.ES_PROYECTO_EN_OPERACION,:OLD.ES_PROYECTO_EN_OPERACION);
			END IF;  
			IF UPDATING('INSTANCIA_PROCESO')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'INSTANCIA_PROCESO',:NEW.INSTANCIA_PROCESO,:OLD.INSTANCIA_PROCESO);
			END IF;  
			IF UPDATING('BAN_ESTATUS')THEN 
			   INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'BAN_ESTATUS',:NEW.BAN_ESTATUS,:OLD.BAN_ESTATUS); 
			END IF;  		
			IF UPDATING('LOGIN_USUARIO')THEN 
			   INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'LOGIN_USUARIO',:NEW.LOGIN_USUARIO,:OLD.LOGIN_USUARIO);
			END IF;  	
			IF UPDATING('NOMBRE_USUARIO')THEN 
			   INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'NOMBRE_USUARIO',:NEW.NOMBRE_USUARIO,:OLD.NOMBRE_USUARIO);
			END IF;  	
			IF UPDATING('LOGIN_USUARIO_ULTIMO_CAMBIO')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'LOGIN_USUARIO_ULTIMO_CAMBIO',:NEW.LOGIN_USUARIO_ULTIMO_CAMBIO,:OLD.LOGIN_USUARIO_ULTIMO_CAMBIO);
			END IF;  
			IF UPDATING('NOMBRE_USUARIO_ULTIMO_CAMBIO')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'NOMBRE_USUARIO_ULTIMO_CAMBIO',:NEW.NOMBRE_USUARIO_ULTIMO_CAMBIO,:OLD.NOMBRE_USUARIO_ULTIMO_CAMBIO);
			END IF;  
			IF UPDATING('FECHA_ULTIMO_CAMBIO')THEN  
			  INSERT INTO TBI_SUPERVISION_CAMPO (ID_BITACORA, CAMPO, VALOR_NUEVO, VALOR_ANTERIOR) VALUES(v_id_tbi_supervision,'FECHA_ULTIMO_CAMBIO',:NEW.FECHA_ULTIMO_CAMBIO,:OLD.FECHA_ULTIMO_CAMBIO);
			END IF;  
		END IF;
	
	EXCEPTION
		WHEN OTHERS THEN
			err_num := SQLCODE;
			err_msg := SUBSTR(SQLERRM,1,250);
			
			
			DBMS_OUTPUT.put_line('Error al actualizar en la tabla de bitácora de supervisión');		
			DBMS_OUTPUT.put_line('Error: '||TO_CHAR(err_num));
			DBMS_OUTPUT.put_line(err_msg);
			
			
			INSERT INTO TBI_SEGUIMIENTO_ERROR (TIPO_INSUMO,NOMBRE_INSUMO,DESCRIPCION_ERROR,FECHA_REGISTRO)
			VALUES('TRG','SUPERVISION_UPD_TGR','Error: '||TO_CHAR(err_num)||' '|| err_msg,TO_DATE(SYSDATE,'DD-MM-YYYY HH24:MI:SS'));
			COMMIT;
			
	END;