<wsdl:definitions name="clasificacionEstrategicaBD_BS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/clasificacionEstrategicaBD_BS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/clasificacionEstrategicaBD_BS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/clasificacionEstrategicaBD_BS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="clasificacionEstrategicaBD_BS_plt">
    <plt:role name="clasificacionEstrategicaBD_BS_role">
      <plt:portType name="tns:clasificacionEstrategicaBD_BS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/clasificacionEstrategicaBD_BS" schemaLocation="clasificacionEstrategicaBD_BS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ClasificacionEstrategicaCollection_msg">
        <wsdl:part name="ClasificacionEstrategicaCollection" element="top:ClasificacionEstrategicaCollection"/>
    </wsdl:message>
    <wsdl:portType name="clasificacionEstrategicaBD_BS_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:ClasificacionEstrategicaCollection_msg"/>
            <wsdl:output message="tns:ClasificacionEstrategicaCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>