package org.bcie.fenix.common.model.vo;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 06 11:04:00 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FinalizacionEstudiosVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdOperacion,
        IdTipoTasa,
        CodigoTasaReferencia,
        FechaFinalizacionEstudios,
        EsFactible,
        DescripcionMoneda,
        Tasa,
        Spread,
        TasaTotal,
        CodTasRef,
        TcaTipoTasaDesembolsoVO,
        TasaReferenciaVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDOPERACION = AttributesEnum.IdOperacion.index();
    public static final int IDTIPOTASA = AttributesEnum.IdTipoTasa.index();
    public static final int CODIGOTASAREFERENCIA = AttributesEnum.CodigoTasaReferencia.index();
    public static final int FECHAFINALIZACIONESTUDIOS = AttributesEnum.FechaFinalizacionEstudios.index();
    public static final int ESFACTIBLE = AttributesEnum.EsFactible.index();
    public static final int DESCRIPCIONMONEDA = AttributesEnum.DescripcionMoneda.index();
    public static final int TASA = AttributesEnum.Tasa.index();
    public static final int SPREAD = AttributesEnum.Spread.index();
    public static final int TASATOTAL = AttributesEnum.TasaTotal.index();
    public static final int CODTASREF = AttributesEnum.CodTasRef.index();
    public static final int TCATIPOTASADESEMBOLSOVO = AttributesEnum.TcaTipoTasaDesembolsoVO.index();
    public static final int TASAREFERENCIAVO = AttributesEnum.TasaReferenciaVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FinalizacionEstudiosVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public Long getIdOperacion() {
        return (Long) getAttributeInternal(IDOPERACION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setIdOperacion(Long value) {
        setAttributeInternal(IDOPERACION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IdTipoTasa.
     * @return the IdTipoTasa
     */
    public Integer getIdTipoTasa() {
        return (Integer) getAttributeInternal(IDTIPOTASA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IdTipoTasa.
     * @param value value to set the  IdTipoTasa
     */
    public void setIdTipoTasa(Integer value) {
        setAttributeInternal(IDTIPOTASA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CadigoTasaReferencia.
     * @return the CadigoTasaReferencia
     */
    public String getCodigoTasaReferencia() {
        return (String) getAttributeInternal(CODIGOTASAREFERENCIA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CadigoTasaReferencia.
     * @param value value to set the  CadigoTasaReferencia
     */
    public void setCodigoTasaReferencia(String value) {
        setAttributeInternal(CODIGOTASAREFERENCIA, value);
    }


    /**
     * Gets the attribute value for the calculated attribute FechaFinalizacionEstudios.
     * @return the FechaFinalizacionEstudios
     */
    public Date getFechaFinalizacionEstudios() {
        return (Date) getAttributeInternal(FECHAFINALIZACIONESTUDIOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FechaFinalizacionEstudios.
     * @param value value to set the  FechaFinalizacionEstudios
     */
    public void setFechaFinalizacionEstudios(Date value) {
        setAttributeInternal(FECHAFINALIZACIONESTUDIOS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EsFactible.
     * @return the EsFactible
     */
    public Integer getEsFactible() {
        return (Integer) getAttributeInternal(ESFACTIBLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EsFactible.
     * @param value value to set the  EsFactible
     */
    public void setEsFactible(Integer value) {
        setAttributeInternal(ESFACTIBLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DescripcionMoneda.
     * @return the DescripcionMoneda
     */
    public String getDescripcionMoneda() {
        return (String) getAttributeInternal(DESCRIPCIONMONEDA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DescripcionMoneda.
     * @param value value to set the  DescripcionMoneda
     */
    public void setDescripcionMoneda(String value) {
        setAttributeInternal(DESCRIPCIONMONEDA, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Tasa.
     * @return the Tasa
     */
    public oracle.jbo.domain.Number getTasa() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TASA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Tasa.
     * @param value value to set the  Tasa
     */
    public void setTasa(oracle.jbo.domain.Number value) {
        setAttributeInternal(TASA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Spread.
     * @return the Spread
     */
    public Number getSpread() {
        return (Number) getAttributeInternal(SPREAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Spread.
     * @param value value to set the  Spread
     */
    public void setSpread(Number value) {
        setAttributeInternal(SPREAD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TasaTotal.
     * @return the TasaTotal
     */
    public Number getTasaTotal() {
        return (Number) getAttributeInternal(TASATOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TasaTotal.
     * @param value value to set the  TasaTotal
     */
    public void setTasaTotal(Number value) {
        setAttributeInternal(TASATOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CodTasRef.
     * @return the CodTasRef
     */
    public String getCodTasRef() {
        return (String) getAttributeInternal(CODTASREF);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CodTasRef.
     * @param value value to set the  CodTasRef
     */
    public void setCodTasRef(String value) {
        setAttributeInternal(CODTASREF, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TcaTipoTasaDesembolsoVO.
     */
    public RowSet getTcaTipoTasaDesembolsoVO() {
        return (RowSet) getAttributeInternal(TCATIPOTASADESEMBOLSOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TasaReferenciaVO.
     */
    public RowSet getTasaReferenciaVO() {
        return (RowSet) getAttributeInternal(TASAREFERENCIAVO);
    }
}

