package org.bcie.fenix.common.model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 18 23:56:52 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TccLineaCreditoCondicionLOVRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TlccId,
        TlccIdLineaCredito,
        TlccIdTermino,
        TlccIdComision,
        TlccIdCondicion,
        TlccFechaRegistro,
        TlccBanEstatus,
        LcId,
        LcIdContrato,
        LcNumeroLineaCredito,
        LcDescripcionLinea,
        LcIdFlexcube,
        LcFondo,
        LcMontoLinea,
        LcEsRevolvente,
        LcTratamientoDiasFeriados,
        LcIdProductoFlexcube,
        LcFechaValor,
        LcFechaVencimiento,
        LcCodigoPlantillaLimite,
        LcCodigoSerialLimite,
        LcCodigoAsignacion,
        LcDescripcionAsignacion,
        LcIdFlexcubePasivo,
        LcCondicionEspecial,
        LcDescripcionCondEspecial,
        LcFechaRegistro,
        LcBanEstatus;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TLCCID = AttributesEnum.TlccId.index();
    public static final int TLCCIDLINEACREDITO = AttributesEnum.TlccIdLineaCredito.index();
    public static final int TLCCIDTERMINO = AttributesEnum.TlccIdTermino.index();
    public static final int TLCCIDCOMISION = AttributesEnum.TlccIdComision.index();
    public static final int TLCCIDCONDICION = AttributesEnum.TlccIdCondicion.index();
    public static final int TLCCFECHAREGISTRO = AttributesEnum.TlccFechaRegistro.index();
    public static final int TLCCBANESTATUS = AttributesEnum.TlccBanEstatus.index();
    public static final int LCID = AttributesEnum.LcId.index();
    public static final int LCIDCONTRATO = AttributesEnum.LcIdContrato.index();
    public static final int LCNUMEROLINEACREDITO = AttributesEnum.LcNumeroLineaCredito.index();
    public static final int LCDESCRIPCIONLINEA = AttributesEnum.LcDescripcionLinea.index();
    public static final int LCIDFLEXCUBE = AttributesEnum.LcIdFlexcube.index();
    public static final int LCFONDO = AttributesEnum.LcFondo.index();
    public static final int LCMONTOLINEA = AttributesEnum.LcMontoLinea.index();
    public static final int LCESREVOLVENTE = AttributesEnum.LcEsRevolvente.index();
    public static final int LCTRATAMIENTODIASFERIADOS = AttributesEnum.LcTratamientoDiasFeriados.index();
    public static final int LCIDPRODUCTOFLEXCUBE = AttributesEnum.LcIdProductoFlexcube.index();
    public static final int LCFECHAVALOR = AttributesEnum.LcFechaValor.index();
    public static final int LCFECHAVENCIMIENTO = AttributesEnum.LcFechaVencimiento.index();
    public static final int LCCODIGOPLANTILLALIMITE = AttributesEnum.LcCodigoPlantillaLimite.index();
    public static final int LCCODIGOSERIALLIMITE = AttributesEnum.LcCodigoSerialLimite.index();
    public static final int LCCODIGOASIGNACION = AttributesEnum.LcCodigoAsignacion.index();
    public static final int LCDESCRIPCIONASIGNACION = AttributesEnum.LcDescripcionAsignacion.index();
    public static final int LCIDFLEXCUBEPASIVO = AttributesEnum.LcIdFlexcubePasivo.index();
    public static final int LCCONDICIONESPECIAL = AttributesEnum.LcCondicionEspecial.index();
    public static final int LCDESCRIPCIONCONDESPECIAL = AttributesEnum.LcDescripcionCondEspecial.index();
    public static final int LCFECHAREGISTRO = AttributesEnum.LcFechaRegistro.index();
    public static final int LCBANESTATUS = AttributesEnum.LcBanEstatus.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TccLineaCreditoCondicionLOVRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TlccId.
     * @return the TlccId
     */
    public Long getTlccId() {
        return (Long) getAttributeInternal(TLCCID);
    }

    /**
     * Gets the attribute value for the calculated attribute TlccIdLineaCredito.
     * @return the TlccIdLineaCredito
     */
    public Long getTlccIdLineaCredito() {
        return (Long) getAttributeInternal(TLCCIDLINEACREDITO);
    }

    /**
     * Gets the attribute value for the calculated attribute TlccIdTermino.
     * @return the TlccIdTermino
     */
    public Long getTlccIdTermino() {
        return (Long) getAttributeInternal(TLCCIDTERMINO);
    }

    /**
     * Gets the attribute value for the calculated attribute TlccIdComision.
     * @return the TlccIdComision
     */
    public Long getTlccIdComision() {
        return (Long) getAttributeInternal(TLCCIDCOMISION);
    }

    /**
     * Gets the attribute value for the calculated attribute TlccIdCondicion.
     * @return the TlccIdCondicion
     */
    public Long getTlccIdCondicion() {
        return (Long) getAttributeInternal(TLCCIDCONDICION);
    }

    /**
     * Gets the attribute value for the calculated attribute TlccFechaRegistro.
     * @return the TlccFechaRegistro
     */
    public Timestamp getTlccFechaRegistro() {
        return (Timestamp) getAttributeInternal(TLCCFECHAREGISTRO);
    }

    /**
     * Gets the attribute value for the calculated attribute TlccBanEstatus.
     * @return the TlccBanEstatus
     */
    public Integer getTlccBanEstatus() {
        return (Integer) getAttributeInternal(TLCCBANESTATUS);
    }

    /**
     * Gets the attribute value for the calculated attribute LcId.
     * @return the LcId
     */
    public Long getLcId() {
        return (Long) getAttributeInternal(LCID);
    }

    /**
     * Gets the attribute value for the calculated attribute LcIdContrato.
     * @return the LcIdContrato
     */
    public Long getLcIdContrato() {
        return (Long) getAttributeInternal(LCIDCONTRATO);
    }

    /**
     * Gets the attribute value for the calculated attribute LcNumeroLineaCredito.
     * @return the LcNumeroLineaCredito
     */
    public String getLcNumeroLineaCredito() {
        return (String) getAttributeInternal(LCNUMEROLINEACREDITO);
    }

    /**
     * Gets the attribute value for the calculated attribute LcDescripcionLinea.
     * @return the LcDescripcionLinea
     */
    public String getLcDescripcionLinea() {
        return (String) getAttributeInternal(LCDESCRIPCIONLINEA);
    }

    /**
     * Gets the attribute value for the calculated attribute LcIdFlexcube.
     * @return the LcIdFlexcube
     */
    public String getLcIdFlexcube() {
        return (String) getAttributeInternal(LCIDFLEXCUBE);
    }

    /**
     * Gets the attribute value for the calculated attribute LcFondo.
     * @return the LcFondo
     */
    public String getLcFondo() {
        return (String) getAttributeInternal(LCFONDO);
    }

    /**
     * Gets the attribute value for the calculated attribute LcMontoLinea.
     * @return the LcMontoLinea
     */
    public BigDecimal getLcMontoLinea() {
        return (BigDecimal) getAttributeInternal(LCMONTOLINEA);
    }

    /**
     * Gets the attribute value for the calculated attribute LcEsRevolvente.
     * @return the LcEsRevolvente
     */
    public Integer getLcEsRevolvente() {
        return (Integer) getAttributeInternal(LCESREVOLVENTE);
    }

    /**
     * Gets the attribute value for the calculated attribute LcTratamientoDiasFeriados.
     * @return the LcTratamientoDiasFeriados
     */
    public String getLcTratamientoDiasFeriados() {
        return (String) getAttributeInternal(LCTRATAMIENTODIASFERIADOS);
    }

    /**
     * Gets the attribute value for the calculated attribute LcIdProductoFlexcube.
     * @return the LcIdProductoFlexcube
     */
    public String getLcIdProductoFlexcube() {
        return (String) getAttributeInternal(LCIDPRODUCTOFLEXCUBE);
    }

    /**
     * Gets the attribute value for the calculated attribute LcFechaValor.
     * @return the LcFechaValor
     */
    public Timestamp getLcFechaValor() {
        return (Timestamp) getAttributeInternal(LCFECHAVALOR);
    }

    /**
     * Gets the attribute value for the calculated attribute LcFechaVencimiento.
     * @return the LcFechaVencimiento
     */
    public Timestamp getLcFechaVencimiento() {
        return (Timestamp) getAttributeInternal(LCFECHAVENCIMIENTO);
    }

    /**
     * Gets the attribute value for the calculated attribute LcCodigoPlantillaLimite.
     * @return the LcCodigoPlantillaLimite
     */
    public String getLcCodigoPlantillaLimite() {
        return (String) getAttributeInternal(LCCODIGOPLANTILLALIMITE);
    }

    /**
     * Gets the attribute value for the calculated attribute LcCodigoSerialLimite.
     * @return the LcCodigoSerialLimite
     */
    public Integer getLcCodigoSerialLimite() {
        return (Integer) getAttributeInternal(LCCODIGOSERIALLIMITE);
    }

    /**
     * Gets the attribute value for the calculated attribute LcCodigoAsignacion.
     * @return the LcCodigoAsignacion
     */
    public Long getLcCodigoAsignacion() {
        return (Long) getAttributeInternal(LCCODIGOASIGNACION);
    }

    /**
     * Gets the attribute value for the calculated attribute LcDescripcionAsignacion.
     * @return the LcDescripcionAsignacion
     */
    public String getLcDescripcionAsignacion() {
        return (String) getAttributeInternal(LCDESCRIPCIONASIGNACION);
    }

    /**
     * Gets the attribute value for the calculated attribute LcIdFlexcubePasivo.
     * @return the LcIdFlexcubePasivo
     */
    public String getLcIdFlexcubePasivo() {
        return (String) getAttributeInternal(LCIDFLEXCUBEPASIVO);
    }

    /**
     * Gets the attribute value for the calculated attribute LcCondicionEspecial.
     * @return the LcCondicionEspecial
     */
    public Integer getLcCondicionEspecial() {
        return (Integer) getAttributeInternal(LCCONDICIONESPECIAL);
    }

    /**
     * Gets the attribute value for the calculated attribute LcDescripcionCondEspecial.
     * @return the LcDescripcionCondEspecial
     */
    public String getLcDescripcionCondEspecial() {
        return (String) getAttributeInternal(LCDESCRIPCIONCONDESPECIAL);
    }

    /**
     * Gets the attribute value for the calculated attribute LcFechaRegistro.
     * @return the LcFechaRegistro
     */
    public Timestamp getLcFechaRegistro() {
        return (Timestamp) getAttributeInternal(LCFECHAREGISTRO);
    }

    /**
     * Gets the attribute value for the calculated attribute LcBanEstatus.
     * @return the LcBanEstatus
     */
    public Integer getLcBanEstatus() {
        return (Integer) getAttributeInternal(LCBANESTATUS);
    }
}

