package org.bcie.fenix.common.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 05 20:15:04 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TreTipoModalidadAdquisicionVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TreTipoModalidadAdquisicionVOImpl() {
    }

    /**
     * Returns the bind variable value for pIdTipoAdquisicion.
     * @return bind variable value for pIdTipoAdquisicion
     */
    public Integer getpIdTipoAdquisicion() {
        return (Integer) getNamedWhereClauseParam("pIdTipoAdquisicion");
    }

    /**
     * Sets <code>value</code> for bind variable pIdTipoAdquisicion.
     * @param value value to bind as pIdTipoAdquisicion
     */
    public void setpIdTipoAdquisicion(Integer value) {
        setNamedWhereClauseParam("pIdTipoAdquisicion", value);
    }
}

