<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.oracle.com/bpel/workflow/taskService"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://www.bcie.org/CorreoMO" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:ns1="http://xmlns.oracle.com/bpel/workflow/taskError"
                xmlns:command="http://xmlns.oracle.com/bpel/workflow/taskService/command"
                xmlns:routingslip="http://xmlns.oracle.com/bpel/workflow/routingSlip"
                xmlns:tsc="http://xmlns.oracle.com/bpel/workflow/common/tsc"
                xmlns:wfcommon="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:ns4="http://xmlns.oracle.com/bpel/workflow/TaskEvidenceService"
                xmlns:ns2="http://xmlns.oracle.com/bpel/workflow/taskQuery"
                xmlns:ns3="http://xmlns.oracle.com/bpel/workflow/taskQueryService"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task" xmlns:ns6="http://www.bcie.org/ResultBO"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns7="http://www.bcie.org/CorreoBO" xmlns:ns5="http://xmlns.bcie.com/CorreoElectronicoService"
                xmlns:ns8="http://www.bcie.org/ErrorBO" xmlns:ns9="http://www.bcie.org/CatalogoBO"
                xmlns:ns12="http://www.bcie.org/TerminoBO" xmlns:ns13="http://www.bcie.org/ReglaBO"
                xmlns:ns15="http://www.bcie.org/OperacionBO" xmlns:ns16="http://www.bcie.org/CommonBO"
                xmlns:ns21="http://www.bcie.org/LineaCreditoBO" xmlns:ns20="http://www.bcie.org/MatrizTCCBO"
                xmlns:ns11="http://www.bcie.org/ProductoBO" xmlns:ns10="http://www.bcie.org/CondicionBO"
                xmlns:ns14="http://www.bcie.org/DeclaracionJuradaBO" xmlns:ns17="http://www.bcie.org/DocumentoBO"
                xmlns:ns18="http://www.bcie.org/HerramientaCEBO" xmlns:ns19="http://www.bcie.org/ComisionBO"
                xmlns:ns22="http://www.bcie.org/DesembolsoBO" xmlns:ns23="http://www.bcie.org/ContratoBO"
                xmlns:ns24="http://www.bcie.org/ClienteBO" xmlns:ns25="http://www.bcie.org/AtributoBO">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/soa/shared/workflow/TaskService.xsd"/>
        <oracle-xsl-mapper:rootElement name="taskAssignedMessage"
                                       namespace="http://xmlns.oracle.com/bpel/workflow/taskService"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/Utilidades/EnviarCorreoElectronico/V1/WSDL/EnviarCorreoElectronico.wsdl"/>
        <oracle-xsl-mapper:rootElement name="enviarCorreoElectronicoRequest" namespace="http://www.bcie.org/CorreoMO"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT OCT 24 11:37:51 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:enviarCorreoElectronicoRequest>
      <tns:CorreoElectronico>
        <ns7:to>
          <xsl:for-each select="/ns0:taskAssignedMessage/task:task/task:systemAttributes/task:assignees">
            <ns7:usuario>
              <xsl:value-of select="task:id"/>
            </ns7:usuario>
          </xsl:for-each>
        </ns7:to>
        <ns7:idOperacion>
          <xsl:choose>
              <xsl:when test="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Operacion/*:CodigoOperacion">
                  <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Operacion/*:CodigoOperacion"/>
              </xsl:when>
              <xsl:otherwise>
                  <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:OperacionPayload/*:idOperacion"/>
              </xsl:otherwise>
          </xsl:choose>
        </ns7:idOperacion>
        <ns7:idClienteFenix>
          <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Cliente/*:IdCliente"/>
        </ns7:idClienteFenix>
        <ns7:proceso>
          <xsl:choose>
              <xsl:when test="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoProceso">
                  <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoProceso"/>
              </xsl:when>
              <xsl:otherwise>
                  <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:CodigoProceso"/>
              </xsl:otherwise>
          </xsl:choose>
        </ns7:proceso>
        <ns7:evento>ASIGNACION DE TAREA</ns7:evento>
        <ns7:parametros>
          <ns7:tag>TAREA</ns7:tag>
          <ns7:valor>
            <xsl:choose>
                <xsl:when test="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoTarea">
                    <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoTarea"/>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:CodigoTarea"/>
                </xsl:otherwise>
            </xsl:choose>
          </ns7:valor>
        </ns7:parametros>
        <ns7:parametros>
          <ns7:tag>ROL</ns7:tag>
          <ns7:valor>
            <xsl:choose>
                <xsl:when test="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoRol">
                    <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoRol"/>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:CodigoRol"/>
                </xsl:otherwise>
            </xsl:choose>
          </ns7:valor>
        </ns7:parametros>
        <ns7:parametros>
          <ns7:tag>URL_WORKSPACE</ns7:tag>
          <ns7:valor>1</ns7:valor>
        </ns7:parametros>
        <xsl:if test="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:Header/*:Tarea/*:CodigoProceso = 17">
          <ns7:parametros>
            <ns7:tag>CONTRATO_DESEMBOLSO</ns7:tag>
            <ns7:valor>
              <xsl:value-of select="/ns0:taskAssignedMessage/task:task/task:payload/*[1]/*:idDesembolso"/>
            </ns7:valor>
          </ns7:parametros>
        </xsl:if>
      </tns:CorreoElectronico>
    </tns:enviarCorreoElectronicoRequest>
  </xsl:template>
</xsl:stylesheet>
