<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/GovernanceAPIApp/GovernanceAPI/GovernanceAPIJMSPubBS" name="GovernanceAPIJMSPubBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GovernanceAPIJMSPubBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/GovernanceAPIApp/GovernanceAPI/GovernanceAPIJMSPubBS"/>
    <wsdl:binding name="ProduceMessage_ptt-binding" type="gov:ProduceMessage_ptt" xmlns:gov="http://xmlns.oracle.com/pcbpel/adapter/jms/GovernanceAPIApp/GovernanceAPI/GovernanceAPIJMSPubBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ProduceMessage">
            <soap:operation soapAction="ProduceMessage"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>