<wsdl:definitions
     name="ConsultarAprobacionByOperacion"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project10/ConsultarAprobacionByOperacion"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project10/ConsultarAprobacionByOperacion"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAprobacionByOperacion"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultarAprobacionByOperacion_plt" >
    <plt:role name="ConsultarAprobacionByOperacion_role" >
      <plt:portType name="tns:ConsultarAprobacionByOperacion_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAprobacionByOperacion" schemaLocation="../XSD/ConsultarAprobacionByOperacion.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAprobacionByOperacionInput_msg">
        <wsdl:part name="ConsultarAprobacionByOperacionInput_msg" element="db:ConsultarAprobacionByOperacionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAprobacionByOperacionOutputCollection_msg">
        <wsdl:part name="ConsultarAprobacionByOperacionOutputCollection" element="db:ConsultarAprobacionByOperacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAprobacionByOperacion_ptt">
        <wsdl:operation name="ConsultarAprobacionByOperacion">
            <wsdl:input message="tns:ConsultarAprobacionByOperacionInput_msg"/>
            <wsdl:output message="tns:ConsultarAprobacionByOperacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
