<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ActualizarTCC" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://www.bcie.org/ActualizarTCC" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.bcie.org/MapeoErrorMO" xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:ns4="http://www.bcie.org/CondicionService" xmlns:ns5="http://www.bcie.org/MatrizTCCService">
   <plnk:partnerLinkType name="ActualizarTCCPTSOR_PLT">
      <plnk:role name="ActualizarTCCPTSOR_Role" portType="ns1:ActualizarTCCPTSOR"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bcie.org/ActualizarTCC" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/MatrizTCC/V1/Wsdl/BPEL/ActualizarTCCSOR.wsdl"/>
   <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
   <wsdl:import namespace="http://www.bcie.org/CondicionService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Condicion/V1/Wsdl/ADAPTER/ActualizarCondicionSAD.wsdl"/>
   <wsdl:import namespace="http://www.bcie.org/CondicionService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/Condicion/V1/Wsdl/ADAPTER/ConsultarCondicionSAD.wsdl"/>
   <wsdl:import namespace="http://www.bcie.org/MatrizTCCService" location="oramds:/apps/Resources/ComponentesComunes/DominioContrato/MatrizTCC/V1/Wsdl/MatrizTCC.wsdl"/>
   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://www.bcie.org/MapeoErrorMO" schemaLocation="oramds:/apps/Resources/ComponentesComunes/Utilidades/MapeoError/V1/Schema/MapeoErrorMO.xsd"/>
      </xsd:schema>
   </wsdl:types>
</wsdl:definitions>
