<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CondicionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:conMO="http://www.bcie.org/CondicionMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="ConsultarCondicionByIdEventoRequestMessage">
    <part name="request" element="conMO:ConsultarCondicionByIdEventoRequest"/>
  </message>
  <message name="ConsultarCondicionByIdEventoResponseMessage">
    <part name="response" element="conMO:ConsultarCondicionByIdEventoResponse"/>
  </message>
  <portType name="ConsultarCondicionByIdEventoPT">
    <operation name="ConsultarCondicionByIdEvento">
      <input message="tns:ConsultarCondicionByIdEventoRequestMessage"/>
      <output message="tns:ConsultarCondicionByIdEventoResponseMessage"/>
    </operation>
  </portType>
  <binding name="ConsultarCondicionByIdEventoPTSOAP12Bnd" type="tns:ConsultarCondicionByIdEventoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ConsultarCondicionByIdEvento">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CondicionService/ConsultarCondicionByIdEvento"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>