<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearReporteCondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CrearReporteCondicionService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/CondicionMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearObservacionCondicionSAD/types" elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="CrearReporteCondicionRequestMessage">
    <part name="request" element="conMO:CrearReporteCondicionRequest"/>
  </message>
  <message name="CrearReporteCondicionResponseMessage">
    <part name="response" element="conMO:CrearReporteCondicionResponse"/>
  </message>
  <portType name="ReporteCondicionPT">
    <operation name="crearReporteCondicion">
      <input message="tns:CrearReporteCondicionRequestMessage"/>
      <output message="tns:CrearReporteCondicionResponseMessage"/>
    </operation>
  </portType>
  <binding name="ReporteCondicion12Bnd" type="tns:ReporteCondicionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearReporteCondicion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearReporteCondicionService/crearReporteCondicion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>