<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/CondicionService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/CondicionService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/CondicionMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CrearCondicionRequestMessage">
    <wsdl:part name="request" element="conMO:CrearCondicionRequest"/>
  </wsdl:message>
  <wsdl:message name="CrearCondicionResponseMessage">
    <wsdl:part name="response" element="conMO:CrearCondicionResponse"/>
  </wsdl:message>
  <wsdl:portType name="CondicionPT">
    <wsdl:operation name="crearCondicion">
      <wsdl:input message="tns:CrearCondicionRequestMessage"/>
      <wsdl:output message="tns:CrearCondicionResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Condicion12Bnd" type="tns:CondicionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="crearCondicion">
      <soap12:operation style="document" soapAction="http://www.bcie.org/CondicionService/crearCondicion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>