<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/GestionCobroMO" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/GestionCobroMO" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
 <types>
    <xsd:schema targetNamespace="http://www.bcie.org/GestionCobroMO/types" elementFormDefault="qualified">
    <xsd:import namespace="http://www.bcie.org/GestionCobroMO" schemaLocation="../../Schema/GestionCobroMO.xsd"/>
    </xsd:schema>
  </types>
 <message name="ConsultarDetalleAvisoCobroRequestMessage">
  <part name="ConsultarDetalleAvisoCobroRequest" element="tns:ConsultarDetalleAvisoCobroRequest"/>
 </message>
 <message name="ConsultarDetalleAvisoCobroResponseMessage">
  <part name="ConsultarDetalleAvisoCobroResponse" element="tns:ConsultarDetalleAvisoCobroResponse"/>
 </message>
 <portType name="ConsultarDetalleAvisoCobroPT">
  <operation name="consultarDetalleAvisoCobro">
   <input message="tns:ConsultarDetalleAvisoCobroRequestMessage"/>
   <output message="tns:ConsultarDetalleAvisoCobroResponseMessage"/>
  </operation>
 </portType>
 <binding name="ConsultarDetalleAvisoCobroPT12Bnd" type="tns:ConsultarDetalleAvisoCobroPT">
  <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="consultarDetalleAvisoCobro">
   <soap12:operation style="document" soapAction="http://www.bcie.org/GestionCobroMO/consultarDetalleAvisoCobro"/>
   <input>
    <soap12:body use="literal" parts="ConsultarDetalleAvisoCobroRequest"/>
   </input>
   <output>
    <soap12:body use="literal" parts="ConsultarDetalleAvisoCobroResponse"/>
   </output>
  </operation>
 </binding>
</definitions>

