<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns2="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoPmt="http://xmlns.banesco.com/eo/Pmt_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Trn_V1.0"
                xmlns:ns9="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:eoBank="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Bill_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardCr/CardCrCashAdd/CardCrCashAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="CardCrCashAddRq" namespace="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardCr/CardCrCashAdd/CardCrCashAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="CardCrCashAddRs" namespace="http://xmlns.banesco.com/eopt/CardCrCashAdd_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [THU JUL 12 20:37:28 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="varOldBody"/>
   <xsl:template match="/">
      <ns0:CardCrCashAddRs>
      <ns0:FIData>
          <eoBank:FIIdent>
            <xsl:value-of select="$varOldBody/ns0:FIData/eoBank:FIIdent"/>
          </eoBank:FIIdent>
        <eoBank:Agency>
          <xsl:if test="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/AGENCY_IDENT/text()">
            <eoBank:AgencyIdent>
              <xsl:value-of select="$varOldBody/ns0:FIData/eoBank:Agency/eoBank:AgencyIdent"/>
            </eoBank:AgencyIdent>
          </xsl:if>
        </eoBank:Agency>
      </ns0:FIData>
      <ns0:PartyKey>
        <eoPar:PartyId>
          <xsl:value-of select="$varOldBody/ns0:PartyKey/eoPar:PartyId"/>
        </eoPar:PartyId>
      </ns0:PartyKey>
      <ns0:Pmt>
        <eoPmt:PmtTrnDetail>
          <xsl:if test="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/DEBIT_ID/text()">
            <ns4:DebitId>
              <xsl:value-of select="/mfl_EVERTEC0410_TEXT_to_XML/DEBIT_ID"/>
            </ns4:DebitId>
          </xsl:if>
          <ns4:TotalCurAmt>
              <ns8:Amt>
                <xsl:value-of select="$varOldBody/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:TotalCurAmt/ns8:Amt"/>
              </ns8:Amt>
              <ns8:CurCode>
                <xsl:value-of select="$varOldBody/ns0:Pmt/eoPmt:PmtTrnDetail/ns4:TotalCurAmt/ns8:CurCode"/>
              </ns8:CurCode>
          </ns4:TotalCurAmt>
          <ns4:TrnKey>
            <xsl:if test="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/TRN_ID/text()">
              <ns4:TrnId>
                <xsl:value-of select="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/TRN_ID"/>
              </ns4:TrnId>
            </xsl:if>
          </ns4:TrnKey>
          <ns4:CardKey>
            <xsl:if test="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/CARD_NUM/text()">
              <ns5:CardNum>
                <xsl:value-of select="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/CARD_NUM"/>
              </ns5:CardNum>
            </xsl:if>
          </ns4:CardKey>
        </eoPmt:PmtTrnDetail>
      </ns0:Pmt>
      <ns0:Status>
        <eoStatus:StatusCode>
                    <xsl:value-of select="DVMFunctions:lookupValue ('Commons/dvm/StatusMappingBcknd', 'EVERTEC', /mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/STATUS_CODE, 'CNCODE', 'M0006' )"/>
                </eoStatus:StatusCode>
                <eoStatus:StatusDesc>
                    <xsl:value-of select="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/STATUS_DESC"/>
                </eoStatus:StatusDesc>
                <eoStatus:AdditionalStatus>
                    <eoStatus:StatusCode>
                        <xsl:value-of select="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/STATUS_CODE"/>
                    </eoStatus:StatusCode>
                    <eoStatus:StatusDesc>
                        <xsl:value-of select="/mfl_EVERTEC0410_TEXT_to_XML/CardCrCashAddRs/STATUS_DESC"/>
                    </eoStatus:StatusDesc>
                </eoStatus:AdditionalStatus>
      </ns0:Status>
    </ns0:CardCrCashAddRs>
   </xsl:template>
</xsl:stylesheet>
