<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="dbFnxInformeResultados" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdquisicionesWSFenix/AdquisicionWeb/dbFnxInformeResultados" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdquisicionesWSFenix/AdquisicionWeb/dbFnxInformeResultados" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxInformeResultados" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="dbFnxInformeResultados_plt">
      <plt:role name="dbFnxInformeResultados_role">
         <plt:portType name="tns:dbFnxInformeResultados_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <plt:partnerLinkType name="dbFnxInformeResultados_plt">
      <plt:role name="dbFnxInformeResultados_role">
         <plt:portType name="tns:dbFnxInformeResultados_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxInformeResultados" schemaLocation="../Schemas/dbFnxInformeResultados.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbFnxInformeResultados" schemaLocation="../Schemas/dbFnxInformeResultados.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="dbFnxInformeResultadosInput_msg">
      <wsdl:part name="dbFnxInformeResultadosInput_msg" element="db:dbFnxInformeResultadosInput"/>
   </wsdl:message>
   <wsdl:message name="dbFnxInformeResultadosOutputCollection_msg">
      <wsdl:part name="dbFnxInformeResultadosOutputCollection" element="db:dbFnxInformeResultadosOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="dbFnxInformeResultados_ptt">
      <wsdl:operation name="dbFnxInformeResultados">
         <wsdl:input message="tns:dbFnxInformeResultadosInput_msg"/>
         <wsdl:output message="tns:dbFnxInformeResultadosOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
