<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PublicarAdjudicadosBpel" targetNamespace="http://xmlns.oracle.com/AdquisicionesWSFenix/AdquisicionWeb/PublicarAdjudicadosBpel" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/AdquisicionesWSFenix/AdquisicionWeb/PublicarAdjudicadosBpel" xmlns:ns1="http://www.bcie.org/AdquisicionMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://www.bcie.org">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/AdquisicionesWSFenix/AdquisicionWeb/PublicarAdjudicadosBpel" xmlns:ns1="http://www.bcie.org/AdquisicionMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://www.bcie.org">
         <import namespace="http://www.bcie.org/AdquisicionMO" schemaLocation="../Schemas/AdquisicionMO.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/AdquisicionesWSFenix/AdquisicionWeb/PublicarAdjudicadosBpel" xmlns:ns1="http://www.bcie.org/AdquisicionMO" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://www.bcie.org">
         <xsd:import namespace="http://www.bcie.org" schemaLocation="../Schemas/AdjudicadoBCIE.xsd"/>
      </xsd:schema>
   </wsdl:types>
</wsdl:definitions>
