<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="urn:bcieBinding" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="urn:bcieBinding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="wsAdquisiciones">
      <plnk:role name="bciePortType" portType="tns:bciePortType"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="urn:bcieBinding" location="http://ws.bcie.org/servicio.php?wsdl"/>
</wsdl:definitions>
