<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/GenerarReporteCondicionValidadorService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/GenerarReporteCondicionValidadorService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/CondicionMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearObservacionCondicionSAD/types" elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/CondicionMO" schemaLocation="../../Schema/CondicionMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="GenerarReporteCondicionValidadorRequest">
    <part name="GenerarReporteCondicionValidadorRq" element="conMO:GenerarReporteCondicionValidadorRequest"/>
  </message>
  <message name="GenerarReporteCondicionValidadorResponse">
    <part name="GenerarReporteCondicionValidadorRs" element="conMO:GenerarReporteCondicionValidadorResponse"/>
  </message>
  <portType name="GenerarReporteCondicionValidadorPT">
    <operation name="GenerarReporteCondicionValidador">
      <input message="tns:GenerarReporteCondicionValidadorRequest"/>
      <output message="tns:GenerarReporteCondicionValidadorResponse"/>
    </operation>
  </portType>
  <binding name="GenerarReporteCondicionValidador12Bnd" type="tns:GenerarReporteCondicionValidadorPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GenerarReporteCondicionValidador">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearReporteCondicionService/GenerarReporteCondicionValidador"/>
      <input>
        <soap12:body use="literal" parts="GenerarReporteCondicionValidadorRq"/>
      </input>
      <output>
        <soap12:body use="literal" parts="GenerarReporteCondicionValidadorRs"/>
      </output>
    </operation>
  </binding>
</definitions>