<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ObtenerDisponibilidadRecursos_DecisionService_1"
     targetNamespace="http://xmlns.oracle.com/ObtenerDisponibilidadRecursos/ObtenerDisponibilidadRecursos_DecisionService_1"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/ObtenerDisponibilidadRecursos/ObtenerDisponibilidadRecursos_DecisionService_1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ObtenerDisponibilidadRecursos_SB">
        <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/ObtenerDisponibilidadRecursos/ObtenerDisponibilidadRecursos_DecisionService_1"
         location="oramds:/apps/Resources/ComponentesComunes/BusinessRules/ObtenerDisponibilidadRecursos/V1/Wsdl/ObtenerDisponibilidadRecursos_DecisionService.wsdl"/>
</wsdl:definitions>
