<wsdl:definitions name="DBSeasonRMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SeasonAPP/SeasonService/DBSeasonRMS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SeasonAPP/SeasonService/DBSeasonRMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBSeasonRMS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="DBSeasonRMS_plt">
    <plt:role name="DBSeasonRMS_role">
      <plt:portType name="tns:DBSeasonRMS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBSeasonRMS" schemaLocation="DBSeasonRMS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="DBSeasonRMSSelect_inputParameters">
        <wsdl:part name="DBSeasonRMSSelect_inputParameters" element="top:DBSeasonRMSSelect_dateInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaSeasonsVwCollection_msg">
        <wsdl:part name="XxSoaSeasonsVwCollection" element="top:XxSoaSeasonsVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBSeasonRMS_ptt">
        <wsdl:operation name="DBSeasonRMSSelect">
            <wsdl:input message="tns:DBSeasonRMSSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaSeasonsVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>