<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearBitacoraReglasDesembolso"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/CrearBitacoraReglasDesembolso"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:regDesMO="http://www.bcie.org/CrearBitacoraReglasDesembolsoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearBitacoraReglasDesembolso/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/CrearBitacoraReglasDesembolsoMO" schemaLocation="../Schema/CrearBitacoraReglasDesembolsoMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestCrearBitacoraReglasDesembolsoMessage">
    <part name="request" element="regDesMO:CrearBitacoraReglasDesembolsoRequest"/>
  </message>
  <message name="responseCrearBitacoraReglasDesembolsoMessage">
    <part name="response" element="regDesMO:CrearBitacoraReglasDesembolsoResponse"/>
  </message>
  <portType name="CrearBitacoraReglasDesembolso_PT">
    <operation name="crearBitacoraReglasDesembolso">
      <input message="tns:requestCrearBitacoraReglasDesembolsoMessage"/>
      <output message="tns:responseCrearBitacoraReglasDesembolsoMessage"/>
    </operation>
  </portType>
  <binding name="CrearBitacoraReglasDesembolso_PTSOAP12Binding" type="tns:CrearBitacoraReglasDesembolso_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="crearBitacoraReglasDesembolso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearBitacoraReglasDesembolso/crearBitacoraReglasDesembolso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>