<wsdl:definitions name="ConsultarComentariosByIdSolicitudAproDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarComentariosByIdSolicitudAproDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarComentariosByIdSolicitudAproDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComentariosDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarComentariosByIdSolicitudAproDB_plt">
    <plt:role name="ConsultarComentariosByIdSolicitudAproDB_role">
      <plt:portType name="tns:ConsultarComentariosByIdSolicitudAproDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarComentariosDB" schemaLocation="../XSD/ConsultarComentariosByIdSolicitudAproDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarComentariosDBInput_msg">
        <wsdl:part name="ConsultarComentariosDBInput_msg" element="db:ConsultarComentariosDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarComentariosDBOutputCollection_msg">
        <wsdl:part name="ConsultarComentariosDBOutputCollection" element="db:ConsultarComentariosDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarComentariosByIdSolicitudAproDB_ptt">
        <wsdl:operation name="ConsultarComentariosByIdSolicitudAproDB">
            <wsdl:input message="tns:ConsultarComentariosDBInput_msg"/>
            <wsdl:output message="tns:ConsultarComentariosDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>