<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO" xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="ConfiguracionProcesos" targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService">
<wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO" schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="requestConfiguracionPreparacionMessage">
<wsdl:part name="request" element="confMO:configuracionPreparacionRequest"/>
</wsdl:message>
<wsdl:message name="responseConfiguracionPreparacionMessage">
<wsdl:part name="response" element="confMO:configuracionPreparacionResponse"/>
</wsdl:message>
<wsdl:portType name="ConfiguracionPreparacionPT">
<wsdl:operation name="configuracionPreparacion">
<wsdl:input message="tns:requestConfiguracionPreparacionMessage"/>
<wsdl:output message="tns:responseConfiguracionPreparacionMessage"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="ConfiguracionPreparacion12Bnd" type="tns:ConfiguracionPreparacionPT">
<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="configuracionPreparacion">
<soap12:operation soapAction="http://xmlns.bcie.com/DocumentoService/configuracionPreparacion" style="document"/>
<wsdl:input>
<soap12:body parts="request" use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body parts="response" use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
</wsdl:definitions>
