<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CrearAvisoCobroV2SAD"
     targetNamespace="http://www.bcie.org/GestionCobroMO"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/GestionCobroMO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CrearAvisoCobroV2">
        <plnk:role name="CrearAvisoCobroV2PT" portType="tns:CrearAvisoCobroV2PT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/GestionCobroMO" location="oramds:/apps/Resources/ComponentesComunes/DominioCliente/GestionCobro/V1/Wsdl/ADAPTER/CrearAvisoCobroV2SAD.wsdl"/>
</wsdl:definitions>
