<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/Comisiones/Payload/V1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://www.bcie.org/CrearBitacoraMO"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:ns1="http://www.bcie.org/CatalogoBO"
                xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns3="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns5="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:ns4="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1"
                xmlns:resBO="http://www.bcie.org/ResultBO" xmlns:regBitBO="http://www.bcie.org/CrearBitacoraBO"
                xmlns:ns6="http://www.bcie.org/ErrorBO">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA02/ComisionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ComisionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Comisiones/Payload/V1"/>
        <oracle-xsl-mapper:param name="comisionDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/ComponentesComunes/Utilidades/CrearBitacora/V1/Schema/CrearBitacoraMO.xsd"/>
        <oracle-xsl-mapper:rootElement name="CrearBitacoraRequest" namespace="http://www.bcie.org/CrearBitacoraMO"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [THU MAY 18 18:25:07 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CrearBitacoraRequest>
      <tns:BitacoraInput>
        <regBitBO:idNegocio>
          <ns1:Id>
            <xsl:value-of select="/ns0:ComisionPayload/ns0:Header/header:Operacion/ns2:CodigoOperacion"/>
          </ns1:Id>
          <ns1:Descripcion>
            <xsl:value-of select="/ns0:ComisionPayload/ns0:Header/header:Operacion/ns2:NombreOperacion"/>
          </ns1:Descripcion>
          <ns1:codigoExterno>OPERACION</ns1:codigoExterno>
        </regBitBO:idNegocio>
        <regBitBO:idProceso>
          <xsl:value-of select="/ns0:ComisionPayload/ns0:Header/header:Proceso/ns3:IdProceso"/>
        </regBitBO:idProceso>
        <regBitBO:nombreProceso>PA02</regBitBO:nombreProceso>
        <regBitBO:instanciaProceso>
          <xsl:value-of select="/ns0:ComisionPayload/ns0:Header/header:Proceso/ns3:InstanciaProceso"/>
        </regBitBO:instanciaProceso>
        <regBitBO:esProceso>true</regBitBO:esProceso>
        <regBitBO:usuario>
          <xsl:value-of select="/ns0:ComisionPayload/ns0:Header/header:Operacion/ns2:ResponsableOperacion"/>
        </regBitBO:usuario>
        <regBitBO:esFinActividad>false</regBitBO:esFinActividad>
        <regBitBO:fechaRegistro>
          <xsl:value-of select="xp20:current-dateTime ( )"/>
        </regBitBO:fechaRegistro>
        <regBitBO:finalizado>false</regBitBO:finalizado>
      </tns:BitacoraInput>
    </tns:CrearBitacoraRequest>
  </xsl:template>
</xsl:stylesheet>
