<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/CrearActualizarClienteProceso"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.bcie.org/CrearActualizarClienteProceso"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:cliProMO="http://www.bcie.org/CrearActualizarClienteProcesoMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/CrearActualizarClienteProceso/types"
                elementFormDefault="qualified">
                <xsd:import namespace="http://www.bcie.org/CrearActualizarClienteProcesoMO" schemaLocation="../Schema/CrearActualizarClienteProcesoMO.xsd"/>
                </xsd:schema>
  </types>
  <message name="requestCreaActualizarClienteProcesoMessage">
    <part name="request" element="cliProMO:CrearActualizarClienteProcesoRequest"/>
  </message>
  <message name="responseCreaActualizarClienteProcesoMessage">
    <part name="response" element="cliProMO:CrearActualizarClienteProcesoResponse"/>
  </message>
  <portType name="CrearActualizarClienteProceso_PT">
    <operation name="CrearActualizarClienteProceso">
      <input message="tns:requestCreaActualizarClienteProcesoMessage"/>
      <output message="tns:responseCreaActualizarClienteProcesoMessage"/>
    </operation>
  </portType>
  <binding name="CrearActualizarClienteProceso_PTSOAP12Binding" type="tns:CrearActualizarClienteProceso_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CrearActualizarClienteProceso">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/CrearActualizarClienteProceso/CreaActualizarClienteProceso"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>