<wsdl:definitions name="QuerySupplierRMSReference" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/SupplierApp/QuerySupplierRMSReference" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/SupplierApp/QuerySupplierRMSReference" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QuerySupplierRMSReference" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="QuerySupplierRMSReference_plt">
    <plt:role name="QuerySupplierRMSReference_role">
      <plt:portType name="tns:QuerySupplierRMSReference_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QuerySupplierRMSReference" schemaLocation="../XSD/QuerySupplierRMSReference_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="QuerySupplierRMSReferenceSelect_inputParameters">
        <wsdl:part name="QuerySupplierRMSReferenceSelect_inputParameters" element="top:QuerySupplierRMSReferenceSelect_supNoInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaVendorVwCollection_msg">
        <wsdl:part name="XxSoaVendorVwCollection" element="top:XxSoaVendorVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="QuerySupplierRMSReference_ptt">
        <wsdl:operation name="QuerySupplierRMSReferenceSelect">
            <wsdl:input message="tns:QuerySupplierRMSReferenceSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaVendorVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>