<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/SupplierApp/QuerySupplierRMSReference" name="QuerySupplierRMSReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="QuerySupplierRMSReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/SupplierApp/QuerySupplierRMSReference"/>
    <wsdl:binding name="QuerySupplierRMSReference_ptt-binding" type="quer:QuerySupplierRMSReference_ptt" xmlns:quer="http://xmlns.oracle.com/pcbpel/adapter/db/OSBAGApp/SupplierApp/QuerySupplierRMSReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="QuerySupplierRMSReferenceSelect">
            <soap:operation soapAction="QuerySupplierRMSReferenceSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>