<wsdl:definitions name="ConsultarPlazoGraciaByLineaFinanciera_DB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarPlazoGraciaByLineaFinanciera_DB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarPlazoGraciaByLineaFinanciera_DB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarPlazoGraciaByLineaFinanciera_DB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarPlazoGraciaByLineaFinanciera_DB_plt">
    <plt:role name="ConsultarPlazoGraciaByLineaFinanciera_DB_role">
      <plt:portType name="tns:ConsultarPlazoGraciaByLineaFinanciera_DB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarPlazoGraciaByLineaFinanciera_DB" schemaLocation="../XSD/ConsultarPlazoGraciaByLineaFinanciera_DB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarPlazoGraciaByLineaFinanciera_DBInput_msg">
        <wsdl:part name="ConsultarPlazoGraciaByLineaFinanciera_DBInput_msg" element="db:ConsultarPlazoGraciaByLineaFinanciera_DBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarPlazoGraciaByLineaFinanciera_DBOutputCollection_msg">
        <wsdl:part name="ConsultarPlazoGraciaByLineaFinanciera_DBOutputCollection" element="db:ConsultarPlazoGraciaByLineaFinanciera_DBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarPlazoGraciaByLineaFinanciera_DB_ptt">
        <wsdl:operation name="ConsultarPlazoGraciaByLineaFinanciera_DB">
            <wsdl:input message="tns:ConsultarPlazoGraciaByLineaFinanciera_DBInput_msg"/>
            <wsdl:output message="tns:ConsultarPlazoGraciaByLineaFinanciera_DBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>