<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultarLineaCreditoFormalizacionSOR" targetNamespace="http://www.bcie.org/ConsultarLineaCreditoFormalizacionSOR" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.bcie.org/ConsultarLineaCreditoFormalizacionSOR" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ConsultarLineaCreditoFormalizacion">
      <plnk:role name="ConsultarLineaCreditoFormalizacion_PT" portType="tns:ConsultarLineaCreditoFormalizacion_PT"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://www.bcie.org/ConsultarLineaCreditoFormalizacionSOR" location="oramds:/apps/Resources/ComponentesComunes/DominioLineaCredito/LineaCredito/V1/Wsdl/BPEL/ConsultarLineaCreditoFormalizacionSOR.wsdl"/>
</wsdl:definitions>
