<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/ActualizarContratoService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ActualizarContratoService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:conMO="http://www.bcie.org/ContratoMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ContratoMO"
                  schemaLocation="../../Schema/ContratoMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ActualizarContratoRequestMessage">
    <wsdl:part name="request" element="conMO:ActualizarContratoRequest"/>
  </wsdl:message>
  <wsdl:message name="ActualizarContratoResponseMessage">
    <wsdl:part name="response" element="conMO:ActualizarContratoResponse"/>
  </wsdl:message>
  <wsdl:portType name="ActualizarContratoPT">
    <wsdl:operation name="actualizarContrato">
      <wsdl:input message="tns:ActualizarContratoRequestMessage"/>
      <wsdl:output message="tns:ActualizarContratoResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ActualizarContrato12Bnd" type="tns:ActualizarContratoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizarContrato">
      <soap12:operation style="document" soapAction="http://www.bcie.org/ActualizarContratoService/actualizarContrato"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>