<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.bcie.org/ConfiguracionDesembolsoExcepcionSOR"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/ConfiguracionDesembolsoExcepcionSOR"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO">
  <types>
    <xsd:schema targetNamespace="http://www.bcie.org/ConfiguracionDesembolsoExcepcionSOR/types"
                elementFormDefault="qualified">
      <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO" schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="requestConfiguracionDesembolsoExcepcionMessage">
    <part name="request" element="confMO:ConfiguracionDesembolsoExcepcionRequest"/>
  </message>
  <message name="responseConfiguracionDesembolsoExcepcionMessage">
    <part name="response" element="confMO:ConfiguracionDesembolsoExcepcionResponse"/>
  </message>
  <portType name="ConfiguracionDesembolsoExcepcion_PT">
    <operation name="configuracionDesembolsoExcepcion">
      <input message="tns:requestConfiguracionDesembolsoExcepcionMessage"/>
      <output message="tns:responseConfiguracionDesembolsoExcepcionMessage"/>
    </operation>
  </portType>
  <binding name="ConfiguracionDesembolsoExcepcion_PTSOAP12Binding" type="tns:ConfiguracionDesembolsoExcepcion_PT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="configuracionDesembolsoExcepcion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/ConfiguracionDesembolsoExcepcionSOR/ConfiguracionDesembolsoExcepcion"/>
      <input>
        <soap12:body use="literal" parts="request"/>
      </input>
      <output>
        <soap12:body use="literal" parts="response"/>
      </output>
    </operation>
  </binding>
</definitions>