<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://xmlns.bcie.com/ConfiguracionProcesosService" 
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://xmlns.bcie.com/ConfiguracionProcesosService" 
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:confMO="http://www.bcie.org/ConfiguracionProcesosMO"
             name="ConfiguracionProcesos"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/ConfiguracionProcesosMO"
                  schemaLocation="../../Schema/ConfiguracionProcesosMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <message name="requestConfiguracionDesembolsoMessage">
    <part name="requestConfiguracionDesembolso" element="confMO:configuracionDesembolsoRequest"/>
  </message>
  <message name="responseConfiguracionDesembolsoMessage">
    <part name="responseConfiguracionDesembolso" element="confMO:configuracionDesembolsoResponse"/>
  </message>
  <portType name="ConfiguracionDesembolsoPT">
    <operation name="configuracionDesembolso">
      <input message="tns:requestConfiguracionDesembolsoMessage"/>
      <output message="tns:responseConfiguracionDesembolsoMessage"/>
    </operation>
  </portType>
  <binding name="ConfiguracionDesembolsoPT12Bnd" type="tns:ConfiguracionDesembolsoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="configuracionDesembolso">
      <soap12:operation style="document"
                        soapAction="http://xmlns.bcie.com/ConfiguracionProcesosService/configuracionDesembolso"/>
      <input>
        <soap12:body use="literal" parts="requestConfiguracionDesembolso"/>
      </input>
      <output>
        <soap12:body use="literal" parts="responseConfiguracionDesembolso"/>
      </output>
    </operation>
  </binding>
</definitions>