<wsdl:definitions name="ValidarInicioAutomaticoFormalizacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarInicioAutomaticoFormalizacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ValidarInicioAutomaticoFormalizacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarInicioAutomaticoFormalizacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ValidarInicioAutomaticoFormalizacion_plt">
    <plt:role name="ValidarInicioAutomaticoFormalizacion_role">
      <plt:portType name="tns:ValidarInicioAutomaticoFormalizacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidarInicioAutomaticoFormalizacion" schemaLocation="../XSD/ValidarInicioAutomaticoFormalizacion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ValidarInicioAutomaticoFormalizacionInput_msg">
        <wsdl:part name="ValidarInicioAutomaticoFormalizacionInput_msg" element="db:ValidarInicioAutomaticoFormalizacionInput"/>
    </wsdl:message>
    <wsdl:message name="ValidarInicioAutomaticoFormalizacionOutputCollection_msg">
        <wsdl:part name="ValidarInicioAutomaticoFormalizacionOutputCollection" element="db:ValidarInicioAutomaticoFormalizacionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ValidarInicioAutomaticoFormalizacion_ptt">
        <wsdl:operation name="ValidarInicioAutomaticoFormalizacion">
            <wsdl:input message="tns:ValidarInicioAutomaticoFormalizacionInput_msg"/>
            <wsdl:output message="tns:ValidarInicioAutomaticoFormalizacionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>