<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.bcie.org/ObjetoProceso/Error/Payload/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.bcie.org/ObjetoProceso/CancelarError/Payload/V1"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:analisis="http://xmlns.bcie.org/ObjetoProceso/Analisis/Payload/V1"
                xmlns:parameter="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:clientes="http://xmlns.bcie.org/ObjetoProceso/Admincliente/Payload/V1"
                xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:elegibilidad="http://xmlns.bcie.org/ObjetoProceso/Elegibilidad/Payload/V1"
                xmlns:preparacion="http://xmlns.bcie.org/ObjetoProceso/Preparacion/Payload/V1"
                xmlns:laft="http://xmlns.bcie.org/ObjetoProceso/LAFT/Payload/V1"
                xmlns:evaluacion="http://xmlns.bcie.org/ObjetoProceso/Evaluacion/Payload/V1"
                xmlns:aprobacion="http://xmlns.bcie.org/ObjetoProceso/Aprobacion/Payload/V1"
                xmlns:header="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:formalizacion="http://xmlns.bcie.org/ObjetoProceso/Formalizacion/Payload/V1"
                xmlns:condiciones="http://xmlns.bcie.org/ObjetoProceso/Condiciones/Payload/V1"
                xmlns:comisiones="http://xmlns.bcie.org/ObjetoProceso/Comisiones/Payload/V1"
                xmlns:ns3="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:enmienda="http://xmlns.bcie.org/ObjetoProceso/Enmiendas/Payload/V1"
                xmlns:cancelar="http://xmlns.bcie.org/ObjetoProceso/Cancelar/Payload/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/Error/VI/ErrorPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ErrorPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Error/Payload/V1"/>
        <oracle-xsl-mapper:param name="errorDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA05/CancelarErrorPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="CancelarErrorPayloadType"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/CancelarError/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [TUE JAN 19 00:41:23 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CancelarErrorPayloadType>
      <tns:Header>
        <header:Operacion>
          <ns2:CodigoOperacion>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:CodigoOperacion"/>
          </ns2:CodigoOperacion>
          <ns2:NombreOperacion>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:NombreOperacion"/>
          </ns2:NombreOperacion>
          <ns2:ResponsableOperacion>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:ResponsableOperacion"/>
          </ns2:ResponsableOperacion>
          <ns2:CodigoCliente>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:CodigoCliente"/>
          </ns2:CodigoCliente>
          <ns2:NombreCliente>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:NombreCliente"/>
          </ns2:NombreCliente>
          <ns2:CodigoProducto>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:CodigoProducto"/>
          </ns2:CodigoProducto>
          <ns2:NombreProducto>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:NombreProducto"/>
          </ns2:NombreProducto>
          <ns2:MontoSolicitado>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:MontoSolicitado"/>
          </ns2:MontoSolicitado>
          <ns2:Pais>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Operacion/ns2:Pais"/>
          </ns2:Pais>
        </header:Operacion>
        <header:Tarea>
          <ns3:CodigoTarea>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Tarea/ns3:CodigoTarea"/>
          </ns3:CodigoTarea>
          <ns3:NombreTarea>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Tarea/ns3:NombreTarea"/>
          </ns3:NombreTarea>
          <ns3:CodigoRol>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Tarea/ns3:CodigoRol"/>
          </ns3:CodigoRol>
          <ns3:NombreRol>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Tarea/ns3:NombreRol"/>
          </ns3:NombreRol>
          <ns3:CodigoProceso>11</ns3:CodigoProceso>
          <ns3:NombreProceso>
            <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/header:Tarea/ns3:NombreProceso"/>
          </ns3:NombreProceso>
        </header:Tarea>
        <xsl:for-each select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Header/parameter:ParameterType">
          <parameter:ParameterType>
            <parameter:parameterName>
              <xsl:value-of select="parameter:parameterName"/>
            </parameter:parameterName>
            <parameter:parameterValue>
              <xsl:value-of select="parameter:parameterValue"/>
            </parameter:parameterValue>
          </parameter:ParameterType>
        </xsl:for-each>
      </tns:Header>
      <tns:Configuration>
        <tns:solicitaGerente>
          <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:Configuration/cancelar:solicitaGerente"/>
        </tns:solicitaGerente>
      </tns:Configuration>
      <tns:solicitaCancelar>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:solicitaCancelar"/>
      </tns:solicitaCancelar>
      <tns:razon>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:razon"/>
      </tns:razon>
      <tns:observacion>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:observacion"/>
      </tns:observacion>
      <tns:EquipoPayload>
        <tns:GerentePais>
          <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:EquipoPayload/cancelar:GerentePais"/>
        </tns:GerentePais>
      </tns:EquipoPayload>
      <xsl:for-each select="/ns0:ErrorPayload/ns0:CancelarPayload/parameter:ParameterType">
        <parameter:ParameterType>
          <parameter:parameterName>
            <xsl:value-of select="parameter:parameterName"/>
          </parameter:parameterName>
          <parameter:parameterValue>
            <xsl:value-of select="parameter:parameterValue"/>
          </parameter:parameterValue>
        </parameter:ParameterType>
      </xsl:for-each>
      <tns:EquipoEjecucionPayload>
        <tns:GerentePais>
          <xsl:value-of select="/ns0:ErrorPayload/ns0:CancelarPayload/cancelar:EquipoEjecucionPayload/cancelar:GerentePais"/>
        </tns:GerentePais>
      </tns:EquipoEjecucionPayload>
      <tns:ErrorMsg>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:ErrorMsg"/>
      </tns:ErrorMsg>
      <tns:ErrorNamespace>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:ErrorNamespace"/>
      </tns:ErrorNamespace>
      <tns:ErrorFault>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:ErrorFault"/>
      </tns:ErrorFault>
      <tns:Accion>
        <xsl:value-of select="/ns0:ErrorPayload/ns0:Accion"/>
      </tns:Accion>
    </tns:CancelarErrorPayloadType>
  </xsl:template>
</xsl:stylesheet>
