<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="UpdateItemProcess" targetNamespace="http://xmlns.oracle.com/UpdateItemApp/UpdateItemProcess/UpdateItemProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/UpdateItemApp/UpdateItemProcess/UpdateItemProcess" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Core/Items/UpdateItemEntity" xmlns:AGSH="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Core/Items/UpdateItemEntity" schemaLocation="../Schemas/UpdateItemSchema.xsd"/>
         <import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" schemaLocation="../Schemas/Commons/AGStandardHeaderSchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="UpdateItemProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:updateItemRequest"/>
   </wsdl:message>
   <wsdl:message name="UpdateItemProcessResponseMessage">
      <wsdl:part name="payload" element="ns1:updateItemResponse"/>
   </wsdl:message>
   <wsdl:portType name="UpdateItemProcess">
      <wsdl:operation name="update">
         <wsdl:input message="client:UpdateItemProcessRequestMessage"/>
         <wsdl:output message="client:UpdateItemProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="UpdateItemProcess">
      <plnk:role name="UpdateItemProcessProvider" portType="client:UpdateItemProcess"/>
   </plnk:partnerLinkType>
   <wsdl:binding name="UpdateItemProcessBinding" type="client:UpdateItemProcess">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="update">
         <soap:operation style="document" soapAction="http://xmlns.oracle.com/UpdateItemApp/UpdateItemProcess/UpdateItemProcess/update"/>
         <wsdl:input>
            <soap:body use="literal" parts="payload"/>
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" parts="payload"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:message name="StandardHeaderMessage">
      <wsdl:part name="headerMessage" element="AGSH:headerMessage"/>
   </wsdl:message>
</wsdl:definitions>
