<wsdl:definitions targetNamespace="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/DistributeCostChangeRequestProcess/v1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cost="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/DistributeCostChangeRequestProcess/v1.0" xmlns:ns1="http://mx.agarcia.ea/Capabilities/Foundation/Party/CostChangeTask" xmlns:AGSM="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" xmlns:AGSH="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://mx.agarcia.ea/Capabilities/Foundation/Party/CostChangeTask" schemaLocation="../../../Schema/CostChangeTaskSvcSchema.xsd"/>
         <import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardMessage" schemaLocation="../../../../../../Capabilities/Foundation/Schemas/Commons/AGStandardMessageSchema.xsd"/>
         <import namespace="http://mx.agarcia.ea/Commons/Schemas/AGStandardHeader" schemaLocation="../../../../../../Capabilities/Foundation/Schemas/Commons/AGStandardHeaderSchema.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="distributeApprovedCostChangeRequest">
      <wsdl:part name="distributeApprovedCostChangeRequest" element="ns1:distributeApprovedCostChangeRequest"/>
   </wsdl:message>
   <wsdl:message name="standardMessageFault">
      <wsdl:part name="fault" element="AGSM:messageError"/>
   </wsdl:message>
   <wsdl:message name="standardMessageHeader">
      <wsdl:part name="header" element="AGSH:headerMessage"/>
   </wsdl:message>
   
   <wsdl:portType name="DistributeCostChangeRequestProcessPType">
      <wsdl:operation name="distributeCostChange">
         <wsdl:input message="cost:distributeApprovedCostChangeRequest"/>
      </wsdl:operation>
      </wsdl:portType>
   <wsdl:binding name="DistributeCostChangeRequestProcessBinding" type="cost:DistributeCostChangeRequestProcessPType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="distributeCostChange">
         <soap:operation style="document" soapAction="http://mx.agarcia.ea/RetailOperations/Buy/CostChange/DistributeCostChangeRequestProcess/v1.0/distributeCostChange"/>
         <wsdl:input>
            <soap:body use="literal" parts="distributeApprovedCostChangeRequest"/>
            <soap:header message="cost:standardMessageHeader" part="header" use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
</wsdl:definitions>