<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/MatrizTCCService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.bcie.org/MatrizTCCService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:mtccMO="http://www.bcie.org/MatrizTCCMO"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/MatrizTCCMO" schemaLocation="../../Schema/MatrizTCCMO.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="RegistrarEnmiendaRequestMessage">
    <wsdl:part name="request" element="mtccMO:RegistrarEnmiendaRequest"/>
  </wsdl:message>
  <wsdl:message name="RegistrarEnmiendaResponseMessage">
    <wsdl:part name="response" element="mtccMO:RegistrarEnmiendaResponse"/>
  </wsdl:message>
  <wsdl:portType name="RegistrarEnmiendaPT">
    <wsdl:operation name="registrarEnmienda">
      <wsdl:input message="tns:RegistrarEnmiendaRequestMessage"/>
      <wsdl:output message="tns:RegistrarEnmiendaResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RegistrarEnmienda12Bnd" type="tns:RegistrarEnmiendaPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="registrarEnmienda">
      <soap12:operation style="document" soapAction="http://www.bcie.org/MatrizTCCService/registrarEnmienda"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>