<wsdl:definitions name="CreateTransferRequestReference" targetNamespace="http://xmlns.oracle.com/OSBAGApp/TransferRequestApp/CreateTransferRequestReference" xmlns:tns="http://xmlns.oracle.com/OSBAGApp/TransferRequestApp/CreateTransferRequestReference" xmlns:inp1="http://TargetNamespace.com/CreateTransferRequestReference_Create_request" xmlns:inp2="http://TargetNamespace.com/CreateTransferRequestReference_Create_response" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="CreateTransferRequestReference">
        <plnk:role name="CreateTransferRequestReferenceProvider" portType="tns:CreateTransferRequestReference_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/CreateTransferRequestReference_Create_request" schemaLocation="../XSD/inputSchema.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://TargetNamespace.com/CreateTransferRequestReference_Create_response" schemaLocation="../XSD/outputSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Create_inputMessage">
        <wsdl:part name="request" element="inp1:CreateTransferRequest"/>
    </wsdl:message>
    <wsdl:message name="Create_outputMessage">
        <wsdl:part name="reply" element="inp2:CreateTransferResponse"/>
    </wsdl:message>
    <wsdl:portType name="CreateTransferRequestReference_ptt">
        <wsdl:operation name="Create">
            <wsdl:input message="tns:Create_inputMessage"/>
            <wsdl:output message="tns:Create_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CreateTransferRequestReference_ptt-binding" type="tns:CreateTransferRequestReference_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Create">
            <soap:operation soapAction="Create"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>