<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/GovernanceAPIApp/GovernanceAPI/GovernanceAPIJMSSubsBS" name="GovernanceAPIJMSSubsBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GovernanceAPIJMSSubsBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/jms/GovernanceAPIApp/GovernanceAPI/GovernanceAPIJMSSubsBS"/>
    <wsdl:binding name="ConsumeMessage_ptt-binding" type="gov:ConsumeMessage_ptt" xmlns:gov="http://xmlns.oracle.com/pcbpel/adapter/jms/GovernanceAPIApp/GovernanceAPI/GovernanceAPIJMSSubsBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsumeMessage">
            <soap:operation soapAction="ConsumeMessage"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>