<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project15/ValidarCondiciones" name="ValidarCondiciones_db_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ValidarCondiciones.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project15/ValidarCondiciones"/>
    <wsdl:binding name="ValidarCondiciones_ptt-binding" type="val:ValidarCondiciones_ptt" xmlns:val="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project15/ValidarCondiciones">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ValidarCondiciones">
            <soap:operation soapAction="ValidarCondiciones"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>