<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/COMPOSICIONES/EliminarTreLineaCredito" name="EliminarTreLineaCreditoAprobacionByIdLineaCreditoIdAprobacion_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EliminarTreLineaCreditoAprobacionByIdLinea.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/COMPOSICIONES/EliminarTreLineaCredito"/>
    <wsdl:binding name="EliminarTreLineaCredito_ptt-binding" type="elim:EliminarTreLineaCredito_ptt" xmlns:elim="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/COMPOSICIONES/EliminarTreLineaCredito">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EliminarTreLineaCredito">
            <soap:operation soapAction="EliminarTreLineaCredito"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>