<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://xmlns.banesco.com/eopt/CardDbHTAdd_V1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.banesco.com/eopt/CardDbAdd_V1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:ns2="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:eoPar="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoCardAcctRel="http://xmlns.banesco.com/eo/CardAcctRel_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:eoBank="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns1="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:eoCard="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns4="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns5="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardDb/CardDbAdd/CardDbAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="CardDbAddRq" namespace="http://xmlns.banesco.com/eopt/CardDbAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/CardDb/CardDbHTAdd/CardDbHTAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="CardDbHTAddRq" namespace="http://xmlns.banesco.com/eopt/CardDbHTAdd_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE APR 10 14:44:15 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CardDbHTAddRq>
         <tns:Agency>
            <xsl:if test="/ns0:CardDbAddRq/ns0:Agency/eoBank:AgencyIdent/text()">
               <eoBank:AgencyIdent>
                  <xsl:value-of select="/ns0:CardDbAddRq/ns0:Agency/eoBank:AgencyIdent"/>
               </eoBank:AgencyIdent>
            </xsl:if>
         </tns:Agency>
         <tns:CardAcctRel>
            <eoCardAcctRel:Card>
               <eoCard:SaleOfficer>
                  <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:SaleOfficer"/>
               </eoCard:SaleOfficer>
               <eoCard:PlasticInfo>
                  <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:BIN/text()">
                     <eoCard:BIN>
                        <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:BIN"/>
                     </eoCard:BIN>
                  </xsl:if>
                  <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:CardEmbossName/text()">
                     <eoCard:CardEmbossName>
                        <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:CardEmbossName"/>
                     </eoCard:CardEmbossName>
                  </xsl:if>
                  <eoCard:CardPromo>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:CardPromo/ns5:Cod/text()">
                        <ns5:Cod>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:CardPromo/ns5:Cod"/>
                        </ns5:Cod>
                     </xsl:if>
                  </eoCard:CardPromo>
                  <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:Customized/text()">
                     <eoCard:Customized>
                        <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:Customized"/>
                     </eoCard:Customized>
                  </xsl:if>
                  <eoCard:FraudInsurance>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:FraudInsurance/ns5:Cod/text()">
                        <ns5:Cod>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:FraudInsurance/ns5:Cod"/>
                        </ns5:Cod>
                     </xsl:if>
                  </eoCard:FraudInsurance>
                  <eoCard:Issuer>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:Issuer/ns5:Cod/text()">
                        <ns5:Cod>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:Issuer/ns5:Cod"/>
                        </ns5:Cod>
                     </xsl:if>
                  </eoCard:Issuer>
                  <eoCard:PayRoll>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:PayRoll/eoCard:Detail/text()">
                        <eoCard:Detail>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:PayRoll/eoCard:Detail"/>
                        </eoCard:Detail>
                     </xsl:if>
                     <eoCard:OrgName>
                        <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:PayRoll/eoCard:OrgName/eoPar:FullName/text()">
                           <eoPar:FullName>
                              <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:PayRoll/eoCard:OrgName/eoPar:FullName"/>
                           </eoPar:FullName>
                        </xsl:if>
                     </eoCard:OrgName>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:PayRoll/eoCard:PayRollRel/text()">
                        <eoCard:PayRollRel>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:PayRoll/eoCard:PayRollRel"/>
                        </eoCard:PayRollRel>
                     </xsl:if>
                  </eoCard:PayRoll>
                  <eoCard:ShippingInfo>
                     <eoCard:Agency>
                        <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:ShippingInfo/eoCard:Agency/eoBank:AgencyIdent/text()">
                           <eoBank:AgencyIdent>
                              <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:ShippingInfo/eoCard:Agency/eoBank:AgencyIdent"/>
                           </eoBank:AgencyIdent>
                        </xsl:if>
                     </eoCard:Agency>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:ShippingInfo/eoCard:CardCourier/text()">
                        <eoCard:CardCourier>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:ShippingInfo/eoCard:CardCourier"/>
                        </eoCard:CardCourier>
                     </xsl:if>
                     <xsl:if test="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:ShippingInfo/eoCard:PINCourier/text()">
                        <eoCard:PINCourier>
                           <xsl:value-of select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Card/eoCard:PlasticInfo/eoCard:ShippingInfo/eoCard:PINCourier"/>
                        </eoCard:PINCourier>
                     </xsl:if>
                  </eoCard:ShippingInfo>
               </eoCard:PlasticInfo>
            </eoCardAcctRel:Card>
            <xsl:for-each select="/ns0:CardDbAddRq/ns0:CardAcctRel/eoCardAcctRel:Acct">
               <eoCardAcctRel:Acct>
                  <ns3:AcctSubtype>
                     <xsl:if test="ns3:AcctSubtype/ns5:Cod/text()">
                        <ns5:Cod>
                           <xsl:value-of select="ns3:AcctSubtype/ns5:Cod"/>
                        </ns5:Cod>
                     </xsl:if>
                  </ns3:AcctSubtype>
                  <xsl:if test="ns3:IsPrincipal/text()">
                     <ns3:IsPrincipal>
                        <xsl:value-of select="ns3:IsPrincipal"/>
                     </ns3:IsPrincipal>
                  </xsl:if>
                  <ns3:AcctKey>
                     <xsl:if test="ns3:AcctKey/ns3:AcctId/text()">
                        <ns3:AcctId>
                           <xsl:value-of select="ns3:AcctKey/ns3:AcctId"/>
                        </ns3:AcctId>
                     </xsl:if>
                  </ns3:AcctKey>
               </eoCardAcctRel:Acct>
            </xsl:for-each>
         </tns:CardAcctRel>
         <tns:PartyKey>
            <xsl:if test="/ns0:CardDbAddRq/ns0:PartyKey/eoPar:PartyId/text()">
               <eoPar:PartyId>
                  <xsl:value-of select="/ns0:CardDbAddRq/ns0:PartyKey/eoPar:PartyId"/>
               </eoPar:PartyId>
            </xsl:if>
         </tns:PartyKey>
         <tns:PartyName>
            <xsl:if test="/ns0:CardDbAddRq/ns0:PartyName/eoPar:FullName/text()">
               <eoPar:FullName>
                  <xsl:value-of select="/ns0:CardDbAddRq/ns0:PartyName/eoPar:FullName"/>
               </eoPar:FullName>
            </xsl:if>
         </tns:PartyName>
         <tns:Flag>
            <ns5:Value/>
         </tns:Flag>
      </tns:CardDbHTAddRq>
   </xsl:template>
</xsl:stylesheet>
