<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreateDiffBUS/DifferentiatorService/DifferentiatorRMS" name="DifferentiatorRMS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DifferentiatorRMS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreateDiffBUS/DifferentiatorService/DifferentiatorRMS"/>
    <wsdl:binding name="DifferentiatorRMS_ptt-binding" type="dif:DifferentiatorRMS_ptt" xmlns:dif="http://xmlns.oracle.com/pcbpel/adapter/db/CreateDiffBUS/DifferentiatorService/DifferentiatorRMS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DifferentiatorRMSSelect">
            <soap:operation soapAction="DifferentiatorRMSSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>