<wsdl:definitions name="DifferentiatorRMS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreateDiffBUS/DifferentiatorService/DifferentiatorRMS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreateDiffBUS/DifferentiatorService/DifferentiatorRMS" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DifferentiatorRMS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="DifferentiatorRMS_plt">
    <plt:role name="DifferentiatorRMS_role">
      <plt:portType name="tns:DifferentiatorRMS_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DifferentiatorRMS" schemaLocation="DifferentiatorRMS_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="DifferentiatorRMSSelect_inputParameters">
        <wsdl:part name="DifferentiatorRMSSelect_inputParameters" element="top:DifferentiatorRMSSelect_dateInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxSoaDiffVwCollection_msg">
        <wsdl:part name="XxSoaDiffVwCollection" element="top:XxSoaDiffVwCollection"/>
    </wsdl:message>
    <wsdl:portType name="DifferentiatorRMS_ptt">
        <wsdl:operation name="DifferentiatorRMSSelect">
            <wsdl:input message="tns:DifferentiatorRMSSelect_inputParameters"/>
            <wsdl:output message="tns:XxSoaDiffVwCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>