<wsdl:definitions name="ConsultarAdquisicion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAdquisicion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/CANALES/ConsultarAdquisicion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAdquisicion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarAdquisicion_plt">
    <plt:role name="ConsultarAdquisicion_role">
      <plt:portType name="tns:ConsultarAdquisicion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarAdquisicion" schemaLocation="../XSD/ConsultarAdquisicion.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarAdquisicionInput_msg">
        <wsdl:part name="ConsultarAdquisicionInput_msg" element="db:ConsultarAdquisicionInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarAdquisicionOutputCollection_msg">
        <wsdl:part name="ConsultarAdquisicionOutputCollection" element="db:ConsultarAdquisicionOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarAdquisicion_ptt">
        <wsdl:operation name="ConsultarAdquisicion">
            <wsdl:input message="tns:ConsultarAdquisicionInput_msg"/>
            <wsdl:output message="tns:ConsultarAdquisicionOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>