<?xml version="1.0" encoding="UTF-8" ?>
<wsdl:definitions targetNamespace="http://www.bcie.org/IniciarAprobacionLotusService"
             xmlns="http://schemas.xmlsoap.org/wsdl/" 
             xmlns:tns="http://www.bcie.org/IniciarAprobacionLotusService"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:iniAprMO="http://www.bcie.org/IniciarAprobacionLotusMO">
  <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.bcie.org/IniciarAprobacionLotusMO"
                        schemaLocation="../Schema/IniciarAprobacionLOTUSMO.xsd"/>
        </xsd:schema>
    </wsdl:types>
  <wsdl:message name="IniciarAprobacionLotusRequestMessage">
    <wsdl:part name="request" element="iniAprMO:IniciarAprobacionLoutsRequest"/>
  </wsdl:message>
  <wsdl:message name="IniciarAprobacionLotusResponseMessage">
    <wsdl:part name="response" element="iniAprMO:IniciarAprobacionLotusResponse"/>
  </wsdl:message>
  <wsdl:portType name="IniciarAprobacionPT">
    <wsdl:operation name="iniciarAprobacion">
      <wsdl:input message="tns:IniciarAprobacionLotusRequestMessage"/>
      <wsdl:output message="tns:IniciarAprobacionLotusResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="IniciarAprobacion12Bnd" type="tns:IniciarAprobacionPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="iniciarAprobacion">
      <soap12:operation style="document"
                        soapAction="http://www.bcie.org/IniciarAprobacionLotusService/iniciarAprobacion"/>
      <wsdl:input>
        <soap12:body use="literal" parts="request"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="response"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>