<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:EliminarLineaCreditoByIdContrato" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:EliminarLineaCreditoByIdContrato" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:linCrBO="http://www.bcie.org/LineaCreditoMO">
  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.bcie.org/LineaCreditoMO"
                  schemaLocation="../../Schema/LineaCreditoMO.xsd"/>
    </xsd:schema>
  </types>
  <message name="EliminarLineaCreditoByIdContratoRequestMessage">
    <part name="EliminarLineaContratoByIdContratoRequest" element="linCrBO:EliminarLineaCreditoByIdContratoRequest"/>
  </message>
  <message name="EliminarLineaCreditoByIdContratoResponseMessage">
    <part name="EliminarLineaCreditoByIdContratoResponse" element="linCrBO:EliminarLineaCreditoByIdContratoResponse"/>
  </message>
  <portType name="EliminarLineaCreditoByIdContratoPT">
    <operation name="eliminarLineaCreditoByIdContratoResponse">
      <input message="tns:EliminarLineaCreditoByIdContratoRequestMessage"/>
      <output message="tns:EliminarLineaCreditoByIdContratoResponseMessage"/>
    </operation>
  </portType>
  <binding name="EliminarLineaCreditoByIdContratoPTSOAP12Binding" type="tns:EliminarLineaCreditoByIdContratoPT">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="eliminarLineaCreditoByIdContratoResponse">
      <soap12:operation style="document"
                        soapAction="urn:EliminarLineaCreditoByIdContrato/eliminarLineaCreditoByIdContratoResponse"/>
      <input>
        <soap12:body use="literal" parts="EliminarLineaContratoByIdContratoRequest"/>
      </input>
      <output>
        <soap12:body use="literal" parts="EliminarLineaCreditoByIdContratoResponse"/>
      </output>
    </operation>
  </binding>
</definitions>