<wsdl:definitions name="ConsultarOperacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BCIE/ADAPTADORES/ConsultarOperacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarOperacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarOperacion_plt">
    <plt:role name="ConsultarOperacion_role">
      <plt:portType name="tns:ConsultarOperacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultarOperacion" schemaLocation="../XSD/ConsultarOperacion_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarOperacionSelect_inputParameters">
        <wsdl:part name="ConsultarOperacionSelect_inputParameters" element="top:ConsultarOperacionSelect_idOperacionInputParameters"/>
    </wsdl:message>
    <wsdl:message name="OperacionCollection_msg">
        <wsdl:part name="OperacionCollection" element="top:OperacionCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarOperacion_ptt">
        <wsdl:operation name="ConsultarOperacionSelect">
            <wsdl:input message="tns:ConsultarOperacionSelect_inputParameters"/>
            <wsdl:output message="tns:OperacionCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>