<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="RPMSavePriceChange" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeProcessBackup/RequestPriceChange/RPMSavePriceChange" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeProcessBackup/RequestPriceChange/RPMSavePriceChange" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RPMSavePriceChange" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="RPMSavePriceChange_plt">
      <plt:role name="RPMSavePriceChange_role">
         <plt:portType name="tns:RPMSavePriceChange_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/RPMSavePriceChange" schemaLocation="../Schemas/RPMSavePriceChange_sp.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="args_in_msg">
      <wsdl:part name="InputParameters" element="db:InputParameters"/>
   </wsdl:message>
   <wsdl:portType name="RPMSavePriceChange_ptt">
      <wsdl:operation name="RPMSavePriceChange">
         <wsdl:input message="tns:args_in_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
