<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SaveMDMPriceChangeEventDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeProcessBackup/RequestPriceChange/SaveMDMPriceChangeEventDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PriceChangeProcessBackup/RequestPriceChange/SaveMDMPriceChangeEventDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SaveMDMPriceChangeEventDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="SaveMDMPriceChangeEventDB_plt">
      <plt:role name="SaveMDMPriceChangeEventDB_role">
         <plt:portType name="tns:SaveMDMPriceChangeEventDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SaveMDMPriceChangeEventDB" schemaLocation="../Schemas/SaveMDMPriceChangeEventDB_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="PrcEventsCollection_msg">
      <wsdl:part name="PrcEventsCollection" element="top:PrcEventsCollection"/>
   </wsdl:message>
   <wsdl:portType name="SaveMDMPriceChangeEventDB_ptt">
      <wsdl:operation name="insert">
         <wsdl:input message="tns:PrcEventsCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
