<wsdl:definitions name="ConsultarTcaTermino" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaTermino" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CreacionJCA/Project9/ConsultarTcaTermino" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTcaTermino" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ConsultarTcaTermino_plt">
    <plt:role name="ConsultarTcaTermino_role">
      <plt:portType name="tns:ConsultarTcaTermino_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTcaTermino" schemaLocation="../XSD/ConsultarTcaTermino.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultarTcaTerminoInput_msg">
        <wsdl:part name="ConsultarTcaTerminoInput_msg" element="db:ConsultarTcaTerminoInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultarTcaTerminoOutputCollection_msg">
        <wsdl:part name="ConsultarTcaTerminoOutputCollection" element="db:ConsultarTcaTerminoOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultarTcaTermino_ptt">
        <wsdl:operation name="ConsultarTcaTermino">
            <wsdl:input message="tns:ConsultarTcaTerminoInput_msg"/>
            <wsdl:output message="tns:ConsultarTcaTerminoOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>