<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://www.bcie.org/CrearActualizarNoObjecionSAD"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://www.bcie.org/CrearActualizarNoObjecionSAD"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CrearActualizarNoObjecion_PS">
        <plnk:role name="CrearActualizarNoObjecionPT" portType="tns:CrearActualizarNoObjecionPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.bcie.org/CrearActualizarNoObjecionSAD" location="oramds:/apps/Resources/ComponentesComunes/DominioOperacion/Adquisicion/V1/Wsdl/ADAPTER/CrearActualizarNoObjecionSAD.wsdl"/>
</wsdl:definitions>
