<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.banesco.com/eopt/ChkOrdAdd_V1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:ns0="http://xmlns.banesco.com/appopt/WFChkAppSvc/ChkOrdAdd_V1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction"
                xmlns:appoptcommon="http://xmlns.banesco.com/appopt/AOptCommon_V1.0"
                xmlns:ns6="http://xmlns.banesco.com/eo/Product_V1.0" xmlns:ns7="http://xmlns.banesco.com/eo/Acct_V1.0"
                xmlns:ns8="http://xmlns.banesco.com/eo/Party_V1.0"
                xmlns:eoStatus="http://xmlns.banesco.com/eo/Status_V1.0"
                xmlns:eoChk="http://xmlns.banesco.com/eo/Chk_V1.0" xmlns:ns3="http://xmlns.banesco.com/eo/Banking_V1.0"
                xmlns:ns5="http://xmlns.banesco.com/eo/Fee_V1.0" xmlns:ns1="http://xmlns.banesco.com/eo/Card_V1.0"
                xmlns:ns2="http://xmlns.banesco.com/eo/Payee_V1.0" xmlns:ns4="http://xmlns.banesco.com/eo/Common_V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/AppOpt/WFChk/ChkOrdAdd/ChkOrdAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="ChkOrdAddRq" namespace="http://xmlns.banesco.com/appopt/WFChkAppSvc/ChkOrdAdd_V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Commons/xsd/EOpt/Check/ChkOrdAdd/ChkOrdAdd_V1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="ChkOrdAddRq" namespace="http://xmlns.banesco.com/eopt/ChkOrdAdd_V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [WED MAY 16 10:08:42 COT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ChkOrdAddRq>
         <tns:Chk>
            <eoChk:ChkData>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:ChkType/text()">
                  <eoChk:ChkType>
                     <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:ChkType"/>
                  </eoChk:ChkType>
               </xsl:if>
               <eoChk:CurAmt>
                  <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CurAmt/appoptcommon:Amt/text()">
                     <ns4:Amt>
                        <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CurAmt/appoptcommon:Amt"/>
                     </ns4:Amt>
                  </xsl:if>
                  <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CurAmt/appoptcommon:CurCode/text()">
                     <ns4:CurCode>
                        <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CurAmt/appoptcommon:CurCode"/>
                     </ns4:CurCode>
                  </xsl:if>
               </eoChk:CurAmt>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData">
                  <eoChk:CreditorData>
                     <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:CreditorAcct">
                        <eoChk:CreditorAcct>
                           <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:CreditorAcct/ns0:AcctId/text()">
                              <ns7:AcctId>
                                 <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:CreditorAcct/ns0:AcctId"/>
                              </ns7:AcctId>
                           </xsl:if>
                        </eoChk:CreditorAcct>
                     </xsl:if>
                     <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee">
                        <eoChk:FSPayee>
                           <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:OrgData">
                              <ns2:OrgData>
                                 <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:OrgData/ns0:OrgName">
                                    <ns8:OrgName>
                                       <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:OrgData/ns0:OrgName/ns0:FullName/text()">
                                          <ns8:FullName>
                                             <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:OrgData/ns0:OrgName/ns0:FullName"/>
                                          </ns8:FullName>
                                       </xsl:if>
                                    </ns8:OrgName>
                                 </xsl:if>
                              </ns2:OrgData>
                           </xsl:if>
                           <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:PersonData">
                              <ns2:PersonData>
                                 <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:PersonData/ns0:PersonName">
                                    <ns8:PersonName>
                                       <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:PersonData/ns0:PersonName/ns0:FullName/text()">
                                          <ns8:FullName>
                                             <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:CreditorData/ns0:FSPayee/ns0:PersonData/ns0:PersonName/ns0:FullName"/>
                                          </ns8:FullName>
                                       </xsl:if>
                                    </ns8:PersonName>
                                 </xsl:if>
                              </ns2:PersonData>
                           </xsl:if>
                        </eoChk:FSPayee>
                     </xsl:if>
                  </eoChk:CreditorData>
               </xsl:if>
               <eoChk:DebtorData>
                  <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:DebtorData/ns0:DebtorAcct">
                     <eoChk:DebtorAcct>
                        <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:DebtorData/ns0:DebtorAcct/ns0:AcctId/text()">
                           <ns7:AcctId>
                              <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:DebtorData/ns0:DebtorAcct/ns0:AcctId"/>
                           </ns7:AcctId>
                        </xsl:if>
                     </eoChk:DebtorAcct>
                  </xsl:if>
               </eoChk:DebtorData>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:Details">
                  <eoChk:Details>
                     <xsl:for-each select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkData/ns0:Details/ns0:Memo">
                        <xsl:if test="./text()">
                           <eoChk:Memo>
                              <xsl:value-of select="."/>
                           </eoChk:Memo>
                        </xsl:if>
                     </xsl:for-each>
                  </eoChk:Details>
               </xsl:if>
            </eoChk:ChkData>
            <eoChk:ChkIssueKey>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:ChkNum">
                  <eoChk:ChkNum>
                     <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:ChkNum"/>
                  </eoChk:ChkNum>
               </xsl:if>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:DraftNum">
                  <eoChk:DraftNum>
                     <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:DraftNum"/>
                  </eoChk:DraftNum>
               </xsl:if>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:SerieId">
                  <eoChk:SerieId>
                     <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:SerieId"/>
                  </eoChk:SerieId>
               </xsl:if>
               <xsl:if test="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:StockId">
                  <eoChk:StockId>
                     <xsl:value-of select="/ns0:ChkOrdAddRq/ns0:Chk/ns0:ChkIssueKey/ns0:StockId"/>
                  </eoChk:StockId>
               </xsl:if>
            </eoChk:ChkIssueKey>
         </tns:Chk>
      </tns:ChkOrdAddRq>
   </xsl:template>
</xsl:stylesheet>
