<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/bpmn/bpmnProcess/ComisionesProcess"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.bcie.org/ObjetoProceso/Comisiones/Payload/V1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:tns6="http://xmlns.bcie.org/ObjetoProceso/Comun/Header/V1"
                xmlns:param="http://xmlns.bcie.org/ObjetoProceso/Comun/Parameter/V1"
                xmlns:ns1="http://xmlns.bcie.org/ObjetoProceso/Comun/Operacion/V1"
                xmlns:ns2="http://xmlns.bcie.org/ObjetoProceso/Comun/Tarea/V1"
                xmlns:notificacion="http://xmlns.bcie.org/ObjetoProceso/Comun/Notificacion/V1"
                xmlns:eqTr="http://www.bcie.org/EqipoTrabajo/V1" xmlns:ns3="http://www.bcie.org/CatalogoBO"
                xmlns:ns4="http://xmlns.bcie.org/ObjetoProceso/Comun/Proceso/V1"
                xmlns:ns5="http://xmlns.bcie.org/ObjetoProceso/Comun/Cliente/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/Resources/BPM/Schema/PA02/ComisionesProcess.xsd"/>
        <oracle-xsl-mapper:rootElement name="InicioComisiones"
                                       namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/ComisionesProcess"/>
        <oracle-xsl-mapper:param name="inicioComisiones"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/Comisiones/V1/ComisionPayload.xsd"/>
        <oracle-xsl-mapper:rootElement name="ComisionPayload"
                                       namespace="http://xmlns.bcie.org/ObjetoProceso/Comisiones/Payload/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.1(XSLT Build 150816.0404) AT [SUN JAN 10 18:25:37 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ComisionPayload>
      <tns:Header>
        <tns6:Operacion>
          <ns1:CodigoOperacion>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:CodigoOperacion"/>
          </ns1:CodigoOperacion>
          <ns1:NombreOperacion>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:NombreOperacion"/>
          </ns1:NombreOperacion>
          <ns1:ResponsableOperacion>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:ResponsableOperacion"/>
          </ns1:ResponsableOperacion>
          <ns1:CodigoCliente>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:CodigoCliente"/>
          </ns1:CodigoCliente>
          <ns1:NombreCliente>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:NombreCliente"/>
          </ns1:NombreCliente>
          <ns1:CodigoProducto>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:CodigoProducto"/>
          </ns1:CodigoProducto>
          <ns1:NombreProducto>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:NombreProducto"/>
          </ns1:NombreProducto>
          <ns1:MontoSolicitado>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:MontoSolicitado"/>
          </ns1:MontoSolicitado>
          <ns1:Pais>
            <xsl:value-of select="/ns0:InicioComisiones/ns0:Header/tns6:Operacion/ns1:Pais"/>
          </ns1:Pais>
        </tns6:Operacion>
        <xsl:for-each select="/ns0:InicioComisiones/ns0:Header/param:ParameterType">
          <param:ParameterType>
            <param:parameterName>
              <xsl:value-of select="param:parameterName"/>
            </param:parameterName>
            <param:parameterValue>
              <xsl:value-of select="param:parameterValue"/>
            </param:parameterValue>
          </param:ParameterType>
        </xsl:for-each>
      </tns:Header>
      <tns:Configuration>
        <xsl:for-each select="/ns0:InicioComisiones/ns0:Header/param:ParameterType">
          <xsl:if test='param:parameterName = "IDCOMISION"'>
            <tns:idComision>
              <xsl:value-of select="param:parameterValue"/>
            </tns:idComision>
          </xsl:if>
        </xsl:for-each>
      </tns:Configuration>
    </tns:ComisionPayload>
  </xsl:template>
</xsl:stylesheet>
